### ISSUE TITLE
Customer "None" when Guest

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce-gateway-stripe#1004]
**Describe the bug**

When checking out as a Guest, on Stripe's Dashboard it says Customer "None"

**To Reproduce**
1. Go to Checkout
2. Checkout as a Guest user filling in the  billing details
3. See error on Stripe's dashboard

**Expected behavior**
Not sure, is this a bug?

**Screenshots**

![](http://d.wedj.at/ReeYaB+)
**Image Link**: http://d.wedj.at/ReeYaB+

**Environment (please complete the following information):**
 - Latest
 - Latest
 - Latest
 - Chrome Latest

Ref 2366304-zen

**Comment by SiR-DanieL** [comment]
Any update on this pls?

**Comment by v18** [comment]
When checking out as a guest, the customer email is now seen in the Stripe dashboard. I'm closing this issue for now, but if there are any problems with seeing the customer or the customer details for guest checkouts, feel free to re-open.
