### ISSUE TITLE
Need action hooks on gateway process_payment before order emails processed

### ISSUE THREAD

**Issue by clariontools** [woocommerce/woocommerce-gateway-stripe#101]
#### What I expected

Expected to be able to save additional postmeta data from the stripe payment response in "class-wc-gateway-stripe.php" in order to display that on any processed emails.  This includes any email that is generated after the stripe gateway $response object is returned, including the error response. 
#### What happened instead

When I used the proved action hook ( "wc_gateway_stripe_process_payment" ) I could save some meta data but that hook is invoked *after* the payment_complete() and *after* emails are created.  There is no other hook available to actually use data from the stripe gateway response object and have it appear on the order emails.
#### Steps to reproduce the issue

Add some additional postmeta data from the process_payment $response in the action hook "wc_gateway_stripe_process_payment", things like brand, last4, if bitcoin, if error then save reason, etc..., then add this additional information to order complete emails, failed order emails.  Your saved postmeta data will *NOT* appear on these emails because the action  "wc_gateway_stripe_process_payment" occurs *AFTER* the payment_complete is called and in the case of a failed order, *AFTER* "send_failed_order_email()" is called.

My temporary fix/hack is to comment out your action at line 595 "wc_gateway_stripe_process_payment" action and copy as is ( do_action( 'wc_gateway_stripe_process_payment', $response, $order ); ) it to three new locations in current class-wc-gateway-stripe.php:

1. Before current line 587 $this->process_response( $response, $order );
2. Before current line 589 $order->payment_complete();
3. Before current line 607 in catch for error if ( $order->has_status( array( 'pending', 'failed' ) ) ) {$this->send_failed_order_email( $order_id );

When the action is called I can detect if it was an error response or on valid responses I can update postmeta data from the $response, then in turn I can use that postmeta data on any of the order emails that get generated.

* Moving the current action does not hurt because it can never be run more than once per payment response.  Of course it maybe better to have a new action, maybe something like "do_action( 'wc_gateway_stripe_process_payment_before_order_email', $response, $order ); )  or you could have a specific action for each case, but doesn't really add much value.

* Main point of this issue is that there is no way to get information from the payment response onto the order emails.

Thank you for listening!

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by clariontools** [comment]
FYI, from current line 586 in  class-wc-gateway-stripe.php:

```php			// Process valid response.
				do_action( 'wc_gateway_stripe_process_payment', $response, $order );
				$this->process_response( $response, $order );
			} else {
				do_action( 'wc_gateway_stripe_process_payment', $response, $order );
				$order->payment_complete();
			}

			// Remove cart.
			WC()->cart->empty_cart();

			//do_action( 'wc_gateway_stripe_process_payment', $response, $order );

			// Return thank you page redirect.
			return array(
				'result'   => 'success',
				'redirect' => $this->get_return_url( $order )
			);

		} catch ( Exception $e ) {
			wc_add_notice( $e->getMessage(), 'error' );
			WC_Stripe::log( sprintf( __( 'Error: %s', 'woocommerce-gateway-stripe' ), $e->getMessage() ) );

			do_action( 'wc_gateway_stripe_process_payment', $response, $order );

			if ( $order->has_status( array( 'pending', 'failed' ) ) ) {
				$this->send_failed_order_email( $order_id );
			}

			do_action( 'wc_gateway_stripe_process_payment_error', $e, $order );
```

**Comment by roykho** [comment]
Looking at this again I believe the one `do_action( 'wc_gateway_stripe_process_payment', $response, $order );` right before the redirect should be enough because it will always reach that hook regardless of the response. So if you hook into that, you can check the response to determine what you want to do. Its been awhile since seeing this so please remind/refresh my memory if what I stated cannot be done.

**Comment by clariontools** [comment]
Actually having one do_action before the redirect is how it works now and in my snippet above you can see I commented that out and moved the same do_action into three distinct locations to allow for modifications to the emails generated based on the response results:

1.Before current line 587 $this->process_response( $response, $order );
2.Before current line 589 $order->payment_complete();
3.Before current line 607 in catch for error if ( $order->has_status( array( 'pending', 'failed' ) ) ) {$this->send_failed_order_email( $order_id );

If you read through the details in my original it describes the use case a little better.  Basically this allows the developer a chance to make customizations to the generated email output, in my case I add licensing information and formatting adjustments to the email that I could not otherwise affect given the location of the current do_action which is after all those emails have been generated.

The other option is to create a new do_action and keep the existing so it would not affect existing implementations, although that was a fairly recent addition to begin with.  Let me know if you need additional information, I would have to go back and review all the details.  Thank you.

**Comment by roykho** [comment]
Right I read your comment however what I am stating is the "one" line of hook will be fired regardless of the "if/else" before it. Can you not hook in then and perform your logic?

Perhaps if you could show me the full code that you currently have now with your edits, I can better see how you're achieving it?

**Comment by clariontools** [comment]
Where the hook is now it is *after* the email is generated, and completely skipped if there is an error.  The goal is to make modifications to the generated emails before sending or notify the user of the problem or take some alternate action.

   $this->process_response( $response, $order );
or
   $order->payment_complete();

The current action happens *after* these calls and if you look at the code in those calls you would not be able to affect change to the email output otherwise.  Also handling on an error is just nice to have and the do_action you have passes the response so it is easy to filter out and decide what action you want to take.

**Comment by roykho** [comment]
Ah I think you're referring to the "normal" emails and not the "failed" email that is trigger later. Is that correct?

**Comment by roykho** [comment]
I think this should work for you? https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.0.0/includes/class-wc-gateway-stripe.php#L729-L753

**Comment by clariontools** [comment]
Perfect!  Thanks Roy!

**Comment by n9yty** [comment]
@roykho @clariontools The above link is no longer valid, but I am looking for a way to also capture metadata and store it on the order to be able to include it in the "new order" emails that go out. How was this resolved?
