### ISSUE TITLE
WC Subs: allow renewal of subscription using customer ID only, not source

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1010]
Tickets: 

* 2381932-zen

Steps to reproduce:

1. Make sure that you already have a WC customer with a stripe customer ID (cus_123)
2. Create a new manual subscription using the steps in this video (also listed below as sub-steps of step 2): https://docs.woocommerce.com/document/subscriptions/add-or-modify-a-subscription/
2a. Subscriptions > Create new subscription
2b. Select a customer
2c. Select the Stripe payment method
2d. Enter the customer ID in the customer ID field
2e. Add subscription product
2f. Save
2g. Create parent order
2h. Go to parent order and change status to processing
2i. Renew subscription
3. See that renewing the subscription with just the customer ID entered will work with plugin version 4.2.3 and not with 4.2.4

h/t @jrick1229 p2-pb06B4-a7

**Comment by jobthomas** [comment]
Another case: 2381932-zen

**Comment by jessLundie** [comment]
Another case: hc-15612114

**Comment by jobthomas** [comment]
FYI @jessLundie I've updated the HC format so it's clickable (if you're not able to click it, DM me and I'll show you the magic)

**Comment by thenbrent** [comment]
From @NickGreen via Slack:

> **Idea:** what if we populated the src field with the default card token at the time of making that charge (if it's blank)?

> That way, over time, the blank src fields would approach zero.

I think that is a really good approach. It means we're fulfill Stripe's (impending) requirement to pass a source, but also maintaining backward compatibility with existing subscriptions setup without a source, and doing that by taking advantage of the customer / subscriber facing UI to set a default payment method in WooCommerce.

If customers find a recurring charge on the a payment method they don't want it on, they can also change this with existing UIs on the WooCommerce store by either changing their default payment method or changing the payment method on the subscription.

This should be documented for store owners in the Stripe extension docs.

**Comment by jrick1229** [comment]
Just adding this here for anyone looking: [zen-2367859](https://woothemes.zendesk.com/agent/tickets/2367859)

This customer manually added the `src_` ID into their subscriptions that were failing, then successfully processed a renewal. This can be hard for us to identify, since they may have already done this by the time we look.

Since we're looking for an empty source when troubleshooting, we may also want to ask customers if they've made any changes to successfully process renewals that were originally failing.
