### ISSUE TITLE
Guest checkout users result in CSRF verification failures after 3D Secure

### ISSUE THREAD

**Issue by lgladdy** [woocommerce/woocommerce-gateway-stripe#1011]
Yesterday, we tried to enable 3D Secure where available in radar. This resulted in 98% of our orders going through PaymentIntents overnight, of which the majority failed.

If the user opts not to create an account during check-out (and so are a guest user), post 3DS auth, they are redirected to /shop so they receive no confirmation of a successful order, and a CSRF verification failed error is generated in the debug log at

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/cd3441773298b0f8ba74343093fa563be4dc36eb/includes/class-wc-stripe-intent-controller.php#L58

But most importantly, payment was still successfully taken, and the order stays in a pending state requiring manual processing. No email is sent to the customer. If they try to checkout again, they get a random error which is logged in stripe as trying to pay for an order which has already been paid for.

> This PaymentIntent's source could not be updated because it has a status of succeeded. You may only update the source of a PaymentIntent with one of the following statuses: requires_payment_method, requires_confirmation, requires_action.

Looking at access logs, a nonce is present in the GET request (GET `/?wc-ajax=wc_stripe_verify_intent&order=<order_number>&nonce=<nonce>&redirect_to=<checkout_complete_url>`) which presumably triggers this error. (Stripe's Webhook POST to `/?wc-api=wc_stripe` also happens at the same timestamp, but this is after the user has been redirected to /shop so I don't believe that is related)

This is only an issue if the user doesn't create an account, which makes me suspect it's related to #882 and maybe #886.

Running WooCommerce 3.7.0 and Stripe Gateway 4.2.4

**Comment by lgladdy** [comment]
I add a bunch of debugging to see if I could figure out what was going wrong. Logging the created nonce, and then checking what was being verified - but it doesn't really help. The user doesn't change, and the nonce is the same.

> 2019-09-26T13:09:54+00:00 DEBUG 
> ====Stripe Version: 4.2.4====
> ====Start Log====
> Modify successful payment result and made nonce 0d763cfde9 The user is: 0
> ====End Log====
> 
> 2019-09-26T13:10:17+00:00 DEBUG 
> ====Stripe Version: 4.2.4====
> ====Start Log====
> Verifying nonce 0d763cfde9, our user is now: 0
> ====End Log====
> 
> 
> 2019-09-26T13:10:17+00:00 DEBUG 
> ====Stripe Version: 4.2.4====
> ====Start Log====
> PaymentIntent verification exception: CSRF verification failed.
> ====End Log====

**Comment by allendav** [comment]
@DanReyLop - would you take a look? We might need to fix this in 4.3.0

**Comment by lgladdy** [comment]
In case it's helpful, I wanted to debug this a little more to make sure it wasn't a plugin manipulating the nonce_user_logged_out filter by debugging what data was in there. I think it proves that the session is being destroyed before the SCA response happens.

> 2019-09-26T17:59:51+00:00 DEBUG 
> ====Stripe Version: 4.2.4====
> ====Start Log====
> {
>     "msg": "Running woocommerce nonce_user_logged_out",
>     "has_session": true,
>     "_customer_id": "79b7a614b11ad0e6326c4bd83f42676d",
>     "uid": 0
> }
> ====End Log====
> 
> 2019-09-26T17:59:51+00:00 DEBUG 
> ====Stripe Version: 4.2.4====
> ====Start Log====
> Creating pi nonce with UID 79b7a614b11ad0e6326c4bd83f42676d
> ====End Log====
> 
> 2019-09-26T18:00:13+00:00 DEBUG 
> ====Stripe Version: 4.2.4====
> ====Start Log====
> {
>     "msg": "Running woocommerce nonce_user_logged_out",
>     "has_session": false,
>     "_customer_id": "c066cfe7e630f53658574b3cf5724606",
>     "uid": 0
> }
> ====End Log====
> 
> 2019-09-26T18:00:13+00:00 DEBUG 
> ====Stripe Version: 4.2.4====
> ====Start Log====
> Verifying pi nonce with UID 0
> ====End Log====
> 
> 
> 2019-09-26T18:00:13+00:00 DEBUG 
> ====Stripe Version: 4.2.4====
> ====Start Log====
> PaymentIntent verification exception: CSRF verification failed.
> ====End Log====

**Comment by RadoslavGeorgiev** [comment]
@lgladdy thank you for the detailed but report. A few of us tried to reproduce this bug, but failed. For me this means that it is not WooCommerce that destroys the previous session, but probably another plugin/extension.

Could you please open a WooCommerce support ticket? This way we'll know what extensions to keep in mind when checking this. Of course, I would recommend disabling all possible culprits first, but I know this is not always possible to do on a live site. Don't forget to mention my username, so that the ticket will be forwarded to us.

**Comment by lgladdy** [comment]
Hey team,

Following this, I spent more time debugging and trying to figure out what it could be. I hadn't been able to replicate it in test or staging, which made me think maybe it was a production hosting platform issue over at WPEngine.

I wondered if maybe it was a caching thing - where `/?wc-ajax=` calls were being cached, and thus sending the wrong checkout cookie, and that seems to be exactly the problem.

After I had them exclude any request with a wc-ajax parameter, it seems everything is working correctly.

Sorry this turned out not to be a stripe gateway plugin issue!

**Comment by nitras** [comment]
Hello there. I have this issue on an up to date WordPress installment. We have a lot of pending payments from stripe. 
However most if not all are perfectly received by my client, on his stripe account. 
So I started to debug logging. All pending payments seem to have the CSRF verifications. (we run 3d secured payments)
We use fastest cache plugin.
How exactly can I do this? "After I had them exclude any request with a wc-ajax parameter, it seems everything is working correctly."

Thank you for your help —

> Hey team,
> 
> Following this, I spent more time debugging and trying to figure out what it could be. I hadn't been able to replicate it in test or staging, which made me think maybe it was a production hosting platform issue over at WPEngine.
> 
> I wondered if maybe it was a caching thing - where `/?wc-ajax=` calls were being cached, and thus sending the wrong checkout cookie, and that seems to be exactly the problem.
> 
> After I had them exclude any request with a wc-ajax parameter, it seems everything is working correctly.
> 
> Sorry this turned out not to be a stripe gateway plugin issue!

**Comment by Buzut** [comment]
Like @nitras I'm experiencing this issue on an up to date version:
* WP Version: 5.8
* WC Version: 5.5.2
*  WooCommerce Stripe Gateway: 5.3.0

I have the error when I allow users to create an account on the checkout page and hook into `woocommerce_checkout_process`. As it's a conversion killer when a user checks this option and he gets an error message stating his account already exists and he needs to login, I use this hook to automatically link his order to his account.

```php
add_action('woocommerce_checkout_process', function () {
    if (!is_user_logged_in() && $_POST['billing_email']) {
        $user = get_user_by('email', $_POST['billing_email']);
        if ($user) wp_set_current_user($user->ID);
    }
});
```

This way, no error message and the order is linked to the already existing user's account. But for whatever reason, this triggers the CSRF error.
