### ISSUE TITLE
If currency is not EUR, don't show all the EUR sub-gateways

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1018]
My store is set for USD. I see a lot of Stripe sub-gateways. I tried enabling them all for grins and giggles. I was denied.

Let's not show sub-gateways that the current store currency does not support.

Extra credit: Have a filter to disable hiding sub-gateways based on currency. If [WooCommerce Multi Currency](https://woocommerce.com/products/multi-currency/) is active, disable hiding sub-gateways.

<img width="1100" alt="Screen Shot 2019-09-27 at 1 31 55 PM" src="https://user-images.githubusercontent.com/1595739/65800539-9ae43080-e12b-11e9-9855-565641337b41.png">

cc @bmccotter - you ok with this?

**Comment by bmccotter** [comment]
Works for me!

**Comment by thenbrent** [comment]
Closing this one due to lack of recent activity, and because the preferred settings UI will be based on the settings provided as part of the "[new checkout experience](https://woocommerce.com/document/stripe/#new-checkout-experience)" which account for currency requirements better AFAIK.
