### ISSUE TITLE
After activate Enable Payment via Saved Cards deactivate does not remove from My Account

### ISSUE THREAD

**Issue by clariontools** [woocommerce/woocommerce-gateway-stripe#102]
#### What I expected

I expected that I could enable the "Enable Payment via Saved Cards" and later deactivate it with the feature completely removed from the users My Account menu.
#### What happened instead

I checked the "Saved Cards" option Enable Payment via Saved Cards and tested it out, then I deactivated the feature and it still shows up in the user's My Account Section.
#### Steps to reproduce the issue

1. Activate the "Saved Cards" option in the Stripe gateway checkout options.
2. Test out the feature on some users.
3. Deactivate the "Saved Cards" option in the Stripe gateway checkout options.
4. Go back to user's "My Account" and the feature with menu option "Payment Methods" is still there.

* How to turn it off once it is activated?  Database cleanup?

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
That is correct. The option is only for enabling/disabling the function of paying via a saved card. It does not remove the Payment Method section.

**Comment by clariontools** [comment]
I don't recall seeing the "Payment Methods" menu choice in "My Account" until I activated the "Saved Card" feature?  Also I still have the "Add Payment Method" button available, but I suppose that could be a function of my template.  I guess I will just go into the database options to remove that option to make sure the "Payment Methods" menu choice does not appear. 

I also wonder, why the menu choice is there if the feature is not active, what purpose (other than user confusion) does it serve if the option is not active?  I might be missing something about the functionality of the "Payment Methods" link for "add-payment-method" slug?

**Comment by clariontools** [comment]
Ok, I think I see the payment method is actually payment methods, like PayPal, Stripe, Check Payments, and not the stored credit card thing of stripe.  Sorry 'bout that, just happens I only have Stripe payments.

**Comment by clariontools** [comment]
I am still a bit confused, I do not recall even having the "Payment Methods" menu in the "My Account" page until I activated the "Saved Card" feature in the stripe checkout gateway?  Even with the option unchecked I can add saved cards so it just doesn't make sense?  So in my case I can add a card in the Payment Methods and I add that with the stripe modal pop and it saves the card.  This just doesn't make sense, I can add cards to the "Payment Methods" through the stripe interface, but cannot use them at checkout?  Also on the Stripe modal checkout popup, I have a "Remember Me" button, is there any way to get rid of that, I do not even want to offer the option to save credit cards?  Still seems like something is not working properly.

**Comment by clariontools** [comment]
I did activate the "Saved Cards" option, seems very dangerous imo, the saved card is selected by default and when I click "Continue To Payment", the transaction is processed immediately.  I think there should be a step in between here, or call the popup with information prefilled where the button says Pay $###.##.  Otherwise it is too easy to hit the button and away you go.  Not sure if you read this closed issue, or if I need to add another issue for how to turn off the "Remember me" checkbox in the modal popup, and with the issue I just mentioned above about some sort of confirmation step when using a saved credit card?

**Comment by clariontools** [comment]
So I figured out that the "Payment Methods" link is activated when payment gateways support add_payment_method or tokenization.  In my case I started out testing with just check payments before activating the Stripe gateway.  That is why I didn't see the "Payment Methods" link.

To deactivate, I cleared the add-payment-method from the "Checkout" endpoints and the payment-methods from the My Accounts Endpoints.  As long as there are no saved payment methods, there should be no reason to delete the delete-payment-method and set-default-payment-method endpoints because they will not display even if typed in.  Of course you need to save Permalinks to completely remove the selection page.

Looks like for the checkout modal options there is a configuration option on the checkout data-allow-remember-me when set to false will hide the "Remember Me" option.  https://stripe.com/docs/checkout

There are some things that I think could be improved with the saved options.  I don't plan to use all that but removing the Remember Me option would be nice.  If I have time I can write this up as an enhancement issue?   Not sure how things work around here or if there is a better place to make those types of suggestions?

**Comment by roykho** [comment]
Actually "Payment Methods" is from WC core and will show once you have any saved methods whether that be from Stripe or any other gateways so we can't remove that from Stripe level.

**Comment by clariontools** [comment]
I do understand "Payment Methods" is from core.  However, it has not been the case that is shows up with any saved payment methods as you indicate.  With a fresh wp and woocommerce installation, I activate check payments only, and go to my account, there is no "Payment Methods" menu choice.

Once I activate the stripe gateway plugin, then the "Payment Methods" appears.  As I understand "Payment Methods" is only active when the gateway plugin supports add_payment_method or tokenization.  I did figure out how to decactivate by removing the endpoints as described.  Still have some suggestions for the stripe plugin, but it will take time to document those for you.
