### ISSUE TITLE
Allow prepaid card filter hook not working

### ISSUE THREAD

**Issue by justinfauci** [woocommerce/woocommerce-gateway-stripe#1020]
Setting _wc_stripe_allow_prepaid_card_ filter hook to return false doesn't block prepaid cards.

Did some digging into the code and found out that the is_prepaid_card() function isn't working as expected. It returns false even if the card IS prepaid, because the return conditions are:

`$source_object && 'token' === $source_object->object && 'prepaid' === $source_object->card->funding`

This is a problem because $source_object->object now returns 'source' instead of 'token'. Tested with both live and test credentials.

**Comment by RadoslavGeorgiev** [comment]
Thanks for reporting this, @justinfauci! I opened a PR, which fixes it.
