### ISSUE TITLE
Does Stripe work with Pre-Orders "pre-order fee"?

### ISSUE THREAD

**Issue by DanReyLop** [woocommerce/woocommerce-gateway-stripe#1027]
Pre-Orders has a per-product field to set a "Pre-Order fee". So, for example, if the pre-order fee is $1 and the product fee is $20, the customer will be charged $1 on checkout and then $20 when the product is released.

I haven't seen any code in the Stripe compatibility class to actually charge that fee during checkout. So, I suspect that the "pre-order fees" are always silently $0 when using the Stripe gateway. This is probably an old bug, maybe has never even worked, and it won't get any worse by the rest of our `4.3.0` changes.

After discussing it, @RadoslavGeorgiev will investigate and decide if this should go on 4.3.0 or pushed to a later release.

**Comment by RadoslavGeorgiev** [comment]
<img width="333" alt="image" src="https://user-images.githubusercontent.com/5311119/65969443-12d09480-e465-11e9-868f-697f44ca612f.png">

...and the button says "Place Pre-Order Now". I guess it's very simple: It's all charged together upon release :)

**Comment by DanReyLop** [comment]
Okey then :)

It makes very little sense to have a "Pre-Order fee" work that way, but whatever, I guess this means it's working correctly.
