### ISSUE TITLE
Does wc_stripe_send_stripe_receipt still work?

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#1030]
**Describe the bug**

Using the filter `add_filter( 'wc_stripe_send_stripe_receipt', '__return_true' );` does not send receipts/emails to the Customer

**To Reproduce**
1. Add the snippet to functions.php
2. Go through a test order
3. Notice customer doesn't get any Stripe receipts

**Expected behavior**

If the filter works, an email receipt form Stripe.com is sent to the customer

**Additional context**
Via `https://wordpress.org/support/topic/stripe-emails-not-sending/`

I've tested on my Stripe development site and using `add_filter( 'wc_stripe_send_stripe_receipt', '__return_true' );` doesn't work.

I think the only way to get receipts/emails from Stripe.com is to change the setting here now - `https://dashboard.stripe.com/account/emails` ( “Email customers about...” ) 

Can this be confirmed/denied?

**Comment by dougaitken** [comment]
via https://wordpress.org/support/topic/stripe-emails-not-sending

**Comment by ryanr14** [comment]
Had a ticket with this same issue, but I wanted to be sure you'd seen this @dougaitken. It seems receipts aren't automatically sent when in test mode. Just an FYI.

https://stripe.com/docs/receipts#receipts-in-test-mode

**Comment by ryanr14** [comment]
Following up on this after some testing. If the filter is added correctly to a site they must also enable the Successful payment email in their Stripe account settings. 

![https://d.pr/i/p2x0KC](https://d.pr/i/p2x0KC+)
Image link: https://d.pr/i/p2x0KC

Once they do that, everything is peachy. Still works for me!

![https://d.pr/i/deIfjw](https://d.pr/i/deIfjw+)
Image link: https://d.pr/i/deIfjw

**Comment by dougaitken** [comment]
@ryanr14 To confirm - those receipts are only sent once that filter is added? If you remove it but keep the option checked on your Stripe.com account, no receipts are sent?
