### ISSUE TITLE
Add Support for WeChat Pay

### ISSUE THREAD

**Issue by tinyliu** [woocommerce/woocommerce-gateway-stripe#1034]
Wechat pay is popular, when will support it?

**Comment by allendav** [comment]
Hi @tinyliu 

WeChat Pay is currently under Beta https://stripe.com/docs/sources/wechat-pay

We (WooCommerce) don't have a planned release for adding WeChat, but if there is enough interest, we can look into adding it. cc @bmccotter @thenbrent

**Comment by dougaitken** [comment]
Also mentioned in #873 and #351

**Comment by jrick1229** [comment]
22586565-hc

**Comment by yangyucacaa** [comment]
@allendav WeChat Pay is now the most popular payment method in China, which has a huge internet user base, and if you can integrate WeChat Pay, it will bring even more interesting things.

**Comment by martynmjones** [comment]
4297385-zen

**Comment by chestnutbak** [comment]
Please add support for WeChat Pay... as stated by multiple people above, this is the most widely used payment platform in China and the fact that the Stripe integration for WooCommerce doesn't have it is a huge hole in the market that needs to be filled ASAP (also based on my understanding of Stripe and the integrations this shouldn't be too hard to do)

**Comment by ryanr14** [comment]
Adding support here for WeChat

40663673-hc

**Comment by grig-23** [comment]
6191568-zen - merchant asks to participate in beta/get early access when WeChat Pay comes out.

**Comment by nicholasjeberlin** [comment]
6629809-zen

**Comment by sophieLN** [comment]
> [<img alt="@allendav" width="20" height="20" src="https://avatars.githubusercontent.com/u/1595739?s=40&amp;u=d849cb482014e2d52bebbfc5d3af8e3733b3c39e&amp;v=4">](/allendav) [allendav](/allendav) changed the title ~when will support Wechat pay?~ Add Support for WeChat Pay [Oct 8, 2019](#event-2692671980)

The Stripe plugin for WooCommerce  Could please enquire if the plugin support Alipay but not support Wechat pay at this moment?  If it is possible to release it for the support of Wechat pay?  Thanks

**Comment by sophieLN** [comment]
https://woo.com/products/stripe/
![Uploading woostripe for wechat support.PNG…]()

**Comment by dougaitken** [comment]
Related: 

* [Enable WeChat Pay in WooCommerce Stripe Payment Gateway](https://woo.com/feature-request/enable-wechat-pay-in-woocommerce-stripe-payment-gateway/)
* [Provide WeChat and CashApp Pay in Woocommerce Stripe](https://woo.com/feature-request/provide-wechat-and-cashapp-pay-in-woocommerce-stripe/)
* [Support WeChat Pay and Payme](https://woo.com/feature-request/support-wechat-pay-and-payme/)

**Comment by wyter** [comment]
Closing since WeChat Pay was added as from version 8.4.0.
