### ISSUE TITLE
SCA challenge for off-session payments does not work when logged out

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [woocommerce/woocommerce-gateway-stripe#1037]
#986 introduced the functionality, which allows customers to complete payments, which require authentication. This is done through a link, which looks like this:

https://your-host.com/checkout/order-pay/3286/?pay_for_order=true&key=wc_order_0XK6ZfBw5XyNa&subscription_renewal=true&wc-stripe-confirmation=1

When you are already logged in, this works. However, if you are not logged in, you will see a login form. When you use it to log in, you are redirected to a standard checkout page, and the SCA challenge does not not automatically appear.

We have two options here:

1. Try to show the SCA challenge even when the customer is logged out.
2. Forward all necessary GET arguments to the checkout/pay for order page after login.

**Comment by v18** [comment]
@LCmry & @james-allan - how important do you think it is to allow logged-out authentication of payments? Should we aim to release it in the SCA for Subscriptions release asap (4.3) or defer to a later release?

I'm not sure if we know how likely customers are to be logged out. It will cause friction, but I'm unclear about the impact.

cc @DanReyLop and @allendav for an opinion, also.

**Comment by RadoslavGeorgiev** [comment]
To iterate, I see two options:

> Try to show the SCA challenge even when the customer is logged out.

This might be useful in 4.3.1 or later, but for now the second option is ok IMO:

> Forward all necessary GET arguments to the checkout/pay for order page after login.

I'm planing to open a (hopefully) small PR for this today.

**Comment by DanReyLop** [comment]
> Forward all necessary GET arguments to the checkout/pay for order page after login.
> I'm planing to open a (hopefully) small PR for this today.

I have the code ready, I just need to clean it up a bit. It **is** a small PR :)
