### ISSUE TITLE
Old Stripe meta data not being removed? Is that intentional?

### ISSUE THREAD

**Issue by hellosg** [woocommerce/woocommerce-gateway-stripe#1038]
#### What I expected

Old Stripe META data that is no longer required, to be removed in the code that detects it

#### What happened instead

Old Stripe META data is left in the system, not being used,

#### Steps to reproduce the issue

While updating our own bespoke subscriptions plugin to integrate with the latest version of WooCommerce Stripe, we found the following code:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/abstracts/abstract-wc-stripe-payment-gateway.php

Line 705-715 in the method `prepare_order_source`

```php
// Since 4.0.0, we changed card to source so we need to account for that.
if ( empty( $source_id ) ) {
	$source_id = WC_Stripe_Helper::is_wc_lt( '3.0' ) ? get_post_meta( $order_id, '_stripe_card_id', true ) : $order->get_meta( '_stripe_card_id', true );
	// Take this opportunity to update the key name.
	WC_Stripe_Helper::is_wc_lt( '3.0' ) ? update_post_meta( $order_id, '_stripe_source_id', $source_id ) : $order->update_meta_data( '_stripe_source_id', $source_id );
	if ( is_callable( array( $order, 'save' ) ) ) {
		$order->save();
	}
}
```

It's in other places too in this file and in the subscriptions compatibility class (and possibly others).

Is there a reason why old META data - `_stripe_card_id` - isn't removed and is left in the system? Was that an intentional decision? I.E. you are aware of other popular extensions or parts of the code that still require it?

I guess this is aimed initially at @roykho as he authored these lines, but welcome input from anyone else :)

**Comment by allendav** [comment]
I assume the old data was retained to support downgrading (e.g. from a 4.2.x to a 4.1.x) in the event an upgrade did not go well.

Let's use this issue to 1) validate that assumption and 2) come up with an approach for when it is safe to remove some of this older meta data (i.e. what about when upgrading two minor versions after the meta is no longer used or something)

**Comment by thenbrent** [comment]
Closing this due to lack of recently activity, also keeping data to help with debugging the lifecycle of a subscription is always a good idea IMO as well as to support things like downgrading.
