### ISSUE TITLE
SameSite Cookie Warning in Chrome

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce-gateway-stripe#1041]
**Update by @dwainm:** This issue needs to be fixed by Stripe. Keeping it open to keep track of it. 

**Describe the bug**

The following error on all pages in Console for sites which use Stripe request buttons:

> A cookie associated with a cross-site resource at http://stripe.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

![https://cld.wthms.co/fRKN3O](https://cld.wthms.co/fRKN3O+) 
Full Size: https://cld.wthms.co/fRKN3O

Is there any action needed from our end? We're getting a few reports about this behaviour on forums.

**Comment by allendav** [comment]
Thanks for catching this @treibalen - we'll reach out to Stripe asap

cc @bmccotter - looks like a SameSite gotcha for Stripe

**Comment by allendav** [comment]
Stripe is looking into the changes needed. Let's check in again with them in a month. Leaving this as critical priority for now so it doesn't get lost in the high priority bundle.

**Comment by karlemilnikka** [comment]
If both the website and the visiting browser has Google Pay enabled, you also get a critical warning in the console on Chrome 77.

Cross-site redirect from "https://android.com/pay" to "https://pay.google.com/about" not allowed for payment manifests.
<img width="1792" alt="Skärmavbild 2019-10-15 kl  01 06 12" src="https://user-images.githubusercontent.com/20514810/66788596-74bede80-eee8-11e9-8560-da732c0840e4.png">

**Comment by shmdt** [comment]
Hi there! I have chrome's version: 77.0.3865.120
 1. go to the chrome://settings/payments 
2. make sure you have at least one card 
![Screen Shot 2019-10-18 at 4 14 44 PM](https://user-images.githubusercontent.com/16562028/67097928-d40c3f80-f1c3-11e9-8bd9-9c268b7a2650.png)
3. hope this help
<img width="1277" alt="Screen Shot 2019-10-18 at 4 22 57 PM" src="https://user-images.githubusercontent.com/16562028/67097905-c6ef5080-f1c3-11e9-83d3-6c64416bbd61.png">

**Comment by treibalen** [comment]
@allendav I guess this is also something that Stripe can look into? I now see the same errors in Console for both my test site with Stripe and on Stripe's own test page:

![https://cld.wthms.co/hVY8rJ](https://cld.wthms.co/hVY8rJ+) 
Full Size: https://cld.wthms.co/hVY8rJ

Happy to open a separate issue if needed.

**Comment by allendav** [comment]
@treibalen wrote

> Happy to open a separate issue if needed.

Please do. Thank you! We'll ask Stripe about this too.

**Comment by allendav** [comment]
We have a bit of runway to fix this... from https://www.chromium.org/updates/same-site

> February 4, 2020: Chrome 80 Stable released. SameSite-by-default and SameSite=None-requires-Secure become default behavior for all users on Stable.

props @DanReyLop

**Comment by treibalen** [comment]
@allendav Issue #1063 created, thank you :)

**Comment by robindra-js** [comment]
@treibalen 
Is there any update on the above issue as I didn't see any new updates on #1063. As I am still getting the same error msge in console and getting null in response (Desktop Chrome).
Thanks!

**Comment by zinkbulb** [comment]
Same error here! 
![Captura de pantalla 2020-03-14 a las 20 42 34](https://user-images.githubusercontent.com/48834859/76689258-61997180-6634-11ea-8aa3-485f9e52ef6e.png)

Any update to this issue?

**Comment by peatidge** [comment]
I don't suppose there has been any update on this, not using woohoo but problem seems to be with stripe using cookies, is an easy fix. Hopefully they will have it done by the time chrome stops supporting it. 

![image](https://user-images.githubusercontent.com/10409574/77223596-1b9f5900-6bb2-11ea-9f29-69e647452db3.png)

**Comment by michaelphipps** [comment]
Hi there!

I've just been researching this issue.  Stripe has resolved the problem.  If you are still seeing these messages is it is because there are still older stripe cookies that were missing the 'SameSite' attribute.  You can fix the problem by removing stripe cookies from your cache and reloading the page.

Here's a link to my source:  https://github.com/stripe/react-stripe-elements/issues/445#issuecomment-634166203

**Comment by vbelolapotkov** [comment]
Checked this today and confirm no more console warnings neither in Chrome nor in Safari. Cookies have [SameSite](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) set to `LAX`
