### ISSUE TITLE
Subscriptions SCA: add note for store admin with the URL for the customer to authenticate payment

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1045]
When a recurring payment requires authentication, the store owner may want to troubleshoot the situation manually. If they would like to send the link for their customer to authenticate, they should be able to find it somewhere - probably as an order note for the order that failed to renew due to customer authentication.

**Comment by thenbrent** [comment]
> If they would like to send the link for their customer to authenticate, they should be able to find it somewhere

This link is now available on the renewal order that requires payment. There is also an order action to allow the merchant to send the standard WC email to the customer:

<img width="1166" alt="Screenshot 2023-04-27 at 14 44 31" src="https://user-images.githubusercontent.com/235523/234761758-cd63127f-898b-40b8-a210-238cf4a34e82.png">

Labelling this as "needs docs" to make sure this information is captured in docs. Once documented, it can be closed.
