### ISSUE TITLE
SCA: Use SetupIntents when a customer updates their payment method for a subscription

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1046]
Steps to repro:
1. Add a new subscription as a customer
2. Update the payment method of the subscription using the test credit card `4000002500003155 ` so that it requires authentication
3. Notice that it does not require authentication
4. As the store owner, manually renew the subscription. See that the renewal payment failed because it requires authentication

Expected: when updating the payment method as the customer, to be shown the authentication modal if it's needed by the card

h/t @WillBrubaker  p2-p7bbVw-3oc#comment-8400

**Comment by RadoslavGeorgiev** [comment]
This sounds like it needs a lot of work, at leas more than a week. Moving to 4.3.2

**Comment by htdat** [comment]
3522087-zen
