### ISSUE TITLE
Subscriptions: Compatibility with Early renewals via Modal

### ISSUE THREAD

**Issue by DanReyLop** [woocommerce/woocommerce-gateway-stripe#1049]
See https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1048 or a lot more context.

~We'll need to remove [this filter](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1048/files#diff-0e15c5ae3c4b28bb406663efdd18e1d2R44) and instead properly fix the flow.~ Not anymore.

If "Accept Early Renewal Payments via a Modal" is enabled, when the customer chooses "Renew now" he will be presented with a modal, and a single "Pay now" button. That button will trigger a payment in the backend, and that payment can potentially require the customer to pass an SCA challenge. Since the customer is *right there*, we should be able to enqueue `stripe.js` and present the SCA modal there.

**Comment by reykjalin** [comment]
Can this issue be closed since #1084 has been merged?

cc @DanReyLop @RadoslavGeorgiev

**Comment by DanReyLop** [comment]
Absolutely. Weird that it didn't auto-close.
