### ISSUE TITLE
3DS for all Mastercard issued token transactions from April 2020

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce-gateway-stripe#1053]
This question has been raised in https://wordpress.org/support/topic/3ds-for-mastercard-issued-tokens/#post-12031609:

> I have been advised that from April 2020, Mastercard has mandated that all ecommerce transactions using a Mastercard issued token (such ApplePay and Android Pay) should be secured using 3DS. Does this plugin currently support this? Or are there plans to implement support?

This is one of the sources where it has been referenced - https://www.actsmart.biz/news/?id=2743&name=Global+Payments+changes+to+support+3DS+with+Digital+Wallets+

Are there any actions that need to be taken from our end? Or are we covered by SCA compliance?

Thank you for looking into it 🙏🏼

**Comment by DanReyLop** [comment]
We will be covered by SCA compliance. By using the new Stripe APIs (Payment Intents, Setup Intents, etc) any transaction (European or not) could potentially require 3DS and the extension would handle it correctly. Stripe determines if a transaction requires further authentication, so as long as Stripe handles those Mastercard transactions well, we have nothing to worry about.
