### ISSUE TITLE
Recurring payments don't work?

### ISSUE THREAD

**Issue by JanisOzolins** [woocommerce/woocommerce-gateway-stripe#106]
I'm using Stripe in test mode and was testing my subscription products but it doesn't seem to be working. Recurring orders are placed and marked as "Processing Payment..." but Stripe Gateway doesn't charge the user. What could be the problem?

**Comment by roykho** [comment]
I just did a test and it is working fine with no issues. Also this is not a place for help/support. You can post those questions here https://wordpress.org/support/plugin/woocommerce-gateway-stripe
