### ISSUE TITLE
Ensure you can purchase a WC Subscription using Google Pay

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1060]
h/t @treibalen 

Purchasing a new subscription with Google Pay has not worked since at least 4.1.16.

**Comment by v18** [comment]
Further testing instructions to come...

**Comment by allendav** [comment]
If y'all think this needs higher priority, feel free to bump to High. Is this a must fix for 4.3.1? Would love to defer to 4.3.2 in January if possible.

**Comment by RadoslavGeorgiev** [comment]
I'll re-check this in order to come up with a particular list of bugs, but I think there are too many of them for `4.3.1`. If that's the case, I'll open a new issue (to disable Subs purchases with Google Pay) for `4.3.1` and move this one to `4.3.2`.

**Comment by thomasdiesenreiter** [comment]
He, can confirm that this is a problem. It doesn't show the payment button but it inserts the "-- OR --" text right in front of the normal order button which is quite confusing.
