### ISSUE TITLE
Double payment complete notification due to duplicate status change

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce-gateway-stripe#1061]
**Describe the bug**

Reported in  2430512-zen

A unique case where a user is experiencing a double payment complete notification in the orders. This is causing the Stripe payout values to show incorrectly, as well as a duplicate status change (double emails). 

![https://cld.wthms.co/o8NBVs+](https://cld.wthms.co/o8NBVs+)
*If the image does not load, please click this link: https://cld.wthms.co/o8NBVs*

**Expected behavior**
A single payment, and status update in the order note section.

**Proposed fix by user**

> I’ve modified the note wrote by your plugin to understand what parts of the code gets actually called. The duplicated “Stripe change” notes were created in `includes/abstracts/abstract-wc-stripe-payment-gateway.php at line 424`.

> In that code block you’re only checking if ‘succeeded’ === $response->status and it’s corrected but as i can see in the log you call that function twice: when the PaymentIntent initiated and when it succeded. And calling it twice cause the error.

**Environment (please complete the following information):**
 - WordPress Version 5.24
 - WooCommerce Version 3.7.1
 - Stripe Plugin Version 4.3.0
 - Browser [e.g. chrome, safari] and Version N/A 
 - Any other plugins installed - Yes, as seen in the System Status Report on the ticket

**Additional context**
Please check the ticket for Background information and slack reference.

**Comment by AashikP** [comment]
Setting up `High Priority` for now, as if this is indeed a bug, we wouldn't want to miss this further.

**Comment by v18** [comment]
Probably the same issue: #1062
