### ISSUE TITLE
Payment Complete occurs twice on Woocommerce Subscriptions

### ISSUE THREAD

**Issue by melzaren** [woocommerce/woocommerce-gateway-stripe#1062]
**Describe the bug**
When renewing a woocommerce subscription, intermittently the payment goes from pending to complete twice for one order. This results in the hooks being fired twice, emails being sent out twice, etc. I've verified that this doesn't occur with other payment options (e.g. Paypal).

**To Reproduce**
  Start a subscription using the woocommerce stripe gateway plugin.
1. Go to tools->scheduled actions.
2. Click on pending actions.
3. Scroll down and click "run" on your subscription.
4. See the order in woocommerce->orders
    The order will go from pending to complete twice for the same order.

  Note that this doesn't occur every time, so you may have to fire the user's renew subscription action under tools->scheduled actions  more than once to trigger an order that is suffering from this bug.

**Expected behavior**
It should go from pending to complete only once.

**Environment (please complete the following information):**
 - WordPress Version 5.2.4
 - WooCommerce Version 3.7.1
 - Stripe Plugin Version 4.3.0
 - Browser [e.g. chrome, safari] and Version 77.0.3865.120
 - Any other plugins installed 

**Additional context**
This is occuring with sandboxed Stripe subscription renewals. I've never seen it occur on regular purchases. So far it only seems to occur with subscription renewals.

This issue has been raised before and appears to be on-going:

https://github.com/woocommerce/woocommerce-gateway-stripe/issues/889

![woocommerce stripe bug](https://user-images.githubusercontent.com/55931261/67234433-01423300-f3fa-11e9-8496-37038badca04.png)

**Comment by melzaren** [comment]
I'm afraid my knowledge of web development is limited. What's that? I'll try to reproduce this error on a fresh install of wordpress in a couple of days. Have you been able to produce it yourself?

**Comment by lvidal1** [comment]
Hey @melzaren @lkraav, did you find any workaround for this? It seems my store is facing the same issue. Not really sure why this is happening.

This is a screenshot I took from one of my current subscription order
![image](https://user-images.githubusercontent.com/6495076/150595944-d6de625d-c64c-4e36-96b2-91d7dd576eb1.png)

**Comment by lkraav** [comment]
> Did you find any workaround for this? It seems my store is facing the same issue. Not really sure why this is happening.

I don't have this problem, just participating in diagnosis.

You should post your plugin list, as there could be multiple things involved with status changes.
