### ISSUE TITLE
Live transactions fail with "trailing slash" error

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce-gateway-stripe#1066]
**Describe the problem**
Reporting as per @allendav and [this slack thread](https://a8c.slack.com/archives/C9976E5MJ/p1571256124020500)

Ticket: zd-2426982

Recently we had a customer who could not process Live transactions through Stripe. Test mode transactions worked, however when they tried live transactions they got the following error:

```
 [error] => stdClass Object
        (
            [message] => Unrecognized request URL (POST: /v1/payment_intents/). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/.
            [type] => invalid_request_error
        )
```

When contacting Stripe their support team said that this was essentially a 404 error due to a trailing `/` on being added to the end of the request. They said that this was a problem with the plugin, and that we would need to fix the request that's being sent to Stripe.

That didn't make sense since the request would work fine when using my Stripe credentials. Same site, same setup, only difference being my Stripe account, not theirs. Also since the customer can't impact the format of the requests the plugin sends to Stripe, it didn't make sense.

Ultimately the problem was resolved by simply inputting a new set of Public/Secret keys and new webhook secret.

It seems to me that either the error message that was given was incorrect. Or that the issue was the second possibility mentioned in the error:
`If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code`
I'm not sure if credentials would be an "Identifier" in this case or not? If they are, that would explain the problem being resolved by generating new credentials.

I don't think/know if there is anything on our side to "fix" but it would be good to know for the proper context of why that error was returned to save a lot of time for us/stripe/our customers trying to chase this down in the future.

**I'm not sure how to replicate this.**

**Comment by kosiew** [comment]
Another case #2455730-zen

**Comment by AashikP** [comment]
Another report in 2470866-zen. I've requested the user to roll the keys and try again.

**Comment by thuautp** [comment]
Following up on 2470866-zen, rolling back the keys didn't work for them. They still received the same error message: 

> "error": { 
> "message": "Unrecognized request URL (POST: /v1/payment_intents/).

**Comment by htdat** [comment]
Following up on 2470866-zen, this error is showing in Stripe Dashboard: 

> We received 60 requests in the last 7 days to an invalid API route.An invalid route may be caused by passing in a null ID to your client library or using unsupported HTTP methods. See the API docs (https://stripe.com/docs/api) for more information, or contact us at support@stripe.com.

The user followed up with Stripe support and got this info: 

> Looking at the logs, I see here that the error being sent is that the resource is missing.
Please provide WooCommerce this : https://stripe.com/docs/error-codes#resource-missing

**Comment by kg-2** [comment]
I'm running into this as well. Looking at the stripe logs, routes without a trailing slash succeed while with a slash return a 404 error

**Comment by kg-2** [comment]
I'm also getting php errors:
Notice: Undefined property: stdClass::$source in /home/tbasvrza/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php on line 1154

**Comment by vbelolapotkov** [comment]
@kg-2 thanks for reporting. Could you please do the following:

1. Share current WooCommerce version and WooCommerce Stripe Gateway version.
2. Check the logs in the stripe [dashboard](https://dashboard.stripe.com/logs?method%5B%5D=get&method%5B%5D=post&method%5B%5D=delete&direction%5B%5D=connect_in&direction%5B%5D=self). Make sure that filters are set as follows:
<img width="251" alt="Screenshot 2020-03-25 at 15 54 09" src="https://user-images.githubusercontent.com/3139099/77538512-e98f3f00-6eb0-11ea-8f58-37e2d84b89ac.png">

Then find the failing POST request like this:
![image](https://user-images.githubusercontent.com/3139099/77538677-252a0900-6eb1-11ea-9d58-980e96b03279.png)

Then check the requests before/after that. There should be preceding GET request, something like that: `GET /v1/payment_intents/pi_<long identifier>`. It should fail with 404 as well.
I'd appreciate if you could share the error details.

**Comment by vbelolapotkov** [comment]
For the record. At the moment the issue seems to be related to the error returned by Stripe API when trying to fetch payment intent by payment intent id stored in the order. [Src code](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/29d13fbaff02f0ef6b9e7939e6ad1e19a29d8f2b/includes/class-wc-gateway-stripe.php#L594).

However, it's unclear why this happens and the issue can't be reliably reproduced either in the test or in live mode.

P.s. Thanks to @RadoslavGeorgiev for the help with debugging.

**Comment by kg-2** [comment]
@vbelolapotkov 
Sorry about the delay- here's a screenshot
 
![image](https://user-images.githubusercontent.com/15877005/78582531-444a6400-77ea-11ea-97b1-01cca897d53e.png)

**Comment by vbelolapotkov** [comment]
@kg-2 thanks for the screenshot.

Could you please click on that one 👇 and share the response details?
![image](https://user-images.githubusercontent.com/3139099/78589883-98d0fc00-7849-11ea-90c0-bef9f86be972.png)

**Comment by kg-2** [comment]
@vbelolapotkov 
`{
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such payment_intent: pi_1GPt4CLfB3Fr5YQDRsg6QUjb; a similar object exists in test mode, but a live mode key was used to make this request.",
    "param": "intent",
    "type": "invalid_request_error"
  }
}`
