### ISSUE TITLE
Guest customer unable to process payment after zip code fails validation

### ISSUE THREAD

**Issue by jjcoffee** [woocommerce/woocommerce-gateway-stripe#1068]
A **guest** customer has reported being unable to make a payment, with the error "Sorry, we are unable to process your payment at this time. Please retry later.". Looking at the order notes, it looks like it initially failed zip code verification, then the customer returned the next day to retry several times (with different cards), but only the "unable to process" error is shown in the notes.

The logs show 6 repetitions of a block beginning with "sources/src_[...]", going through "Info: Begin processing payment for order ..." and ending with:

```
payment_intents/pi_[...] request: Array
(
    [source] => src_[...]
    [customer] => cus_[...]
)
```

The customer id changes each repetition (maybe because they are a guest?). Finally the request seems to go through and there's the following error:

```
[code] => payment_intent_unexpected_state
            [doc_url] => https://stripe.com/docs/error-codes/payment-intent-unexpected-state
            [message] => You cannot modify `customer` on a PaymentIntent once it already has been set. To fulfill a payment with a different Customer, cancel this PaymentIntent and create a new one
```

**Steps to reproduce (in test mode)**

1. Checkout as guest, using the zip and address line 1 validation error card number: 4000000000000010, which correctly displays the zip code invalid error
2. Retry payment using a valid card number (i.e. 4242424242424242)
3. Error shows: "Sorry, we are unable to process your payment at this time. Please retry later."

Running the latest WC and Stripe versions.

**Comment by rwaynick** [comment]
Today in 16215050-hc a user on Stripe 4.3.0 reported a similar issue. A customer tried to purchase but their card was declined. When they attempted another card the error in the log was,

```
 [code] => payment_intent_unexpected_state
            [doc_url] => https://stripe.com/docs/error-codes/payment-intent-unexpected-state
            [message] => You cannot modify `customer` on a PaymentIntent once it already has been set. To fulfill a payment with a different Customer, cancel this PaymentIntent and create a new one.

```

and the order notes displayed, "Sorry, we are unable to process your payment at this time. Please retry later.",

<img width="266" alt="Screen Shot 2019-10-25 at 2 49 34 PM" src="https://user-images.githubusercontent.com/10882502/67596433-b2b4d180-f736-11e9-81af-36fed699c72d.png">

I've asked the user to change the status back to Pending Payment and see if the customer can process payment in 2447750-zen

**Comment by v18** [comment]
Reported in 2450280-zen

**Comment by Luminus** [comment]
Reported again in 16342614-hc

**Comment by anant1811** [comment]
Reported in 2472532-Zen as well

**Comment by v18** [comment]
Reported in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1079

**Comment by damiannep** [comment]
Another report in 2474498-zen

**Comment by damiannep** [comment]
Another report in 2474498-zen
