### ISSUE TITLE
Stripe Payment Request button using incorrect Google Pay brand asset

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1071]
p7bbVw-3af-p2

https://href.li/?https://wordpress.org/support/topic/change-text-on-google-and-apple-pay-button/#post-11539622

Related: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/751

**Comment by dougaitken** [comment]
Previously: #753 #946

**Comment by NickGreen** [comment]
19136829-hc provided this link, which might help: https://developers.google.com/pay/api/android/guides/brand-guidelines

**Comment by dougaitken** [comment]
2871636-zen

**Comment by dougaitken** [comment]
WordPress.org - https://wordpress.org/support/topic/google-pay-button-styling/

**Comment by yukikatayama** [comment]
another request: 2881413-zen

**Comment by vbelolapotkov** [comment]
Blocked by #946 and #1197 .
