### ISSUE TITLE
Updating recurring payment method from non-Stripe to Stripe - Customer ID token is not saved to the subscription

### ISSUE THREAD

**Issue by jessLundie** [woocommerce/woocommerce-gateway-stripe#1072]
**Describe the bug**
Related to WooCommerce Subscriptions - when updating recurring payment method via My Accounts > Payment Methods from a non-Stripe payment method to Stripe, no Customer ID token is saved on the subscription. Subsequent recurring payments fail for a lack of Customer ID token.

A customer profile is correctly created in Stripe (in the case of a new Stripe customer) and the Source ID token is correctly saved on the subscription.

Seen in 2447640-zen

**To Reproduce**

1. Purchase a subscription through a non-Stripe automatic recurring payment solution (i.e. PayPal Checkout w/Reference Transactions)
2. Go to **My Account > Payment Methods** and add a new Stripe payment method
3. Be sure to select the option for "Update the Payment Method used for all of my active subscriptions (optional)."
4. Go to the subscription and click "Billing Details" to edit
5. See that no Customer ID token has been saved to this subscription

This will cause future renewal payments for this subscription to fail. 

**Expected behavior**
When updating the recurring payment method on an existing subscription from a non-Stripe option to Stripe, both the Customer ID token and the Source ID token should be saved to the subscription. 

**Screenshots**
![https://cld.wthms.co/VhdYxs](https://cld.wthms.co/VhdYxs+)
Full Image: https://cld.wthms.co/VhdYxs+

![https://cld.wthms.co/NIObsv](https://cld.wthms.co/NIObsv+)
Full Image: https://cld.wthms.co/NIObsv+

**Environment (please complete the following information):**
 - WordPress v. 5.2.4
 - WooCommerce version 3.7.1
 - Stripe v. 4.3.0
 - PayPal Checkout v. 1.6.17
- Browser / OS - Any

**Comment by poolet08** [comment]
Hi all ... Do we know if this has been resolved yet? 

Thanks

**Comment by treibalen** [comment]
Also reported in 2548516-zen
