### ISSUE TITLE
Stripe receipts not sent to customers

### ISSUE THREAD

**Issue by thuautp** [woocommerce/woocommerce-gateway-stripe#1077]
2442005-zen

**Describe the bug**
Stripe receipts are not sent to customers but only to admin, when user places a manual order and the customer pays through the customer payment link. I can't test/reproduce this on the Stripe test mode, but below are the steps if you can reproduce it:

**To Reproduce**
1. Create a manual order and change the status to `Pending Payment`
2. Pay as the customer through the Customer Payment link
3. Stripe receipt only gets sent to admin and not the customer

**Expected behavior**
Stripe receipt should be sent to both the admin and customer

**Screenshots**

Metadata being passed to stripe, which is correct, but then the email has been sent to admin's email address:
![9UNquA jpg](https://user-images.githubusercontent.com/13119409/68311104-abe96f80-00e3-11ea-8655-eedbec39a9b5.png)
![rLNPSw jpg](https://user-images.githubusercontent.com/13119409/68311106-ac820600-00e3-11ea-9edb-2d72fdcbec6b.png)

**Environment (please complete the following information):**
 - WordPress Version 5.2.4
 - WooCommerce Version 3.7.1
 - Stripe Plugin Version 4.3.0
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**
They've reached out to Stripe and below is what they said:

> 13 of the 30 most recent charges were created with a dynamic receipt email address, which overrides the default settings. I took a look through your payments and it looks like your email address is being passed on the charge object for some of the payments. (THE 13 WERE ORDERS I PROCESSED ON BEHALF OF CUSTOMERS PHONING IN THEIR ORDER)

> This is not supposed to happen, it should be the customer's email address that is passed on the payment, so I would suggest reaching out to WooCommerce about this and flagging this with them. They may have set your email address to dynamically override this, so they will probably just need to revert to their previous settings.

> it is happening because of the information WooCommerce are passing so they should be able to resolve this. They are sending the email address through the metadata but they are just not adding the email address to the payment intent object so it probably happened when they updated their plugin for SCA

**Comment by dougaitken** [comment]
Could be related to #1030 ? 

By default, customers don't get the Stripe.com generated receipt @thuautp since all invoicing and such are handled by WooCommerce

**Comment by v18** [comment]
@thuautp - the issue of not sending receipts to customers was fixed in the latest release of Stripe - 5.0.0. In order to enable sending receipts to customers, please add this filter using a snippet plugin:

`add_filter( 'wc_stripe_send_stripe_receipt', '__return_true' );`

I'm going to close this issue for now. If sending the customer receipt is still not working, feel free to re-open this issue to let us know the details of what's going on.
