### ISSUE TITLE
Refund attempt after cancelling an authorized payment

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-gateway-stripe#1081]
**Describe the bug**
When we cancel an authorized payment by changing an order to cancelled manually, we would expect the payment to be cancelled. However it seems it triggers a whole lot including a refund request which fails with the following error:

```
2019-11-07T12:54:58+00:00 DEBUG 
====Stripe Version: 4.3.0====
Error: This uncaptured Charge was created by a PaymentIntent (pi_1FcAV...). You must cancel the PaymentIntent to reverse the authorization instead of refunding the Charge directly. For more information, see https://stripe.com/docs/payments/payment-intents/creating-payment-intents#separate-auth-capture
```

In this case it was already cancelled which we can confirm with the following (earlier) log entry:

```
2019-11-07T12:54:57+00:00 DEBUG 
====Stripe Version: 4.3.0====
Success: Pre-Authorization Released
```

**To Reproduce**
We've had some issues replicating this behaviour, since on some sites it wasn't happening and on others it was. I was finally able to reproduce the behaviour on a site hosted on Pressable.

1. Turn off the Sstripe setting to "Capture charge immediately"
2. Make sure the Stripe webhooks are setup correctly and working for this site
3. Purchase a product and complete the checkout using Stripe
4. As an administrator manually change the order status to cancelled and update the order
5. Wait for the webhooks to trigger and change the order
6. Observe the order status is changed to "refunded" and we can see the error in the logs about the refund failing

**Expected behavior**

I'd expect the payment intent to just be cancelled but it seems there is a whole other chain of events started. Here are the events which are logged by Stripe:

```
Current PaymentIntent status: canceled

11/7/19, 12:54:58 PM
400 ERR A request to create a refund failed
POST /v1/refunds

11/7/19, 12:54:57 PM
A payment pi_1FcAV... for $15.00 USD was canceled
payment_intent.canceled

11/7/19, 12:54:57 PM
A $15.00 USD payment was refunded to user@email.test
charge.refunded

11/7/19, 12:54:57 PM
200 OK A request to cancel a PaymentIntent completed
POST /v1/payment_intents/pi_1FcAV.../cancel

11/7/19, 12:54:28 PM
The amount_capturable for payment pi_1FcAV... was updated
payment_intent.amount_capturable_updated

11/7/19, 12:54:28 PM
An uncaptured payment for $15.00 USD was created for user@email.test
charge.succeeded

11/7/19, 12:54:27 PM
200 OK A request to confirm a PaymentIntent pi_1FcAV... completed
POST /v1/payment_intents/pi_1FcAV.../confirm

11/7/19, 12:54:27 PM
A new payment pi_1FcAV... for $15.00 USD was created
payment_intent.created

11/7/19, 12:54:27 PM
200 OK A request to create a PaymentIntent completed
POST /v1/payment_intents
```

We can see these same events happening in the order:

![image](https://user-images.githubusercontent.com/11388669/68400290-b18c9700-016f-11ea-9485-ebfd167baf61.png)

What we can see there is that the order has the following note: Pre-Authorization Released via Stripe Dashboard
Although the payment was cancelled in the WooCommerce Dashboard, so we shouldn't have gotten this to show up. Nor would we expect the order to change to the refunded status.

**Environment:**
- WordPress 5.2.4
- WooCommerce 3.8.0
- Stripe Plugin 3.4.0

Affected ticket: 2467542-zen

**Comment by johndcoy** [comment]
Here is the series of events recorded by Stripe after an order is changed to Canceled:

![Screenshot](https://cld.wthms.co/DslVKX+)
Screenshot link: https://cld.wthms.co/DslVKX

**Comment by luismuv** [comment]
Is anyone looking into this?

**Comment by thezenit** [comment]
Hi all,

I have exactly the same problem on my website with:

WordPress: 5.3.2
Woocommerce: 3.9.2
Stripe Gateway plugin: 4.3.1

Thanks

**Comment by luismuv** [comment]
Hi, dont even bother with this support. use this one instead https://yithemes.com/themes/plugins/yith-woocommerce-stripe/ better support and it works as promised. you can also use an offline card processing plugin if somehow that doesnt work for you.

**Comment by thezenit** [comment]
Hi luismuv,

thanks for the suggestion, but the free version of the plugin is not enough for me, because I need deferred payments.

Furthermore, I tested a lot of different payments cases with the official plugin, and I cannot retry all tests with another plugin.

I hope some dev will notice this bug and fix it :)

Thanks

**Comment by thezenit** [comment]
Any updates?

Thanks

**Comment by ryonwhyte** [comment]
I am also having this same issue in the most recent version of WooCommerce (4.0.1) and WooCommerce Stripe Gateway (4.3.1 ) running WordPress 5.3.2. OceanWP and Elementor

**Comment by v18** [comment]
This is now fixed, closing the issue.
