### ISSUE TITLE
Error with stored cards after 4.3.0 upgrade

### ISSUE THREAD

**Issue by jenkoian** [woocommerce/woocommerce-gateway-stripe#1082]
**Describe the bug**
Upgraded to 4.3.0 on our test environment and are seeing the following bugs when attempting to checkout with previously saved cards:

`No such source: src_1DvjKZJT....Qlwu`

**To Reproduce**
1. Have a WooCommerce instance with a user with a saved card
2. Upgrade stripe plugin to 4.3.0
3. Attempt to checkout with said user using their saved card

**Expected behavior**
User should be able to checkout without issue.

**Screenshots**
![image (3)](https://user-images.githubusercontent.com/131355/68405213-96be2080-0177-11ea-9e4a-7f335bb54fed.png)

**Environment (please complete the following information):**
 - WordPress Version: 5.2.4
 - WooCommerce Version: 3.7.1
 - Stripe Plugin Version: 4.3.0
 - Browser [e.g. chrome, safari] and Version: Chrome 78.0.3904.87
 - Any other plugins installed: WooCommerce, WooCommerce PayPal Express Checkout (others too but less relevant) 

**Additional context**
If I delete the saved card and re-add it in my account > payment methods it seems to work as expected.

**Comment by thenbrent** [comment]
> It seems if you delete the stored card and re-save it, the issue goes away??

@jenkoian can you please provide more details on that, as it seems like an important clue. Are you deleting / re-saving via the **My Account > Payment methods** page? Or in the WordPress database directly? Or at Stripe.com?

**Comment by jenkoian** [comment]
@thenbrent have updated the issue description but I deleted the saved card and re-added within My Account > Payment methods.

**Comment by jenkoian** [comment]
Further update, we rolled back to the previous version and the issue is still occurring. So perhaps not an issue with this update? Unless the DB is in a state due to the update that this is now being caused?

**Comment by jenkoian** [comment]
Ok, so figured out what's going on here. Unlikely an issue with the new version (sorry).

We have two test accounts and the source was saved against account a, and we had switched to account b and thus the source was not being found (correct behaviour).

We do still get an error though. So switching back to account a, trying to checkout with the source that exists on count a, for some reason the customer parameter isn't included in the request and we're getting..

```
{
  "error": {
    "code": "parameter_missing",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-missing",
    "message": "The `source` parameter supplied src_1EBN5CD...lwm1xhHgHlWZ belongs to the Customer cus_EegS...RgW7k. Please include the Customer in the `customer` parameter on the PaymentIntent.",
    "param": "source",
    "type": "invalid_request_error"
  }
}
```

Here is the request body...

```
{
  "source": "src_1EBN5C...wm1xhHgHlWZ",
  "amount": "1849",
  "currency": "gbp",
  "description": "XXX - Order XXXXX",
  "metadata": {
    "customer_name": "XXX",
    "customer_email": "mxxxx.zxxxxx@xxxxx.com",
    "order_id": "XXXXX"
  },
  "capture_method": "automatic",
  "payment_method_types": {
    "0": "card"
  }
}
```

So the `"customer": "cus_EegS...RgW7k"` part of the request was missing. This was back on 4.2.5 though.

**Comment by allendav** [comment]
@RadoslavGeorgiev - would you take a quick look at this issue? I'm scoring as Priority: High for now

**Comment by RadoslavGeorgiev** [comment]
@allendav This should be an edge case and AFAICT there are not many reports for it, so as you said, we should not hold up today's release.

@jenkoian the described behavior doesn't make sense to me. Here's why:

Within [`WC_Stripe_Payment_Gateway::prepare_source`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.3.0/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L640) we are always making sure that a customer ID is set (introduced in 4.3.0).

The same `prepared_source` object (returned by the aforementioned method) is used when creating intents [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.3.0/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L1033). Unless an exception is thrown, the `customer` field must always be populated.

If you try this again, could you please monitor the extension's logs?

**Comment by jenkoian** [comment]
@RadoslavGeorgiev we've since tried again with a number of new and saved cards and are unable to recreate the issue. So perhaps just something to keep an eye on? We are now running 4.3.0 in production and no issues so far. Feel free to close this. Thanks for your help.
