### ISSUE TITLE
Customer's name being passed to Description field instead of Name field

### ISSUE THREAD

**Issue by thuautp** [woocommerce/woocommerce-gateway-stripe#1086]
#2482472-zd

**Describe the bug**

When running transactions, some of the customer data is not being sent to the right parameters in Stripe account. In the Account Information, the customers first/last name are being stored in the description section, while the `Name` field is blank. I can recreate this on my test site, using my Stripe account.

**To Reproduce**
1. Pay for an order using **Stripe** in test mode
2. Go to your **Stripe** account
3. Find the Customer's information under **Customers**
4. See **Details > Account Information**, `Name` field is blank, instead `Name` and `Username` can be found under `Description`, such as `Description: Name: first last Username: user_name`

**Expected behavior**
There should be the Customer's name under `Name` field, and not under `Description`

**Screenshots**
![Dashboard – Mobilyte – Stripe  Test ](https://user-images.githubusercontent.com/13119409/68592293-43c0d200-04c5-11ea-9bca-8a483568d053.png)

**Environment (please complete the following information):**
 - WordPress Version 5.2.4
 - WooCommerce Version 3.7.1
 - Stripe Plugin Version 4.3.0
 - Browser [e.g. chrome, safari] and Version 
 - Any other plugins installed
Advanced Custom Fields: Theme Code: by hookturn and Ben Pearson – 1.4.1
Advanced Custom Fields: by Elliot Condon – 5.8.6
Custom Post Type UI: by WebDevStudios – 1.6.2
Header Footer Code Manager: by 99robots – 1.1.6
Kadence WooCommerce Email Designer: by Kadence Themes – 1.3.4
User Role Editor: by Vladimir Garagulya – 4.52
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.3.9
Woo Discount Rules: by Flycart Technologies LLP – 1.8.1
WooCommerce Admin: by WooCommerce – 0.21.0
WooCommerce: by Automattic – 3.7.1 – 3.8.0 is available
WP Freshdesk: by Brainstorm Force – 1.0.3
WPForms Lite: by WPForms – 1.5.6

**Additional context**

**Comment by zhollenbeak** [comment]
17886123-hud reported this issue.

**Comment by v18** [comment]
This is fixed - the name now shows up in the name field for the customer.
