### ISSUE TITLE
Required Field not being respected when using Stripe payment plugin

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gateway-stripe#109]
@joelwills commented on [Thu Sep 08 2016](https://github.com/woocommerce/woocommerce-checkout-field-editor/issues/49)

When adding a required field, such as a checkbox:

![image](https://cloud.githubusercontent.com/assets/3228004/18363424/e806ec9e-75be-11e6-936c-765ab40c291a.png)

Then checking out using the Stripe plugin, you can checkout when the required field is not selected.

![image](https://cloud.githubusercontent.com/assets/3228004/18363601/a235d5b2-75bf-11e6-931e-2dd076a9c184.png)
- Tested on latest versions and replicated
- Other payment methods DO respect this and say that the field is required. It is only Stripe so far in my testing that does not
- It does this for both embedded checkout and Stripe Checkout
- Stripe does respect the default required fields, like Name, Phone etc. It seems to only be additional required fields added with CFE that are not respected

Please let me know if you have any further questions, thanks!

---
- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

---

@roykho commented on [Tue Sep 13 2016](https://github.com/woocommerce/woocommerce-checkout-field-editor/issues/49#issuecomment-246697302)

Hi @joelwills - from my testing it is only Stripe Checkout that has this issue. The embedded Stripe method works as expected. Can you please confirm?

---

@joelwills commented on [Tue Sep 13 2016](https://github.com/woocommerce/woocommerce-checkout-field-editor/issues/49#issuecomment-246743574)

Hmmm, it's only doing it for Stripe Checkout for me too now. When I first tested I'm 100% sure it did it for both as I switched back and forth, but perhaps that was due to a mistake when testing. 

Sorry about that!

**Comment by roykho** [comment]
In my latest test against master, this seems to be working. @joelwills please re-open if this is still an issue.

**Comment by WPprodigy** [comment]
Working for me: http://cld.wthms.co/NJFq/33GNflVI.

**Comment by jpottaway** [comment]
The issue is that custom fields are not validated BEFORE presenting the modal payment box.  All the default fields (like billing address etc) are validated before but a custom field (order notes for example in my case) are not validated until after the modal dialog returns, confusing the user.  I made the order note required using the top plugin on the WP repository.
