### ISSUE TITLE
No such customer error isn't handled correctly.

### ISSUE THREAD

**Issue by srjwebster** [woocommerce/woocommerce-gateway-stripe#1092]
Users who had a stripe customer ID once that no longer does generate an error and the handler isn't working correctly.

A recent payment request returned the following:

{
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such customer: cus_GB59S1zpxxxxxx",
    "param": "id",
    "type": "invalid_request_error"
  }
}

At line 234 of class-wc-stripe-customer.php uses a method is_no_such_customer_error() which looks like it would return true according to the three checks that are run, but it doesn't create a new user and the transaction fails. The message "No such customer: cus_GB59S1zpxxxxxx" appears in the front end.

We're running latest version plugin with latest version wordpress using a multisite setup.

It'd be useful to prefix the stripe customer id key with the site prefix so we can store multiple stripe customer IDs (one per website on the multisite).

**Comment by allendav** [comment]
> Users who had a stripe customer ID once that no longer does

How does this happen, exactly?

**Comment by srjwebster** [comment]
In my instance it's because I'm using a multisite where every site uses different stripe credentials but there is only one users table.

But this is a pre-existing method written to handle missing users. Assumedly this is used when people change stripe accounts (losing all customer records).

**Comment by srjwebster** [comment]
Thanks for adding to the milestone.

It looks like the mechanism is falling over during the update_customer() method of the WC_Stripe_Customer class.

It is called during the prepare_source() method of the main process_payment() method.

Updating the !empty($response->error) statement to include:

`if ( ! empty( $response->error ) ) {
    if ( $this->is_no_such_customer_error( $response->error ) ) {
	delete_user_meta( $this->get_user_id(), '_stripe_customer_id' );
	$this->create_customer();
    } else {
        throw new WC_Stripe_Exception( print_r( $response, true ), $response->error->message );
    }
}`

Seems to allow the order to complete successfully.

**Comment by srjwebster** [comment]
The more ideal solution is to always prefix the `_stripe_customer_id` field with the blog prefix.

**Comment by mikkamp** [comment]
Have a similar problem where we are seeing the following message:

```
[error] => stdClass Object (
	[code] => resource_missing
	[doc_url] => https://stripe.com/docs/error-codes/resource-missing
	[message] => No such customer: cus_GJqf5cmnLK4nSD; a similar object exists in test mode, but a live mode key was used to make this request.
	[param] => id
	[type] => invalid_request_error
)
```

In this scenario the user is switching from using test keys to live keys (we also see the same if they switch the other way around).

As previously mentioned there is a function which checks for this error: `is_no_such_customer_error`
Even though that function would match in this case, it seems like this is only checked when creating a new customer. In our case we have a Stripe ID so it triggers the code to update the customer, which just returns the error, see: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.3.1/includes/class-wc-stripe-customer.php#L186-L188

Or as suggested above, do we need to make the field `_stripe_customer_id` use a unique key in the following scenarios:
- live mode
- test mode
- different multi site

**Comment by allendav** [comment]
p6q7sZ-6uE-p2

**Comment by richardsplayground** [comment]
I have just run into this issue as well.  In our case, our organization changed legal structure and so we had to set up a new stripe account, but we are using the same web site.  We tried changing the Stripe public/secret keys in the plugin, and immediately started getting this error for all customers that had previously made a transaction with our old Stripe account.

In our case, using the blog prefix would not solve the issue, because it is the same web site.  We would need the stripe plugin to handle the situation gracefully: create a new customer record and record that new customer record in its data tables for future use.

**Comment by grigorijurasov** [comment]
2617224-zen - one more report.

**Comment by harishankerr** [comment]
2653686-zen - Yet another report.

**Comment by allendav** [comment]
@RadoslavGeorgiev - how soon can we have a PR for this?
