### ISSUE TITLE
Update_checkout removing the stripe card details.

### ISSUE THREAD

**Issue by rrpatil761** [woocommerce/woocommerce-gateway-stripe#1093]
When triggering update_checkout it is removing the stripe details as well. I can see the code of which is storing the payment info and restoring but seems like it is not working.

Is there any other way not to refresh stripe credit card details?

**Comment by dechov** [comment]
Thanks @rrpatil761 for reporting and @juliaamosova for forwarding.

The re-population after update (https://github.com/woocommerce/woocommerce/pull/12821) doesn't work for `<iframe>`'d fields such as the Stripe Elements used here, but the broader issue should be addressed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/927 and https://github.com/woocommerce/woocommerce/pull/24227 (merged but not yet released).
