### ISSUE TITLE
Add support for Boletos installments

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1096]
p7bbVw-3uD-p2

**Comment by allendav** [comment]
For the purpose of 4.4.0 APM-palooza, it would be best to first do a spike / estimated effort instead of aiming to close this issue in 4.4.0.  The results of the spike/estimate should be recorded here.

cc @bmccotter

**Comment by jffaria** [comment]
Hello! It took a while for Stripe to enable the beta Boletos for my account, but they did so last Friday. Has there been any development on this front here?

**Comment by allendav** [comment]
Hi @jffaria - not yet, sorry

cc @bmccotter 

Duplicate with #1247 ?

**Comment by jffaria** [comment]
Hello, I think this can be closed, I see boleto has been pushed now.

**Comment by jffaria** [comment]
tho not with support for woo subscriptions

**Comment by thenbrent** [comment]
Closing this one as [OXXO and Boleto are now available](https://href.li/?https://woocommerce.com/document/stripe/#additional-payment-methods). If there are specific features you would like supported in those payment methods (like installments or WC Subscriptions' support), please vote or open a feature request on the feature request board here: https://woocommerce.com/feature-requests/stripe/# as this feature request board will be used to track popularity of feature requests and use that to help determine their priority.
