### ISSUE TITLE
Error message "Could not find payment information" although correct datas are entered

### ISSUE THREAD

**Issue by SpabRice** [woocommerce/woocommerce-gateway-stripe#110]
Since some hours we have problems for the credit card checkout.
Even if all datas are enterred correct, we get an error message "Could not find payment information"
This is very urgent because we're loosing clients.

**Comment by roykho** [comment]
Hello,

This is not the place to get help but rather a place to report reproducible bugs. If you need help please post your question on the proper channel here https://wordpress.org/support/plugin/woocommerce-gateway-stripe
