### ISSUE TITLE
Apple Pay - Idempotency

### ISSUE THREAD

**Issue by jrick1229** [woocommerce/woocommerce-gateway-stripe#1103]
**Describe the bug**
When using Apple Pay during checkout, clicking the pay button more than once (which can occur if slow loading, etc.) can result in more than one payment being made.

**More Information**
This was brought up with Stripe support, who suggested that this can occur due to idempotency not being used on these types of payments.

- https://stripe.com/gb/blog/idempotency
- https://stripe.com/docs/api/idempotent_requests

**Additional context**
Ticket: [2537410-zen](https://woothemes.zendesk.com/agent/tickets/2537410)

<details>

```
WP Version: 5.2.4
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1
WooCommerce: by Automattic – 3.6.5
```

</details>

**Comment by jrick1229** [comment]
Sorry for my lack of available details.
I would be happy to find out more information if requested.

**Comment by dwainm** [comment]
Moving complexity to large as this requires an apple pay account which is a process we'll need to resolve as we should be able to test Apple pay from any region where Automatticians live.

This is also not easy to reproduce. The payment request doesn't not have any idempotency parameters:
https://stripe.com/docs/js/payment_request

**Comment by dwainm** [comment]
I'm closing this issue for the following reasons:

1. All payment requests need to be authenticated before the payment goes through. A user has to confirm payment before the process can deduct money.
2. It can't be replicated
3. There have been no other reports.
