### ISSUE TITLE
Payment Card Icon shows based on currency settings rather than Stripe rules

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce-gateway-stripe#1115]
**Describe the bug**
The Discover card icon will show for European Stripe accounts. 

From Stripe, U.S. businesses can accept Visa, MasterCard, American Express, JCB, Discover, and Diners Club. Australian, Canadian, European, and Japanese businesses can accept Visa, MasterCard, and American Express.

```
        if ( 'USD' === get_woocommerce_currency() ) {
            $icons_str .= isset( $icons['discover'] ) ? $icons['discover'] : '';
            $icons_str .= isset( $icons['jcb'] ) ? $icons['jcb'] : '';
            $icons_str .= isset( $icons['diners'] ) ? $icons['diners'] : '';
        }
```
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.3.1/includes/class-wc-gateway-stripe.php#L210-L214

**To Reproduce**
Here is a screenshot showing Discover as a disallowed card with Ireland as the country within Stripe > Settings > Account settings. 

**Screenshots**
![Screen Capture on 2020-01-08 at 09-48-39](https://user-images.githubusercontent.com/55294242/71999251-ac4ad780-3206-11ea-836a-39bbc074e258.gif)

**Expected behavior**
The expected behavior is for there to be a notification for disallowed card types based on Stripe's settings. Also, see #974 for icon showing inline with card number field.

**Comment by damiannep** [comment]
Another report of this in 3131713-zen

**Comment by damiannep** [comment]
Another case of this in 3517242-zen

**Comment by dmallory42** [comment]
Another case of this reported in 3734248-zd-woothemes. This time it related to JCB branding not appearing when the store currency is set to JPY. [Stripe documentation](https://support.stripe.com/questions/accepting-japan-credit-bureau-(jcb)-payments) specifies which regions/currencies JCB is supported by.
