### ISSUE TITLE
No Setting for Apple Pay Merchant Name

### ISSUE THREAD

**Issue by thinkcodenyc** [woocommerce/woocommerce-gateway-stripe#112]
#### What I expected

I expected the Apple Pay option to display my Merchant Name from my Stripe Account on my MacBook Pro's Touch Bar. 

#### What happened instead

Instead of displaying my Merchant Name from my Stripe account, it displayed my Site Name in my WordPress settings on my Touch Bar. Often times, site names in WordPress settings are loaded with keywords for SEO and aren't what you'd want to display to users in these circumstances.

I recommend a metabox be added to the Stripe configuration settings to define your Merchant Name, and by default it can use your site name. I expect that would be the most flexible solution. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Close in favor of #130
