### ISSUE TITLE
Stripe & Apple Pay Design Test 

### ISSUE THREAD

**Issue by bmccotter** [woocommerce/woocommerce-gateway-stripe#1121]
**Is your feature request related to a problem? Please describe.**

Apple Pay does not appear on the checkout (only prior to final checkout)

**Describe the solution you'd like**
Run a design test which reminds the customer they'll have the opportunity to confirm the final amount prior to paying. 

**Describe alternatives you've considered**

**Additional context**
@allendav  and I have been working with the Stripe team on solutioning

**Comment by thenbrent** [comment]
Closing this one as Apple Pay and other PRBs are displayed at the top in the checkout blocks now.
