### ISSUE TITLE
possible "reusable source" error when renewing subscription

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1126]
This has not yet been reproduced.

Steps:
1. Checkout with SEPA for a subscription with a free trial
2. The first payment goes through ok
3. The renewal does not go through with this error:

```
The reusable source you provided is consumed because it was previously charged without being attached to a customer or was detached from a customer. To charge a reusable source multiple time you must attach it to a customer first. 
```

cc @grigorijurasov 

Ticket: zen-2601963

**Comment by reykjalin** [comment]
I'm tagging this with `Priority: Low` since this seems to be an isolated incident, and no one has been able to reproduce the issue, even on the staging site provided by the customer.

**Comment by damiannep** [comment]
A user reported another case of this in 21065429-hc using Stripe, not SEPA.

**Comment by tsetend** [comment]
I'm not sure if this is related but I got a user in 3070467-zen where the auto-renewal doesn't go through and gives error:

`"[message] => The provided source has already been used to make another payment. You cannot reuse sources without attaching them to a Customer object first.
[type] => invalid_request_error"`

However, they can process the renewal manually from the orders page.

**Comment by blueneel05** [comment]
did anybody found any solution ? 
I am facing similar issue this is from woocommerce stripe log
`Error: stdClass Object
(
    [error] => stdClass Object
        (
            [message] => The source you provided has already been attached to a customer.
            [param] => source
            [type] => invalid_request_error
        )

)`

**Comment by katinthehatsite** [comment]
Another case in 3302752-zen

The customer shared the following solution that worked for them:

We’ve resolved the problem by changing the “_stripe_source_id" and “_stripe_customer_id” in the subscription. But the question is still there.

**Comment by samourenn** [comment]
Hi @katinthehatsite 

I have the same issue.
What do you mean by changing the “_stripe_source_id" and “_stripe_customer_id” in the subscription ?

Regards

**Comment by abhishek-pokhriyal** [comment]
@samourenn in the `wp_postmeta` table check the for meta_key `_stripe_source_id` and `_stripe_customer_id` for the particular subscription ID. Update those values with the correct values, the ones found in the stripe dashboard.

**Comment by samourenn** [comment]
Thanks @abhishek-pokhriyal but when you have a source which is "consumed" in Stripe even if you have source ID and customer ID, You can do anything. Correct ?

**Comment by v18** [comment]
I'm not able to repro this issue using the steps outlined in the main post, so I'm closing the issue.

If there are any other issues related to the reusable source error, please provide steps to repro so we can take a look:

`The reusable source you provided is consumed because it was previously charged without being attached to a customer or was detached from a customer. To charge a reusable source multiple time you must attach it to a customer first.`
