### ISSUE TITLE
Handle Stripe.com account changes

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#1128]
2657609-zen

**Describe the bug**

Under certain circumstances, store owners may need to change the Stripe.com account.

This will cause the error shown in #1092 but has a large scope of how to fix that.

**To Reproduce**

I chatted to a store owner on WooCommerce.com live chat, this was their scenario:

> We recently went through a legal change that required us to create a new Stripe account. We were using the Stripe/Woo plugin fine previously. After inputting the new Stripe keys for our new account, we tried placing a test order in test mode using my WordPress Admin user, but we received the following error
> 
> No such customer: cus_xxxxxxxxx
> 
> Later we tried to place another test order in incognito mode and it worked, but we wanted to check with you about this, and see if you could take a look and give us directions. Reading some support forums such as the one below it looks like this issue could potentially affect all existing customers.

Also https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1092#issuecomment-571888062 by @richardsplayground 
>  We tried changing the Stripe public/secret keys in the plugin, and immediately started getting this error for all customers that had previously made a transaction with our old Stripe account.

**Expected behavior**

Store owners can change their Stripe.com if required using the Settings screen, our extension handles the code aspect

**Additional context**
p6q7sZ-6uE-p2#comment-19674

cc @compchris per p2 post and @richardsplayground due to your comment in #1092 

@allendav I'm placing Low due to the description of that label - this only affects a small number of users but is a show stopper for those customers so you may want to reprioritize.

**Comment by DustinHartzler** [comment]
I had chat with 17338909-hc on Saturday and it turns out they got the error:

> No such customer: cus_xxxxxxxxx

Because they imported some customers from a different website and the Stripe customer_ID was saved in the database in the `wp_usermeta` table. Since this table used a different Stripe account, when logged in users tried to make a purchase, they got the error message because that customer account wasn't created in the new Stripe account.

**Comment by grigorijurasov** [comment]
A similar error happens when switching from live to test modes and vice versa:

No such customer: cus_***; a similar object exists in live mode, but a test mode key was used to make this request.'

Two reports from today:

2665580-zen

18504981-hc

**Comment by dougaitken** [comment]
@grigorijurasov that scenario is covered in #1092 👍 

This issue is specific to different Stripe.com accounts

**Comment by DavidAnderson684** [comment]
Stripe will transfer customers between Stripe accounts if you ask them and can produce documentation.

**Comment by amandasjackson** [comment]
Another report 2735987-zen

**Comment by johndcoy** [comment]
Another 2756015-zen

**Comment by johndcoy** [comment]
from @mikkamp in another issue's thread:

```
[error] => stdClass Object (
	[code] => resource_missing
	[doc_url] => https://stripe.com/docs/error-codes/resource-missing
	[message] => No such customer: cus_GJqf5cmnLK4nSD; a similar object exists in test mode, but a live mode key was used to make this request.
	[param] => id
	[type] => invalid_request_error
)
```

In this scenario the user is switching from using test keys to live keys (we also see the same if they switch the other way around).

As previously mentioned there is a function which checks for this error: `is_no_such_customer_error`
Even though that function would match in this case, it seems like this is only checked when creating a new customer. In our case, we have a Stripe ID so it triggers the code to update the customer, which just returns the error, see: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.3.1/includes/class-wc-stripe-customer.php#L186-L188

Or as suggested above, do we need to make the field _stripe_customer_id use a unique key in the following scenarios:

live mode
test mode
multisite

**Comment by johndcoy** [comment]
Another 2835672-zd
