### ISSUE TITLE
Stripe Google Chrome Payment issue

### ISSUE THREAD

**Issue by hardipparmar-multidots** [woocommerce/woocommerce-gateway-stripe#1138]
**Describe the bug**

I have created a support ticket on strip plugin,
Please check this support ticket URL: https://wordpress.org/support/topic/stripe-google-chrome-payment-issue/

The wrong variation placed when payment via chrome stripe payment.

**Comment by hardipparmar-multidots** [comment]
Today, I have debugged stripe plugin in my local. There is an issue with (slash) attributes ie.(`Fits 2-1/2\" Hitch`) and an actual attribute is (`Fits 2-1/2" Hitch`).

I have added code on the following files.
`/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-payment-request.php`
Ajax function names: `1. ajax_add_to_cart` and `2. ajax_get_selected_product_data`

Line number 921(ajax_add_to_cart) after adding code:
`$attributes = array_map( 'stripslashes_deep', $attributes );`

Line number 821(ajax_get_selected_product_data) after adding code:
`$attributes = array_map( 'stripslashes_deep', $attributes );`

Please check this: [screenshot URL](https://i.imgur.com/v3bLEdI.png)

Also, when I pass the attribute in query parameter of the product variation like [?attribute_hitch-size=Fits+2-1%2F2"+Hitch&attribute_pa_tow-rating=16000lbs](https://i.imgur.com/bRbwhmW.png)

Then the first time showing the wrong price in chrome payment popup.
After adding following code in `startPaymentRequest` this function of the `stripe-payment-request.js` file [screenshot](https://i.imgur.com/Cjbj8Kr.png)
`$( window ).on( 'load', function() {
        $( '#wc-stripe-payment-request-button' ).block( { message: null } );
           $.when( wc_stripe_payment_request.getSelectedProductData() ).then( function( response ) {
	        $.when( paymentRequest.update( {
		          total: response.total,
  	                 displayItems: response.displayItems
	                  } ) ).then( function() {
		$( '#wc-stripe-payment-request-button' ).unblock();
		} );
	} );
} );`

After all the above changes, I have tested its variations and price getting correctly on thank you page.
Can you verify and let me know.

**Comment by reykjalin** [comment]
Tagging this with `Priority: Low` for now, since I can't find any other reports of this issue.

**Comment by hardipparmar-multidots** [comment]
@reykjalin Thank you for replay. can you please create `Fits 2-1/2" Hitch` this type of attribute and try it.
you will get the issue. 

Thanks
