### ISSUE TITLE
Fatal error:WCS_Early_Renewal_Manager

### ISSUE THREAD

**Issue by arjun1638** [woocommerce/woocommerce-gateway-stripe#1139]
**Describe the bug**
Uncaught Error: Call to undefined method WCS_Early_Renewal_Manager::is_early_renewal_via_modal_enabled() in /var/www/shop-test.bertrand.bio/html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php:382

**To Reproduce**
Create subscription order and access the my accounts-> susbscripions

**Expected behavior**
Should show a list of susbscription orders

**Screenshots**
![stripe](https://user-images.githubusercontent.com/18402562/75022256-0beb0280-5496-11ea-9f5d-2b02e5d238b7.PNG)
2

**Environment (please complete the following information):**
 - WordPress Version : 5.3.

 - WooCommerce Version 3.8.1
 - Stripe Plugin Version 4.3.2
 - Browser - chrome
 - Any other plugins installed

**Additional context**

**Comment by DanReyLop** [comment]
Hi there!

I've opened #1141, that should fix the error. However, we don't know when the next release of the Stripe plugin will happen.

In the meantime, the easiest solution is to update the `WooCommerce Subscription` plugin, because the `is_early_renewal_via_modal_enabled` function only exists in WooCommerce Subscriptions `2.6.0` or later.

Cheers!

**Comment by giulianorapoz** [comment]
Hi @DanReyLop 

Also same bug on my site. My Woocommerce Subscriptions license has expired (current version `2.5.5`) , so I cannot update to `2.6.0`. Is there any other fix in the meantime whilst waiting for the Stripe patch?

Thanks!

**Comment by arjun1638** [comment]
Hello
You can downgrade stripe plugin to 4.3.1 as of now, it should work.

**Comment by DanReyLop** [comment]
Yes, you can downgrade to 4.3.1, or you can also manually apply the change on https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1141 to the plugin in your site (it's just one line).

Sorry for the inconvenience, I'll see if we can release a new version of Stripe soon.

**Comment by reykjalin** [comment]
Tagging this with `Priority: Low` since we already have a solution to this, and it should be merged in the next release. @DanReyLop feel free to change the prioritization as you see fit 🙂.

**Comment by enoteware** [comment]
> Yes, you can downgrade to 4.3.1, or you can also manually apply the change on #1141 to the plugin in your site (it's just one line).
> 
> Sorry for the inconvenience, I'll see if we can release a new version of Stripe soon.

Your method worked for me with the same issue. Stripe please review :D
