### ISSUE TITLE
No stripe button at checkout in live mode (but present in test mode)

### ISSUE THREAD

**Issue by EnjeruTantei** [woocommerce/woocommerce-gateway-stripe#1140]
**No stripe button at checkout in live mode (but present in test mode)**
There is no stripe checkout button among the payment methods on the checkout page. 

**To Reproduce**
1. Install Stripe Gateway
2. Go to Stripe settings in payments
3. Put in Publishable Key, Secret Key, and Webhook Key
4. See missing button.

**Expected behavior**
There should be a stripe checkout button among the payment methods on the checkout page. 

**Screenshots**
https://drive.google.com/file/d/18nvcxG44ye3NK__53Gf7HNa8vN5aD0MN/view?usp=sharing
https://drive.google.com/file/d/1-o68L__VlKYpEQ6advpRElS7DRN3yWkL/view?usp=sharing

**Environment (please complete the following information):**
 - WordPress Version: 5.3.2
 - WooCommerce Version: 3.9.2
 - Stripe Plugin Version: 4.3.2
 - Browser [e.g. chrome, safari] and Version: Google Chrome - Version 80.0.3987.116 (Official Build) (64-bit)
 - Any other plugins installed: 
&nbsp;&nbsp;&nbsp;&nbsp;Elementor
&nbsp;&nbsp;&nbsp;&nbsp;Elementor Pro, 
&nbsp;&nbsp;&nbsp;&nbsp;Facebook for WooCommerce, 
&nbsp;&nbsp;&nbsp;&nbsp;Gooten Shipping for WooCommerce, 
&nbsp;&nbsp;&nbsp;&nbsp;Ocean Custom Sidebar, 
&nbsp;&nbsp;&nbsp;&nbsp;Ocean Extra, 
&nbsp;&nbsp;&nbsp;&nbsp;Ocean Product Sharing, 
&nbsp;&nbsp;&nbsp;&nbsp;Ocean Social Sharing, 
&nbsp;&nbsp;&nbsp;&nbsp;Ocean Stick Anything, 
&nbsp;&nbsp;&nbsp;&nbsp;Official Facebook Pixel, 
&nbsp;&nbsp;&nbsp;&nbsp;Printful Integration for WooCommerce, 
&nbsp;&nbsp;&nbsp;&nbsp;Printify, 
&nbsp;&nbsp;&nbsp;&nbsp;WooCommerce, 
&nbsp;&nbsp;&nbsp;&nbsp;WooCommerce Admin, 
&nbsp;&nbsp;&nbsp;&nbsp;WooCommerce PayPal Checkout Gateway, 
&nbsp;&nbsp;&nbsp;&nbsp;WooCommerce Services, 
&nbsp;&nbsp;&nbsp;&nbsp;WooCommerce Stripe Gateway, 
&nbsp;&nbsp;&nbsp;&nbsp;WP Mail SMTP, 
&nbsp;&nbsp;&nbsp;&nbsp;WPForms Lite

**Additional context**
The interesting thing is that the button shows up as expected when in test mode, but not in live mode. I've tried re-rolling the secret key, replacing the key value, disabling and re-enabling, but no dice.

**Comment by RadoslavGeorgiev** [comment]
Hi @EnjeruTantei,

could you please clarify this line?

>  There should be a stripe checkout button among the payment methods on the checkout page.

Do you mean that the option to choose Credit Card (Stripe) is not displayed at all, or the fields within it are not visible?

From what I see in your settings, everything looks alright. The only reason not to see the gateway in the list on the checkout page would be an empty secret and/or publishable key, but that's not the case for you.

Could you please test this while disabling the other installed plugins? I don't see anything that would interfere with the gateway, but I don't see any other meaningful explanation either.

**Comment by reykjalin** [comment]
I don't see many reports of this, so I'm tagging this with `Priority: Low`.

As a sidenote, maybe this is happening because the site [isn't using HTTPS](https://docs.woocommerce.com/document/stripe/#section-21)? This could also happen if the customer [isn't in a supported region](https://docs.woocommerce.com/document/stripe/#section-22).

**Comment by EnjeruTantei** [comment]
@reykjalin @RadoslavGeorgiev My apologies for the late response. I did figure out how to get it to show up. I believe my issues to have been tied to two factors. At first, I was confused on how the API, Webhook, and Secrets worked via Test/Live mode, so I had them set incorrectly. The second factor was that I needed to click the checkbox at the top of the box to turn the gateway off (in the Woocommerce settings), save, and then turn it back on. 

I'm unsure as to why this would prevent it from displaying correctly, but as soon as I did this, it suddenly started working. The interesting thing is that my website does have HTTPS ( and it's using it as well ), but for some reason the gateway doesn't detect it. Not sure why, but even now ( with it functioning as intended ) it gives me a notice about SSL not working, even though it 100% is. Strange, but at least it's working now.

**Comment by v18** [comment]
Thanks @EnjeruTantei for letting us know that the stripe checkout button is now working as expected. I'm going to close this issue. It sounds like there is still an outstanding issue with SSL - if that persists, please open a new issue with details about the problem so we can investigate.

**Comment by allendav** [comment]
@EnjeruTantei wrote:

> my website does have HTTPS ( and it's using it as well ), but for some reason the gateway doesn't detect it

What hosting company and plan are you using?
