### ISSUE TITLE
Order-pay endpoint wrong amount

### ISSUE THREAD

**Issue by askebode** [woocommerce/woocommerce-gateway-stripe#115]
#### What I expected

On a failed automated transaction, the user is sent an email asking to complete the order with new card datails on /cart/order-pay/###

#### What happened instead

The issue I'm having is that the payment data in `payment_fields()` is taken from the cart total: `WC()->cart->total` and not from the order total leaving the payment either wrong or zero.

#### Steps to reproduce the issue

I use the Stripe checkout option, but the issue should be easy to reproduce.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
> On a failed automated transaction

Can you please explain what you mean by "automated transaction" here? Subscriptions? If so, which subscription plugin are you using?

**Comment by askebode** [comment]
No, it's pre-orders. I'm using "Woocommerce Pre-Orders".

**Comment by roykho** [comment]
So you're using "Charge upon release" ?

**Comment by askebode** [comment]
Yes, exactly.

**Comment by roykho** [comment]
Hi @askebode - would you mind checking out the master branch and see if this is resolved for you?

**Comment by askebode** [comment]
Hi! Yeah this solves it! Thanks - this opens another issue though, but I'll post a new one.
