### ISSUE TITLE
Stripe placeholder text not translated to “nb”

### ISSUE THREAD

**Issue by simenjh** [woocommerce/woocommerce-gateway-stripe#1152]
WordPress 5.3.2
Woocommerce 4.0.1
WooCommerce Stripe Gateway 4.3.2

The site language is in Norwegian (nb), but the Stripe placeholder text is not translated to nb. According to this: [How can I translate the placeholders text inside the credit card form?](https://docs.woocommerce.com/document/stripe/#section-33), nb is supported. 

It doesn't translate Suomi (fi) either, but does properly translate locales like en, de and fr. I have made sure to update Wordpress after selecting a new site language.

**Comment by yukikatayama** [comment]
This came in from the [forums](https://wordpress.org/support/topic/stripe-placeholder-text-not-translated-to-nb/). 

I was also able to replicate that the placeholder text does not translate when in Norwegian.

**Comment by allendav** [comment]
Hi @simenjh @yukikatayama 

I was able to reproduce this as well. It looks like Stripe doesn't like the full locale `nb_NO` being passed to them but needs it to be just `nb`

If you change the custom filter as follows:

```
add_filter( 'wc_stripe_elements_options', 'wc_update_locale_in_stripe_element_options' );
function wc_update_locale_in_stripe_element_options( $options ) {
    return array_merge(
        $options,
        array(
            'locale' => 'nb'
        )
    );
};
```

You should get a properly localized field:

<img width="290" alt="Screen Shot 2020-03-27 at 1 42 33 PM" src="https://user-images.githubusercontent.com/1595739/77799203-8678e600-7031-11ea-8bfd-f49bd75413f7.png">
