### ISSUE TITLE
No such customer error

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce-gateway-stripe#1159]
**Describe the bug**

This has been described by @mikkamp here: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1092#issuecomment-565794126

I am not sure if that has been fixed in the PR of that issue, but I keep seeing this error when customers switch from test to live.

**Expected behavior**

Switching should not create such an issue. Or we should have a way to clear the data from the Dashboard without needing to access the database.

**Comment by tijosh** [comment]
Report of this in #3174322-zen

**Comment by v18** [comment]
@SiR-DanieL and @tijosh - are there steps we can follow to reproduce the issue?

**Comment by SirDarcanos** [comment]
@v18 try signing-up for a WooCommerce Subscriptions sub in test mode, then switch in live mode and try renewing that sub.

I think that should trigger the issue

**Comment by wjrosa** [comment]
This issue was fixed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3110
