### ISSUE TITLE
function allowed_items_in_cart

### ISSUE THREAD

**Issue by exdefoot** [woocommerce/woocommerce-gateway-stripe#1170]
Hi,

I was facing a fatal error when trying to edit a page that has a custom shortcode that checks the user’s cart content:

`Fatal error: Uncaught Error: Call to a member function get_cart() on null in /plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-payment-request.php on line 419`

Wrapping the function between `if( ! is_admin() ) {` fixed the issue and I would recommend to do so in your future updates.

Best regards

**Comment by dwainm** [comment]
Hi @exdefoot. The code for checking this should be added to the custom shortcode. The code we have there should never be loaded in an admin context and therefore we do not check for it.
