### ISSUE TITLE
Cant fill credit card form

### ISSUE THREAD

**Issue by diyquad** [woocommerce/woocommerce-gateway-stripe#1171]
Hi,

With woocommerce and stripe gateway last version. Stripe is new stripe accout, so by defaut using last version of Stripe API. But in stripe plugin, it call the 2019-09-09 API version

I have 2 differents bugs: 
1) icons of Visa / Mastercard became huge 
2) It's not impossible to complet Text filled [for](url) credit card details are not displaying

Have been able to solve 1) with simple CSS trick, but for 2) it's not working;
I have tryed different theme template, even default one, still same problem

**To Reproduce**
Go to front, add to cart, proceed to checkout, impossible to enter credit card details

**Expected behavior**
display filled to enter details

**Screenshots**
![Capture d’écran (6)](https://user-images.githubusercontent.com/34099384/79453721-58f8da00-7fea-11ea-9c23-2b115e098428.png)

**Environment (please complete the following information):**
 - WordPress Version: 4.0.1
 - WooCommerce Version: 4.0.1
 - Stripe Plugin Version: 4.3.3  (but also try 4.3.1 and 4.3.2)

Thanks for your help

**Comment by allendav** [comment]
Can you share a URL that we could look at?

**Comment by diyquad** [comment]
solved. it think it was due to ssl issue. thanks

**Comment by scux** [comment]
Hi @diyquad we've encountered the same issue. Can you please share the founded fix ?
As we can see, the plugin dependencies (css & js) are not loaded.

**Comment by diyquad** [comment]
@scux you have to force SSL checkout and check all your CSS/JS call to be sure to call everything to HTTPS (no mixed content)
then it work...
