### ISSUE TITLE
Furture -> Future

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1173]
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/5958ce9f3c98f5e20b22b9bd6aaa156a77332b43/includes/admin/class-wc-stripe-admin-notices.php#L160

**Comment by dwainm** [comment]
Fixed along with https://github.com/woocommerce/woocommerce-gateway-stripe/issues/833
