### ISSUE TITLE
No charge on order-pay endpoint

### ISSUE THREAD

**Issue by askebode** [woocommerce/woocommerce-gateway-stripe#118]
#### What I expected

Hi! Starting on the order-pay endpoint, the Stripe Checkout opens with the right amount, and everything seems good, and I'd expect the order to be payed and redirected to the thank you-page.

#### What happened instead

The Stripe Checkout button goes green, a token is sent, but no charge is sent and there is no redirect - nothing really happens.

#### Steps to reproduce the issue

Trying to pay for a order through the order-pay endpoint.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Could you please test this same situation again but this time with "Stripe Checkout" disabled and see if you get the same result?

**Comment by askebode** [comment]
It's the same - a token is sent but no charge and the site just freezes

**Comment by roykho** [comment]
Strange, it is working on my end. After payment, I get the "Order Received" page. What theme are you using? Can you please switch to a WordPress Default theme say 2016 theme and see if that works?

**Comment by roykho** [comment]
Closed due to lack of activity and unable to reproduce.
