### ISSUE TITLE
Update WooCommerce Compatibility

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/woocommerce-gateway-stripe#1182]
**Describe the bug**
In light of this [PR](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/828#issuecomment-490667496), Stripe is not backwards compatible with WC 2.6.12. We should update the following to make sure users aren't relying on features that won't work in their version of WooCommerce:

* https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/woocommerce-gateway-stripe.php#L11
* https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/readme.txt#L67

**Expected behavior**
That supported WooCommerce versions are accurately reflected in the readme.

**Additional context**
For addition context: #20622642-hc

**Comment by dwainm** [comment]
Hi @RiaanKnoetze, This issue is being handled in the next sprint:
https://github.com/woocommerce/woocommerce-gateway-stripe/issues/833

I've added your PR to the todo list to be merged there. I'll close this issue as a duplicate.
