### ISSUE TITLE
Remove SCRIPT_DEBUG support, remove unminified JS, and add link to this repo to readme.txt

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1184]
Reduce the size of the plugin, meet the requirements of the guidelines

p7bbVw-3Iv-p2

cc @DanReyLop

**Comment by mattallan** [comment]
Closing this in favour of cleaning up stale open issues.

FWIW, the unminified JS files shipped in our Stripe extension amount to ~70KB which hasn't posed as an issue yet.
