### ISSUE TITLE
FPX for Malaysia 

### ISSUE THREAD

**Issue by bmccotter** [woocommerce/woocommerce-gateway-stripe#1186]
**Is your feature request related to a problem? Please describe.**

Unlocking FPX as a payment method for Malaysian merchants. It is now GA with Stripe.

Docs: https://stripe.com/docs/payments/fpx 

**Additional context**
Ideas Board: https://woocommerce.com/feature-request/add-fpx-support-for-stripe-plugin-malaysia/

**Comment by RiaanKnoetze** [comment]
Also raised at https://wordpress.org/support/topic/fpx-payment-method-for-malaysia-not-available-in-woocommerce-2/

**Comment by gitdel** [comment]
When will FPX for WooCommerce Stripe Payment Gateway be available?

**Comment by reykjalin** [comment]
We've put this feature on our roadmap, and it remains a priority, but unfortunately it doesn't make the cut to immediate priorities right now. There are some higher priority issues we're currently focused on.

Thank you all for communicating your interest! ❤️

**Comment by EquilibriumTechx** [comment]
When will this be set into motion, it has been 1 year,

**Comment by bmccotter** [comment]
Hello @EquilibriumTechx, we're working to implement more payment methods that require a bit of refactoring work of the plugin. This is in progress and we hope to have support ready by the end of the year. We're partnering with Stripe on this effort and will keep you posted on the availability of FPX as soon as we know.

**Comment by amElnagdy** [comment]
36353385-hc - a merchant is looking forward to this implementation.

**Comment by dougaitken** [comment]
It would be great to have you add your vote for this feature to the Feature Request: [Add FPX support for Stripe plugin (Malaysia)](https://woocommerce.com/feature-request/add-fpx-support-for-stripe-plugin-malaysia/) - this way the team can understand the demand.

Currently there is no progress to share around this feature.
