### ISSUE TITLE
Inconsistent Error Code Messages

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gateway-stripe#1187]
See here: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8ed8a390e3a7e782d775d7c29b1c38b8a10c0eb0/includes/class-wc-stripe-helper.php#L209-L226

There is a mixture of "card" and "card's" wording. All of these notices would work with "card", for example:

> The card\'s expiration month is invalid.

Becomes:

> The card expiration month is invalid.

This also avoids the need to escape the `'` in the translation string.

**Comment by v18** [comment]
Closing as a `wontfix` - the original wording was flagged as less awkward.
