### ISSUE TITLE
no order note on failed transaction - no order status change

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#119]
#### What I expected
To have some sort of indication why an order is not in a paid status when using Stripe

#### What happened instead
A CC was declined (evidenced in the Stripe log). The order remained in a pending status with no indication as to why

#### Steps to reproduce the issue

Reference #18 as this is similar - the old version set an order note and marked the order as processing.

1. Do a test purchase with Stripe and card number 4000000000000002 which produces a declination.
2. The card is declined
3. The order status is "pending" when it should be failed
4. There is no order note indicating anything

@roykho 

source ticket: 504708-zd-woothemes

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by corsonr** [comment]
related? 510796-zd-woothemes
