### ISSUE TITLE
Apple Pay and Subscriptions error - "Create account password is a required field" 

### ISSUE THREAD

**Issue by eurello** [woocommerce/woocommerce-gateway-stripe#1194]
### Affected ticket(s)

#2960364-zen

#### What I expected

Apple Pay to be offered as a functional checkout method. 

#### What happened instead

When using Stripe/Apple Pay and subscriptions together, an error message displays on the cart, "Create account password is a required field." @jessepearson was able to repro this on his test site. 

![Screen Shot on 2020-05-12 at 13-03-04](https://user-images.githubusercontent.com/8698879/81720474-150bc000-9444-11ea-8b2d-fe421c617592.png)

The customer also reports that the Apple Pay button is hidden on their product page, but we weren't able to repro that: 

![Screen Shot on 2020-05-12 at 13-03-30](https://user-images.githubusercontent.com/8698879/81721477-87c96b00-9445-11ea-8642-b5dbbd0b5f68.png)

#### Steps to reproduce the issue

Add a simple subscription and the Apple Pay option. Attempt to purchase the subscription using Apple Pay and you will see the error on checkout. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by jessepearson** [comment]
Just to note, the below doc also references that Apple Pay and Subs are not compatible, but in reviewing the code it seems like they are:

* https://docs.woocommerce.com/document/accepting-apple-pay-woocommerce/#section-3
* https://docs.woocommerce.com/document/accepting-apple-pay-woocommerce/#section-13
* https://docs.woocommerce.com/document/accepting-apple-pay-woocommerce/#section-16

Code:
* https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.3.3/includes/payment-methods/class-wc-stripe-payment-request.php#L415-L417

**Comment by dougaitken** [comment]
As a workaround, if you enable `Automatically generate customer password` via WP Admin > WooCommerce > Settings > Accounts & Privacy > Account creation, then this warning is not shown.

I've tested and confirmed this myself independent of this Issue.

**Comment by mbruschi** [comment]
According to the description [here](https://docs.woocommerce.com/document/accepting-apple-pay-woocommerce/#section-16) shouldn't the Apple Pay button automatically be hidden if a non-one-time purchase is in the cart?

> Since payment data cannot be saved with Apple Pay, the Apple Pay button will only be available for one-time purchases, it cannot be used for recurring payments or a payment that’s saved and billed later.

**Comment by dougaitken** [comment]
As a note, this document - https://docs.woocommerce.com/document/accepting-apple-pay-woocommerce - is generally for the SkyVerge payment gateways and as mentioned throughout it, the Stripe payment gateway is separate.

**Comment by jessepearson** [comment]
I just had another chat asking if Apple Pay and Subs work together and the SkyVerge docs come up in Google vs the Stripe doc: https://docs.woocommerce.com/document/stripe/#section-23

Just wanted to add the proper doc here for informational purposes.

**Comment by leonclaus** [comment]
Are there any plans to resolve this? We are currently facing this problem and we do not really want to enable automatic password creation for all user accounts just to enable the payment requests API.

IMO, if account creation is required either through enforcement from inside WooCommerce or through purchasing a subscription, purchases via Payment Request API/Apple Pay should automatically fallback to the "autogenerate password" behavior thats already present inside WooCommerce. That would be the best of both worlds.

**Comment by v18** [comment]
Related to #1352

**Comment by contemplate** [comment]
Would really like to see this request as a solution https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1537 as we desire to allow the customer to set their password at checkout rather than have it auto-generated.

**Comment by ricardo** [comment]
@contemplate unfortunately there's no way to do it through the Payment Request API flow. We would need to guide the users to the authentication/account creation page, and then allow them to pay after authentication.

**Comment by contemplate** [comment]
Thanks for the quick response @ricardo and hoping the guided Account Creation can become a reality as I have numerous clients looking for this with subscription purchases.  In the meantime I'll have to test the auto generated password approach.

**Comment by leonclaus** [comment]
@ricardo Wouldn't it be possible to make the account creation optional? That would mean that users could set their own passwords when doing a manual checkout and if they dont, they would receive it via email. As far as we have looked through the code, that would be really easy to implement, backwards compatible if you would just create another wp_option for passwords being optional and keep the current wp_option for autogeneration and account creation being mandatory, and it would enable the Payment Request API for all use cases. We have been thinking about creating a PR to woocommerce core for this as we are subscription based and think that its an essential feature, but we currently don't have the time for it and we are not sure whether it is a wanted feature.

**Comment by ricardo** [comment]
There are settings in WooCommerce > Settings > Accounts & Privacy to manage account creation and guest checkout, but WooCommerce Subscriptions overwrites that and makes authenticated checkout mandatory.

> As far as we have looked through the code, that would be really easy to implement, backwards compatible if you would just create another wp_option for passwords being optional and keep the current wp_option for autogeneration and account creation being mandatory, and it would enable the Payment Request API for all use cases.

I guess it would be an interesting feature for WooCommerce Subscriptions or WooCommerce core, but I don't see this as the payment gateway's responsibility. We must follow what's enabled in Accounts & Privacy, but perhaps improving it as proposed in #1537 would be the way to go.

**Comment by SIUdesigns** [comment]
Latest version changelog states the following:

5.3.0 – 2021-07-21

Fix – Disable Payment Request Buttons when order has to be split into multiple packages because Payment Requests do not support that use case.
**Tweak – Payment request button should guide users to login when necessary.**
