### ISSUE TITLE
!BROKEN! on AWS Cloudfront.

### ISSUE THREAD

**Issue by shanemarsh28** [woocommerce/woocommerce-gateway-stripe#1195]
Update by @dwainm:

Add a filter is_valid_request return value . Pass along the function parameters.

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/70640ab3a2dd3dfc4a700dee3dc2393fcaca95a7/includes/class-wc-stripe-webhook-handler.php#L93-L95

----

**Original Issue**
Plugin has conflict with Amazon Cloudfront CDN whereby the correct User Agent is forcefully rewritten by the CDN. On all requests, the User Agent is modified to "Amazon Cloudfront".  This causes all webhook requests to return 400 even when correctly setup by failing on line 93 of /includes/class-wc-stripe-webhook-handler.php.

If I comment out lines 93-95 I get expected behaviour. 

The Cloudfront specification can be found here: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html

Commenting out the three lines is sufficient but it’s not a long term fix. Please can you introduce an exception or a way of being able to disable this specific security measure.

Wordpress.org support ticket: https://wordpress.org/support/topic/cloudfront-user-agent/#post-12826607

**Environment (please complete the following information):**
 - WordPress Version - all
 - WooCommerce Version - 4.0.1
 - Stripe Plugin Version - 4.3.3
 - Browser [e.g. chrome, safari] and Version - all browsers

**Comment by dougaitken** [comment]
Hey @shanemarsh28 Thanks for posting! I've brought this up with the developers and we'll look at possible solutions. I can't put a timeline on this but this thread will be updated with any comments going forward.

Internal discussion w/ @RadoslavGeorgiev - p1589456342038300-slack-CHG7MTCAF

Related code: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/70640ab3a2dd3dfc4a700dee3dc2393fcaca95a7/includes/class-wc-stripe-webhook-handler.php#L93-L95

**Comment by shanemarsh28** [comment]
Thank you. Even wrapping the three lines in a filter hook would be sufficient.

**Comment by shanemarsh28** [comment]
Do you have an ETA as to when this update will be added to a release? Currently I can only apply updates manually for your plugin.

**Comment by shanemarsh28** [comment]
Can you please give an ETA as to when this will be addressed? This issue has been open for 6 months.

**Comment by Zetanova** [comment]
I have the same problem and made a bit better workaround for apache server

On the server enable mod_headers
```
sudo a2enmod headers
sudo service apache2 restart
```

In the .htaccess of the webspace add:
```
<IfModule mod_headers.c>
  <If "%{QUERY_STRING} =~ /wc-api=wc_strip/">
    RequestHeader set User-Agent "Stripe"
  </If>
</IfModule>
```

**Comment by shanemarsh28** [comment]
Sadly Zetanova for me a workaround for our Nginx/FastCGI stack isn't nearly as easy.

Come - it's 8 months already!! Getting frustrated now.

**Comment by Zetanova** [comment]
@shanemarsh28 

Add in your nginx config something like:

```
location / {
    fastcgi_pass   unix:/path/to/socket;
    fastcgi_index  index.php;
    
    //add this
    if ( $args ~ "wc-api=wc_strip" ) {
        fastcgi_param  HTTP_USER_AGENT "Stripe";
    }

   //or this
    if ( $arg_wc_api = "wc_strip" ) {
        fastcgi_param  HTTP_USER_AGENT "Stripe";
    }
}
```

More info:
https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/

**Comment by shanemarsh28** [comment]
Ah that's very helpful thank you. My last attempt it got as far as this but wasn't having much luck. I'll try your solution as it's cleaner. 

```
set $stripeagent $http_user_agent;
if ($arg_wc-api != "") { set $stripeagent "Stripe"; }
fastcgi_param HTTP_USER_AGENT  $stripeagent;
```

**Comment by shanemarsh28** [comment]
Sorry to update further, just reminded myself why I tried it the way I did. fastcgi_param can't be inside an if.

**Comment by Zetanova** [comment]
map for the rescue

```
map $arg_wc_api $new_user_agent {
     default $http_user_agent;
    'wc_strip' "Stripe";
}

//maybe this one 
map $arg_wc-api $new_user_agent {
     default $http_user_agent;
    'wc_strip' "Stripe";
}

location / {
    fastcgi_pass   unix:/path/to/socket;
    fastcgi_index  index.php;
    
    //add this
    fastcgi_param  HTTP_USER_AGENT $new_user_agent;
}
```

**Comment by shanemarsh28** [comment]
Nope - none of those options work. Trying to override User-Agent headers in Nginx is just a waste of time. Also, using User-Agents as a security measure is amature, inconvenient and easy to spoof (provided you don't use Nginx!).

Now, please, a developer, any developer, is beg of you, ffs and with cherries on top, ho ho f***ing ho - FIX THE PLUGIN!
Thank you please - love you forever.

**Comment by mikedubinsky-odb** [comment]
I am also experiencing the issue as the poster described. The workaround of commenting out those lines of code or checking for the CloudFront user agent (as seen below) fixes the issue. Is there a better way?
`if ( ! empty( $request_headers['USER-AGENT'] ) && !(preg_match( '/Stripe/', $request_headers['USER-AGENT'] ) || preg_match( '/Amazon CloudFront/', $request_headers['USER-AGENT'] )) ) {
    return false;
}`

**Comment by mikedubinsky** [comment]
I am also experiencing the issue as the poster described. The workaround of commenting out those lines of code or checking for the CloudFront user agent (as seen below) fixes the issue. Is there a better way?
`if ( ! empty( $request_headers['USER-AGENT'] ) && !(preg_match( '/Stripe/', $request_headers['USER-AGENT'] ) || preg_match( '/Amazon CloudFront/', $request_headers['USER-AGENT'] )) ) { return false; }`

**Comment by smdev0925** [comment]
I don't think the the developers have any interest whatsoever in helping with this, despite marking the issue with a high priority more than 9 months ago.

**Comment by smdev0925** [comment]
Is this project being maintained?

**Comment by gabriserra** [comment]
Hi, the same issue here. Furthermore, the title of the issue is not helping at all. I mean it seems something not so important to "add a filter", while solving an important issue for all people using AWS well it's different.

However, I'll try to go ahead with the nginx config path. @shanemarsh28 did you try to do a PR? Maybe they will accept it in case.

**Comment by smdev0925** [comment]
> However, I'll try to go ahead with the nginx config path. @shanemarsh28 did you try to do a PR? Maybe they will accept it in case.

Hi Gabriserra, I didn't create a pull request because I didn't think the developer needed one to simply remove three lines of code. :)

**Comment by gabriserra** [comment]
@shanemarsh28 I agree with you. However, instead of removing the three-line check, we provided a solution as suggested by you and other guys, wrapping it up in a filter. Maybe @RadoslavGeorgiev can take into account this #1483 PR?

**Comment by smdev0925** [comment]
> @shanemarsh28 I agree with you. However, instead of removing the three-line check, we provided a solution as suggested by you and other guys, wrapping it up in a filter. Maybe @RadoslavGeorgiev can take into account this #1483 PR?

I much prefer your solution although it's well known that User Agents can be easily altered and it's bad practice to use them as a security measure. This is why I'd actually recommend those lines are removed.

Lets hope they do something but with 213 open tickets dating back to 2018, I am not holding my breath.
