### ISSUE TITLE
Add customer billing details when processing payment

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#1206]
**Describe the bug**

This came from a forum thread around "India Exports" - https://wordpress.org/support/topic/passing-product-description-billing-and-customer-name-to-stripe/

Details here https://stripe.com/docs/india-exports

When a transaction is processed, the customer name and billing address are passed into the payment intent but those details are not added to the customer record in Stripe.com

**To Reproduce**
1. Make a purchase on a site using Stripe extension
2. Look at the Billing details via the customer record here – https://dashboard.stripe.com/customers/ 
3. Notice no customer address listed
4. Have the store set as INR and make the purchase to a billing address outside of India
5. See error - Non-INR transactions must supply name, address and description” to stripe for payments outside India

**Expected behavior**

Any supported country in `wc_stripe_supported_countries` should be able to process transactions.

**Comment by ravirnjn88** [comment]
Facing same problem. Any patch for it which I can apply until it is fixed.

**Comment by vbelolapotkov** [comment]
The related internal conversation is here: p1589962702049300-slack-CHG7MTCAF

**Comment by therealshubham** [comment]
When can I expect the issue to be resolved? Also yes, the description is the same as I told on the forums...

**Comment by dougaitken** [comment]
This snippet has been mentioned by someone in the forums - https://gist.github.com/kdctek/c00214cdc9ae499137f8a16cbfa5c7f8 and also here - https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1284#issuecomment-673727338

**Comment by robertocyrino** [comment]
We've received a similar request in 27921653-hc.

The specific use case is: the merchant offers a subscription with a free trial, which allows the customers to checkout without adding a payment method. It is still possible to add one after the checkout and before the first renewal.

If using Stripe, the payment method can then be manually added via My Account (during trial, thus outside checkout circuit), but the Billing Information will not be passed together with the CC info:

![https://d.pr/i/usavpO](https://d.pr/i/usavpO+) 
Full Size: https://d.pr/i/usavpO

To note that the method via My Account was added for an account with addresses registered for the customer, but outside checkout.

The merchant's main concern is fraud prevention, based on this official page for **Preventing disputes and fraud** from Stripe: https://stripe.com/docs/disputes/prevention

**Comment by ricardo** [comment]
I didn't test this thoroughly, but I think the error for Non-INR transactions is fixable by adding billing metadata to the payment intent.

We probably need to add billing args [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/2d7e3f2fa642a3d3fe427b9af7ba6c5c2a7e0375/includes/class-wc-stripe-customer.php#L102) too.

For the disputes concern:
> Some disputes are lost because only the minimum information was required during checkout ([source](https://stripe.com/docs/disputes/prevention))

Stripe _could_ use the payment method billing details for fraud prevention, but I think this still has to do with the payment intent, not the payment method added via My Account or saved at checkout.

**Comment by pssyss** [comment]
the mindfu** continues, no resolution yet

**Comment by pssyss** [comment]
Hello Matt,

Thanks for the update. Does it work now? We lose 2-3 sales a week due to
bad experience with Stripe checkout. Not only do banks decline
transactions, but its also a problem for customers to enter their address
again on stripe after entering it on our website also.

Regards

**Comment by mattallan** [comment]
Hey @pssyss, thanks for checking in on this issue and I'm sorry to hear the loss in sales due to this bug existing.
The changes have been merged into our development branch and will be available in 7.7 which is scheduled to be released in a few days on Nov 9th.
