### ISSUE TITLE
Update Stripe API version to latest 

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#1207]
The current Stripe API version used is [`2019-09-09`](https://stripe.com/docs/upgrades#2019-09-09) - we should look at updating this. 

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-api.php#L17

Changelog - https://stripe.com/docs/upgrades#api-changelog

I don't see any updates between the current version and now but wanted to have this visible and checked so we can reference this.

Context - https://wordpress.org/support/topic/stripe-webhook-errors/#post-12850859

**Comment by vbelolapotkov** [comment]
Thanks for creating this one @dougaitken! It's a good point to keep API version in sync, however after checking the context and Stripe changelog those things doesn't look related.

One thing worth checking is API version in the Stripe [dashboard](https://dashboard.stripe.com/developers). AFAIK it's not updated automatically and ideally should be the same as Stripe API version used in the plugin (`2019-09-09` at the moment).

**Comment by broksonic21** [comment]
Note: it looks like the backend uses the 2019-09-09 version specifically (which could use an update).

The client side (/v1/sources and /v1/tokens) is using the account default as it's not being passed in. Ideally this was specific to match.

**Comment by broksonic21** [comment]
In addition to the backend (2019-09-09) and the client side (no version set), there's also a question of web hook version back in. I filed a ticket w/ questions on that here - https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1305

Sorry for adding to this one, upping this version (we were on a very old version) to avoid any potential future compat worries is high on our agenda.

**Comment by broksonic21** [comment]
One more: looks like backend (php) calls to /v1/payment_intents/ are sometimes using the default version, not a specific version like other backend calls. It would be nice if this plugin were specific on all versions.

**Comment by imclean** [comment]
This is a year old Open ticket, and Stripe are now on 2020-08-27, is there any news when this will be updated to support the latest API which is almost itself a year old? 
Are there any known issues if people update their Stripe API to latest with the plugin? Has this been tested internally?

**Comment by sodecos** [comment]
+1

**Comment by newtlabs** [comment]
+1

**Comment by enoch85** [comment]
@sodecos @newtlabs Please use the '👍'-button in the first post. 

Thanks!

**Comment by hay318** [comment]
+1

**Comment by hay318** [comment]
Any updates?

**Comment by asumaran** [comment]
https://wordpress.org/support/topic/upsells-are-not-working/#post-16606045
6081586-zd-woothemes

**Comment by webbfox88** [comment]
Hello,
Still waiting for your API update, unfortunately, this bug is giving me so many problems with Stripe, I am losing so many payments for this.

Are you able to update or not?
Thank you

**Comment by dougaitken** [comment]
Hey @webbfox88 - can you reach out to us via WooCommerce.com Support so we can help investigate this, please? 

Many of the recent updates to the Stripe API aren't used or related to how our WooCommerce Stripe plugin uses the API so the "outdated" aspect is often cosmetic. 

That said, we do want to make sure that your usage isn't impacted by this in any way so please do reach out if you haven't alread.

**Comment by webbfox88** [comment]
Hello, @dougaitken I have contacted the WooCommerce team and they said to look at this thread and wait for updates. Do I need to contact them again?

Anyway, Stripe costumer care said API must be updated to fix my problem.

**Comment by PiotrKrzyzek** [comment]
Stripe has made many updates to security, process and more lately. As such, we feel it would be wonderful if the WooCommerce Stripe plugin officially moves / upgrades to the latest API (Currently sitting at: `2022-11-15`: https://stripe.com/docs/upgrades#2022-11-15) to ensure future compatibility 'just in case'.

**Comment by gggeek** [comment]
Stripe API is now at 2023-10-16...

ps: I think that this issue correlates as well to 1305. See in particular the details given in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1305#issuecomment-1884563024

pps: changelog between API versions 12019-09-09 and 2023-10-16 is available at https://stripe.com/docs/upgrades#2023-10-16

**Comment by pawelkmpt** [comment]
Can we get any traction on it?

**Comment by adamj7** [comment]
I don't understand why this hasn't been updated. Is the Stripe integration dead in favour of Woo's new Payment plugin? From a business aspect, Stripe is now a direct compeditor to Woo since Woo entered the payment gateway business, so maybe that's the reason why they are doing this - possibly deliberately.

**Comment by shaunkuschel** [comment]
Received another request to update the API on 7841649-zen
