### ISSUE TITLE
Payment Request API: Total should reflect updated shipping

### ISSUE THREAD

**Issue by madmath** [woocommerce/woocommerce-gateway-stripe#121]
#### What I expected

In Payment Request, when selecting a shipping address, the shipping rate is recomputed based on the different store rules and the Total should also be modified by that amount.

#### What happened instead

The shipping rate is updated, but the total does not take into account the shipping rate.

#### Steps to reproduce the issue

* Trigger the Payment Request UI (I used Chrome for Android on [https://woocommerce.paymentrequest.show](https://woocommerce.paymentrequest.show) and "bought" something).
* Choose a shipping option and see that the total does not reflect the shipping rate.

In the following screenshot, the total should be $6.00
![paymentrequestshipping](https://cloud.githubusercontent.com/assets/499162/20995094/ae2b43d0-bcc2-11e6-9dae-0968c77dfc01.png)

#### Notes

Here is an example of how to recompute the "details" (including the total) when the shipping rate changes: https://googlechrome.github.io/samples/paymentrequest/dynamic-shipping/

cc @claudiosanches given the previous contributions.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by claudiosanches** [comment]
@madmath shipping works just fine: https://www.youtube.com/watch?v=3LX_Gp2BDP8
And this is issue is really offensive... "Here is an example of how to recompute the "details" (including the total) when the shipping rate changes", this is really necessary? Are you trying to say what with it?
So test it better and come back with a better tone if you are having some trouble, so I can help you.

**Comment by madmath** [comment]
Hi @claudiosanches 

I'm so sorry I didn't mean to be offensive! I just meant to include as much information as I can. Thanks for your video link, I can see that it works properly in your demo. I will try to figure out what is wrong with my demo store (at https://woocommerce.paymentrequest.show).

**Comment by claudiosanches** [comment]
@madmath Sorry but this is not information, real information about the bug would be showing me your debug.log file or something like it. You are still keeping this offensive.

**Comment by madmath** [comment]
Hi, I have looked into the code and I think I may have found why it's behaving like my screenshot above.

When there is only one shipping option, it is preselected (see [this line](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-payment-request.php#L195)). However, at this point the total is not updated to reflect this option (see my screenshot). 

Therefore, the bug doesn't happen if there are more than 1 shipping options because when the user selects one, the [updateShippingDetails function](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/assets/js/payment-request.js#L114) runs.

The solution would be to update the Total when there is only one shipping option preselected.

**Comment by claudiosanches** [comment]
@madmath ok, submit a Pull Request.
