### ISSUE TITLE
Error A token may not be passed in as a Source. You can convert your token into a Source using /v1/sources

### ISSUE THREAD

**Issue by hicreate** [woocommerce/woocommerce-gateway-stripe#1218]
**Describe the bug**
When creating a remote rquest via Woocommerce REST api to pay for an order I pass parameters to a custom endpoint (order_id, payment_method and payment_token).

instantiating a new WC_Gateway_Stripe() as below:

`$wc_gateway_stripe                = new WC_Gateway_Stripe();
				$_POST['stripe_token']            = $payment_token;
				$payment_result               = $wc_gateway_stripe->process_payment( $order_id );`

However when I try to create the charge I get the error "A token may not be passed in as a Source. You can convert your token into a Source using /v1/sources" even though the Stripe docs say that a token can be a source?

**To Reproduce**
As above

**Expected behavior**
Token should be accepted as source, charge is processed and returned as successful.

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by ATMEGA17** [comment]
Facing the same problem here 
have you figure it out ?

**Comment by hicreate** [comment]
@ATMEGA17 yes I abandoned that process altogether as it isn't SCA compliant, which is why the Gateway patched over it. I wrote a plugin that allows the REST api to leverage the Payment Intents API. I'm in the middle of completing my Medium post on the process that I'll publish this weekend, it's a bit long-winded for GitHub comments.

**Comment by hicreate** [comment]
@ATMEGA17 If it helps, here is an article I just published describing how I used the payment intent API instead of the previous token/charge method >>> article [here](https://medium.com/@dansutherland_48833/woocommerce-rest-api-for-progressive-web-applications-taking-stripe-payments-in-your-pwa-89da3c02aa59?sk=8eeb58df453d2feb7ff6379d50c87ef2)

**Comment by ATMEGA17** [comment]
@hicreate  Thank you for sharing with me i will read your article  
as for me i recently fixed the problem on the PHP side after a lot of debugging   and i receive  payment successful as JSON response 
se here is how i made the request now using PHP 
`if ( $payment_method === "stripe" ) {
				$wc_gateway_stripe                = new WC_Gateway_Stripe();
			
				$_POST['wc-stripe-payment-token']            = 2;
				
	
				$payment_result               = $wc_gateway_stripe->process_payment( $order_id);
				if ( $payment_result['result'] === "success" ) {
					$response['code']    = 200;
					$response['message'] = __( "Your Payment was Successful", "wc-rest-payment" );

					$order = wc_get_order( $order_id );

					// set order to completed
				    if( $order->get_status() == 'processing' ) {
				        $order->update_status( 'completed' );
				    }

				} `
after debugging i noticed that a post value called `wc-stripe-payment-token` is always a constant equals to 2 so ... instead of sending the token i send this constant value and woocommerce will take care of everything after that generate new stripe source and validate the payment.

Thank you

**Comment by slash1andy** [comment]
Marking this as resolved 👍

**Comment by blueorange589** [comment]
Here is another solution

On javascript side you can create a Source instead a Token using
`stripe.createSource(card, {type: 'card',currency: 'usd'}).then(function(result) {});`

and then pass result.source.id as payment token id. Worked well for the case
