### ISSUE TITLE
Duplicate Google Pay button on Checkout page

### ISSUE THREAD

**Issue by nabeel-s** [woocommerce/woocommerce-gateway-stripe#1220]
Priority: High

#### What I expected

I added the following line in functions.php to add the Payment Request Button to checkout page, as per documentation:

`add_filter( 'wc_stripe_show_payment_request_on_checkout', '__return_true' );`

With the 'Branded' button type, this should display the Google Pay button once on the checkout page.

#### What happened instead

For 'Default' and 'Buy' button types, the button is displayed once as expected, but with the 'Branded' button type, the Google Pay button is displayed twice – one on top of each other. 

Please see this screenshot: https://nimb.ws/Utxe92

#### Steps to reproduce the issue

Add the following line in functions.php to add the Payment Request Button to checkout page, as per documentation:

`add_filter( 'wc_stripe_show_payment_request_on_checkout', '__return_true' );`

Set the option 'Payment Request Button Type' to 'Branded' in plugin settings.

Add an item to cart and go to the Checkout page. The Google Pay button appears twice.

**Comment by harryrbrown** [comment]
I am also suffering from this problem on my site - Default and Buy buttons appear as normal but the branded Google Pay button appears twice. The Apple Pay button is however fine.

**Comment by nabeel-s** [comment]
@harryrbrown, thanks for confirming that the issue is reproducible. Hopefully the team will get it fixed soon.

**Comment by dougaitken** [comment]
I was about to replicate this - as mentioned, the specific requirements for this are:

* Filter added to child theme
* `Branded` option for Payment Request button type
* Either `Logo only` or `Text and logo` selected for Payment Request Branded Button Label Format

I keep a site purely for snippets and testing Stripe in this way so you can see that by adding a product to the cart then navigating to the Checkout page - `https://dev.doug.press`

Here is a screenshot showing Safari and Microsoft Edge (for some reason Chrome wasn't playing along and refused to show the button). 
The "extra" Payment Request button shows up after the first loads, they don't load at the same time.

![https://d.pr/i/ftsgEJ](https://d.pr/i/ftsgEJ+)
Image link: https://d.pr/i/ftsgEJ

I've tested with the default snippet and also moving the Payment Request button - it still duplicates the Google Pay button.
For reference, this is the code currently active on my site:
```
/*
* Adds then moves Payment Request button on the checkout page.
*/

add_filter( 'wc_stripe_show_payment_request_on_checkout', '__return_true' );

remove_action( 'woocommerce_checkout_before_customer_details', array( WC_Stripe_Payment_Request::instance(), 'display_payment_request_button_html' ), 1 );
remove_action( 'woocommerce_checkout_before_customer_details', array( WC_Stripe_Payment_Request::instance(), 'display_payment_request_button_separator_html' ), 2 );

add_action( 'woocommerce_after_checkout_form', array( WC_Stripe_Payment_Request::instance(), 'display_payment_request_button_html' ), 2 );
add_action( 'woocommerce_after_checkout_form', array( WC_Stripe_Payment_Request::instance(), 'display_payment_request_button_separator_html' ), 1 );
```

**Comment by nabeel-s** [comment]
> Here is a screenshot showing Safari and Microsoft Edge (for some reason Chrome wasn't playing along and refused to show the button).

I had that issue with Chrome and it was solved after I removed and re-entered the payment method (credit card) in Chrome settings.
