### ISSUE TITLE
Introduce a new filter to manage the display of payment request buttons in cart

### ISSUE THREAD

**Issue by xristos3490** [woocommerce/woocommerce-gateway-stripe#1222]
### Description
The goal here is for third-parties to be able to filter whether or not to show Payment request buttons in cart context. 

Under `WC_Stripe_Payment_Request` class the `display_payment_request_button_html()` method is controlling the display of such buttons in various contexts. 

Currently, there are filters for controlling the display in:
- Product single (see `wc_stripe_hide_payment_request_on_product_page`)
- Checkout (see `wc_stripe_show_payment_request_on_checkout`)
- Cart (none)

**Solution**
My suggestion is to introduce a new boolean filter named `wc_stripe_show_payment_request_on_cart` inside the `allowed_items_in_cart` method in the same class.

**Additional context**
Screenshot of the affected method: https://cl.ly/1f4e00446334

**Comment by reykjalin** [comment]
Tagging with this a `Low` priority for now, since this is an enhancement request and nothing is inherently broken.

@xristos3490 thank you for submitting a PR along with the issue! We really appreciate that ❤️
