### ISSUE TITLE
Duplicate failed order emails

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-gateway-stripe#1229]
**Describe the bug**

In some cases, a webhook handler explicitly sends a failed order email after updating order status to `'failed'` (which also triggers that same email), as pointed out by @DanReyLop in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1108#discussion_r396561802. For instance:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/19e5f4a47d4ad94d4d367a588b3cd4b227c9f80d/includes/class-wc-stripe-webhook-handler.php#L673-L678

Also, the failed email is currently sent when a dispute comes in, even though the order status is _not_ set to `'failed'` – is this desirable?

**To Reproduce**
To trigger the example case above, check out with failure case test card 4000008400001629 then click for successful verification, then verify it fails (as expected) and that _two identical emails_ are sent. (Tested on remote test site so that the emails are properly sent, but can also probably hook into core email module for logging.)

**Comment by csmcneill** [comment]
Reported in 4673427-zen

**Comment by gameDNA-Helix** [comment]
I also experience this issue. Could you please fix?

**Comment by cl0udres** [comment]
Can someone please solve this problem? It's crazy that this issue has been open for 4 years.
