### ISSUE TITLE
Verify that dispute needs response before saying so?

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-gateway-stripe#1233]
When a new dispute event arrives, the order note that is added [[code](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/19e5f4a47d4ad94d4d367a588b3cd4b227c9f80d/includes/class-wc-stripe-webhook-handler.php#L290-L291)] says that "Response is needed." but this isn't true in 100% of cases (for instance, [SEPA Direct Debit disputes](https://stripe.com/docs/payments/sepa-debit#disputed-payments) are always closed immediately).

Should we be checking for `needs_response` or `warning_needs_response` status [[doc](https://stripe.com/docs/api/disputes/object#dispute_object-status)] before messaging this to the merchant?

**Comment by csmcneill** [comment]
Cartes Bancaires disputes also fall into this realm, so work associated with https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3001 is also impacted (cc @wjrosa). Please see pbUcTB-4VQ-p2 for more details.
