### ISSUE TITLE
Payment Request Shipping Should Include Tax

### ISSUE THREAD

**Issue by matty0501** [woocommerce/woocommerce-gateway-stripe#1234]
**Describe the bug**
On the payment request popup for Google Pay, the shipping amount in the order summary and the shipping method picker is showing without tax. On a store that is displaying prices including tax, this is very confusing for customers, as the shipping amount being displayed is not the amount they are being charged. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable Stripe Payment Request Button on a store with taxes and prices displaying with tax
2. Click on the Pay Now payment request button for Google Pay
3. You will see that the Shipping amount is displayed without tax, despite the store settings displaying prices including tax. You will also see that once you enter your shipping address, you can change the shipping method within the payment request popup. The prices shown here are also shown excluding tax.

**Expected behaviour**
It would be expected that if a store is displaying prices including tax that the shipping amounts shown within the Payment Request popup would also display including tax.

**Screenshots**
![stripe-pr-1](https://user-images.githubusercontent.com/17788098/84375076-eb76bd80-abd6-11ea-97ac-24a1bc620aba.png)
![stripe-pr-2](https://user-images.githubusercontent.com/17788098/84375106-f6315280-abd6-11ea-873b-399be9d33c9c.png)

**Environment (please complete the following information):**
 - WordPress Version - 5.4.2
 - WooCommerce Version - 4.2.0
 - Stripe Plugin Version - 4.4.0
 - Browser - Chrome 83.0.4103.97
 - No other plugins installed. Running on Storefront Theme. Same behaviour on TwentyTwenty Theme.

**Additional context**
I've gone through the source code, and have had a play around. The problem is fixed by changing two lines in `/includes/payment-methods/class-wc-stripe-payment-request.php`

**Line 814**
Change from: `'amount' => WC_Stripe_Helper::get_stripe_amount( $rate->cost ),`
To: `'amount' => WC_Stripe_Helper::get_stripe_amount( $rate->cost + array_sum( $rate->taxes ) ),`

**Line 1252**
Change from: `'amount' => WC_Stripe_Helper::get_stripe_amount( $shipping ),`
To: `'amount' => WC_Stripe_Helper::get_stripe_amount( $shipping + WC()->cart->shipping_tax_total ),`

This then displays all the shipping amounts in the Payment Request popup inclusive of tax. All of the other values remain the same (order total for example) and the correct amount is still charged by Stripe, so the above code changes do fix the problem. I suppose that the code could be modified further with a conditional to establish how the store is displaying prices with regards to tax.

**Comment by bernattorras** [comment]
Another customer reporting this issue in 3083013-zen

**Comment by v18** [comment]
Closing in favour of #1064
