### ISSUE TITLE
Wocommerce add_fee() showing on cart and checkout but not working on payment

### ISSUE THREAD

**Issue by RiusmaX** [woocommerce/woocommerce-gateway-stripe#1235]
**Describe the bug**
Hello,
I use the add_fee() function of woocommerce to manually apply a discount to my customers' shopping cart. Everything works fine but at the time of payment Stripe charge the original amount of the order and not the amount indicated at the time of checkout.
This is very critical because customers do not pay the amount indicated at the time of the order.
I use the hook "woocommerce_cart_calculate_fees" to apply my discount.

The function is working, you can check it here : 
https://gist.github.com/RiusmaX/05b83f47b03e7f21ebf38333a74151d1

website link : https://donatello-and-co.com/

**To Reproduce**
1. Create a custom discount function (see my example)
2. The discount is included on the cart & checkout page so the price is correct.
3. Pay with card with Stripe in test mode 
4. After the payement, look the price in the order confirmation, it not include the discount.

**Expected behavior**
Stripe charge the amount with the discount included.

**Screenshots**
The cart : 
![image](https://user-images.githubusercontent.com/10097331/84508687-f7d84480-acc2-11ea-93cc-a813bab50306.png)

The checkout page : 
![image](https://user-images.githubusercontent.com/10097331/84508924-50a7dd00-acc3-11ea-920b-63a02e0ad6db.png)

Order confirmation page : 
![image](https://user-images.githubusercontent.com/10097331/84508977-65847080-acc3-11ea-916f-e5973fa1ca1f.png)

**Environment (please complete the following information):**
 - WordPress Version : 5.4.2
 - WooCommerce Version : 3.9.2
 - Stripe Plugin Version : 4.3.2
 - Browser [e.g. chrome, safari] and Version : Chrome latest stable

I've tried to update but there is no changes.

**Additional context**
I've searched a lot, I couldn't find any similar cases. Maybe it's not a bug, maybe I misunderstood something. I could really use some help solving this problem.
Thank you all for your work.
Thank you in advance for your help.

**Comment by n-dawson** [comment]
This is listed under Stripe but given that the discount isn't reflected in the order confirmation either, have you tested it with other payment gateways?

You have a check in there for the action firing twice, is that an issue you've run into previously? I use similar logic without that check and have never had a discount applied more than once. I wonder if the calculate action gets called more than once during the order process.

**Comment by RiusmaX** [comment]
It was indeed the protection of the recall that was in question, thank you very much ! I had put this method because I had had a problem with multiple additions of promotion. 
That's not the case anymore. 
Thanks again!
