### ISSUE TITLE
Display a default logo for connected stores without a logo

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1237]
Merchants who elect to connect to our Stripe Connect Standard platform but who don't have a logo set in https://dashboard.stripe.com/settings/branding will get a possibly confusing white box:

<img width="856" alt="stripe-account" src="https://user-images.githubusercontent.com/1595739/84709573-45e58600-af17-11ea-8ea1-7ead964d9c03.png">

Perhaps we could display a proper default logo in the box, or suppress the box entirely

**Comment by thenbrent** [comment]
Closing this one due to lack of recent activity. While it is valid UX issue, it's not been a priority in the last 3 years, and unlikely to become one soon. We can reopen and/or create a new issue if this becomes a priority.
