### ISSUE TITLE
Rename master branch to trunk

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1238]
May require an update to woorelease first

**Comment by allendav** [comment]
See also https://github.com/Automattic/woocommerce-payments/issues/736

**Comment by reykjalin** [comment]
I'm setting the priority on this to `High` so we can align with the rest of A8c asap.

**Comment by allendav** [comment]
Added to janitorial trello

**Comment by v18** [comment]
Closing as done.
