### ISSUE TITLE
Apple Pay: "Not a valid URL" notice lacks context

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1240]
A notice with simply "Not a valid URL" can appear if Apple Pay validation fails. Unfortunately, although the notice seems to only appear on the Stripe settings view in wp-admin, it isn't immediately clear what the error means or what the user should do to fix it.

Observed while running a fresh out-of-the-box docker setup.

I recommend rewording the error to something like "WooCommerce Stripe: Apple Pay domain verification failed: (URL) is not a valid URL."

<img width="1154" alt="Screen Shot 2020-06-19 at 2 44 54 PM" src="https://user-images.githubusercontent.com/1595739/85181845-d5eb3e80-b23b-11ea-8f32-e8fa93211893.png">

**Comment by reykjalin** [comment]
I'm setting the priority on this to `Low`. I'm not sure exactly what the `Partner Fixed Due Date` label is for, so if this should be a `High` priority issue, please feel free to change it @bmccotter 🙂 

cc @allendav

**Comment by bmccotter** [comment]
Hey @reykjalin we have a partnership with Apple Pay that starts at the end of this month, so we will need to prioritize ensuring Apple Pay bugs/fixes etc.. are addressed. This should be high.

**Comment by dechov** [comment]
That message comes from the domain registration response [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f85e41d95f9c9366beaa4942cdb1726f88e796e2/includes/class-wc-stripe-apple-pay-registration.php#L159) and is rendered [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f85e41d95f9c9366beaa4942cdb1726f88e796e2/includes/class-wc-stripe-apple-pay-registration.php#L260). At a minimum, the latter line should be modified to contextualize the notice, but we could also just combine with the notice below it.

**Comment by bmccotter** [comment]
I'm aligned with this.
