### ISSUE TITLE
Early renewal modal unresponsive and fails to redirect when Stripe is not the payment method

### ISSUE THREAD

**Issue by jorgeatorres** [woocommerce/woocommerce-gateway-stripe#1246]
**Describe the bug**
When using the modal to early renew a subscription (WooCommerce Subscriptions) that is tied to a gateway other than Stripe, the modal fails to redirect the user to the correct URL after processing the payment. Instead, the user is stuck with the modal in a blocked unresponsive state:

<img width="505" alt="Screen Shot 2020-06-26 at 16 38 37" src="https://user-images.githubusercontent.com/184724/85894711-ac965980-b7cb-11ea-9157-4360baa6be8e.png">

The JavaScript console shows that some JSON parsing errors are the reason:

<img width="485" alt="Screen Shot 2020-06-26 at 15 03 06" src="https://user-images.githubusercontent.com/184724/85894890-f8490300-b7cb-11ea-994f-d6313d0b954f.png">

Besides the UX being less than ideal, this is also problematic because it gives the impression that the renewal didn't come through, when in fact it could have.

**Additional details**
I did some research and found out that in order to handle SCA, Stripe ["hijacks"](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f597353e4a0caf7fd426e53a7f41262ad5ab3cb5/assets/js/stripe.js#L252-L253
) the early renewal modal submit button. This happens even when Stripe is not the associated payment method.

The callback here ([`onEarlyRenewalSubmit`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f597353e4a0caf7fd426e53a7f41262ad5ab3cb5/assets/js/stripe.js#L796-L821
)) performs the request and expects the result to be from the Stripe gateway, which is in JSON format. As such, it [tries to parse](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f597353e4a0caf7fd426e53a7f41262ad5ab3cb5/assets/js/stripe.js#L809) the result, which under most circumstances (and for other gateways) is plain HTML due to the default handling being a redirect.

Because the request is actually executed, the payment might have happened already, but the UI is stuck due to the JS errors.

Even though it'd be good to add a `try… catch` around the JSON parsing code in this function, this is not really a fix and for a proper one Subscriptions probably needs to make the payment method available somewhere in the early renewal modal (maybe through a `data-…` attribute or a CSS class) so that Stripe can figure out whether it needs to override the default handling or not (if the subscription uses a different payment method).

**To Reproduce**
1. Activate WooCommerce Subscriptions, the Stripe payment gateway and [another gateway with proper Subscriptions support](https://docs.woocommerce.com/document/subscriptions/payment-gateways/). I tested with CyberSource.
2. Enable the early renewal modal. Go to WC > Settings > Subscriptions and make sure the following are enabled: "Accept Early Renewal Payments" and "Accept Early Renewal Payments via a Modal".
3. Create and purchase a subscription product using a gateway other than Stripe.
4. Go to My Account > Subscriptions (or "My Subscription") and click "Renew now".
5. Click "Pay Now".
6. Confirm that the modal gets stuck and no indication of what happened is given to the user.
7. Reload the page and confirm that the renewal probably went through (check the next payment dates).
8. Disable the Stripe extension and try 4-5 again, this time confirming that the modal is not stuck and the final redirect occurs.

**Expected behavior**
Early renewal handling to work correctly, redirecting the user back to the subscription after completing the payment.

**Environment (please complete the following information):**
 - WordPress Version: 5.4.2
 - WooCommerce Version: 4.2.2
 - Stripe Plugin Version: 4.5.0.
 - WooCommerce Subscriptions Version: 3.0.5

**Comment by reykjalin** [comment]
Thank you for the detailed issue description @jorgeatorres! The details are very much appreciated 👏 

I'm marking this with a `High` priority for now since my gut feeling is that the amount of merchants using more than 1 gateway with subscriptions is significant. @allendav I'll defer to you on whether we want to change that to `Low`.

**Comment by jorgeatorres** [comment]
@reykjalin: No problem! You'll probably need something in Subscriptions to fix this, a way to differentiate an early renewal via Stripe vs other gateways. Maybe we can add a CSS class or a `data-payment-method` attribute to the button itself so that you can target the proper "Renew now" buttons. I've assigned myself on the Subscription's side of this issue, so do let me know what you need from us and I'll take care of it (that is, if you're not submitting the PR yourselves 😅). Thanks for looking into this!

**Comment by reykjalin** [comment]
>do let me know what you need from us and I'll take care of it

Thank you @jorgeatorres! I'm not sure when we'll get to solving the issue on our end and would have to defer to @allendav on that one, but we'll definitely be in touch once we do start working on this! 😄

**Comment by ryanengland** [comment]
@jorgeatorres thanks for posting such a detailed bug report. We're in exactly the same boat using PayPal and this Stripe bug is causing confusion with users when they attempt to renew early - we've had several cases of users accidentally renewing twice, for example.

@reykjalin and @allendav it looks like the breaking change was introduced in this pull request https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1084 and in particular the changes to stripe(.min).js here: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1084/files#diff-1f8d151e9960b8b51bc43b4a2aba09d4 - perhaps the bind in lines 247-249 needs to be wrapped in an "if paymentmethod is stripe" to avoid interfering with other payment methods.

Do you accept public pull requests? If so, happy to give it a go!

**Comment by dechov** [comment]
@ryanengland We absolutely do look at / accept contributions, and you're welcome to go ahead and open a PR, if you're willing. Thanks!
