### ISSUE TITLE
Boleto support

### ISSUE THREAD

**Issue by jffaria** [woocommerce/woocommerce-gateway-stripe#1247]
Hello folks,

Stripe is opening up a private beta for Boleto payments in Brazil (very popular payment method down here) and I have been contacted by them to join, so I would like to ask you how do you guys work regarding new payment methods introduced by Stripe, if you are already aware of Boleto and/or have it somewhere in your roadmap, and, finally, how should I go about contributing code if I wanna try my hand at implementing this.

Thanks!

**Comment by allendav** [comment]
Hi @jffaria ! We are working on this now - see #1096

**Comment by jffaria** [comment]
Hello @allendav ! Awesome! I will start by integrating in a very bare bones, separate plugin, just to try it out, and will look to use the boletos support from the official plugin later on. By all means let me know if I can be of any help with #1096  :-)  Cheers

**Comment by reykjalin** [comment]
@allendav is this issue redundant? Should we close it in favor of #1096?

Assuming this issue is not redundant I'm marking it as `High` priority to match #1096.

**Comment by jffaria** [comment]
Hi @allendav @reykjalin Stripe is now finally rolling out Boleto, has there been any developments on it here?

**Comment by allendav** [comment]
Hi @jffaria - not yet - sorry

cc @bmccotter

**Comment by uiliw** [comment]
Hello guys!
Any news about this upgrade?
Here in Brazil Boleto is widely used and im sure Stripe would have a lot of new customers by adding this feature to the plugin! Would be great if it also support recurrence payment like credit card for woocommerce subscription. Instead of automatic payment like CC, it would automatically generate the boleto and send to the user for him to pay.

Thanks!

**Comment by thenbrent** [comment]
Removing the priority label on this so that the priority label can be used for backlog grooming. As a feature, this will be part of roadmap planning.

**Comment by thenbrent** [comment]
Closing this one as [OXXO and Boleto are now available](https://href.li/?https://woocommerce.com/document/stripe/#additional-payment-methods). If there are specific features you would like supported in those payment methods, please vote or open a feature request on the feature request board here: https://woocommerce.com/feature-requests/stripe/#
