### ISSUE TITLE
WP 5.6 - Test with core jQuery update

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1250]
WordPress is rolling the version of jQuery bundled with it. Let's test compatibility. https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/

**Comment by allendav** [comment]
https://wptavern.com/wordpress-5-6-will-ship-with-another-major-jquery-change

**Comment by allendav** [comment]
p7bje6-2Di-p2

**Comment by v18** [comment]
@reykjalin - is this fixed to your satisfaction now?

**Comment by v18** [comment]
Closing this and we can re-open if there are more issues 👍
