### ISSUE TITLE
ApplePay: Domain verification notice, triggered upon activation

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1251]
Add domain verification notice, triggered upon activation

**Comment by dechov** [comment]
Closing, as domain verification is performed automatically, and as of the 4.5.3 release, I don't believe there's any known reason why it wouldn’t work in the vast majority of cases (no matter whether they have yet to load the gateway settings page; see https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1320) – feel free to re-open if necessary.
