### ISSUE TITLE
Add additional countries

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1252]
Bulgaria
Czech Republic
Greece
Cyprus
Malta
<del>UAE (in beta)</del>
Slovenia

**Comment by allendav** [comment]
Note: While UAE is in Beta, it might require a Stripe Connect Standard account on our platform to be available to merchants.

**Comment by allendav** [comment]
Hey @bmccotter - do you know if we should enable Alipay, Bancontact, EPS, Giropay, Ideal, P24, Sofort, Multibanco or Sepa for these countries?

**Comment by bmccotter** [comment]
I think we should enable for the countries that these are supported in.

**Comment by allendav** [comment]
Note: Alipay, Bancontact, EPS, Giropay, Ideal, P24, Sofort, Multibanco and SEPA require only EUR and are not tied to country. 

Of the six countries being added, four are EUR countries but two are not (Bulgaria/BGN, Czech Republic/CZK)
