### ISSUE TITLE
Warn sellers if live and test webhook signing secrets are the same

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1257]
Because they shouldn't be able to do that. Stripe assigns random hashes when you add endpoints in https://dashboard.stripe.com/test/webhooks

**Comment by v18** [comment]
@allendav - would be curious to hear about a case where this issue came up for users? how they did end up with that state?

**Comment by allendav** [comment]
I don't recall the exact merchant/ticket, but they pasted the same secret into both somehow.

**Comment by thenbrent** [comment]
Closing this one due to lack of recent activity. While it is valid potential issue for merchants, it's not been a priority in the last 3 years, and unlikely to become one soon. We can reopen and/or create a new issue if this becomes a priority based on merchant experience.
