### ISSUE TITLE
Missing Filters in `off_session` payment intent requests 

### ISSUE THREAD

**Issue by rfair404** [woocommerce/woocommerce-gateway-stripe#1274]
**Is your feature request related to a problem? Please describe.**
When making a "normal" payment intent, the request data that is sent to stripe's API is filtered via the `wc_stripe_generate_create_intent_request` - the off_session intent creation however lacks a similar filter. In my particular use case, the ability to add an `application_fee` to the intent request is failing, which is causing subscription renewals to incorrectly calculate the renewal order.

**Describe the solution you'd like**
There should be a filter that makes this data filterable by developers.

**Describe alternatives you've considered**
I attempted to use the `woocommerce_stripe_request_body` filter in `WC_Stripe_API` however the order details are not passed to this filter, making it impossible to get context needed from the `$order`.

**Additional context**
I created a PR ~~#1273~~ initially but have recently created a similar PR #1301. Just adding this issue for completeness.

**Comment by reykjalin** [comment]
Marking as `High` priority since we already have a PR in the works.

Thank you @rfair404 for reporting the issue and opening a PR! 🥇

**Comment by rfair404** [comment]
@reykjalin PR #1301 replaces #1273 - just needs review.
