### ISSUE TITLE
Minor: readme.txt missing WooCommerce version support declaration

### ISSUE THREAD

**Issue by conschneider** [woocommerce/woocommerce-gateway-stripe#1282]
Readme.txt missing: 

`WC requires at least: 2.6`
`WC tested up to: 4.3.2`

Source: https://docs.woocommerce.com/document/create-a-plugin/#section-12

**Comment by allendav** [comment]
Hi! The fields are expected and present in the plugin header:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/woocommerce-gateway-stripe.php#L11-L12
