### ISSUE TITLE
India country is not supported in v 4.5.1

### ISSUE THREAD

**Issue by kdctek** [woocommerce/woocommerce-gateway-stripe#1284]
**Describe the bug**
When update the plugin to v 4.5.1 and if the Store's country is India, get the following notice:
`Stripe is not available in your store's country and will not be available for buyers to choose during checkout.`

**To Reproduce**
1. Install/ Update to version 4.5.1
2. WooCommerce > Settings > Select Store country as 'India' _any state_
3. See error

**Expected behavior**
- If the Store Country is 'India' and the Store Currency is 'INR', it should not be blocked because even with the Stripe India Preview account works perfectly.
- The plugin is ineffective only if the Store Country is 'India' but the Store Currently is anything other than 'INR'.

**Environment (please complete the following information):**
 - WordPress Version: 5.5
 - WooCommerce Version 4.3.2
 - Stripe Plugin Version: 4.5.1

**Additional context**
The IN + non-INR issue is happening because of [this](https://stripe.com/docs/india-exports#export-of-goods), the lack of the buyer’s `name`, `billing address`, `shipping address` or `description` is not provided, the payment will **fail**.

In case of IN + INR, the plugin works flawless.

---

> It should not just check compatibility only based on the Store Country, but in combination if Store Country is Indian and also Store Currency is non-India.

**Comment by kdctek** [comment]
Frankly anyone doing business in India with Stripe India Preview account having listed Store Country as **India** and Store Currency as INR, will break the website, even if there is nothing wrong in compatibility and processing. :-(

**Comment by claudiulodro** [comment]
See https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1254
> Removes Brazil, India and the Philippines. Stripe is not supported in the those countries. (Brazil and India are in preview, but not general availability.)

Lots of reports on the support forums from this change also. [This snippet is going to be the easiest solution for now.](https://wordpress.org/support/topic/after-the-latest-update-stripe-is-not-working-on-my-website/#post-13251503)

**Comment by kdctek** [comment]
@claudiulodro thank you for sharing the snippet, as it was breaking our LIVES site, had to come up with a quick solution.
So the snippet will allow India as a supported Store Country.

But still the issue of non-INR export needed resolution, so quickly wrote this [GIST - _kdc-wc-stripein-fix.php_](https://gist.github.com/kdctek/31c73c0464bf4e08b709951022935f7a).

Best of luck to whoever could not previously use Stipe India _Preview_ for non-INR transactions :-)

**Comment by sultan-ul-arefin** [comment]
claudiulodro i also getting same error on Singapore.

**Comment by dougaitken** [comment]
Hi @kdctek 

Thanks for passing on the details about International customers, exports, and Indian Stripe accounts - https://stripe.com/docs/india-exports

I've added your snippet to an open Issue we have to track that specific part - https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1206

As to the warning message: 

>  Stripe is not available in your store's country and will not be available for buyers to choose during checkout.

This is as expected as Claudiu mentioned. 

@sultan-ul-arefin I have tested and confirmed that I don't see this error when setting the Store Address country as Singapore. GitHub isn't a place for support so please do open a thread on the Stripe support forum - https://wordpress.org/support/plugin/woocommerce-gateway-stripe/

**Comment by allendav** [comment]
Thank you all. We're going to release a 4.5.2 that removes the country check.
