### ISSUE TITLE
Action Hook wc_gateway_stripe_process_payment_error ($error, $order) doesn't get fired

### ISSUE THREAD

**Issue by MrBukkitGamer** [woocommerce/woocommerce-gateway-stripe#1287]
I try to move the error message(stripe as example credit card details are wrong ...) to the normal woocommerce error place instead of directly to the input field (in the gateways). 
I found the hook "wc_gateway_stripe_process_payment_error ($error, $order)" on the website, but unfortunately it does not work for me. Nothing happens If i don't fill something in the credit card details.
On stackoverflow they told me to report here, because they said it should normally work. But I could also made a mistake...

I'm trying to add the message to the hook like that:
`add_action( 'wc_gateway_stripe_process_payment_error', 'test_this', 10, 2 );
function test_this($error, $order) {
$woocommerce->add_error( __( 'Your Credit card details are wrong.', 'woocommerce' ) );
}  `
But nothing happens...

**I'm in testmode
WooCommerce Stripe-Gateway : Version 4.5.1 
WooCommerce : Version 4.3.3
Wordpress: 5.5**

Hopefully I'm just making anything wrong...
Greetings,
Justus

**Comment by dwainm** [comment]
Hi @MrBukkitGamer It might be that you're not triggering the error in the correct way. 

We do not offer support via GitHub issue, please reach out to our support team here: https://woocommerce.com/contact-us/
