### ISSUE TITLE
Stripe Checkout allowing form submission without stripe_source

### ISSUE THREAD

**Issue by danielbreves** [woocommerce/woocommerce-gateway-stripe#1293]
**Describe the bug**
I'm seeing payment failures occasionally due to Stripe Checkout allowing form submission without `stripe_source`.

**To Reproduce**
I haven't been able to reproduce the issue, but I can see the symptoms from the logs. The frontend never POSTs the source to stripe, but still allows the customer to submit the form without it, resulting in an order with payment failure. From the logs below it seems the ajax call is made a minute earlier, then the form is submitted, which in theory shouldn't be possible.

```
<customer IP> www.localseeds.com.au - [16/Aug/2020:22:06:18 +0000] "POST /?wc-ajax=checkout HTTP/1.1" 200 169 "https://www.localseeds.com.au/checkout/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" | TLSv1.3 | 25.501 25.548 25.547 - D NC:300000 UP:1
<customer IP> www.localseeds.com.au - [16/Aug/2020:22:07:32 +0000] "POST /checkout/ HTTP/1.1" 200 41730 "https://www.localseeds.com.au/checkout/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" | TLSv1.3 | 2.620 2.658 2.658 - D NC:320000 UP:1
```

**Expected behavior**
The frontend should block the user from submitting the form without a payment source from stripe and the backend should not create an order without a payment source.

**Environment (please complete the following information):**
 - WordPress Version: 5.5
 - WooCommerce Version: 4.4.1
 - Stripe Plugin Version: 4.5.2
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed: dokan-lite 3.0.9, SG Optimizer 5.6.5, Hummingbird 2.5.1

**Comment by reykjalin** [comment]
Hi @danielbreves! 👋 

Thank you for reporting the issue! We'll be sure to look into this 🙂 

I'm tagging this as `Low` priority because we haven't seen many reports of this issue.

**Comment by v18** [comment]
Hi @danielbreves 👋 Have you seen this pop up in your logs recently with the most recent version of Stripe? Does this happen with more than one customer? Are there any clues that would help us figure out how to reproduce this issue?

**Comment by danielbreves** [comment]
@v18 I haven't noticed this issue recently. Feel free to close. Thanks!
