### ISSUE TITLE
Google Pay not showing in mobile

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce-gateway-stripe#1295]
reported in 3275196-zen

**Describe the bug**

While Google Pay button appears fine in desktop, it is not showing on mobile.

**To Reproduce**
1. enable Payment Requests
2. see that button shows in Chrome with saved cc on desktop, but not in mobile

**Screenshots**

Missing on mobile:

![](https://d.pr/i/z4MzV3+)
Link to screenshot: https://d.pr/i/z4MzV3

Payment method added:

![](https://d.pr/i/OUg4DK+)
Link to screenshot: https://d.pr/i/OUg4DK

Shows fine on desktop:

![](https://d.pr/i/i46U2M+)
Link to screenshot: https://d.pr/i/i46U2M

WC 4.4.1
Stripe 4.5.2

**Comment by reykjalin** [comment]
Tagging this as a `High` priority issue since this presumably affects all stores being used on mobile.

@allendav should we bump this to `Critical`?

**Comment by ryanr14** [comment]
Howdy all, any chance for an update for this issue? Ticket is back open again. Thank you!

**Comment by allendav** [comment]
@ryanr14 - I've added it to the next sprint (21) pc4etw-20-p2

**Comment by v18** [comment]
I was able to see the Google Pay button on mobile on the user's site. Closing for now.
