### ISSUE TITLE
The SOFORT Logo is old, since Klarna bought Sofort AG

### ISSUE THREAD

**Issue by antoinehenrich** [woocommerce/woocommerce-gateway-stripe#1297]
The provided SOFORT logo is old. It should be adopted to the new SOFORT Logo.

Not more to say... :-)

**Comment by dougaitken** [comment]
See more details here - https://github.com/woocommerce/woocommerce-gateway-stripe/issues/751#issuecomment-494152398

**Comment by v18** [comment]
Closing this issue in favour of #751
