### ISSUE TITLE
Check out page Credit card section bug with latest edition 4.5.2

### ISSUE THREAD

**Issue by priyankatotala** [woocommerce/woocommerce-gateway-stripe#1300]
Credit card section in my website's checkout page does not take the inputs for credit card number as well as cvv number. 
Also it squished the card entering section. 
So I intsalled the earlier version. 

**To Reproduce**
Add some product in your cart.
1. Go to 'Checkout page'
2. Select 'Credit card' and then you see the bug
Website url
----------------
https://nathanjac.com.au/shop-2/checkout/

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version 5.5.1
 - WooCommerce Version 4.4.1
 - Stripe Plugin Version 4.5.2
 - Browser [e.g. chrome, safari] and Version Chrome, safari, opera
![checkout_page](https://user-images.githubusercontent.com/39249471/92371165-a19e6480-f13e-11ea-91f6-79c6f01f2804.png)

 - Any other plugins installed

**Additional context**

**Comment by duanesteel** [comment]
I am having the same issue. We can't take any payments on our site

**Comment by priyankatotala** [comment]
@duanesteel I have solved this issue now.
There might be some jquery issues in your website. If you right click on your website and check the developer console window, you can see those errors.
Some of your old js files are causing this problem.
Install this WordPress plugin **"Enable jQuery Migrate Helper".** 
This will fix the jquery issues and checkout page will work normally.
