### ISSUE TITLE
Implement a blocking mechanism for LPM redirect payments

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [woocommerce/woocommerce-gateway-stripe#1302]
**Describe the bug**

`WC_Stripe_Order_Handler::process_redirect_payment` performs external calls to Stripe's API in order to complete the payment process for an order. Here's an abstract of how the method works:

```js
if ( order_awaits_payment_based_on_order_status ) {
    retrieve_source()
    create_charge()
    update_order_status()
}
```

The method is called when customers are redirected back from LPMs to URLs like this:

`http://localhost:9082/?client_secret=src_client_secret_CZA5OWmZkoL5LXXXXXX&key=wc_order_fkIFRU65wwmaG&livemode=false&order-received=65&order_id=65&page_id=7&redirect_status=succeeded&source=src_1HRfasIDdSUSdcIr6yRBVsDr&utm_nooverride=1`

It's possible for the same URL to be called twice at the same time. Whenever this happens, the code might proceed after the `order_awaits_payment_based_on_order_status` check more than once. Afterwards duplicate order notes and customer emails will be added/sent.

Reported in 3290928-zen

**To Reproduce**

1. Use a Local Payment Method for a successful purchase.
2. Check the order notes/sent emails. It's possible that they would be duplicated.

I was not able to reproduce the bug, and I do not know why it is happening. However, I think the reason is not important and we should make sure that our code prevents the bug from surfacing.

Note: Sometimes browsers load the page twice. I've experienced this while using Xdebug on certain pages, and I suspect it's connected.

**Expected behavior**

Order notes and emails are only added/sent once.

**Suggested changes**

Add the same payment blocking mechanism that already exists for payment intents to LPM webhooks, and payment processing.

h/t @madeincosmos for reporting this.

**Comment by jessepearson** [comment]
Customer has reached out again in 3444666-zen looking for a status update on this issue.

**Comment by reykjalin** [comment]
Potential similar issue in 5539924-zen
