### ISSUE TITLE
4.5.2: Elevated Risk payment approval moves Virtual product order to Processing status, instead of Completed

### ISSUE THREAD

**Issue by lkraav** [woocommerce/woocommerce-gateway-stripe#1306]
**Describe the bug**
This seems to be a follow-up to https://github.com/woocommerce/woocommerce-gateway-stripe/issues/818

We are using https://woocommerce.com/products/woocommerce-order-status-control/ to auto-complete all Virtual and Download product orders.

Elevated Risk payment approval process should behave in a compatible manner.

Any ideas how to achieve this? Is this subject to OSC plugin implementation instead?

**To Reproduce**
1. Approve a payment in Radar review queue
2. Open relevant order in WC
3. See "The opened review for this order is now closed. Reason: (approved) Order status changed from On hold to Processing." note

**Expected behavior**
Order ends up in Completed status.

**Environment (please complete the following information):**
 - WordPress Version: 5.5.1
 - WooCommerce Version: 4.5.2
 - Stripe Plugin Version: 4.5.2
 - Any other plugins installed: metric ton (150), but we know what we're doing

**Comment by dechov** [comment]
Hi – thank you for reporting this case! It should be addressed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1232/commits/b627ac1e447655290cdf0093966927453604fd16 (meant to restore the status from before the hold), which we expect to review and include in the next release.
