### ISSUE TITLE
Error in install of current build

### ISSUE THREAD

**Issue by CompKingCanada** [woocommerce/woocommerce-gateway-stripe#131]
I get the following error after installing build direct from GitHub 3.1.0

Fatal error: Can't use method return value in write context in /home4/ab3585/public_html/tftr.ca/wp-content/plugins/woocommerce-gateway-stripe-master/includes/class-wc-stripe-apple-pay.php on line 287

Is a release of this build coming soon?

**Comment by CompKingCanada** [comment]
This is happeing on the entire website after installation direct from GitHub

**Comment by roykho** [comment]
No, please use public build.
