### ISSUE TITLE
Apple Pay doesn't work with variation changes and guest users, only with registered

### ISSUE THREAD

**Issue by shillo92** [woocommerce/woocommerce-gateway-stripe#1316]
**Describe the bug**
When a variation changes in a single product view, Apple Pay button does not get refreshed. Instead, an AJAX response in the console of 403 is received. However, with a logged in user, the Apple Pay does get refreshed once a variation is changed.

**To Reproduce**
1. Go to your Wordpress admin and create a Variation Product with at least two attributes.
2. Go to your frontend.
3. Make sure you're log out or enter with Incognito mode in your browser.
4. Go to your Variation Product.
5. Switch to another variation.
6. Console error appears with HTTP code of 403 and a -1 message.

**Expected behavior**
Variations should change and update the Apple Pay button as well so when pressed, users can pay only for the selected variation.

**Environment (please complete the following information):**
 - 5.5.1
 - 4.5.2
 - 4.5.2
 - Safari
 - Elementor, Elementor Pro, Subscriptions, All Products for Subscription

**Additional context**
I understand it's something to do with the _wp_verify_nonce_ function but i've yet figured out. Does anyone else able to reproduce this bug? or it's just me?
I've created this custom function to log the failed nonces. Maybe it can help you realise something I'm missing.
```php
add_action('wp_verify_nonce_failed', function ($nonce, $action, \WP_User $user, $token) {
            $stack_trace = wp_debug_backtrace_summary();
            $request_vars = print_r($_REQUEST,true);
            $user_string = "ID: {$user->ID}, Username: {$user->display_name}, Email: {$user->user_email}";
            ob_start();
            trigger_error(
                "Failed authenticating the AJAX referer for action '$action' with nonce '$nonce'"
                ."for User:\n$user_string\nRequest vars:\n$request_vars\nStack Trace:\n$stack_trace"
            );
            ob_get_clean();
		}, 999, 4);
```

**Comment by vbelolapotkov** [comment]
Hey @shillo92 , thanks for reaching to us. I've tried to reproduce the steps above without success. The button is being updated as expected.

I see you're using Elementor plugins and a couple of the subs related plugins. Have you tried to reproduce the issue with Storefront theme and those plugins deactivated?

**Comment by shillo92** [comment]
> Hey @shillo92 , thanks for reaching to us. I've tried to reproduce the steps above without success. The button is being updated as expected.
> 
> I see you're using Elementor plugins and a couple of the subs related plugins. Have you tried to reproduce the issue with Storefront theme and those plugins deactivated?

Eventually I managed to fix it by asking WPEngine to disable Server Caching. Apparently it's caching also AJAX requests, even though I didn't suspect it cause I saw that other AJAX requests were working just fine. Also, I thought their caching system is smart enough not to cache AJAX requests as well.

So the fix is basically disabling the server's cache. Is there a way from Wordpress backend to bypass AJAX caching? Even if the server uses caching?

**Comment by shillo92** [comment]
Ok. They've add exclusion for the product page. Working properly now.
