### ISSUE TITLE
Send Apple Pay domain verification requests less frequently

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-gateway-stripe#1330]
Currently, when the Payment Request Button setting is enabled (as by default), a request to register the domain with Apple [[source](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/cac73fce691e1344b56651d856ea8e58d89c9ddc/includes/class-wc-stripe-apple-pay-registration.php#L147-L153)] is made on every page load of the gateway settings, even if it has already completed successfully. This slows down the page load, for little reason (particularly after successful verification). The only advantage I see is that it would automatically adapt to a change in domain name (as long as the Settings page is visited).

I think we could either have it only run the domain verification if `apple_pay_domain_set` is not set, or keep track of the domain that was registered and only run it again if it changes.

**Comment by ricardo** [comment]
The extension doesn't trigger domain registration on every settings page load anymore. It triggers only if you enable Payment Request Buttons - I think it's a good approach to keep it that way as way to re-trigger domain registration manually.

#1466 Adds domain registration automatically when the domain name changes.
