### ISSUE TITLE
Update docs to reflect Euro method auto-signup

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1333]
> Stripe supports a number of popular European payment methods including Bancontact, EPS, giropay, iDEAL, Przelewy24, SOFORT, and SEPA Direct Debit. We will be making these payment methods available out-of-the-box for users in all countries excluding Brazil, India, and Malaysia on October 20th. This means that your users will no longer have to manually activate these payment methods from their Stripe Dashboard. They will still be able to check their payments settings to confirm which payment methods are available to them.

**Comment by thenbrent** [comment]
Closing as these docs have been updated since Oct 2020: https://woocommerce.com/document/stripe/#additional-payment-methods
