### ISSUE TITLE
Updated Docs to reflect the right method to test Apple Pay

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce-gateway-stripe#1336]
[Stripe documentation](https://docs.woocommerce.com/document/stripe/#section-26) asks us to follow the instructions in Sandbox Testing to test Apple Pay, while[ Stripe asks to use live cards while in test mode](https://developer.apple.com/apple-pay/sandbox-testing/).

Should both the testing methods work? If yes, update the document to include both the methods.

If what's suggested by Stripe is indeed the right and only working method. Update the document to remove the existing one and add the one suggested by Stripe.

Moved from: p1602738098025300-slack-woo-stripe

**Comment by v18** [comment]
Closing this issue since we no longer reference the Apple sandbox testing doc: https://developer.apple.com/apple-pay/sandbox-testing/

For reference, the new Apple Pay section is here: https://docs.woocommerce.com/document/stripe/#apple-pay

**Comment by AashikP** [comment]
@v18 

Looks like we still have the following in the docs:

---

### Can I test Apple Pay? 

Yes, please follow the link here for instructions [Apple Pay Testing](https://developer.apple.com/support/apple-pay-sandbox/).

---

Also, https://docs.woocommerce.com/document/stripe/#apple-pay doesn't have confirmation on how to test Apple Pay.

---

If you can confirm that [the method recommended by Stripe is the right way to test Apple Pay](https://developer.apple.com/apple-pay/sandbox-testing/), I can update the docs :)

**Comment by dechov** [comment]
Looks like that doc section (now at https://docs.woocommerce.com/document/stripe/#test-apple-pay) has been updated, and no longer links to Apple's doc. We could consider linking to both, so that a live card isn't required for testing (though I personally haven't tested the Sandbox method).
