### ISSUE TITLE
Alipay should allow store currency to be set to CNY

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#1340]
**Describe the bug**

When store currency is set to CNY, Alipay isn't available. Checking with the [Stripe.com documentation](https://stripe.com/docs/payments/alipay), this should be possible.

**Expected behavior**

Store Currency can be set to Chinese yuan (CNY ¥) and Alipay is a payment method for customer to use.

WP Admin > WooCommerce > Settings > Currency options 

**Screenshots**

The message can be seen in #1156 

**Additional context**

I believe this may have changed but it could be this scenario hasn't been thought of. Linked to this, the `Relevant Payer Geography: China` in the payment method settings doesn't make sense since this can be set to something else and Alipay will work; such as setting store address to New Zealand and currency to NZD. 

The extension works as expected going by the [mannual tests](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/tests/manual/stripe-alipay.md) that were set up years ago but it looks like this is now incorrect.

**Comment by allendav** [comment]
`Relevant Payer Geography` - yeah, that should probably be removed or reworded as something like `Principal Payer Geography` - what do you think @bmccotter ?

**Comment by bmccotter** [comment]
sounds good. We should follow Stripe's guidelines here.

**Comment by allendav** [comment]
@bmccotter wrote

> We should follow Stripe's guidelines here.

Good idea. Stripe's documentation uses the term

"Customer Geography"

Let's use that
