### ISSUE TITLE
Bump WC required at least 3.2, if not newer

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1341]
Right now we are at 3.0. To avoid having to test for things like get_base_address (added in 3.1.1) it would be awesome to bump `WC requires at least` to at least 3.2 (released Oct 2017), if not newer.

cc @bmccotter

**Comment by allendav** [comment]
@laurendavissmith - this would be good to consider for our payment gateways and extensions as well

**Comment by thenbrent** [comment]
Closing this is now at `7.4` and I believe this should be handled by `woorelease` automatically now, or at least it's being handled manually better.
