### ISSUE TITLE
Customer email appearing in Stripe Dashboard under 'Name' field - Ver 3.0.6

### ISSUE THREAD

**Issue by PJCwasHere** [woocommerce/woocommerce-gateway-stripe#135]
**What I expected**
The customer's billing name to be entered into the 'Name' field in the Stripe Dashboard.

**What happened instead**
When an order is submitted to Stripe through the plugin, it seems to be entering the customer's email as the 'Name'. This is same as closed issue #95 which indicated it would be fixed in Version 3.0.6

I have Version 3.0.6 and it is still putting the email into the Name Field. Will this be fixed soon? It is very important to capture the name and email. It would be good that the Stripe Name is made up of the Firstname + Lastname. This creates a single field called Customer name.  Whilst fixing, is it possible to also send Firstname and Lastname to seperate Metadata fields as well? We use the seperate Stripe metafields to propogate onto MailChimp and to XERO accounting software.

<img src="https://cloud.githubusercontent.com/assets/3007053/19927064/ff0ba86a-a0ef-11e6-92d5-51741a919b4b.png">

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Please provide steps to reproduce including all settings.

**Comment by roykho** [comment]
Ok so I was able to replicate this however it is not the same issue as #95. That issue is based on Stripe only and this issue you have only happens when using Stripe Checkout ( modal popup ). And unfortunately there is no way to fix this as Stripe doesn't support this using Stripe Checkout. So the next best thing is to add customer name into the meta data.

**Comment by PJCwasHere** [comment]
Thanks for ascertaining that, Roy. But how do I pass the metadata
Firstname, Lastname from WooCommerce via your plugin so that it gets to
Stripe?

Cheers,
Peter

Peter J. Coburn
http://Coburns.biz
Mobile: 0419 330 184
[Message sent remotely via Mobile Phone]

**Comment by roykho** [comment]
You won't need to, its already done and will be in the 3.1.0 release.

**Comment by PJCwasHere** [comment]
Ah, excellent!  Do you have an anticipated timeframe till we see V3.1.0?
