### ISSUE TITLE
Update for PHP8

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1353]
PHP8 will be released on Thursday, November 26, 2020 (Thanksgiving in the US, and the start of the holiday shopping season). Ensuring this extension works well with PHP8 is a high priority.

Task list in progress:

- [x] Test with PHP8 to identify any problems
- [x] Fix PHP8 related problems
- [ ] Update Travis to include PHP 8 in the versions of PHP to be tested with

Related:

- https://github.com/woocommerce/woocommerce/issues/27674

**Comment by kalessil** [comment]
Approved the related PR and created a follow-up ticket for adding PHP8 build environment to Travis: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1382 later.

**Comment by v18** [comment]
@dechov - hey was this issue re-opened for the Travis build only, or were there some more PHP8 compatibility tasks for the plugin itself?

**Comment by dechov** [comment]
Ah, Travis build only – I'd overlooked that @kalessil had opened a separate issue for that.

I believe the PHP8 compatibility is complete. I myself had only tested initial configuration and a single checkout – thanks again @kalessil for the additional testing.
