### ISSUE TITLE
Update travis.yml

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1354]
A few warnings from config validation:

- root: deprecated key sudo (The key `sudo` has no effect anymore.)
- root: missing dist, using the default xenial
- root: missing os, using the default linux

<img width="1345" alt="Screen Shot 2020-10-29 at 2 59 58 PM" src="https://user-images.githubusercontent.com/1595739/97637243-85f56300-19f7-11eb-9113-abcd288a7b82.png">

WooCommerce uses dist: xenial, let's use that too

linux works for os, let's keep using that?

**Comment by diegocurbelo** [comment]
Replaced with GitHub Actions in #1449
