### ISSUE TITLE
Don't attempt to submit level 3 data for non-US merchants

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1366]
Level 3 data is only supported for US merchants.  According to Stripe, while we shouldn’t get a hard error from sending it for non-US merchants, they still recommend against it.

**Comment by allendav** [comment]
3481034-zd

**Comment by htdat** [comment]
3503397-zen

**Comment by guicmazeredo** [comment]
3562903-zd
