### ISSUE TITLE
Apple Pay processing

### ISSUE THREAD

**Issue by NathanDillon** [woocommerce/woocommerce-gateway-stripe#137]
Apple Pay is fine all works besides 2 issues, shipping address keeps going to red exclamation mark and when I change it for a not shippable product when I use Touch ID to complete the purchase it keeps on saying processing and won't complete

**Comment by roykho** [comment]
You should check on your website without using Apple pay to make sure your shipping is setup correctly first. It is possible you misconfigured your shipping in WooCommerce.
