### ISSUE TITLE
Statement Descriptor doesn't accept periods

### ISSUE THREAD

**Issue by broksonic21** [woocommerce/woocommerce-gateway-stripe#1374]
**Describe the bug**
Prior to Version 4.5.4 (or 4.5.5) we had a statement descriptor setup at Stripe that had a ".COM" at the end.

With 4.5.4 (or 4.5.5), there's now a UI option in the plugin for a statement descriptor. We put our domain name with a .com at the end, but it shows up on cards with a space COM instead of dot com.

Example:

DOMAIN.COM in the UI field in the plugin
statement shows "DOMAIN COM" (without the quotes)

Even deleting that value from the plugin doesn't fix it to get back to the stripe setup - it instead keeps the space version from now on.

This is a big issue for our marketing team.

**To Reproduce**
1. Update to 4.5.4 or 4.5.5
2. Go to Stripe Settings under WooCommerce Payment
3. Fill in the Statement descriptor with a .com
4. Place an order
5. Look at your credit card statement autos

**Expected behavior**
Should show ".com" - that's a valid character

**Environment (please complete the following information):**
 - WordPress Version: 5.5.3
 - WooCommerce Version 4.7.0
 - Stripe Plugin Version 4.5.5
 - Browser [e.g. chrome, safari] and Version - any

**Comment by broksonic21** [comment]
Note: This might be a stripe bug itself vs a plugin.

In Stripe, the descriptor does have a dot, but not on the credit card statement.

**Comment by dechov** [comment]
Thank you for reporting. This is likely due to the changes on Stripe's end, as you note. The statement descriptor has been a gateway setting in the extension for years, and is unchanged in recent releases.

Closing, but definitely feel free to reopen if you notice discrepancies between the extension and what appears in Stripe.
