### ISSUE TITLE
Version 4.5.4 function name conflict

### ISSUE THREAD

**Issue by paymentplugins** [woocommerce/woocommerce-gateway-stripe#1375]
**Describe the bug**
In version `4.5.4` of this plugin, a new function `wc_stripe` was added. That function name conflicts with a function of the same name located in the plugin [Stripe For WooCommerce](https://wordpress.org/plugins/woo-stripe-payment/)

**To Reproduce**
1. Download and active Stripe For WooCommerce and WooCommerce Stripe Gateway
2. On the plugin activation page you should see an activation error showing the function name conflict

**Expected behavior**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
 - WordPress Version 5.5.3
 - WooCommerce Version 4.7.0
 - Stripe Plugin Version 4.5.4+
 - Any other plugins installed: Stripe For WooCommerce

**Additional context**
If possible, please rename your `wc_stripe` function to something that does not conflict. I am also looking in to changing my function name but it has been in use since the plugin's creation and so there is a high likely hood that developers have referenced the `wc_stripe` function in their custom development.

Kind Regards,

**Comment by paymentplugins** [comment]
Hi Team,

There are quite a few reports of this issue now in the Wordpress.org support threads. I am planning a release today so I'll be updating the function `wc_stripe` to `stripe_wc` within my plugin. Please do not use the function name `stripe_wc` in future releases of your plugin.

There will still be references to the `wc_stripe` function out in the wild where developers have added custom code to integrate. For that reason I am adding a check where the `wc_stripe` function will be loaded if your plugin is not active. That means it's still a good idea if you rename your function to something else.

Kind Regards,

**Comment by katinthehatsite** [comment]
I have another customer that I was working with and they got the same issue as reported: https://wordpress.org/support/topic/installation-breaks-website/ however, they did not have Stripe for WooCommerce from `paymentplugins` installed. The exact error that happens upon activating Stripe:

Uncaught Error: Call to a member function get_base_city() on null in

/public/wp-content/plugins/woocommerce-gateway-stripe/includes/connect/class-wc-stripe-connect-api.php:209 Stack trace: #0
/public/wp-content/plugins/woocommerce-gateway-stripe/includes/connect/class-wc-stripe-connect-api.php(99): WC_Stripe_Connect_API->request_body(Array) #1 
/public/wp-content/plugins/woocommerce-gateway-stripe/includes/connect/class-wc-stripe-connect-api.php(58): WC_Stripe_Connect_API->request('POST', '/stripe/oauth-i...', Array) #2
/public/wp-content/plugins/woocommerce-gateway-stripe/includes/connect/class-wc-stripe-connect.php(50): WC_Stripe_Connect_API->get_stripe_oauth_init('https://lockitu...') #3
/public/wp-content/plugins/woocommerce-gateway-stripe/includes/admin/stripe-settings.php(23): WC_Stripe_Connect->get_oauth_url() #4 /sr
/public/wp-content/plugins/woocommerce-gateway-stripe/includes/connect/class-wc-stripe-connect-api.php on line 209
