### ISSUE TITLE
Add CVC (card verification code) re-collection

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#1380]
CVC (card verification code) re-collection: You can now use Stripe Elements to re-collect a CVC when accepting a payment with a saved card. Having the correct CVC can be a strong signal that the charge is being made by the cardholder.

@bmccotter @thenbrent - I think this should be a setting, enabled by default. Although most merchants will welcome the likely reduction in fraud/disputes, some may balk at the slightly more complicated checkout experience for their buyers using saved cards. What do you think?

https://stripe.com/docs/payments/save-during-payment

**Comment by bmccotter** [comment]
> I think this should be a setting, enabled by default. Although most merchants will welcome the likely reduction in fraud/disputes, some may balk at the slightly more complicated checkout experience for their buyers using saved cards. What do you think?

I agree. I think that it will become table stakes in the industry in a short amount of time.

**Comment by jrick1229** [comment]
Requested: https://wordpress.org/support/topic/ask-for-cvv-on-saved-cards/

**Comment by SivaArkwell** [comment]
Is this still not a feature? Literally every single Woocommerce store in the entire world is insecure, all you need to be is an Admin and you can just login as anyone and use their saved credit card info to bill them for anything. That is absolutely outrageous, bordering on negligence to be honest.

**Comment by thenbrent** [comment]
Closing this due to lack of demand and activity the last 3 years. The [feature request board](https://woocommerce.com/feature-requests/stripe/#) is the best way to track popularity and help determine priority in our roadmap for features like this, instead of a GitHub issue (which will be focused on bug backlog), so please open a new request for this on there if you want to see it included.
