### ISSUE TITLE
[PHP 8 + WC 4.8.0-beta.1 + WP 5.6-RC1] Magic method warning

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce-gateway-stripe#1385]
Similar to https://github.com/woocommerce/woocommerce-admin/issues/5613

With the following setup, you'll see a PHP warning: 

**Testing Env:**

Atomic ephemeral
**WP:** Version 5.6-RC1
**WC:** WC 4.8.0-beta.1
**PHP:** 8.0.0RC3
macOS
Chrome
2021 theme

*Query Monitor:*

![https://d.pr/i/L5r2CX+](https://d.pr/i/L5r2CX+)

**Additional context**

pb22l9-ce-p2

**Comment by dechov** [comment]
Thank you for reporting! Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/commit/84b6457d691f47bdbcaa45f4d218ba852532c857
