### ISSUE TITLE
Update Apple Pay messaging to remove holiday language after the holidays

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1388]
This is the new messaging we'd like to use starting December 26:

> **Boost sales with Apple Pay**
> Now that you accept Apple Pay with Stripe, you can increase conversion rates by letting your customers know that Apple Pay is available. Here’s a marketing guide to help you get started.

**Comment by bmccotter** [comment]
messaging is great! Please be sure to keep the registered trademark messaging apart of Apple Pay -- we're literally just removing the "holiday" from the header.

**Comment by allendav** [comment]
@bmccotter - do you want to update un-dismissed notes placed in the inbox before Dec 25, or do you just want us, starting on Dec 26 to drop the "holidays" for newly verified Apple Pay merchants?

**Comment by bmccotter** [comment]
@allendav I think we can start a few days before, if that works?

**Comment by allendav** [comment]
Yup! But - I was more interested in what we're trying to accomplish with this change. I want to make sure I'm not over doing it.

We could update any existing notes in merchant inboxes to remove the "holiday" bits from the title AND drop the "holiday" bits from the title for merchants that don't have this note yet

OR

We could just drop the "holiday" bits from the title for merchants that don't have this note yet.

**Comment by bmccotter** [comment]
@allendav  holiday messaging for ALL merchants should stay intact lets say through December 22, and then it should switch to non holiday. 

Non holiday:
Boost sales with Apple Pay
Now that you accept Apple Pay with Stripe, you can increase conversion rates by letting your customers know that Apple Pay is available. Here’s a marketing guide to help you get started.
