### ISSUE TITLE
Apple Pay Shipping Address Not Accepted Upon Checkout (Like Issue #137)

### ISSUE THREAD

**Issue by blustonedesign** [woocommerce/woocommerce-gateway-stripe#140]
#### What I expected

Apple Pay to populate and accept shipping address given by customer's stored credentials with Apple Pay upon checkout.

#### What happened instead

Upon trying to use Apple Pay a Red Exclamation Mark after the Processing spinner indicates the customer is using invalid address. 

Multiple variations and iterations of addresses have been tried (Ex. trying Street, ST, St., St, STREET). Postal code has been verified and address is in proper format ( tried both iterations X0X 0X0 and X0X0X0).

WooCommerce shipping settings have been included in screenshots - and present no issues during regular checkout without Apple Pay.

Tried with TwentySeventeen, WooCommerce and Stripe enabled only - still presents an issue.

I'm positive I have everything configured correctly on the shipping end of WooCommerce, if you require any additional information - please let me know.

General Shipping Settings:
<img src="https://i.imgur.com/9AuIStW.png">

Shipping Option Settings (Flat Rate):
<img src="https://i.imgur.com/aANbnbD.png">

Checkout With Shipping:
<img src="https://i.imgur.com/ZIvVxZS.png">

Thanks!
-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Please include the exact address you're using and also remove "pick up in store" and see what happens.

**Comment by blustonedesign** [comment]
Hey there -

Pick up in store - removed. Cookies, cache, everything cleared - tried again, multiple machines - same issue, unfortunately.

Exact address:

120 Sterling Street
London, Ontario
N5Y 1Y8

Thanks again!

**Comment by roykho** [comment]
So this appears to be either a Stripe issue or Apple issue and it only happens on Canadian addresses. I am in contact with them to see what the resolution is for this.

**Comment by blustonedesign** [comment]
Great, thanks for your time and the update. If you need more info, please let me know!

**Comment by DerbyST** [comment]
I'm having the same issue using a UK address. Cookies/cache cleared, tried on 2 different iPhone 7s yet still getting the red exclamation mark.

**Comment by brunocrosier** [comment]
I'm having the same issue with a UK address, red exclamation mark, using iPhone 6.

**Comment by prescottt** [comment]
Same issue here with a UK Address, I managed to checkout using a virtual product where the shipping address wasn't needed and it worked, but one thing I did notice was that 'United States' was added to the bottom of my billing address, not sure whether this is related. Can't checkout at all when the shipping address is needed it keeps throwing the red exclamation mark.

**Comment by mikecreativehope** [comment]
Same issue with the UK address on a 6s, 7 and 7Plus

**Comment by getaccessories** [comment]
I'm also having this issue in the UK on a 6S. Have tried the same card and shipping address on a different apple pay website (uses shopify) and the issue doesn't arise there.

**Comment by roykho** [comment]
Not something we can fix. This issue has already been passed to Stripe and Apple. They're working on it.

**Comment by getaccessories** [comment]
Is there any more on this? It is a major issue as you can't charge people for shipping or offer expedited shipping

**Comment by roykho** [comment]
Again this is a Stripe/Apple issue. Not with our plugin.

**Comment by dihetherington** [comment]
Good morning, has anyone heard whether this has been resolved? I have an api from last year, wondering whether updating it will resolve it?

**Comment by RubiousShaun** [comment]
I'm getting this problem too with UK addresses.

**Comment by RubiousShaun** [comment]
I contacted Stripe and they said this is an issue with the plugin.

**Comment by prescottt** [comment]
I'm quite surprised the plugin went public without this being fixed to be honest, regardless of where the issue lies

**Comment by dihetherington** [comment]
I think it is a problem with the postcode, if I omitted the postcode it worked. At Stripe they said the issue was with Apple although I didnt say about the plugin.

**Comment by roykho** [comment]
See open issues regarding this:
https://openradar.appspot.com/30757800
https://forums.developer.apple.com/thread/15217

I did find a possible way around this but not sure if it is the best solution. But it is a solution for now nonetheless. The solution is to bypass postal code validation in WC core.

**Comment by RubiousShaun** [comment]
@roykho please can you share the code you used to bypass postal code validation?

**Comment by roykho** [comment]
Ok so I've added in a filter to bypass the postal code validation check from WC core. Because WC core will invalidate any postal codes that are partial. That is the first part of the issue which this fix circumvents. But we're still not out of the woods because the shipping method used still needs to be able to retrieve rates based on a partial postal code. And this is not something we can control. It will depend on the shipping method you use. So far I know that USPS will work. UPS no.

I have spoke to Apple Pay about this and it seems they will not change this for now. So the only other option is a way to find a 3rd party address validation API which we can pass in partial postal code and it will spit out the full postal code based on the address. That of course adds another layer of complexity not to mention if that is even feasible in terms of if they charge per API call or not...etc.

But if you want to give the current partial solution a test, feel free to download it from the master branch.

**Comment by ConnorLinfoot** [comment]
This seemed to work for myself with a UK address.

**Comment by mdmoore** [comment]
@roykho Would failures in using a 7 digit postcode(Scotland) be related to this?  With the filter, the postcode shouldn't even be validating, so I'm not sure why a 7 digit postcode isn't working with Apple Pay.  

Postal Code: 
CV32 5EB

**Comment by SiR-DanieL** [comment]
@roykho ^ any news on this?

**Comment by roykho** [comment]
@SiR-DanieL - yes Apple will not change this for now.
