### ISSUE TITLE
SEPA checkout fails to render when Stripe credit card payment method is disabled

### ISSUE THREAD

**Issue by jrodger** [woocommerce/woocommerce-gateway-stripe#1404]
**Describe the bug**
If the Stripe credit card payment method is disabled, but the SEPA payment method is enabled, then the SEPA checkout doesn't render due to the `woocommerce_stripe` JavaScript not being registered when the SEPA code tries to enqueue it.

**To Reproduce**
1. Go to Settings > Payments, disable "Stripe - Credit Card (Stripe)" and enable "Stripe SEPA Direct Debit - SEPA Direct Debit"
2. Add a product to your basket and go to the checkout
3. See that the field to enter your IBAN is missing

**Expected behavior**
With just SEPA payments enabled I should be able to checkout with the SEPA payment method.

**Screenshots**
<img src="https://user-images.githubusercontent.com/686419/101505055-d4d5d700-396b-11eb-97a9-98e577fa2d6a.png" height=400/>

**Environment (please complete the following information):**
 - WordPress Version: 5.5.3
 - WooCommerce Version: 4.7
 - Stripe Plugin Version: 4.5.5
 - Browser: Chrome 87

**Additional context**
We may want to check whether other payment methods included in this plugin are also affected by the issue. It's the script registration not running [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/adaef2bf0b0db57fec02c604606280a70921264f/includes/class-wc-gateway-stripe.php#L404) that seems to be causing the problem.

**Comment by dougaitken** [comment]
Can confirm. 

Ref: 14718985-hc

**Comment by dougaitken** [comment]
Possibly related? https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1751

**Comment by wpniall** [comment]
Reported in 4777973-zen. I can also confirm that with the new checkout experience (early access) feature enabled, it's not possible to display SEPA only, as the credit card option can't be turned off without turning off Stripe entirely at checkout.

As such, both options have to be enabled, which allows the credit card and SEPA options to display; the IBAN field works correctly too:

![https://d.pr/i/a4bW1v](https://d.pr/i/a4bW1v+) 
Full Size: https://d.pr/i/a4bW1v

**Comment by nuart73** [comment]
Verified today, the issue is still present.

**Comment by jacoswan** [comment]
Another in 5451901-zen, WC 6.7.0, Stripe 6.5.1

**Comment by dougaitken** [comment]
This only happens with the standard (old) payment methods, not UPE.

Still happening with Stripe `6.6.0`.

I think this is related to whatever is causing #1575 

My recommendation would be for merchants to enable UPE if they feel that is appropriate.

**Comment by paulostp** [comment]
Another report in 5540342-zd-woothemes. Site with WC 6.8.2 and Stripe 6.7.0.

**Comment by SvenHerr** [comment]
no workaround?

**Comment by webiw** [comment]
Same problem here, any solution?

**Comment by orhanfernandes** [comment]
6054042-zen. Site with WC 7.5.0 and WC Stripe 7.2.0.
