### ISSUE TITLE
PHP Fatal error:  Uncaught Exception: Invalid data store

### ISSUE THREAD

**Issue by ablears** [woocommerce/woocommerce-gateway-stripe#1414]
**Describe the bug**
PHP Fatal error:  Uncaught Exception: Invalid data store upon activation

**To Reproduce**
Activating the plugin causes the following fatal error:

NOTICE: PHP message: PHP Fatal error:  Uncaught Exception: Invalid data store. in /var/www/zzz/wp-content/plugins/woocommerce/includes/class-wc-data-store.php:107
Stack trace:
#0 /var/www/zzz/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(139): WC_Data_Store->__construct('admin')
#1 /var/www/zzz/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/Note.php(85): WC_Data_Store::load('admin-note')
#2 /var/www/zzz/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/DeprecatedNotes.php(53): Automattic\WooCommerce\Admin\Notes\Note->__construct('')
#3 /var/www/zzz/wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-inbox-notes.php(121): Automattic\WooCommerce\Admin\Notes\WC_Admin_Note->__construct()
#4 /var/www/zzz/wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-inbox-notes.php(56): WC_Stripe_Inbox_Notes::create_failure_note()

**Environment (please complete the following information):**
Status report: https://pastebin.com/U88bWdpK

**Additional context**
Multisite network.

**Comment by v18** [comment]
Thanks @ablears for the report. Upgrading to Stripe 4.6.0 will fix the issue.
