### ISSUE TITLE
3.1.0 - Is ApplePay going to support Subscriptions?

### ISSUE THREAD

**Issue by JustinSainton** [woocommerce/woocommerce-gateway-stripe#142]
[Reviewing the code](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-apple-pay.php#L144-L152), it appears that WC does not intend on supporting ApplePay w/ Subscriptions.

Is there a reason for this? [The Stripe website](https://stripe.com/apple-pay) seems [to indicate](https://cloudup.com/cXxZggnd530) that subscriptions are supported on their end.

**Comment by roykho** [comment]
Yes subs support will be in a future phase just not now. And it will not support Stripes subs but our own subs extension.
