### ISSUE TITLE
Bug when attempting to create an account on checkout with an invalid credit card

### ISSUE THREAD

**Issue by bbruman** [woocommerce/woocommerce-gateway-stripe#1428]
In sandbox mode, using the card `4000 0000 0000 0002` which is a card to test that the `Charge is declined with a card_declined code.` (from https://stripe.com/docs/testing)

On my checkout page I have a checkbox to `Create an Account` while checking out.  If I checkmark this and input a password, Stripe does not return an error message in the ajax call (as it does normally here: https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/checkout.js#L542 if I am not attempting to `Create an Account`

Instead, the ajax call returns with a `result.reload` of `true` here: https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/checkout.js#L531

triggering the reload of the page via `window.location.reload();`, with the account being created and the order not going through  without any error message output and starting the checkout process over again.

I disabled account creation on checkout for now, as this is a quite annoying bug for potential customers (creates the account, starts checkout process over, and doesn't tell the user why the (declined) charge did not go though).

**Comment by annemirasol** [comment]
Closing, as no longer reproducible in latest extension version. Tested on 9.0.0.

When `Allow customers to create an account: During checkout` is enabled, and the card is declined:

**Block checkout**
<img width="400" alt="Image" src="https://github.com/user-attachments/assets/c7300a41-079e-4f6e-8da5-41d2b143fb4f" />

**Classic checkout**
<img width="400" alt="Image" src="https://github.com/user-attachments/assets/4ae81a68-5242-44a9-8c64-4c9348051b32" />

The behavior and error message are the same for when account creation on checkout is disabled.
