### ISSUE TITLE
Error message on checkout is misleading if the API keys are invalid

### ISSUE THREAD

**Issue by javorszky** [woocommerce/woocommerce-gateway-stripe#143]
#### What I expected

I had incorrect API keys in the settings. Upon checkout, I expected the site to throw an error along the lines of "sorry, your API keys are invalid".

#### What happened instead

![](https://cldup.com/fotKSsGdMg.png)

#### Steps to reproduce the issue

Install WooCommerce, configure stripe, add wrong API test keys, attempt to check out.

Using latest WP at the time (4.7), and WooCommerce 2.6.11 (release).

**Comment by roykho** [comment]
I am getting this ![](http://cld.wthms.co/lAfY+)
