### ISSUE TITLE
Spike: Stripe Checkout - implement successful flow

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1441]
Implement Stripe Checkout as a payment method available on the checkout page. To start, can implement just the successful flow.

We'll want to send Stripe these fields:

- success_url
- cancel_url
- mode
- payment_method_types
- customer_email

After the initial implementation is working, we can also potentially send these fields:

- line_items
- locale

Once Stripe Checkout is working, are there any issues?

More notes: pc4etw-7v-p2

**Comment by v18** [comment]
Related PR: #1285

**Comment by clintonb** [comment]
API docs are at https://stripe.com/docs/api/checkout/sessions/create.

You can pass in the email directly (`customer_email`) or indirectly (pulled from `customer`). The billing address is either always required or only required when necessary as determined by Stripe (`billing_address_collection`).

The `line_items` can be configured for tax using the `tax_rates` parameter. Shipping is typically included as its own line item.

The shipping address data collected is available on the Checkout Session object. I don't know if it's also written to the customer.

**Comment by diegocurbelo** [comment]
Stripe Checkout spike was cancelled, and superseded by UPE and Stripe Link
