### ISSUE TITLE
Spike: Apple Pay - best way forward to verify domain

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1442]
This issue affects both the WCPay and Stripe repos. h/t @dechov for surfacing this, including these questions/concerns:

- should we go back to copying the verification file or continue to use the rewrite rule?
- can check with data to make sure validate that the method we use to verify the domain is reliable?
- let's get a second opinion on this

**Comment by dechov** [comment]
For a bit more context, we switched in version 4.5.4 from copying the domain association file to using a rewrite rule – it looks like it's still failing a significant portion of the time though, and it's possible that it's failing in some cases where copying the file would have worked – we could consider restoring the earlier approach, as a fallback perhaps.
