### ISSUE TITLE
Payment request button does not display if there are only payment methods added through Google Pay

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-gateway-stripe#1444]
**Describe the bug**
The Stripe payment request button will NOT display if there are only payment methods added through Google Pay: 

![https://d.pr/i/2lX3fn](https://d.pr/i/2lX3fn+)
Image link: https://d.pr/i/2lX3fn

![https://d.pr/i/Yogw7V](https://d.pr/i/Yogw7V+)
Image link: https://d.pr/i/Yogw7V

If there are any payment methods that have not been added through Google Pay, the payment request button will display: 

![https://d.pr/i/WtaSvJ](https://d.pr/i/WtaSvJ+)
Image link: https://d.pr/i/WtaSvJ

![https://d.pr/i/5lDjul](https://d.pr/i/5lDjul+)
Image link: https://d.pr/i/5lDjul

**To Reproduce**
1. Setup Stripe and enable payment request options: https://docs.woocommerce.com/document/stripe/#payment-request-buttons
2. Add a payment option through Google Pay (ex: In Chrome: `Settings > Payment methods > To add or manage Google Pay payment methods, visit your Google Account` option)
3. Go to any product page where the payment request button should display and it won't be there.
4. Add a payment option that is not through Google Pay (ex: In Chrome: `Settings > Payment methods > Add` option)
5. Payment request button displays ONLY when a non-Google Pay option is added as a Payment method.

**Expected behavior**
Payment request button displays when there is only a `Google Pay` option added as a Payment method

**Environment (please complete the following information):**
 - WordPress Version `5.6`
 - WooCommerce Version `4.8.0`
 - Stripe Plugin Version `4.7.0`
 - Chrome browser - Version `87.0.4280.88`
 - No other plugins installed outside of Jetpack and WP Mail Logging

3600888-zen

**Comment by ricardo** [comment]
It seems like Chrome for desktop [is no longer exposing](https://blog.chromium.org/2018/07/bringing-google-pay-to-paymentrequest.html) cards stored in users accounts as a payment method via the Payment Request API.

As per the [Google Pay developer docs](https://developers.google.com/pay/api/web/guides/paymentrequest/tutorial):
> Chrome for Android is currently the only web browser supporting the Payment Request API with third-party payment methods, including Google Pay.

In fact, on Chrome for Android, the button shows up and you can pay using your Google Pay account, as shown below:

<img src="https://user-images.githubusercontent.com/5509901/106520945-48074f80-64bc-11eb-8d2a-5a1b1ccea6ce.jpeg" width="200"> <img src="https://user-images.githubusercontent.com/5509901/106520953-49d11300-64bc-11eb-9c82-508d0429e136.jpeg" width="200">

I tested [Stripe's demo](https://stripe-payments-demo.appspot.com/) as well and it produces the same result - it doesn't display the button if you have only Google Pay as a payment method.

Since it's not a problem with our extension, I'm afraid we can't do anything about this issue.

**Comment by zwiesman31** [comment]
@ricardo Thanks for checking!

Is there anything else we can do to look into it? Do you think it's even productive to contact Chrome/Stripe support?

If not, is this worth mentioning in the [Stripe documentation here](https://docs.woocommerce.com/document/stripe/#gpay) that Google Pay may no longer work?

**Comment by ricardo** [comment]
@zwiesman31

> Is there anything else we can do to look into it? Do you think it's even productive to contact Chrome/Stripe support?

It really isn't clear from [Stripe docs](https://stripe.com/docs/stripe-js/elements/payment-request-button) - Either Google Pay only works on Android devices or we need to do something else to integrate Google Pay besides the Stripe Elements set up.

I just contacted Stripe support to make sure we have the right information. I'll update this thread once I get a response.

> If not, is this worth mentioning in the Stripe documentation here that Google Pay may no longer work?

If that's really the case, I believe it's worth mentioning in our docs that payment methods added through Google Pay will only work on Chrome for Android.

**Comment by zwiesman31** [comment]
Thanks so much, @ricardo!

**Comment by ricardo** [comment]
This is what I found from our folks at Stripe:

Google Pay through Chrome desktop only works if you have a ServiceWorker installed. But to have that kind of setup, the customer needs to have previously used a native Google Pay implementation in the browser. - Which we can't expect from customers. So technically, we can say that it works only for Android devices right now.

They say Stripe doesn't integrate with Google Pay directly. It integrates with a web standard (Payment Request API), which serves as a layer for Google Pay.

Unfortunately, Chrome's commitment to the Payment Request web standard is not great. Eventually Stripe should natively integrate with Google Pay through Payment Request Buttons, but they don't have a timeline on that.

@zwiesman31, do you think we can mention under notes in our [docs](https://docs.woocommerce.com/document/stripe/#gpay) that "Google Pay may only work as a payment method on Android devices" or something along those lines?

**Comment by zwiesman31** [comment]
@ricardo Thanks so much for investigating this more!

> do you think we can mention under notes in our docs that "Google Pay may only work as a payment method on Android devices" or something along those lines?

Yes, that looks like the best way forward. I'm wondering if there's a good way to link the documentation text that we will add directly to this issue for more information, since the repository is public and anyone can view. Thoughts on that?

**Comment by ricardo** [comment]
I've seen linked GitHub issues on WooCommerce docs (like [this one](https://docs.woocommerce.com/document/stripe/#stripe-checkout)).

To make sure, we can ask on p0-slack-woo-docs-guild.

Then it would be nice to update your issue description with what we just found out.

**Comment by v18** [comment]
This is a known issue that needs to be solved from Stripe's end. It's related to when Google chooses to display different payment methods added to Google Pay. Closing this issue since there isn't anything for the Stripe gateway to do.
