### ISSUE TITLE
Add payment method - add option to apply new card to existing Subscriptions

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-gateway-stripe#145]
User raised a good point about when a new credit card is added it is not applied to existing Subscriptions. Would it be possible to add a checkbox to the **Add Payment Method** screen that allowed subscribers to apply the new payment method to existing Subscriptions?

#### Affected ticket(s)

518252-zd-woothemes

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Closed in favor of this https://github.com/woocommerce/woocommerce-gateway-stripe/issues/149
