### ISSUE TITLE
Invalid or missing payment token fields

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce-gateway-stripe#1450]
**Describe the bug**

When you attempt to checkout using a card with insufficient funds, checkout page displays `Invalid or missing payment token fields` error instead of the actual Stripe response, which is:

```
{
  "error": {
    "code": "card_declined",
    "decline_code": "insufficient_funds",
    "doc_url": "https://stripe.com/docs/error-codes/card-declined",
    "message": "Your card has insufficient funds.",
    "param": "",
    "type": "card_error"
  }
}
```

**To Reproduce**
1. Attempt to checkout a product using this test card: `4000000000009995`
2. Notice the following error:
    ![https://d.pr/i/WOpcd5+](https://d.pr/i/WOpcd5+)
3. Check the logs to find that we've only logged this for the transaction:

```
2021-01-15T09:55:58+00:00 DEBUG 
====Stripe Version: 4.7.0====
====Start Log====
customers/cus_REDACTED/sources request: Array
(
    [limit] => 100
)

====End Log====


2021-01-15T09:56:57+00:00 DEBUG 
====Stripe Version: 4.7.0====
====Start Log====
sources/src_REDACTED
====End Log====


2021-01-15T09:56:58+00:00 DEBUG 
====Stripe Version: 4.7.0====
====Start Log====
customers/cus_REDACTED/sources request: Array
(
    [source] => src_REDACTED
)

====End Log====
```

4. Check your stripe account to confirm that there there is no failed payment created, but when you search for the source created for this transaction in the logs, you see a 402 error:

    ![https://d.pr/i/vGp2rR+](https://d.pr/i/vGp2rR+)

 **Expected behavior**

Display the right error to the customer. 

**Environment (please complete the following information):**

This can only be replicated on the latest version of Stripe. In Stripe 4.6, this is what I see:

![https://d.pr/i/KkZoNM+](https://d.pr/i/KkZoNM+)

Perhaps, we should also display why the card was declined?

**Customer Report**

3630220-zen

**Comment by stan-saluda** [comment]
Stripe production error 402 for this situation always includes this response:
`{
  "error": {
    "code": "card_declined",
    "decline_code": "do_not_honor",
    "doc_url": "https://stripe.com/docs/error-codes/card-declined",
    "message": "Your card was declined.",
    "param": "",
    "type": "card_error"
  }
}`

**Comment by rtpHarry** [comment]
My client has just called me up saying they are seeing this as well.

**Comment by rtpHarry** [comment]
It is happening for me with the `do_not_honor` code.

**Comment by stan-saluda** [comment]
I've also been informed that at least in one case, the card issuer treated these transactions as potential fraud and sent appropriate notification to the customer. Don't know what might have triggered that but definitely doesn't look good from the customer's perspective.

**Comment by erika-dike** [comment]
I am also seeing this on live and test environments. In the test environment, I see it for cards that should be used to test specific error responses: https://stripe.com/docs/testing#cards-responses.

**Comment by extremeleadprogram** [comment]
I am on Version 4.8.0 and just had a customer trying to order and was getting the same error: "Invalid or missing payment token fields".

Logged into stripe and see it's a Zip code fail...

**Comment by melindahelt** [comment]
Another report
3726343-zen

Please follow up with this user.

**Comment by colmtroy** [comment]
Also seeing this with one of my customers who attempted to pay with a card expiring this month.

**Comment by MrOli3000** [comment]
> In my case, Stripe production error 402 for this situation always includes this response:
> `{ "error": { "code": "card_declined", "decline_code": "do_not_honor", "doc_url": "https://stripe.com/docs/error-codes/card-declined", "message": "Your card was declined.", "param": "", "type": "card_error" } }`


I am getting the "Card declined" "do not honor" error in the stripe logs. My users are seeing the error "missing payment token fields"

I am also not see an attempt to charge the card in the woocommerce order notes.

**Comment by itallogravina** [comment]
I also have the same problem

**Comment by yukikatayama** [comment]
25879451-hc has also reported this. Where customers see ` Invalid or missing payment token fields` and in Stripe account, error code:

```
{
  "error": {
    "code": "card_declined",
    "decline_code": "do_not_honor",
    "doc_url": "https://stripe.com/docs/error-codes/card-declined",
    "message": "Your card was declined.",
    "param": "",
    "type": "card_error"
  }
}
```

**Comment by ericboles** [comment]
Seeing this same issue with checkout displaying `Invalid or missing payment token fields.` when using test cards designed to show various errors (real customers are also running into this in a production environment).  

Environment details:
WooCommerce 5.0.0
WooCommerce Stripe Gateway 4.8.0
Woocommerce Subscriptions 3.0.13

It's been over a month since this was reported on the last version (4.7.0)...appreciate some attention/assignment on this.

**Comment by ericboles** [comment]
Further testing shows that this seems to be an issue limited to purchases that save cards.  When purchasing a subscription product or selecting "save payment information to my account" for a regular product, the customer receives `Invalid or missing payment token fields.` when they should see a decline error.  On the same sites when purchasing a regular product and not selecting "save payment", customers see the correct decline error.

I've run tests on multiple sites, and this is a consistent across all of them. Not sure if the circumstances are similar for the others here who have reported this issue, but I hope this information can help further identify/test and fix the problem.

Also...confirming that this is still an issue with the latest WooCommerce Stripe Gateway version -- 4.9.0.

**Comment by npphases** [comment]
The same issue occurs on a couple of production websites. Can you please release a patch for this?

**Comment by neilgee** [comment]
Seeing this error `Invalid or missing payment token fields:`

Using:
WooCommerce 5
WooCommerce Subscriptions 3.0.13
Stripe 4.9.0

When logged in via my-account and user goes to change 'Add Payment Method', fatal error occurs:
```
[04-Mar-2021 23:45:18 UTC] PHP Fatal error:  Uncaught Exception: Invalid or missing payment token fields. in /home/wpbeaches/webapps/wpbeaches/wp-content/plugins/woocommerce/includes/data-stores/class-wc-payment-token-data-store.php:44
Stack trace:
#0 /home/wpbeaches/webapps/wpbeaches/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(169): WC_Payment_Token_Data_Store->create()
#1 /home/wpbeaches/webapps/wpbeaches/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php(218): WC_Data_Store->create()
#2 /home/wpbeaches/webapps/wpbeaches/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-customer.php(300): WC_Data->save()
#3 /home/wpbeaches/webapps/wpbeaches/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php(974): WC_Stripe_Customer->add_source()
#4 /home/wpbeaches/webapps/wpbeaches/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(525): WC_Stripe_Payment_Gateway->add_payment_method()
#5 /home/wpbeaches/webapps/wpbeaches/wp-includes/class-wp in /home/wpbeaches/webapps/wpbeaches/wp-content/plugins/woocommerce/includes/data-stores/class-wc-payment-token-data-store.php on line 44
```

**Comment by renatho** [comment]
Same happening here. Waiting for the release. =)
