### ISSUE TITLE
Adding a SEPA payment method should work

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1451]
Steps to repro:
1. Log in to customer account, go to payment methods page
2. Try to add a SEPA payment method
3. See error "Card couldn’t be set up for future usage"
4. See in Stripe account that the bank account _was_ correctly set up

First reported here: https://wordpress.org/support/topic/update-4-7-0-sepa-setup-intent-is-not-correct/

**Comment by luizreis** [comment]
Also reported in 3680436-zd-woothemes

**Comment by springcast** [comment]
Same problem here. What's the current sprint? So I can get a good estimate on when to expect this issue to be fixed. I Also experience this issue with CreditCard when someone already has a current payment method active.

**Comment by neoseeyou** [comment]
Hello, we report this important issue 1 month ago, which obliges us to keep version 4.6.0

It's not a normal situation knowing that it is a very Vital plugin for an ecommerce website.

Any fix soon please?

**Comment by RiaanKnoetze** [comment]
Also reported in 3714636-zd-woothemes

**Comment by rossviviano** [comment]
Reported in 27787811-hc
