### ISSUE TITLE
Webhooks: Test that webhook is working and notify user if not

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1452]
This can be done on the Stripe settings page, or as part of the Woo set up.

Note it may not be possible to test if webhooks are working - need to check with Stripe.

**Comment by dechov** [comment]
I don't see a way to do this directly, but we can direct the merchant to the webhook view on their Stripe dashboard, wich lets you send a test webhook. Trying it just now, the test webhook event has an ID of `evt_00000000000000`, which I assume we can use to identify it as a test webhook received (if necessary) and report to the merchant that webhooks are working properly.

**Comment by diegocurbelo** [comment]
Available on the plugin settings tab:
`https://[HOST]/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings`

![Image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/407542/b7afa75d-7197-498e-b1c8-9db4433f070e)
