### ISSUE TITLE
PHP 8 Support - Deprecated Code

### ISSUE THREAD

**Issue by meek2100** [woocommerce/woocommerce-gateway-stripe#1454]
Hi, I'm running PHP 8.0.1 on my development environment as we start planning out our upgrade and I'm getting a deprecated code warning (see below) for code used in your plug-in. Can you please address this in your next update so your plug-in is no longer a blocker from us migrating to PHP 8.0.1 on our production environment? Thanks. 

` PHP Deprecated: Required parameter $currency follows optional parameter $order in \woocommerce-gateway-stripe\includes\class-wc-stripe-helper.php on line 40 `

**Comment by SiR-DanieL** [comment]
Another report of this from the forums:

```
PHP Deprecated:  Required parameter $currency follows optional parameter $order in \wp-content\plugins\woocommerce-gateway-stripe\includes\class-wc-stripe-helper.php on line 40
```

https://wordpress.org/support/topic/php-8-0-support/

**Comment by webhouse-dev** [comment]
Any updates?

**Comment by meek2100** [comment]
The plugin has been updated twice since this was reported and still has the issue mentioned above.  Can we get a timeline for when this plugin will be fully compatible with PHP 8?
