### ISSUE TITLE
Migrate checkout and cart blocks to this repo

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1455]

**Comment by reykjalin** [comment]
# Blocks vs. shortcode

Comment will be updated as I find new flows and test features.

✅ Works
❓ Not tested
❌ Doesn't work
🚫 Not supported

Where blocks are 🚫 not supported, that usually means you can't easily modify the page to add a block or the block in question doesn't exist.

Some of the things that ❌ don't work (e.g. payment request buttons, 3DS with saved cards) will be worked on in the near-future. This comment will be updated once those features have been fixed and tested.

## Cart

| Feature | Shortcode | Blocks |
|:---:|:---:|:---:|
| Payment Request Buttons | ✅ | ✅ |


| Error | Shortcode | Blocks |
|:---:|:---:|:---:|
| Payment Request Button errors | ✅ * | ✅   |

## Checkout

### Non-3DS

| Feature | Shortcode | Blocks |
|:---:|:---:|:---:|
| Pay with new card | ✅ | ✅ |
| Saved Cards | ✅ | ✅ |
| Payment Request Buttons | ✅ * | ✅  |


| Error | Shortcode | Blocks |
|:---:|:---:|:---:|
| CVV check failed | ✅ | ✅ |
| ZIP code check failed | ✅ | ✅ |
| Card expired/canceled | ✅ | ✅ |
| Card declined | ✅ | ✅ |
| Card has insufficient funds | ✅ | ✅ |
| Error processing payment | ✅ | ✅ |
| Payment Request Button errors | ✅ * | ✅  |


\* Requires filter

### 3DS

| Feature | Shortcode | Blocks |
|:---:|:---:|:---:|
| Pay with new card | ✅ | ✅ |
| Saved Cards | ✅ | ✅ |
| Payment Request Buttons | ✅ * | ✅  |


| Error | Shortcode | Blocks |
|:---:|:---:|:---:|
| Authentication failed | ✅ | ✅ |
| Payment Request Button errors | ✅ * | ✅  |


## Pay for order

| Feature | Shortcode | Blocks |
|:---:|:---:|:---:|
| Pay with new card | ✅ | 🚫 |
| Saved Cards | ✅ | 🚫|
| Payment Request Buttons | ✅ * | 🚫  |


| Error | Shortcode | Blocks |
|:---:|:---:|:---:|
| CVV check failed | ✅ | 🚫 |
| ZIP code check failed | ✅ | 🚫 |
| Card expired/canceled | ✅ | 🚫 |
| Card declined | ✅ | 🚫 |
| Card has insufficient funds | ✅ | 🚫 |
| Error processing payment | ✅ | 🚫 |
| Payment Request Button errors | ✅ * | 🚫  |

## Subscriptions

| Feature | Shortcode | Blocks | Comment |
|:---:|:---:|:---:|:---:|
| Pay with new card | ✅ | ❌   | Payment successful, but no subscription registered |
| Saved Cards | ✅ | ❌   | Payment successful, but no subscription registered  |
| Renewal payment | ✅ | ❌  | No way to create a subscription via blocks, so impossible to test  |
| Retry renewal payment | ✅ | 🚫 | Retry renewal page doesn't use blocks |
| Payment Request Buttons | ✅ | ❌   | Payment successful, but no subscription registered |


| Error | Shortcode | Blocks |
|:---:|:---:|:---:|
| CVV check failed | ✅ | ❓ |
| ZIP code check failed | ✅ | ❓ |
| Card expired/canceled | ✅ | ❓ |
| Card declined | ✅ | ❓ |
| Card has insufficient funds | ✅ | ❓ |
| Error processing payment | ✅ | ❓ |
| Renewal payment failed | ✅ | ❓ |
| Payment Request Button errors | ✅ | ❓    |

## Pre-order

| Feature | Shortcode | Blocks | Comment |
|:---:|:---:|:---:|:---:|
| Pay with new card | ✅ | ❌  | Payment successful, but no pre-order registered |
| Saved Cards | ✅ | ❌   | Payment successful, but no pre-order registered  |
| Payment Request Buttons | ✅ | ❌    | Payment successful, but no pre-order registered |


| Error | Shortcode | Blocks |
|:---:|:---:|:---:|
| CVV check failed | ✅ | ❓ |
| ZIP code check failed | ✅ | ❓ |
| Card expired/canceled | ✅ | ❓ |
| Card declined | ✅ | ❓ |
| Card has insufficient funds | ✅ | ❓ |
| Error processing payment | ✅ | ❓ |
| Renewal payment failed | ✅ | ❓ |
| Payment Request Button errors | ✅ | ❓    |

## I18n

| Feature | Shortcode | Blocks |
|:---:|:---:|:---:|
| Payment Request Button default text | ❓  | ❓   |
| Directions on checkout page | ❓ | ❓ |

## My Account

| Feature | Shortcode | Blocks |
|:---:|:---:|:---:|
| Add new card | ✅ | 🚫  |


| Error | Shortcode | Blocks |
|:---:|:---:|:---:|
| CVV check failed | ✅ | 🚫 |
| ZIP code check failed | ✅ | 🚫 |
| Card expired/canceled | ✅ | 🚫 |
| Card declined | ✅ | 🚫 |
| Card has insufficient funds | ✅ | 🚫 |
| Error processing payment | ✅ | 🚫 |

**Comment by v18** [comment]
@reykjalin - hey I wanted to ask you about what happens when the Blocks extension is disabled. Both before any cart or checkout blocks are added, and after. Does it cause an error on someone's site?

**Comment by reykjalin** [comment]
@v18 If you change your "Checkout" and "Cart" pages to use the cart and checkout blocks and then disable the blocks plugin you'll just see an empty pages:

| Checkout | Cart |
|:---:|:---:|
| <img width="868" alt="image" src="https://user-images.githubusercontent.com/13835680/113814357-16ed1900-97a4-11eb-911f-3e0b5bc568e2.png"> | <img width="868" alt="image" src="https://user-images.githubusercontent.com/13835680/113814378-22404480-97a4-11eb-9d9a-15600e3b28e0.png"> |

Using the shortcode checkout when blocks is enabled (or deactivated) works the same as if the blocks plugin wasn't present.
