### ISSUE TITLE
Add 3.0.7 update notes to the changelog

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/woocommerce-gateway-stripe#146]
The details regarding the 3.0.7 update are missing from the changelog: https://wordpress.org/plugins/woocommerce-gateway-stripe/changelog/

**Comment by roykho** [comment]
How so? I see it here http://cld.wthms.co/Cm99/38YYKU2V

**Comment by danieldudzic** [comment]
@roykho Sorry, this is very confusing.

The Polish version of the website is showing only 3.0.6: https://pl.wordpress.org/plugins/woocommerce-gateway-stripe/changelog/

Probably the user had a similar issue.

**Comment by roykho** [comment]
@danieldudzic - not sure but I assure you its there. See the code https://github.com/woocommerce/woocommerce-gateway-stripe/blob/release/3.0/readme.txt#L90-L93
