### ISSUE TITLE
"Clear Stripe account keys" button is always disabled

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-gateway-stripe#1461]
**Describe the bug**

https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1226 introduced a bug on the settings screen, causing the "Clear all Stripe account keys." button to always be disabled. This is because the event triggered [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/e2447605a9a5460dbef8bde5d8acea55967b4088/assets/js/stripe-admin.js#L147) puts the form in an "unsaved changes" state for purposes of that button (handled [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/e2447605a9a5460dbef8bde5d8acea55967b4088/assets/js/stripe-admin.js#L115)).

**To Reproduce**
Go to Stripe settings, and verify that button is disabled on page load:
<img width="815" src="https://user-images.githubusercontent.com/1867547/106540581-2dd66d00-64ce-11eb-9b21-b8091e6e015e.png">

**Expected behavior**
Button should not be disabled until something is actually changed by the merchant:
<img width="704" src="https://user-images.githubusercontent.com/1867547/106540578-2d3dd680-64ce-11eb-96a6-7677b367b86d.png">

**Comment by aheckler** [comment]
This affects the button even if you have not set up the plugin yet:

<img width="987" alt="Markup 2021-04-22 at 08 40 57" src="https://user-images.githubusercontent.com/5512652/115715824-889d9900-a346-11eb-913a-abe39e37355c.png">

3920410-zen
