### ISSUE TITLE
Level 3 data: Add fees as line items

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1462]
**Steps to repro**

1. Ensure you're using a connected Stripe account
2. Ensure that the `wc_stripe_level3_not_allowed` transient does not exist on the site
2. Create a new order in the admin.
3. Use Add item(s) and then Add fee.
4. Make sure the order status is Pending payment and then create the order.
5. Use the Customer payment page link to go to the checkout page for the order.
6. Attempt to checkout and you will see the following error in the Stripe logs:

```
====Start Log====
Level3 data sum incorrect: 
Missing required param: level3[line_items].
Order line items: 
Array
(
)

Order shipping amount: 
0
Order currency: 
USD
====End Log====
```

**Solution**
Add fees to line items sent to Stripe, see https://github.com/Automattic/woocommerce-payments/pull/1246

h/t @jessepearson 

A similar first reported and solved in WooCommerce Payments: https://github.com/Automattic/woocommerce-payments/issues/1190

**Comment by dmvrtx** [comment]
While the error message is not reproducible on my local set-up, I can certainly see level3 data empty.
