### ISSUE TITLE
Adjust README.txt copy to reflect Apple Pay and Web Payment Requests updates

### ISSUE THREAD

**Issue by mattyza** [woocommerce/woocommerce-gateway-stripe#147]
Logging this for @MarinaWoo to update the `readme.txt` file with copy promoting Apple Pay, and Web Payment Requests.

**Comment by MarinaWoo** [comment]
Thanks for this, on my list.

**Comment by MarinaWoo** [comment]
@mattyza - I don't feel 100% comfortable doing this, can I pass this ball back to you for the Apple Pay launch and keep my focus on the other marketing elements?

**Comment by mattyza** [comment]
Sure @MarinaWoo. :)
