### ISSUE TITLE
Payment validation process needs a progress bar

### ISSUE THREAD

**Issue by Rick-OGSS** [woocommerce/woocommerce-gateway-stripe#1473]
After pressing the "Place Order" the plugin either needs to display a progress bar or change the button text.  Ideally a prgress bar with events notifications like this.

Disable Button/change colour

- Contacting Payment Channel
- Verifying Account
- Processing transaction
- Transaction Succeeded/Failed

Re-enable Button and restore colour

Right now it just sits there and you are left wondering what is happening, often for more than 10 seconds on slower networks.
Priority: High

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by ricardo** [comment]
@Rick-OGSS WooCommerce provides a loading indicator after clicking "Place order". Do you suggest replacing that with a progress bar?

<img width="76" alt="Screen Shot 2021-02-22 at 16 20 32" src="https://user-images.githubusercontent.com/5509901/108758641-16692d80-752a-11eb-8b62-60083f5a9dec.png">

>- Contacting Payment Channel
>- Verifying Account
>- Processing transaction
>- Transaction Succeeded/Failed

I'm afraid this isn't possible. The checkout usually triggers just one endpoint: `wc-ajax=checkout`, therefore, the best UI indicator in my opinion would be the spinner.

**Comment by Rick-OGSS** [comment]
Hey Ricardo,

The problem seems to be that for checkout pages that extend beyond the
bottom of a view, there is no indication.  Here is a quick video example of
what I am talking about.
As you can see, the customer is left with no feedback for about 15
seconds.  It's only when the screen jumps back to the top do you know its
progress status.

I would like to see a progress bar or dynamic "Place Order" button so that
if you have scrolled down a page you do not lose your progress status.

Thanks for looking into this,

Rick

**Comment by ricardo** [comment]
@Rick-OGSS thanks for clarifying further. This might be something we need to pay attention to, perhaps this is not an issue with Stripe, but with WooCommerce. I guess you missed the video, can you provide a link?

**Comment by Rick-OGSS** [comment]
Here you go.

**Comment by Rick-OGSS** [comment]
https://user-images.githubusercontent.com/56748365/108793301-9a86d980-7559-11eb-81d6-65caf2718913.mp4

looks like I cant include an attachment by replying from email.  Hopefully this works

**Comment by ricardo** [comment]
@Rick-OGSS this seems to be unique to your website.

When placing an order, WooCommerce adds an overlay, blocking the screen, and the spinner is centered on the screen, no matter the scroll position.

Please try using the WooCommerce Storefront theme. It should render the loading indicator correctly.

If you want to fix this in your current theme, you might need some custom CSS.
Since this is not part of Stripe and we don't deal with this type of inquiry here on GitHub, I'd suggest taking a look at our [Woo Experts](https://woocommerce.com/experts/) page, or contacting your theme support.

**Comment by v18** [comment]
I'm closing this issue since it's not an issue related to the Stripe gateway specifically.
