### ISSUE TITLE
Support currency switcher extensions to enable payment methods based on presentment currency instead of store currency

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#1488]
**Is your feature request related to a problem? Please describe.**

giropay allows accepting payments for customers in Germany but Stripe extension says the base currency should be set in EUR - https://stripe.com/docs/sources/giropay

**Describe the solution you'd like**

giropay payment method can be activated if the store currency is not set to EUR, such as GBP. The store owner can use a currency changer plugin to handle the currency charged.

**Describe alternatives you've considered**

Changing the base currency of the store isn't viable for international stores based in certain countries, such as in UK where the currency is in GBP.

28029474-hc

**Comment by dmvrtx** [comment]
I wonder if it actually makes sense to tie Giropay (and iDeal as well) to shop currency? Stripe allows to use them for USD shop accounts without any issues and does all the required currency convertion.

**Updated:** So, it's actually more complicated than that. Stripe indeed allows payments to USD account from EUR payment method. But the intent must be created in EUR. If intent will be in GBP or any other currency, payment will fail.

Now that I look at the currency switcher plugin, it has an option to pay in the currency selected by a buyer, but it is disabled but default. And if currency limitation will be removed then a plain WooCommerce without any currency switcher will be presenting Giropay to the users while trying to pay with it will result in an error:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/683297/114724159-90a07c00-9d3b-11eb-8e4e-22ab520a5c60.png">

This makes me think that it is a *currency switcher plugin* which has to hack into `wc_stripe_ideal_supported_currencies` filter and add whatever shop currency is set if and only if "*Pay in user selected currency*" setting is active and this setting is set to EUR.

**Comment by v18** [comment]
Wanted to note that Stripe supports switching to a different currency using this extension:
https://woocommerce.com/products/currency-switcher-for-woocommerce/

When using this extensions, and the price for the customer is switched to EUR, giropay and the other payment methods requiring EUR are available at checkout using Stripe.

Going to close this issue since Stripe supports the feature requested. Feel free to open if there are any other related issues/bugs/questions.
