### ISSUE TITLE
WC_Admin_Notes is deprecated since WC 1.7.0

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#1489]
**Describe the bug**

When trying to use `WC_Admin_Notes` right now, we're catching these errors, but they're still being logged:

```
Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes::get_note is deprecated since version 1.7.0! Use Automattic\WooCommerce\Admin\Notes\Notes::get_note instead.
```

Looks like the fix is simply to replace `WC_Admin_Notes` with `Notes`.

**To Reproduce**

1. Go to `localhost:8082`.
2. Enter live Stripe publishable + secret keys.
2. Disable the Payment Request buttons setting and then re-enable it to trigger an Apple Pay verification error inbox note.
3. The error above should be logged in `docker/logs/apache2/error.log`.

**Comment by v18** [comment]
~As part of this issue, let's remove the hard-coded notes in this repo and add them remotely instead.~

Moved this to a separate issue: #1540

**Comment by dechov** [comment]
We should also change `WC_Admin_Note` to `Note`, is that right? WCPay has compatibility logic for that one [[code](https://github.com/Automattic/woocommerce-payments/blob/e099744fb8cead46fe23ec25d785e40827947c1f/includes/compat/class-wc-payment-woo-compat-utils.php#L19-L30)] – do we need that, or is the last version with only `WC_Admin_Note(s)` no longer supported?

**Comment by ricardo** [comment]
@dechov Good question. From the issue description it says `WC_Admin_Note::get_note` is deprecated since version 1.7.0, so if that's correct, I think it makes sense to support only `Note`, because we have `WC requires at least: 3.0` in `woocommerce-gateway-stripe.php`.
