### ISSUE TITLE
Improved Subscriptions compatibility - trying payments when default credit card is change

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce-gateway-stripe#149]
#### Affected ticket(s)
516228-zd-woothemes
See ticket for further discussion and details

#### What I expected
When using Stripe and Subscriptions, subscriptions is not notified if the default credit card in Stripe has been changed. According to the Prospress team, this was previously handled properly by the Stripe extension, but since removed.

#### What happened instead
Subscription fails as it tries to charge the old card.

From the custom who reported the issue:
> With WC Subscriptions, the payment card is stored in wp_postmeta in the meta_key _stripe_card_id. When it's time for renewal, WC Subscriptions attempts to process the renewal automatically using this card ID.
If a user has previously deleted this card, WC Subscriptions is not notified, so it fails with error "Stripe Transaction Failed (Customer cus_*********** does not have a linked source with ID card_************.) Order status changed from Pending Payment to Failed."

From Prospress:

> I also think this type of issue may have been prevented in an earlier version of Stripe where it would retry payment just using the customer ID after it failed with a specific card. ie if it failed with a deleted card, it would retry by just using the customer id and therefore would use the new default card. This was removed in a later version when Subscriptions added its own retry system though.
Because that feature has been removed, I would suggest this change be added to the Stripe plugin. The Stripe plugin is better placed to handle this because:
>- it adds that option to make changes to the saved cards from the My Account page.
>- it knows what meta needs to change (if for instance, the meta keys changed in the future, for whatever reason, Subscriptions wouldn't need to be updated)

#### Steps to reproduce the issue

- A user purchases a subscription using Card A. - Card A is added on their Stripe profile.

- They go into member's area and adds a new card (Card B). Card B is added on ther Stripe profile.

- The user marks the card as default on member's area.

- The user removes Card A from member's area.

-------------------

- [x] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

**Comment by sittingduck83** [comment]
Any progress on this? We are getting this type of error a lot and worried we are losing subscriptions based on this problem. Any idea on how to handle this or how we could ask the customer to rectify this on their end?

**Comment by MrFent** [comment]
Yes, please provide a status update. I am getting failed renewals in my subscriptions because of this.

**Comment by barifit** [comment]
I am also having this exact same issue and have 11 failed renewals with more added everyday as many credit card companies issued new card due to recent breach.

**Comment by edie-etoile** [comment]
This is a major issue. Recurring payments are failing left and right because the Stripe plugin internal method does not work! When will this be address? Subscribers can't be assured that a changed payment method will actually result in the next automatic payment going through despite every reasonable attempt on their part to change their payment method. The wrong token is presented.

**Comment by roykho** [comment]
Can you folks please test this branch https://github.com/woocommerce/woocommerce-gateway-stripe/tree/issue-149 and see if this fixes your issues.

What it now does is when the payment fails, it will re-try again with customer's id instead.
