### ISSUE TITLE
Add hints or docs around webhook validation config

### ISSUE THREAD

**Issue by vbelolapotkov** [woocommerce/woocommerce-gateway-stripe#1496]
Webhook request validation was updated in #1493. It would be nice to add some docs or hints for merchants with recommended approach.

See https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1493#pullrequestreview-605297580 for more context.

**Comment by diegocurbelo** [comment]
The Webhook UI has been updated, and webhooks are (re)configured automatically since version `8.5.0`
