### ISSUE TITLE
Add T&C links to the Apple Pay checkbox

### ISSUE THREAD

**Issue by mattyza** [woocommerce/woocommerce-gateway-stripe#150]
For the Apple Pay settings checkbox, we're required to link to two terms of service URLs.

Let's swap this to a description below the checkbox, and link to the URLs, as follows:

https://stripe.com/apple-pay/legal
https://developer.apple.com/apple-pay/acceptable-use-guidelines-for-websites/

Text:

"By using Apple Pay, you agree to [Stripe](https://stripe.com/apple-pay/legal) and [Apple](https://developer.apple.com/apple-pay/acceptable-use-guidelines-for-websites/)'s terms of service."

@MarinaWoo - Does the above copy look alright to you?

cc @roykho

**Comment by MarinaWoo** [comment]
Looks good to me.

**Comment by tommyshellberg** [comment]
@roykho How's this look?

https://github.com/woocommerce/woocommerce-gateway-stripe/compare/fix-apple-pay-settings#diff-ca7c9cbe1db3fe97ca0d44f83aa44adaL144

**Comment by roykho** [comment]
@tommyshellberg - this is already done.
