### ISSUE TITLE
Add support for domain verification via Stripe

### ISSUE THREAD

**Issue by mattyza** [woocommerce/woocommerce-gateway-stripe#151]
In order to use Apple Pay for the Web, a verified domain is required with Apple. Stripe makes this easier (and free) by offering a domain verification service.

Docs: https://stripe.com/docs/apple-pay/web#going-live

Requirements:
- A Stripe secret key must be added and saved. Let's hide domain verification until a key is added.
- A [domain verification file](https://stripe.com/files/apple-pay/apple-developer-merchantid-domain-association) is to be added to the `/.well-known/` directory on the server. This should be available at `https://example.com/.well-known/apple-developer-merchantid-domain-association`.

The domain verification file is the same for all Stripe users, so we could bundle this file, and then move it to the correct location as part of verification.

- I'd propose we display admin notices while awaiting domain verification (so if Apple Pay is enabled, yet a domain is not verified).
- Lets run the verification process via an AJAX request, to create a smoother UX.
- If there are any errors, lets report those clearly. I suspect there may be errors with moving the domain verification file, and perhaps with making calls to Stripe's domain verification service.

Proposed UI elements:

![image](https://cloud.githubusercontent.com/assets/880803/22100553/c79bd798-de38-11e6-8703-a63a830fb22b.png)
Apple Pay is enabled, and the domain is not yet verified.

![image](https://cloud.githubusercontent.com/assets/880803/22100565/d1403f6e-de38-11e6-8365-acd695ea21a6.png)
Default state, once the domain is verified. Also a "success" response state.

![image](https://cloud.githubusercontent.com/assets/880803/22100587/dd241012-de38-11e6-8118-7cf0bb63d17c.png)
Something went wrong. Let's show an error message.

Thoughts on the above, @roykho, @kellychoffman, @jameskoster?

**Comment by mattyza** [comment]
@MarinaWoo @pmaiorana - Looping you in for your reference and feedback.

**Comment by roykho** [comment]
@mattyza - I am not 100% sure if this would work because the server/host may prevent a script on application level to be able to write to that area. Especially a "hidden" folder. I could be wrong but just thought I would mention that.

I will implement this and test it out on Pressable to see if it works there.

**Comment by madmath** [comment]
.well-known appears to be used for other cases as well, and looking around there's even a WP plugin that supports it. https://github.com/pfefferle/wordpress-well-known

Hope this helps :)

**Comment by mattyza** [comment]
@roykho - sure. If moving the file to the .well-known directory doesn't work, we can show a message with a link to instructions, and/or a link to the plugin @madmath recommended. :)
