### ISSUE TITLE
Question: How long can authorization to use credit card be stored? 

### ISSUE THREAD

**Issue by sahil48** [woocommerce/woocommerce-gateway-stripe#1510]
We are looking to authorize a charge at checkout for made or order products and it can sometimes take a few weeks to fulfill the order. Can credit cards for a customer be saved for usage on multiple orders? Can a card be authorized without expiring (ex. 1 month) until the order is fulfilled and then charged? If the above are problematic, what alternatives can be considered for this application.

**Comment by jessepearson** [comment]
@sahil48 for support inquiries like this, please use the support form found in your dashboard at WooCommerce.com.

To answer your question, though, an authorization will not work for you. Stripe can store a token for the credit card on the site for it to be used later. This happens in one of two ways:
* Customer makes a purchase and chooses to save their card to their account.
* Customer creates an account and then adds the card as a payment method.

With that, it is not possible for an admin to create an order and charge the customer directly. It is possible for the admin to use something like the User Switching plugin, and check out as the customer with the saved card, though.

Something else that might work is the [WooCommerce Deposits](https://woocommerce.com/products/woocommerce-deposits/) extension. This would allow the customer to pay a deposit up front, and then you would be able to generate a follow up order when the rest of the amount is due. The customer could then log in and pay that order.

Again, this is not an area for support, please reach out to the Happiness Engineers at WooCommerce.com for further questions.
