### ISSUE TITLE
Apply credit card icon filters in Blocks checkout

### ISSUE THREAD

**Issue by reykjalin** [woocommerce/woocommerce-gateway-stripe#1517]
We need to somehow [apply the `woocommerce_gateway_icon` filter](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/0c182f1dc17614207c5c559abcae220b9735882e/includes/class-wc-gateway-stripe.php#L206) here.

The non-block parts of the plugin provide a string to this filter that has a **very different structure**, so that's going to be difficult, but I think we need to provide parity here, and allow merchants to filter the accepted payment method icons.

We might have to introduce an entirely new filter for this, or somehow extract data out of a big string [full of `<img />` elements](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/0c182f1dc17614207c5c559abcae220b9735882e/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L212-L232).

It's potentially enough to just apply the [`wc_stripe_payment_icons` filter](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/0c182f1dc17614207c5c559abcae220b9735882e/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L212-L213) here, and maybe we should be applying the `woocommerce_gateway_icon` filter [in the frontend](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/0c182f1dc17614207c5c559abcae220b9735882e/client/blocks/credit-card/payment-method.js#L20-L30)?

Actually, @nerrad does the blocks extension apply the `woocommerce_gateway_icon` filter for us?

_Originally posted by @reykjalin in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1467#discussion_r601696163_

**Comment by reykjalin** [comment]
@nerrad made an excellent note about this in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1467#discussion_r613202948:

>Important to keep in mind, that the new checkout flow does not have the goal of parity with the previous shortcode flow in terms of compatibility and design. I realize you may be referring to compatibility in terms of sharing code between the flows, but I do encourage avoiding simply adding filters here because the shortcode flow has them. There's opportunity to think through why these filters are in place and whether the problem being solved can be solved in a way that preserves some of the direction being taken with the new flows.

I think Darren is right; is this something we want to enable? Is there a better way to get the same effect? What is this filter usually used for?

cc @v18

**Comment by reykjalin** [comment]
I'd like to ping both @v18 and @LevinMedia here to ask the question again:

1. Is allowing merchants to add custom credit card icons important enough to allow this in the Blocks checkout?
    - My initial impression is no, but maybe there are some merchants that like to either remove some icons or add their own?
    - Maybe this is important for theme authors that include custom made icons?
2. If yes, do we introduce a new filter or re-use the old one?
    - Keep in mind that the format for icon data is different in Blocks and Shortcode flows so we'd need to do some conversion magic with the old filter if we want to re-use it.

**Comment by nerrad** [comment]
Would there be any harm in releasing with the filter out and see if anyone asks for it? I only ask because we haven't accounted for that in the version included with Blocks and it's been that way for over a year without any complaints (that I know of) from users wanting it.

**Comment by LevinMedia** [comment]
@nerrad  No I don't think so - I'm leaning towards that for now. Additional discussion in p1621016731397600-slack-CGGCLBN58

**Comment by v18** [comment]
I'm aligned on not adding a way for merchants to turn off the icons. As Darren mentioned we haven't received any interest in this. Going to close this issue as `wontfix` for now and we can revisit this at a later date.
