### ISSUE TITLE
Fix zip code validation and state matching in Blocks checkout

### ISSUE THREAD

**Issue by reykjalin** [woocommerce/woocommerce-gateway-stripe#1518]
@reykjalin I didn't read all comments here, so forgive me if this was already discussed, but I was doing some testing in the Stripe plugin for the Cart block & Payment Request compatibility in WCPay, and I noticed the functions used to calculate shipping options in the Payment Request button are different with this integration.

The functions in `class-wc-stripe-payment-request.php` avoid some errors with zip code validation and state matching. E.g. if you try to calculate shipping for Ireland, Argentina or China, it will return an error saying the state is invalid.

_Originally posted by @ricardo in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1467#issuecomment-812317833_

**Comment by reykjalin** [comment]
The state matching is solved in #1467 but I'm not sure how to properly fix the zip code validation. I'm not even sure if that's something we have to do. That's going to require some further testing.

**Comment by reykjalin** [comment]
It seems there is no need to fix the zip code validation. The code we already have in place to do so works properly since it relies on a WooCommerce hook instead of anything fancier than that. Or at least that seems to be the case based on my testing.

@ricardo it'd be wonderful if you could verify that both the zip code validation and state matching have been fixed since you've worked on that in WCPay and Stripe before I worked on it here 🙏

**Comment by ricardo** [comment]
Yeah, zip code doesn't look like an issue to me.
