### ISSUE TITLE
wc_stripe_payment_request_params not defined on checkout block on non-default checkout page

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1525]
Steps to reproduce the behaviour:

1. Install the WooCommerce Blocks extension
2. Check out the branch `feature/support-block-checkout` from https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1467 (this is probably not a required step to repro)
3. Add a checkout block to a page that's not the default checkout page
4. Add a product to cart
5. Go to the non-default checkout page from step 3 above
6. See the payment request button not working with the error "This site is experiencing difficulties with this payment method. Please contact the owner of the site for assistance."
<img width="1165" alt="Screen Shot 2021-04-09 at 2 42 44 PM" src="https://user-images.githubusercontent.com/11487924/114134047-007cc400-9942-11eb-9084-2b61c2b64cf0.png">
7. See this error in the console: `ReferenceError: wc_stripe_payment_request_params is not defined`

The problem is that the script is not enqueued for just any page.

**Comment by ricardo** [comment]
Closing as it was merged in #1530. Apparently it didn't get closed automatically because it was merged into a different branch.
