### ISSUE TITLE
Google Pay Button's Popup render on Onpageload

### ISSUE THREAD

**Issue by merajali294** [woocommerce/woocommerce-gateway-stripe#1535]
Describe the bug
I’m trying to modify JS so that the Google Pay Button Popup Automatically loads once user comes to cart Page, but it does not work, can someone here check and fix this?

My use case is,
I want the Chrome PopUp to appear once the user clicks AddToCart in Single Product Page and then goes to Cart Page, and in this page I need Popup to appear so that he does the Payment right away,
I’m tweaking this part, prButton.mount( ‘#wc-stripe-payment-request-button’ );
But this mount function doesn’t allow me to use the window.addEventListener(‘load’, #wc-stripe-payment-request-button);

Please check this part and correct me so that Chrome Popup is enabled once user gets to Cart page,

Have implemented similar part here, it works, https://sravan523.com/api.php

Expected behavior
As I said it above I need this (https://i.imgur.com/S7pBqml.png) PopUP on page reload, it's quite simple, isn't it?
Thank you for your help!

Environment (please complete the following information):

WordPress Version 5.7
WooCommerce Version 5.1.0
Stripe Plugin Version 5.0.0
Browser chrome

Use Case:-

1. Let me explain you my requirement here, Once user does the AddToCart, Im sending them to my Custom Page where I want to render the PayNow PopUp so that he immediately selects Address and does the Payment.

**Comment by v18** [comment]
Hi there - it's not possible to open the dialog to pay before the customer clicks the "pay now" button. I recommend displaying the button on the product page, or adding the "pay now" button where the cart button is displayed to enable quicker checkout.

I'm closing this issue as a wontfix.
