### ISSUE TITLE
Allow account creation when checking out with Payment Request Button

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1537]
Background: We fixed issue #1352 by not showing the payment request button (Apply Pay, Google Pay, etc) when an account is required for checkout.

However, we'd like to be able to allow these buttons to show up, and guide the customer through account creation as part of the checkout flow with the payment request buttons.

This should work for both the shortcode & block checkout flows. Note that payment request buttons can be used on these pages:
- product page
- cart
- checkout

**Comment by v18** [comment]
Related: https://github.com/Automattic/woocommerce-payments/issues/1502

**Comment by v18** [comment]
Related: #1435

**Comment by leonclaus** [comment]
Hi, we are currently working on a fix for this. Please have a look at our proposal here and please provide feedback if possible:
https://github.com/woocommerce/woocommerce/issues/29867
Our solution would also include a fix for #1564.

**Comment by ricardo** [comment]
@leonclaus We're proposing a different solution in WooCommerce Payments [#1811](https://github.com/Automattic/woocommerce-payments/pull/1811) which later will be brought here in Stripe.

The solution is letting users know they need to authenticate first, then redirect them to "My account" and finally redirect them back to the product page after login.

This is a broader approach which also fixes issues where other settings might prevent from using express payment methods.
