### ISSUE TITLE
Spike: investigate the problem with ThreeDSecurePaymentHandler and open relevant issue

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1541]
Issue is described in this conversation: pc4etw-8L-p2#comment-519

**Comment by reykjalin** [comment]
This is related to #1573, and could potentially be handled in the same Spike PR. This is a piece of what's required to look into to properly wrap our heads around #1573.

**Comment by Mayisha** [comment]
We can close this issue. The `ThreeDSecurePaymentHandler` component is part of the legacy checkout experience and it is not used in the new checkout experience.
