### ISSUE TITLE
Email and Name variables aren't properly processed on Stripe

### ISSUE THREAD

**Issue by parvnoor** [woocommerce/woocommerce-gateway-stripe#1547]
Hi guys, on the stripe dashboard the Name and Email variables don't fill in, and instead you get the following:

<img width="680" alt="Screenshot 2021-04-30 at 11 19 31" src="https://user-images.githubusercontent.com/62034071/116682264-f16bbd80-a9a5-11eb-83bc-fca97f777ec0.png">

## What happens now

If you go to the frontend checkout as a shopper on Woocommerce Blocks,
Fill in the necessary fields and make a payment using the 'stripe' payment method (credit / debit card)
Go to the Stripe dashboard and check the processed payment
You should see that the name and email fields have not been captured properly.

## Expected behavior

What should be expected is that the first three fields which say 'Name, Guest' should show an email like the 4th item:
<img width="680" alt="Screenshot 2021-04-30 at 11 19 31" src="https://user-images.githubusercontent.com/62034071/116682264-f16bbd80-a9a5-11eb-83bc-fca97f777ec0.png">

## Environment

Woocommerce: Version 5.2.2
Woocommerce blocks: Version 5.0.0
Wordpress: Version 5.7.1

## Additional comments

Here is a message chain between me and the stripe team

**Me:** 
I recently changed my checkout on my wordpress site, however now you can see that the email addresses don't show next to each payment, though previously they were showing, prior to the checkout change
Stripe: Got it, thanks for the info. Let me pull up the payments on our side to see the reason for this and analyze how to change it. It could be the case that the checkout is using the wrong variable from the API

**Stripe:** 
Thanks for your patience.
It seems that it is indeed the case, the checkout is using the incorrect variable. We're receiving the customer's email as metadata, while it should be included in the email parameter for us to show it for the payments.
You can see this by comparing a payment that shows the customer's email with one that only shows as guest. 

https://v2uploads.zopim.io/R/m/R/RmREdxtJY6wntrxzsaDPMTQeaAlLN7H0/bdb8ce01d4e8df446d0e0ce8bae64e31fcdeb4

While this payment does not include the customer's email address in this parameter, but instead as metadata:

https://v2uploads.zopim.io/R/m/R/RmREdxtJY6wntrxzsaDPMTQeaAlLN7H0/5bc005da992bab268029ad61bc9f521202b7d320.png

When this happens, our system doesn't know what is the customer's email. Thus, it is not shown in your Dashboard for the payment.

**Me:** 
So how do I fix this?

**Stripe:**
Depending on how you integrated your payments, it will be necessary to work either with your developer or third party to resolve this. This is because this part of the integration is managed from your website, which is where the customer enters the info and it is passed to us.
As long as the customer's email is included in the correct parameter, we'll show the info always. For example, in your Dashboard, receipts, invoices, notifications, etc...

**Comment by parvnoor** [comment]
Hey, thanks for the swift response.

I was using stripe with the previous default checkout, yup.

The plugin is WooCommerce Stripe Gateway (https://wordpress.org/plugins/woocommerce-gateway-stripe/) - should I try the WooCommerce Stripe extension instead?

**Comment by weroh** [comment]
Hi, we're experiencing this same issue on our storefront. I haven't been able to determine whether or not we're using Woocommerce Blocks or not. We were using another payment processor up until recently and switched over to Stripe. This issue happens intermittently for us. It's not all transactions. I can provide more details as needed. If this is a bug, then we'll wait for a fix. If this is an issue on our end, then we may start developing a solution.
