### ISSUE TITLE
Safari "Allow websites to check for Apple Pay" setting have to be disabled in order Apple Pay button appears.

### ISSUE THREAD

**Issue by kalessil** [woocommerce/woocommerce-gateway-stripe#1548]
**Describe the bug**

See https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1111. The issue is still there: p1619724791069000-slack-C7U3Y3VMY (see the thread for sample URLs)

**To Reproduce**

- Use Safari with the setting enabled
- Open the sample URLs in private mode (the button expected to appear on both sites)
- Open the sample URLs in normal mode (the button expected to appear only on one site)

**Comment by ServusNL** [comment]
Any update on this? I have the same problem. aPay button only showing in private browsers. Is the issue confirmed? 

My problem appeared to be in the domains. Deleted all domain mentions, added new for both domain.xx and www.domain.xx, manually added the verification file to the /.well-known/ folder, and now my config is working again.

To be clear, I had the same problem that aPay was working in a private browser.

**Comment by aheckler** [comment]
Same thing here: https://wordpress.org/support/topic/apple-pay-not-displaying-when-safari-set-to-show/

Having them try this: https://woocommerce.com/document/stripe/#section-46

**Comment by aheckler** [comment]
4684545-zen

EDIT: This user said:

> Updated: after remove the domain from Apple Pay settings in Stripe and add it again, the Apple Pay both shows on desktop and mobile

**Comment by aheckler** [comment]
4718808-zen

**Comment by aheckler** [comment]
4749764-zen

**Comment by wyter** [comment]
4793814-zen

**Comment by csmcneill** [comment]
This issue also affects merchants using WooCommerce Payments. Separate issue created in that repo here: https://github.com/Automattic/woocommerce-payments/issues/3876

**Comment by csmcneill** [comment]
35269229-hc

We resolved this by:

1. Going to Apple Pay management in Stripe dashboard: https://dashboard.stripe.com/settings/payments/apple_pay
2. Removing the existing Apple Pay domain.
3. Adding it again inside the dashboard.

We did not need to re-upload the domain verification file. The only issue is that their browser was caching their site. Viewing in a private Safari browser or on a mobile device resolved the issue.

**Comment by AashikP** [comment]
Another example in 5220976-zen. In my test site, using a simulator, I had to disable this option for Safari (iOS) to view the payment button:

![image](https://user-images.githubusercontent.com/17475174/169186306-b9a0d48e-fad0-4a96-860e-079b08957c9e.png)

**Comment by thuautp** [comment]
Also reported in 5248116-zen

**Comment by thisissandip** [comment]
33410688-hc

The [workaround](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1548#issuecomment-1107920101) from @csmcneill worked for the merchant.

**Comment by aheckler** [comment]
5330148-zen

**Comment by ericfri** [comment]
5467803-zen

**Comment by ericfri** [comment]
5489647-zen

**Comment by marissaexplores** [comment]
5526436-zen

Suggesting that the merchant try the [workaround](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1548#issuecomment-1107920101) from @csmcneill

**Comment by stuartduff** [comment]
5533075-zen

**Comment by amElnagdy** [comment]
5539171-zen

**Comment by amElnagdy** [comment]
5530251-zen - the workaround from this [reply](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1548#issuecomment-1107920101) fixed the issue.

**Comment by wpniall** [comment]
5556835-zen

**Comment by Brianmitchtay** [comment]
5560755-zen

**Comment by wpniall** [comment]
5577785-zen - Shared csmcneill's steps above, which are now found in the Stripe plugin's docs here: https://woocommerce.com/document/stripe/#apple-pay-button-only-shows-in-private-incognito-safari-window

**Comment by shiki** [comment]
Update on 5526436-zen: The workaround described in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1548#issuecomment-1107920101 did not work for them.

**Comment by MariaChek** [comment]
5616150-zen - I was able to replicate this issue on the customer's staging site (the issue disappears if I open it on a private window), but not on the live site. I asked them to follow the workaround for the staging site, and we will also be looking into a possible conflict, as the staging site has different plugins/theme.

**Comment by dreamtooloud** [comment]
> 5616150-zen - I was able to replicate this issue on the customer's staging site (the issue disappears if I open it on a private window), but not on the live site. I asked them to follow the workaround for the staging site, and we will also be looking into a possible conflict, as the staging site has different plugins/theme.

In regards to 5616150-zen ,  I don't think this is related to the bug. They have one product on their site and it is a `course` type product.  [According to the Stripe documentation](https://woocommerce.com/document/stripe/#what-type-of-products-can-be-purchased-with-the-payment-request-button), express checkout buttons are compatible with `simple` , `variable` , and `subscriptions` product types only. When I created a test simple product on this user's staging site, the Apple Pay button did show up in a normal Safari window.

**Comment by ericfri** [comment]
5620004-zen

**Comment by ericfri** [comment]
5716902-zen - The workaround worked for this merchant.

**Comment by ericfri** [comment]
5791065-zen

**Comment by Mxchael** [comment]
5790516-zen

**Comment by thisissandip** [comment]
5880255-zen - workaround fixed it

**Comment by ericfri** [comment]
5947966-zen

**Comment by jrick1229** [comment]
5957616-zen

**Comment by Brianmitchtay** [comment]
6005980-zen

**Comment by Brianmitchtay** [comment]
6561770-zen, The workaround from [@csmcneill's comment above](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1548#issuecomment-1107920101) did not resolve the issue

**Comment by thuautp** [comment]
7292301-zen

**Comment by bogdanailincaipnt** [comment]
I am not using Stripe or Woo, yet I am having the same problem. I use Nuvei as the payment processor. I haven't found a solution, but here is an explanation of what happens, by [Brave Leo AI](https://brave.com/leo/):

<img width="1110" alt="Screenshot 2023-11-24 at 12 13 40" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/93596663/6fdfd392-be18-42f4-b1bf-562d0430a7cc">

**Comment by bogdanailincaipnt** [comment]
I just found a fix for my problem. I was sending the `merchantSiteId` instead of `merchantId` to the [ApplePaySession.canMakePaymentsWithActiveCard()](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaysession/1778000-canmakepaymentswithactivecard) function call.

**Comment by mattallan** [comment]
Hi all, I'm revisiting old issues labelled with `priority:high` to determine if these bugs are still present.

With that said, **I haven't been able to reproduce this issue on the latest Stripe extension.**

---

Given there hasn't been any recent reports of this one, I'm going to close this in favour of opening a new issue if it occurs again.

FWIW Here are my findings from testing. On both iphone and safari browser, the apple pay button was loading when the "check for apple pay" was enabled.

### Using iPhone

| Settings | Apple Pay Button |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/7437d217-1668-4cbc-b450-564ee50edc90)| ![image](https://github.com/user-attachments/assets/4c7d63b4-e360-40d3-bd17-1c6b9334146e) |



### Using Safari browser

| Settings | Apple Pay Button |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/74128342-2f57-4206-a631-1be8d4c40ce9) | ![image](https://github.com/user-attachments/assets/987e7660-5cfc-4117-861d-6a2fa2962448)|
