### ISSUE TITLE
Settings: introduce individual toggles for the pay buttons

### ISSUE THREAD

**Issue by kalessil** [woocommerce/woocommerce-gateway-stripe#1549]
In the stripe dashboard under `Settings -> Checkout -> Customize checkout -> Accelerated checkouts` it's possible to enable the pay buttons individually. It would be great to have similar settings on the gateway side as well.

**Comment by igotdes** [comment]
Just adding that this feature was requested from #3934134-zen so we can inform the user of any significant updates.

**Comment by dechov** [comment]
Looks like we could expose a setting that configures the payment request's `disableWallets` property [[API doc](https://stripe.com/docs/js/payment_request/create#stripe_payment_request-options-disableWallets)] 👍 

(Those Stripe Dashboard settings appear to control the behavior of Stripe Checkout, which isn't currently supported by the extension.)

**Comment by a-danae** [comment]
Closing this issue as we won't introduce this enhancement for now. We can always reopen it in the future if needed.
