### ISSUE TITLE
php_uname() throwing unnecessary warnings

### ISSUE THREAD

**Issue by dhafner** [woocommerce/woocommerce-gateway-stripe#1566]
**Describe the bug**
If the server has disabled the function _php_uname()_ the following warning is thrown whenever the plugin is called, eg during checkout.

`PHP Warning: php_uname() has been disabled for security reasons in /home/wp/disk/wordpress/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-api.php on line 69` 

**To Reproduce**
Disable php_uname() and use the plugin.

**Expected behavior**
`'uname' =>  (!function_exsists('php_uname')) ? false:php_uname(),`
Disabling php_uname() for security reasons is absolutely fine. So the plugin should check if the function is available.

**Environment (please complete the following information):**
 - WordPress Version 5.7.2
 - WooCommerce Version 5.3.0
 - Stripe Plugin Version 5.1.0

**Comment by Mingendahl** [comment]
Can confirm this annoys me, too ;-)
It's super simple to fix. Would be happy, I you find the time

**Comment by ChristophGeier** [comment]
+1

**Comment by t0b1hh** [comment]
+1

**Comment by kaushikasomaiya** [comment]
- 5845810-zen 

- https://wordpress.org/support/topic/plugin-causing-critical-error-on-website-2/
