### ISSUE TITLE
Logos for alternative payment methods misaligned when Credit Card payment deactivated

### ISSUE THREAD

**Issue by theabhig** [woocommerce/woocommerce-gateway-stripe#1575]
**Describe the bug**

Using Stripe, when credit card payment is deactivated but Stripe alternative payment options are active, the logos for the alternative payment methods become misaligned.

This happened on a user site, tested internally in Slack, and also on my own test installation.

**To Reproduce**

1. Activate Stripe as payment gateway on WooCommerce site using Storefront theme.
2. Deactivate `Stripe – Credit Card (Stripe)` and activate an alternative payment method such as iDeal, SEPA or Multibanco.
3. Add items to cart and proceed to checkout.
4. On the payment options, the icons will be misaligned as in the below screenshots.

<details>
<summary>
SSR
</summary>
**Environment (please complete the following information):**

`
### WordPress Environment ###

WordPress address (URL): https://theabhigwoofit.mystagingwebsite.com
Site address (URL): https://theabhigwoofit.mystagingwebsite.com
WC Version: 5.3.0
REST API Version: ✔ 5.3.0
WC Blocks Version: ✔ 4.9.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.2.6
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.18
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.76.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.22-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.3.0
WC Database Prefix: wp_
Total Database Size: 10.29MB
Database Data Size: 5.74MB
Database Index Size: 4.55MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.23MB + Index: 0.20MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.48MB + Index: 0.45MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.31MB + Index: 0.25MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.11MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 0.80MB + Engine InnoDB
wp_posts: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
aw_workflow: 2
bookable_person: 4
bookable_resource: 3
custom-css-js: 1
fgf_rules: 1
follow_up_email: 4
gtw_custom_fields: 3
gtw_rules: 3
page: 11
post: 1
product: 50
product_variation: 24
revision: 21
shop_coupon: 86
shop_order: 88
shop_subscription: 29
wc_booking: 15
wc_membership_plan: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 5.2.0
WooCommerce: by Automattic – 5.3.0

### Inactive Plugins (35) ###

Akismet Anti-Spam: by Automattic – 4.1.9
AutomateWoo: by WooCommerce – 5.4.0
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.1
Code Snippets: by Code Snippets Pro – 2.14.1
Follow-Up Emails: by WooCommerce – 4.9.13
Free Gifts for WooCommerce: by FantasticPlugins – 6.8
Gift Wrapper for WooCommerce: by FantasticPlugins – 3.0
Jetpack by WordPress.com: by Automattic – 9.7
Simple Custom CSS and JS: by SilkyPress.com – 3.36
Smart Product Bundles For WooCommerce: by wpexpertsio – 1.1.4
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.24
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.26
WooCommerce Blocks: by Automattic – 5.1.0
WooCommerce Bookings: by WooCommerce – 1.15.37
WooCommerce Bookings Availability: by WooCommerce – 1.1.18
WooCommerce Composite Products: by SomewhereWarm – 8.0.2
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.9.3
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.3.2
WooCommerce Deposits: by WooCommerce – 1.5.6
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.14
WooCommerce Memberships: by SkyVerge – 1.21.4
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.20
WooCommerce One Page Checkout: by Automattic – 1.7.11
WooCommerce PayFast Gateway: by WooCommerce – 1.4.18 (update to version 1.4.19 is available)
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce PayPal Payments: by WooCommerce – 1.3.1
WooCommerce Points and Rewards: by WooCommerce – 1.6.43
WooCommerce Product Add-ons: by WooCommerce – 3.5.0
WooCommerce Product Bundles: by SomewhereWarm – 6.8.0
WooCommerce Product Vendors: by WooCommerce – 2.1.49
WooCommerce Smart Coupons: by StoreApps – 4.19.0
WooCommerce Square: by WooCommerce – 2.3.4 (update to version 2.5.1 is available)
WooCommerce Subscriptions: by WooCommerce – 3.0.13
WooCommerce Subscriptions - Delete Cancel Subscription Confirmation: by Prospress Inc. – 1.0
WooCommerce Xero Integration: by WooCommerce – 1.7.37

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
bundle_product (bundle_product)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 3
Oldest: 2021-05-05 08:37:09 +0000
Newest: 2021-05-10 13:01:42 +0000

Complete: 1,273
Oldest: 2021-04-19 09:26:00 +0000
Newest: 2021-05-20 08:11:46 +0000

Pending: 56
Oldest: 2021-05-20 08:13:12 +0000
Newest: 2022-05-15 08:09:58 +0000

### Status report information ###

Generated at: 2021-05-20 08:11:58 +00:00
`
</details>

**Expected behavior**

Expected behavior:

![Annotation%20on%202021-05-20%20at%2009-08-43](https://user-images.githubusercontent.com/52214/186419189-41652c9c-0da3-42a2-a474-55ef42fc2306.png)

**Screenshots**

Layout with `Stripe – Credit Card (Stripe)` deactivated.

![Layout with `Stripe – Credit Card (Stripe)` deactivated.](https://user-images.githubusercontent.com/52214/186419327-3cf47ed6-6453-4cf0-8ad4-5379235bd9d7.png)

User site

![User site](https://user-images.githubusercontent.com/52214/186419558-705920b2-1f14-49b6-91ce-421327cf7321.png)

Internal test
![Internal test](https://user-images.githubusercontent.com/52214/186419832-6c758626-3fa0-4cc6-b7fa-0a4a78a7117e.png) 

**Additional context**

First reported in 3999258-zen.

Tested locally in Slack thread: p1621496533338200-slack-C3NCP7ZJ6

**Comment by dougaitken** [comment]
This only happens with the standard (old) payment methods, not UPE.

Still happening with Stripe `6.6.0`

**Comment by grig-23** [comment]
https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2416

**Comment by wjrosa** [comment]
Closing as this affects only the legacy checkout.
