### ISSUE TITLE
Apple pay button don't show on iphone

### ISSUE THREAD

**Issue by val711** [woocommerce/woocommerce-gateway-stripe#158]
Hi, 

I have some trouble with the plug-in. Indeed i have followed all the steps with my Stripe account but when i go on my iphone to show the apple pay button on my website, i see nothing. 

On my desktop computer i see the apple pay button is there with the css but don't show on mobile. 

I saw an issue in which you say we need to have an apple beta tester account but what does that mean? It means, in the plug in, apple pay function is just for test? it doesn't work in "live"? 

Thanks for your reply

**Comment by brunocrosier** [comment]
This plugin is for Stripe (www.stripe.com) , not Braintree

**Comment by val711** [comment]
Yes my mistake, i use stripe so i would like to say "with my stripe account"

**Comment by roykho** [comment]
Yes it works for live. Make sure your site is under SSL and you actually have Wallet setup on your iPhone with credit cards.

**Comment by val711** [comment]
My bank doesn't support apple pay yet, so i cant configure it on my iphone. But i juste wanted to see if all works on my website. It's meens the button will not show if you don't have apple pay configured on the phone? 

I tried with an other website which support apple pay, and i see the black button

**Comment by brunocrosier** [comment]
This also happened to me ... I have apple pay fully set up on my phone, but when i navigate to the Cart page on my site, it doesnt show the apple pay logo (but it does create a blank space which brings up the apple pay dialog if you click on it) 

Not sure if its a theme issue?

**Comment by val711** [comment]
Not really, 

I see nothing even if i click on a blank space. But when i am on my computer, with the css inspector, i see apple pay button is here... 

I have follow this tutorial to set up the plug in : http://chrislema.com/woocommerce-apple-pay-integration/

**Comment by val711** [comment]
Thanks for the answers

**Comment by roykho** [comment]
@val711 what is the link to your website?

**Comment by val711** [comment]
ted-berslay.com

**Comment by roykho** [comment]
@val711 - this is what I see on your site with my iPhone ![](http://cld.wthms.co/SCyT/s2rHCCoo+)

**Comment by val711** [comment]
Thank you, I still see nothing. May be the reason is i don't have apple pay configured on my iphone, i don't know. 
So thanks again!

**Comment by roykho** [comment]
@val711  And make sure you're using Safari as your browser. It only works on Safari.

**Comment by val711** [comment]
Yes i am using Safari, Thanks for your support
