### ISSUE TITLE
Hide Apple Pay button when all variations are out of stock

### ISSUE THREAD

**Issue by stephhjacq** [woocommerce/woocommerce-gateway-stripe#1580]
4014744-zen

**Describe the bug**
When all variations are out of stock, payment request button is shown even though item cannot be added to cart.

**To Reproduce**
1. Create a variable product and set all variations to out of stock
2. Visit product page, see Apple Pay button
3. Select any variation to see out of stock message
4. Click Buy with Apple Pay, error dialogue appears.

**Expected behavior**
Payment request buttons are hidden when all variations are out of stock, to match behaviour of simple product pages. 

**Screenshots**

Error shown after clicking Buy with Apple Pay:
![https://d.pr/i/XiG65J](https://d.pr/i/XiG65J+)
Full Image: https://d.pr/i/XiG65J

Simple product page for out of stock item, Apple Pay is hidden:
![https://d.pr/i/89Tr5e](https://d.pr/i/89Tr5e+)
Full Image: https://d.pr/i/89Tr5e

**Environment (please complete the following information):**
 - WordPress Version 5.7.2
 - WooCommerce Version 5.3.0
 - Stripe Plugin Version 5.2.0
 - Browser [e.g. chrome, safari] and Version Safari Version 14.1 (16611.1.21.161.3)

**Comment by stephhjacq** [comment]
Issue does not appear to affect Google Pay in Chrome, which is hidden as expected for product with all variations out of stock.

**Comment by v18** [comment]
> When all variations are out of stock, payment request button is shown even though item cannot be added to cart.

<img width="459" alt="unavailable" src="https://user-images.githubusercontent.com/11487924/119456037-356b9b80-bd75-11eb-96fa-1a41fecbd5a4.png">

:trollface:

**Comment by stephhjacq** [comment]
@v18 I'm not sure what you mean by this face, could you expand on that?

**Comment by v18** [comment]
@stephhjacq - sorry for the confusion. I was just pointing out how silly this UX is :)
