### ISSUE TITLE
Configurable payment request button locations

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1586]
Allow merchants to configure payment request button locations using settings instead of using filters.

Related issue in WCPay: https://github.com/Automattic/woocommerce-payments/issues/1475

PR in WCPay: https://github.com/Automattic/woocommerce-payments/pull/1584

**Comment by asumaran** [comment]
@reykjalin I think we can close this now?

**Comment by reykjalin** [comment]
Ah yes, I didn't realize this was still open! This was fixed in #1672
