### ISSUE TITLE
Update `tested up to` more regularly

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#1595]
**Describe the bug**

With WooCommerce being released on a monthly cadence for some time now, the `tested up to` for Stripe is outdated and is one of the more common plugins that customers ask about compatibility. 

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/08362113e6af5f91768c20a94d08ecdbc12c85f3/woocommerce-gateway-stripe.php#L12

The `tested up to` versions have been `4.2`, `4.3`, `4.9, `5.0` and it has remained on this since the Stripe `4.9.0` release on 24th Feb.

Given the last two updates to the Stripe were specifically released due to bugs related to compatibility with the core WooCommerce plugin, can we look at ensuring the `tested up to` is updated more often, please?

**Comment by thenbrent** [comment]
Closing this as tested up to is now at `7.6` and I believe this should be handled by `woorelease` automatically now.
