### ISSUE TITLE
Twenty Twenty-One: Stripe error messages have styling issues

### ISSUE THREAD

**Issue by ldr2273** [woocommerce/woocommerce-gateway-stripe#1612]
**Describe the bug**
When using Stripe with Twenty Twenty-One theme, error messages are displayed poorly.

**To Reproduce**
1. Install and activate Stripe with Twenty Twenty-One theme.
2. Add a product to cart/checkout, and enter a test card with a past expiry date to force an error.
3. Notice the poor styling of the error message.
4. Test with Storefront next and repeat. Error is displayed clearly.

**Expected behavior**
For Stripe error messages to display properly on Twenty Twenty One.

**Screenshots**
Stripe error with Twenty Twenty-One:

![Stripe error](https://d.pr/i/cZMRA8+)
Link: https://d.pr/i/cZMRA8

Stripe error with Storefront:

![Stripe error](https://d.pr/i/p7iZZ7+)
Link: https://d.pr/i/p7iZZ7

**Environment (please complete the following information):**
 - WordPress Version - 5.7.2
 - WooCommerce Version - 5.4.1
 - Stripe Plugin Version - 5.2.3
 - Browser [e.g. chrome, safari] and Version - Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by dechov** [comment]
Looks like Twenty Twenty:
<img width="395" alt="stripe-validation-error-twenty-twenty" src="https://user-images.githubusercontent.com/1867547/123519882-db177080-d67b-11eb-9b89-b309d07609ee.png">

…though the overall form has some room for improvement in Twenty Twenty-One as well:
<img width="419" alt="stripe-validation-error-twenty-twenty-one" src="https://user-images.githubusercontent.com/1867547/123519881-da7eda00-d67b-11eb-8d1c-5367e3013e18.png">

**Comment by andyb2000** [comment]
thanks, and how do I solve this as it's only in the stripe woocommerce that I have this error? If i just need to adjust the css or similar any pointers as I cannot see how to fix?

**Comment by nielslange** [comment]
@andyb2000 I'd say adjusting the CSS is sufficient to solve this problem. You could do that using the CSS prefix `.theme-twentytwenty`, to target only the Twenty Twenty theme.

**Comment by Mayisha** [comment]
Confirming that the error message is displayed nicely in Twenty Twenty-one and Twenty Twenty-five.


## Twenty Twenty-one theme

### Block checkout (error displayed on top of the payment element)

Legacy checkout experience           |  New checkout experience
:-------------------------:|:-------------------------:
![Image](https://github.com/user-attachments/assets/f5e9f0c4-76a3-44e3-bffa-c102f95de64a)  |  ![Image](https://github.com/user-attachments/assets/60003fa6-b589-4d27-b2e2-1545570ac871)

### Shortcode checkout (error displayed on top of the page)

Legacy checkout experience           |  New checkout experience
:-------------------------:|:-------------------------:
![Image](https://github.com/user-attachments/assets/cba0628b-8ad3-4097-a800-5562fa6f5f86)  |  ![Image](https://github.com/user-attachments/assets/6f31eb52-68cd-4d6c-9117-7716af93c753)




## Twenty Twenty-five theme

### Block checkout (error displayed on top of the payment element)

Legacy checkout experience           |  New checkout experience
:-------------------------:|:-------------------------:
![Image](https://github.com/user-attachments/assets/172bce7e-4c6b-44a8-9d3b-e2197b5b674d)  |  ![Image](https://github.com/user-attachments/assets/f43bb0d9-6865-4751-8f68-18ce1c12f589)

### Shortcode checkout (error displayed on top of the page)

Legacy checkout experience           |  New checkout experience
:-------------------------:|:-------------------------:
![Image](https://github.com/user-attachments/assets/32a016bc-f88d-4c1e-b1a0-8392d9677ffe) |  ![Image](https://github.com/user-attachments/assets/a93d9f05-7d75-447e-99f3-8b033cbc3888)
