### ISSUE TITLE
Gateway svg icon images do not display request new filter on get_icon() function

### ISSUE THREAD

**Issue by clariontools** [woocommerce/woocommerce-gateway-stripe#162]
Expected to see the credit card icons.

The icons do not appear because of some browser issues when displaying .svg images, need inline-block;.

You could add the inline-block; to the style if 2.6 or higher, but it would it would be wonderful to have a filter so we could do additional styling and fix any issues like those I have seen with .svg image display.  Please consider adding a filter in class-wc-gateway-stripe.php on the get_icon() function similar to below:

	public function get_icon() {
		$ext   = version_compare( WC()->version, '2.6', '>=' ) ? '.svg' : '.png';
		$style = version_compare( WC()->version, '2.6', '>=' ) ? 'style="margin-left: 0.3em"' : '';
		$style = apply_filters( 'woocommerce_gateway_icon_style', $style, $this->id );

Thank you for your consideration.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
There is already a filter you can use https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L254

**Comment by clariontools** [comment]
Not exactly the same thing, I am talking about a filter for the $style variable since you have hard coded the style="margin-left: 0.3em" for 2.6 or higher with .svg images.  The filter you added will force me to do a search and replace on the full img tag string rather than simply overriding the $style variable.  It is a shame to have to hack the plugin on every update or resort to string search and replace to override a hard coded style, sorry for asking...

**Comment by roykho** [comment]
Why do you need to do a "search and replace" with the filter we've provided? You can use the filter to generate your own icons completely bypassing the defaults one.

**Comment by clariontools** [comment]
That is true, but it seems a bit much to replicate all the code in get_icon() in my filter if all I need to do to fix the .svg display issue is to change the style.  The issue is really revolving around the hard coded $style and the lack of inline-block; that causes .svg images to not appear.

**Comment by clariontools** [comment]
Again, the issue is not the ability to generate replacement icons or bypassing the defaults, it is all about the inline style that you are applying to the img tag.  The hardcoded style you apply does not contain the property required for .svg images that is needed for proper display on some browsers.  Not sure how else I can put this, but again sorry to bother you, I will spend less time trying to explain the need for this versus adding my own filter on each new release.  Cheers.
