### ISSUE TITLE
Payment Request buttons allowing orders in countries that are blocked from purchases in settings

### ISSUE THREAD

**Issue by edequalsawesome** [woocommerce/woocommerce-gateway-stripe#1620]
**Describe the bug**
When a country has been blocked from store sales from `WooCommerce > Settings > General`, completing orders using payment request buttons will still work in those countries

**To Reproduce**
1. Go to `WooCommerce > Settings > General`
2. Under `Selling Options`, choose `Sell to all countries except for`, and block purchases from the United States (or any location where you can use payment request buttons)
3. Save settings
4. Attempt to purchase a product from the U.S. (or whatever location you chose in step 2) using a payment request button

**Expected behavior**
The purchase would be blocked since it came from the U.S.

**Screenshots**
Setting on my test site to block sales from U.S.:
<img width="730" alt="Sell Except for United States" src="https://user-images.githubusercontent.com/4000628/124324713-6c418800-db51-11eb-91ba-9efd961374d8.png">

Apple Pay modal working on my test site:

![Pay with Apple Pay](https://user-images.githubusercontent.com/4000628/124324872-add23300-db51-11eb-8dc6-3839ec5e5816.png)

Order completed successfully:

![Order Completed](https://user-images.githubusercontent.com/4000628/124324980-e07c2b80-db51-11eb-95e9-cd6b65addfdd.png)

**Environment (please complete the following information):**
 - WordPress Version: 5.7.2
 - WooCommerce Version: 5.4.1
 - Stripe Plugin Version: 5.2.3 
 - Browser [e.g. chrome, safari] and Version: Safari 14.1.1 (16611.2.7.1.4) & Chrome 91.0.4472.101
 - Any other plugins installed: Duplicated with only WooCommerce/Stripe Payment Gateway/Storefront active

**Additional context**
Originally reported in #4112231-zen

**Comment by dougaitken** [comment]
hey @edequalsawesome

I appreciate some time has passed since the original comment, thanks for your patience. I’ve been unable to replicate the issue you described using the latest release of the core WooCommerce plugin and the [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/).

As I’m unable to reproduce this, I’m marking this Issue as Closed. Please do open a new one if you are able to reproduce this again.
