### ISSUE TITLE
Spike: Any issues when switching from current payment method to UPE?

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1621]
When a merchant switches from using their current payment methods in the Stripe extension (credit card, Apple Pay, sofort, SEPA, etc) to using them in UPE, are there any issues they can run into for each payment method?

The payment methods we currently support are listed here: pc4etw-9M-p2 (under "LPMs currently supported in Stripe")

What are the considerations to switching to using UPE & switching back for an existing merchant? Both in terms of their Stripe extension experience and their experience in the Stripe dashboard / settings.

**Comment by v18** [comment]
Additional question:

If a merchant switches back from UPE to legacy payment methods, will we be able to re-enable the previous legacy payment methods for the merchant in the same way they were before?

Reference: pc4etw-ch-p2#comment-689

**Comment by EvanDotPro** [comment]
Handled in #1654.

Switching UPE on or off transparently preserves whatever payment methods are currently active.

There _may_ be one tiny edge case, mentioned at the bottom of my comment [here](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1688#issuecomment-904725575).
