### ISSUE TITLE
Spike: When UPE enabled, possible to not show payment methods in main payment settings list?

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1622]
When a user has UPE enabled, we'd like to remove the usual payment methods from the main payment methods list under WooCommerce > Settings > Payments (`wp-admin/admin.php?page=wc-settings&tab=checkout`):

<img width="696" alt="woocommerce-payments-settings" src="https://user-images.githubusercontent.com/11487924/124338341-5039f700-dbe2-11eb-9c50-e96faaedfe55.png">

Instead, we'll want to add this toggle list in the current Stripe settings, under WooCommerce > Settings > Payments > Stripe (`wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe`):

![woocommerce-stripe-settings](https://user-images.githubusercontent.com/11487924/124338369-8d9e8480-dbe2-11eb-9d3a-f133d0210370.jpeg)

Notes:
- We'll want to remove all the payments methods on this list that can be used with UPE. So, for example, Multibanco won't be removed since it can't be used with UPE.

Questions:
- Is this possible to do? Are there any caveats / gotchas?

**Comment by EvanDotPro** [comment]
> Is this possible to do?

Yes. :)

**Comment by EvanDotPro** [comment]
> Are there any caveats / gotchas?

None encountered so far.

Implemented [here](https://github.com/woocommerce/woocommerce-gateway-stripe/commit/ae9e7b02a0b671d8ea5c964d355510273358b9b0).

Without UPE enabled:
![](https://caps.evan.pro/0c60df.png)

After enabling UPE:
![](https://caps.evan.pro/8129be.png)
