### ISSUE TITLE
Save Payment Method

### ISSUE THREAD

**Issue by peterwilson86** [woocommerce/woocommerce-gateway-stripe#1626]
The param: "save_payment_method": "true", doesnt appear in the default Woocommerce - Stripe API.

Can I get help in adding so we can see the customer card details in our Stripe backend and use to recharge on other part of customer payment at a later date once payment terms have lapsed

A screenshot attached showing the param is missing from an earlier transaction

![778fe78c4c78dda9e9b3f996a5cf779878a8630c](https://user-images.githubusercontent.com/87027800/124624936-43810180-de75-11eb-8b53-10b9f7a20b07.png)

**Comment by dougaitken** [comment]
Hey @peterwilson86 

I appreciate this is now over a year old, we're working to speed up the Issue discussions and resolution.

As there hasn’t been any activity on this Issue after your initial post, I’m going to close this Issue.

> and use to recharge on other part of customer payment at a later date once payment terms have lapsed

It reads like you're looking for functionality that falls outside the current or future functionality of the plugin, and would require customization to fit your needs.

If this is still a requirement for your site, for assistance with customization or development with your site, we recommend reaching out to someone on our [customizations page](https://woocommerce.com/experts/) as we're not able to offer that help here.

Thanks
