### ISSUE TITLE
Use Stripe API to save statement descriptor, to catch any blocked words

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1627]
Steps to repro bug:
1. Go to Stripe settings (`wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe`)
2. Add "example" to your statement descriptor
3. See that it gets saved (this is a problem - should show an error, ideally coming from the Stripe API)
4. Purchase a product on your store
5. Go to the payment in the Stripe dashboard. See that the payment's statement descriptor contains the blocked word.

Some more details here: pc4etw-bL-p2

Related in WooCommerce Payments: 939-gh-Automattic/woocommerce-payments-server

Related, previous issue in Stripe: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1262

We previously fixed a similar problem by checking against blocked characters in the Stripe extension. Instead, it would be better to use the Stripe API so that we don't need to update the plugin when there are future changes to the block list.

**Comment by ricardo** [comment]
Unlike in WCPay, it's not possible to use the Stripe API to save the statement descriptor to the account, and therefore we can't use the Stirpe API to validate the statement descriptor.

More about this here: p1638293368433600/1637246174.324800-slack-C01BZUL57SQ

**Comment by ricardo** [comment]
Closing this since it's not possible to address this on our end.

More details in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2189#issuecomment-998954529

**Comment by dechov** [comment]
Ah, I didn't realize this was closed – we can still consider validating against a list of blocked strings (see pc4etw-bL-p2).

**Comment by ricardo** [comment]
> we can still consider validating against a list of blocked strings (see pc4etw-bL-p2).

cc @cesarcosta99 who is working on this right now.

**Comment by cesarcosta99** [comment]
I'm keeping this issue closed. I've referenced this in #2189 so it can be assessed over there once it's under the same scope. Feel free to reopen it if you judge necessary.
