### ISSUE TITLE
Apple Pay sheet is sliding up on load

### ISSUE THREAD

**Issue by mattyza** [woocommerce/woocommerce-gateway-stripe#163]
When clicking "Buy with Apple Pay" on the checkout or cart, the sheet slides down and then quickly slides up. I tested this across South Africa and New York where @pmaiorana confirmed that this happens on his end as well.

@roykho

**Comment by roykho** [comment]
On what site is this happening on?

**Comment by mattyza** [comment]
On https://wc-test-store.mystagingwebsite.com/ @roykho. Is this because of the sandbox?

**Comment by roykho** [comment]
No it is not. And it works for me. I just tested it.

**Comment by roykho** [comment]
It won't work for Paul because he has a live account from last I spoke with him. Live account won't work on a Sandbox setup.

**Comment by pmaiorana** [comment]
Yup, I am using my personal Apple ID/Apple Pay account. Makes sense!
