### ISSUE TITLE
Hong Kong addresses always fail validation via Apple Pay

### ISSUE THREAD

**Issue by reykjalin** [woocommerce/woocommerce-gateway-stripe#1630]
**Describe the bug**

Apple Pay currently sends us an address in a format we don't expect; the Hong Kong Region (e.g. "New Territories") is put into the `postalCode` property of the `paymentRequest` object, instead of the `region` like we would expect.

This makes it so that when you try to pay via Apple Pay with a Hong Kong address the payment always fails with a very cryptic error message.

**This means customers are unable to pay merchants through Apple Pay when using a Hong Kong address.**

**To Reproduce**

Reproduction and testing steps available in #1593 

**Expected behavior**

Address validation succeeds for valid addresses and payments can be processed.

**Comment by solstudioim** [comment]
Got an error `Shipping Address Invalid` when using Apple Pay in Hongkong, 4132420-Zen

**Comment by reykjalin** [comment]
Thanks for the report! For anyone else that receives news of this bug (through tickets or otherwise), please let us know!

We're in the process of trying to fix this with Apple Pay, but it's going to take some time. This still remains as one of our top priorities, so once we've figured out a fix with the help of Apple Pay it will be implemented ASAP.

More context in pc4etw-bY-p2.

**Comment by felipevelzani** [comment]
We also had the same thing on 4017162-zen.
