### ISSUE TITLE
Doc: Update with requirements for Apple Pay etc

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#1631]
Two requirements for registering a domain with Apple Pay are:
- SSL
- port 443 open

If these aren't met, this error is shown:

> Apple's domain verification service appears to be temporarily down. Please retry your request in a few minutes. We've been notified of the issue, but if this error persists, please feel free to contact us at https://support.stripe.com/contact.

---

We can add this information to this doc in the Apple Pay section (or a new sub-doc):
https://docs.woocommerce.com/document/stripe/#apple-pay

Inspiration doc - an Apple Pay doc, the requirements section:
https://docs.woocommerce.com/document/payments/apple-pay/#requirements

Background: paJDYF-21m-p2

**Comment by dougaitken** [comment]
👋🏻 Hey @v18 - is this something your team will handle or do you want the docs guild to handle?

**Comment by dougaitken** [comment]
Reported to docs guild internally. p1659024751531819-slack-CSP74N77C

**Comment by EjayhanFernandes** [comment]
Keeping everyone in the loop. I have now added this information to the Apple Pay section of our Stripe doc: 
https://woocommerce.com/document/stripe/#requirements
