### ISSUE TITLE
UPE - Free trial subscriptions

### ISSUE THREAD

**Issue by bborman22** [woocommerce/woocommerce-gateway-stripe#1670]
The goal of this issue is to be able to checkout a subscription with a free trial using UPE. The [WCPay implementation](https://github.com/Automattic/woocommerce-payments/pull/2424) can be used as a reference for this. In short, a setup intent needs to be used while also saving the payment method for the recurring payments.

**Comment by ricardo** [comment]
I duplicated this issue without noticing, sorry.

Duplicate #1867.

Since the other was already referenced in a couple places, I'll close this one.
