### ISSUE TITLE
Replace charges API with payment intents

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#1671]
Ticket: 4191425-zd-woothemes

Apparently, the old `v1/charges` API is still being used in Stripe, whereas the payment intents API should be used instead.

I was not able to reproduce the issue from the ticket. When paying with credit cards, both regular and SCA cards, it always uses the payment intents API on my local setup, but it looks like the charges API might still be used as a fallback somehow. We need to investigate that.

Unfortunately, I don't have repro steps at the moment, but when trying to make a SEPA payment, it uses the charges API, and I think it makes sense to replace that endpoint with payment intents.

**Comment by v18** [comment]
For reference, the docs for accepting SEPA using payment intents is here:
https://stripe.com/docs/payments/sepa-debit/accept-a-payment?platform=web

Note for this issue that SEPA calls made with charges are not non-SCA compliant. All non-compliant SCA calls are for credit card payments only.

**Comment by nicdwilson** [comment]
Stripe's reply on this: 4202538-zen

**Comment by shaunkuschel** [comment]
4273283-zen reported that they received a message about SCA compliance in their Stripe dashboard, which I suspect is related to this issue. The merchant contacted Stripe and confirmed that their account is SCA compliant but the Stripe team mentioned that the message was related to our Stripe gateway integration.

The message shown to the customer in their Stripe dashboard is the following (which was translated from Spanish to English):

> Finish your integration for the SCA

> European regulations require the Strong Customer Authentication (SCA), which means that a type of two-step authentication is now required for many card payments. According to our data, your payments in the last 7 days have used an SCA-ready product. Complete the migration by following the instructions below.

> Complete the migration
Try dynamic authentication using 3D Secure
Mandatory

This customer's site is using current versions of WordPress (5.8), WooCommerce (5.6.0), and Stripe (5.4.1).

**Comment by ricardo** [comment]
cc @EvanDotPro for visibility - This is related to the SCA gaps project (pc4etw-8a-p2), which is currently paused. We're still making use of the non-compliant `charges` endpoint in certain circumstances.

**Comment by jacoswan** [comment]
Just to note another instance mentioned in 4450304-zen

**Comment by mattallan** [comment]
Closing this as it has become stale.

Since this issue was opened, our Stripe extension has implemented payment intents and is the default option.
