### ISSUE TITLE
Opt-out survey definition

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1677]
## Description

When a merchant opts-out of UPE, we will display a toast notification. The toast notification links to an optional survey for the merchant to take.
The purpose of this ticket is _not_ to implement that toast notification but to create the final survey for the merchant to take.

UX had some preference on Crowdsignal, but please confirm.

## Acceptance criteria
- Survey platform has been determined
- Merchant can provide answers via an external link
- Survey questions are confirmed
- Survey is ready to receive responses when the link is accessed

**Comment by tommyshellberg** [comment]
Survey can be viewed here:

https://woocommerce.survey.fm/woocommerce-stripe-upe-opt-out-survey
