### ISSUE TITLE
Inspect how coupons work with the Apple Pay sheet

### ISSUE THREAD

**Issue by mattyza** [woocommerce/woocommerce-gateway-stripe#168]
When the Apple Pay sheet is in use, the user should be able to apply a coupon to the sheet. This is important, as we don't want users to feel limited when using the sheet.

@roykho

**Comment by roykho** [comment]
The coupon is entered when they're on the cart page. So the calculation is done prior to them clicking the Apple Pay button. Will this not work?

**Comment by mattyza** [comment]
@roykho for the cart, I reckon this is fine. The checkout page is a bit different, as we display the coupon field as part of the main form. Apple Pay mentioned something about being able to apply a coupon directly on the sheet. I looked through Stripe's docs on this integration, and don't see anything about a discount code or coupon on the sheet.

I'll check with them on this in our next call, for clarification.

**Comment by roykho** [comment]
@mattyza so my thinking is the people who will use Apple Pay won't even get to the checkout screen. They would have clicked it from the cart already. And if they do get to the checkout screen, it is still not a show stopper as they can still apply the coupon from the dropdown form and still click Apple Pay and it will work the same.

But if this is a must, I will look to see if there is a way.

**Comment by mattyza** [comment]
Thanks @roykho. I've lowered this to "High" as it's important to Apple Pay, yet we have a flow in place which currently makes sense.

I'll discuss further and see if they have feedback for us.

**Comment by mattyza** [comment]
I got clarification on this, @roykho. The way we have it set up on the cart and checkout pages is correct, and Apple Pay doesn't have a coupon entering facility.
