### ISSUE TITLE
[settings] onboarding wizard UI

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1683]
## Description
The purpose of this ticket is to port the onboarding wizard mechanism and its UI from WCPay.

Mainly it will be a copy/paste of the wizard componentry + the UI implementation of the wizard with its steps.

There's no need to implement the data layer, clicking on the buttons will just navigate between the steps.

This will allow the backend and the data layer to be implemented separately.

The onboarding wizard needs to be displayed as a separate view, not as an onboarding task (like WCPay). See more details here: pc4etw-a9-p2#comment-816

## Acceptance criteria
- Onboarding wizard can be accessed when behind the "new settings" feature flag https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1737
- The onboarding wizard shows the 3 steps
- The first step's UI matches the designs
- The first step's CTA navigates to the second step (it will later [use this](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1684) and [this](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1724))
- The second step's UI matches the design (with the exclusion of the list of payment methods, which don't need to match the designs)
- The second step's CTA navigates to the third step
- The third step's UI matches the design (with the exclusion of the payment method icons)

**Comment by harriswong** [comment]
Note: The fees in second step would be using the fees from https://www.stripe.com/pricing. Refer to p1628888133149200/1628885390.148700-slack-C9976E5MJ for more info.

**Comment by harriswong** [comment]
I split this ticket into 2 more tickets:
- Adding "Select all" in step 2: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1765
- Update "missing fees": https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1766
