### ISSUE TITLE
Investigate handling Stripe account capabilities for UPE

### ISSUE THREAD

**Issue by EvanDotPro** [woocommerce/woocommerce-gateway-stripe#1688]
Some of the UPE methods require that the merchant has specific "capabilities" enabled on their Stripe account. We should check if the required capabilities are missing, and if so, either try to enable them via the Stripe API and/or display some sort of notice / call to action to the merchant.

**Comment by bborman22** [comment]
We had a brief conversation this morning that wandered in to this topic after the experience in WCPay and one thing we found is that certain capabilities require additional information from the merchant, but luckily [there is an endpoint for checking that](https://stripe.com/docs/connect/account-capabilities#viewing)! Just wanted to pass that along as I wasn't aware of that before.

**Comment by EvanDotPro** [comment]
## Technical background

First, [the `GET /account` endpoint, which returns a `capabilities` property](https://stripe.com/docs/api/accounts/object#account_object-capabilities) that is an array of the account capabilities currently enabled for that account:

```php
$stripe_account      = WC_Stripe_API::retrieve( 'account' );
$stripe_capabilities = (array) $stripe_account->capabilities;
```

Then, there is the endpoint @bborman22 mentioned, [`POST /accounts/$account_id/capabilities/$capability_id`](https://stripe.com/docs/api/capabilities/update). This _may_ enable the given capability for the merchant if there are no additional requirements to do so. However, as @bborman22 also said, some capabilities may have additional requirements the merchant must fulfill before the capability can be enabled. If that's the case, the `POST /accounts/$account_id/capabilities/$capability_id` endpoint will return an array of the needed requirements but the capability will not be enabled.

```php
$capability = WC_Stripe_API::request( [ 'requested' => 'true' ], "accounts/{$stripe_account->id}/capabilities/{$capability_id}" );
if ( 'active' === $capability['status'] ) {
	   // The capability was enabled successfully (or perhaps already was).
} else {
	   // status = inactive || pending
	   // User action(s) or verification/approval required:
	   // print_r( $capability['requirements'] )
}
```

**Note:** It _seems_ the capability ID's are the same as the UPE method ID strings, but with the suffix `_payments` (i.e., The capability ID for the `giropay` UPE method is `giropay_payments`. We should verify if this will always be the case so we can avoid having more things to define when adding additional methods.

## UX considerations

The question now becomes how we want the experience to look for a merchant.

Currently the Stripe extension does not bother checking if a merchant's Stripe account has the required capabilities when they enable LPM's with required capabilities. Thus, no notice or anything is shown if the capability is missing— presumably the only indication to the merchant is that the payment method fails at checkout when they try it.

The goal here is to utilize the above API methods to help merchants get their desired payment methods all working properly.

The logic would probably look something like this:

- When enabling a new UPE method, check if the required account capability is already active on their Stripe account.
  - **If yes:** All good, enable the UPE method.
  - **If no:** Request the required account capability be enabled on their Stripe account via `POST /accounts/$account_id/capabilities/$capability_id`.
    - **If the required capability was enabled:** All good, enable the UPE method.
    - **If the required capability was NOT enabled:** There are additional requirements the merchant must fulfill to enable this capability or verification by Stripe is pending. Do not enable the UPE method.

The last bullet point is where the UX questions come into play. How do we want to present this to the merchant?

- A simple "Unable to enable XYZ payments because XYZ capability is not enabled on your Stripe account." perhaps with a link to the relevant place in the Stripe dashboard?
- If the `POST /accounts/$account_id/capabilities/$capability_id` response indicates it's just pending verification (thus no action is required by the merchant besides waiting), would we want to provide a different message?
- Do we want such notices to be transient? i.e., goes away once they refresh or navigate away/back.
- Do we want to use any of the other `requirements` values returned by Stripe to make the notices more informative for merchants? (On this note, is there any way we can get an idea of what the possible values for these might be?)
```json
 "requirements": {
    "current_deadline": null,
    "currently_due": [],
    "disabled_reason": null,
    "errors": [],
    "eventually_due": [],
    "past_due": [],
    "pending_verification": []
  }
```

Weird edge case to keep in mind: Because there's no such checks currently, it will technically be possible that a merchant had an LPM enabled, but not working because their Stripe account lacked the capability, then they enable UPE (which in turn tries to enable the equivalent UPE method automatically). We'll need to make sure we communicate to the merchant why one of their enabled LPM's wasn't carried over to UPE.

**Comment by LevinMedia** [comment]
@EvanDotPro thanks for the great outline of the UX considerations here. 

One question I wanted to run by you before we start looking at design solutions... Are we only able to check on requirements after a capability has been enabled? Or can we get that info before a merchant attempts to enable a UPE method in their settings? 

I'm thinking if we could fetch any missing requirements before a merchant tries to activate a method, we'd be able to display some form of notice along side  / under each inactive payment method, letting them know what information they'd need to provide to get the payment method up and running. If there were no additional requirements for a method, there'd be no notice, and they could go ahead and just turn it on, in which case we'd also activate the capability for them as well. 

>>Weird edge case to keep in mind: Because there's no such checks currently, it will technically be possible that a merchant had an LPM enabled, but not working because their Stripe account lacked the capability, then they enable UPE (which in turn tries to enable the equivalent UPE method automatically). We'll need to make sure we communicate to the merchant why one of their enabled LPM's wasn't carried over to UPE.

It seems like we could use a similar notice approach to cover this edge case as well. If the method was previously enabled without the correct requirements - there would be a noticed attached to the payment method informing them that the method is disabled and why, and presumably we'd be able to provide a link that would take them to their stripe dashboard to fix it. 

cc @jarekmorawski

**Comment by EvanDotPro** [comment]
@LevinMedia:

> One question I wanted to run by you before we start looking at design solutions... Are we only able to check on requirements after a capability has been enabled? Or can we get that info before a merchant attempts to enable a UPE method in their settings?

We can check at any time as long as their Stripe keys are set, so what you described _should_ be possible. However, I'm not sure if Stripe will return the requirements list for a capability that hasn't been requested. In their [docs](https://stripe.com/docs/api/capabilities/list) for the `capabilities/list` method, they only show an example where the capability _has_ been requested. I'll see if I can find a way to disable/"un-request" the capabilities on my dev account so I can test this.

**Comment by LevinMedia** [comment]
>they only show an example where the capability has been requested. I'll see if I can find a way to disable/"un-request" the capabilities on my dev account so I can test this.

Okay thanks for looking into it further - my concern with firing a request first then un-requesting would be triggering an email to the merchant noting that they need to provide additional information to meet the requirements.

**Comment by EvanDotPro** [comment]
Right, sorry. I just meant that all of the capabilities are already enabled on my particular dev account, so before I can test how the Stripe API behaves in terms of returning requirements for non-requested capabilities (the docs are ambiguous), I'll need to see if I can get then un-requested/disabled.

**Comment by FangedParakeet** [comment]
> Are we only able to check on requirements after a capability has been enabled? Or can we get that info before a merchant attempts to enable a UPE method in their settings?

Just poking my nose in to share something we discussed on the call with Stripe the other day: there is a [separate endpoint](https://stripe.com/docs/api/capabilities/retrieve), where we can [preview account capabilities](https://stripe.com/docs/connect/account-capabilities#viewing) that will be required for a particular account. If we provide the account ID and the payment method capability (e.g. `card_payments`, `giropay_payments`, etc.) we can check additional fields/information that are past due, currently due, and ones that will be eventually due before enabling the capability for the account.

**Comment by jarekmorawski** [comment]
> If we provide the account ID and the payment method capability (e.g. card_payments, giropay_payments, etc.) we can check additional fields/information that are past due, currently due, and ones that will be eventually due before enabling the capability for the account.

That's good! We could check on the requirements when merchant clicks the "Add payment methods" button, before we display the modal. Then, like David suggested before, we'd add a notice to payment methods shown that require setup. I'd, however, allow merchants to add them to checkout in a disabled/hidden state. This way it'd be clear that they've been successfully added, but require further configuration.

https://user-images.githubusercontent.com/79307566/130765791-e9b3fad8-de30-4d72-aca1-c9b7878e4892.mov

Do you think the capabilities requirements are here to stay? Is it possible that Stripe will somehow handle them for us in the future? If not, I think we might have to make changes to the adding payment method flows to better present information like the missing capabilities.

**Comment by LevinMedia** [comment]
>Just poking my nose in to share something we discussed on the call with Stripe the other day

ah, thanks @FangedParakeet I had just assumed that was the API that @bborman22 had mentioned earlier.

**Comment by FangedParakeet** [comment]
> I'd, however, allow merchants to add them to checkout in a disabled/hidden state. This way it'd be clear that they've been successfully added, but require further configuration.

Just to be clear, if we add the payment method to checkout in the UPE without the right capability enabled, there will be an error at checkout and the UPE won't load. However, if we enable the capability without updating required fields, the user will get an email from Stripe. So if we were to enable a payment method pending setup, we'd have to leave it in a limbo state to avoid these two scenarios: the method would be enabled in the settings, but not yet included at checkout. This would raise another potential issue, as we would need to create a trigger to let us know when a user had completed setup and supplied valid values for the missing fields, so that we could then add the method to the UPE at checkout.

> Do you think the capabilities requirements are here to stay? Is it possible that Stripe will somehow handle them for us in the future?

Near the end of the call we had with Stripe, it was stated that with Universal Payment Capabilities enabled for all payment methods, we would not need to worry about filling in any of these fields and capabilities would just work without any interference...but I'm not sure if that was real.

**Comment by LevinMedia** [comment]
>Do you think the capabilities requirements are here to stay? 

@jarekmorawski they are - however, as @FangedParakeet mentioned, eventually this will no longer be an issue when universal payment capabilities are rolled out in full. Until then however, we'll need to account for this issue.

**Comment by jarekmorawski** [comment]
> This would raise another potential issue, as we would need to create a trigger to let us know when a user had completed setup and supplied valid values for the missing fields, so that we could then add the method to the UPE at checkout.

@LevinMedia, maybe it'd make sense to rethink how merchants add payment methods to checkout? Given that some options require extra steps, perhaps we should go back to square one and let merchants select methods from all available.

In the future, when payment methods will move to a separate tab in settings like in Stripe, the list shouldn't overwhelm.

![image](https://user-images.githubusercontent.com/79307566/130970809-e0060de7-c250-4987-906e-026d5e3502d1.png)

**Comment by jarekmorawski** [comment]
@EvanDotPro @FangedParakeet I've run into a few issues while working on the design for account capabilities.

- In WCPay, how merchants can manually edit capabilities if they don't have a regular Stripe account? Can we do it automatically for them?
- Can we provide merchants a link to a setup flow that will ask them for information required for a specific payment method?
- Can we identify missing info and ask for it _inside_ WooCommerce, then send it to Stripe on user's behalf?

**Comment by EvanDotPro** [comment]
> In WCPay, how merchants can manually edit capabilities if they don't have a regular Stripe account? Can we do it automatically for them?

The closest I've found is the [`POST /accounts/$account_id/capabilities/$capability_id`](https://stripe.com/docs/api/capabilities/update) method, but as mentioned above, it will only actually enable a capability if it has no pending requirements.

> Can we provide merchants a link to a setup flow that will ask them for information required for a specific payment method?

Doesn't look like it. Seems like the "Request access" buttons don't link to a page with a distinct URL, but rather trigger a modal popup on https://dashboard.stripe.com/settings/payments, which is probably the best URL to send them to.

> Can we identify missing info (...)

Identify? Probably, yes.

We get this data back from Stripe's API when asking about a capability that's not enabled yet or pending:

```json
 "requirements": {
    "current_deadline": null,
    "currently_due": [],
    "disabled_reason": null,
    "errors": [],
    "eventually_due": [],
    "past_due": [],
    "pending_verification": []
  }
```

That said, I don't know what the possible values are for those keys. I either overlooked it in [the docs](https://stripe.com/docs/api/capabilities/retrieve) or we need to check with Stripe.

> (...)  and ask for it inside WooCommerce, then send it to Stripe on user's behalf?

Collect and send to Stripe on the merchant's behalf? Probably not.

From what Ive read in the docs, I do not believe this is possible. The only capabilities-related (write/update) API method available is [`POST /accounts/$account_id/capabilities/$capability_id`](https://stripe.com/docs/api/capabilities/update) which only accepts a single parameter (`requested=true`).

**Comment by FangedParakeet** [comment]
> In WCPay, how merchants can manually edit capabilities if they don't have a regular Stripe account? Can we do it automatically for them?

As far as I'm aware, there is no route for a user to log into their connected Stripe account from within WCPay.

> Can we provide merchants a link to a setup flow that will ask them for information required for a specific payment method?

Once again as far as the dwarfish reach of my awareness can grasp, I don't think this exists anywhere on Stripe's end. 

> Can we identify missing info and ask for it inside WooCommerce, then send it to Stripe on user's behalf?

Within the domain of our existing power, we are able to check what capabilities a user's account has enabled, what information is missing, and what information will be required if they were to enable a particular capability. @EvanDotPro, I think [this link](https://stripe.com/docs/connect/account-capabilities#viewing) contains a little more information about what those key values would look like, though with some emphasis on the adjective "little". I also think we will be able to update that account information ourselves--as well as capabilities--on a customer's behalf via the [update accounts API endpoint](https://stripe.com/docs/api/accounts/update). 

That being said, we would have to develop this flow and all the required forms to enter account information ourselves, within WCPay. Essentially, prior to enabling a payment method, we would have to check with Stripe to see if any additional account information would be required for the user, then request this information somehow from the user, send it to Stripe, verify the information, then finally once the lights go green, enable the capability and with it the payment method. With a customer's account in the palm of our hands, we would know which fields would be required ahead of time, so this could in theory be included in the onboarding process as well, while a user picked out preferable payment methods. 

It's also worth noting that apparently with the UPC enabled with all desired payment methods supported, this entire user-flow would be redundant for new users: we'd have to ask Stripe whether they'd be able to backfill the UPC for existing users at this point.

**Comment by jarekmorawski** [comment]
Thanks for looking into this, folks. It seems like our hands are pretty much tied at the moment, which is unfortunate given how important this part of the setup is (especially for new users going through the onboarding).

> It's also worth noting that apparently with the UPC enabled with all desired payment methods supported, this entire user-flow would be redundant for new users: we'd have to ask Stripe whether they'd be able to backfill the UPC for existing users at this point.

New users, even if we enable all capabilities for them during onboarding, will need to provide additional information for payment methods like iDeal. To my best knowledge, Stripe cannot backfill existing WCPay accounts. Is that correct, @LevinMedia?

I've got a few other questions:

1. How long does it take for Stripe to add a capability or accept the new info entered by merchant?
2. Can you give me links or screenshots of pages users land on while attempting to add capabilities/missing info?

**Comment by EvanDotPro** [comment]
@jarekmorawski:

> How long does it take for Stripe to add a capability or accept the new info entered by merchant?

:man_shrugging: 

> Can you give me links or screenshots of pages users land on while attempting to add capabilities/missing info?

https://dashboard.stripe.com/settings/payments

**Comment by bborman22** [comment]
So I spent a little time looking in to this from the **perspective of determining which payment methods should be included at the point of checkout**. Quick background/review, when using UPE we need to create an intent and as part of that we provide a list of payment methods we want to offer up in UPE. If we provide a payment method that is not available for the account due to missing capabilities, we will get an error when trying to mount the UPE with that intent. So the key question I was looking to answer with this digging was: What check should we perform to make sure that including a payment method won't throw an error at checkout?

### Performing the Check

As @EvanDotPro found above we have one great access point through the [`GET /account` endpoint, which returns a capabilities property](https://stripe.com/docs/api/accounts/object#account_object-capabilities). This property returns an object of the form:

```json
"capabilities": {
    "acss_debit_payments": "inactive",
    "afterpay_clearpay_payments": "inactive",
    "bancontact_payments": "inactive",
    "card_payments": "inactive",
    "eps_payments": "inactive",
    "giropay_payments": "inactive",
    "ideal_payments": "inactive",
    "p24_payments": "inactive",
    "sepa_debit_payments": "inactive",
    "sofort_payments": "inactive",
    "transfers": "inactive"
  }
```

The [possible values for the status](https://stripe.com/docs/api/accounts/object#account_object-capabilities) are: `active`, `inactive`, or `pending`. I have put in a question to Stripe to confirm that a status of active means we can use the payment method in UPE or not and will follow up with their answer. This would be the easiest/cleanest check. One thing that was noted above, but I want to reiterate here, is that this list will only contain capabilities that have been requested, which led to the following fallback option next.

If, for some reason, a status of active is not enough to be certain there are no missing requirements or we wanted to be very thorough with the list of capabilities we check, there is also the [`GET /accounts/:id/capabilities` endpoint](https://stripe.com/docs/api/capabilities/list) that will provide a full list with details of each capability. This provides a list of capability objects of this form:

```json
 {
      "id": "ideal_payments",
      "object": "capability",
      "account": "acct_xxxxxx",
      "future_requirements": {
         ...  
      },
      "requested": true,
      "requested_at": 1631721080,
      "requirements": {
        "current_deadline": null,
        "currently_due": [
          "business_profile.mcc",
          "business_profile.product_description",
          "business_profile.support_phone",
          "business_profile.url",
          ...
        ],
        "disabled_reason": "requirements.fields_needed",
        "errors": [ ],
        "eventually_due": [
          "business_profile.mcc",
          "business_profile.product_description",
          "business_profile.support_phone",
          "business_profile.url",
          ...
        ],
        "past_due": [
          "business_profile.mcc",
          "business_profile.product_description",
          "business_profile.support_phone",
          "business_profile.url",
          ...
        ],
        "pending_verification": []
      },
      "status": "inactive"
    }
```

This object includes the status as well as some other useful fields about requirements, disabled reason, or pending verifications. Again, if an active status is not a sufficient indicator, this object should provide enough information to parse out whether to include the payment method or not. I also wanted to note that we can make a similar request for an individual capability as well since the full list of capabilities can be quite large.

I just wanted to point these two options out to signal that I feel very confident we will be able to determine whether or not to include a payment method at the time of checkout or not.

### Using the Check Results

With confidence in our ability to determine that, I wanted to look in to some options for how we could track these capabilities without having to hit one of these endpoints each time and my first thought went to transients. I was thinking we could store either the serialized array of capabilities and their status (my initial preference) or store a transient for each capability we are interested in. This transient could be refreshed at its regular time interval, but also whenever there is an update to the UPE payment method settings or even manually.

And finally once we have that store of capabilities, we already have a convenient [`is_enabled_at_checkout` function](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/c719957a5bf073d845278ad7af4101ce2e22d341/includes/payment-methods/class-wc-stripe-upe-payment-method.php#L103) for any UPE payment methods. I was thinking we could check against the transient within that function and return accordingly. I don't believe there would be any major performance hit from this as any transient miss here would rebuild it and then subsequent checks would be against the transient. 

There is a bit of brainstorming here on how best to use the capability check so any input/feedback would be great!

**Comment by bborman22** [comment]
I got confirmation that an active status on the capability signals that the payment method is indeed fully ready for use, so I believe the `GET /account` endpoint should be sufficient to check against and if the payment method is missing, we know it hasn't been requested yet.

@jarekmorawski in regards to:

> How long does it take for Stripe to add a capability or accept the new info entered by merchant?

I got a response that it should be within 24 hours and is usually much faster.

**Comment by Mayisha** [comment]
Mentioning this here in case it is useful. In one of my PRs [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1869) I have used the `GET /account` and caching the account data.

**Comment by EvanDotPro** [comment]
I think this can be closed now. :)
