### ISSUE TITLE
SPIKE - OAuth flow

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1695]
## Description

We need to port the oauth flow to the new settings.
In order to provide the best experience for our users we need to understand a few more things.
Please also inform UX of the findings.

## Questions
- Does the existing process gathers both test and live keys from the OAuth flow?
  - If not, can we improve it and obtain both?
- Can the keys change?
  - If so, in which scenarios?
  - If so, can they be updated automatically or would the merchant need to update them manually?
- By using an updated flow, can we hide the keys from the settings? Are they used for specific reasons?

**Comment by c-shultz** [comment]
While we're looking at this, I would also like to better understand the dependency on the Connect Server (assuming that dependency still exists)

**Comment by waclawjacek** [comment]
Here's the class making the Connect Server requests: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/38744bb1c4add59869f5067734c0960f726b1228/includes/connect/class-wc-stripe-connect-api.php

**Comment by superdav42** [comment]
pc4etw-hW-p2

**Comment by frosso** [comment]
Thanks @superdav42 !
