### ISSUE TITLE
Card tokenization & payment fails when payment form in non-default location

### ISSUE THREAD

**Issue by avishai** [woocommerce/woocommerce-gateway-stripe#170]
#### What I expected

Using the default theme, I moved the payment form from its default location under order review, to after the customer details section using the following hooks:

```
// Move payment form to underneath customer details
remove_action( 'woocommerce_checkout_order_review', 'woocommerce_checkout_payment', 20 );
add_action( 'woocommerce_checkout_after_customer_details', 'woocommerce_checkout_payment', 20 );
```

I expected to fill in the payment details, and process the payment as usual. This failed, raising the following error: 

**Please enter your card details to make a payment. Developers: Please make sure that you are including jQuery and there are no JavaScript errors on the page.**

#### What happened instead

1. An error message that says **Please enter your card details to make a payment. Developers: Please make sure that you are including jQuery and there are no JavaScript errors on the page.**
1. No other JS errors
1. The payment does not go through and the checkout page is displayed again. 

#### Steps to reproduce the issue

First, move the position of the payment method selection & credit card fields to a different position in the checkout form. Everything should be on one page. 
```
// Move payment form to underneath customer details
remove_action( 'woocommerce_checkout_order_review', 'woocommerce_checkout_payment', 20 );
add_action( 'woocommerce_checkout_after_customer_details', 'woocommerce_checkout_payment', 20 );
```
Then:

1. Enter a test card number (`4242 4242 4242 4242`)
1. Enter a valid expiration (12/19)
1. Enter a valid CVV (123)
1. Submit payment

### Potential Solution
I traced the issue, and it appears that if the form isn't wrapped in a `#review_order` div, the tokenization process does not get triggered. This of course shouldn't happen, as there isn't always an order review form, just checkout. 

To fix in the meantime, I added this code to `woocommerce-gateway-stripe/assets/js/stripe.js`, in `wc_stripe_form`'s `init()` function:

```
$( 'form.woocommerce-checkout' )
	.on(
		'submit',
		this.onSubmit
	);
```

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Then the solution for you would be to either keep it within the `#order_review` ID or create a wrapper with that ID. You can't just remove it like you did as other templates also rely on this ID such as the Pay for order template.

**Comment by avishai** [comment]
Ok, I've updated my template to reflect that. It's not the best solution though, since it gives little flexibility to developers who want to put the credit card fields somewhere else. In my opinion, the default placement provides a pretty poor user experience, especially considering how many fields WC asks the user to fill in by default.
