### ISSUE TITLE
Add Apple Pay button to the single product screens

### ISSUE THREAD

**Issue by mattyza** [woocommerce/woocommerce-gateway-stripe#171]
Apple Pay have requested that we add the "Buy with Apple Pay" button to the single product screens. They say this is a blocker to launch, as it helps to make a more complete case to their team for future Apple Pay integrations for WooCommerce, and also helps to increase overall conversions of the more "casual shopper" (low intent shopper), who is browsing the store, yet may not have enough intent to go through the checkout.

@roykho - Alexis mentioned the option to add to cart in the background, and then use the cart to calculate shipping, etc, instead of a custom endpoint.

cc @roykho @MarinaWoo @pmaiorana

**Comment by roykho** [comment]
@mattyza - So if they're on the single product page and click on Apple Pay button, the payment sheet is suppose to come up on the same page without any redirecting? So that would also mean, any chance of entering a coupon is bypassed as well is that ok?

**Comment by mattyza** [comment]
@roykho - I've not seen any coupon fields on PDPs (product detail pages) in their example implementations, so I'd say that's fine for now. Adding the coupon field may require some additional UI, which we don't have a proper implementation for right now.

**Comment by mattyza** [comment]
@roykho - Also, the option for the coupon code is available on the cart page, so a user can run through that flow ("add to cart" -> "apply coupon" -> "Buy with Apple Pay") if they are adamant that a coupon must be used on their order.

The PDP integration is designed for low intent users (aka. someone who is browsing casually, perhaps for the first time), so this user will most likely not be aware of a coupon code available to them.

**Comment by roykho** [comment]
@mattyza - As I work on this, several more concerns came about.

- The placement of the button is going to be tricky because the theme ultimately will decide if it will look good or not. I am currently hooking into the hook `woocommerce_before_add_to_cart_form` and that will look like this ![](http://cld.wthms.co/o9lj/58GKAnsx+) and it will look similar for variable products which then would not make sense or even for simple products because the quantity field is below it. Also for variable, they would need to first select a variation before they can buy. So is placing the button below the "add to cart" form/button ok?

- How would we deal with custom addons such as product addons or composite products...etc? I would imagine the logic to deal with those is not going to be worth it. For now I would suggest we stick to simple products and variable products ignoring the custom fields.

**Comment by mattyza** [comment]
@roykho - how about the `woocommerce_before_add_to_cart_button` hook? This would enable a layout similar to to that on the mockup of the landing page @garymurray designed, where the Apple Pay button sits next to the "add to cart" button, and after the quantity field.

We can remove the "Or" in that context.

This should then help other product types.

I'm okay with having this on simple and variable products, for now. For the rest, let's add an issue to use the "add to cart" approach Apple Pay suggested for non-standard product types, extra fields, etc.

How does that sound?

Mockup:

![image](https://cloud.githubusercontent.com/assets/880803/22979274/703b481e-f39e-11e6-9555-73268d288bca.png)

**Comment by roykho** [comment]
@mattyza - I remember an issue using that hook with our other extensions but I can revisit that again. Naturally it will not sit next to the add to cart button. So were you thinking that we add our own CSS to align it? If so, do you foresee this being an issue with themes?

**Comment by roykho** [comment]
@mattyza - also the quantity field still comes after that hook.

**Comment by mattyza** [comment]
@roykho - I had to use the `woocommerce_after_add_to_cart_button` hook, and `float: right;` to make it look like that mockup, because the "Add to cart" button is floated right, so the markup order isn't the same as the visual.

That should solve the quantity field issue as well. :)

I'd say it's fine to add a bit of positioning CSS ourselves. Themes can override that if they wish to do so, as it's purely positioning.

**Comment by roykho** [comment]
@mattyza - So on Storefront it looks like this ![](http://cld.wthms.co/V27A/2SunKKTg+) but here is what it looks like on a default WP theme (don't mind the button text) ![](http://cld.wthms.co/QSZZ/2drKN5zA+)

If you're still ok with this, then I will go ahead and make this change.

**Comment by roykho** [comment]
So its all over the place. In Storefront variable product it looks like this ![](http://cld.wthms.co/xPUU/4nbS1Egj+)

**Comment by mattyza** [comment]
@roykho - For now, we only need to support Storefront, and the themes we support in core (the Twenty-something themes).

Would you mind adding some basic styling for each, and then @jameskoster, would you mind taking a look at the styling for the themes we support in core, to ensure this Apple Pay button displays correctly?

**Comment by garymurray** [comment]
For the record - I did not design that page :) or the mockup you trying to replicate - it was done by Firing squad.

**Comment by mattyza** [comment]
@garymurray - sure. It's pretty nice, though. :)

**Comment by roykho** [comment]
Just to note here we also have to account for localization. So in English it may fit next to the `add to cart` button but once switched to say French, it will no longer fit. @jameskoster any idea how we can hook in the button to be after the quantity field but before `add to cart` and can account for different languages?

**Comment by mattyza** [comment]
@tiagonoronha @kellychoffman 

I'd be happy with having the Apple Pay button display above "add to cart", with no "Or" in the middle, as well.

Either on top or to the left of the "add to cart" button is fine.

**Comment by jameskoster** [comment]
Small FYI, in Storefront 2.2.0 we've moved that button a little;

![button](https://cldup.com/ek2H_htSIj-3000x3000.png)

Assuming the quantity field works as expected then I think putting the Apple Pay button adjacent to the regular add to cart button makes sense. 

I quite like the 'or' though as it helps highlight the behaviour is different. I'd also suggest changing the label to say "buy now with Apple pay" to further help with that.

![apple](https://cldup.com/1vCT3wqInD-1200x1200.png)

**Comment by mattyza** [comment]
@jameskoster - thanks! Is there any way we could swap those buttons around (Apple Pay first), and have the button be the official "buy with Apple Pay" button? Those are two points Apple Pay will certainly remark on, as blockers.

**Comment by jameskoster** [comment]
If they are definitely blockers then I guess we have to :p

Using the official button style is no problem of course. Can we add 'now' to the label or is that out of our control?

Swapping the order is a pain tbh, purely because of where `woocommerce_after_add_to_cart_button` is positioned in the template. It would require fairly ugly CSS in Storefront plus a class added to the body by the plugin itself. In any other theme it would look pretty awful.
 
Having the Apple button appear after the regular one would be a lot simpler.

If the Apple button absolutely must appear first I'd propose we add a new hook to WC core in the appropriate place. That'd make the integration seamless regardless of theme and seems by far the best solution.

**Comment by roykho** [comment]
@jameskoster - thanks for chiming in. I also talked with @mikejolley today about adding an additional hook to "after" the quantity field and before the "add to cart" button so we don't need to use CSS trickery to position the button. But will leave that up to you guys to decide.

Furthermore to answer your question @jameskoster - we can't change the text on the button. It is auto populated by Apple's JS script.

**Comment by jameskoster** [comment]
New hook definitely gets my vote @mikejolley. Created an issue; https://github.com/woocommerce/woocommerce/issues/13221

**Comment by carasmo** [comment]
Will this be added to 2.6.x or 2.7 or both? And this is great!

**Comment by mattyza** [comment]
@carasmo - The new hook would be added in 2.7. :)

@jameskoster @mikejolley - I love the idea of the new hook, as well.

That said, we'd see a significantly low uptake in Apple Pay if using a hook that's only available in 2.7.

Would it be possible to position the button before the "Add to cart" in 2.6.x (in a nicely designed way), and then after the button in 2.7?

**Comment by jameskoster** [comment]
Yep, that works for me.

Will just need a version check to decide which hook to use and where to place the 'or'.

**Comment by tiagonoronha** [comment]
I'm happy with that solution as well. :)

It's a bit weird to have the Apple Pay button first, kinda takes over our own checkout flow and feels like it is the primary action.

Out of curiosity, is this implementation for single product purchases or does it also take into account other items the user might have in the cart?

**Comment by mattyza** [comment]
@tiagonoronha - This implementation is purely for the single product.

It _is_ a bit odd that it takes over, yet bear in mind the context in which the button is visible. This is visible only to eligible Apple Pay users, browsing on their mobile devices (already connected to Apple Pay) or on their desktops in Safari, on macOS Sierra and higher. For this customer, Apple Pay is an expected option, and is the best purchase experience.

The objective of the PDP integration is to capture low intent users. This is someone who is eligible, and is casually browsing, with little to no intent to purchase. Making it easy to purchase the item they see in front of them, with little to no friction, increases conversion rates for stores using Apple Pay.

Hence placing the button first now has a bit more context as to the intention and reasoning. :)

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/woocommerce-gateway-stripe/tree/apple-pay-styling

The Apple Pay button is displayed **before** the "Add to cart" button in 2.6 and 2.7.

Needs testing with extensions that add elements to those hooks.

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/33527cf270f8bc8a4b427f2144bb2839ff8e3da3

**Comment by hobadams** [comment]
Hey  @roykho @mattyza , I've just stumbled across this issue and wondered how you dealt with this?

When i add ApplePay to the PDP I get the error `must create a new applepaysession from a user gesture handler`.  This is because I first add the product to cart (using the click event) and then, using a callback start the ApplePay session.

Any advice or feedback would be amazing
