### ISSUE TITLE
Determine minimum required version for UPE and UPE settings

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1712]
## Description

The current minimum required version for WP is 4.6: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/20fc7b735d300955ac67c0f9bc21e3d0d61cd582/readme.txt#L4

With the addition of the React library dependencies, this might not be accurate anymore.

More details here on the plan: p1629405693041000/1629383980.012900-slack-C02BHNRN6R1

## Acceptance criteria
- Determine the minimum required version
- Add a version check for when the UPE preview feature flag (which shows the new settings) is enabled to the root of the project
- Add version check to add an admin note for when the version isn't satisfied and the UPE preview feature flag is disabled
- Add an inbox note to alert merchants that have WCStripe installed

**Comment by frosso** [comment]
This needs to be done before September 8th, so that the admin note & version check are part of the release.

**Comment by v18** [comment]
Noting here that we'll also want to communicate this in the following ways:

- admin note (in addition to inbox note, as noted above)
- woocommerce blog post

Depending on the version we require for dependencies, would be great to find out the number of merchants affected to make a decision around rollout.

**Comment by frosso** [comment]
Blog entry: 199-gh-woocommerce/woocommerce-developer-advocacy
Code: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1749
