### ISSUE TITLE
Stripe not change to live mode

### ISSUE THREAD

**Issue by dluxbarcelona** [woocommerce/woocommerce-gateway-stripe#172]
#### Affected ticket(s)

Stripe plugin not change to LIVE MODE

#### What I expected

I enabled and disabled some times the plugin
I deleted the plugin and install again
I changed the API Keys 2 times

#### What happened instead

When disable TEST MODE the plugin not change to LIVE MODE, I go to Check out Cart and down the page when select the Credit Card, down put this:

Pay with your credit card via Stripe. TEST MODE ENABLED. In test mode, you can use the card number 4242424242424242 with any CVC and a valid expiration date or check the documentation "Testing Stripe" for more card numbers.

I spoke directly with stripe and told me that speak with yours about this problem.

Can you help us?

Thank you

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Probably a caching issue. After you switch modes, dump your cache.

**Comment by dluxbarcelona** [comment]
Hello Roy,

I deleted all came memories, wordpress cache, computer cache... and the problem is the same, not change to Enable Mode.

**Comment by roykho** [comment]
What is your site url?

**Comment by dluxbarcelona** [comment]
https://www.dluxbarcelona.com

**Comment by roykho** [comment]
Also please take a screenshot of your api key settings area ( redact the keys of course ).

**Comment by dluxbarcelona** [comment]
API keys are OK, If you want I can create you an Admin Login for enter in website?
Is secure this channel for send passwords and other information?

**Comment by roykho** [comment]
It is not secured. Please just paste a link of the screenshot here.

**Comment by dluxbarcelona** [comment]
https://www.dropbox.com/s/nqplwu48du36kiy/stripe.tiff?dl=0

**Comment by roykho** [comment]
And what is the version of the plugin you're using?

**Comment by dluxbarcelona** [comment]
stripe : Version 3.0.7
wordpress : version 4.7.2 the last

**Comment by roykho** [comment]
PHP version?

**Comment by roykho** [comment]
And one other thing to try is turn all plugins off except WooCommerce and Stripe. Even change your theme to WordPress default theme and re-test.

**Comment by dluxbarcelona** [comment]
PHP 5.6.30

I'll try turn off all plugins except woocommerce plugins tonight, ok?
Now is impossible.

Tomorrow morning I'll tell you something.
Thank you Roy

**Comment by dluxbarcelona** [comment]
Hello Roy,

Seems to be that the new plugin WPML Version 2.1.24 have an internal conflict with Stripe.
Thank you for your help, I'll send this problem to WPML this morning.
Thank you.

**Comment by LeleDev** [comment]
@dluxbarcelona any news regarding WPML and stripe live problems?

**Comment by dluxbarcelona** [comment]
hello Emanuele,

all is working ok, tank you for ask me.

regards.




Engineering - Ingeniería
DLUX Barcelona

phone  	+34 93 757 01 50
e-mail 	info@dluxbarcelona.com
    site  	www.dluxbarcelona.com <http://www.dluxbarcelona.com/>


La  información contenida tanto en este correo electrónico, como en los documentos adjuntos, es  información privilegiada para uso exclusivo de la persona o personas a las que va dirigido. No está permitido el acceso a este mensaje a cualquier otra persona  distinta a los indicados. Si Usted no es uno de los destinatarios, cualquier duplicación, reproducción, distribución, así como cualquier uso de la información contenida en él o cualquiera otra acción u omisión tomada en relación con  el mismo, está prohibida y puede ser ilegal. En dicho caso, por favor, notifíquelo al  remitente y proceda a la eliminación de este correo electrónico así como de sus adjuntos si los hubiere. 

En cumplimiento de la Ley 15/1999(LOPD), el reglamento UE 2016/679 y la LSSICE 34/2002, le informamos que sus datos se encuentran incluidos en un fichero, titularidad de DLUX COMPOSITES SL, cuya finalidad es la gestión de la actividad de la empresa tanto administrativa como comercial. DLUX COMPOSITES SL   se compromete a no ceder sus datos a terceros y aplicar las medidas técnicas de seguridad para garantizar su privacidad. Sus datos serán conservados mientras sean necesarios para la finalidad para la que han sido recabados. Usted puede acceder a sus datos, rectificarlos, suprimirlos, limitar su tratamiento, solicitar su portabilidad, así como también retirar el consentimiento a su tratamiento en cualquier momento, o comunicar que no desea seguir recibiendo información comercial de nuestros productos o servicios. Puede hacerlo enviando un e-mail con el asunto “LOPD” y su solicitud a lopd@dluxbarcelona.com. También puede presentar una reclamación ante la autoridad de control <https://www.agpd.es/portalwebAGPD/enlaces/index-ides-idphp.php>.

The content of this e-mail message and any attachments are legally privileged and are intended only for the person(s) or entity to whom they are addressed. The access to this mail by persons other than the indicated recipient is prohibited. If you are not the intended recipient, any copying, reproduction, distribution, as well as any use of its content or taking any other action in reliance on the contents of this information of this email is prohibited and can be illegal. In that case, please notify the sender and delete this message and its attachments, if any.

In compliance with the Law 15/1999 (LOPD), EU Regulation 2016/679 and LSSICE 34/2002, we inform you that your data will be incorporated into an automated file owned by DLUX COMPOSITES SL, with the purpose of management both of the administrative and commercial activity of the company. DLUX COMPOSITES SL undertakes not to transfer your data to third parties and to apply technical security measures to guarantee its privacy. Your data will be kept as long as it is necessary for the purpose for which it have been collected. You can access your data, rectify, delete, limit its treatment, request its portability, and withdraw your consent for its treatment at any time or communicate that you do not wish to continue receiving  the commercial information of our products or services. You can do this by sending an email with your request, indicating as subject "LOPD", lopd@dluxbarcelona.com. You can also file a claim to the supervisory authority.
