### ISSUE TITLE
Add Support for WeChat Pay #1034  Open

### ISSUE THREAD

**Issue by bchambers8** [woocommerce/woocommerce-gateway-stripe#1728]
Woocommerce -Strip plugin

this has been an open issue for over 2 years - any chance we can have a resolution

**Comment by dougaitken** [comment]
Duplicate of #1034 - please keep all discussion there. 

It would be great to have you add your ideas and enhancement requests to the [Stripe Feature Request Portal](https://woocommerce.com/feature-requests/stripe/), which is where developers go to look for future plugin features and improvements.

I've found a corresponding feature request here - [Enable WeChat Pay in WooCommerce Stripe Payment Gateway](https://woocommerce.com/feature-request/enable-wechat-pay-in-woocommerce-stripe-payment-gateway/)
