### ISSUE TITLE
Transaction responses visible on debug.log when "Logging" is disabled

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce-gateway-stripe#173]
#### What I expected

We have explicitly disabled the WooCommerce Stripe logging, but enabled WordPress Logging to file.
Transaction logs should not be written on debug.log.

#### What happened instead

Transaction logs like the ones below are written on debug.log

`Info: Begin processing subscription payment for order XXXXXX for the amount of 15`

```
charges request: Array
(
    [currency] => gbp
    [amount] => 1500
    [description] => Order XXXXXX
    [capture] => true
    [expand[]] => balance_transaction
    [customer] => cus_XXXXXXXXX
    [source] => card_XXXXXXXXX
    [metadata] => Array
        (
            [payment_type] => recurring
        )

)
```
`Info: Begin processing payment for order XXXXXX for the amount of 10`

```
Processing response: stdClass Object
(
    [id] => ch_XXXXXXXXX
    [object] => charge
    [amount] => 1500
    [amount_refunded] => 0
    [application] => 
    [application_fee] => 
    [balance_transaction] => stdClass Object
        (
        ...
```

#### Steps to reproduce the issue

1. Go to Admin -> WooCommerce -> Settings -> Checkout -> Stripe
2. Ensure "Logging" is disabled
3. Add the following on wp-config.php
```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true ); /* save errors to /wp-content/debug.log */
define( 'WP_DEBUG_DISPLAY', false ); /* Show debug messages in HTML */
```
4. Process a new transaction or wait until WooCommerce Subscriptions process a renewal
5. Check the wp-content/debug.log

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
So far I am not able to replicated this.

**Comment by glagonikas** [comment]
Hi @roykho,

I'm testing this on WP 4.7.2, WC 2.6.16, WC Stripe 3.0.7.

I've switched the theme to twentyseventeen and left just the two plugins enabled, but i can still reproduce this.

I can give  you FTP and admin details for a staging server if you like.

**Comment by glagonikas** [comment]
OK so the bug i reported appears to be a duplicate of #132 (point 1).

Looking at your code, this should now be fixed on the latest version which is not live yet so i'll wait till you release it.
