### ISSUE TITLE
UPE - Save payment method during classic checkout

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#1730]
The goal of this issue is to implement the feature `save payment method` during checkout... Code to add a payment method to a customer (and create the customer) will be added in #1668 and should be reused to complete the missing login in #1659

**Comment by ricardo** [comment]
We need to make sure saving a payment method also works in the pay for order page #1669.

If that can't be done with the same changes when closing this issue, let's create another issue to make sure this works with #1669 as well.

**Comment by FangedParakeet** [comment]
@ricardo, I'd recommend creating a new issue to resolve this, since we're locked in a little Mexican standoff right now, as we're both working on implementing these new features that need to support each other at the same time. 😄

**Comment by ricardo** [comment]
👍 Sounds good! Created a new issue: #1784
