### ISSUE TITLE
Checkout: Error in stripe_checkout.js

### ISSUE THREAD

**Issue by levidps** [woocommerce/woocommerce-gateway-stripe#174]
#### What I expected

When submitting form on checkout page I click the checkout button expecting to get the form to submit payment for checkout. 

#### What happened instead

However when clicking 'Place Order' nothing happens and in the console I'm getting an error stating 'Uncaught TypeError: wc_stripe_form.form.unblock is not a function'. As can be seen in the screen shot this error appears every time I click the button. 

#### Steps to reproduce the issue

All I've done to this point is install the plugin, activate it with stripe test keys and attempt to process a transaction. 

#### Temporary Solution Found

I've found that by commenting out the unblock() called inside of the initial unblock() function ( screen shot below ) that the test functions as expected and the error is resolved. Not sure if I'm missing something but I've tried disabling all plugins beside woocommerce ones and that hasn't resolved the issue...just thought I'd 

Stripe Payment Form
![image](https://cloud.githubusercontent.com/assets/7575078/23147559/f25ac2d6-f833-11e6-8c70-5120b8b40d82.png)

Console Error on Attempted Submission
![image](https://cloud.githubusercontent.com/assets/7575078/23147533/bce14dc8-f833-11e6-8967-30805b83f638.png)

Commented out code for solution 
![image](https://cloud.githubusercontent.com/assets/7575078/23147862/55201aea-f836-11e6-8812-e4d9d8d6838f.png)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Try switching to a default theme.

**Comment by levidps** [comment]
Thanks mate, got it sorted. Issue was caused by deregistering 'jquery-migrate'.
Cheers,
