### ISSUE TITLE
UPE - Errors at checkout are not reflected on order status

### ISSUE THREAD

**Issue by FangedParakeet** [woocommerce/woocommerce-gateway-stripe#1740]
**Describe the bug**

This is a mirror of the same WCPay issue at Automattic/woocommerce-payments#2702.

> When completing a checkout using credit/debit cards with the UPE, if the payment information provided causes an error, we do not update the order with this event. The previous, parent payment gateway would update the order's status to `Failed` at this stage and a note would be left on the order explaining the specific error message. With the UPE, in this case, we simply display the error at checkout to the user, without sending any request to update the order. This could be confusing to a site owner, since the order's status remains as `Pending payment` and is not associated with other failed orders.

**To Reproduce**
1. Enable the UPE following the steps in #1659. 
2. Add an item to your cart and proceed to checkout and wait for the UPE to load.
3. Select credit/debit card within the UPE and use the details from one of [these test cards](https://stripe.com/docs/testing#cards-responses) to effect a failing response. Note that an error is displayed at checkout. 
4. From your site's admin section, view your latest orders and find the corresponding order for your checkout. Note that the status is still `Pending payment` with no notes added to the order.
5. You can repeat these steps with the UPE disabled to see how the order should be reflecting the error instead. The order should be updated to `Failed` and there should be notes on the order explaining the error.

**Expected behavior**

Order status should change to `Failed`. Order should contain note explaining transaction error.

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**

**Comment by ricardo** [comment]
Although this issue refers to order notes from errors, it's worth pointing out that some other notes are inconsistent with the classic checkout.

i.e #1850 - SEPA payments should add an order note and move status from "pending" to "on hold".

There might be other inconsistencies. We need to check that.

**Comment by FangedParakeet** [comment]
Nice call-out. If you check [this list](https://stripe.com/payments/payment-methods-guide), the payment methods whose `PAYMENT COMPLETION` is not "Immediate" are the ones we'll have to watch out for, where there will be inconsistencies in how the payment intent status changes during a regular checkout. I think the only UPE payment methods on our agenda that have delayed payment completion are Sofort and SEPA Direct Debit, so those are the two we'll have to keep an eye on.
