### ISSUE TITLE
Variable Subscriptions: sign-up fees not included in total

### ISSUE THREAD

**Issue by asumaran** [woocommerce/woocommerce-gateway-stripe#1745]
**Describe the bug**

This bug was previously fixed for Simple Subscriptions [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1555) ([Issue](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1459)). The same fix needs to be applied for Variable Subscriptions.

**To Reproduce**
- Ensure Payment Request Button is enabled under WooCommerce > Settings > Payments > Stripe.
- Install WooCommerce Subscriptions.
- Create a Variable Subscription
- Add a custom attribute with the following values `red|green|blue`
- Create a variation from all attributes
- Add "Subscription price ($)" and a "Sign-up fee ($)" to each variation
- Save and visit the product's page
- Select a variation and click the PRB
- Product in modal **does not** include the sign-up fee

Notice the amount is fixed only after picking a Shipping address.

**Expected behavior**
Subtotal in modal includes sign-up fee

**Screenshots**

<img width="477" alt="Screen Shot 2021-08-25 at 12 10 07 PM" src="https://user-images.githubusercontent.com/1025173/130834937-22064caa-85c4-4485-a7ef-3bb6ca5b5880.png">

<img width="489" alt="Screen Shot 2021-08-25 at 12 12 17 PM" src="https://user-images.githubusercontent.com/1025173/130835248-bf3ebcf4-df6b-4b43-b6d5-9c842c2aa279.png">

**Environment:**
 - Stripe Plugin Version: 5.3.0

**Comment by aheckler** [comment]
4666245-zen

**Comment by mattallan** [comment]
This issue was fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2741
