### ISSUE TITLE
Error in the Woocommece Checkout Settings and Update Notification

### ISSUE THREAD

**Issue by aimkbe** [woocommerce/woocommerce-gateway-stripe#175]
I downloaded the Woocomerce Gateway Stripe plugin from the repository, and that version, 3.0.7 did not have the apple pay function in the settings for woocommerce.

I downloaded the version here removed the first version i downloaded, 3.0.7.

When I downloaded the version on GitHub, there was an update notification. I did not update.

Second, when I go to my woocommerce tab > settings > checkout > stripe on the very top of the screen, above the woocommerce settings tabs, i see an error:

Warning: mkdir(): File exists in /home/washmyballs/public_html/wp-content/plugins/woocommerce-gateway-stripe-master/includes/class-wc-gateway-stripe.php on line 326

Not sure what this is, please advise. Thank you!

**Comment by roykho** [comment]
Please do not use this version as it is not public. Stick with the public stable version.

**Comment by aimkbe** [comment]
thank you!

**Comment by aimkbe** [comment]
so currently the public version does not have apple pay capability?

**Comment by roykho** [comment]
correct.
