### ISSUE TITLE
Payment not recorded in WC for 3DS transaction if completion takes longer than hold stock value

### ISSUE THREAD

**Issue by martynmjones** [woocommerce/woocommerce-gateway-stripe#1756]
**Describe the bug**
When using a card that's 3D secure, if a customer takes longer than the value of hold stock to `Complete Authentication` in the Stripe pop-up then the payment is successful and they are taken to an order confirmation screen, however, the order in WC will show as canceled and not have a record of the Stripe transaction.

**To Reproduce**
1. Set `hold stock` to 1 minute
2. Create a test simple product
3. Place an order using a 3DS card
4. Wait for more than 1 minute before clicking on `Complete Authentication`
5. See order details in WP Admin

**Expected behavior**
I would expect that the order would display in WooCommerce as processing as payment was successfully received

**Environment (please complete the following information):**
 - WordPress Version: 5.8
 - WooCommerce Version: 5.6
 - Stripe Plugin Version: 5.4
 - Browser: Chrome 92.0.4515.159. Also tested in FireFox with same results, assuming the browser is irrelevant
 - Any other plugins installed: No

**Comment by martynmjones** [comment]
Reported in 4249788-zen

**Comment by martynmjones** [comment]
I'm assuming other payment gateways could have the same results so I will run additional tests and open bug reports on other repos if required.

**Comment by anthonywnz** [comment]
Hello, just wondering if there's any estimated timeline for this being addressed?

We've had this happen a few times on our site now, and we've not identified a good way to actually identify orders where this happens.

Is there anyone else facing this issue that has a workaround or solution to at least identify these orders? I'm surprised that nobody else is reporting this.
