### ISSUE TITLE
Apple Pay Button not showing in checkout

### ISSUE THREAD

**Issue by SimonKubica** [woocommerce/woocommerce-gateway-stripe#176]
#### What I expected

To be able to see an Apple Pay button on the checkout page when using my Apple Pay ready iPhone.

#### What happened instead

No Apple Pay button appearing in the frontend and no Apple Pay code in the page html.

#### Steps to reproduce the issue

Install the master plugin via FTP, enable Apple Pay in settings along with in Stripe dashboard. View checkout page.

I believe that Apple Pay support has been pulled from the master, I assume to stop people adding it to production sites? It doesn't seem to be visible in the frontend despite me setting it up correctly.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Please give more details. Are you using a Apple Developer's account in test mode and or live? Are you using Safari on iPhone 6 and higher?

**Comment by SimonKubica** [comment]
I am using an iPhone 7 on the latest version of iOS. I am able to make Apple Pay purchases using this device on other websites. However as the Apple Pay button is not appearing in the checkout page HTML at all, I assume that the device being used is not the issue. 

I am in live mode in Stripe settings. I do not have an Apple Developers account, is there any reason I would need one?

**Comment by roykho** [comment]
Are you seeing any JS errors in the browser console? Try switching your theme to a WP default theme or Storefront theme.

**Comment by SimonKubica** [comment]
No JS errors. You can add a product to your cart and visit the checkout here to see that Apple Pay is not appearing there. 

https://shavershianfitness.com/

**Comment by roykho** [comment]
Check if your country is a supported country here https://support.stripe.com/questions/apple-pay-questions

**Comment by SimonKubica** [comment]
Hi Roy, yes Apple Pay is supported in Australia. In Stripe dashboard, I have successfully setup Apple Pay. Can you see any reason why this is not appearing in the checkout page of the aforementioned URL?

You can also see here, that others are reporting not being able to get this working in the comments section: http://chrislema.com/woocommerce-apple-pay-integration/

**Comment by roykho** [comment]
As I mentioned before test your theme, change it to a default theme. Also change your currency to USD to test.

**Comment by SimonKubica** [comment]
It was actually not having WooCommerce up to date that caused the issue. Maybe a notice on the plugin that checks to ensure the latest WooCommerce version is present would be useful to users who may get confused as to why Apple Pay is not working would help. Thanks!
