### ISSUE TITLE
Update Documentation for New Checkout Experience(UPE) Release

### ISSUE THREAD

**Issue by tommyshellberg** [woocommerce/woocommerce-gateway-stripe#1763]
Fixes #1676 

For the release of the new Checkout Experience, we'll need to make quite a few updates to the [existing Stripe plugin documentation](https://docs.woocommerce.com/document/stripe/).

There are essentially two parts to this: the new Settings page updates and actual UPE implementation at checkout. Since they could technically be launched separately and they're handled by different squads, I've separated them here.

Please ensure that all the `TODO` links on the plugin's side have been replaced with the correct URLs.

### Setup and Configuration 

- [x] Update [screenshot of general settings page](https://docs.woocommerce.com/wp-content/uploads/2012/09/WooCommerce-Stripe-Settings-1.png) under Setup and Configuration section.
- [x] Update section text to accommodate for changes in configuration from the main settings page(keys, webhook secret, express checkout button customization not modified directly on settings page).
- [ ] Update the setup steps to include the new OAuth signup flow along with manual key setup.
Design post: pc4etw-i9-p2
- [ ] Work with the localization team to ensure plugin will have updated strings for the settings fields and screenshots in multiple languages(French, Spanish, Portuguese). Could be a good time for German to show up. :)
- [ ] Add a new section explaining the new Checkout Experience; this can be lifted from WooCommerce Payments. 
- [x] Include text instructions for enabling UPE along with screenshot of before/after enabling.

### Additional Payment Methods
This section would need to be re-worked to separate the UPE methods from non-UPE methods(GiroPay, SOFORT, SEPA, etc).

- [x] Update the screenshot to show the above methods as part of the core Stripe method w/ UPE(not their own gateways).
Design Post: pc4etw-a9-p2
- [x] Instructions on how to add new payment methods with screenshot.
- [x] Instructions for removing a specific payment method with screenshot.

### Payment Request Buttons
The Express Checkout buttons now have a new UI for customization so we'll need to update with screenshots and instructions.
- [x] Update Payment Request Buttons customization area with screenshots and instructions
- [x] Bonus: GIF showing the button changing based on settings change.

### Webhooks
Once a user is authenticated with OAuth, they'll have a button to edit keys and webhook settings.

- [x] Update text on how to add or update webhook settings for the plugin.
- [x] Update screenshot showing how to edit once a connection has been created.
Design post: pc4etw-a9-p2

### Customer Usage

- [x] The current doc says that the checkout form uses Stripe Elements, to be totally accurate we would want to first show the new Checkout Experience w/ UPE along with an updated screenshot showing GiroPay, SOFORT, SEPA, etc. This needs to live alongside the existing checkout experience until UPE becomes the standard.
- [x] Update the [Saved Card(token) screenshot ](https://docs.woocommerce.com/wp-content/uploads/2012/09/stripe_docs_stripe_checkout_field_saved.png)as well.
- [x] Explain how the payment methods will be dynamically shown to the customer based on their location **and** translated in their language.
- [x] If the Payment Request(Express Checkout) Buttons images are out of date, update the screenshots.

## General(could be done by either squad)

- [ ] Make a doc for [Stripe fees like WCPay?](https://docs.woocommerce.com/document/payments/faq/fees/)
- [ ] Add a list of [supported countries like WCPay?](https://docs.woocommerce.com/document/payments/countries/)

**Comment by dechov** [comment]
The new settings were released today in 5.8.0, and @ricardo and I have updated the documentation, covering the bulk of what was listed above, though not precisely every item. It will likely need some more tweaks over the next release or two.

**Comment by lovo-h** [comment]
An [issue that came up in a separate thread](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2149#issuecomment-969265678) and that [we may want to address here](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2149#issuecomment-969299485), is the following:
- In the Stripe docs, we could rename the link `https://woocommerce.com/document/privacy-payments/#section-3` to `https://woocommerce.com/document/privacy-payments/#woocommerce-gateway-stripe` for more accurately named links.

**Comment by ricardo** [comment]
@lovo-h I've made the suggested change, but probably due to cache it's still not showing up. I'll check later.

**Comment by ricardo** [comment]
Update: There's actually a compatibility problem between the new WooCommerce documentation and blocks, which makes it impossible now to assign custom anchors to headings.

This should be fixed here 11997-gh-Automattic/woocommerce.com

**Comment by lovo-h** [comment]
@ricardo, thanks for looking into this.

Will we need to update the `#woocommerce-gateway-stripe` anchor links in [woocommerce-gateway-stripe](https://github.com/woocommerce/woocommerce-gateway-stripe), for the meantime?

Or should we wait for [the issue](https://href.li/?11997-gh-Automattic/woocommerce.com) to be resolved, leave the links as-is in the meantime, and update the docs to coincide with the anchor links once the issue has been resolved?

**Comment by ricardo** [comment]
I'd say we can wait for a fix in woocommerce.com. We still have some time until the next Stripe release, so either way we wouldn't have an immediate fix.

**Comment by dougaitken** [comment]
As all documentation is handled internally, please open a request with Product Operations and/or the documentation guild for any docs updates still required.
