### ISSUE TITLE
Add "Select all" to UPE onboarding wizard second step

### ISSUE THREAD

**Issue by harriswong** [woocommerce/woocommerce-gateway-stripe#1765]
## Description
Add "Select all" so that when user clicks it, all payments are selected.
![image](https://user-images.githubusercontent.com/572862/131378519-2d03d9fc-8dd7-4851-9a25-2806d8f0d86f.png)

relates to https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1683

## Acceptance criteria
- Clicking "Select all" should select all payments.

**Comment by waclawjacek** [comment]
I have implemented this in #1796 which is currently in draft state.
