### ISSUE TITLE
Apple Pay Overwriting Billing Country

### ISSUE THREAD

**Issue by prescottt** [woocommerce/woocommerce-gateway-stripe#177]
#### What I expected

Tested Apple Pay using my UK registered credit card and UK billing address, expected the address to be passed to Stripe exactly as it is set in my phone, ending 'United Kingdom'.

#### What happened instead

When I view the completed payment details in Stripe's dashboard, the last line of the billing address I used 'United Kingdom' is replaced by 'gb' so it must be identifying the country code somewhere, but underneath that 'Origin' is set to 'United States' and also when I view the order in Woocommerce the last line of my address has been saved as 'United States (US)'

#### Steps to reproduce the issue

Checkout using Apple Pay and a UK billing address (or possibly any address outside the US?), check the address saved in the Stripe payment details and in Woocommerce order details

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
I spoke with Stripe about this and it turns out the `Origin` takes the IP address of where the transaction took place and if the IP denotes United States, then that is what it will show. This is not something we can manipulate in our plugin.
