### ISSUE TITLE
UPE fails to process payment if some checkout fields are missing

### ISSUE THREAD

**Issue by bborman22** [woocommerce/woocommerce-gateway-stripe#1770]
**Describe the bug**
This is a reference to a similarly discovered bug from a [WCPay issue](https://github.com/Automattic/woocommerce-payments/issues/2785). When using a plugin that allows editing the checkout fields such as [Checkout Field Editor](https://woocommerce.com/products/woocommerce-checkout-field-editor/), it is possible to remove a field that gets referenced during a UPE checkout. When creating the UPE element [we tell it that there is no need to collect certain fields](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/1de740902485806f48d28b75ea7e57ed7a540f8e/client/classic/upe/index.js#L109) on the expecation that we will be passing them in later. We then [retrieve those fields to pass in when we process the payment](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/1de740902485806f48d28b75ea7e57ed7a540f8e/client/classic/upe/index.js#L211), but if the fields are removed this causes an error.

There will be scenarios where fields won't be necessary to UPE, like a second address line. But there will also could be scenarios where a required field is removed, like country or postal code for credit cards. Any fix for this issue should handle both cases.

**To Reproduce**
- Start with a store with this branch and UPE enabled (_wcstripe_feature_upe set to 'yes' in wp_options table) and the new checkout experience enabled from the WC Stripe settings page.
- Install a plugin that allows you to edit checkout fields, such as [Checkout Field Editor](https://woocommerce.com/products/woocommerce-checkout-field-editor/).
- Disable one of the fields, such as `billing_address_2`
- As a customer, go to checkout with a product.
- Enter valid payment details in the UPE and click Place Order.
- Confirm that the error message in the screenshot below is displayed and customer is unable to checkout.

**Expected behavior**
Any non-required address fields should not prevent a checkout and any required fields should not be removed from the UPE so the customer could still checkout even if the required fields are removed elsewhere.

**Screenshots**
![UPE-checkoutfields-error](https://user-images.githubusercontent.com/68524302/131569426-e4cd1ab0-0cd2-4287-8b91-946f128a8e15.png)

**Comment by melek** [comment]
Also encountered in 4269213-zen
