### ISSUE TITLE
Add UPE methods' metadata (localized names, descriptions)

### ISSUE THREAD

**Issue by EvanDotPro** [woocommerce/woocommerce-gateway-stripe#1773]
- [ ] Add readable names, short, and long descriptions for all UPE methods.
- [ ] Ensure all names/descriptions are localized with `__( )`.
- [ ] Verify the `reusable` attribute is correct on all UPE methods.

**Comment by c-shultz** [comment]
@EvanDotPro I'm making sure we have a good picture of MVP vs non-MVP issues. Would this fall in the category of a nice-to-have technical debt cleanup? I'll tentatively mark it that way, but let me know if I'm misunderstanding

**Comment by frosso** [comment]
I'm splitting up this ticket so it can be split between a few people (I still added everything to the MVP Milestone):
- Description/name updates: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1892
- Reusable attribute: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1901
- Short description is not going to be applicable to the newer designs (it's replaced by the "Needs activation" bubble)

Let me know if I missed anything!
Closing this for now.
