### ISSUE TITLE
Getting Subscription Customer ID from User instead of Subscription Order

### ISSUE THREAD

**Issue by MachineITSvcs** [woocommerce/woocommerce-gateway-stripe#1775]
Since the last update, the prepare_order_source() function in the file:
includes/abstracts/abstract-wc-stripe-payment-gateway.php
has been updated to set the $stripe_customer_id variable by user option instead of the Customer ID as defined in the Subscription.

Before the line read as:
`$stripe_customer_id = get_post_meta( $order_id, '_stripe_customer_id', true );`

But now it reads as:
`$stripe_customer_id = $this->get_stripe_customer_id( $order );`

The get_stripe_customer_id() function it now calls first checks if the user option is set, and if not uses the subscription order meta, but it should check the subscription order meta first if the subscription has the customer ID option. Otherwise, the Customer ID option/text box/meta on the subscription is useless. Today most of my subscriptions failed, as the Customer ID has been updated on the subscriptions since the initial orders (when the old customer ID’s were stored to the user options). Now I have to go through all my subscriptions and update the corresponding customer’s ‘_stripe_customer_id’ option to match the new customer ID in the subscriptions, or manually revert this line of file back to the previous code myself. But why have this option still be in the subscription if it does nothing? I’d really prefer to keep this option in the subscription and reference to it correctly in the code.

Thank you for the great plugin. For now I will just revert this line of the code back to the previous version so I can retry the failed payments.

To Reproduce:
1. Get a subscription order (initial customer ID is stored as user option) and in subscription as meta
2. Update customer ID in subscription by clicking pen icon to edit Billing information
3. Attempt to process renewal and you'll see customer ID used is old ID stored as user option, not what was updated in subscription meta

Expected behavior:
It should attempt to get the customer ID from subscription since it's stored there specifically for that subscription. Customer ID could change on user. A subscription renewal should use the customer ID set in the subscription itself, otherwise why have the option there? Perhaps utilize the same get_stripe_customer_id() function but make the subscription meta primary and fallback to user option, perhaps on failure and replace it in subscription ONLY IF the renewal failed (i.e. subscription meta customer ID not found).

**Comment by sisaacrussell** [comment]
Woke up to the same: dozens of subscription renewals that failed with an error in the order log as "Sorry, we are unable to process your payment at this time. Please retry later."

The debug logs show:

```
2021-09-01T17:48:40+00:00 DEBUG 
====Stripe Version: 5.4.0====
====Start Log====
Error: stdClass Object
(
    [error] => stdClass Object
        (
            [message] => The PaymentMethod card_[redacted] does not belong to the Customer you supplied cus_[redacted]. Please use this PaymentMethod with the Customer that it belongs to instead.
            [param] => payment_method
            [type] => invalid_request_error
        )

)

====End Log====
```

Thanks for sharing the temporary patch, @MachineITSvcs

**Comment by reykjalin** [comment]
Thank you for the report and testing instructions @MachineITSvcs! 

We're working on releasing a fix for this as we speak, we hope to have it out in the next several hours 🙂

**Comment by diegocurbelo** [comment]
Hey @MachineITSvcs 👋🏼.. We have released version 5.4.1 with the fix you suggested. Thank you again for reporting the issue! 😄

**Comment by MachineITSvcs** [comment]
Great! Thanks! 😄

**Comment by senff** [comment]
I just noticed a customer reporting the same issue even though they do have 5.4.1:

```
2021-09-02T11:25:13+00:00 DEBUG
====Stripe Version: 5.4.1====
====Start Log====
Error: stdClass Object
(
[error] => stdClass Object
(
[code] => payment_intent_incompatible_payment_method
[doc_url] => https://stripe.com/docs/error-codes/payment-intent-incompatible-payment-method
[message] => The Source src_1JPRUkClzsaJuxhFveigUzrr does not belong to the Customer you supplied cus_K6v12lS1ZeZEth. Please use this Source with the Customer that it belongs to instead.
[param] => source
[type] => invalid_request_error
)
```

Ref: 4267603-zen

**Comment by MachineITSvcs** [comment]
I can confirm the new version 5.4.1 works for me. He should check his Stripe Dashboard and make sure both the customer exists by the ID and the source is linked to the customer, and not a single-use source (has to be recurring).

**Comment by reykjalin** [comment]
I'm closing this since it seems the issue has been fixed. I'll keep an eye on the ticket @senff and we'll re-open the issue if this is still a problem 🙂

**Comment by jrick1229** [comment]
_redacted_

**Comment by MachineITSvcs** [comment]
@jrick1229 please read above message on what to try next

**Comment by jrick1229** [comment]
Sorry @MachineITSvcs - can't believe I missed that 😁
