### ISSUE TITLE
Checkout Form Field Validation After Card Details Submitted

### ISSUE THREAD

**Issue by ApplicationError** [woocommerce/woocommerce-gateway-stripe#178]
What I expected:

1.) Enter personal details on the checkout page
2.) Choose Stripe as payment option
3.) Click on "Continue to payment"
4.) Get error message shown with invalid value in form

Actual experience:

1.) Enter personal details on the checkout page
2.) Choose Stripe as payment option
3.) Click on "Continue to payment"
4.) Stripe modal is shown
5.) Enter payment details and submit
6.) Success message shown and modal closes
7.) Form field error is shown (user not redirected to completion page)

Steps to reproduce:

1.) Enter personal details on the checkout page
2.) Provide invalid email address (e.g. me@addresscom)
2.) Choose Stripe as payment option
3.) Click on "Continue to payment"
4.) Enter payment details and submit

**Comment by roykho** [comment]
Is your issue related to this? https://github.com/woocommerce/woocommerce-gateway-stripe/issues/161
