### ISSUE TITLE
UPE - Make sure saving a payment method works with pay for order page

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#1784]
The goal of this issue is to make sure saving a payment method and using a saved payment method works with the the pay for order page.

Since both features are being delivered separately in #1669 and #1730, we need to make sure they can both work together.

**Comment by diegocurbelo** [comment]
Works fine after merging #1669 and #1730 (and #1891).

The error when the `pre-orders` plugin is enabled is going to be fixed in #1820, but after #1891 was merged UPE is automatically disabled if `pre-orders` plugin is enabled
