### ISSUE TITLE
UPE - Block checkout support

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#1787]
The goal of this issue is to bring support for UPE in the [block checkout](https://docs.woocommerce.com/document/using-the-new-block-based-checkout/).

The implementation will probably look similar to WCPay - 2429-gh-Automattic/woocommerce-payments.

Things to keep in mind:
- Make sure the existing express checkout block (aka payment request buttons) still works in the checkout flow.
- If #1730 is already implemented, make sure saving a payment method and using saved payment methods still works. Otherwise create a new issue for this feature.

**Comment by EvanDotPro** [comment]
Related: #1667

**Comment by ricardo** [comment]
@EvanDotPro this is related, but the other is intended to be a spike. This would be for actually implementing UPE in the block checkout.
