### ISSUE TITLE
[settings] account keys - connection test functionality

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1806]
## Description
A "Test connection" button allows testing the connection to the Stripe server with the keys entered in the modal

![Screen Shot 2021-09-08 at 4 12 00 PM](https://user-images.githubusercontent.com/273592/132586292-52e6a387-b51e-43a2-80a1-5f4ddde61439.png)

**Comment by ricardo** [comment]
Blocked by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2073.

I'm not aware of any existing or previous functionality to simply test the connection from the old settings, but one way I see this could work is by implementing two subsequent requests, one for the publishable key and another for the secret key:

1. For the publishable key, we could create a new token, example:
```js
const stripe = new Stripe('pk_test_***');
stripe.createToken('pii', { personal_id_number: '123456789' });
```

2. For the secret key, we could get the token id from the above Promise and make an AJAX request to an endpoint which tries to retrieve the token, that way we can match this public key with its pair secret key, and not validate the keys separately.

---

Personally, I don't think we need to validate the webhook signing secret, so a successful message which says something like "[Live/Test] publishable and secret keys are valid" should work.

Edit: Also, the webhook secret validation might require having to set up webhooks first. And there's already some notices about webhook validation under the "Account details" card.

And regarding the feedback, how should the success/error message look like? A toast or a notification perhaps?

**Comment by frosso** [comment]
The priority on this should be pretty low - it's not something that the current Stripe plugin offers.

>  And regarding the feedback, how should the success/error message look like? A toast or a notification perhaps?

From my understanding, it would happen inline with the button (at least that's what the Figma designs propose):
![Screen Shot 2021-11-04 at 12 09 35 PM](https://user-images.githubusercontent.com/273592/140386433-df6e518c-be1e-466a-ab8f-056693cbf088.png)
![Screen Shot 2021-11-04 at 12 09 45 PM](https://user-images.githubusercontent.com/273592/140386430-8e561e89-4895-4423-ad9d-f7cfa0a3d5bf.png)
![Screen Shot 2021-11-04 at 12 09 39 PM](https://user-images.githubusercontent.com/273592/140386432-fc2e0bea-98be-4c08-85b6-7b2d4001b853.png)

I'm unsure if there have been additional updates from UX on this :)
