### ISSUE TITLE
[settings] checkout preview functionality

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1808]
## Description

Allows the merchant to preview their checkout experience.

**Comment by cesarcosta99** [comment]
@frosso do you know if there is a design for that (I couldn't find it)? Otherwise we should close this issue.

**Comment by frosso** [comment]
@cesarcosta99 here it is:

![Screen Shot 2021-11-18 at 4 53 41 PM](https://user-images.githubusercontent.com/273592/142509711-91629b01-a2e6-4c41-9364-991107f270bb.png)

To be confirmed with UX whether the preview should display unsaved or saved settings.

**Comment by cesarcosta99** [comment]
Thank you, @frosso!

@jarekmorawski do we have a flow or idea on how we would like to display that preview for the user? Would that be on a modal? On a new page? Or simply redirecting the user to the checkout page?

**Comment by jarekmorawski** [comment]
> Would that be on a modal? On a new page? Or simply redirecting the user to the checkout page?

If you have time, we'd display the preview in a modal per the design below (the same design was used in the multi currency settings). If you don't have time, we could open checkout in a new tab.

![image](https://user-images.githubusercontent.com/79307566/143203903-60cd1412-06f4-4405-a877-e0a4c0719ee4.png)


> To be confirmed with UX whether the preview should display unsaved or saved settings.

I assume it'll be easier to display saved settings.
