### ISSUE TITLE
[settings - UPE] Stripe settings persistence - main settings page

### ISSUE THREAD

**Issue by waclawjacek** [woocommerce/woocommerce-gateway-stripe#1812]
Part of #1717.

Add settings data API integration to the main settings page (both "Payment methods" and "Settings" tabs).

Due to some uncertainty regarding the Payment methods card on the main settings page (p1631570172089800-slack-C01RTUVR81K), this component should not be included in the PR.

**Comment by harriswong** [comment]
Block by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1797 and https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1796

**Comment by c-shultz** [comment]
@waclawjacek We're pausing on this to focus on using the old settings instead (for now), so I'm unassigning you
