### ISSUE TITLE
UPE - Pre-orders support

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#1820]
The goal of this issue is to add support for pre-orders in the UPE checkout. The issue is complete when UPE can be used for pre-orders.

This issue will probably involve some refactoring around the `WC_Stripe_Pre_Orders_Compat` class and turning it into a trait.

**Steps to test pre-orders support:**
1. Install and activate [WooCommerce Pre-Orders](https://woocommerce.com/products/woocommerce-pre-orders/).
2. Create a new pre-order product:
  i. Under product data, choose "Simple product".
  ii. Add a regular price.
  ii. Click "Pre-Orders".
  iii. Enable pre-orders.
  iv. Set an availability time in the future.
  v. Select "When to charge: Upon Release".
  vi. Click "Create/Update".
3. Try checking out with and without UPE enabled. You'll see the payment method when it's available.

**Comment by ricardo** [comment]
@superdav42 Have you started with this issue? And if so, do you plan to resume it? Otherwise I could assign myself.

**Comment by superdav42** [comment]
@ricardo I did start before but basically everything I did is no good now. So feel free to take it.
The current work done with subscription free trials is basically the some thing we need to do for pre-orders so it should be easier now.
