### ISSUE TITLE
UPE - Add notice to settings page letting merchants know about unsupported features

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#1821]
The goal of this issue is to implement some sort of notice in the settings page, letting merchants know that some features might not be fully supported in case they enable UPE.

Ideally, I believe we should mention which specific features are not (fully) supported, e.g Pre-orders or Blocks checkout. It doesn't need to be a regular notice component, but it should communicate what's not supported when UPE is enabled.

We can also consider checking if that feature is available in the store, i.e checking if the Pre-orders plugin is installed, before displaying the notice, to avoid confusion around separate extensions that the merchant might not even be familiar with.

This issue doesn't need to be fixed in case we get 100% of the UPE scope released before the deadline (currently September 30th).

👉 In case the new settings is done, this needs to be implemented in the new settings, otherwise it should be in the old settings.

**Comment by c-shultz** [comment]
I'm moving this off the MVP milestone. We'll aim to capture this as a note in the docs to start with: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1899

**Comment by ricardo** [comment]
The goal of this issue was mostly to inform users about possible unsupported features before we released UPE.

This doesn't seem relevant anymore, since pre-orders, blocks and subscriptions should be fully supported now.
