### ISSUE TITLE
[settings] account status display

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1822]
## Description

We need to display the information about the account status on the UI.
So far we have hardcoded data styled in the UI ( https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1758 ). We now need to display accurate information, with data gathered from the backend/Stripe API.

## Acceptance criteria
- "Payments" status is accurate
- "Deposits" status is accurate
- "Base fee" status is accurate

**Comment by Mayisha** [comment]
Need to show the real information for `Payments` and `Deposits`. We don't need the `Base fee` here as per the design decision. [Here](https://github.com/woocommerce/woocommerce-transact-design/issues/29) is the design ticket.
