### ISSUE TITLE
SPIKE: Toggling live/test mode without inputting test keys results in onboarding

### ISSUE THREAD

**Issue by waclawjacek** [woocommerce/woocommerce-gateway-stripe#1827]
In the "Connect Stripe Account" onboarding modal, if you have live keys but you enable test mode without entering keys, you are presented with a modal as if you had no keys. Maybe we should treat this scenario differently? [Initially discovered here.](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1774#pullrequestreview-743713421)

> Let's say you are using test mode. In the current UI, when you do a fresh installation, enable test mode and input the test API keys, the live keys are blank but everything will works as expected. This is good.
> 
> However, when you toggle the checkbox so it says "live mode" now and you don't input live keys, you'll get the Connect Stripe Account card displayed now, even though you have some keys that are working, you just don't have the ones for the currently-selected mode (live/test).
> 
> The same probably happens if you have live keys but you switch to test mode and don't input test keys - you'll get the Connect Stripe Account card.
> 
> I am wondering if this could be misleading to merchants and if there is something we could do about it. Maybe this is a question for a separate issue.

**Comment by frosso** [comment]
Added to the board as a spike, might be good to figure this scenario out with UX.

**Comment by frosso** [comment]
I just realized - in the original requirements we'll want to show the modal to enter the keys when test mode is enabled and the keys are not present: pc4etw-i9-p2

![2021-09-30 11 40 59](https://user-images.githubusercontent.com/273592/135496533-266bfb5a-1206-4819-80b1-b7a0b1aa0473.gif)

@waclawjacek does this sound acceptable?

**Comment by waclawjacek** [comment]
Yep! This prevents the situation where the extension acts as if the user's never used it.

**Comment by frosso** [comment]
Thanks for confirming - I'll close this for now.
We'll tackle the account keys form UI here: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1835
