### ISSUE TITLE
[settings] account keys form UI

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1835]
## Description

Clicking the "Edit details" button on the settings UI opens a modal that allows to enter the account keys and the webhook secret.
Clicking "Enter account keys (advanced)" on the onboarding UI opens a modal that allows to enter the **live** account keys and the webhook secret (PLEASE NOTE: the latest designs have been updated, but let's use the same modal for now, as a first step).
Clicking "enable test mode" without test keys should open _the same form_ (without the live/test keys tabs) that allows to enter the test keys (in a different modal).

The modal persists the data to the backend (use `wp/data` implementation from https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2004 ) immediately after confirmation.

![live keys modal](https://user-images.githubusercontent.com/273592/132585128-57efce9e-6fff-443f-b646-f9681db98d8a.png)

![Keys edit modal](https://user-images.githubusercontent.com/273592/132585851-de74ae02-95b4-4d2d-ab8e-02627f17ab3e.png)

![2021-09-30 11 40 59](https://user-images.githubusercontent.com/273592/135496533-266bfb5a-1206-4819-80b1-b7a0b1aa0473.gif)

The "Test connection" functionality is implemented separately: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1806

## Acceptance criteria
- Enabling "Enable test mode" without test keys opens the modal that allows to enter test keys
- Disabling "Enable test mode" without live keys opens the modal that allows to enter live keys
- Clicking the "Edit details" button opens the modal
- Clicking "Enter account keys (advanced)" on the onboarding UI opens the modal
- Modal matches the latest design (please be aware that the attached screenshot might not be updated)
- Modal is dismissable
- Clicking the "Save & connect" button persists the data to the backend
- Once the data is successfully persisted, the modal is closed
- dismissing the modal should not persist the data, and reopening it should show the persisted data (not the previously edited one)
- On the onboarding UI, the page is refreshed once the data is successfully persisted

**Comment by harriswong** [comment]
@frosso This is only for the 3 fields (publishable key, live key, webhook secret) in the screenshot right? Not for everything inside the original settings page:
![image](https://user-images.githubusercontent.com/572862/132922260-73ee8422-c3cc-460a-84a7-20844416539a.png)

**Comment by frosso** [comment]
@harriswong that's correct - this controller should be specific to the webhook secret/publishable key/secret key. Possibly for both test and live mode of those 3 fields.

**Comment by harriswong** [comment]
Perfect, thanks!

**Comment by frosso** [comment]
Hey @tommyshellberg , I noticed you picked up this ticket. A few days ago (before https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2004 was getting merged ) I started adding a confirmation modal for test mode here: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2024

Just pointing it out, since it's going overlap with part of the requirements of this ticket :)

**Comment by tommyshellberg** [comment]
This is about 90% done but could use some polish and another test before a PR review is done. Pushing up what I have as a Draft PR.
