### ISSUE TITLE
Apple Pay domain verification failed. Please check the log to see the issue.

### ISSUE THREAD

**Issue by reidbiztech** [woocommerce/woocommerce-gateway-stripe#185]
From my post on the wordpress.org support forum:

I am getting this error after updating from 3.0.7 to 3.1.0:

>Apple Pay domain verification failed. Please check the log to see the issue.

The word "log" in that message is linked (`/wp-admin/page=wc-status&tab=logs`), which gives a 404 error on my WooCommerce 2.6.14 install.

I suspect you are trying to use the Woo 2.7.0/3.0.0 log where it does not yet exist?

Checking my server error logs, I find this error:
`PHP Warning:  mkdir(): File exists in wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 326, referer: wp-admin/admin.php?page=wc-settings&tab=checkout`

And looking at the code I see you are using the .well-known directory, I already have such a folder from using Let's Encrypt (via Virtualmin)...

I will take a look at the filesystem and see if I can figure out what happened with your code on my server.

and a follow up post:

I think I see the problem. They are trying to create the .well-known directory without first checking for its existence and throwing an exception inside a try statement… so the file does not get copied to the directory in the code that follows.

mkdir will return false if the directory already exists.

edit: correction – they are checking for the directory… but something funky is going on here… :/

Also, you may need to check your logging code and references for compatibility with Woo 2.6.x

**Comment by roykho** [comment]
That's correct. The code assumes you didn't have the .well-known path already and if it does, it won't proceed to overwrite anything.

**Comment by reidbiztech** [comment]
I think I do see a problem in the logic though...

```php
			if ( ! file_exists( $path . '/' . $dir ) || ! file_exists( $fullpath ) ) {
				if ( ! mkdir( $path . '/' . $dir, 0755 ) ) {
					throw new Exception( __( 'Unable to create domain association folder to domain root.', 'woocommerce-gateway-stripe' ) );
				}

				if ( ! file_exists( $path . '/' . $dir . '/' . 'apple-developer-merchantid-domain-association' ) ) {
					if ( ! copy( WC_STRIPE_PLUGIN_PATH . '/' . $file, $fullpath ) ) {
						throw new Exception( __( 'Unable to copy domain association file to domain root.', 'woocommerce-gateway-stripe' ) );
					}
				}
			}
```

That first conidtional is an OR, so it tries to create the directory even though it exists, because the conditional also checks for the file.

**Comment by roykho** [comment]
There is a check even before that see https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L321

**Comment by reidbiztech** [comment]
But that check is for the fullpath/filename....

**Comment by roykho** [comment]
Right. I think I know what you mean now. You have .well-known but for other reasons, not for Apple Pay? Is that correct? I thought you meant you already have .well-known with the apple pay association file.

**Comment by reidbiztech** [comment]
Correct, the .well-known directory already exists on my server as it is used by Let's Encrypt.

**Comment by reidbiztech** [comment]
So I have modified that block of code to separate the conditionals like so:

```php
if ( ! file_exists( $path . '/' . $dir ) ) {
	if ( ! mkdir( $path . '/' . $dir, 0755 ) ) {
		throw new Exception( __( 'Unable to create domain association folder to domain root.', 'woocommerce-gateway-stripe' ) );
	}
}

if ( ! file_exists( $fullpath ) ) {
	if ( ! file_exists( $path . '/' . $dir . '/' . 'apple-developer-merchantid-domain-association' ) ) {
		if ( ! copy( WC_STRIPE_PLUGIN_PATH . '/' . $file, $fullpath ) ) {
			throw new Exception( __( 'Unable to copy domain association file to domain root.', 'woocommerce-gateway-stripe' ) );
		}
	}
}
```

and now I find this error in my log:

`PHP Warning:  copy(/home/*accountname*/public_html/wp-content/plugins/woocommerce-gateway-stripe/apple-developer-merchantid-domain-association): failed to open stream: No such file or directory in /home/*accountname*/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 333, referer: https://*mydomain*/wp-admin/admin.php?page=wc-settings&tab=checkout`

(error anonymised for post)

I will now look into why this is happening...

**Comment by reidbiztech** [comment]
And that would be because that file:
woocommerce-gateway-stripe/apple-developer-merchantid-domain-association

does not exist in the plugin as distributed or installed.

Also there is the log thing.

Woo is beginning to have some worrisome QA issues.

**Comment by reidbiztech** [comment]
the file (apple-developer-merchantid-domain-association) is present in the github tree but not in the zip file distributed on wordpress.org.

i mean really, I'm sorry... but this kind of thing is totally unacceptable with millions of installs...

**Comment by reidbiztech** [comment]
Even if the file were included, how can this possibly work, with millions of domains/sites all using the exact same domain verification file? I have not looked at the Apple Pay API (because Apple), but I am pretty confident that is not how it is supposed to work. My bet is that you need to generate this file on every site, tell apple about it and its contents, and then have apple look for it. Using the same file for everyone makes no sense at all as a domain ownership verification.

**Comment by lhopkins** [comment]
Isn't this issue just an incorrect URL?

**Current** URL: `/wp-admin/page=wc-status&tab=logs`
**Correct** URL: `/wp-admin/admin.php?page=wc-status&tab=logs`

The log page exists even with WC 2.6.14.

**Comment by roykho** [comment]
Nope that file is a generic file and not site specific

**Comment by robconery** [comment]
@reidbiztech this is how it's supposed to work - same domain ver file for everyone; it just identifies Stripe as the vendor. 

Also: thanks for your sleuthing. This is rather annoying as I'm having the same problems as you... errors everywhere.

**Comment by lhopkins** [comment]
@roykho How is `/wp-admin/page=wc-status&tab=logs` not incorrect? It has query arguments but no leading `?`? Also missing `admin.php`. How could that URL ever resolve correctly?

I am also having an issue in WC_Gateway_Stripe::process_apple_pay_verification() on line 328. Checks to see if `/.well-known` or `/.well-known/apple-developer-merchantid-domain-association` exist. If `/.well-known` exists but `/.well-known/apple-developer-merchantid-domain-association` does not, it still attempts to create `/.well-known` anyway, resulting in a PHP warning.

**Comment by robconery** [comment]
It is incorrect, checking the log files results in a 404. Also @lhopkins you are correct, errors and warnings. Wondering if this is a regression or if anyone tested this ...?

**Comment by roykho** [comment]
Not sure what you mean I didnt reply to you

**Comment by roykho** [comment]
My replies are for op. If you have other issues please open new issue.

**Comment by lhopkins** [comment]
@roykho Apologies, did not realize your reply was for OP. However, my original question is exactly this issue and belongs here. OP said `/wp-admin/page=wc-status&tab=logs` resulted in 404, same for me. This URL cannot resolve correctly. However, the corrected URL I posted does resolve correctly.

I will open a separate issue for the `WC_Gateway_Stripe::process_apple_pay_verification()` issue.

**Comment by robconery** [comment]
For what it's worth I was able to fix this error by:

 - Go to Stripe, [Apple Pay Settings](https://dashboard.stripe.com/account/apple_pay)
 - Add New Domain, then download the verification file
 - Go to your WP root and find the .well-known directory this plugin is fumbling around with
 - Add the verification file manually

This worked for me and removed all warnings.

**Comment by cubewebsolutions** [comment]
@robconery interestingly I created the .well-known directory and downloaded the verification file and uploaded it via ftp for a bunch of clients. I then updated all client's Stripe extensions... went to their WooCommerce Settings / Checkout, and I got the error at the top of the page 'Apple Pay domain verification failed. Please check the log to see the issue.' that everyone is talking about.

If I simply clicked on 'Save' at the bottom of the page, the error goes away.

I'm not sure what to make of that.

And yes, the link on the word 'Log' is incorrect and needs to be fixed.

**Comment by roykho** [comment]
Please pull from master branch and load that to your site and see if it corrects your issue.

**Comment by reidbiztech** [comment]
I have already manually corrected the code and uploaded the verification file.

If you need assistance with software QA, please contact me and we can discuss rates.

**Comment by lhopkins** [comment]
@roykho Confirmed that this resolves the URL issue.

**Comment by roykho** [comment]
@lhopkins Thanks for checking. Can anyone confirm Apple Pay is working for them?

**Comment by roykho** [comment]
Close via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/4ea63e66b8f318e48d3b2b40406901652573a8b1

**Comment by robconery** [comment]
It's working for me, yes. Crowd-sourced QA FTW...

**Comment by roykho** [comment]
The main issue here was an oversight of the logic assuming `.well-known` does not already exist. Sorry folks.

**Comment by markdeli** [comment]
This is still an issue for me. Even with the 3.1.1. update installed.
"Error: Unable to copy domain association file to domain root." is what I am seeing in the LOG. Any insight as to why this issue was closed even though it still exists?

**Comment by roykho** [comment]
@markdeli - not the same issue. Yours is most likely a genuine "cannot copy file to location". This could be a server configuration issue where it won't allow the app to copy things there. So for this, you probably have to do it manually.

**Comment by reidbiztech** [comment]
Sorry, but that is incorrect. The problem is that the apple-developer-merchantid-domain-association file is still not present in the distributed zip. Check wordpress.org, download the plugin, unzip it, the file is not there.

You're welcome. ;)

**Comment by roykho** [comment]
@markdeli here are steps for manual copy https://stripe.com/docs/apple-pay/web#going-live

**Comment by roykho** [comment]
@reidbiztech - it should be there. Cache?

**Comment by reidbiztech** [comment]
Nope. Not cache. The filename is different. Plugin is current version 3.1.1.

You need to add the file to the subversion repository on wordpress.org.

**Comment by reidbiztech** [comment]
Oh, I see the file is present in the repo:

https://plugins.svn.wordpress.org/woocommerce-gateway-stripe/tags/3.1.1/

But it is not in the zip... is wordpress.org dropping the file from the zip for some reason?

**Comment by roykho** [comment]
I don't think so but I do know sometimes when I just push updates to .org I get back staled files. I have to hard refresh couple times to get the updated file.

**Comment by reidbiztech** [comment]
And now the file is present in the zip file. 

Yeah wordpress.org can be a bit flaky that way.

Should be good to go from here...

**Comment by kokomomtl** [comment]
I copied the file into my .well-known folder and now I get the following error:
"03-16-2017 @ 17:36:00 - Error: Unable to verify domain - Bad Request"

**Comment by roykho** [comment]
@kokomomtl try doing it manually following these steps https://stripe.com/docs/apple-pay/web#going-live

**Comment by BurlesonBrad** [comment]
`.well-known` is done via LetsEncrypt like @reidbiztech mentioned & it's on a few **million** sites 🤕 

I totally should have mentioned something when I first saw it, tested it, & got the error months ago. On one hand I'm sorry. Yet, at the same time, passing travis / scrutinizer / or anything else **never** implies it works in real life on a real site and it's "**ready**" for a blog post / update / scatter-link-in-various-groups / or any type of announcement.

Lesson(s) learned to avoid this in the future:
1. Test It & Report It _(unlike what I did NOT do)_
2. Higher priority should be given to testing outside of the Ninjas _(which I ❤️)_ But perhaps sometimes the real world application can be better.

**Comment by OGProgrammer** [comment]
FYI as said, goto https://dashboard.stripe.com/account/apple_pay and download the cert, DO NOT COPY/PASTE THIS FILE AS THAT CHANGED CHECKSUM OR SOMETHING.

I had to SCP the file over to my server and then it worked. Oh and I had a rule in nginx that is not a fan of dot hidden folders so same with let encrypt I went and just added this to my nginx


`# Allow Lets Encrypt to do its business
# (If you get denied, its probably cause this rule isn't working and the rule below is messing LE up.)
location ^~ /.well-known/acme-challenge/ {
    allow all;
    default_type "text/plain";
}

# Apple Pay Verification
location ^~ /.well-known/apple-developer-merchantid-domain-association {
    allow all;
    default_type "text/plain";
}

# Rather than just denying .ht* in the config, why not deny
# access to all .invisible files
location ~ /\. { deny  all; access_log off; log_not_found off; }`

**Comment by jayshields** [comment]
My fix - upload the file direct, don't create the file yourself and paste the contents.

**Comment by Outer-net** [comment]
My fixperience - Get away from any computer or device, look out the window and imagine it working, once you have this in your mind > back to it and **delete .well-known folder** and **recreate it** again exactly as it should be[.well-known] > **Download the file** from [stripe account](https://stripe.com/gb) > Place this file in new folder making sure there's no file extension just [apple-developer-merchantid-domain-association] > **Empty cache and make sure you use www**. or whatever sub you use.
![jim-the-man](https://user-images.githubusercontent.com/35470102/34963354-eb560e28-fa3f-11e7-99c7-ee9284df4b5a.gif)

**Comment by mhobotpplnet** [comment]
So follow above what @cubewebsolutions said.
I generated the file in Stripe, went to my hosting - ./well-known might not be displayed but in most cpannels , you should be able to go there by manually typing the dir. Place the file from stripe and then go back to wp > woocommerce > checkout > stripe and click save..
