### ISSUE TITLE
Apple Pay button language and WPML

### ISSUE THREAD

**Issue by t-bo** [woocommerce/woocommerce-gateway-stripe#186]
How behave the Apple button language setting if we run WP on a multilungual site with WPML plugin?

**Comment by roykho** [comment]
Apple Pay has language settings.

**Comment by t-bo** [comment]
Apple Pay has single language setting. That doesn't answer the initial question when used with WPML.

**Comment by roykho** [comment]
Does not work with WPML.

**Comment by t-bo** [comment]
Enhancement suggestion.

**Comment by roykho** [comment]
WPML is quite difficult to work with so we have no plans to support that at this time.

**Comment by t-bo** [comment]
Okay but multilingual site is now pretty common, I can predict several people requests this feature anytime soon.
as WPML is supported widely in many plugins and scenarios, I don't think it's that difficult (to not plan to support it) to implement.

**Comment by roykho** [comment]
Feel free to open a PR for this code and I will review.
