### ISSUE TITLE
Fix SCA authorization flow on the non-UPE checkout

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#1866]
The SCA authorization flow is not working in `develop` due to some regression from recent UPE changes.

To fix this, we should probably revert [this change](https://github.com/woocommerce/woocommerce-gateway-stripe/commit/f4b456773b1ae1bd6f778e74ab8c3b7a2d366c32#diff-8c1f01376167e4e75ce4eee534a35f3082229236433132282465407f7ff244edL652-L677) - Internal ref: p1631814673096100/1631746474.081600-slack-C02BHNRN6R1

**Comment by FangedParakeet** [comment]
Just as a heads up, for some reason, [I undid this](https://github.com/woocommerce/woocommerce-gateway-stripe/commit/f4b456773b1ae1bd6f778e74ab8c3b7a2d366c32#diff-8c1f01376167e4e75ce4eee534a35f3082229236433132282465407f7ff244edL652-L677); I'm relatively confident putting it back and doing it again will fix this flow and once more return balance to the non-UPE checkout.
