### ISSUE TITLE
WC_Gateway_Stripe::process_apple_pay_verification() attempts to create directory that already exists.

### ISSUE THREAD

**Issue by lhopkins** [woocommerce/woocommerce-gateway-stripe#187]
`WC_Gateway_Stripe::process_apple_pay_verification()`, `line 325` checks to see if `/.well-known` or `/.well-known/apple-developer-merchantid-domain-association` exist. If `/.well-known` exists but `/.well-known/apple-developer-merchantid-domain-association` does not, it still attempts to create `/.well-known` anyway, resulting in a PHP warning.

**Comment by roykho** [comment]
Please pull from master branch and load that to your site and see if it corrects your issue.

**Comment by lhopkins** [comment]
@roykho Yes, this resolves the issue. Thanks for the quick response!

**Comment by roykho** [comment]
@lhopkins thanks for checking! closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/4ea63e66b8f318e48d3b2b40406901652573a8b1
