### ISSUE TITLE
CSRF error with 3DS & automatic user linking

### ISSUE THREAD

**Issue by Buzut** [woocommerce/woocommerce-gateway-stripe#1870]
**Describe the bug**
When a customer uses an email already associated with an account, he gets an error stating that he should connect to his account. This clearly hinders the conversion rate.

Therefore, I tap into `woocommerce_checkout_process` to automatically link the current order to the email's associated account.

```php
add_action('woocommerce_checkout_process', function () {
    if (!is_user_logged_in() && $_POST['billing_email']) {
        $user = get_user_by('email', $_POST['billing_email']);

        if ($user) wp_set_current_user($user->ID);

        else {
            $user_id = wc_create_new_customer($order_email);
            wp_set_current_user($user_id);
        }
    }
});
```

It works without issue for non 3DS cards, but for 3DS cards, after verification, the user is presented an error message: "Payment verification error: CSRF verification failed.", although the payment has actually been processed.

It still works with the plugin in its 4.1.16 version where the 3DS verification happened directly on Stripe's website instead of in the onsite pop-in.

**Environment (please complete the following information):**
 - WordPress Version: 5.8.1
 - WooCommerce Version: 5.6.0
 - Stripe Plugin Version: 5.5.0

**Comment by dougaitken** [comment]
It reads like you're customizing the core functionality of the Stripe plugin and WooCommerce so we cannot offer advice about this specific Issue. 

I did take a quick look for similar and found this comment - https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1011#issuecomment-536646700 that might be of interest. 

As there hasn’t been any activity on this Issue recently, I’m going to close this Issue. If you feel this is still relevant and requires attention, please post a [new Issue](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/new/choose) with some more details.

If this is a bug, please use the [bug report Issue template](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/new?assignees=&labels=&template=bug_report.md&title=) and include all the relevant information.

For support requests, this is handled by the Happiness Engineers for the WooCommerce Stripe plugin. If you post this in the [WooCommerce Stripe Support Forums](https://wordpress.org/support/plugin/woocommerce-gateway-stripe/), someone will be able to offer support or advice there.

**Comment by Buzut** [comment]
Hi @dougaitken 

I am not in any way modifying a core functionality of Stripe's plugin. I am just using a WC hook to smartly handle user account management. Not touching Stripe in any way…
