### ISSUE TITLE
[settings - payment methods management] Show toast when payment method list is updated

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1878]
## Description
When the list of payment methods is updated through https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1875 , show toast notifying the merchant of which item has been added.

<img width="527" alt="Screen Shot 2021-09-16 at 1 00 39 PM" src="https://user-images.githubusercontent.com/273592/133661946-660c9bea-5d2c-413c-a618-a586110606ca.png">

**Comment by rafaelzaleski** [comment]
@frosso 

1. Should we show the message only after the settings are saved? or is checking the checkbox for the payment method enough to trigger the message? 
2. If the user marks the checkbox, but the payment method requires activation and/or requires currency, should we show the message anyway? They wouldn't be able to use the payment method in this scenario.

**Comment by rafaelzaleski** [comment]
Hey @jarekmorawski, can you help us with the questions above? Thank you!

**Comment by jarekmorawski** [comment]
Hi there! Thanks for the ping. 🤗 

> Should we show the message only after the settings are saved? or is checking the checkbox for the payment method enough to trigger the message?

Immediately after returning to Woo from the Stripe dashboard and refreshing the payment methods list (illustrated here: pc4etw-lh).

> If the user marks the checkbox, but the payment method requires activation and/or requires currency, should we show the message anyway? They wouldn't be able to use the payment method in this scenario.

Great question. We would only show the message when the payment method's status is active. In other cases we'd add it to the list and check the box, but also show the requirement pill and hide the method on checkout. If someone adds multiple payment methods with mixed statuses, upon returning to Woo we'd show the message only for those with the active status.

If someone checks the box/enables a payment method that was already in the payment methods list, we'd not show the message. In other words, the message is only displayed in the add-through-Stripe-dashboard flow, but not the regular payment methods management flow in Woo.
