### ISSUE TITLE
Issues adding payment method in My Account

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gateway-stripe#188]
Reported here https://wordpress.org/support/topic/there-was-a-problem-adding-the-card/

When trying to add the payment method in My Account pages, it gives an error.

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/d1c9a7d5c26f4bfd080e7b8bdecc25209dfcee12

**Comment by ziodave** [comment]
@roykho this is happening to us in 3.2.2, I see that the file doesn't have the code in the commit.

**Comment by darioconca** [comment]
That d1c9a7d fix was wiped back into
https://github.com/woocommerce/woocommerce-gateway-stripe/commit/94537973b1bf946ed71ff24f21b3f7c5ba5b2363.
I still have this problem.

**Comment by aaemnnosttv** [comment]
Still seems to be a problem. This error appears after attempting to add a payment method via `/my-account/add-payment-method/`.

![image](https://user-images.githubusercontent.com/1621608/35429235-d71a0fe2-027b-11e8-8d6f-94fdc35b7e55.png)

The user does have shipping information set, but that shouldn't matter just to add a payment method I would think.

WooCommerce 3.2.6
Stripe Gateway 4.0.3

**Comment by roykho** [comment]
No issues here. Do you have some type of custom code like anything to do with custom checkout fields?

**Comment by aaemnnosttv** [comment]
Hmmm, not yet. Could be a plugin issue perhaps. I'll see if I can figure it out and follow up.
