### ISSUE TITLE
Trying to get property of non-object in /woocommerce-gateway-stripe/includes/class-wc-stripe-apple-pay.php on line 131

### ISSUE THREAD

**Issue by cloudsurferuk** [woocommerce/woocommerce-gateway-stripe#189]
This has only started with today's update when Apple Pay was introduced.

Apple Pay is disabled the control panel however I receive the error "Trying to get property of non-object in /home/aviationwales/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-apple-pay.php on line 131" on pages.

**Comment by roykho** [comment]
@cloudsurferuk is your WP debug on?

**Comment by cloudsurferuk** [comment]
It was yes, presumably I wouldn't have seen the error otherwise.

**Comment by roykho** [comment]
So I just tried replicating your issue with WP debug on and I don't see this notice. Does it show on any particular page?

**Comment by cloudsurferuk** [comment]
It appears on the dashboard and preview pages. Not on live pages as far as I can see.

**Comment by roykho** [comment]
Would you mind please take a screenshot of it and link it here?

**Comment by cloudsurferuk** [comment]
![2017-03-17](https://cloud.githubusercontent.com/assets/11637840/24057043/e0c879ba-0b3d-11e7-80f6-988583936dfb.png)

**Comment by roykho** [comment]
Ok thanks for that and if I were to replicate this preview how do I do that? Is this specific to a plugin you're using or a theme? Because I have already tried preview via products page, blog page and regular page and none of the preview had errors for me.

**Comment by roykho** [comment]
Ok I put in a check for object type before using which should fix your issue. Please download from master branch and let me know.

**Comment by cloudsurferuk** [comment]
thanks, will do that tomorrow and let you know.

**Comment by cloudsurferuk** [comment]
Hi, I can confirm the error is gone. Thanks for sorting it.
