### ISSUE TITLE
[old settings] "Get more payment methods" link

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1894]
## Description
Add button at the bottom of the payment methods list to link to the Stripe dashboard to manage the payment methods.

![image (1)](https://user-images.githubusercontent.com/273592/133826643-146c79f5-2670-48f1-9374-9030e4d62f88.png)

**Comment by harriswong** [comment]
@frosso Do you know if this button open a new tab or stay on the same page? Secondly, dow e need to add those icons beside the button?

**Comment by frosso** [comment]
> Do you know if this button open a new tab or stay on the same page?

Let's have it open to a new window, if possible

> Secondly, dow e need to add those icons beside the button?

We won't implement the additional icons at this moment

**Comment by harriswong** [comment]
@frosso Is this also hiding behind `WC_Stripe_Feature_Flags::is_upe_preview_enabled()`?

**Comment by frosso** [comment]
@harriswong that's correct, the whole section is hiding behind that flag 👍
