### ISSUE TITLE
[old settings] Verify `reusable` attribute accuracy on UPE payment methods

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#1901]
## Description

Split from https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1773

Verify the `reusable` attribute is correct on all UPE methods.

**Comment by harriswong** [comment]
@evandotpro for this issue, is there something i can verify against for the `reusable` attribute? I see `is_reusable` in some of the `class-wc-stripe-*` classes, for example, [this one](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-upe-payment-method-bancontact.php#L22).

Is the purpose of this issue to just go check each file to make sure there is a `is_reusable` attribute? Or to set it all to `true` or set it all to `false` or something?

**Comment by EvanDotPro** [comment]
@harriswong We just need to make sure the reusable attribute is true for all methods that support recurring payments and false for those which do not. I'm unfortunately not at my comp right now, but the info is in the stripe docs and I believe also in the dashboard under payment method settings if I recall correctly.

**Comment by harriswong** [comment]
Found a link https://stripe.com/en-ca/payments/payment-methods-guide#payment-methods-fact-sheets. Going to be using this and also the settings under https://dashboard.stripe.com/settings/payments as references.

**Comment by harriswong** [comment]
There are 6 payment methods under the `class-wc-stripe-upe-payment-method-*.php` naming structure. I confirmed they match both the Stripe doc and the dashboard's settings:

bancontact: true
cards/credit card: true
eps: false
giropay: false
ideal: true (Supported through Stripe via SEPA Direct Debit)
sepa: true

**Comment by frosso** [comment]
Awesome, thanks for confirming @harriswong !
