### ISSUE TITLE
Notice: Undefined index: apple_pay in class-wc-stripe-apple-pay.php on line 290

### ISSUE THREAD

**Issue by andy-tschiersch** [woocommerce/woocommerce-gateway-stripe#191]
This notice occurs if WP_DEBUG is true and if you just updated from 3.0.7 to 3.1.2

Here is the code where it happens:

	public function body_class( $classes ) {
		if ( 'yes' === $this->_gateway_settings['apple_pay'] && isset( $gateways['stripe'] ) ) {
			$classes[] = 'wc-stripe-legacy';
		}
		return $classes;
	}

First, the isset() condition should go first, otherwise it makes no sense.
Second, $gateways is not defined inside this function.

I think it should looks like so:

    if ( isset( $this->_gateway_settings['apple_pay'] ) && 'yes' === $this->_gateway_settings['apple_pay'] ) {`

**Comment by roykho** [comment]
This was already removed.
