### ISSUE TITLE
Fatal error when WC Admin disabled

### ISSUE THREAD

**Issue by superbmario** [woocommerce/woocommerce-gateway-stripe#1914]
Fatal error when WC Admin is disabled:

https://wordpress.org/support/topic/fatal-error-in-version-5-5-0/

https://wordpress.org/support/topic/fatal-error-and-unable-to-access-admin-after-upgrade-to-5-5-0/

`Fatal error: Uncaught Automattic\WooCommerce\Admin\Notes\NotesUnavailableException: Notes are unavailable because the "admin-note" data store cannot be loaded. in /wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/Notes.php:452 Stack trace: #0 /wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/NoteTraits.php(108): Automattic\WooCommerce\Admin\Notes\Notes::load_data_store() #1 /wp-content/plugins/woocommerce-gateway-stripe/includes/notes/class-wc-stripe-upe-compatibility-note.php(68): WC_Stripe_UPE_Compatibility_Note::possibly_delete_note() #2 /wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-upe-compatibility-controller.php(40): WC_Stripe_UPE_Compatibility_Note::init() #3 /wp-includes/class-wp-hook.php(287): WC_Stripe_UPE_Compatibility_Controller->add_inbox_note( in /wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/Notes.php on line 452`

**Comment by simplysaru** [comment]
This Fatal error was coming from the Disable WooCommerce Bloat: by ospiotr – 2.5.3 where the user had disabled the WooCommerce Admin. 
![](https://snipboard.io/lRZbeI.jpg)

Disabling this plugin fixes these fatals. User confirmed this [here](https://wordpress.org/support/topic/fatal-error-in-version-5-5-0/#post-14894576)

**Comment by superbmario** [comment]
I'm not using the Disable WooCommerce Bloat plugin. I am just using the following filter, which results in the fatal error in the Stripe plugin:

`add_filter('woocommerce_admin_disabled', '__return_true');`
