### ISSUE TITLE
UPE Gateway title is always "Credit Card (Stripe)"

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#1919]
**Describe the bug**

The payment gateway title is "Credit Card (Stripe)", and in the description it shows the text: "Pay with your credit card via Stripe." even when other payment method than Credit Card is selected (like iDeal, Sofort, etc)

<img width="630" alt="Screen Shot 2021-09-21 at 13 57 07" src="https://user-images.githubusercontent.com/407542/134225447-f8c90dc0-1d61-4f55-a523-e53bcb6e5db1.png">

**To Reproduce**
1. In Settings / payments enable UPE with at least 2 payment methods
2. Add a product to the cart
3. Go to the checkout page (both shortcode and blocks)
4. Verify that the gateway title says "Credit Card (Stripe)"

**Expected behavior**
The WC Payments extension uses a the generic title: "Popular payment methods" and there is no description:
<img width="433" alt="Screen Shot 2021-09-21 at 15 24 50" src="https://user-images.githubusercontent.com/407542/134226681-39e3dcc9-8d76-4eef-8353-76489c4ef63e.png">

But, it has code in place to show the specific method title as the gateway title:
https://github.com/Automattic/woocommerce-payments/blob/569ef5b88156648325d004a676d603dc14697618/client/checkout/classic/upe.js#L351-L354

**Comment by bborman22** [comment]
Great catch! I actually just noticed that on the order details, it also always puts the gateway title there. Let me know if you think it would make sense to tackle both cases in this issue or if you wanted a separate issue to handle the order details area? Below is a screenshot from an order using Giropay. This can be reproduced by checking out with a non credit card payment method in UPE and then viewing the order details as the merchant.

![Order-Details-Method-Title](https://user-images.githubusercontent.com/68524302/134352651-d6890204-e5a9-411c-ac28-2b751639f0cc.png)

**Comment by diegocurbelo** [comment]
> Let me know if you think it would make sense to tackle both cases in this issue or if you wanted a separate issue to handle the order details area?

I think we should keep this issue to the minimum by just fixing the title, so we can merge smaller changes (one PR for the shortcode checkout and another for the blocks version)... Created an issue for order details bug: #1933
