### ISSUE TITLE
PHP version completely disables Stripe without warning

### ISSUE THREAD

**Issue by LaurenaRehbein** [woocommerce/woocommerce-gateway-stripe#192]
I just updated the Stripe extension and went to look for the Stripe settings in Settings > Checkout. They are gone. I see a message that says that the minimum PHP version is 5.6.0: 

![](http://cld.wthms.co/6mhL+)
Direct Link: http://cld.wthms.co/6mhL  

I've been in touch with Desktopserver tech support, and PHP 5.6.0 is not available until their next release, so I am not able to update. 

Now, I can't use Stripe at all - even without the Apple Pay enabled. 

I understand the importance of updating PHP as soon as possible, but this update renders the existing Stripe payment gateway entirely useless, without warning. 

Upgrading PHP is not always a quick task - it can require waiting on support tickets with your developer or host, and in some cases, migrating to a new host - and the disabled payment gateway can not be used in the meantime.

**Comment by roykho** [comment]
This is not a bug. For the mean time, they can edit this line to change to whatever their server currently supports https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/woocommerce-gateway-stripe.php#L36

But it is not recommended as some code may require 5.6+. They really should update ASAP.

**Comment by mikeyarce** [comment]
@roykho does Stripe (without Apple Pay) require 5.6?

**Comment by roykho** [comment]
@mikeyarce Yes the whole plugin. Even WC core requires 5.6+ as seen in our docs https://docs.woocommerce.com/document/server-requirements/

We will be pushing this minimum going forward more and more.
