### ISSUE TITLE
Hide the "Size of the button displayed for Express Checkouts" button

### ISSUE THREAD

**Issue by harriswong** [woocommerce/woocommerce-gateway-stripe#1923]
**Describe the bug**
The "Size of the button displayed for Express Checkouts" button was introduced for the new settings UI. In the old UI, we continue to let users choose whichever height they want to set. We want to hide the new express checkout button, but keep the old "payment request button":
![image](https://user-images.githubusercontent.com/572862/134248319-e7a31c4a-534a-4fc8-a009-9c18af7d1063.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. This applies to both situations where `_wcstripe_feature_upe` feature flag is enabled or disabled.
2. Go to `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe`
3. Scroll down to "Payment Request Button Height" 
4. See both "Payment Request Button Height" and "Size of the button displayed for Express Checkouts" 

**Expected behaviour**
Only shows "Payment Request Button Height"

**Screenshots**

**Comment by frosso** [comment]
FWIW, the "Size of the button displayed for Express Checkouts" applies to `_wcstripe_feature_upe`.
The "Payment Request Button Height" should no longer apply once we enable `_wcstripe_feature_upe`.

We will be making the next release with `_wcstripe_feature_upe` enabled, but we _could_ still add an `if` condition here to `unset` the `payment_request_button_height` setting when `_wcstripe_feature_upe` is disabled: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/baa79e5c199a3dd0145437cea849ecca645be1ab/includes/admin/stripe-settings.php#L230
