### ISSUE TITLE
Remove the payment method links inside Stripe UPE

### ISSUE THREAD

**Issue by harriswong** [woocommerce/woocommerce-gateway-stripe#1928]
**Describe the bug**
We no longer need these titles to be links. We can remove them.
![image](https://user-images.githubusercontent.com/572862/134372819-9bccc271-7d3e-45e4-8836-7c8fe9992b4c.png)

**To Reproduce**
1. Enable feature flag by making `WC_Stripe_Feature_Flags::is_upe_preview_enabled()` returns true
2. Go to `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe`
3. See payment method's title with link

**Expected behavior**
No link

**Comment by frosso** [comment]
Please ensure that they match the updated designs: Igkr3nOx0UoGDlHrsJ4eux-fi-1471%3A70898
![Screen Shot 2021-09-22 at 11 26 14 AM](https://user-images.githubusercontent.com/273592/134383721-7d160a6d-07fb-4f41-93db-6df12e90dacc.png)

**Comment by waclawjacek** [comment]
@frosso In the above PR, I have only removed the links and vertically centered the list items (screenshots in the PR demonstrate that). Should this PR contain anything else?
