### ISSUE TITLE
Apple Pay Icon Disappeared

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce-gateway-stripe#193]
I set up Apple Pay for my client. However, when "Enable Test Mode" was on, the Apple Pay Icon appeared, but when it was turned off, the Apple Pay disappeared.

I tested it on safari on both Mac OS X 10.12.3 and iOS 10.2

**Comment by roykho** [comment]
With live you have to have live iOS device ( with Wallet setup ) link to the computer you're using to shop.
