### ISSUE TITLE
Stripe UPE payment methods "Enabled" states are not reflected on the UI after saved

### ISSUE THREAD

**Issue by harriswong** [woocommerce/woocommerce-gateway-stripe#1934]
**Describe the bug**
The "Enabled" column is not toggled after saving. I checked the DB options table and I can confirm the payment methods are saved. So it's most likely just a UI thing.
ie. after saved, I can see the new payment methods added to the `upe_checkout_experience_accepted_payments` key:
```
    "upe_checkout_experience_accepted_payments": [
        "card",
        "giropay",
        "eps",
        "bancontact",
        "ideal",
        "sepa_debit"
    ],
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Make sure `WC_Stripe_Feature_Flags::is_upe_preview_enabled()` is enabled.
2. Go into Stripe UPE's settings `admin.php?page=wc-settings&tab=checkout&section=stripe`
3. Enable a few payment methods
4. Scroll down, click "Save changes"
5. The page refreshes and the "Enabled" column toggles don't reflect the changes.

**Expected behaviour**
The toggles should reflect the saved payment method statuses.

**Screenshots**
![Kapture 2021-09-22 at 12 00 33](https://user-images.githubusercontent.com/572862/134397143-112729ed-c612-4081-80e5-cd35d13cc7d7.gif)

**Comment by frosso** [comment]
Fixed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1949 - now the settings are correctly displayed and persisted regardless of the status of the "capture" setting.
