### ISSUE TITLE
Error messages translations missing

### ISSUE THREAD

**Issue by jyourstone** [woocommerce/woocommerce-gateway-stripe#194]
Regarding #179 

Some error messages still aren't translated after updating to the latest version. However, I found this closed issue: #39

I'm guessing that issue is related to the one I have now. One theory I have is that Stripe changed some of the error messages to display "YOUR card..." instead of "THE card..." which rendered those translations invalid in the PO file.

Or was it simply never fixed like samuelaguilera suggested in that thread?

**Comment by roykho** [comment]
There has since been an updated POT file. Did you check that first?

**Comment by jyourstone** [comment]
Yes I tried the new POT file but that made no difference. Even if it did work, all translations should be made through translate.wordpress.org

**Comment by roykho** [comment]
They definitely should be translatable. Please see them defined here https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L472

I am guessing the POT file did not picked them up during generation. I will check and if so, I will manually generate a new one. Yes in the future it will eventually be on GlotPress.

**Comment by jyourstone** [comment]
The error messages display "YOUR card..." instead of "THE card..." like in function get_localized_messages though. Doesn't that mean the error messages come directly from Stripe and not through function get_localized_messages() ?

**Comment by roykho** [comment]
Here is the list from Stripe's API docs. ![](http://cld.wthms.co/uZ7k+)

**Comment by jyourstone** [comment]
That's weird, if I do a test purchase with an expired card I get the error message "Your card has expired", not "The card has expired". You can test it yourself on our staging site: http://staging.yourstone-keramik.se/keramik-figurer/tomtefamiljen/

**Comment by jyourstone** [comment]
Any more info on this?

**Comment by roykho** [comment]
Sorry I am  not able to replicate your issue. I see this ![](http://cld.wthms.co/C8SF+)

**Comment by jyourstone** [comment]
That error message is correct since it's the "year" message. Use this test card number instead: 4000000000000069
That throws the expired_card error. 
You can also try the number 4000000000000127 which throws the error incorrect_cvc which also isn't translated.

**Comment by roykho** [comment]
I am unsure why they would have a different message from what they state in their docs. I will have to contact them.

**Comment by jyourstone** [comment]
Let me know if you want me to check all error messages too see which ones aren't translated.

**Comment by roykho** [comment]
@jyourstone - can you please test against the master branch and see if your issue is now fixed?

**Comment by jyourstone** [comment]
@roykho - Works great, thank you!

**Comment by Danielmcm86** [comment]
I have the exact same problem. What was the solution?

**Comment by jyourstone** [comment]
They fixed it in an update. What language are you using? Maybe Stripe isn't fully translated for that language on wp.org?

**Comment by Danielmcm86** [comment]
Thanks for the quick response Johan. The language is Spanish so it is fully translated, but all the translations and the files of Stripe are with "THE card" but on the website it appears with "YOUR card". I don't know where this "YOUR card" comes from, and by looking at the responses I thought you changed something in the master branch.

**Comment by jyourstone** [comment]
Yeah that's the problem I had as well, but it was fixed in version 3.0.6 I believe. I'm guessing you're running the latest version of Stripe?

I think those error messages come from Stripe.com and not the plugin itself, I'm not sure though.

**Comment by Danielmcm86** [comment]
I'm running version 3.2.3. I'm going to check if I can figure this out. Thank you Johan I'll see if it is coming from Stripe.com
