### ISSUE TITLE
Unable to set shipping = null for existing transactions after the shipping update post 4.5.4 ver 

### ISSUE THREAD

**Issue by ZeeBreaker** [woocommerce/woocommerce-gateway-stripe#1941]
Hi,
Our downstream system do not have support to parse shipping object sent from the payment intent from Stripe.

We have a bunch of transactions that have failed to parse due to stripe adding the 'shipping' address by default starting from 4.5.4 version. We need to set the **shipping =null** for these existing transactions for importing them to the downstream systems.
Please assist on how this can be achieved. 

We tried the below are are getting an error:
_You passed an empty string for 'shipping'. We assume empty values are an attempt to unset a parameter; however 'shipping' cannot be unset. You should remove 'shipping' from your request or supply a non-empty value._
    
function stripe_script() {​​​​​
    $match_date = '> 2021-09-21';
    $wc_args = array( 'limit' => 1, 'status' => array( 'completed', 'processing' ), 'date_created' => $match_date, 'customer' => get_current_user_id() );    
    $orders = wc_get_orders($wc_args);
    
    
        foreach( $orders as $order ) {​​​​​
            if ( ! method_exists( $order, 'get_shipping_postcode' ) ) {​​​​​
                echo "shipping postcode method does not exists.";
                continue;
            }​​​​​
            if ( empty( $order->get_shipping_postcode() ) ) {​​​​​
                echo "shipping postcode method is empty.";
                continue;
            }​​​​​
            $intent_id = $order->get_meta( '_stripe_intent_id' );
            if ( empty( $intent_id ) ) {​​​​​
                echo "stripe intent id is empty.";
                continue;
            }​​​​​
            echo "Intent ID " . $intent_id;
            $post_data = array();
            $post_data = array('shipping' => null);
            $response = WC_Stripe_API::request( $post_data, 'payment_intents/' . $intent_id );
            echo "<pre> Response with shipping array " . print_r($response,1) . "</pre>";
        }​​​​​
}​​​​​

Thanks!

**Comment by dougaitken** [comment]
Hey! As there hasn’t been any activity on this Issue recently, I’m going to close this Issue. 

It reads like you're looking for functionality that falls outside the current or future functionality of the plugin, and would require customization to fit your needs. 

For assistance with customization or development with your site, we recommend reaching out to someone on our [customizations page](https://woocommerce.com/experts/) as we're not able to offer that help here.

Thanks,
