### ISSUE TITLE
Saving SEPA payment method in Blocks with UPE enabled shows incorrect title

### ISSUE THREAD

**Issue by reykjalin** [woocommerce/woocommerce-gateway-stripe#1942]
**Describe the bug**

Saving a SEPA payment method in the Block based checkout creates an entry called "Saved token for Stripe" when it should say "SEPA IBAN ending in XXXX":

**To Reproduce**

1. Make sure UPE is enabled
1. Add a product to your cart
2. Go to the Blocks checkout
3. Pay with `AT321904300235473204`
4. Go to **My Account** > **Payment Methods** and note that the entry has the last for digits
5. Add a new product to your cart
6. Go the Blocks checkout and see that the saved SEPA payment method is just called "Saved token for Stripe"

**Expected behavior**

Saved SEPA payment method should say "SEPA IBAN ending in XXXX"

**Screenshots**

![image](https://user-images.githubusercontent.com/13835680/134428364-5f09e169-b772-4af6-bdc1-9a5cbae37bf5.png)

**Comment by superdav42** [comment]
Seems to be not limited to UPE.

**Comment by Mayisha** [comment]
Confirming that this is not reproducible anymore.

✅ Saved Sepa token during checkout via block checkout (UPE enabled) => saved token displayed correctly on the block checkout, shortcode checkout and 'My account' pages.
✅ Saved Sepa token during checkout via shortcode checkout (UPE enabled) => saved token displayed correctly on the block checkout, shortcode checkout and 'My account' pages.
✅ Saved Sepa token during checkout via 'My Account' page (UPE enabled) => saved token displayed correctly on the block checkout, shortcode checkout and 'My account' pages.
✅ Saved Sepa token during checkout via shortcode checkout (UPE disabled) => saved token displayed correctly on the shortcode checkout and 'My account' pages (Sepa is not available in block checkout in legacy experience).
✅ Saved Sepa token during checkout via 'My Account' page (UPE disabled) => saved token displayed correctly on the shortcode checkout and 'My account' pages (Sepa is not available in block checkout in legacy experience).

<img width="781" alt="Screenshot 2024-08-16 at 1 41 38 AM" src="https://github.com/user-attachments/assets/f9dd2d29-65da-4cd4-8727-3fe41ada4da7">
