### ISSUE TITLE
Asynchronous SEPA payments aren't updated with UPE enabled

### ISSUE THREAD

**Issue by reykjalin** [woocommerce/woocommerce-gateway-stripe#1943]
**Describe the bug**

When paying with an asynchronous SEPA account (`AT321904300235473204` can be used for testing) with UPE enabled the order status is never updated from `On-hold` even though the payment is successful.

**To Reproduce**

1. Make sure UPE is enabled
2. Add a product to your cart
3. Go to the checkout page
4. Select SEPA in the UPE element
5. Pay with `AT321904300235473204`
6. Wait 5 minutes
7. Check your Stripe dashboard; see that the payment has been completed successfully
8. Check **WooCommerce** > **Orders** and see that the order is still `On-hold`

**Expected behavior**

In step 8 above the order status should be `Processing` (or `Completed` for digital products).

**Comment by harriswong** [comment]
If this functionality is missing, we may need to do something similar to this: https://github.com/Automattic/woocommerce-payments/pull/1623
