### ISSUE TITLE
When Apple Pay is enabled, variable products add to cart issue

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gateway-stripe#195]
Reported here: https://wordpress.org/support/topic/safari-issue-on-macosx-when-adding-a-variable-product-to-cart/

The quantity of the variable product seems to double when adding to the cart if "Enable redirect to cart when items added" is enabled.

**Comment by roykho** [comment]
Some notes here: It is quite difficult to have Apple Pay button on the product detail page because upon click of the Apple Pay button, it doesn't allow us to run off to perform some logic before the Apple Pay payment sheet appears. With that being the issue, it forces us to do the logic when Apple Pay is present and when the page loads. Because it creates this cart object in session when page loads, it also simulates the adding of the cart for that item. Otherwise if you click Apple Pay, there would be nothing to pay for.

Recommended resolution for this is to remove Apple Pay completely from product detail page and just have it live on cart/checkout pages. However I will try to see if I can find another way. Perhaps try to create an alternative cart object/session that does not alter the main session.

**Comment by jaydisc** [comment]
I've tried hooking in to remove the Buy with Apple Pay button on the product detail page with:

```
remove_action( 'woocommerce_after_add_to_cart_quantity', 'display_apple_pay_button' );
remove_action( 'woocommerce_after_add_to_cart_button', 'display_apple_pay_button' );
```
Alas, this doesn't work. It seems that the hook is given a custom index on each page load. Is there a workaround we can use in functions.php to hide the button from the product detail page?

**Comment by roykho** [comment]
Try

```
remove_action( 'woocommerce_after_add_to_cart_quantity', array( WC_Stripe_Apple_Pay::instance(), 'display_apple_pay_button' ) );
remove_action( 'woocommerce_after_add_to_cart_button', array( WC_Stripe_Apple_Pay::instance(), 'display_apple_pay_button' ) );
```
