### ISSUE TITLE
UPE reloads unnecessarily on block checkout (not on shortcode checkout)

### ISSUE THREAD

**Issue by EvanDotPro** [woocommerce/woocommerce-gateway-stripe#1952]
**Describe the bug**

With using the block checkout with UPE and some other payment method enabled, if UPE is selected, a partial credit card is entered, then the customer selects the other payment method, then re-selects UPE, you'll see that the rendered UPE has been destroyed (losing any unsubmitted input) and has to reload.

**To Reproduce**

- Enable UPE.
- Also enable a non-UPE payment method such as check payment.
- Add item to cart, proceed to block checkout page.
- Select UPE, type some stuff into credit card field.
- Change selection to check payment.
- Change selection back to UPE.

UPE now has to load all over again and of course has lost whatever you had typed.

This does not happen in the shortcode checkout.

**Expected behavior**

UPE shouldn't be reloaded unless necessary.

**Comment by diegocurbelo** [comment]
No longer happens with the new implementation of Split PE in 8.0.0
