### ISSUE TITLE
Apple Pay: hide pay button content by default on other browsers

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce-gateway-stripe#196]
When viewing the page in Safari, the Apple Pay button show as expected, bu with Chrome the button is supposed to be hidden however the code for the div container andthe button are present, just have no inner HTML. The point is that some themes have default styles for buttons tag, so the button always appears:

![](http://cld.wthms.co/wzqE+)

**Comment by roykho** [comment]
Hey @tiagonoronha - Any remedy for this?

**Comment by tiagonoronha** [comment]
The button should be hidden on all browsers that don't support Apple Pay: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/assets/css/stripe-apple-pay.less#L1-L5

@corsonr can you share the link?

**Comment by corsonr** [comment]
Here is the link, I couldn't replicate with my latest Chrome version though:

https://streamworksaudio.com/swa-complete-cubase-pro-9/

zd-woothemes-548674

**Comment by tiagonoronha** [comment]
@corsonr 

I checked the link and they don't seem to have Apple Pay enabled. Please follow up with the customer and ask for more details. 

Double check that they are using the CSS included with the extension.
