### ISSUE TITLE
Enqueueing scripts/styles on single page in Apple Pay causes error on non-WooCoomerce single pages

### ISSUE THREAD

**Issue by lewell94** [woocommerce/woocommerce-gateway-stripe#198]
In the WC_Stripe_Apple_Pay class, the single product page scripts/styles are enqueued in the function single_scripts() on line 121. This function uses the global $post->ID to get the WC product using wc_get_product(), and when the single page is not for a WC product, this function returns false. However, the next part of this function assumes that what is returned from wc_get_product() is an object:

`$product = wc_get_product( $post->ID );`
`if ( ! in_array( ( version_compare( WC_VERSION, '3.0.0', '<' ) ? $product->product_type : $product->get_type() ), $this->supported_product_types() ) ) {
			return;
		}`

Therefore when you have a non-WC single page, and wc_get_product() returns false, an error is caused. 

`Notice: Trying to get property of non-object in /Applications/MAMP/htdocs/move-it-or-lose-it/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-apple-pay.php on line 134`

Checking that $product is an object first seems to solve this

`if ( ! is_object( $product ) || ! in_array( ( version_compare( WC_VERSION, '3.0.0', '<' ) ? $product->product_type : $product->get_type() ), $this->supported_product_types() ) ) {
			return;
		}`

**Comment by roykho** [comment]
What version are you using?

**Comment by lewell94** [comment]
3.1.2, I've just updated and see that this is fixed in 3.1.3, should've checked that first sorry! I will close the issue
