### ISSUE TITLE
[old settings] After enabling UPE but before saving, non-UPE settings are still visible

### ISSUE THREAD

**Issue by waclawjacek** [woocommerce/woocommerce-gateway-stripe#1988]
**Describe the bug**

Irrelevant settings are not hidden with JS depending on "UPE enabled" state.

This is probably not worth implementing at the moment but I wanted to bring this up just in case it is deemed worth adjusting.

**To Reproduce**

1. Go to WC > Settings > Payments > Stripe.
2. Enable **Try the new payment experience (Early access)** but _don't save settings yet_!
3. Scroll to the top.
   * The **Description** and **Inline Credit Card Form** settings are visible.
4. Save settings.
5. The aforementioned fields are no longer visible.

**Expected behavior**

JS is used to hide fields that will no longer be relevant **or** a relevant notice informing of updated settings fields becoming available after saving should be presented.

**Screenshots**

Before refresh:

![Markup on 2021-09-28 at 12:50:33](https://user-images.githubusercontent.com/1759681/135073659-f8e52275-9d21-4397-b792-fa3434ef095d.png)

**Environment (please complete the following information):**

WC Stripe 5.6-test

**Comment by frosso** [comment]
If we immediately hide the settings when the UPE flag is clicked, does it mean we should also show the UPE settings on toggle of the UPE flag?

**Comment by waclawjacek** [comment]
I think so.

I believe the issue might be more complicated than just adding the necessary JS code - we'd probably also have to change the list of settings registered in PHP to always include all of the fields, and then hide them conditionally with CSS.

An alternative could be to display a message like the one displayed next to the OAuth connect button when you toggle "Enable Test Mode" (something along the lines of "please save the settings first").

**Comment by dougaitken** [comment]
No longer relevant due to change in settings UI.
