### ISSUE TITLE
Modal height too small

### ISSUE THREAD

**Issue by waclawjacek** [woocommerce/woocommerce-gateway-stripe#1990]
**Describe the bug**

Height of the 3D Secure modal could be increased to accommodate for the modal's entire contents so no scrollbar is necessary.

I do not know if this also happens in live mode.

**Happens regardless of using UPE.**

**To Reproduce**

1. Go to checkout.
2. Use this card `4000002500003155` and any future expiration date and CVV.
3. See that the modal is a bit too short to fit all the contents.

**Screenshots**

![Markup on 2021-09-28 at 13:05:29](https://user-images.githubusercontent.com/1759681/135075739-36944c1d-5d41-46dc-a41d-c9b601162bdd.png)

**Environment (please complete the following information):**

- WC Stripe 5.6-test
- Twenty Twenty-One
- Mac OS X
- Firefox 92.0.1

**Comment by mdmoore** [comment]
We're unable to control height with the available appearance parameters offered by Stripe. It seems this will only happen in testing though, as a live 3DS transaction would forward the customer to the card issuers website.

@waclawjacek I'll go ahead and close for now, but feel free to reopen if you feel there's something we can do here :)

**Comment by waclawjacek** [comment]
Hmm... Is it an iframe that's loaded? How about resizing the modal once the iframe is loaded?

Or is the entire modal controlled via Stripe's SDK?

**Comment by mdmoore** [comment]
Yeah, the entire modal is controlled via the Stripe SDK. It might be something to bring up with Stripe though.
