### ISSUE TITLE
Stuck in Test Mode if WPML is enabled

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce-gateway-stripe#200]
When WPML is enabled the frontend form on the checkout page always loads the test mode form. Latest WC, WP, Stripe and WPML versions.

551340-zd-woothemes
558688-zd-woothemes

**Comment by roykho** [comment]
Not sure if we will support WPML. But do you have a copy of WPML? If it is a quick win, I can take a look otherwise this won't be fixed.

**Comment by corsonr** [comment]
I asked for it. Will send it yo you asap.

**Comment by roykho** [comment]
Is there a specific steps to reproduce this? I installed WPML and configured it but everything is working for me. I turned off test mode and the checkout form shows correctly the production style.

**Comment by corsonr** [comment]
No specific step, just enabling it seems to be enough.

**Comment by roykho** [comment]
Unfortunately I can't replicate this. Did you try this yourself?

**Comment by corsonr** [comment]
I'm trying to replicate with the WPML add-ons that the customers uses in addition to WPML. I'll come back to you once I have more details.

**Comment by madeincosmos** [comment]
WPML developers say customers using Stripe live mode should not be affected. If they still are, I believe this is something worth letting them know about: https://wpml.org/forums/topic/stripe-gateway-test-mode-keeps-showing-on-live/

**Comment by roykho** [comment]
In reading what they wrote, it seems they're aware of the issue and it is on their end to solve so closing this for now.
