### ISSUE TITLE
[Old settings] Incorrect message: Please save changes before selecting this button

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#2002]
**Describe the bug**
In a fresh Stripe installation, the message "Please save changes before selecting this button" appears under "Stripe Account Keys" in the old settings page, even when there's no button next to it.

**To Reproduce**
1. Navigate to **WooCommerce > Settings > Payments > Stripe**.
2. Copy your current publishable and secret keys.
3. Click "Clear all Stripe account keys".
3. The page shall be refreshed and the API keys must be emptied.
4. Paste the copied API keys again.
5. Notice this message appears: "Please save changes before selecting this button".

**Expected behavior**
That message should only appear if the button is present.

**Comment by Mayisha** [comment]
Closing this issue as the old setting mentioned in the description does not exist anymore. It was removed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2166
