### ISSUE TITLE
[settings] "Disconnect" functionality

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#2005]
## Description

The "Disconnect" button deletes the account keys stored in the Stripe settings.

![Screen Shot 2021-09-29 at 6 59 07 PM](https://user-images.githubusercontent.com/273592/135364383-7892b6f3-748b-4996-a00a-37670e1d071e.png)

(use `wp/data` implementation from https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2004 ).

Show a confirmation dialog upon clicking.
![Screen Shot 2021-09-30 at 8 32 48 AM](https://user-images.githubusercontent.com/273592/135465011-7051b431-7851-47b1-b195-bf069d77782a.png)

Please consult with UX on functionality. In particular:
- Whether this erases both test and live account keys/hooks
- Whether the page should be refreshed upon confirmation, to show the onboarding again (I'm assuming so, but better confirm)

**Comment by LevinMedia** [comment]
@frosso @Mayisha 

>Whether this erases both test and live account keys/hooks
Whether the page should be refreshed upon confirmation, to show the onboarding again (I'm assuming so, but better confirm)

Yes to both of these questions 

cc: @jarekmorawski
