### ISSUE TITLE
Apple Pay broken on checkout page with the Dynamic Pricing extension

### ISSUE THREAD

**Issue by douglsmith** [woocommerce/woocommerce-gateway-stripe#201]
When the Dynamic Pricing extension is enabled, clicking on the Apple Pay button on the checkout page does not work or show any visible action. The Apple Pay button works as expected on the single product page and on the cart page.

This happens in Safari on the desktop only.

I switched themes and disabled all extensions except WooCommerce, Stripe, and Dynamic Pricing and still had the problem.

Every time I click the Apple Pay icon I am seeing two javascript errors appear in Safari's console. A screen shot is attached.

<img width="866" alt="apple-pay-error" src="https://cloud.githubusercontent.com/assets/2446310/24248774/c2bc80fa-0f9e-11e7-868c-d1220f63d9e9.png">

**Comment by roykho** [comment]
That's correct. For our MVP, we wanted it to just work with WC core and with bare essentials. To make this work with many other extensions such as Product Addons and this will take more time. So this is in the future planning.

**Comment by douglsmith** [comment]
The MVP approach makes sense. However, by enabling Apple Pay by default, anyone using the Dynamic Pricing extension will have part of their checkout broken and may not even know the experience for their customers could be frustrating.

**Comment by roykho** [comment]
Its enabled by default because of an agreement we have which I will not get into. But WooCommerce extensions are very complicated and many different extensions need to co-exists and work together. It would be impossible for us to test that it works with every extensions we have. So this was not foreseen.

With that said, e-Commerce is a business and one that is quite sensitive. So I always urge people don't blindly just click on update. Always have a staging/test site you can test it on before you use it live.

**Comment by douglsmith** [comment]
Thanks, Roy. Should I also put in a ticket through woocommerce.com account to make sure Lucas is aware there is an issue with Dynamic Pricing?

**Comment by roykho** [comment]
Not necessary as I am already taking a look. I am guessing it just needs to add a couple of filters that Dynamic Pricing is needing.

**Comment by Deaner666** [comment]
I agree Apple Pay should be off by default, although it seems that isn't possible due to some behind-the-scenes deal. But in terms of this plugin breaking when other extensions are installed, it's a moot point. Sites are breaking whether or not Apple Pay is enabled.

**Comment by rabidin** [comment]
Douglamith mentioned this only happens on Safari on desktop only. However it also does not work on my iPhone 6.

**Comment by rabidin** [comment]
Sorry for name typo!

**Comment by roykho** [comment]
Hi @douglsmith - I have put in a fix for this. If you wouldn't mind testing to see if it now works for you? Thanks!

**Comment by samunderwood** [comment]
Are there still plans for product add-ons support?
