### ISSUE TITLE
SPIKE: get test mode oauth keys

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#2012]
## Description

The current design shows a desire to automatically fetch the test mode keys when going through the OAuth flow.
Or to automatically fetch the test mode keys when the merchant connected their Stripe account through the OAuth flow.

![2021-09-30 11 34 15](https://user-images.githubusercontent.com/273592/135495412-b3be2878-9494-43fe-86b9-a392c21353e5.gif)

## Questions
- Does the connect server allow to retrieve both test and live keys?
- Does the connect server allow to retrieve either live or test keys, by tweaking the query string parameters?

## Acceptance criteria
- Determine feasibility of design intent
- Discuss possible alternatives
- UX flow has been clarified and tickets have been created

**Comment by frosso** [comment]
At first glance it looks like the connect server allows to only get "live" keys depending on a static configuration parameter.
In order to get "test" keys, the configuration would need to be tweaked.

See https://github.com/Automattic/woocommerce-connect-server/blob/master/lib/stripe-client/index.js#L14 & https://github.com/Automattic/woocommerce-connect-server/blob/master/lib/stripe-client/index.js#L66-L75
The `client_id` is used to determine whether "live" or "test" keys are returned: https://stripe.com/docs/connect/oauth-reference#post-token

> When converting an authorization code to an access token, you must use an API key that matches the mode—live or test—of the authorization code (which depends on whether the `client_id` used was production or development).

**Comment by harriswong** [comment]
@superdav42 previously did an OAuth spike (https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1695)/ pc4etw-hW-p2 around Stripe. Following that spike and some testing locally. I think it is not possible to fetch both "live" and "test" keys together. Both would require their own onboarding flow; as in, both would need to go through separate onboarding with 2 different redirect URLs.

I pinged Stripe to ask if there is a way to fetch both live/test keys without going through onboarding twice.

**Comment by harriswong** [comment]
@jarekmorawski, I am still waiting for a response from Stripe, but I think "live mode" and "test mode" need their own redirection. If this is the case, "Enable test mode" won't be able e to fetch the keys underneath. Should "Enable test mode" open up a `<div>` which has a button to redirect user to onboarding? Similar to this one:
![image](https://user-images.githubusercontent.com/572862/136110631-c94cd6b0-74ab-48b7-921f-f283e1cbc95b.png)

Then, upon clicking it, the user will be redirected to the same onboarding flow but with "test mode" enabled:
![image](https://user-images.githubusercontent.com/572862/136111047-5e844cce-6f1c-41be-a99f-50e632ef7f2d.png)

**Comment by frosso** [comment]
FWIW, at this time we're showing a modal to enter the missing account keys when the merchant wants to enable test mode and the test keys are not present (we're showing the same modal when the merchant wants to enable "live" mode and the "live" keys are not present).

Confirmation modal skeleton implementation: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2024
Account keys form implementation: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1835

**Comment by harriswong** [comment]
Popping open a modal with instructions on how to get the test key may be less confusing to redirect them to the "Stripe connect"'s onboarding flow page again.

**Comment by cesarcosta99** [comment]
Closing it since all the acceptance criteria seem to have been accomplished 👍 Feel free to re-open it if there's still research/work to be done.
