### ISSUE TITLE
UPE - Unit Tests: Saving Payment Methods as Tokens

### ISSUE THREAD

**Issue by FangedParakeet** [woocommerce/woocommerce-gateway-stripe#2014]
**Is your feature request related to a problem? Please describe.**
A journey of 100% test coverage begins with a single assertion. This is one small step towards complete unit test coverage for the UPE gateway and its recently created dependencies.

**Describe the solution you'd like**
Specifically, these functions on `WC_Stripe_UPE_Payment_Method` and its inheritors are missing test coverage:
 - `add_token_to_user_from_intent`
 - `add_token_to_user_from_payment_method`
 - `create_payment_token_for_user`
 - `get_payment_method_details_from_intent`

**Describe alternatives you've considered**
Inserting fingers into ears and going "Lalalalalalala..."

**Additional context**
Related issues: #2015, #2016

**Comment by brettshumaker** [comment]
Updating this to say that since #2052 was merged in, the only method left out of this list to test is `create_payment_token_for_user`.
