### ISSUE TITLE
Fatal error in `WC_REST_Stripe_Settings_Controller::__construct()`

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#2019]
**Describe the bug**
Reported in the forums:

```
WC_REST_Stripe_Settings_Controller::__construct() must be an instance of WC_Stripe_Payment_Gateway, null given
```

https://wordpress.org/support/topic/version-5-6-critical-error-with-elementor/

**To Reproduce**
Seems to be possibly related to Elementor.
Error is happening when editing pages in Elementor.

**UPDATE:** this is an issue when using "WooFunnels Funnel Builder" together with Elementor, not an issue with Elementor itself.

**Expected behavior**
No fatal error.

**Comment by frosso** [comment]
Initial investigation suggested Elementor being problematic.
Installing Elementor alongside with Stripe isn't causing issues to Elementor pages.

Initial reports also included "WooCommerce Conditional Shipping and Payments".
But subsequent reports didn't.

As reports came in, they all had in common a few plugins developed by WooFunnels. More specifically:
```
WooFunnels Funnel Builder
WooFunnels Funnel Builder Pro
```

I am looking into this new lead, now.

**Comment by thuautp** [comment]
also reported in 4343732-zen

**Comment by wpniall** [comment]
Also reported in:

- 4341850-zen
- 4341609-zen
- 4341475-zen
