### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce-gateway-stripe#205]
Notice: Undefined index: testmode in /var/www/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-apple-pay.php on line 141

Notice: Undefined index: publishable_key in /var/www/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-apple-pay.php on line 141

Version 3.1.3

**Comment by roykho** [comment]
Already working on this.
