### ISSUE TITLE
Email Validation Issue (Have Fix, Attached as ZIP)

### ISSUE THREAD

**Issue by ApplicationError** [woocommerce/woocommerce-gateway-stripe#206]
I've been getting these error messages sometimes on the payments page when selecting Stripe as the option: 

> Please enter your card details to make a payment. Developers: Please make sure that you are including jQuery and there are no JavaScript errors on the page.

It appears as though it happens when there is a + in the email address. I discovered this during testing when I tried to use plus email addressing to use "unique" email addresses. 

Someone on our team also ran into this, but I'm not sure if she had a special character in her email address. 

![to-do - resolve strange error message for stripe option](https://cloud.githubusercontent.com/assets/26173192/24302197/6ecdc07e-1077-11e7-820f-ef65681770e9.png)

**Comment by ApplicationError** [comment]
Good day. I paid someone on Upwork to look into this and he was able to fix it. Here are the files he edited. Not sure if that helps. 

[stripe-checkout.js.zip](https://github.com/woocommerce/woocommerce-gateway-stripe/files/870214/stripe-checkout.js.zip)

**Comment by roykho** [comment]
Can you please see if the master branch works for you.

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/bd180dec57c40358291dccdcab60c315c13a8f1a
