### ISSUE TITLE
Add Oxxo & Boleto to UPE

### ISSUE THREAD

**Issue by frosso** [woocommerce/woocommerce-gateway-stripe#2066]
**Is your feature request related to a problem? Please describe.**
Add Oxxo & Boleto payment methods to the UPE.

Please ensure that:
- They work with the "new" and "old" settings (the new settings need to be configured with some icons & descriptions @ https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/client/payment-methods-map.js )
- They work when enabling/disabling the UPE (since they aren't part of the currently offered payment methods)
- Their capabilities work

**Additional context**
- https://stripe.com/docs/payments/boleto
- https://stripe.com/docs/payments/oxxo
- pc4etw-nQ-p2

**Comment by jarekmorawski** [comment]
✅ Added Oxxo and Boleto icons to the [Figma library](https://www.figma.com/file/Yy1WqI163cKRcnANjHDb5i/%5BWCPay%2FStripe%5D-Shared-components-library?node-id=3%3A5433).

**Comment by ricardo** [comment]
@leonardola it looks like you're working on this issue, so I've assigned you on it.

Let me know if I'm mistaken.
