### ISSUE TITLE
UPE - Fatal error when changing payment method for subscription

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#2078]
Internal ref: p1634091616216900-slack-C7U3Y3VMY

**Describe the bug**
When changing the payment method as a shopper for a subscription with UPE enabled, a fatal error occurs:

```
Call to undefined method WC_Stripe_UPE_Payment_Gateway::create_token_from_setup_intent()
```

**To Reproduce**
1. Ensure you have WooCommerce subscriptions installed.
2. Ensure you have UPE enabled.
3. As a merchant, create a subscription product.
4. As a shopper, purchase the subscription product.
5. As a shopper, navigate to **My account > Subscriptions**, and select the recently purchased subscription.
6. Click "Change payment" and proceed to add a new credit card as the payment method.
7. Notice a fatal error occurs.

**Comment by reykjalin** [comment]
Proposed fix is to re-introduce the `create_token_from_setup_intent()` function that was removed in https://github.com/woocommerce/woocommerce-gateway-stripe/commit/66ecaa434d556c0e47cf9e1e44a04006a9ebac8d.
