### ISSUE TITLE
Apple Pay: Make use of Stripe error messages, if one is returned

### ISSUE THREAD

**Issue by mattyza** [woocommerce/woocommerce-gateway-stripe#209]
> "message": "Before you can start using Apple Pay on the Web, you must first accept Apple's Terms of Service. You can do so through the Stripe Dashboard here: https://dashboard.stripe.com/account/apple_pay."

If an error message similar to the above is returned, we should display it in the relevant location (for example, below an applicable setting, or as an admin_notice).

The above example occurs when a merchant attempts to use Apple Pay, yet hasn't enabled Apple Pay on their Stripe dashboard.

cc @roykho

**Comment by fred-stripe** [comment]
I would recommend in general passing through any error messages sent by Stripe's "register domain" endpoint—there are several steps that we try to help users self-diagnose, for example:

1. Unable to verify SSL certificate.
2. Domain verification file returns a non-200 status (redirects are common here).

I think the validation you've built into this plugin prevents some other errors (invalid URL scheme, wrong file contents, etc) from happening, which is great. But between "ToS not accepted" and the two errors I mentioned those are the most common things users will run into. I don't recommend trying to match the error texts directly, as I'd hate for the error display to break if something changes on Stripe's end; always passing through the domain registration error message is a good strategy here.

Usability-wise I'd love it if any URLs returned in the error message were displayed as HTML anchors, but that's extremely minor. :)

**Comment by mattyza** [comment]
Thanks @fred-stripe. For the URLs in error messages, we can run the string through `make_clickable()` and then through `wp_kses()`, which will convert the URLs into anchor tags.
