### ISSUE TITLE
[settings] Fix all "todo" links

### ISSUE THREAD

**Issue by cesarcosta99** [woocommerce/woocommerce-gateway-stripe#2092]
## Description

Add a useful link to all links that are broken and need a valid URL. Here's a list (amount of links that need to be repaired in `()`):

1. UPE opt-in banner (1)
"Learn more"
![image](https://user-images.githubusercontent.com/10233985/138368270-324b2065-fb80-4dfe-bfa2-626d3f1760e6.png)
2. Onboarding flow (2)
http://localhost:8082/wp-admin/admin.php?page=wc_stripe-onboarding_wizard
![image](https://user-images.githubusercontent.com/10233985/140412025-789728fb-246c-4250-9be4-4d059d640c14.png)
![image](https://user-images.githubusercontent.com/10233985/140412145-8b7ccf44-8425-4fe0-bb68-e0cdc2f8a81f.png)

3. Express checkouts section (1)
![image](https://user-images.githubusercontent.com/10233985/138368823-ea77b819-c32a-490e-86ea-00851a948d8d.png)
4. General section (2)
![image](https://user-images.githubusercontent.com/10233985/138368989-25bb5f3a-1957-4fef-8844-d095382ebc98.png)
5. Payments & transactions section (1)
![image](https://user-images.githubusercontent.com/10233985/138369034-9c20a797-bb42-4ce8-9d2c-68fb2e8c1e69.png)
6. Disable modal (1)
"Stripe docs"
![image](https://user-images.githubusercontent.com/10233985/138369136-c8a2dd76-c087-4f3a-8e6a-8561e865320e.png)

## Questions

- Where those links should point to?

## Acceptance criteria

- All links point to a valid and useful URL
- [Have the docs.woocommerce.com links updated](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2092#issuecomment-961331598) (it can be addressed in another PR)

**Comment by reykjalin** [comment]
I wanted to pick up this issue, but wasn't sure who to consult regarding where the links should point to, so I'm just starting a discussion on that here.

1. UPE opt-in banner (1) — Probably some announcement that introduces the new checkout experience? I'm not sure.
2.  Onboarding flow (2) — I'm not sure what this refers to. What link is this? Where is it located?
3. Express checkouts section (1) — Should probably point to the WooCommerce.com Stripe PRB docs [here](https://docs.woocommerce.com/document/stripe/#payment-request-buttons)?
4. General section (2)
    - View Stripe docs — Should probably point to the [Stripe docs on WooCommerce.com](https://docs.woocommerce.com/document/stripe/).
    - Get Support — WooCommerce.com support link maybe? https://woocommerce.com/my-account/create-a-ticket/
5. Payments & transactions section (1) — I think the [Stripe docs on WooCommerce.com](https://docs.woocommerce.com/document/stripe/) again?
6. Disable modal (1) — Probably not a link, and instead just a handler in the component?


cc @cesarcosta99 @LevinMedia

**Comment by ricardo** [comment]
Following up on @reykjalin's questions, while waiting for confirmation from others:

> UPE opt-in banner (1) — Probably some announcement that introduces the new checkout experience? I'm not sure.

Either that, which I also don't have a link for, or this doc section: https://docs.woocommerce.com/document/stripe/#new-checkout-experience

> Onboarding flow (2) — I'm not sure what this refers to. What link is this? Where is it located?

I think it's this "Learn more" link, which right now is pointing to `TODO?`. It should link to [Stripe docs](https://docs.woocommerce.com/document/stripe/#additional-payment-methods) I suppose.

<img width="350" alt="Screen Shot 2021-11-03 at 19 44 17" src="https://user-images.githubusercontent.com/5509901/140220177-18cddb5d-6a0d-4ee7-9a14-46690a7a18dc.png">

> Disable modal (1) — Probably not a link, and instead just a handler in the component?

I think it's referring to the links in the [screenshot](https://user-images.githubusercontent.com/10233985/138369136-c8a2dd76-c087-4f3a-8e6a-8561e865320e.png). Right now:
- "Stripe docs" points to `TODO?`.
- "contact support" points to `https://woocommerce.com/contact-us/`.

> Get Support — WooCommerce.com support link maybe? https://woocommerce.com/my-account/create-a-ticket/

This page requires authentication although you don't need a WooCommerce account in order to download Stripe, is there any problem with that?

---

The other links @reykjalin suggested make sense to me too.

**Comment by ricardo** [comment]
FYI: p1636037526141700-slack-C07418EA0

All docs.woocommerce.com links now get redirected to woocommerce.com/document, so we might as well update the existing links.

**Comment by cesarcosta99** [comment]
I updated the description to make the places we need to update more clear.

---

>Onboarding flow (2) — I'm not sure what this refers to. What link is this? Where is it located?

When you disable UPE there will be a section leading you to enable UPE, when you click in the button to enable it, you will be redirected to the onboarding flow. There you'll find two broken links. (added screenshots now)

>5. Payments & transactions section (1) — I think the Stripe docs on WooCommerce.com again?

We can maybe include the `faq` section and make it https://woocommerce.com/document/stripe/#faq

>>Get Support — WooCommerce.com support link maybe? https://woocommerce.com/my-account/create-a-ticket/

>This page requires authentication although you don't need a WooCommerce account in order to download Stripe, is there any problem with that?

I think `https://woocommerce.com/contact-us/` makes more sense in this case because the customer may want to go somewhere else rather than creating a ticket right away, and that page gives them all the possibilities.

1. UPE opt-in banner (1) - In WCPay it points to `https://woocommerce.com/document/payments/additional-payment-methods/#introduction` so here it should probably point to `https://woocommerce.com/document/stripe/#additional-payment-methods`.

>All docs.woocommerce.com links now get redirected to woocommerce.com/document, so we might as well update the existing links.

Thanks for bringing that up, I added in the description.
