### ISSUE TITLE
Undeprecate wc_stripe_hide_payment_request_on_product_page

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-gateway-stripe#2099]
**Describe the bug**
The Name Your Price plugin needs this filter to exist in order to disable the payment request buttons conditionally on products where Name Your Price is enabled. The admin UI feature that has been introduced cannot account for this. 

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/68d94d8886507c2620dff5a3b1df3112836dbad6/changelog.txt#L31

**To Reproduce**
Enable payment request buttons on products
Enable Name Your Price plugin
Go to NYP-enabled simple product
if `DEBUG_MODE` is enabled, see the deprecation notice:
>Deprecated: wc_stripe_hide_payment_request_on_product_page is deprecated since version 5.5.0 with no alternative available. Please configure Payment Request Button locations through the Stripe plugin settings. in /home/cabox/workspace/wp-includes/functions.php on line 5596

**Expected behavior**
In an ideal world, there would be a way to disable/enable the payment request buttons dynamically depending on my price input's validity. If that is possible, please let me know. I haven't followed development here too closely and may have missed it.

Without that, it's important to disable the request buttons as they can lead to purchases that do not meet the minimum price requirements. Disabling request buttons universally on products seems too draconian. It's a great feature for products that support it, which is why plugins like mine need this filter.

**Comment by reykjalin** [comment]
Hi @helgatheviking! Thank you for bringing this to our attention!

First of all, I just want to make one thing clear; we do not plan to remove the filters any time soon, even though they are deprecated. You don't need to worry about the Name Your Price plugin losing this functionality to hide the PRBs.

The filters are intended as a way for merchants to choose general locations to display the PRBs, instead of selectively displaying them depending on other factors; that's why we deprecated them in favor of the admin UI settings.

> In an ideal world, there would be a way to disable/enable the payment request buttons dynamically depending on my price input's validity

This is an interesting request, and it sounds like we may want to keep the deprecation of the old filters, and instead add new ones to selectively hide the PRBs for specific products 🤔 

Would that be better than using the currently available filters? Or do you think the currently deprecated filters would be a better fit for the Name Your Price plugin's use case?

Do you know what parameters we'd need to pass to a filter like this for it to fit the Name Your Price use case?

**Comment by helgatheviking** [comment]
The current filters are a short term patch for me, but they work perfectly for what I need right now.

The front-end scripts do not support me dynamically setting a custom price that can be sent to Google/apple so for now it's better for me to remove the buttons entirely via filter. 

I think there's always going to be a need for conditionally disabling the buttons based on the specific _$product_ object. In my case I am checking some product meta... If it exists and this is a product where the customer is meant to enter their own price.. then I need to disable the PRB. That's where the admin UI approach falls short. A simple product might support the PRB, but a simple product with a custom field like mine (or product add-ons) may not.

For full compat, you'll need to introduce some extensibility to the _frontend_ JS. 1. Hide/show PRB similar to how variable products do when the variation is not selected. 2.. Allow me to dynamically set the price that the PRB sends to the gateway. In Name Your Price, the customer enters a price into a field... So the price cannot be pulled from the database.

**Comment by drwpcom** [comment]
Noting here that this filter is also used by Gift Cards for WooCommerce as discussed in p1643984760975669/1643979837.488689-slack-C7U3Y3VMY.

**Comment by helgatheviking** [comment]
I would still like to see this notice removed. It's just going to generate support tickets. There are established use cases for hiding/showing the buttons on a per-_product_ basis and the settings can't handle that level of conditional logic.

**Comment by jimjasson** [comment]
I agree with @helgatheviking on this one. 

Stripe quick pay buttons do not currently parse nor validate any extra fields that may exist in the single product page. 

In Gift Cards, these fields are the recipient e-mail, the sender, the gift card message and delivery date. Gift Cards adds these fields on Simple and Variable Products -- these are product types for which the quick pay buttons show up by default. Therefore, Stripe buttons show up for Gift Card Simple/Variable Products, but if you use these buttons to purchase a gift card, then a gift card with missing attributes is created. 

As Kathy mentioned, this issue affects Name Your Price as well and will likely affect other plugins that add extra fields in the single product page (for example, Product Add-Ons). 

I think that [these filters](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/changelog.txt#L79) are essential for plugins that integrate with Stripe and hiding these buttons is currently the only robust way to prevent customers from bypassing the single product page validation. 

I propose to remove the deprecation notice for these filters (as it creates extra support load) until Stripe buttons properly parse and validate all single product page fields. What do you think?

**Comment by helgatheviking** [comment]
>is currently the only robust way to prevent customers from bypassing the single product page validation.

Phew yes. Can't believe I forgot to say the PRB on incompatible products all customers to _bypass_ validation!! In Name Your Price a customer can "buy" a product for $0 even though the minimum price is meant to be $100. Or in Mix and Match Products a customer can buy a product and their chosen configuration isn't passed along.

**Comment by reykjalin** [comment]
I think based on the discussions we're seeing here we'll want to do 3 things:

1. Undeprecate the filters.
2. Introduce three new filters:
    - `wc_stripe_show_payment_request_for_product`: Will receive a Product ID as a parameter; returning `false` will hide the PRB on that product's page. 
    - `wc_stripe_show_payment_request_on_cart_for_cart`: Will receive an array of Product IDs; the products currently in the cart. Returning `false` will hide the PRB on the cart page for a given cart.
    - `wc_stripe_show_payment_request_on_checkout_for_cart`: Will receive an array of Product IDs; the products currently in the cart. Returning `false` will hide the PRB on the checkout page for a given cart.
    - The point of these filters is to provide a more targeted set of filters to give plugins and merchants more control over when to show the PRBs.
    - Sidenote: it may be better to pass the actual product objects to the filters so plugins/merchants won't have to make database requests for the actual product information to make a decision on whether to hide the PRBs or not.
3. Deprecate the original filters again.

**Comment by helgatheviking** [comment]
So `wc_stripe_show_payment_request_for_product` would be exactly the inverse of `wc_stripe_hide_payment_request_on_product_page`?

>Sidenote: it may be better to pass the actual product objects

At least on the single product display, yes... please pass the product object.

**Comment by reykjalin** [comment]
> So wc_stripe_show_payment_request_for_product would be exactly the inverse of wc_stripe_hide_payment_request_on_product_page?

Almost; we're planning on passing a product object as a parameter to the filter instead of the `global $post` object.

**Comment by helgatheviking** [comment]
@reykjalin Is there a timeline for adding the `wc_stripe_show_payment_request_for_product` filter?
