### ISSUE TITLE
Use Default WP Site language and NOT en-US

### ISSUE THREAD

**Issue by danielbarenkamp** [woocommerce/woocommerce-gateway-stripe#2114]
Hello,

our german customers receive English SEPA mails, because the get_user_locale returns empty strings for NEW customers.

Please change the default language here: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/1ecaea47625b2ff4c49190dcf7d9c3c7e8553a84/includes/class-wc-stripe-customer.php#L652

to the original wp site language. You can use "get_locale" functionality and then validate if that exists.

Code:
```
$default_locale = 'en-US';
$site_local = get_locale();
if( isset( $stripe_locales[ $site_local ] ) ) {
$default_locale = $stripe_locales[ $site_local ];
}
$preferred = isset( $stripe_locales[ $locale ] ) ? $stripe_locales[ $locale ] : $default_locale;
```

**Comment by mdmoore** [comment]
Hey @danielbarenkamp! Thanks for the report. I haven't been able to reproduce this with a new customer. `get_user_locale()` returns `false` for a new customer and falls back to `get_locale()` within `get_customer_locale()` [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/1ecaea47625b2ff4c49190dcf7d9c3c7e8553a84/includes/class-wc-stripe-customer.php#L664). [get_user_locale()](https://developer.wordpress.org/reference/functions/get_user_locale/) has a built-in fallback to `get_locale()` as well, in case an empty string makes it's way in.

I'm wondering if another plugin might be getting in the way here.

**Comment by danielbarenkamp** [comment]
Let me check that on client's site! Thanks for coming back to me

**Comment by sun** [comment]
We are facing the same symptom.  I believe you have formal German (de_DE_formal) configured as site locale.

PR https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2357 fixes this by including formal German in the locale mapping.
