### ISSUE TITLE
Spike: Support other payment methods in the blocks checkout

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#2117]
Currently, we only support UPE payment methods and the non-UPE credit card on the blocks checkout.

Questions:
- Do we want to support other non-UPE payment methods that are included in UPE? E.g SEPA? If the non-UPE checkout gets deprecated in the future, it might not be worth it.
- Can we add support for payment methods that are not included in UPE? E.g Alipay?

**Comment by leonardola** [comment]
Boleto and Oxxo will need support too if we decide to add support
