### ISSUE TITLE
Don't enable Apple Pay by default

### ISSUE THREAD

**Issue by pmgarman** [woocommerce/woocommerce-gateway-stripe#212]
![](http://c.pmgr.mn/tQGy+)

This should be reason enough, by enabling Apple Pay users are inherently accepting Apple Pay's TOS. They never agreed to the TOS of Apple Pay, most users just installed an update. If users are required to accept TOS to use a service, then they should *accept* those TOS by enabling it themselves.

**Comment by roykho** [comment]
^^ @mattyza

**Comment by mattyza** [comment]
@pmgarman - thanks for your feedback.

Enabling Apple Pay by default is a request from Apple directly. There's also a really compelling reason. :)

Apple Pay is only available a) to merchants who have enabled it on their Stripe account, and b) to customers who are eligible for Apple Pay (using a specific browser, with an Apple ID in a specific region, and a card saved on file).

Thus, Apple Pay would show only for those who it is able to show for, not for everyone.

The language below says "by using Apple Pay". This doesn't imply a connection between this checkbox and the terms of service for Stripe and Apple Pay. The acceptance of said terms of service is done on the Stripe dashboard.

Perhaps there's a way we can clarify this through the language on the field description?

**Comment by corsonr** [comment]
Just to add to this, I saw tat request in our support tickets a couple times too.

**Comment by pmgarman** [comment]
@mattyza maybe, being apple, a really slick on boarding UI could be created that really awesome experience for the store owner? Every time you turn on a new apple device that on boarding experience has always been a part of their thing. that's a big change but could be a cool one that for a non technical store owner who doesn't know what Apple Pay is could also be shown "what is Apple Pay?"

I've also seen a fair amount of complaints about Apple Pay about how it having issues or breaking on some stores in that auto activation - which is probably why @corsonr heard some of that feedback as well :D

Also circling back to that text, maybe it could be moved where it isn't *part of the description of the checkbox* if it is not directly tied to that checkbox. Throw it in the global description of the gateway that appears on the gateway settings page or at the very bottom of the settings page. "By using X and/or Z you accept their TOS" sort of thing. I think anyone could easily assume that checkbox is tied to both enabling Apple Pay *and* their TOS based on that placement.

**Comment by LinnAlexandra** [comment]
Thirding this request – the checkout completely broke on a client's live site who had not enabled Apple Pay in their Stripe account, effectively taking down their store until I downgraded the Stripe plugin to a pre-Apple Pay version.

Simply unticking the "Enable Apple Pay" box didn't help: a banner error persisted saying "Apple Pay domain verification failed" and every time the checkout loaded the logs read "Error: Unable to verify domain - Bad Request". These errors continued even after I updated to 3.1.4 from this repo.

The update details said nothing about enabling Apple Pay via Stripe, so when the best practice is to "always update your plugins!" this kind of change is a real problem.

**Comment by mattyza** [comment]
Thanks for your feedback on this, everyone.

We've made a few adjustments to how the domain verification works, to do our best to minimise the number of failure cases here, if not eliminate them all completely.

As this feature provides the best possible customer experience for any eligible Apple Pay user, we'd like to keep this enabled by default for now, until such time as we have more data with which to assess this.

While I'll close out this issue for now, please do comment back here if you have further feedback, or have seen a new scenario which you feel we may not yet be catering for, which causes this to fail.

Thanks everyone. :)
