### ISSUE TITLE
Add API endpoint for Stripe account details 

### ISSUE THREAD

**Issue by brianyu28** [woocommerce/woocommerce-gateway-stripe#2121]
**Description**

For in-person payments, the mobile application will need to call an endpoint to fetch details of the Stripe account attached to the store. This is used to determine if the account is fully set up and eligible for in-person payments.

Sample response:

```
{
  "data": {
    "has_pending_requirements": false,
    "has_overdue_requirements": false,
    "current_deadline": null,
    "status": "complete",
    "statement_descriptor": "DO.WPMT.CO",
    "store_currencies": {
      "default": "usd",
      "supported": ["usd"]
    },
    "country": "US"
  }
}
```

**Additional context**

pdfdoF-er-p2

**Comment by cesarcosta99** [comment]
@brianyu28, there's a REST controller that may attend most of what you need. You can find out more in [this file](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/admin/class-wc-rest-stripe-account-controller.php). There's even a [data structure](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/client/data/account/index.js) built for it. Hope it helps! 😃
