### ISSUE TITLE
Add API endpoint to capture payment

### ISSUE THREAD

**Issue by brianyu28** [woocommerce/woocommerce-gateway-stripe#2125]
**Description**

For in-person payments, the mobile application will need to call an endpoint to capture the funds of a Payment Intent created by the mobile app.

Sample request body:
```
{
  "payment_intent_id": "pi_abcd"
}
```

Sample responses are below, based on what WooCommerce Payments currently returns for these endpoints. The error codes currently all begin with the `wcpay_` prefix. I imagine we will want to change that to a `wc_stripe_` prefix, or change the prefixes to avoid mention of a specific gateway.

Sample successful response:

```
{
  "data": {
    "status": "succeeded",
    "id": "dummy_payment_id"
  }
}
```

Error if invalid order id provided:

```
{
  "code": "wcpay_missing_order",
  "message": "Order not found",
  "data": {
    "status": 404
  }
}
```

Error if payment already captured:

```
{
  "code": "wcpay_payment_uncapturable",
  "message": "The payment cannot be captured",
  "data": {
    "status": 409
  }
}
```

Error if capturing payment failed:

```
{
  "code": "wcpay_capture_error",
  "message": "Payment capture failed to complete with the following message: <ERROR_MESSAGE>",
  "data": {
    "status": 502
  }
}
```

Unexpected error:

```
{
  "code": "wcpay_server_error",
  "message": "Unexpected server error",
  "data": {
    "status": 500
  }
}
```

**Additional context**

pdfdoF-er-p2

**Comment by nxmndr** [comment]
Could you please make it work with Transactions instead of Orders ? This would make it compatible with plugins that have multiple payments per order, like payment plans. Example : https://wordpress.org/plugins/deposits-partial-payments-for-woocommerce

Edit : opened #2556
