### ISSUE TITLE
Change Payment Method dropdown populating Stripe title incorrectly (Subscriptions)

### ISSUE THREAD

**Issue by NickGreen** [woocommerce/woocommerce-gateway-stripe#213]
#### Affected ticket

https://woothemes.zendesk.com/agent/tickets/552559

#### To Reproduce

- Enable WooCommerce Subscriptions plugin
- Enable both PayPal and Stripe
- Edit subscription that was made with PayPal
- Edit payment method

The title for Stripe in the dropdown is populating with 'PayPal' : https://cloudup.com/cgbub0wTOfT

The html is showing that the value of stripe is being populated correctly : https://cloudup.com/cjPlcibxrg5

We've reproduced locally and on several online test sites.

#### Possible Reasons

We've tracked the error down to `woocommerce-gateway-stripe/includes/class-wc-stripe-apple-pay.php` with the `filter_gateway_title()` function.

If we disable that filter, the title is populated correctly. We believe this is because it is returning the title from the post ID, which is PayPal in this case.

They probably wanted to add Apple Pay, but weren't aware of the use case of using the get_title() function to display a list of payment methods to allow a method change.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Fixed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/919814fcf0c7e33dbf41130a4d6ce5cc177227aa
