### ISSUE TITLE
Apple Pay Buttons do Not Show on Safari

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce-gateway-stripe#214]
#### What I expected

For some reason the Apple Pay buttons do not show on Safari, for some sites, when they should. I can't really explain why, but I saw multiple tickets stating that Apple Pay isn't displayed on some Macs with Safari. I was able to replicate: @mdmoore was able to see Apple Pay while I wasn't (the weird part is that I usually see Apple Pay, and when I test locally my Apple Pay does show).

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@corsonr - use the master branch and turn on debug log and re-test. If it still doesn't show, check the log as it will tell you exactly why it isn't showing.

**Comment by corsonr** [comment]
Ok, I will try on the customer's site as the buttons do show fine on my local install.

**Comment by roykho** [comment]
Closing for now as this is probably not a plugin issue. Please re-open if it is.

**Comment by corsonr** [comment]
Related:

554004-zd-woothemes

**Comment by corsonr** [comment]
hey @tiagonoronha can I please have your feedback on this one please? Many thanks

**Comment by tiagonoronha** [comment]
@corsonr the JS controls when the button should be displayed.

Have you tried what @roykho suggested? The logs should tell you why the button is not being displayed.

Your commit above would display the button to all Safari users even if they don't have Apple Pay configured and/or not supported on their country.
