### ISSUE TITLE
[settings] Allow customization of the payment method title

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#2145]
## Description

Context: p1636014637180500-slack-C7U3Y3VMY

On the old settings (`_wcstripe_feature_upe_settings` option set to `no`), there used to be a way to change the payment method title and description for the credit card payment method. Also, when UPE was enabled, there used to be a customizable title "Popular payment methods".

This behavior is currently missing from the new settings. It's only available for other non-UPE payment methods ATM.

Ideas proposed for fixing it in the new settings: p1636539899240000/1636014637.180500-slack-C7U3Y3VMY - We should go with idea number 2.

~~Question: Should we go with Idea 1 or Idea 2?~~

Note: Apparently there's a bug (#2039) on the old settings, where the title gets cleared after switching off UPE. This is probably caused by not preserving the credit card title when UPE is enabled and then saving the settings again. We can fix this by always preserving the credit card title if editing the UPE title only. Please check the old settings to see how it's done.

## Acceptance criteria

- Design is implemented: p1636539899240000/1636014637.180500-slack-C7U3Y3VMY

**Comment by cesarcosta99** [comment]
Let us please follow-up #2120 closely while working this out, since it's under the same context.
