### ISSUE TITLE
New Inbox message: Stripe feedback

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce-gateway-stripe#2147]
Title: Share your feedback on Stripe
Content: Share your feedback in this 2 minute survey about accepting payments on your store.
Segmentation: Stripe installed / PayPal Standard not installed
Cadence: Once
CTA leads to: http://automattic.survey.fm/stripe-feedback
CTA label: Share feedback

**Comment by dougaitken** [comment]
hey @elizaan36 

_To ensure the WooCommerce team are having the most impactful work, we review older open Issues on this GitHub repository to find out what is still relevant._ 

**As there hasn’t been any activity on this Issue recently, I’m going to close this Issue.** 

If this is still needed, please ping me on Slack internally.
