### ISSUE TITLE
Update documentation links

### ISSUE THREAD

**Issue by cesarcosta99** [woocommerce/woocommerce-gateway-stripe#2149]
## Description

`docs.woocommerce.com` links now get redirected to `woocommerce.com/document`, so we should update all the references.

## Acceptance criteria

- Any link that points to `docs.woocommerce.com` should be replaced with `woocommerce.com/document`.

**Comment by lovo-h** [comment]
@cesarcosta99, after updating the links, I ended up with some links that were not properly directed. Please see below:
* Should `https://woocommerce.com/document/stripe/#styling` be the following, instead: `https://woocommerce.com/document/stripe-styling-fields`
* Should `https://woocommerce.com/document/privacy-payments/#woocommerce-gateway-stripe`, be the following, instead: `https://woocommerce.com/document/privacy-payments/#section-3`
  * For this one, I was not entirely sure if the docs should be updated or not. Thoughts?

**Comment by cesarcosta99** [comment]
Both links seem to be unused but let's maybe change them for their own sake.

`https://woocommerce.com/document/stripe/#styling` could be `https://woocommerce.com/document/stripe/#new-checkout-experience` because the messaging is about styling changes in the checkout.

The second sounds good to me.

>For this one, I was not entirely sure if the docs should be updated or not. Thoughts?

Perhaps we can address that in #1763.
