### ISSUE TITLE
Remove UPE settings redesign flag

### ISSUE THREAD

**Issue by cesarcosta99** [woocommerce/woocommerce-gateway-stripe#2150]
## Description

We're releasing the settings redesign on v5.8.0, and we have only defaulted the feature flag to `yes` for now. Later on we should remove the flag completely.

This change is aimed to be released on v5.9.0 or higher.

## Acceptance criteria

- Have the `_wcstripe_feature_upe_settings` flag removed, including all conditions that make use of it.

**Comment by asumaran** [comment]
@cesarcosta99 do we still going to use the `_wcstripe_feature_upe` flag? For example here it's being used to determine UPE is enabled.

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/71cbd0a4a8585084e3b707ebfae56b652ec6075c/includes/class-wc-stripe-feature-flags.php#L15-L17

**Comment by asumaran** [comment]
@cesarcosta99 if we remove all traces of `_wcstripe_feature_upe_settings` flag, that means the new Settings UI will be active by default, right? Also, does that mean that should we also remove all traces of the old settings view?

**Comment by cesarcosta99** [comment]
@asumaran thanks for bringing those concerns up.

>do we still going to use the _wcstripe_feature_upe flag?

No, but that removal is being addressed in #1948.

>if we remove all traces of _wcstripe_feature_upe_settings flag, that means the new Settings UI will be active by default, right? Also, does that mean that should we also remove all traces of the old settings view?

Yes for both questions. However, I'd say that removing all traces of the old settings doesn't seem a trivial change. For that reason, I'd suggest the we address that in a different issue/PR so we can perform a complete test on it.

**Comment by asumaran** [comment]
@cesarcosta99 I went ahead and already [started](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2166/files) removing everything related to the old settings UI. Hope that's not a problem. Removing the `_wcstripe_feature_upe_settings` was quite simple and I think it's better to have it reviewed as a whole in my opinion.

**Comment by ricardo** [comment]
@asumaran we might want to wait a bit more and check for issues in #woo-devs to see if we don't need to force the old settings again for some merchants depending on issues with the new settings.

If we remove the option completely, it won't be possible to switch back to the old settings.

**Comment by asumaran** [comment]
@ricardo I agree, but this is going to be released on 5.9.0 which should happen in a at least a couple of weeks. If something happens by that time we could revert the PR.
