### ISSUE TITLE
Refactor disconnect confirmation modal

### ISSUE THREAD

**Issue by cesarcosta99** [woocommerce/woocommerce-gateway-stripe#2152]
## Description

When we try to disconnect Stripe it works well, but we could tweak a couple of things to make a smoother experience:

1. We don't see a loading state when we make the API call.
2. We're just led to the same UI, whereas we would need to connect before using the plugin again.

![image](https://user-images.githubusercontent.com/10233985/141531706-500e25a3-afc6-4d03-8534-4e1c721c7f49.png)

## Acceptance criteria

- After the API call is fulfilled, the page is reloaded.
- We can see a loading state while disconnecting is being performed
- The buttons of the modal are disabled while disconnecting is being performed
- Both loading state and disabled buttons continue "forever" even after the API call is fulfilled, because the page will reload, giving the impression something is still happening.

![image](https://user-images.githubusercontent.com/10233985/141532868-fc4ce5a9-c23f-4cdf-a655-710f77d27143.png)

**Comment by asumaran** [comment]
@cesarcosta99 is there a design/figma file for this?
