### ISSUE TITLE
Refactor account keys modal behavior

### ISSUE THREAD

**Issue by cesarcosta99** [woocommerce/woocommerce-gateway-stripe#2153]
## Description

There are many aspects of the account keys modal behavior that we can polish. Some things were tweaked within the `release/5.8.0` branch so we want to start from there.

The account keys modal is a component that is present both in the onboarding and in the settings tab. This way we need to make sure it works well on both.

## Acceptance criteria

**In the plugin setup:**

<img src="https://user-images.githubusercontent.com/10233985/141596171-61f7c7ff-7794-4283-97e4-351c861ad61f.png" width="400" />

- After providing live keys, modal stays in busy state and page is reloaded. (current behavior)
- After providing test keys, modal stays in busy state, page is reloaded and test mode is enabled. (current behavior)
- If API call errors for whatever reason, modal remains open, leaves busy state and allows the user to provide correct info. Page does not reload at all.

**In the settings, either clicking in the "Edit account keys" button or in the "Edit account keys" option in the "Account details" dropdown:**

<img src="https://user-images.githubusercontent.com/10233985/141596690-0f6684c4-902b-47bc-8439-d416920d8f12.png" width="600" />

- "Enable test mode" checkbox only triggers the modal if the option is disabled **and** there are no test keys.
- After providing live keys, the modal stays in busy state while making the API call. After API call is fulfilled, modal closes and account data is fetched to update the account info.
- After providing test keys, the modal stays in busy state while making the API call. After API call is fulfilled, modal closes and account data is fetched to update the account info.
- Test mode is never automatically enabled/disabled while in the settings.
  - If the user is in the settings, it means the user has provided either live keys, test keys, or both. So we leave that decision entirely in their hands.
  - That means the test mode value is automatically updated in the plugin setup only.
  - That way we avoid page reloads, which can be especially confusing for the user, as we might lose the local test mode state.
- If the user cleans both live and test keys (same as disconnecting), the page reloads. (current behavior)
- If API call errors for whatever reason, modal remains open, leaves busy state and allows the user to provide correct info. Page does not reload at all.

**Comment by cesarcosta99** [comment]
@diegocurbelo, I wonder if you have any thoughts on the behaviors I specified since you were working on that. I may have missed something.

**Comment by diegocurbelo** [comment]
@cesarcosta99 After the changes we still have some inconsistencies after updating keys (or removing them) but not reloading, that would be solved by [Invalid keys notice #1807](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1807); I'll add that in the same PR so we can test the entire flow.
