### ISSUE TITLE
Idempotency issues with new checkout experience. 

### ISSUE THREAD

**Issue by slash1andy** [woocommerce/woocommerce-gateway-stripe#2154]
Twice customers have been charged twice for the same order, user indicated it's since they've enabled the Enhance Payment experience.  User reached out to Stripe who suggested activating the "idempotency" feature.

Grab order notes and logs from the Slack link, as this is a public repo.

**Comment by dougaitken** [comment]
There is a possibly related issue in #2339 about fixing this but as there has been no further updates since this was opened, I'm closing this for now.
