### ISSUE TITLE
UPE pay for order page displays "Use a new payment method" radio even if there are no other payment methods saved

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#2163]
**Describe the bug**
UPE pay for order page displays "Use a new payment method" radio button even if there are no other payment methods saved.

If the radio is not selected, this causes an error when trying to pay:

> Payment processing failed. Please retry.

**To Reproduce**
1. Make sure you have no payment methods saved to your account.
2. Add any product to cart.
3. Go to checkout.
4. Add this credit card `4000000000000002`.
5. Checkout.
6. An error message should be displayed.
7. Go to My account > Order > Last order > Pay.
8. Notice the radio button is present and is not automatically selected.

**Expected behavior**
It shouldn't display the radio button when there are no other payment methods saved. And it should have one of the radio buttons automatically selected, the same way as in the checkout page.

**Screenshots**
<img width="802" alt="Stripe pay for order page UPE - use a new payment method" src="https://user-images.githubusercontent.com/5509901/142291665-1683de4b-96ba-4549-9a2e-ea9974909f90.png">

**Additional context**
p1637159154256000-slack-C01BZUL57SQ

**Comment by raifd** [comment]
The same issue was mentioned here: 4611643-zd-woothemes

**Comment by leonardola** [comment]
@raifd I just asked for another review on the PR so this should be fixed ASAP. It will probably be shipped on the next release.
