### ISSUE TITLE
Apple Pay is not working on iOS

### ISSUE THREAD

**Issue by williamlwu** [woocommerce/woocommerce-gateway-stripe#217]
Apple Pay is not working in Shop Single Page on iOS 10.2.1

#### What I expected

The Apple Pay payment prompt should remain extended before payment is completed.

#### What happened instead

The prompt showed "Processing" and disappear within a mere second. The WooCommerce is setup with free shipping and at 9% tax rate.

#### Steps to reproduce the issue

Click on any [product page](https://activalley.com/shop/) with iPhone, and the payment cannot be processed with Apple Pay.

Using WooCommerce Stripe Gateway 3.1.5

**Comment by roykho** [comment]
Turn on debug in Stripe settings and repeat the process. Then go to WooCommerce->system status->logs and view the Stripe log to see what you get.

**Comment by williamlwu** [comment]
Hello Roy,

I turned on the debug and tried purchasing using Apple Pay. But it’s not showing anything under the Logs tab.

William

**Comment by roykho** [comment]
Try turning shipping off.

**Comment by williamlwu** [comment]
it's off

**Comment by williamlwu** [comment]
So, after updating 3.1.4 I believe (when it first start to support Apple Pay), the quantity section in Shop single page has some serious appearance issue. It will be divided into 3 lines instead of one, with minus on the first line, then amount in the second line, and plus on the third line. I don't know if it has to do with it.

**Comment by williamlwu** [comment]
It used to be the Apple Pay not working on iOS, but I think the button stop working now on Desktop too. I just updated to 3.1.5 yesterday.

**Comment by roykho** [comment]
When I tested your site it works. Only on single product page where it doesn't. But on my test site all works fine.

**Comment by williamlwu** [comment]
Yes, in single product page the button doesn't work for both Desktop and iOS on my end. It only works in the checkout page for Desktop, not for iOS either.

In iOS, the button doesn't work at all (single product, cart, and checkout)

**Comment by roykho** [comment]
All my testing was on iOS.

**Comment by williamlwu** [comment]
Okay, hmm. It doesn't seem to work on my devices.
Do you know why?

**Comment by roykho** [comment]
I suggest you turn all plugins off except Stripe and WC, then switch to a WP default theme. Re-test.

**Comment by williamlwu** [comment]
I don't think I can afford to do that at this moment, besides of that, any suggestions?

**Comment by roykho** [comment]
Nothing else at this point.

**Comment by williamlwu** [comment]
Check now. It's deactivated

**Comment by williamlwu** [comment]
It's still not working in Twenty Seventeen Theme, with all plugins deactivated except WC and Stripe

**Comment by roykho** [comment]
With shipping off?

**Comment by williamlwu** [comment]
yes

**Comment by roykho** [comment]
I am still seeing the same theme.

**Comment by williamlwu** [comment]
Okay, let me deactivate again. Let me know when you're done

**Comment by williamlwu** [comment]
Check now, all deactivated

**Comment by roykho** [comment]
yup worked for me.

**Comment by williamlwu** [comment]
But it doesn't work for me... the button is retracting again... and it shows processing for a short second

**Comment by williamlwu** [comment]
The problem exist even after I reinstalling the plugin, do you have any idea why?

**Comment by roykho** [comment]
You can try opening up a support ticket at woocommerce.com. Without logging into your site and do troubleshooting, it is hard to know what is going on.

**Comment by williamlwu** [comment]
thanks for your support
