### ISSUE TITLE
Paid orders are marked "pending payment" when a new account is created at checkout using the "early access" payment methods.

### ISSUE THREAD

**Issue by billrobbins** [woocommerce/woocommerce-gateway-stripe#2176]
**Describe the bug**
With the new "early access" payment method enabled, if a customer creates an account at checkout, the order status remains "pending payment" even though the order is paid.  The Stripe metadata is not saved to the order as it typically is.

**To Reproduce**
1. Go to WooCommerce > Settings > Payments > Stripe.
2. Click on the "Enable in your store" button.  Enable at least one payment method and save your settings.
3.  Go to WooCommerce > Settings > Accounts & Privacy.  Make sure the option to allow customers to create accounts at checkout is enabled.  
4. Use a private window to purchase a product.  Select the option to create an account at checkout.
5. Notice how the created order is "pending payment."

**Expected behavior**
I expect orders to be "processing" after they are paid even if an account is created at checkout.

**Logs**
The logs show this error related to the order that is created.  

```
2021-11-22T15:57:37+00:00 DEBUG 
====Stripe Version: 5.8.0====
====Start Log====
Could not find order via intent ID: pi_3JyetKFtFg3Sw8Dk1Mg55zmM
====End Log====
```

**Screenshots**

Stripe meta missing
![missing-stripe-meta](https://user-images.githubusercontent.com/1138631/142901028-8597e07c-fde4-46ec-ae84-68230a8c3546.png)

Correct Stripe order from same site
![stripe-meta](https://user-images.githubusercontent.com/1138631/142901047-7c901601-62db-4f32-9a66-23bd0ac1d942.png)

**Environment (please complete the following information):**
 - WordPress Version: 5.8.2
 - WooCommerce Version 5.9.0
 - Stripe Plugin Version 5.8.0
 - Browser: Chrome 96.0.4664.45
 - Any other plugins installed: none active

**Additional context**
4536655-zen

**Comment by aheckler** [comment]
I have a similar case in 4546839-zen. Upon testing on my own site as described above, the order has the correct metadata and status, but I still see errors in my Stripe logs.

```
2021-11-29T18:42:33+00:00 DEBUG 
====Stripe Version: 5.8.1====
====Start Log====
Could not find order via intent ID: pi_XXXXXXXXXREDACTEDXXXXXX
====End Log====
```

**Comment by fevered** [comment]
Also reported in 4561735-zen

**Comment by billrobbins** [comment]
Another report: 4565782-zen

**Comment by WillBrubaker** [comment]
4569758-zen

**Comment by aheckler** [comment]
Pretty sure 4547608-zen is this.

**Comment by wpniall** [comment]
Another report in 4579434-zen

**Comment by billrobbins** [comment]
One more 33036722-hc

**Comment by fevered** [comment]
I am pretty sure 4630589-zen is experiencing this issue

**Comment by nicholasjeberlin** [comment]
33583151-hc

**Comment by pauljacobson** [comment]
@billrobbins Do we have any feedback that we can share with our merchants who are affected by this issue?

**Comment by billrobbins** [comment]
@pauljacobson I have not seen any movement on this issue yet.  The only workaround that I'm aware of is to disable the early access payment methods.  That should allow this to work as expected for the merchants.

**Comment by AashikP** [comment]
Heads up that this can only be replicated on those stores without a correctly configured webhook secret (HT @cesarcosta99) :

![https://d.pr/i/kkNLWU+](https://d.pr/i/kkNLWU+)

As per [Webhooks - Documentation](https://woocommerce.com/document/stripe/#webhooks) we need to configure the webhook secret.

**Comment by cesarcosta99** [comment]
Closing this issue in favor of the issue mentioned above, which will provide a tool to fix the orders affected by this problem. As @AashikP commented, the webhooks needs to be (re)configured and the problem will go away. The new checkout experience can be re-enabled as well.

**Comment by jivaneo** [comment]
Still experiencing same bug on my live sites.
Seems we need to disable “early access” payment methods... 
Any update on this topic?
