### ISSUE TITLE
Javascript "[Error] TypeError: Type error" on single Buy w/Apple Pay Button on Safari 10.1 (12603.1.30.0.34)

### ISSUE THREAD

**Issue by jaydisc** [woocommerce/woocommerce-gateway-stripe#218]
Hi, saw that Stripe was updated today. I had previously been using 3.1.4 directly from GitHub. `git fetch` said there was one commit that didn't match (maybe a commit was removed/amended as I did not modify), so I `git reset --hard origin/master` and was now running 3.1.5.

Next, I want to a single product page and chose Buy with Apple Pay.

I expected the sheet to pop down, but instead I got the following JavaScript error in the console:

    [Error] TypeError: Type error
    	(anonymous function) (v2:3:6952)
    	a (v2:3:6952)
    	buildSession (v2:2:19316)
    	(anonymous function) (stripe-apple-pay-single.min.js:1:1221)
    	dispatch (jquery.js:3:12450)
    	handle (jquery.js:3:9179)

I then did a `git checkout 3.1.4` and refreshed, but the same error persisted.

I then downloaded and installed Stripe 3.1.5 directly from the WooCommerce website - same issue.

I did not think to test before I upgraded Stripe. Could this possibly be caused by the recent macOS 10.12.4 update?

This does not occur when choosing Buy w/Apple Pay from the cart page.

**Comment by roykho** [comment]
I am not seeing that issue on my end. Try flushing your cache. Also check if there are no conflicts with other plugins or theme.

**Comment by jaydisc** [comment]
I've disabled all plugins (except WooCommerce and the Stripe Gateway), used stock Storefront, and still having it. Here is a URL if you'd like to try: https://garagesale.itfdb.com/shop/transformers/masterpiece/takara-tomy-transformers-masterpiece-mp30-ratchet/

**Comment by roykho** [comment]
Can you state what Safari and macOS version you're using?

**Comment by jaydisc** [comment]
macOS Version 10.12.4 (16E195)
Safari Version 10.1 (12603.1.30.0.34)

Did you try my site?

**Comment by roykho** [comment]
Not yet. Trying to replicate this. Does it happen if you use iOS instead of desktop?

**Comment by roykho** [comment]
Can you please test master branch and see if it fixes your issue?

**Comment by jaydisc** [comment]
Yes! Working with commit 35a813d.

Interestingly (I've reported this elsewhere), I got a shipping charge on the sheet, but it still didn't show my shipping address: https://cl.ly/joIU

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/35a813d86c6c914987ab10a6dad5a0ed43b3525c
