### ISSUE TITLE
Inline checkout field is not working with the new update of 5.8

### ISSUE THREAD

**Issue by FunkyCss** [woocommerce/woocommerce-gateway-stripe#2184]
**Describe the bug**

**To Reproduce**

1. Go to your plugin settings , and choose the new checkout experience, save it . After you have save it enable it again.

2. After you have NOT enabled anymore the new checkout experience ( Go to  Enable separate credit card form ) and DO NOT select that field, 

3. Go to checkout page and notice that it should work with inline style but it works as seperate credit card form even if you have not select that option.

Please NOTICE , that this issue as my other one https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2183

In the first visit seems that they work OK , but my guess is that the new checkout experience brakes things up when first has been selected. So keep this on mind that in the first sight you will see everything fine , but it is not.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version - 5.8
 - WooCommerce Version - 5.9 
 - Stripe Plugin Version - 5.8.1
 - Browser [e.g. chrome, safari] and Version - chrome 
 - Any other plugins installed - None

**Additional context**

**Comment by WillBrubaker** [comment]
A Stripe user stopped in to chat with us in 32103387-hc and the issue that they are encountering seems very closely related to this, if not the same issue. On checkout, they are seeing the following:
![see screen shot](https://d.pr/i/P0pbVX+)

And they discovered that deselecting the box to enable separate forms fixes it for them.

**Comment by diegocurbelo** [comment]
In the New checkout experience the CC form fields are always displayed separately.
The old settings did not have the option enable/disable it when the new experience was enabled.
