### ISSUE TITLE
Google Pay does not appear as an option on Google Chrome (iOS)

### ISSUE THREAD

**Issue by csmcneill** [woocommerce/woocommerce-gateway-stripe#2186]
**Describe the bug**
When accessing a site using Google Chrome on an iOS device, Google Pay is not displayed on the cart or checkout pages.

Identified in 4406789-zen. I experience the same issue with WooCommerce Payments, so this may be an issue on Stripe's end.

**To Reproduce**
1. Configure a site to accept Google Pay.
2. Access the site using Google Chrome.
3. Confirm that Google Pay is an available option.
4. Attempt to purchase the same products using Google Chrome on an iOS device.
5. Google Pay is not visible.

**Expected behavior**
Google Pay is available for iOS devices running Chrome, so it is expected that Google Pay would be an available option when viewing WooCommerce sites via Chrome on iOS.

**Screenshots**
Google Pay available on desktop:

![https://d.pr/i/b9YrB3](https://d.pr/i/b9YrB3+) 
Full Size: https://d.pr/i/b9YrB3

Google Pay unavailable on mobile:

![https://d.pr/i/eRtOcD](https://d.pr/i/eRtOcD+) 
Full Size: https://d.pr/i/eRtOcD

**Environment (please complete the following information):**
 - Desktop: Chrome Version 96.0.4664.55
 - Mobile: Chrome Version 96.0.4664.53

SSR:
<details>
`
### WordPress Environment ###

WordPress address (URL): https://cmtestwoo.wpcomstaging.com
Site address (URL): https://cmtestwoo.wpcomstaging.com
WC Version: 5.9.0
REST API Version: ✔ 5.9.0
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: 5.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.26
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.78.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.22-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.0
WC Database Prefix: wp_
Total Database Size: 12.89MB
Database Data Size: 9.22MB
Database Index Size: 3.67MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_aw_gc_codes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aw_gc_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aw_gc_users_gift_card: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ce4wp_contacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.08MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 0.45MB + Engine InnoDB
wp_posts: Data: 0.30MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 0.47MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 79
aw_workflow: 1
customize_changeset: 5
def_reg_fields: 10
jetpack_migration: 2
jp_img_sitemap: 4
jp_sitemap: 4
jp_sitemap_master: 4
mailpoet_page: 1
nav_menu_item: 11
page: 10
post: 2
product: 74
product_variation: 46
revision: 8
shop_coupon: 1
shop_order: 38
shop_order_refund: 3
shop_subscription: 4
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce Stripe Gateway: by WooCommerce – 5.8.1
WooCommerce Payments: by Automattic – 3.3.0
WooCommerce: by Automattic – 5.9.0

### Inactive Plugins (43) ###

Akismet Anti-Spam: by Automattic – 4.2.1
AMP: by AMP Project Contributors – 2.1.4
AutomateWoo: by WooCommerce – 5.4.2
B2B for WooCommerce: by Addify – 1.8.5 (update to version 1.9.0 is available)
Classic Editor: by WordPress Contributors – 1.6.2
CoBlocks: by GoDaddy – 2.19.1
Creative Mail by Constant Contact: by Constant Contact – 1.4.7
Crowdsignal Forms: by Automattic – 1.5.12
Facebook for WooCommerce: by Facebook – 2.6.7
Gift Card By Aheadworks: by Aheadworks – 1.0.0
Google Listings and Ads: by WooCommerce – 1.7.0
Gutenberg: by Gutenberg Team – 11.9.1
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack: by Automattic – 10.4-a.9
Layout Grid: by Automattic – 1.7.2
MailPoet 3 (New): by MailPoet – 3.74.1
Meks Quick Plugin Disabler: by Meks – 1.0
Order Tags: by 99w – 1.2.1 (update to version 1.4.0 is available)
Page Optimize: by Automattic – 0.5.1
Printful Integration for WooCommerce: by Printful – 2.1.26
Storefront Hamburger Menu: by WooCommerce – 1.2.2
Storefront Homepage Contact Section: by WooThemes – 1.0.5
Storefront Product Sharing: by WooCommerce – 1.0.6
WCS staging: by mb – 1.0
WooCommerce Chained Products: by StoreApps – 2.9.9 (update to version 2.11.0 is available)
WooCommerce Composite Products: by SomewhereWarm – 8.1.4 (update to version 8.3.3 is available)
WooCommerce Deposits: by WooCommerce – 1.5.7
WooCommerce Force Sells: by WooCommerce – 1.1.28 (update to version 1.1.29 is available)
WooCommerce Mix and Match Products: by Kathy Darling – 1.11.2
WooCommerce One Page Checkout: by Automattic – 1.8.0 (update to version 1.9.0 is available)
WooCommerce PayPal Payments: by WooCommerce – 1.6.2
WooCommerce Product Add-ons: by WooCommerce – 4.1.0 (update to version 4.4.0 is available)
WooCommerce Product Bundles: by SomewhereWarm – 6.10.3 (update to version 6.12.7 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.46
WooCommerce Shipping & Tax: by WooCommerce – 1.25.20
WooCommerce Smart Refunder: by StoreApps – 1.5.4 (update to version 1.6.0 is available)
WooCommerce Square: by WooCommerce – 2.7.0
WooCommerce Subscriptions: by WooCommerce – 3.1.4 (update to version 3.1.6 is available)
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.30 (update to version 3.0.35 is available)
WooCommerce Variation Swatches and Photos: by Element Stark – 3.1.3 (update to version 3.1.4 is available)
WooCommerce Xero Integration: by WooCommerce – 1.7.37 (update to version 1.7.40 is available)
WordPress.com Editing Toolkit: by Automattic – 3.19643
WP Mail Logging: by Wysija – 1.10.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
gift_card_virtual (gift_card_virtual)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #19 - /
Cart: #20 - /cart/
Checkout: #21 - /checkout/
My account: #22 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://cmtestwoo.wpcomstaging.com
Subscription Statuses: wc-on-hold: 3
wc-active: 1

WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

Stripe: wc-active: 1
wc-on-hold: 3

### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method

### WooCommerce Payments ###

Version: 3.3.0
Connected to WPCOM: Yes
Blog ID: 195247783
Account ID: acct_1J9yD42Er53zccJQ

### Action Scheduler ###

Complete: 70
Oldest: 2021-11-12 17:20:55 -0800
Newest: 2021-11-24 10:34:17 -0800

Pending: 2
Oldest: 2021-11-24 12:24:07 -0800
Newest: 2022-08-25 20:48:08 -0700

### Status report information ###

Generated at: 2021-11-24 10:45:06 -08:00
`
</details>

**Additional context**

**Comment by ricardo** [comment]
The plugin uses Stripe's [Payment Request Button](https://stripe.com/docs/stripe-js/elements/payment-request-button) integration for Apple Pay and Google Pay.

Unfortunately, Chrome's support of/commitment to the PaymentRequest web standard is not great, so the Google Pay button is not supported on iOS devices. AFAICT, it's fully supported on Chrome + Android, and on Chrome + desktop devices which have a Google Pay ServiceWorker running in the background.

Stripe said earlier this year that they'd be working on a native integration for Google Pay, which would be bundled into stripe.js and would fix this issue, but unfortunately that wasn't released yet.

I've asked Stripe for an ETA on this.

More details in internal thread: p1639043218081600-slack-CGGCLBN58

**Comment by ricardo** [comment]
This is Xiao's (Stripe) reply to my query about an ETA for Google Pay to be available as a native implementation:

> Hi both - want to revert back here that due to technical limitation,  we don’t anticipate to support GPay on Mobile Chrome on iOS in the near-term future.
This has dependency on both Google and Apple’s own product supportability, and will require significant undertaking engineering wise.
Sorry that it’s not the answer you are looking for. We will keep you in the loop if anything changes on this front.

So unfortunately it doesn't look like we can do much about this issue 😞. We could either close it, or keep it indefinitely with a blocked status.

**Comment by aheckler** [comment]
4684545-zen

**Comment by shaunkuschel** [comment]
35159469-hc

**Comment by dougaitken** [comment]
Since this is a feature gap outside of the plugin offering, I'm closing this Issue. Whenever Stripe update to having Google Pay show on iOS browsers, I believe this will work without any change on our side. We can revisit when that happens.
