### ISSUE TITLE
about verify domain

### ISSUE THREAD

**Issue by 996express** [woocommerce/woocommerce-gateway-stripe#219]
I installed using the stripe plugin and would like to use applepay. 
The plugin always prompts: You do not have the correct file at at https://996express.com/.well-known/apple-developer-merchantid-domain-association. To verify with Apple that you control your domain, you must host This file: https://stripe.com/files/apple-pay/apple-developer-merchantid-domain-association. For more information, see https://stripe.com/docs/apple-pay/web#verifying- Your-domain. 
But I use https://996express.com/.well-known/apple-developer-merchantid-domain-association can be opened, why is there an error message?

**Comment by roykho** [comment]
I would suggest you delete that file and the .well-known folder and let the plugin do everything for you.

**Comment by 996express** [comment]
which plugin?

**Comment by roykho** [comment]
The Stripe plugin you're using here.

**Comment by 996express** [comment]
I filled out the Live Publishable Key and Live Secret Key, but the page still shows：
Apple Pay domain verification failed. Please check the log to see the issue. (Logging must be enabled to see recorded logs)

**Comment by roykho** [comment]
Turn on the debug log in the plugin settings and re-test. Then check the log to see what message it is giving you.

**Comment by 996express** [comment]
04-01-2017 @ 22:47:10 - Apple Pay: Items in the cart has unsupported product type ( Apple Pay button disabled )
04-01-2017 @ 22:47:10 - Apple Pay: Items in the cart has unsupported product type ( Apple Pay button disabled )
04-01-2017 @ 22:47:10 - Apple Pay: Items in the cart has unsupported product type ( Apple Pay button disabled )
04-01-2017 @ 22:47:10 - Apple Pay: Items in the cart has unsupported product type ( Apple Pay button disabled )
04-01-2017 @ 22:47:28 - Apple Pay: Items in the cart has unsupported product type ( Apple Pay button disabled )
04-01-2017 @ 22:47:28 - Apple Pay: Items in the cart has unsupported product type ( Apple Pay button disabled )
04-01-2017 @ 22:47:28 - Apple Pay: Items in the cart has unsupported product type ( Apple Pay button disabled )
04-01-2017 @ 22:47:28 - Apple Pay: Items in the cart has unsupported product type ( Apple Pay button disabled )
04-01-2017 @ 22:47:34 - Apple Pay: Items in the cart has unsupported product type ( Apple Pay button disabled )
04-01-2017 @ 22:47:34 - Apple Pay: Items in the cart has unsupported product type ( Apple Pay button disabled )
04-01-2017 @ 23:06:07 - Error: Unable to verify domain - You do not have the correct file hosted at https://996express.com/.well-known/apple-developer-merchantid-domain-association. To verify with Apple that you control your domain, you must host this file: https://stripe.com/files/apple-pay/apple-developer-merchantid-domain-association. For more information, see https://stripe.com/docs/apple-pay/web#verifying-your-domain.
04-01-2017 @ 23:06:10 - Error: Unable to verify domain - You do not have the correct file hosted at https://996express.com/.well-known/apple-developer-merchantid-domain-association. To verify with Apple that you control your domain, you must host this file: https://stripe.com/files/apple-pay/apple-developer-merchantid-domain-association. For more information, see https://stripe.com/docs/apple-pay/web#verifying-your-domain.

**Comment by roykho** [comment]
After you deleted the folder as I asked, did you let the plugin create that folder and file for you? And if so, did you check if that file is there?

**Comment by 996express** [comment]
I deleted the folder and the file, re-enabled the stripe plugin.
and find the plugin create the folder and file
Then what should i do?

**Comment by roykho** [comment]
Then are you still getting the error? Check the log if you're still getting new errors. Check timestamp. If that still doesn't work, then I suggest you contact Stripe support.

**Comment by 996express** [comment]
04-01-2017 @ 23:44:09 - Error: Unable to verify domain - You do not have the correct file hosted at https://996express.com/.well-known/apple-developer-merchantid-domain-association. To verify with Apple that you control your domain, you must host this file: https://stripe.com/files/apple-pay/apple-developer-merchantid-domain-association. For more information, see https://stripe.com/docs/apple-pay/web#verifying-your-domain.
04-01-2017 @ 23:44:12 - Error: Unable to verify domain - You do not have the correct file hosted at https://996express.com/.well-known/apple-developer-merchantid-domain-association. To verify with Apple that you control your domain, you must host this file: https://stripe.com/files/apple-pay/apple-developer-merchantid-domain-association. For more information, see https://stripe.com/docs/apple-pay/web#verifying-your-domain.

I think I should contact stripe technical support

thanks
