### ISSUE TITLE
Enable Stripe after plugin setup

### ISSUE THREAD

**Issue by cesarcosta99** [woocommerce/woocommerce-gateway-stripe#2202]
## Description

We need to enable the Stripe gateway after the merchant completes the connect flow, either via OAuth or the account keys.

![image](https://user-images.githubusercontent.com/10233985/143870707-81b37270-28ad-4ff5-8abf-73e74fd00d52.png)

## Acceptance criteria

- After completing the plugin setup, Stripe is enabled.

**Comment by rafaelzaleski** [comment]
@cesarcosta99 

What if I want to save the account keys or connect my account, but I don't want to enable Stripe on my store right now? 

This situation will be particularly annoying if we don't show a message that we enabled the payment gateway and the merchant doesn't see it was enabled automatically.

IMO, a warning on the top of the settings page when the gateway is disabled would provide a better experience.

**Comment by cesarcosta99** [comment]
Good call! We can maybe consider, after the plugin setup, **if** Stripe **is not** enabled already (they may have just disconnected), redirect the user to the Settings tab, where they can straight enable Stripe if they want. If we don't do anything people may assume it gets automatically enabled after the plugin setup.

**Comment by rafaelzaleski** [comment]
That's a good idea! Thank you.
