### ISSUE TITLE
Add prompt when leaving with unsaved changes

### ISSUE THREAD

**Issue by cesarcosta99** [woocommerce/woocommerce-gateway-stripe#2203]
## Description

We can make use of a prompt to confirm leaving the page with unsaved changes.

Implementation example:

https://github.com/Automattic/woocommerce-payments/blob/3fa326bfbca4a4609db2bc02a21dbe1b07b04906/client/disputes/evidence/index.js#L380-L389

## Acceptance criteria

- When leaving the page with any changes, a prompt pops up asking if the user really want to leave.

**Comment by asumaran** [comment]
> to confirm leaving the page with unsaved changes.

@cesarcosta99, which page precisely?  I assume the page you are referring to is the Stripe settings page?

I understand the confirmation should be displayed every time the user tries to navigate away from the stripe settings page but should it also be displayed when switching tabs (Payment Methods/Settings)?

**Comment by cesarcosta99** [comment]
>I assume the page you are referring to is the Stripe settings page?

Yes, that's correct, it's the settings page. Perhaps we can make an extra effort to implement this in the payment gateways page (e.g. SEPA, Alipay etc). Since the payment gateway screen logic is unique for all gateways, I think it's not a big deal.

>should it also be displayed when switching tabs

IMO, it shouldn't. The changes we make don't get lost when we switch tabs, therefore, when we save, all changes made regardless the tab we have currently selected are correctly passed to the API.
