### ISSUE TITLE
Fix copy of CTA on express checkout customization

### ISSUE THREAD

**Issue by cesarcosta99** [woocommerce/woocommerce-gateway-stripe#2206]
## Description

In the [express checkout customization page](http://localhost:8082/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings&area=payment_requests), we should replace the CTA option "Only icon" with "Default".

![image](https://user-images.githubusercontent.com/10233985/143879696-1b45d748-b8a1-462d-8cd4-2794acefc806.png)

**Comment by asumaran** [comment]
@cesarcosta99 it seems the "Default" option has been renamed to "Icon Only" ([Ref](https://wcpay.wordpress.com/2021/05/05/stripe-call-payment-request-buttons-and-digital-wallets-in-woocommerce-payments/)).

Closing this issue now /cc @frosso
