### ISSUE TITLE
Do not perform update if PHP is outdated

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce-gateway-stripe#221]
This is an interesting question: should we allow the update process to perform if PHP is outdated?

Here is a comment from a user:

>I upgraded and the plugin has effectively (although not literally) deactivated itself. It is technically active, but it is not operational because my PHP version is too low.
>Shouldn't this be a warning and the upgrade stop RATHER than allowing the upgrade and then totally shutting down the plugin? It is a payment method after all.

**Comment by roykho** [comment]
I would recommend people to always use testing/staging site before updating anything. That is just the best practice to prevent issues like this.

With that said, pre 5.6 had a lot of security issues so we had to push this forward. You can see here that the minimum requirement for WC is 5.6 https://docs.woocommerce.com/document/server-requirements

So we follow suit in this update. However we could have done a better job of showing a notice perhaps one release prior and will do this in the future.

Thanks for bringing this up.

**Comment by corsonr** [comment]
Thanks for the clarifications
