### ISSUE TITLE
Make Apple Pay Instance Static?

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce-gateway-stripe#222]
I was wondering if the instance of Apple Pay shouldn't be set to static [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-apple-pay.php#L126) so that we can use code similar to this for example:

```
remove_action( 'woocommerce_after_add_to_cart_quantity', array( WC_Stripe_Apple_Pay::instance(), 'display_apple_pay_button' ), 1 );
```

As for now, and apparently since 3.1.5, this snippet creates an error:

>Deprecated: Non-static method WC_Stripe_Apple_Pay::instance() should not be called statically in /wp-content/themes/twentyseventeen/functions.php on line 31

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Good catch! Yes it should be static and was put there exactly for this purpose to remove hooks. I must of missed it.

**Comment by corsonr** [comment]
![](http://cld.wthms.co/stAb+)
