### ISSUE TITLE
Missing translations for strings in transpiled js files

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#2223]
**Describe the bug**

Some translations strings are missing in the generated POT file, particularly those added with the new settings.

If the compiled files are not minified we can extract the strings directly, if minified we will need to use source-maps like WC Payments: https://github.com/Automattic/woocommerce-payments/pull/3486

The generated POT files has a reference to some of compiled files (build/index.js), but others are missing and also there are references to the docker folder:
```
#: build/index.js:1
#: client/blocks/stripe-utils/utils.js:135
#: docker/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-blocks/assets/js/payment-method-extensions/payment-methods/stripe/stripe-utils/utils.js:211
#: docker/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-blocks/build/wc-payment-method-stripe.js:1
msgid "The card expiration year is in the past"
msgstr ""
```

**To Reproduce**
1. Run `npm run makepot`
2. Open the generated POT file: `languages/woocommerce-gateway-stripe.pot`
3. Verify that several translation strings are missing, for example:
- `Enabled` from `client/settings/account/details/index.js`
- `To preview the %1$s button, view this page in the %2$s browser.` from `client/upe-onboarding-wizard-methods-selector`
- `Get early access to additional payment` from `client/entrypoints/payment-request-button-preview.js`

**Expected behavior**
All strings must be present in the POT file.

**Additional context**

**Comment by dmallory42** [comment]
I had a German customer in my support rotation who raised what seems to be a related concern regarding the "Pay with credit/debit card" string in the UPE checkout.

Screenshot:
<img width="922" alt="Screenshot 2021-12-13 at 11 56 41 (1)" src="https://user-images.githubusercontent.com/11770181/145810613-83dcfd8c-5ab5-40d4-a0eb-d83ca63e92ae.png">

This was in version 2.8.1, however I checked the `pot` file and cannot see the string.
