### ISSUE TITLE
Doc: The #new-checkout-experience anchor doesn't take the user to any specific section

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2227]
**Describe the bug**

We're using URL `https://woocommerce.com/document/stripe/#new-checkout-experience` in several places to refer to the documentation of the new checkout experience, but the anchor `#new-checkout-experience` doesn't take the user to any specific section.

This is happening with a few other anchors we link to in the docs as well. These are the ones I found:
`#additional-payment-methods`
`#does-stripe-support-authorization-and-capture`
`#express-checkouts`
`#test-mode`

**To Reproduce**
1. Go to https://woocommerce.com/document/stripe/#new-checkout-experience (or any of the anchors I mentioned above)
2. Notice that it takes you to the top of the page, not to a section with information about the new checkout experience

You can find them in the docs by searching either in the page's elements or in the page source.

**Expected behavior**
I'd expect this link to take me to a section in the docs where I'd learn about the new checkout experience.

**Additional context**
Besides the internal links in the documentation, we're linking to this URL from the plugin in several places, like from here, for example (screenshot below) when UPE is disabled. 
![image](https://user-images.githubusercontent.com/41606954/145684482-e09d896e-0c02-46f8-b377-df14c36edaa2.png)

If we decide to update the URL or its anchor, we'd need to update the link in the plugin as well. #2229 refers to this issue but from within the plugin.

**Comment by dougaitken** [comment]
[#additional-payment-methods](https://woocommerce.com/document/stripe/#additional-payment-methods) is fixed
[#new-checkout-experience](https://woocommerce.com/document/stripe/#new-checkout-experience) is fixed
[#does-stripe-support-authorization-and-capture](https://woocommerce.com/document/stripe/#does-stripe-support-authorization-and-capture) is working
[#test-mode](https://woocommerce.com/document/stripe/#test-mode) is working

I think some of this was with the migration of the documentation from the subsite to the main site, anchor refs were broken.
