### ISSUE TITLE
Doc: There are links in the public documentation pointing to WP's edit post URL

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2228]
**Describe the bug**
In [our Stripe docs](https://woocommerce.com/document/stripe), there are links that point to `https://woocommerce.com/wp-admin/post.php?post=8828148&action=edit`.

**To Reproduce**
1. Go to https://woocommerce.com/document/stripe/, in incognito to make things simpler
2. Open the browser inspect tools
3. Search for `action=` within the page's elements
4. Notice there are three instances where we're linking to WP's edit post URL instead of the public URL for the docs
![image](https://user-images.githubusercontent.com/41606954/145684894-dc07fb0b-4b4f-46c3-991e-48792f9af099.png)

**Expected behavior**
These links should point to the public URL for the docs, not to the edit post URL. That'd be `https://woocommerce.com/document/stripe/#new-checkout-experience` instead of `https://woocommerce.com/wp-admin/post.php?post=8828148&action=edit#new-checkout-experience`

**Additional context**
If we decide to update the URLs in #2227, this issue would get solved.

**Comment by dougaitken** [comment]
I've fixed this one and I'll comment on the others but documentation queries are best handled by the docs guild or Payment Ops.
