### ISSUE TITLE
Links within the plugin are pointing to inexistent anchors in the docs

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2229]
**Describe the bug**
There are some links in the plugin that are supposed to go to a section in the docs but they leave you at the beginning of the docs instead.

**To Reproduce**
This is one example:
1. Go to `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe`
2. Under "Express checkouts", notice that "Learn more" links to https://woocommerce.com/document/stripe/#payment-request-buttons
![image](https://user-images.githubusercontent.com/41606954/145686168-bcdb75a6-9743-48c7-ae2a-07403576ae70.png)

3. Click on it
4. Notice it takes you to the beginning of the documentation

**Expected behavior**
I'd expect it to take me to a section where I'd learn about the Payment request buttons.

**Additional context**
These are some other instances of this issue I found:
`#payment-request-buttons`
`#faq`
`#new-checkout-experience`
`#additional-payment-methods`
`#apple-pay`

<img src="https://user-images.githubusercontent.com/41606954/145686202-61e606a9-efb1-4aee-b8ed-424ab366f3d2.png" width="400px"/>

#2227 refers to this same issue but within the docs themselves.

**Comment by dougaitken** [comment]
It looks like at some point `#payment-request-buttons` has been rewritten to be the [Express checkouts](https://woocommerce.com/document/stripe/#express-checkouts) section, correctly matching the name of this feature with in the plugin.

> These are some other instances of this issue I found:
> #payment-request-buttons
> #faq
> #new-checkout-experience
> #additional-payment-methods
> #apple-pay

[#faq](https://woocommerce.com/document/stripe/#faq) is working
[#new-checkout-experience](https://woocommerce.com/document/stripe/#new-checkout-experience) is fixed
[#additional-payment-methods](https://woocommerce.com/document/stripe/#additional-payment-methods) is fixed
[#apple-pay](https://woocommerce.com/document/stripe/#apple-pay) is working

overall, the PR / Express checkouts anchor is the only one that needs a PR here.

**Comment by Mayisha** [comment]
The express checkout anchor was also fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2464. I did a quick check and the other links are also pointing to the correct sections.

Closing this issue as no fix is required.
