### ISSUE TITLE
Display Accepted Payment Types Based on Location, not Currency

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce-gateway-stripe#223]
According to Stripe, the accepted payment types are based on the shop location, not the shop  currency:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L205

Which means we should use `get_woocommerce_currency()` [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L205), but `wc_get_base_location()` instead.

555123-zd-woothemes

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
I believe this code was added a long time ago. Has someone complained about this? Also do you have reference to the Stripe document with this statement?

**Comment by corsonr** [comment]
>Has someone complained about this?

Yes, in the ticket listed above.

>Also do you have reference to the Stripe document with this statement?

yes, sorry I thought I added the URL in my initial message: https://support.stripe.com/questions/which-cards-and-payment-types-can-i-accept-with-stripe

**Comment by roykho** [comment]
Sorry I totally missed the ZD ticket #. :)

**Comment by corsonr** [comment]
Man, you're on fire today!
