### ISSUE TITLE
Add conditional to prevent applying mask on non existing element

### ISSUE THREAD

**Issue by leonardola** [woocommerce/woocommerce-gateway-stripe#2233]
**Describe the bug**
@areoimiles commented [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2115#issuecomment-991856005) that When Boleto is disabled an error can happen and block the use of other payment methods. The error happens at https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/assets/js/stripe.js#L279.
I could not simulate the error but a validation can be added to make sure the element is present instead of trying to apply a mask in a non existent element.

**Comment by leonardola** [comment]
@areoimiles I could not reproduce the error but added the conditional you suggested so the next release should not cause that error anymore. 

In the meantime. Does the jquery-mask.min.js file gets loaded without errors on checkout page? Because if it does not load correctly that could generate the error you mentioned. Not just the element not existing. 
Many things can cause it to not load on your end like host restriction, cache, firewall, etc.

**Comment by areoimiles** [comment]
@leonardola thanks very much for looking in to this. Yes, I can confirm the jquery-mask.min.js is loaded without error. I'll look out for the next release!
