### ISSUE TITLE
Add a filter call when updating an intent (wc_stripe_update_existing_intent)

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#2240]
**Describe the bug**

Currently there is a filter "wc_stripe_generate_create_intent_request" when creating a new intent, but there is no filter when updating an existent intent.

Function with the filter:
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/fe881c4c271fcbe0457[…]2150c/includes/abstracts/abstract-wc-stripe-payment-gateway.php

Function that should have an equivalent filter:
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/fe881c4c271fcbe0457[…]2150c/includes/abstracts/abstract-wc-stripe-payment-gateway.php

**Expected behavior**
Should be possible to add a filter to update the intent being updated (like its possible when creating an intent)

**Comment by shaunkuschel** [comment]
Reported via 4609846-zen
