### ISSUE TITLE
Update Now button to update business information does not go to the correct page

### ISSUE THREAD

**Issue by joashrajin** [woocommerce/woocommerce-gateway-stripe#2241]
**Describe the bug**

When you see the `Payments/payouts may be disabled for this account until missing business information is updated.` message, the `Update Now` button links you to https://stripe.com/support which seems incorrect

**To Reproduce**
1. You would need to have a Stripe account that has Payments or Deposits disabled. This can be done on an account that is not activated
2. Go to WooCommerce > Settings > Payments > Stripe > Settings > Account details
3. Click on the Update Now button to update your business information

**Expected behaviour**

You would expect it to take you to: https://dashboard.stripe.com/account

**Screenshots**

![image](https://user-images.githubusercontent.com/16253818/145994958-28a8ac05-6e66-408a-b176-4f2d80cf9edb.png)

**Environment (please complete the following information):**
 - WordPress Version: 5.8.2
 - WooCommerce Version: 5.9
 - Stripe Plugin Version: 5.9.0
 - Browser: Chrome Version 96.0.4664.93 

**Additional context**

4573201-zd-woothemes

**Comment by joashrajin** [comment]
I have made my first PR for this and hope it is correct 😅

**Comment by anasbouz** [comment]
Hello, this is a problem caused by a glitch in the plugin and not in the strip. I have the same problem, but everything is fine. I have paid strip settings that pass despite the presence of the yellow message in the payment settings, even with the update of WordPress to the latest version 5.8.2. Good payments

**Comment by joashrajin** [comment]
@anasbouz This sounds different from the bug mentioned here. Please make a ticket about it at https://woocommerce.com/my-account/create-a-ticket/
