### ISSUE TITLE
Custom Stripe styles ignored when UPE enabled

### ISSUE THREAD

**Issue by templeman** [woocommerce/woocommerce-gateway-stripe#2247]
After upgrading WooCommerce Stripe Gateway to 5.8.0 and enabling the 'New checkout experience', custom Stripe styles are lost.

**To Reproduce**
1. Before enabling UPE, add some custom Stripe styles using the documented filter `wc_stripe_elements_styling`. Here's a basic example based off of the [official docs](https://woocommerce.com/document/stripe-styling-fields/)
```
function my_stripe_fields_styles($styles)
{
    return array(
        'base' => array(
            'iconColor'     => '#666EE8',
            'color'         => '#31325F',
            'fontSize'      => '15px',
            '::placeholder' => array(
                'color' => '#a5bf24',
            ),
        ),
    );
}
add_filter('wc_stripe_elements_styling', 'my_stripe_fields_styles');
```
2. Observe the custom ::placeholder color shows up in the front end checkout (the filter is working).
3. Now install the [Stripe Dev plugin](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Resources-for-testing-the-WooCommerce-Stripe-Payment-Gateway#add-the-stripe-dev-plugin).
4. Under the WC Stripe Dev menu, click to enable both `UPE enabled` and `UPE redesign`.
5. Revisit checkout and observe custom Stripe styles.

**Expected behavior**
::placeholder should reflect the custom color set with `wc_stripe_elements_styling` filter.

**Actual behavior**
Custom ::placeholder style is missing.

**UPE Disabled (note custom placeholder color)**
![Screen Shot 2021-12-17 at 11 33 47 AM](https://user-images.githubusercontent.com/427403/146598413-a10e4488-ef63-42cc-8b53-5b5c2237a384.png)

**UPE Enabled**
![Screen Shot 2021-12-17 at 11 25 22 AM](https://user-images.githubusercontent.com/427403/146598468-9cc57829-83da-4656-bc81-67196437401c.png)

**Environment**
 - WordPress 5.8.2
 - WooCommerce 6.0.0
 - Stripe Plugin 5.8.0
 - Chrome Version 96.0.4664.110

This behavior can be consistently replicated by toggling UPE on/off using the WC Stripe Dev plugin.

**Comment by asumaran** [comment]
@templeman customization is not compatible with the new checkout experience. That filter only applies to the original checkout form.
