### ISSUE TITLE
Items in the cart has unsupported product type

### ISSUE THREAD

**Issue by 996express** [woocommerce/woocommerce-gateway-stripe#225]
Today I completed the domain name verification, enabled applepay, but I found that the page did not show applepay button, query the log, found that "04-04-2017 @ 23:08:19 - Apple Pay: Items in the cart Has unsupported product type (Apple Pay button disabled)
What does it mean? How can i solve this problem?

**Comment by roykho** [comment]
Try using master branch.

**Comment by 996express** [comment]
I do not quite understand you.
Can you say more detail?
Thank you very much!

**Comment by roykho** [comment]
Please update to the latest version.

**Comment by 996express** [comment]
today,i have already update 3.1.6.
But still shows "04-05-2017 @ 08:24:37 - Apple Pay: product not supported in the product type (disabled Apple Pay button)".


i use iphone ios 10.3.2(14F5065b)

**Comment by roykho** [comment]
What type of product are you putting in the cart? It only supports simple and variable.

**Comment by 996express** [comment]
variable product

**Comment by roykho** [comment]
I am not seeing this issue in my testing. I can see the Apple Pay button for both simple and variable products.
