### ISSUE TITLE
Add filters to make it compatible with other plugins

### ISSUE THREAD

**Issue by priyanka-cedcoss** [woocommerce/woocommerce-gateway-stripe#2256]
We are making stripe plugin compatibility with others plugin
so we need some filters in following places to handle payment option in stripe on checkout.
In your **plugin file /include/class-wc-stripe-upe-payment-gateway.php**

1. we need a filter within ‘**get_upe_enabled_at_checkout_payment_method_ids**’ function
like `return apply_filters(‘wc_stripe_upe_enable_payment_method’, $available_method_ids, $order_id );`
For Example,

 ```
public function get_upe_enabled_at_checkout_payment_method_ids( $order_id = null ) {
		$is_automatic_capture_enabled = $this->is_automatic_capture_enabled();
		$available_method_ids         = [];
		foreach ( $this->get_upe_enabled_payment_method_ids() as $payment_method_id ) {
			if ( ! isset( $this->payment_methods[ $payment_method_id ] ) ) {
				continue;
			}

			$method = $this->payment_methods[ $payment_method_id ];
			if ( $method->is_enabled_at_checkout( $order_id ) === false ) {
				continue;
			}

			if ( ! $is_automatic_capture_enabled && $method->requires_automatic_capture() ) {
				continue;
			}

			$available_method_ids[] = $payment_method_id;
		}

		return apply_filters('wc_stripe_upe_enable_payment_method', $available_method_ids, $order_id );
	}
```

2. Also in **process_payment** function after **line no 496.**
`$save_payment_method = apply_filters('wc_stripe_upe_force_save_source', $save_payment_method, $order );`

Please review this and provide the filter, if you have any alternate solution please provide.

**Comment by dougaitken** [comment]
Hey @priyanka-cedcoss 

It reads like you're looking for functionality that falls outside the current or future functionality of the plugin, and would require customization to fit your needs.

For assistance with customization or development with your site, we recommend reaching out to someone on our [customizations page](https://woocommerce.com/experts/) as we're not able to offer that help here.

If you feel this is a feature request, it would be great to have you add your ideas and enhancement requests to the [Stripe Feature Request Portal](https://woocommerce.com/feature-requests/stripe/), which is where developers go to look for future plugin features and improvements.

Please do search by keyword as others may have submitted already - you can then add your vote.
