### ISSUE TITLE
Payment icons are not showing

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce-gateway-stripe#226]
The icons are not showing for me after upgrading WooCommerce to 3.0. I disabled all other plugins but still the same issue.

![screen shot 2017-04-04 at 4 33 16 pm](https://cloud.githubusercontent.com/assets/2909982/24677359/923b3a24-1954-11e7-918f-cb4a2284903d.png)

![screen shot 2017-04-04 at 4 34 41 pm](https://cloud.githubusercontent.com/assets/2909982/24677378/a0f63f96-1954-11e7-952b-baa6ded45b7a.png)

**Comment by roykho** [comment]
Probably means your host is not supporting SVG files. Ask your host to enable these for you.

**Comment by kevin25** [comment]
@roykho  We have many sites on the same server and this one got the issue. The other sites are fine.
