### ISSUE TITLE
Failing JS unit tests when the node modules are installed from scratch

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2265]
**Describe the bug**
A couple of JS unit tests that normally pass, fail when `package-lock.json` and `node-modules` are removed locally and added again.

**To Reproduce**
1. Pull the latest `develop`. It's at `4f47751f` as of now
2. Run `npm run test:js`
3. Notice that all tests pass. All good until here
4. Now delete the `package-lock.json` file
5. Delete the `node_modules` directory
6. Run `npm i`
7. Run `npm run test:js` again
8. Notice that now there are two tests failing: `PaymentRequestsButtonPreview › displays an info notice if stripe is falsy` and `PaymentRequestsButtonPreview › displays the payment button when stripe is loaded` from `client/entrypoints/payment-request-settings/__tests__/payment-request-button-preview.test.js`

**Expected behavior**
I'd expect the tests to remain consistent before and after re-installing all of the packages since there weren't any changes.

**Environment (please complete the following information):**
 - Node version: 12.22.6
 - Npm version: 6.14.15

**Additional context**
There's some more context in the PR for setting up the e2e environment, [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2238). 

The issue seems to be that the speak function from @wordpress/a11y isn't being mocked [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2238/files#diff-f558a2bb1e6e3625f54d34e9b1225700a2c13a2b851220dad69fea4cf6298a70L7).

The speak function [prints the notice for screen readers](https://github.com/WordPress/gutenberg/blob/7cbba2646a522738fd95894db8240e4d3d5ac1d3/packages/a11y/src/index.js#L60), so we have the message twice on the page when Stripe isn't available (we use the [Notice](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/notice/index.js#L35) component to display the message). All good so far.

Because speak was mocked before, we're not expecting the screen reader version of this message in the tests, where they're being printed now, thus they fail.

It looked like this was happening because of the packages that were introduced there, but this also happens on `develop` so they aren't related. Hat tip to @diegocurbelo for taking the time to go through this.

**Comment by asumaran** [comment]
I'll take a look at this one
