### ISSUE TITLE
Outdated Payment Element (UPE) 'payment_element_beta_1' notice

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce-gateway-stripe#2267]
Related in WCPay: https://github.com/Automattic/woocommerce-payments/issues/3448

> You are using payment_element_beta_1, an outdated beta version of the Payment Element. To upgrade: https://stripe.com/docs/payments/payment-element/upgrade-from-beta

The Payment Element was launched publicly in October 2021. We must follow [the above guide](https://stripe.com/docs/payments/payment-element/upgrade-from-beta) to upgrade.

**To reproduce:**
1. Make sure UPE is enabled.
2. Add a product to the cart.
3. Head to the checkout page.
4. Notice the above warning in the console.

**Comment by diegocurbelo** [comment]
Removed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2375

**Comment by ricardo** [comment]
@diegocurbelo Seems like it's still there: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/client/api/index.js#L72
