### ISSUE TITLE
Please wrap get_account_summary return value in new WP_REST_Response

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#2268]
**Describe the bug**

Props @joshheald for [noticing this](https://github.com/woocommerce/woocommerce-ios/pull/5799#discussion_r779646571). Unlike other endpoint response functions, the return value of get_account_summary is not wrapped in WP_REST_Response:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/13b254d7e16f5123c3e1110f48c78ddda586adab/includes/admin/class-wc-rest-stripe-account-controller.php#L101

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
WooCommerce Stripe 5.9.0

**Additional context**
N/A

cc @brianyu28

**Comment by brianyu28** [comment]
Good catch, thank you! I've opened a PR for this in #2269.

**Comment by allendav** [comment]
Thank you!
