### ISSUE TITLE
Woocommerce.com and Woothemes.com are down

### ISSUE THREAD

**Issue by johnb1000000** [woocommerce/woocommerce-gateway-stripe#228]
I noticed about a week ago my store customers were complaining their cards are not being accepted by our woocommerce cart - weve also received some bad reviews becasue of it.

I noticed the card type error was being triggered every time (were using WooCommerce SagePay Form and SagePay Direct Gateway). I logged into the wordpress site and I can see updates are required - but nothing will update and Woocommerce sites are all down and Im unable to access my account.

So right now I cannot accept payments and haven't been able to do for some time, we're losing sales and I'e received bad reviews as some buyers have blamed us for the cart not working.

When will Woocommerce be back up again?

**Comment by roykho** [comment]
Wrong place to be posting about this.
