### ISSUE TITLE
Don't save failed cards when purchasing a Subscription based product

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce-gateway-stripe#2281]
**Describe the bug**

While attempting to purchase a Subscription-based product, the card is saved as a payment method even though the transaction fails.

**To Reproduce**

1. Attempt to purchase a simple product using the [test card](https://stripe.com/docs/testing#regulatory-cards) that's supposed to fail with `insufficient funds` error: `4000008260003178` while having `Save this card` option checked
2. Notice that the payment fails with `The card was declined.` error.
3. Reload the page and confirm that the card is not saved as a payment method
4. Now, attempt to purchase a [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038) product
5. You see the same error on checkout page, but reloading the page confirms that the card is saved

**Expected behavior**

Only save the card to user account if the transaction is successful.

**Screenshots**

![https://d.pr/i/aEgIT4+](https://d.pr/i/aEgIT4+)

![https://d.pr/i/DSpWWl+](https://d.pr/i/DSpWWl+)

**Environment (please complete the following information):**
 - WordPress Version: 5.8.3
 - WooCommerce Version: 6.1.0
 - Stripe Plugin Version: 6.0.0
 - Browser [e.g. chrome, safari] and Version: Any
 - Any other plugins installed: [WooCommerce Subscriptions](https://woocommerce.com/products/woocommerce-subscriptions/?aff=10486&cid=1131038)

**Customer Reports**

4679367-zd-woothemes

**Comment by asumaran** [comment]
Probably related to https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1362

**Comment by kaushikasomaiya** [comment]
Spotted in 7392499-zen

**Comment by wjrosa** [comment]
Hi @AashikP ! I tried to reproduce the issue using the latest version of the plugin, but I couldn't. It was probably fixed before. Can you confirm, please?

**Comment by AashikP** [comment]
@wjrosa, I can confirm that I can't replicate the issue with the above steps using the latest version of Stripe and WooCommerce Subscriptions. As you said, it may be fixed in one of the previous updates.

Closing this one. Thank you for the ping, @wjrosa!
