### ISSUE TITLE
Notification message is hidden behind account keys modal

### ISSUE THREAD

**Issue by lovo-h** [woocommerce/woocommerce-gateway-stripe#2282]
**Describe the bug**
Upon attempting to test the connection status of an invalid account key, the error notification appears behind the modal.

**To Reproduce**
1. As a merchant, go to `WooCommerce > Settings > Payments > Stripe` and click on the `Settings` tab (at the top).
2. Click on the `Edit account keys` button in order to open the **Edit test account keys & webhooks** modal.
3. Enter invalid publishable (`pk_invalid_key_0000`) and secret (`sk_invalid_key_0000`) keys and click on the `Test connection` link.
4. Notice the notification message appears behind the modal.

**Expected behavior**
The notification message should appear above the modal. Alternatively, the message should appear somewhere where it is visible to the merchant.

**Screenshots**
![](https://cdn-std.droplr.net/files/acc_1209167/5m9yVt)

**Environment (please complete the following information):**

| Environment | Version |
|---|---|
| WordPress Version | 5.8.3 |
| WooCommerce Version | 6.0.0 |
| Stripe Plugin Version | 6.0.0 |
| Browser | Any |

**Comment by asumaran** [comment]
I'll see what I can do 👍
