### ISSUE TITLE
Account endpoint returns status "complete" after deleting keys

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#2296]
**Describe the bug**
- I deleted my pk_test_... and sk_test_... keys from the plugin settings (plugin was in test mode). I then used the iOS mobile app to fetch `wc/v3/wc_stripe/account`
- I was surprised to receive status "complete" in the response body.
- Subsequent attempts to connect my card reader failed (as one would expect with no keys, but we test the account in the app to avoid the merchant getting that far, so it would be good to return a different status than complete in a case like this.)

**To Reproduce**
See above

**Expected behavior**
- Should probably return a "invalid" status.

**Screenshots**

<img width="774" alt="Screen Shot 2022-01-24 at 4 04 48 PM" src="https://user-images.githubusercontent.com/1595739/150885770-8156e3b2-be7f-49d4-851a-1db7cea9dd1c.png">

**Environment (please complete the following information):**
- Plugin version 6.0.0

**Comment by allendav** [comment]
Was testing my latest onboarding PR for iOS and ran into this unexpectedly today. Please fix :)

https://github.com/woocommerce/woocommerce-ios/pull/5958

cc @ctarda @malinajirka

**Comment by malinajirka** [comment]
@brianyu28 I haven't tested it, but it might have been fixed as part of https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2275, wdyt?

**Comment by brianyu28** [comment]
Yes, this was fixed in #2275 — in this situation, the status will now be `NOACCOUNT` for consistency with how WCPay handles no linked account. This fix will be included in Stripe v6.1.0, but in the meantime the latest `develop` branch should work as expected.

**Comment by allendav** [comment]
Thank you!

**Comment by brianyu28** [comment]
This should be fixed now in Stripe 6.1.0

**Comment by allendav** [comment]
Thank you!
