### ISSUE TITLE
Post Meta Stripe Transaction ID Empty

### ISSUE THREAD

**Issue by jmawebtech** [woocommerce/woocommerce-gateway-stripe#230]
Hi,

I am using the WooCommerce REST API V3. I am trying to find the Stripe transaction_id in the order custom fields. I found the Stripe fee and net amount, but the transaction_id is missing. The field exists in the post meta table:

![capture wp_postmeta](https://cloud.githubusercontent.com/assets/1679993/24928954/4829bc84-1ed2-11e7-8265-3bfc0b674db2.png)

How do I get the transaction_id to appear in the order_meta?

GET https://mypanier.com/wc-api/v3/orders/9922?consumer_key=X&consumer_secret=X&filter%5bmeta%5d=true HTTP/1.1
Accept: application/json
Authorization: Basic X
Host: mypanier.com
Connection: Keep-Alive

Response

{"order":{"id":9922,"order_number":9922,"order_key":"wc_order_589b68cada44d","created_at":"2017-02-08T18:51:57Z","updated_at":"2017-02-08T19:19:18Z","completed_at":"2017-02-08T19:19:18Z","status":"completed","currency":"USD","total":"13.24","subtotal":"4.90","total_line_items_quantity":1,"total_tax":"0.39","total_shipping":"7.95","cart_tax":"0.39","shipping_tax":"0.00","total_discount":"0.00","shipping_methods":"Flat Rate - Ground Shipping","payment_details":{"method_id":"stripe","method_title":"Credit Card","paid":true},"billing_address":{"first_name":"X","last_name":"X","company":"","address_1":"147 pavilion park","address_2":"","city":"Irvine","state":"CA","postcode":"92618","country":"US","email":"X@gmail.com","phone":"X"},"shipping_address":{"first_name":"X","last_name":"X","company":"","address_1":"147 pavilion park","address_2":"","city":"Irvine","state":"CA","postcode":"92618","country":"US"},"note":"","customer_ip":"98.191.202.118","customer_user_agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/56.0.2924.87 Safari\/537.36","customer_id":3,"view_order_url":"https:\/\/www.mypanier.com\/my-account\/view-order\/9922","line_items":[{"id":851,"subtotal":"4.90","subtotal_tax":"0.39","total":"4.90","total_tax":"0.39","price":"4.90","quantity":1,"tax_class":null,"name":"Organic Almonds, 2oz","product_id":2730,"sku":"agp002","meta":[{"key":"made by","label":"made by","value":"ALLGOOD Provisions"}],"bundled_by":"","bundled_item_title":"","bundled_items":[]}],"shipping_lines":[{"id":852,"method_id":"flat_rate:1","method_title":"Flat Rate - Ground Shipping","total":"7.95"}],"tax_lines":[{"id":853,"rate_id":"8","code":"US-CA-CA TAX-1","title":"CA Tax","total":"0.39","compound":false}],"fee_lines":[],"coupon_lines":[],"is_vat_exempt":false,"customer":{"id":3,"created_at":"2016-08-09T22:36:00Z","last_update":"2017-02-11T17:39:04Z","email":"X@gmail.com","first_name":"X","last_name":"X","username":"chris","role":"customer","last_order_id":"9938","last_order_date":"2017-02-08T19:16:04Z","orders_count":12,"total_spent":"608.15","avatar_url":"https:\/\/secure.gravatar.com\/avatar\/?s=96","billing_address":{"first_name":"X","last_name":"X","company":"","address_1":"147 Pavilion Park","address_2":"","city":"Irvine","state":"CA","postcode":"92618","country":"US","email":"X@me.com","phone":""},"shipping_address":{"first_name":"X","last_name":"X","company":"","address_1":"147 Pavilion Park","address_2":"","city":"Irvine","state":"CA","postcode":"92618","country":"US"},"customer_meta":{"nickname":"chris","first_name":"X","last_name":"X","description":"","rich_editing":"true","comment_shortcuts":"false","admin_color":"fresh","use_ssl":"0","show_admin_bar_front":"true","locale":"","dismissed_wp_pointers":"ampforwp_subscribe_pointer","bp_xprofile_visibility_levels":{"1":"public","2":"public"},"last_update":"1486834744","wp_capabilities":{"customer":true},"wp_user_level":"0","user_social_links":{"facebook":"https:\/\/www.facebook.com\/X","twitter":"https:\/\/twitter.com\/X","linkedin":"https:\/\/www.linkedin.com\/in\/boyac\/en","google-plus":"","youtube":"","instagram":"","pinterest":""},"billing_first_name":"X","billing_last_name":"X","billing_company":"","billing_address_1":"147 Pavilion Park","billing_address_2":"","billing_city":"Irvine","billing_postcode":"92618","billing_country":"US","billing_state":"CA","billing_phone":"","billing_email":"X@me.com","shipping_first_name":"X","shipping_last_name":"X","shipping_company":"","shipping_address_1":"147 Pavilion Park","shipping_address_2":"","shipping_city":"Irvine","shipping_postcode":"92618","shipping_country":"US","shipping_state":"CA","session_tokens":{"X":{"expiration":1488238209,"ip":"98.191.202.118","ua":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/56.0.2924.87 Safari\/537.36","login":1487028609}},"last_activity":"2017-02-15 20:29:31","manageedit-shop_ordercolumnshidden":["billing_address"],"wp_dashboard_quick_press_last_post_id":"100","favorite_products":[47],"bp_latest_update":{"id":15,"content":"@greyghost Hello!"},"paying_customer":"1","wp_user-settings":"libraryContent=browse","wp_user-settings-time":"1486581066","wpseo_title":"","wpseo_metadesc":"","wpseo_metakey":"","wpseo_excludeauthorsitemap":"","wpseo_content_analysis_disable":"","wpseo_keyword_analysis_disable":"","googleplus":"","twitter":"","facebook":"","wsl_current_provider":"Facebook","wsl_current_user_image":"https:\/\/graph.facebook.com\/10210005491947321\/picture?width=150&height=150"}},"order_meta":{"ampforwp_custom_content_editor_checkbox":"","Stripe Fee":"0.68","Net Revenue From Stripe":"12.56"}}}

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
You probably could use WP Rest API instead of WooCommerce to get the post meta.
