### ISSUE TITLE
Notifications still present even after verification & TOS acceptance

### ISSUE THREAD

**Issue by BurlesonBrad** [woocommerce/woocommerce-gateway-stripe#231]
#### What I expected
The notifications to go away
The site is verified:
![apple-is-verified](https://cloud.githubusercontent.com/assets/6208757/25030469/ac37aec0-208a-11e7-97f9-f2a0690a6f6a.png)
And, _(hence)_ Apple's TOS _(of course)_ been accepted:
![stripe-notifications-for-apple-pay](https://cloud.githubusercontent.com/assets/6208757/25030546/2827a864-208b-11e7-80ca-ca80dc33a077.png)

#### What happened instead
Verified the site, notifications persist with no dismissal 

#### Steps to reproduce the issue
Open someone's site who never even realized Apple pay was an option.  Run through the motions, accept the tos in the stripe acct., snag the file, drop it like it's hot into their site, double check manually that the file is viewable even though stripe already did, open the ftp again, verify the path, decide to run through all the steps again, download the file from inside the stripe account, drop it like it's hot _(again)_, run back over to `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe`, wait a day, .............and the notifications (both) are still present

**Comment by roykho** [comment]
That notice means the API to verify the domain is not able to verify. So it is a legitimate notice.

**Comment by BurlesonBrad** [comment]
As I go looking for the triggers in the API, what might one be looking for specifically? Both are indeed verified correctly in Stripe. So where, between Stripe and WooCommerce, might the disconnect be happening?

**Comment by roykho** [comment]
Can you verify that you can make live apple pay payments?

**Comment by BurlesonBrad** [comment]
Not sure at the moment. Lemme find someone with an iPhone.

**Comment by roykho** [comment]
Closing this for now. Feel free to re-open if this is still an issue.
