### ISSUE TITLE
"Error disconnecting account" displayed on deleting test keys

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#2310]
Observed on a test store running 6.1.0 with only (developer account) test keys. When I delete the keys, I get an error message in the lower left corner. Refreshing the page works to "reset" the flow back to the beginning of onboarding:

![error](https://user-images.githubusercontent.com/1595739/151860150-5ca28ef9-f4ba-49d4-be5d-07b86ddb5a70.gif)

@joshheald also observed this recently

fyi @ctarda @malinajirka

**Comment by harriswong** [comment]
+1 I can reproduce this as well while testing the keys removal.
