### ISSUE TITLE
WPML custom permalinks + Settings Stripe WP-JSON make a 404 request

### ISSUE THREAD

**Issue by rvola** [woocommerce/woocommerce-gateway-stripe#2311]
**Describe the bug**
It is not possible to configure the Stripe Gateways extension with WPML a customize permalinks mode

**To Reproduce**
Install plugins:
* WooCommerce
* Woocomerce Stripe Gateway
* WPML Multilingual CMS
* Multilingual WooCommerce
* WPML String Translation

- Configure WooCommerce (basic)
- Configure WPML (basic) just one language
- Configure WooCommerce Multilingual (basic)

1. Then in WPML > Languages, in the "Language URL format" section
2. Enable the "Different languages ​​in directories" setting
3. Check "Use directory for default language"
4. And select "a page"
5. To safeguard
6. Then click on "Create root page"
7. Add any title
8. Save as draft or publish the page
9. Go back to WPML > Languages, in the "Language URL format" section
10. Click on "Save"
11. Follow the link to update the permalinks (in my example the format "https://wordpress.localhost/%postname%/")

The site is now operational to have urls of the type:
https://wordpress.localhost/en/checkout/
https://wordpress.localhost/fr/basket/
etc...

Go to the settings of the gateways in WooCommerce Stripe Gateway

We can no longer modify the settings or initialize the plugin because we get the message "Error retrieving settings" or/And "Error retrieving account data" or/and "Error retrieving account keys"

Looking at the console the urls of the type:
/wp-json/wc/v3/wc_stripe/settings?_locale=user returns a 404 error.

Simply deactivate WPML Multilingual CMS, configuration is possible again.

**Expected behavior**
A functional setting of the extension even with a setting of WPML

**Environment:**
 - WordPress Version 5.9.0
 - WooCommerce Version 6.1.1 or next 
 - Stripe Plugin Version 6.1.0
 - Chrome Version 97.0.4692.99

**Comment by rvola** [comment]
Hello world!
Anyone for this bug?

**Comment by ZgrK** [comment]
I have same problem with last version

**Comment by rvola** [comment]
Hi 
Still the same problem with version 6.3.0.

I must clarify to administrators that this configuration is absolutely not exotic, but common.
WooCommerce + Stripe Gateway + WPML

The use of language of the type domain.com/**fr**/ is extremely common.

Thank you for your return, I have 10 sites blocked in version 5.7 for the moment.

**Comment by takaacstamaas** [comment]
I have the exact same issue :(

**Comment by ZgrK** [comment]
Still same issue

**Comment by rvola** [comment]
Part of the solution is here: https://wpml.org/forums/topic/urgent-woocommerce-multilingual-breaks-stripe-gateway-in-woocommerce/

However the problem is caused by WPML and not Stripe.
Too bad to have broken a plugin using native features such as fields provided by WooCommerce for a JS/API solution that does not provide any additional comfort.

**Comment by rvola** [comment]
the problem has been fixed with the WPML WooCommerce Multilingual 5.0.0 version.
It's fully functional
https://wpml.org/version/woocommerce-multilingual-5-0-0/
