### ISSUE TITLE
Enable Stripe as a payment method after connecting account

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce-gateway-stripe#2314]
**Describe the bug**

After completing on-boarding and connecting an account, Stripe does not appear to be enabled for card payments by default. It requires an additional action.

For more details, and a demo see here: p58i-c2s-p2#comment-53598

**To Reproduce**

Steps to reproduce available in the video here: p58i-c2s-p2 starting at 18 minutes 48 seconds in.

**Expected behavior**

Stripe would be enabled and ready to accept payments after connecting an account.

**Comment by dechov** [comment]
@lovo-h has addressed this in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1569 – is it correct that it should enable it for both the Connect / OAuth flows and the manual input? And in the latter case, would it be worth verifying that the keys work before auto-enabling the gateway?

**Comment by lovo-h** [comment]
> And in the latter case, would it be worth verifying that the keys work before auto-enabling the gateway?

Should we extend this to storing the account keys, as well? That is, would it be worth verifying that the keys are valid before storing them (and auto-enabling the gateway)?
