### ISSUE TITLE
UPE: Payment intent sent upon Checkout page load

### ISSUE THREAD

**Issue by tijosh** [woocommerce/woocommerce-gateway-stripe#2315]
**Describe the bug**

When using the New Checkout Experience / UPE, the extension sends a payment intent to the Stripe API immediately upon page load, before any customer billing information or credit card is added to the checkout form. This results in unwanted `Incomplete` payments listed in the Stripe dashboard.

Reported 4752785-zen and https://wordpress.org/support/topic/incomplete-transactions-sent-to-stripe/

**To Reproduce**
1. Enable UPE/New Checkout Experience in Stripe settings
2. Add a product to cart, navigate to checkout page
3. Check Stripe dashboard and see `Incomplete` payment for amount of order
4. `woocommerce-gateway-stripe` logs show details of payment intent sent

**Expected behavior**

Payment intent sent after checkout form is submitted.

**Screenshots**

![image](https://user-images.githubusercontent.com/35117248/152654837-ed8f30a5-fa85-4b81-b254-f77d01113773.png)

![image](https://user-images.githubusercontent.com/35117248/152654841-cc183d2e-ecc0-43d2-aff6-32393f16b528.png)

**Environment (please complete the following information):**
 - WordPress Version - 5.9
 - WooCommerce Version - 6.1.1
 - Stripe Plugin Version - 6.1.0
 - Browser [e.g. chrome, safari] and Version - all

**Comment by joashrajin** [comment]
+1 at 5639931-zd-woothemes

**Comment by rossviviano** [comment]
37995876-hc

**Comment by fetenlakhal** [comment]
5921616-zd-woothemes

**Comment by anastas10s-afk** [comment]
6667654-zd from what I gather

**Comment by rossviviano** [comment]
7643406-zen

**Comment by diegocurbelo** [comment]
The new Deferred Intent + Split PE implementation in 8.0.0 no longer creates an intent on page load.
