### ISSUE TITLE
Chrome throwing warning in debug tool which says basic card payment method is deprecated.

### ISSUE THREAD

**Issue by daniyalahmadk** [woocommerce/woocommerce-gateway-stripe#2319]
**Describe the bug**
Chrome debug tool showing deprecation warning about the basic card. The “basic card” is a payment method that is typically built into the browser to help users easily enter credit card numbers without remembering and typing them.

`[Deprecation] The 'basic-card' payment method is deprecated and will be removed in M100, around March 2022.`

This warning is coming from the stripe JS file which is loading from Stripe servers.

**To Reproduce**
1. Go to any website where the Stripe extension is set up.
2. Access the debug tool and under the issues tab, we will be able to see this warning.

**Expected behavior**
It seems like Stripe is thinking to remove this feature so this warning should go away when they remove that feature.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/13753012/153454439-adafab75-327f-4187-8f04-72576ec04758.jpg)

**Environment (please complete the following information):**
 - WordPress Version: 5.9
 - WooCommerce Version: 6.2.0
 - Stripe Plugin Version: 6.1.0
 - Browser [e.g. chrome, safari] and Version: Chrome

**Additional context**

[Sunsetting the "basic-card" payment method in the Payment Request API](https://blog.chromium.org/2021/10/sunsetting-basic-card-payment-method-in.html)

**Comment by dougaitken** [comment]
Hey @daniyalahmadk 

I'm going to close this as that "affected resource" is a Stripe hosted JS file so not something we have control over. 

Thanks,
