### ISSUE TITLE
Payments accepted on checkout does not show

### ISSUE THREAD

**Issue by SirDarcanos** [woocommerce/woocommerce-gateway-stripe#2324]
**Describe the bug**
The section "Payments accepted on checkout" in WooCommerce > Settings > Payments > Stripe does not show anymore.

**To Reproduce**
1. Go to WooCommerce > Settings > Payments > Stripe
2. See error

**Expected behavior**
Show the payment accepted.

**Screenshots**

![](https://d.pr/i/rieYit+)
**Image Link**: https://d.pr/i/rieYit+

**Environment (please complete the following information):**
 - WordPress Version: Latest
 - WooCommerce Version: Latest
 - Stripe Plugin Version: Latest

[4818207](4818207-zd-woothemes)

**Comment by SirDarcanos** [comment]
Reported in 34416779-hc as well

**Comment by rafaelzaleski** [comment]
I cannot reproduce this on:

- WordPress 5.9.2
- WooCommerce 5.3.1
- WooCommerce Stripe Gateway 6.3.0
- Active theme: StoreFront

Please recommend a [conflict test](https://woocommerce.com/document/how-to-test-for-conflicts/) to the site owner to investigate if other plugins or themes are causing this issue. 
They can also check on the Stripe account if there is anything wrong with enabled payment methods on the account.
