### ISSUE TITLE
Occasional manual capture method despite plugin settings

### ISSUE THREAD

**Issue by theandrew168** [woocommerce/woocommerce-gateway-stripe#2335]
Firstly, thanks for the great plugin and hard work being done!

**Describe the bug**
A small number of payment intents (maybe 10% or so) are reaching Stripe with `"capture_method": "manual"` despite ensuring that the setting "Issue an authorization on checkout, and capture later" is NOT enabled. When this occurs, the orders are sitting on-hold until someone updates their status in WooCommerce (causing the authorized payment to then be captured).

**To Reproduce**
I'm not sure if there is a guaranteed way to reproduce this issue. I suppose I'm really just wondering if there is some other reason that a PaymentIntent would get sent over to stripe with a manual capture method? Most payment intents created by this plugin _do_ have an automatic capture method which is what we want.

**Expected behavior**
I would expect that ALL payments sent over to Stripe would have `"capture_method": "automatic"` because of how the plugin is configured.

**Environment:**
 - WordPress 5.9.3
 - WooCommerce 6.3.1
 - WooCommerce Stripe Gateway 6.3.0
 - WooCommerce Memberships 1.22.7
 - WooCommerce Shipping and Tax 1.25.25

**Comment by kgeorgee** [comment]
5237473-zen

**Comment by dougaitken** [comment]
Hey @theandrew168 

> I suppose I'm really just wondering if there is some other reason that a PaymentIntent would get sent over to stripe with a manual capture method?

I've never seen this before, and aside from the example above, I didn't know this was possible. 

Why is it happening? I'm unsure but we'd need to have reproducible steps before the team were able to tack this. 

I know that isn't the answer you want to read, especially after waiting over three months for a reply so if you've seen any other patterns, please do share them with us.

Thanks

**Comment by theandrew168** [comment]
@dougaitken Thanks for the response and no worries about the delay. I knew that there probably wouldn't be many actions to take without a repro. I figured I'd at least check upfront and see if there was some hidden setting or logic path that'd cause an intent to get sent with `"capture_method": "manual"`.

This issue hasn't reappeared in recent months so I'd be okay to call it a fluke. I appreciate the response nonetheless!
