### ISSUE TITLE
Empty box for express checkout

### ISSUE THREAD

**Issue by tarunvijwani** [woocommerce/woocommerce-gateway-stripe#2336]
## Describe the bug

After disabling the express checkout option, the Checkout block is displaying the Empty box for express checkout. 

<img width="695" alt="image" src="https://user-images.githubusercontent.com/11503784/161778910-290be537-29c6-49da-b7ed-6000bea636f7.png">

## To reproduce

1. Install and activate WooCommerce Stripe
2. Enable the Express checkout payment method. 
3. Visit the Checkout block page. Express checkout will be visible. 
4. Deactivate the Express checkout payment. 
5. Visit the Checkout block page. It will display the empty box for express checkout

## Expected behaviour

The express checkout box should not be visible after disabling the express checkout payment method.

**Comment by opr** [comment]
I'll add this to the data stores project as a bug to look out for - we should be able to solve this when moving to data stores.

**Comment by EvanDotPro** [comment]
This is fixed by #2337, which I've just rebased on the latest develop. Hopefully it will be reviewed and merged soon!
