### ISSUE TITLE
Incorrect/Contradictory UX when partially refunding authorized, uncaptured orders

### ISSUE THREAD

**Issue by melek** [woocommerce/woocommerce-gateway-stripe#2338]
**Describe the bug**
Right now, a partial refund on an authorized, uncaptured order results in the whole order being cancelled. While we've [made it somewhat more clear](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1481) to the merchant that this happens when they attempt that partial refund via notes, the refund button remains unchanged. This is bad UX, because there are contradictory messages to the user about how the feature works, and the most likely places for the user to look lead them to cancelling orders with the full expectation they will be partially refunded.

**To Reproduce**
1. Place a test order with Stripe when capturing is off.
2. Edit the order and click 'Refund'. 
3. The button will say 'Refund X.XX', instead of a correct message.

**Expected behavior**
I expect the button text/UI to match the actual behavior. Here are some options that would make for a predictable experience when partially refunding uncaptured orders:

* (Less work) When refunding uncaptured orders, options to refund anything but the whole amount are disabled and red text appears explaining that for partial refunds, the order must be set to 'processing' / captured first. 
* (More work) While the refund amount is under the order total, the button reads 'Capture payment and refund $X.XX via Stripe', and then that sequence is performed for the user. When the full amount is entered, it reads 'Cancel Order' or a similar message that communicates that the order will be cancelled, not refunded. 

**Screenshots**
![Screenshot](https://d.pr/i/F9kejQ+.png)
*If you do not see the image, please [click here](https://d.pr/i/F9kejQ).*

**Additional context**
* This was suggested previously, but I couldn't find an actual issue for it: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/757#issuecomment-509107961
* 35138597-hc

To begin, I set this to 'Medium' priority. The reason is that businesses which authorize first, then capture are much less common than capture first; that said, I think that the risk of accidentally cancelled an order instead of partially refunding may lead to embarrassing and unprofessional situations for merchants. I don't know of any other UX flow where a control says it does one thing, and you have to read the order notes to know what other, different thing will happen when you hit the button.

**Comment by EvanDotPro** [comment]
@melek What if for uncaptured orders, the refund button in the screenshot below is simply replaced with a "Cancel Order" button? Perhaps along with some sort of a note like you suggested along the lines of "Refunds are only available after payment has been captured." or similar.

![](https://caps.evan.pro/4d60a0.png)

**Comment by EvanDotPro** [comment]
@melek So, I started working on implementing what I said above, but had a thought...

UX-wise, would it make more sense to simply just _not show_ the refund button (nor a cancel button in its place as I suggested) at all for orders where payment hasn't been captured yet? Hear me out... There's already a UI mechanism for cancelling orders that merchants are familiar with. I feel like having a button that sometimes says cancel and sometimes says refund will negatively impact new users' ability to memorize where things are in the interface and just add one more UI nuance they need to think about for no actual benefit (at least for those merchants who use the capture later option).

So I'm now leaning towards simply hiding the refund button altogether and _only_ showing a notice like you originally suggested. Something like:

> ℹ️ Refunding is unavailable because funds have not been captured for this order.

Thoughts?

**Comment by melek** [comment]
@EvanDotPro Thanks for working on this!

I think that your message in lieu of a 'Cancel Order' / cancel authorization button is just fine. That corrects the basic problem that the current UI lets users think they can refund these orders rather than cancel them, but they can't (since they never collected payment).

The notice may even be better than a cancel button, since the goal of any change should be to help a user understand _why_ they can't perform the usual refund process. I'd consider using the same or similar language that is in the note:

> ℹ️ Refunding via Stripe is unavailable because funds have not been captured for this order. Process order to take payment, or cancel to remove the pre-authorization.

Note that the `Attempting to refund the order in part or in full will release the authorization and cancel the payment.` part of the existing note which is added may need to be updated. 

Regarding totally removing the refund button, I think the UI should empower the user to correct mistakes / issue manual refunds. Maybe you'd have to click a button to enable a manual refund button to show. For instance, let's just suppose for a moment that the order's state in WooCommerce is not accurate (maybe the database was restored to a point after the payment was authorized, but before it was captured). In this event, a 'Manual' refund may be needed. 

I haven't tested how Stripe currently handles something like that - maybe 'capturing' and already captured payment isn't a problem, but I do want to be aware that every time a button is totally hidden that can lead to additional confusion.

What do you think?

**Comment by EvanDotPro** [comment]
@melek I've opened a [pull request](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2423) for this. Please feel free to review and let me know what you think.
