### ISSUE TITLE
Clarify usage of Apple/Google Pay and custom required fields on checkout page

### ISSUE THREAD

**Issue by therealgilles** [woocommerce/woocommerce-gateway-stripe#2343]
**Is your feature request related to a problem? Please describe.**
It is not clear if custom required fields are compatible with the Apple/Google Pay Express Checkout flows on the checkout page.

**Describe the solution you'd like**
It would be great to have documentation on whether this is supported and if so, how (does it require custom validation code? what hooks are available?).

If it is not supported, the Express Checkout buttons should not show if there are custom required fields.

**Additional context**
See https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2169.

**Comment by helgatheviking** [comment]
I believe you could use the [`wc_stripe_show_payment_request_on_checkout` filter](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-payment-request.php#L947)

**Comment by therealgilles** [comment]
@helgatheviking Thanks for the pointer. This is not quite my request though.

**Comment by Brianmitchtay** [comment]
Seeing a user come through with this issue in 5743171-zen. 

IMO the fact that express checkout buttons are still shown when custom fields are in place which will make them fail should be considered a bug, not an enhancement.

**Comment by samholguin** [comment]
Any joy with this? We have had to make our custom fields not required

**Comment by shrutimoorthy** [comment]
Seen in 6927184-zen.

**Comment by StefsterNYC** [comment]
Hey @dougaitken hope you're well bro. We ran into an issue as well where we have two custom hooked fields that have the required class attached and both are coming back as erroring even though they're filled out.

**Comment by kaushikasomaiya** [comment]
7406565-zen

**Comment by Mayisha** [comment]
Thanks for flagging this issue. We can reproduce this and we have planned to hide the GooglePay/ApplePay buttons when a custom required field is present.

**Comment by element-software** [comment]
I too am having a similar issue - we have added some custom fields on checkout which are unchecked/false by default, but if the user checks out with Google/Apple Pay, they have no ability to check these fields in the Google/Apple Pay checkout flow.

Adding custom fields would be great and would keep things consistent. We cannot make the fields optional as one of the fields is a checkbox asking the user if they'd like to claim gift aid (the website is a charity non-profit website). By default, any payments made with Google/Apple Pay have reclaim gift aid as false and the charity is losing out.

Any help would be appreciated on this.
