### ISSUE TITLE
Support WordPress 6.0

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#2347]
### Description
Test and validate the plugin compatibility with WordPress 6.0.

Adding `WordPress 6.0-RC1` to the Compatibility workflow testing matrix (in [this PR](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2346)) results is one error:
https://github.com/woocommerce/woocommerce-gateway-stripe/runs/6356923902?check_suite_focus=true

```
There was 1 error:

1) WC_Stripe_UPE_Availability_Note_Test::test_get_note
Undefined property: stdClass::$primary

/home/runner/work/woocommerce-gateway-stripe/woocommerce-gateway-stripe/tests/phpunit/test-class-wc-stripe-upe-availability-note.php:27
```

**Expected behavior**
All tests should pass and the [critical flows](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Critical-flows) should work.

**Comment by EvanDotPro** [comment]
For context, this is a compatibility issue with WC 6.5.0, not WP 6.0.

The "primary" property [was removed](https://github.com/woocommerce/woocommerce-admin/pull/8474/files#r829672400) from `Automattic\WooCommerce\Admin\Notes\Note` in WC 6.5.0.

Fixed in #2348.
