### ISSUE TITLE
PayNow Singapore payment method not an option in this plugin

### ISSUE THREAD

**Issue by Shahbazhassan** [woocommerce/woocommerce-gateway-stripe#2378]
#### Affected ticket(s)
Local Payment Method not showing. I'm using Stripe inline form with saved card function but local payment methods that i enable in my stripe account not showing. My Store Currency is SGD.

#### What I expected
I'm expecting all my local payment methods that i enabled in my Stripe Account will show up on WooCommerce checkout.

#### What happened instead
Only Card option is showing. No local payment method appearing that i enabled in my stripe dashboard.

#### Steps to reproduce the issue
1. Go to https://www.bettervision.com.sg/.
2. Add Items in cart from "Sunglasses" Category
3. Go to checkout
4. You will see only Credit Card but no PayNow. Whereas i've already enabled PayNow that's a local payment methd in Singapore.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by bmccotter** [comment]
Hi @Shahbazhassan - appreciate the feedback! We do not yet have PayNow built into the Stripe plugin for WooCommerce. We will take your feedback and evaluate how and when we can implement it into our roadmap.

**Comment by solstudioim** [comment]
Another merchant in 5427028-zd-woothemes using WooCommerce Stripe gateway enquired about PayNow payment method integration.

**Comment by rynaldos** [comment]
Another merchant asking in 5461916-zd-woothemes

**Comment by zdenys** [comment]
Another merchant in 5703446-zd-woothemes asking about PayNow option in Stripe.

**Comment by dougaitken** [comment]
Hi everyone,

For Feature Requests, we review the [Stripe Feature Request Portal](https://woocommerce.com/feature-requests/stripe/) for product enhancements.

There currently isn’t an existing Feature Request related to this scenario, so please do create one so others can add their vote.
