### ISSUE TITLE
StripeLink: Check input field styles

### ISSUE THREAD

**Issue by dpaun1985** [woocommerce/woocommerce-gateway-stripe#2384]
Stripe will introduce some missing styles for Link when using `payment_element_beta_1` meta. 
We need to check if all elements are in good shape when the styles will be present.

**Comment by dpaun1985** [comment]
This item is blocked until Stripe will introduce the styles for `payment_element_beta_1`

**Comment by kalessil** [comment]
The discussion thread: p1657209230573929-slack-C9976E5MJ

**Comment by dpaun1985** [comment]
The styles were added, so we can close this issue.
