### ISSUE TITLE
Notices during renewal: id and customer_user were called incorrectly

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce-gateway-stripe#239]
#### Affected ticket(s)

N/A

#### What I expected

No notices during subscription renewal.

#### What happened instead

I got notice while testing https://github.com/woocommerce/woocommerce-gateway-stripe/pull/237.

```
PHP Notice:  id was called <strong>incorrectly</strong>. Order properties should not be accessed directly. Backtrace: require_once('wp-admin/admin.php'), do_action('admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_AdminView->maybe_execute_action, ActionScheduler_QueueRunner->process_action, ActionScheduler_Action->execute, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, WC_Subscriptions_Manager::prepare_renewal, wcs_create_renewal_order, apply_filters('wcs_renewal_order_created'), WP_Hook->apply_filters, WC_Gateway_Stripe_Addons->delete_renewal_meta, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.0.) in /srv/www/wordpress-default/wp-includes/functions.php on line 4137
```

```
PHP Notice:  customer_user was called <strong>incorrectly</strong>. Order properties should not be accessed directly. Backtrace: require_once('wp-admin/admin.php'), do_action('admin_init'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_AdminView->maybe_execute_action, ActionScheduler_QueueRunner->process_action, ActionScheduler_Action->execute, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, WC_Subscriptions_Payment_Gateways::gateway_scheduled_subscription_payment, WC_Subscriptions_Payment_Gateways::trigger_gateway_renewal_payment_hook, do_action('woocommerce_scheduled_subscription_payment_stripe'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Gateway_Stripe_Addons->scheduled_subscription_payment, WC_Gateway_Stripe_Addons->process_subscription_payment, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.0.) in /srv/www/wordpress-default/wp-includes/functions.php on line 4137
```

#### Steps to reproduce the issue

1. Sign up for subs
2. Change the default payment method and remove previous card
3. Run scheduled action for renewal

-------------------

- [x] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

**Comment by fellars** [comment]
Should I still be getting this error on version 4.1.9 ??

full error:
customer_user was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Stripe_Subs_Compat->process_payment, WC_Gateway_Stripe->process_payment, WC_Stripe_Payment_Gateway->process_response, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_processing'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_Customer_Processing_Order->trigger, WC_Email->get_content, WC_Email_Customer_Processing_Order->get_content_html, wc_get_template_html, wc_get_template, include('/plugins/woocommerce/templates/emails/customer-processing-order.php'), do_action('woocommerce_email_order_meta'), WP_Hook->do_action, WP_Hook->apply_filters, Openside_Woocommerce->opwc_customer_processing_order_email, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0
