### ISSUE TITLE
WC session cookie is being set on product pages even when not loading scripts. Cache buster.

### ISSUE THREAD

**Issue by essentique** [woocommerce/woocommerce-gateway-stripe#2392]
**Describe the bug**
A woocommerce session cookie is set when on a product page even though prbs is disabled on it and the wc_stripe_load_scripts_on_product_page_when_prbs_disabled filter returns false. 

**To Reproduce**

1. Disable express checking on product pages.
2. add_filter( 'wc_stripe_load_scripts_on_product_page_when_prbs_disabled', '__return_false' );
3. Go to any single product page.
4. Inspect the network requests in chrome devtools
5. See the request headers and notice the wc session cookie is set, even though scripts are not loaded
6. Subsequent reload of the page results in cache MISS (or BYPASS) because of the presence of the cookie

**Expected behavior**
Since there is a filter already for 'wc_stripe_load_scripts_on_product_page_when_prbs_disabled', it should not set the cookie if the filter returns false. Setting the cookie essentially makes the product page non-cacheable for no good reason. Having something like this in class WC_Stripe_Payment_Request would be ideal:

```
        public function set_session() {
                if ( ! $this->is_product() || ( isset( WC()->session ) && WC()->session->has_session() ) ) {
                        return;
                }

                if ( WC_Stripe_Helper::should_load_scripts_on_product_page() )
                        WC()->session->set_customer_session_cookie( true );
        }
```
This way, the session cookie only gets set when the scripts are also loaded.

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version 6.0.1
 - WooCommerce Version 6.7.0
 - Stripe Plugin Version 6.4.3
 - Browser [e.g. chrome, safari] and Version Chrome Version 103.0.5060.114 (Official Build) (x86_64)

**Additional context**
When express checkout is disabled on product pages, some merchants may want to get optimum performance on those pages, especially for google indexing and ranking (SEO). To do that, the existing wc_stripe_load_scripts_on_product_page_when_prbs_disabled filter was put in place to select whether to load js scripts and set stripe cookies or not. Which is great, and we merchants can control that. But unfortunately, the wc session cookie is set regardless. This means that the pages will bypass the proxy cache in front of the service.

**Comment by dougaitken** [comment]
Hey @essentique - can you confirm which specific cookie or cookies are being set, please? You mention `wc session cookie`, that could be a core WooCommerce cookie rather than from the Stripe payment gateway plugin but I wanted to confirm.

**Comment by essentique** [comment]
Yes, the core woocommerce session cookie. The plugin is actually setting that via the `WC()->session->set_customer_session_cookie( true );` call above.

**Comment by dougaitken** [comment]
Sorry @essentique I'm having trouble fully understanding your ask - are you looking for a way in which using the filter you've mentioned above would **_also_** stop the core WooCommerce cookie from being set?

**Comment by essentique** [comment]
Yes. There's no reason to set the core wc session cookie if the scripts are not being loaded (i.e., there is no express payment functionality on the page). The filter is a way to control whether the scripts should be loaded. So, if the filter returns false, there's also no need to set the wc cookie. 

The main point is, for some of us, who decide not to load any stripe payment functionality on our single product pages, we do not want the core wc cookie to be set. IOW, we would like the plugin to just leave the product page alone and not mess with it. Hope that helps. Thanks.

**Comment by michiphp** [comment]
I'm having the exact same problem, when I deactivate the plugin Stripe it is working as expected and not setting any session cookie. Is there a solution to this? I feel this is a fairly new behaviour because in the past I was able to cache my single product pages without any problems.

**Comment by essentique** [comment]
I'm fairly new to the plugin and it's been like this since I've been using it. Looks like a year or so ago, the filter mentioned here was put in to disable loading the scripts. I'm not entirely sure why they added a new filter; seems to me that if express checkout is disabled on any page (product or cart) the plugin should just leave the page alone. You don't need another filter for that. But at least we have that control now.

Today, even if you disable express checkout on your page, the plugin still loads the scripts, modifies the dom, sets stripe cookies, *and* sets the core wc session cookie. If I say I don't want stripe on my product pages, I expect they just leave the page alone. 

To answer your question, as to whether there is an existing solution for this, no there isn't. Unless you want to:

1. add_filter( 'wc_stripe_load_scripts_on_product_page_when_prbs_disabled', '__return_false' );
2. modify `class-wc-stripe-payment-request.php` and add the if-clause shown above

which I had to do to get my cache back.

**Comment by essentique** [comment]
So, any word on this? Is there a chance to get this in? It's super important for me to have a functioning cache which I pay extra for. Right now, after every release I have to make this mod to your code. I really rather not have to do that, but I will have to unless you fix it or I find something else. 

I am sure this is important to many, so it would be really helpful if your plugin could coexist with reverse proxies or cdn caches.

Thanks.

**Comment by rajaamanullah72** [comment]
Do you want to read the details of how woocommerce sessions and cookies work?

Only for developers and technical persons. 

https://rajaamanullah.com/how-to-use-woocommerce-sessions-and-cookies/

**Comment by farrelsari** [comment]
I'm bumping this request. Have same problem with varnish cache on WordPress VIP. When user visits single product page wc session cookie is set and further user requests becomes uncacheable. User didn't add any product to the cart yet. As @essentique said this is big deal. You are breaking cache for many people.

**Comment by dixonl90** [comment]
Just confirming I have also ran into this issue. I'd rather not modify plugin files directly, please include the proposed code change in the next release. Happy to submit a PR if it'll get it merged faster.

**Comment by jjcoffee** [comment]
This is actually a major privacy/GDPR issue on Kinsta hosted sites, as their default caching setup doesn't bypass on product pages if the wp_woocommerce_session cookie is set. This leads to customer data added on the checkout leaking across sessions (i,e. a random customer will see address details from another customer when they load the checkout page).

Seems the same issue was brought up before (#1248 ).

**Comment by joel-gigged** [comment]
If anyone wants to hotfix this without editing core files, you can manually unhook the set_session function like this:

```
add_action('template_redirect', function(){
	global $wp_filter;

	// set_session is hooked in WC_Stripe_Payment_Request, but we can't use remove_action
	// as WC_Stripe_Payment_Request hooks using $_this, which is in a private variable
	foreach ( $wp_filter['template_redirect'][10] as $key => $hook ) {
		if ( strpos( $key, 'set_session' ) !== false && 
			!empty( $hook['function'] ) && !empty( $hook['function'][0] ) &&
			($hook['function'][0] instanceof WC_Stripe_Payment_Request) 
		) {
			unset( $wp_filter['template_redirect']->callbacks[10][$key] );
			break;
		}
	}
	
}, 1 );
```

Note that you need to disable payment request buttons on product pages.

**Comment by dougaitken** [comment]
Closing this in favour of #1248 as has been mentioned above.
