### ISSUE TITLE
Synchronized Subscriptions Requiring Shipping Can't Be Purchased with Apple Pay/Google Pay

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-gateway-stripe#2395]
Copy of https://github.com/Automattic/woocommerce-payments/issues/3742 as the same issue exists in Stripe.

**Describe the bug**

If a customer tries to purchase a synchronized subscription that requires shipping with Apple Pay or Google Pay, the transaction will be canceled and an "Invalid recurring shipping method" notice added.

This works as expected for virtual subscription products.

**To Reproduce**
1. Enable the WooCommerce Subscriptions extension on a site using WooCommerce Stripe
2. Create a simple subscription product with "Synchronise renewals" set for a day other than today.
3. Add the item to the cart and try to pay with Apple Pay or Google Pay.
4. Notice how the transaction is canceled and the error message appears.

![image](https://user-images.githubusercontent.com/2275145/181660857-fecc17f9-4784-484e-a6ef-3f63d47ad8d0.png)

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**

Inside our [`allowed_items_in_cart()`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8e54228bfbcbf4c877336e37854f4a9dc9d1cae5/includes/payment-methods/class-wc-stripe-payment-request.php#L577) function we have code which handles a similar issue for Trial Subscriptions but I think we missed this for Synced Subscriptions.

I've added some additional notes to the same wcpay issue that might be relevant to fixing this in Stripe. See https://github.com/Automattic/woocommerce-payments/issues/3742#issuecomment-1198763191

**Comment by marklifeboxfood** [comment]
Hi Team,

Thank you for looking into this bug. Naturally I'm very keen on hearing about any progress, as the ability to use Apple Pay or Google Pay for our subscription service would lead to significantly higher sales conversions as we've had to disable these payment methods across the board for all our sub and non-sub products.

I know always difficult to say, but do you have any idea of when this might be included in an upcoming sprint? 

Great to see this being tracked.

**Comment by WildPress** [comment]
Hey guys, with Black Friday and Christmas coming up, I'm curious to know if you anticipate a resolution anytime soon, please?

**Comment by joaodante** [comment]
5189645-zen

**Comment by marklifeboxfood** [comment]
Hi Team, as an alternative could you please suggest if there is a way to hide the Express Payment options if a certain product type is in the cart / product page? In this case, a Synchronised Subscription product. It would be great to be able to show the button for all the other products on our site, but not show for these products. Right now we have to disable it globally and that's costing us conversions across the board. Thank you so much for your consideration

**Comment by ricardo** [comment]
Hi all 👋,

As an update, unfortunately, we can't provide compatibility with synchronized renewal subscriptions as of now.

Still, as an intermediary approach, you can use the following filters to disable express checkouts for synchronized subscription products only:

```php
/**
 * Hide express checkouts (Apple Pay/Google Pay) for synchronized
 * subscriptions on the cart and checkout pages.
 *
 * @param bool $should_show_payment_request - Defaults to true.
 *
 * @return bool
 */
function hide_payment_request_for_synced_subscription( $should_show_payment_request ) {
	if ( class_exists( 'WC_Subscriptions_Synchroniser' ) && WC_Subscriptions_Synchroniser::cart_contains_synced_subscription() ) {
		$should_show_payment_request = false;
	}
	return $should_show_payment_request;
}

/**
 * Hide express checkouts (Apple Pay/Google Pay) for synchronized
 * subscriptions on the product page.
 *
 * @param bool $should_hide_payment_request - Defaults to false.
 * @param object $product - WC product.
 *
 * @return bool
 */
function hide_payment_request_for_synced_subscription_on_product_page( $should_hide_payment_request, $product ) {
	if ( ! empty( $product ) && class_exists( 'WC_Subscriptions_Synchroniser' ) && WC_Subscriptions_Synchroniser::is_product_synced( $product ) ) {
		$should_hide_payment_request = true;
	}

	return $should_hide_payment_request;
}

add_filter( 'wc_stripe_show_payment_request_on_cart', 'hide_payment_request_for_synced_subscription', 10, 1 );
add_filter( 'wc_stripe_show_payment_request_on_checkout', 'hide_payment_request_for_synced_subscription', 10, 1 );
add_filter( 'wc_stripe_hide_payment_request_on_product_page', 'hide_payment_request_for_synced_subscription_on_product_page', 10, 2 );
```

You can add the filter above using plugins such as [Code snippets](https://br.wordpress.org/plugins/code-snippets/).

Meanwhile, I've bumped the priority for this issue, so our team can pay closer attention to it for the next releases.

**Comment by marklifeboxfood** [comment]
Brilliant thank you. It works as expected! 
FYI - the product page code does not seem to work when using a Variable Subscription product, but I used another method to hide this in that case. 

`add_filter( 'wc_stripe_hide_payment_request_on_product_page', function( $hide, $post ) { if ( $post->ID === 259133 ) { // Change this to the Product ID that you want to hide return true; } return $hide; }, 10, 2 );`

**Comment by gabriel-fuentes** [comment]
The code worked like a charm for the user in 5189645-zen 🙂

**Comment by solstudioim** [comment]
Reported in 37060230-HC

**Comment by thuautp** [comment]
also reported in 42511973-hc

**Comment by mrbrack** [comment]
Hey, 

Is there any update on this bug? Desperate to get Apple Pay and Google Pay integrated as the customer delivers locally so has no choice but to align payments and ship. 

Thanks,
Nigel

**Comment by ryanr14** [comment]
I know this issue has been open for about a year. Any chance to assign it some priority and find a fix?

6383158-zen

**Comment by thenbrent** [comment]
> I know this issue has been open for about a year.

@ryanr14 the reason it was open so long is due to staffing of the Stripe extension, which changed just 2 weeks ago (P2 reference here: pLwCt-cvk-p2).

As of two weeks ago, we now have folks working on the high priority issues (of which this is one, but there are also 30 others in the Stripe queue, and others for the queues of other extensions.) That means you should see see more progress soon as we work through those 30 issues.

**Comment by ryanr14** [comment]
That's great news, and thanks for the update @thenbrent!

**Comment by mrbrack** [comment]
Hey,

It is great to hear that the Stripe bugs are being worked through. Do you have an update on this one? 


Many thanks!

**Comment by thenbrent** [comment]
@mrbrack no update on this one yet unfortunately. Recent security issues have consumed much of the team's Stripe efforts over the last month and there are other issues higher in priority ahead of this one for Stripe.
