### ISSUE TITLE
6.5.0 Stripe Link payment method option in admin - I'm not seeing it...

### ISSUE THREAD

**Issue by user-1138** [woocommerce/woocommerce-gateway-stripe#2396]
**Describe the bug**

> *** Changelog ***
> 
> = 6.5.0 - 2022-07-28 =
> * Add - Stripe Link: Add beta headers for Stripe server requests
> * Add - Stripe Link payment method option in admin
> * Add - Stripe Link payment method on checkout form
> * Add - Stripe Link payment method on blocks checkout form

Just upgraded (Dev/Staging/Prod) and I'm not seeing any of it.

**To Reproduce**
1. Go to 'WP Dashboard > WooCommerce > Settings > Payments'
2. Ensure 'Stripe - Credit/Debit Card' payment option is enabled, click 'Manage'.
3. Then under the 'Express checkouts' section, only the 'Enable express checkouts' tick box is displayed with Stripe, Apple, and Google's terms of use.

**Expected behavior**
I was expecting new/separate 'Apple Pay / Google Pay' and 'Stripe Link' tick boxes, like the WooCommerce Payments plugin has - [Shown here](https://woocommerce.com/document/payments/woocommerce-payments-stripe-link/#section-1).
And I cannot find a Stripe Link payment method option anywhere else in admin.

**Environment (please complete the following information):**
 - WordPress Version 6.0.1
 - WooCommerce Version 6.7.0
 - Stripe Plugin Version 6.5.0
 - Firefox 91.12.0esr (64-bit)
 - Any other plugins installed (a bunch)

**Additional context**
I couldn't find any reference to Link payments availability by region (e.g. [https://link.co/en-au](https://link.co/en-au), [https://support.stripe.com/questions/adding-link-to-your-site](https://support.stripe.com/questions/adding-link-to-your-site)). This site/store is based in Australia, so I'm not sure if something like that is a factor, or if I'm just jumping the gun in general here (I take a Change Log 'Add' to mean 'available')?

**Comment by dougaitken** [comment]
Hey @user-1138 

> This site/store is based in Australia, so I'm not sure if something like that is a factor, or if I'm just jumping the gun in general here

You're totally correct, being based in Australia is a factor. Link by Stripe requires USD as a store and Stripe account currency  - https://stripe.com/docs/payments/link

> I was expecting new/separate 'Apple Pay / Google Pay' and 'Stripe Link' tick boxes, like the WooCommerce Payments plugin has - [Shown here](https://woocommerce.com/document/payments/woocommerce-payments-stripe-link/#section-1).

This documentation is about Link by Stripe in the [WooCommerce Payments plugin](https://woocommerce.com/payments/) specifically. 

I'll pass this to my documentation colleagues to update the [Stripe Documentation](http://docs.woocommerce.com/document/stripe) ASAP.

As I've answered your main query about why Link isn't showing for you, I'm going to mark this as Closed.

Thanks,
