### ISSUE TITLE
WooCommerce is not sending shipping Address in Stripe..

### ISSUE THREAD

**Issue by maverick14** [woocommerce/woocommerce-gateway-stripe#2408]
**Describe the bug**
Not able to test the stripe payment using woocommerce plugin. Tried different ways to pass the shipping information to the Stripe, but it is not working. 

Attached screenshot to the problem.

**To Reproduce**
1. Open https://webfortesting.in/carrymebags/ (sample)
2. Add product to cart
3. Provide Billing & Shipping information, Enter Test card details.
4. Getting failure message.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1592988/183786507-cf176b82-a9be-4c5f-baa0-c691a64ca203.png)

Shipping setting:
![image](https://user-images.githubusercontent.com/1592988/183787394-6d67d775-462c-4262-b385-0502bf522bfc.png)

**Environment (please complete the following information):**
 - WordPress Version : 6.0.1
 - WooCommerce Version 6.8.0
 - Stripe Plugin Version : 6.5.1 
 - Browser [e.g. chrome, safari] and Version : Chrome, Edge
 - Any other plugins installed : No

**Additional context**
Request log

{
  "type": "card",
  "owner": {
    "name": "mayank  billing",
    "address": {
      "line1": "test",
      "line2": "ss",
      "state": "NY",
      "city": "new york",
      "postal_code": "10005",
      "country": "US"
    },
    "email": "mayank.maverick14@gmail.com",
    "phone": "123456789"
  },
  "card": {
    "number": "************4242",
    "cvc": "***",
    "exp_month": "12",
    "exp_year": "23"
  },
  "guid": "xxxxxx-xx-xxxx-xxxx-xxxxxx",
  "muid": "xxxxxx-xx-xxxx-xxxx-xxxxxx",
  "sid": "xxxxxx-xx-xxxx-xxxx-xxxxxx",
  "pasted_fields": "number",
  "payment_user_agent": "stripe.js/1220a6236; stripe-js-v3/1220a6236",
  "time_on_page": "169293",
  "key": "pk_test_*********************************************************************************************6Gau3h"
}

**Comment by dougaitken** [comment]
_To ensure the WooCommerce team are having the most impactful work, we review older open Issues on this GitHub repository to find out what is still relevant._ 

**As there hasn’t been any activity on this Issue recently, I’m going to close this Issue.** 

To confirm if this is a bug or conflict, please first go through the WooCommerce [How to Test for Plugin and Theme Conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/) documentation.

If you feel this is still relevant and requires attention, please post a [new bug report](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/new/choose) with some more details, including the results of conflict testing.

For support requests, this is handled by the Happiness Engineers for the WooCommerce Stripe plugin. If you post this in the [WooCommerce Stripe Support Forums](https://wordpress.org/support/plugin/woocommerce-gateway-stripe/), someone will be able to offer support or advice there.
