### ISSUE TITLE
Compatibility with PHP 8.1

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#2411]
Add PHP 8.1 to the compatibility workflow matrix.

Make sure all flows work fine with PHP 8.1

**Comment by stharvey** [comment]
Is there any news when this plugin will be compatible with PHP 8.1 ?  Currently, the flow of connecting a Stripe account in the backend fails in PHP 8.1 but works with PHP 8.0.

`PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #2 must be of type array, bool given in /home/xxxxx/public_html/shop/wp-content/plugins/woocommerce-gateway-stripe/includes/connect/class-wc-stripe-connect.php:111`

Thanks

Simon

**Comment by RiaanKnoetze** [comment]
Related: https://wordpress.org/support/topic/php-error-when-connecting-to-stripe-account/#post-17850739

**Comment by 0yz** [comment]
Still doesn't work.
When connecting to my Stripe account i get a fatal error on PHP 8.2 and 8.3.
Only after reverting to PHP version 7.4 i was able to connect my Stripe account.
This is an unacceptably urgent issue that needs to be fixed asap.

```
[06-Aug-2024 12:05:37 UTC] PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #2 must be of type array, bool given in /var/www/website.xyz/wp-content/plugins/woocommerce-gateway-stripe/includes/connect/class-wc-stripe-connect.php:135
Stack trace:
#0 /var/www/website.xyz/wp-content/plugins/woocommerce-gateway-stripe/includes/connect/class-wc-stripe-connect.php(135): array_merge()
#1 /var/www/website.xyz/wp-content/plugins/woocommerce-gateway-stripe/includes/connect/class-wc-stripe-connect.php(87): WC_Stripe_Connect->save_stripe_keys()
#2 /var/www/website.xyz/wp-content/plugins/woocommerce-gateway-stripe/includes/connect/class-wc-stripe-connect.php(110): WC_Stripe_Connect->connect_oauth()
#3 /var/www/website.xyz/wp-includes/class-wp-hook.php(324): WC_Stripe_Connect->maybe_handle_redirect()
#4 /var/www/website.xyz/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 /var/www/website.xyz/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /var/www/website.xyz/wp-admin/admin.php(175): do_action()
#7 {main}
  thrown in /var/www/website.xyz/wp-content/plugins/woocommerce-gateway-stripe/includes/connect/class-wc-stripe-connect.php on line 135
```

**Comment by aheckler** [comment]
Related: https://wordpress.org/support/topic/connecting-to-stripe-causes-critical-error/
