### ISSUE TITLE
Large logos for payment methods on some themes like 2022

### ISSUE THREAD

**Issue by kaushikasomaiya** [woocommerce/woocommerce-gateway-stripe#2416]
**Describe the bug**

5490246-zen

Not sure why the style sheet `stripe-styles.css` isn't loaded on the checkout page.

This is causing logos on some themes like 2022 to appear big:

![image](https://d.pr/i/Qyn7Ij+)

**Comment by francoishvz** [comment]
Same issue here: 5622849-zd-woothemes

Possible problem is that sites have other payment gateways enabled but have Stripe disabled (so no credit card payments).

Would need to test to confirm.

**Comment by dougaitken** [comment]
Hey @kaushikasomaiya @francoishvz - have either of you been able to reproduce this accurately to understand the exact scenario causing this?

**Comment by kaushikasomaiya** [comment]
Hey @dougaitken I haven't checked in detail but will do it and get back.

**Comment by kaushikasomaiya** [comment]
@dougaitken I was able to figure out what's causing this:

If credit card (Main Stripe method) is disabled, the style that controls icon sizes doesn't get registered:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/90937a41ef1fb5683811e3e5dafbfd0a3869bcbe/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L1801

**Comment by Mayisha** [comment]
This issue was also reported in GS testing https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2876 and was fixed in PR https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2878.
