### ISSUE TITLE
Order not updating upon successful payment - Could not find order via intent ID

### ISSUE THREAD

**Issue by c7nj7n** [woocommerce/woocommerce-gateway-stripe#2419]
My issue is that a successful Stripe payment does not update the WooCommerce order (anymore, this worked a while ago), despite correct Webhook setup both on WooCommerce (the keys are valid in prod and test, the connection tests successfully). I am on version 6.6.0 that uses Stripe's API version 2019-09-09. I am using the REST API, but this should not play a role here since it's all about Stripe communicating with WooCommerce upon a successful payment.

The logs show the following:

2022-08-25T09:08:53+00:00 DEBUG 
====Stripe Version: 6.6.0====
====Start Log====
Could not find order via intent ID: pi_3Lac14GmwEXjR3ln0NECVR0W
====End Log====

I expect the Webhook to be intercepted by WooCommerce and to put the order into "Processing".

**Environment (please complete the following information):**
 - WordPress Version 6.0.1
 - WooCommerce Version 6.8.2
 - Stripe Plugin Version 6.6.0
 - Any other plugins installed: All-in-One WP Migration, Contact Form 7, JWT Auth, PayPal Zettle POS, Preview E-mails for WooCommerce, REST API Password Reset with Code, WP Mail SMTP

**Do you have any hints on how to debug this?**

All the heavy lifting is happening inside the gateway plugin, all that can go wrong is the authentication on WooCommerce or the calling of the Webhook from Stripe. I am confident that both have been setup correctly.

**Comment by c7nj7n** [comment]
I found the issue, it's been entirely on my end: I have not (anymore) updated the WooCommerce's order with Stripe's payment intent, hence there's no chance for the gateway to make a connection. My bad.

**Comment by bobhuf** [comment]
> I have not (anymore) updated the WooCommerce's order with Stripe's payment intent

How exactly do you do that? I'm facing the same error but Stripe support says this due too authorisation issues on the client's side.

**Comment by c7nj7n** [comment]
I'm using WooCommerce entirely via REST, and all I do is updating the order as follows (it all goes into the order's meta data):

`body.meta_data = [{
            'key': '_stripe_intent_id',
            'value': params.paymentIntentId,
        }];`

**Comment by bobhuf** [comment]
Not applicable to me but thanks 👍
