### ISSUE TITLE
Stripe version stuck to 2019-09-09

### ISSUE THREAD

**Issue by hay318** [woocommerce/woocommerce-gateway-stripe#2424]
Hello, I'm having trouble because my Stripe API is not getting updated. On my Stripe dashboard, I selected the latest (2022-08-01) version for the webhook. However, the payment is only going through using the default set by the plug-in (2019-09-09). Do you perhaps have any instructions on how to update the Stripe version?

**Comment by dougaitken** [comment]
Closing in favour of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1207
