### ISSUE TITLE
Cannot Erase Personal Data for WordPress users

### ISSUE THREAD

**Issue by scottbuscemi** [woocommerce/woocommerce-gateway-stripe#2439]
**Describe the bug**
There is a bug in this plugin that is preventing the WordPress "Erase Personal Content" functionality from completing: "An error occurred while attempting to find and erase personal data."

**To Reproduce**
1. A user requests for their personal data to be removed
2. Press "Erase personal data" for the user at `wp-admin/erase-personal-data.php`
3. An error message will show
**Expected behavior**
The data should be removed without issue

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version  6.0.2
 - WooCommerce Version 6.9.3
 - Stripe Plugin Version 6.7.0 
 - Browser [e.g. chrome, safari] and Version Chrome 105
 - Any other plugins installed

**Additional context**

Stacktrace:

```TypeError Unsupported operand types: string * int 
    /nas/content/live/site/wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-privacy.php:413 WC_Stripe_Privacy::is_retention_expired
    /nas/content/live/site/wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-privacy.php:385 WC_Stripe_Privacy::maybe_handle_order
    /nas/content/live/site/wp-content/plugins/woocommerce-gateway-stripe/includes/admin/class-wc-stripe-privacy.php:302 WC_Stripe_Privacy::order_data_eraser
    /nas/content/live/site/wp-admin/includes/ajax-actions.php:5130 wp_ajax_wp_privacy_erase_personal_data
    /nas/content/live/site/wp-includes/class-wp-hook.php:307 WP_Hook::apply_filters
    /nas/content/live/site/wp-includes/class-wp-hook.php:331 WP_Hook::do_action
    /nas/content/live/site/wp-includes/plugin.php:476 do_action
    /nas/content/live/site/wp-admin/admin-ajax.php:187 [main]```

**Comment by dougaitken** [comment]
Hey @scottbuscemi - so I can try and replicate this, can you give me a bit more context?

What details do you have under **WooCommerce > Settings > Accounts & Privacy > Personal data retention**

I have `N/A` set which I found after going through the process with a test user on my site, but there were no errors so I'm looking for what could be throwing this error.

Thanks,

**Comment by scottbuscemi** [comment]
This doesn't seem repro'able anymore -- not sure if a recent Woo or Stripe plugin update may have resolved. I'll re-open if this happens again and I have more info. Thanks!
