### ISSUE TITLE
Payment processing failed. Please retry.

### ISSUE THREAD

**Issue by oggy49** [woocommerce/woocommerce-gateway-stripe#2440]
Hi i have a woocommerce website that's been experiencing issues with the payment gateway. 

when i try to place an order after i put the card details in it shows me the message "Payment processing failed. Please retry." Yet it created the order in the backend with the order status set to failed from pending payment. 

If i login to an account dashboard go to orders and click pay on the order that has the order status failed the payment works fine. 
i get the following error. 

 
![7af5eb065fb8ef440ea2204a7c241d88](https://user-images.githubusercontent.com/62858604/193350619-de856cf1-3af0-4e48-a2c0-10cfa92aa80b.png)

when i speak to stripe support they said it's an issue on woocommerce and that the id for the customer doesn't exist.

**Comment by dougaitken** [comment]
Hi! Support for the WooCommerce Stripe plugin is handled by the Happiness Engineers

If you post this in the [WooCommerce Stripe Support Forums](https://wordpress.org/support/plugin/woocommerce-gateway-stripe/) someone will be able to offer support or advice there.
