### ISSUE TITLE
When a new order is placed, the PaymentIntent for previous order that had not been ultimately paid for through Stripe is updated and the new order does not get paid status.

### ISSUE THREAD

**Issue by jffaria** [woocommerce/woocommerce-gateway-stripe#2443]
A customer placed a subscription order (Woocommerce Subscriptions) and tried to pay with credit card (Stripe) but the charge was denied by the bank. The customer then proceeded to pay via another gateway (PagSeguro) and started the subscription. The subscription was then set to manual renewal as PagSeguro plugin does not support automatic renewals. Upon subscription renewal, a new order was created by Woocommerce Subscriptions and the customer chose to pay via boleto (Stripe). He was able to download the boleto and pay it in the bank, but the order was never updated with the payment. Checking in the Stripe dashboard, I saw that the payment intent for the first order (subscription parent order) was updated when the customer was trying to pay the second order (subscription renewal order) and thus the subscription was left on-hold even though the customer had paid.

**Comment by dougaitken** [comment]
Hi! Support for the WooCommerce Stripe plugin is handled by the Happiness Engineers

If you post this in the [WooCommerce Stripe Support Forums](https://wordpress.org/support/plugin/woocommerce-gateway-stripe/) someone will be able to offer support or advice there.
