### ISSUE TITLE
Stripe Connect

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce-gateway-stripe#245]
Are we planning to add Stripe Connect for split payments?

- https://stripe.com/connect

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Yes however I am not sure if that would make sense to add it to this extension as it is completely different and uses are completely different as well. So closing this for now.

**Comment by tgroshon** [comment]
I may have a use case that is narrow enough to make sense: a user has a stripe account setup as a vendor on a 3rd party's Stripe Connect platform (referred to as SC_Platform for clarity), but uses a wordpress site that is not shared with anyone else.  So additional values need to be stored/submitted but the process is almost identical.

This could happen if a eCommerce company purchases a turn-key Wordpress site from a web development firm who manages a Stripe Connect platform and sets up the customer company as a vendor on it's platform (to streamline on boarding, capture fees, etc.).

This _appears_ like it could be solved in the current system by adding (a) the ability to store the `stripe_user_id` in the normal process of configuring stripe with the key and secret and then (b) submitting that value as the  `Stripe-Account` header when making charges.

Here are some stripe docs/guides that discuss the process: https://stripe.com/docs/recipes/store-builder#connecting-accounts

That may be enough to support making payments with a stripe account _connected_ to a platform.

Does the use case and/or solution make sense and seem reasonable?

If it does, I am willing to submit a patch if someone can give me some pointers of where to start looking.
