### ISSUE TITLE
StripeLink: Update docs for UPE

### ISSUE THREAD

**Issue by dpaun1985** [woocommerce/woocommerce-gateway-stripe#2454]
Since UPE isn't a new experimental feature, we need to update the docs accordingly.
Context [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2450#issuecomment-1273088335).

**Comment by dpaun1985** [comment]
@cesarcosta99 could you please prioritize and handle this issue, since we don't have the expertise and rights to change the docs ?

**Comment by dougaitken** [comment]
For docs, please use internal Slack workflow or consult the Field Guide for Documentation updates.

**Comment by dpaun1985** [comment]
I used the internal Slack workflow to ask for docs update. thx.
