### ISSUE TITLE
Apple Pay button uses the incorrect cursor on hover

### ISSUE THREAD

**Issue by mattyza** [woocommerce/woocommerce-gateway-stripe#246]
#### Affected ticket(s)

None. Reported by Apple.

#### What I expected

A hand cursor, when  hovering over the Apple Pay button.

#### What happened instead

A standard text cursor.

#### Steps to reproduce the issue

Hover over a displayed Apple Pay button.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
I am not able to replicate this issue. This is what I see ![](http://cld.wthms.co/gsPri+)

And its the same cursor on single product page and checkout page.

**Comment by mattyza** [comment]
Thanks @roykho. What cursor do you see when you hover over the button text itself? It should be the hand cursor as well.

**Comment by roykho** [comment]
@mattyza - same cursor.
