### ISSUE TITLE
Blank settings screen in new stripe gateway (extend class WC_Gateway_Stripe)

### ISSUE THREAD

**Issue by shayzaf89** [woocommerce/woocommerce-gateway-stripe#2466]
**Describe the bug**
 When I try to extend the WC_Gateway_Stripe class and create a new gate of Stripe I get a blank screen in the payment settings screen.

**To Reproduce**
1. Create a new class in your plugin.
2.  Extend the class WC_Gateway_Stripe (woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php).
3. Open the screen woocommerce->settings->payments via the admin pannel.

**Screenshots**
![image](https://user-images.githubusercontent.com/100773855/198211004-e2422fee-0a87-4d1e-9c13-fbf14cab0225.png)

**Expected Behavior**
![image](https://user-images.githubusercontent.com/100773855/198211763-1cb68825-b925-415c-a7f7-4b3e88674301.png)

**Environment (please complete the following information):**
 - WordPress Version - 6.0.2
 - WooCommerce Version - 7.0.0
 - Stripe Plugin Version - 6.9.0

**Additional context**
I want to add more stripe accounts.

**Comment by dougaitken** [comment]
_To ensure the WooCommerce team are having the most impactful work, we review older open Issues on this GitHub repository to find out what is still relevant._ 

It reads like you're looking for functionality that falls outside the current or future functionality of the plugin, and would require customization to fit your needs. 

For assistance with customization or development with your site, we recommend reaching out to someone on our [customizations page](https://woocommerce.com/customizations/) as we're not able to offer that help here.
