### ISSUE TITLE
Trying to charge the customer without email

### ISSUE THREAD

**Issue by stoasis** [woocommerce/woocommerce-gateway-stripe#2467]
**Describe the bug**
We dont have emails in our system the user register with his mobile number and the email is optional. when he try to buy its not completing and throwing an error 500 that the email is required.

**To Reproduce**
1. Go to checkout
2. Click on stripe payment
3. try to pay then it shows completed but the order is on hold.

**Expected behavior**
We need to proceed with online payments without email of customer.

**Screenshots**
None

**Environment (please complete the following information):**
 - WordPress Version 6.0.3
 - WooCommerce Version 7.0.0 

**Additional context**
We need a solution as soon as possible.

**Comment by dougaitken** [comment]
_To ensure the WooCommerce team are having the most impactful work, we review older open Issues on this GitHub repository to find out what is still relevant._ 

It reads like you're looking for functionality that falls outside the current or future functionality of the plugin, and would require customization to fit your needs. 

For assistance with customization or development with your site, we recommend reaching out to someone on our [customizations page](https://woocommerce.com/customizations/) as we're not able to offer that help here.
