### ISSUE TITLE
Could not find order via intent ID: pi_XXXXXX

### ISSUE THREAD

**Issue by isaklafleur** [woocommerce/woocommerce-gateway-stripe#2480]
Since I changed to the new Stripe Experience at checkout I'm getting this errors.

2022-11-21T10:28:47+00:00 DEBUG 
====Stripe Version: 7.0.1====
====Start Log====
Could not find order via intent ID: **pi_3M6XDuHQeNUw8fEu1tRPmxMB**
====End Log====

2022-11-21T10:45:00+00:00 DEBUG 
====Stripe Version: 7.0.1====
====Start Log====
Could not find order via intent ID: pi_3M6XTCHQeNUw8fEu1RnfcHre
====End Log====

2022-11-21T10:45:22+00:00 DEBUG 
====Stripe Version: 7.0.1====
====Start Log====
Could not find order via intent ID: pi_3M6XDuHQeNUw8fEu1tRPmxMB
====End Log====

But I can find the order in Stripe via the intent ID. Why do I get this log error?

(Im using latest version of WC, WP and Stripe plugin.

![image](https://user-images.githubusercontent.com/10033653/203036061-e8cb2461-ef76-4f47-973d-da6a57bfb6e8.png)

**Comment by isaklafleur** [comment]
2022-11-19T14:27:41+00:00 CRITICAL Uncaught Error: Call to a member function update_status() on null in /www/theuntamedeurope_244/public/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-intent-controller.php:683
Stack trace:
#0 /www/theuntamedeurope_244/public/wp-includes/class-wp-hook.php(308): WC_Stripe_Intent_Controller->update_failed_order_ajax('')
#1 /www/theuntamedeurope_244/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#2 /www/theuntamedeurope_244/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /www/theuntamedeurope_244/public/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(94): do_action('wc_ajax_wc_stri...')
#4 /www/theuntamedeurope_244/public/wp-includes/class-wp-hook.php(308): WC_AJAX::do_wc_ajax('')
#5 /www/theuntamedeurope_244/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(false, Array)
#6 /www/theuntamedeurope_244/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /www/theuntamedeurope_244/public/wp-includes/template-loader.php(13): do_action('template_redire...')
#8 /www/theuntamedeurope_244/public/wp-blog-header.php(19): require_once('/www/theuntamed...')
#9 /www/theuntamedeurope_244/public/index.php(17): require('/www/theuntamed...')
#10 {main}
  thrown in /www/theuntamedeurope_244/public/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-intent-controller.php on line 683

**Comment by isaklafleur** [comment]
This happens only when using the latest API version that was released last week.

**Comment by dougaitken** [comment]
Hey @isaklafleur - are you still having these errors displayed in the Stripe plugin log file? If so, are you on the latest version of the Stripe plugin, version 7.0.2?

Thanks

**Comment by dougaitken** [comment]
_To ensure the WooCommerce team are having the most impactful work, we review older open Issues on this GitHub repository to find out what is still relevant._ 

**As there hasn’t been any activity on this Issue recently, I’m going to close this Issue.** 

To confirm if this is a bug or conflict, please first go through the WooCommerce [How to Test for Plugin and Theme Conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/) documentation.

If you feel this is still relevant and requires attention, please post a [new bug report](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/new/choose) with some more details, including the results of conflict testing.

For support requests, this is handled by the Happiness Engineers for the WooCommerce Stripe plugin. If you post this in the [WooCommerce Stripe Support Forums](https://wordpress.org/support/plugin/woocommerce-gateway-stripe/), someone will be able to offer support or advice there.
