### ISSUE TITLE
Stripe Link has been enabled for all other countries since the 11th of November.

### ISSUE THREAD

**Issue by joejordanbrown** [woocommerce/woocommerce-gateway-stripe#2481]
The plugin should now enable all other countries that are on the list here https://stripe.com/docs/payments/link 

Prior to November 11th they were request feature access only.

**Comment by dougaitken** [comment]
Hi @joejordanbrown - can you check https://dashboard.stripe.com/settings/link - from what we've seen, Stripe Link is enabled by default and this will show on the Checkout page as an Express Payment button.

**Comment by joejordanbrown** [comment]
Hi @dougaitken, Yes it's showing up with that enabled. Just need the settings to show on the WooCommerce settings page. Linked to this array https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2437

**Comment by eurello** [comment]
While Stripe Link is enabled for other countries, Woo's payment gateway plugins still limit it to the US only: see relevant documentation for the [Stripe](https://woocommerce.com/document/stripe/#stripe-link) and [WooCommerce Payments](https://woocommerce.com/document/woocommerce-payments/payment-methods/link-by-stripe/) plugins. Would it be possible to enable this for all merchants?

**Comment by NatAliash88** [comment]
> While Stripe Link is enabled for other countries, Woo's payment gateway plugins still limit it to the US only: see relevant documentation for the [Stripe](https://woocommerce.com/document/stripe/#stripe-link) and [WooCommerce Payments](https://woocommerce.com/document/woocommerce-payments/payment-methods/link-by-stripe/) plugins. Would it be possible to enable this for all merchants?

I'm interested in this option too, thanks.

**Comment by energiajook** [comment]
I'm also not in the US but would like to use Stripe Link. 
Stripe's support confirm it is available in my country and I have it enabled in Stripe settings, however, WooCommerce doesn't allow using it. 
Thanks!

**Comment by jtobiesen** [comment]
Question/interest about Link availability the UK 5954528-zen

**Comment by jtobiesen** [comment]
Would like to use Link from Italy. 5941574-zen

**Comment by jtobiesen** [comment]
5982457- zen interest for Austria

**Comment by AbhinavSakalle** [comment]
7077177-zen interest about the availability in Australia

**Comment by ghost** [comment]
It would be great to get an update re when this would be available please, as I am getting an increasing amount of customers asking why I don't offer it. Approx 50% of my site users are in the USA and they don't understand why I wouldn't offer it.

**Comment by NatAliash88** [comment]
I offer only paypal now as they offered me a lower rate. They called me on
the phone.

**Comment by maticomp** [comment]
Hello! Bringing this issue up. The `includes/payment-methods/class-wc-stripe-upe-payment-method-link.php` payment gateway class for Link is actively limiting the use of Link now:

```
$this->supported_currencies = [ 'USD' ];
```

and:

```
public function is_available() {
	//if merchant is outside US, Link payment method should not be available
	$cached_account_data = WC_Stripe::get_instance()->account->get_cached_account_data();
	$account_country     = $cached_account_data['country'] ?? null;

	return 'US' === $account_country && parent::is_available();
}
```

However, Stripe LInk is happily available for other merchants as well, confirmed by Stripe's support.

Assuming this was a preview feature and is now widely available, it would be cool to see this roadmapped in the Woocommerce's Stripe integration.

Thanks.
