### ISSUE TITLE
Declined debit card transactions resulting in orders with status of Pending Payment

### ISSUE THREAD

**Issue by grayayer** [woocommerce/woocommerce-gateway-stripe#249]
#### What I expected

When an order through stripe is declined because a valid debit card doesn't have enough funds to cover the transaction, I expect the Stripe Modal Checkout to shake and have an arrow notice indicating "Your card was declined" as it does for bad credit cards (as is seen in the attached screenshot)

#### What happened instead

When I go to pay for an order through stripe with a debit card that doesn't have enough funds, the Stripe modal window will close, reveal a "card declined" message on the checkout page. WooCommerce unfortunately also creates an order with a status of "payment pending". Within the order notes there is a message of "the card was declined".

#### Steps to reproduce the issue

 I've tested this on a couple sites, with only Twenty Seventeen theme and the latest WooCommerce and Stripe payment gateway plugin. I've even created a brand new clean install. So it seems like this is the default configuration.

If we don't use the "stripe checkout modal" and instead have people enter credit card info directly on the checkout page, even bad credit card attempts create "pending payment orders". 

#### Why this is a problem

This can cause all sorts of issues when trying to download WooCommerce data into quickbooks based on order status. Customers repeatedly try to modify the cart to reduce the total $ amount, which fails multiple times and creates even more failed orders. 

![image](https://cloud.githubusercontent.com/assets/3773395/25925738/638aeae6-359f-11e7-9025-d6c2f40862f9.png)

**Comment by roykho** [comment]
Yes that is the behavior of how it works. There should be pending payment orders if a charge failed. You have to use custom code if you want a different behavior.

**Comment by grayayer** [comment]
I understand the value of creating pending payment orders if a debit card fails, but why should this be a different result than by using an invalid credit card. Why the inconsistency?

**Comment by roykho** [comment]
Because using the modal, it is abstracted away from WC until after the process.

**Comment by grayayer** [comment]
Which is abstracted away? The credit card or the debit card format?

**Comment by roykho** [comment]
So when modal is used, Stripe handles the process within the modal therefore abstracts away what WC handles. But when the default Stripe is use ( non modal ), WC is the one that triggers the API calls to "try" and process the payment. I hope that makes sense. Or perhaps I am not understanding your question?

**Comment by grayayer** [comment]
It's just that the YITH Stripe plugin ![image](https://cloud.githubusercontent.com/assets/3773395/25926464/3a50dde8-35a4-11e7-8105-c7f7a5751a4c.png)

**Comment by grayayer** [comment]
Is it not possible, _while using the stripe modal_, to check whether there are sufficient funds _on a debit card_ before creating an order, which gets the status of pending payment if rejected?

**Comment by roykho** [comment]
Please be patient. This will be investigated in time. Don't worry about the "closed" status of the issue.

**Comment by grayayer** [comment]
oh great. I wasn't sure whether you thought it was worth while looking into, or understood me correctly. Thank you.

**Comment by roykho** [comment]
@grayayer - So I have contacted Stripe about this and as I suspected, there is no way to control this on our plugin level. It is all done via Stripe's end. Please see the explanation from their support.

> It depends on when the card or charge is declined and why. As you may know, Checkout itself doesn't create the charge, it's just a way to create the token.

> When using Checkout and in order to create the token, we send an automatic authorization on the card to the bank, which can be declined right away. In those cases, the payment would be marked as declined in the modal.

> If that authorization works, the modal marked the payment as validated but it's only then that your script tries running the charge. The charge can also be declined at that point, either by the bank or by Stripe. In that case, it could work in the modal but be marked as declined afterwards.

> If the card has insufficient funds, it would be marked as validated in the modal but fail afterwards.
