### ISSUE TITLE
How can i load Stripe JS outside the checkout page?

### ISSUE THREAD

**Issue by eldoroshi** [woocommerce/woocommerce-gateway-stripe#2498]
Hello,

I want to load the Stripe Payment UPE payment method outside the WooCoomerce Checkout page but it seems impossible.
I have a modal box that has to be shown on each page of my site but the Stripe card form doesn't load except the checkout page.

Let me know how I can change the code of the plugin to make it possible. I noted that the Stripe js files are not loaded except for the page WooCommerce checkout page.

You can also add an option to the plugin settings to make it possible with a simple click.

Let me know.

Regards!

**Comment by dougaitken** [comment]
It reads like you're looking for functionality that falls outside the current or future functionality of the plugin, and would require intensive customization to fit your needs.

For assistance with customization or development with your site, we recommend reaching out to someone on our [customizations page](https://woocommerce.com/customizations/) as we're not able to offer that help here.
