### ISSUE TITLE
E2E test cases for smoke tests

### ISSUE THREAD

**Issue by rafaelzaleski** [woocommerce/woocommerce-gateway-stripe#2500]
Cover all [smoke tests](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Smoke-testing-instructions) with E2E tests.

**Onboarding**
- [ ] Manual plugin update

**Checkout**
- [ ] Checkout with normal credit card
- [ ] Checkout with saved card
- [ ] Checkout with SCA card
- [ ] Checkout failures (with one of the error cards)
- [ ] Checkout with Payment Request
- [ ] Checkout with Payment Request (3DS card)

**Order**
- [ ] Full refund

**Subscriptions**
- [ ] Purchase subscription product
- [ ] Renew subscription

**WooCommerce Blocks**
- [ ] Create a Cart page with the Cart Block
- [ ] Create a Checkout page with the Checkout Block
- [ ] Checkout with normal credit card
- [ ] Checkout with SCA card
- [ ] Checkout failures (with one of the error cards)
- [ ] Checkout with Payment Request
- [ ] Checkout with saved card
- [ ] Purchase subscription product

**Comment by diegocurbelo** [comment]
Merged with "Add Playwright E2E tests #2483"
