### ISSUE TITLE
E2E tests: WooCommerce Blocks

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#2506]
- [x] [Merchant - WooCommerce Blocks: Create a Cart page with the Cart Block](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#blocks-create-a-cart-page-with-the-cart-block)
- [x] [Merchant - WooCommerce Blocks: Create a Checkout page with the Checkout Block](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#blocks-create-a-checkout-page-with-the-checkout-block)
- [x] [Shopper - WooCommerce Blocks: Checkout with normal credit card](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#blocks-checkout-with-normal-credit-card)
- [x] [Shopper - WooCommerce Blocks: Checkout with SCA card](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#blocks-checkout-with-sca-card)
- [x] [Shopper - WooCommerce Blocks: Checkout failures (with one of the error cards)](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#blocks-checkout-failures-with-various-cards)
- [ ] [Shopper - WooCommerce Blocks: Checkout with Payment Request](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#blocks-checkout-with-payment-request-button)
- [x] [Shopper - WooCommerce Blocks: Checkout with saved card](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#blocks-checkout-with-saved-card)

**Comment by rafaelzaleski** [comment]
Due to technical limitations of E2E tests, [Shopper - WooCommerce Blocks: Checkout with Payment Request](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#blocks-checkout-with-payment-request-button) cannot be implemented.
