### ISSUE TITLE
Fatal error on checkout page when Apple Pay is enabled + WPML

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce-gateway-stripe#251]
There's a fatal error on the checkout page with latest Stripe and WC versions **only** when Apple Pay is enabled and WPML activated.

#### Affected ticket(s)

573222-zd-woothemes
574217-zd-woothemes

#### What I expected

Payment methods should be displayed properly on the checkout page.

#### What happened instead

There's a fatal error on the checkout page:

>Fatal error: Call to a member function get_payment_method() on boolean in /wp-content/plugins/woocommerce/includes/wc-order-functions.php on line 707

#### Steps to reproduce the issue

- Use latest Stripe, WC
- Activate WPML
- Enable Apple Pay

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Is this issue with just the base WPML or with other addons like the WooCommerce Multilangual?

**Comment by corsonr** [comment]
According to my tests it's WPML, not WooCommerce Multilangual.

**Comment by roykho** [comment]
I have just tested this, no errors for me.

**Comment by corsonr** [comment]
Ok, i'll give it some more time for testing. I'll come back to you.

**Comment by spraveenitpro** [comment]
@roykho you can also check this one  574217-zd-woothemes

**Comment by spraveenitpro** [comment]
Any update on this would be great :)

**Comment by roykho** [comment]
@spraveenitpro did you test this yourself? What are the steps you used to make the error show? What plugins you have installed exactly as I know WPML has lots of added extensions for WC. What is your setup to reproduce this?

**Comment by roykho** [comment]
Closing for now due to lack of activity.

**Comment by spraveenitpro** [comment]
@roykho Don't have apple pay in this part of the world but this has been confirmed by @corsonr,

Can you please confirm @corsonr ? thanks

**Comment by corsonr** [comment]
it doesn't seem I replicate anymore with the latest versions of all addons.

**Comment by zwiesman31** [comment]
@roykho @corsonr @spraveenitpro @conschneider : I'm on ticket 574217-zd-woothemes and not sure how best to proceed? Do we send them the 4.0.0 beta and ask them to test/wait for the release? Or is there something else needed here to address this? Thanks!

**Comment by conschneider** [comment]
Hi @zwiesman31 - I would sent them the beta for testing and give a clear and friendly warning that this is beta and a full backup is very, very important.
