### ISSUE TITLE
Payment uncaught error

### ISSUE THREAD

**Issue by binyamindavid** [woocommerce/woocommerce-gateway-stripe#2511]
**Describe the bug**
When someone makes a payment. Woocommerce does not accept the successful callback

**To Reproduce**
1. Go to make a purchase
2. As a customer nothing happens, looks like my payment was not received.

**Expected behavior**
Should notify woocommerce and accept the payment on the order

**Screenshots**

![Screenshot 2022-12-26 at 18 03 32](https://user-images.githubusercontent.com/972227/209566090-583fc824-33ba-4a5e-a2b3-9d82a64fa963.png)

**Environment (please complete the following information):**
 - WordPress Version 6.1.1
 - WooCommerce Version 7.2.2
 - Stripe Plugin Version 7.0.1

**Comment by dougaitken** [comment]
Hey @binyamindavid 

Does this happen for every payment? Were payments working as expected previous and this error is something new?

I’ve been unable to replicate the issue you described using the latest release of the core WooCommerce plugin and the [WooCommerce Stripe Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-stripe/) as mentioned in the WooCommerce [How to Test for Plugin and Theme Conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/) documentation. 

As I’m unable to reproduce this, I’m marking this Issue as Closed. If you feel this is still relevant and requires attention, please post a [new Issue](https://github.com/woocommerce/woocommerce-gateway-stripe/issues/new/choose) with some more details, including the results of any conflict testing.
