### ISSUE TITLE
Add filter hook to enable custom styling of the updated checkout experience

### ISSUE THREAD

**Issue by morakniv1891** [woocommerce/woocommerce-gateway-stripe#2514]
**Is your feature request related to a problem? Please describe.**
The styling of the Stripe Payment Element is dependent on the styling of the rest of the checkout page making it theme dependent and limiting. Adding the possibility to alter the styling rules used to create the element would allow for custom, non theme dependent styling of the form.

**Describe the solution you'd like**
Add filter hook to the appearance object that is used to create the Stripe Payment Element (perhaps on line 304 in woocommerce-gateway-stripe-develop\includes\payment-methods\class-wc-stripe-upe-payment-gateway.php for example)

**Describe alternatives you've considered**
I've looked through the code and I can't find any way to override the styling without altering the plugin code.

**Additional context**
The solution I've suggested comes from my understanding of the code so far after looking into it just a bit. It seems that the styling used for the .Input class in the form for example comes from cloning the #billing_first_name fields element, use the computed styling from that cloned element to set a transient, then getting this transient when creating wc_stripe_upe_params.appearance that is used when creating the Stripe Payment Element. If that is how it works, it should be as easy as adding a filter hook on the line suggested as solution.

**Comment by ricardo** [comment]
Related: p1672849559341919-slack-C7U3Y3VMY

Indeed it's currently not possible to customize the new checkout experience styling without changing the plugin code directly.

As a possible fix, we can introduce a new filter, or make use of the existing filter for the old checkout experience / non-UPE: [wc_stripe_elements_styling](https://woocommerce.com/document/stripe-styling-fields/#section-4).

Before fixing this and closing the issue, we should also update our docs: https://woocommerce.com/document/stripe-styling-fields/

**Comment by addedlovely** [comment]
@Ricardo is the documentation still out of date?

I need to change the font family, and it reads like the 'appearance' setting is the correct place to do, but can't see how this filter helps?
[](https://stripe.com/docs/js/elements_object/create#stripe_elements-options)

**Comment by ricardo** [comment]
> is the documentation still out of date?

I believe the documentation is only valid for when the new checkout experience is disabled.

cc'ing @woocommerce/quark

**Comment by wheeleran** [comment]
is there an update on this?

**Comment by mrbjjackson** [comment]
Also curious if there is still no way to style Stripe form on the most recent checkout experience.

**Comment by a-danae** [comment]
Hi there 👋 Thanks for checking in!

It's not possible yet to customize the styling of the updated checkout experience. The updated checkout experience is undergoing changes and this will continue to be on hold for now. We'll update this issue with news.

**Comment by pmjcreations** [comment]
I would like to have options to customize the payment form. At least an option to choose one design from official design/theme sets https://docs.stripe.com/elements/appearance-api

**Comment by PaulSchiretz** [comment]
Now, that the legacy experience is deprecated a way to style the checkout is a must for many of us to move forward. Can we please have a simple filter for the array you are passing to stripe via the json "appearance" field so we can use the stripe documentation on how to tweak the stripe elements to our liking? That would be just perfect! 

If needed i could also write a pull request.... but thought you are quicker on that matter!

**Comment by ABACHOPPA** [comment]
This is now mission critical to be in place before the legacy experience is fully deprecated. Some custom themes break the styling of the new checkout experience payment form, leaving us with no way to fix the styling issue if the theme developer is slow to do so.
