### ISSUE TITLE
Missing mention of Link on Settings page and documentation

### ISSUE THREAD

**Issue by anu-rock** [woocommerce/woocommerce-gateway-stripe#2523]
**Describe the bug**

A couple of months ago, Stripe enabled the Link button for express checkouts. So, now express checkout shows Google Pay, Apple Pay, or Link button depending on which conditions are met by the user. Eg. if you are logged in to your Google account and you have your wallet configured, it will show the Google Pay button.

But there is no mention of this behavior on either the Settings page or our [documentation](https://woocommerce.com/document/stripe/#express-checkouts).

**Screenshots**

No mention of Link on Settings page:

![Screenshot 2023-01-11 at 18 22 31](https://user-images.githubusercontent.com/1288616/212030706-693371c9-e300-4349-bee0-0e9af335e38c.png)

Yet, Link appears on preview and product pages:

![Screenshot 2023-01-11 at 19 55 28](https://user-images.githubusercontent.com/1288616/212030715-216406aa-b97e-4bba-94bc-98ed90d9f085.png)
![Screenshot 2023-01-11 at 18 22 59](https://user-images.githubusercontent.com/1288616/212030731-24eec97b-7aa3-4a26-b9c1-98be1e234cab.png)

**Comment by diegocurbelo** [comment]
For the new checkout experience, an option to disable the Link payment request button independently of Apple Pay / Google Pay was added.

![Image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/407542/f37a88e5-a587-4117-917e-170afd7cc420)
