### ISSUE TITLE
get_options() deprecation notice in error logs

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce-gateway-stripe#2525]
**Describe the bug**
There is the following error regarding `get_options()` being deprecated

`PHP message: The AutomatticWooCommerceAdminAPIOptions::get_options function is deprecated since version 3.1.PHP message: The AutomatticWooCommerceAdminAPIOptions::get_options function is deprecated since version 3.1" while reading response header from upstream, client: 88.83.108.76, server: thebbqexperts.co.uk, request: "GET /wp-json/wc-admin/options?options=wc_show_upe_customization_options_notice&_locale=user HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8.1-fpm-thebbqexpertscouk.sock:", host: "thebbqexperts.co.uk:13539", referrer: "https://thebbqexperts.co.uk/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe"`

**To Reproduce**
1. Have debugging enabled
2. Navigate to Stripe settings.
3. View log file

**Expected behavior**
Fixed deprecated issues and no logs added

**Screenshots**
![https://d.pr/i/ODpesS](https://d.pr/i/ODpesS+)
Image link: https://d.pr/i/ODpesS

&

![https://d.pr/i/TzwJ5T](https://d.pr/i/TzwJ5T+)
Image link: https://d.pr/i/TzwJ5T

**Environment (please complete the following information):**
 - WordPress Version: 6.1.1
 - WooCommerce Version: 7.2.2
 - Stripe Plugin Version: 7.0.1

**Comment by ryanr14** [comment]
5857328-zen

**Comment by dougaitken** [comment]
Duplicate - Closing in favour of #2371
