### ISSUE TITLE
Pulls wrong address into WooCommerce from Google Payment Request API / Apple Pay

### ISSUE THREAD

**Issue by shawaj** [woocommerce/woocommerce-gateway-stripe#253]
When using payment through Google Payment Request API or through Apple Pay, regardless of what shipping address is chosen in the checkout process, this plugin brings in the "default" address rather than the one chosen by the customer.

Can this be resolved as a priority?

**Comment by shawaj** [comment]
In support forum also - https://wordpress.org/support/topic/google-payment-request-api-brings-in-incorrect-address/

**Comment by roykho** [comment]
Customer can choose the address when the payment sheet opens.

**Comment by shawaj** [comment]
@roykho - you have closed this prematurely. This *is* an issue.

If you choose an address in the payment sheet, it does not get pulled into WooCommerce. The default address gets pulled in regardless of what you choose on the payment sheet.

This is the same for both Apple Pay and Google payment request API.

Please reopen this issue. Would be grateful for a quick fix

**Comment by roykho** [comment]
Ok your original explanation was not clear. I had understood it as you wen to the checkout process on the WC checkout page and entered an address there and later you use Apple Pay and it didn't see that address and picked a default one.

**Comment by shawaj** [comment]
Sorry, my bad. I mean when you go to it from cart, choose to checkout directly from there,, choose address from that screen, confirm order. It doesn't pull the correct address back into WooCommerce for delivery address

**Comment by roykho** [comment]
I just tested this with Apple Pay and was not able to reproduce. I have 2 address in my Apple Pay profile and I select the one that is not selected by default and went through the paying process and that same selected address did get populated in my WC order.

**Comment by shawaj** [comment]
Ok I'll test again with Apple pay tomorrow.

I just tested again on Google payment request API and still seeing the same issue.

Can send you screenshots via email if you want?

**Comment by shawaj** [comment]
@roykho - any fix for this yet?

**Comment by roykho** [comment]
@shawaj no as I am not getting the same issue you're having. In my test, payment request is not working at all if there is shipping. This is related to WC 3.0 as before that, it was working fine. So I am not sure how in your test, you're able to even go through the process.

**Comment by shawaj** [comment]
What do you mean "if there is shipping"? For me it gives me shipping options in the payment request popup and also gives me a delivery address option?

Can you email me - my GitHub name @gmail.com and I'll send you some screenshots?

Don't want to share my personal details here.

Thanks

**Comment by roykho** [comment]
@shawaj what I am getting is after I select shipping on the payment sheet and click on pay, I get an error stated no shipping is chosen. Not quite the same issue as you. Nonetheless it will be looked at.

**Comment by shawaj** [comment]
Yes because you have to surely select the delivery​ address and shipping method before it'll let you pay?

Hence why I wanted to send you these screenshots to make it easier to understand

**Comment by roykho** [comment]
@shawaj yes both were selected in my case.
