### ISSUE TITLE
Some critical flows are failing with HPOS enabled

### ISSUE THREAD

**Issue by cesarcosta99** [woocommerce/woocommerce-gateway-stripe#2531]
The following [critical flows](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience) are failing when [HPOS is enabled](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Enabling-High-Performance-Order-Storage-(HPOS)) with both UPE and non-UPE checkouts:

- [x] Shopper - Subscriptions - Change payment method to new card.
- [x] Shopper - Subscriptions - Change payment method to saved card.
- [x] Shopper - Subscriptions - Set default payment method – https://github.com/Automattic/woocommerce-subscriptions-core/pull/395.
- [x] Shopper - Subscriptions - Change default payment method – https://github.com/Automattic/woocommerce-subscriptions-core/pull/395.
- [x] Merchant - Subscriptions - Renew subscription automatically.

**Comment by asumaran** [comment]
@cesarcosta99 I've pulled your branch and can confirm the first two items from the list are fixed. I'll continue looking tomorrow.

**Comment by asumaran** [comment]
Found the reason why the critical flow `Shopper - Subscriptions - Set default payment method.` isn't working on WCStripe.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/1025173/214757537-c859f0fa-40f0-4b59-8a63-5daa55ab4781.png">

When the `Update the payment method used for all...` option is checked [there's a call](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/class-wc-subscriptions-change-payment-gateway.php#L419) to `WC_Subscriptions_Change_Payment_Gateway::update_payment_method()`  to update the other subscriptions. The data for the `$new_payment_method_meta` argument is incorrect though.

[Lines above](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/class-wc-subscriptions-change-payment-gateway.php#L395) using ` WCS_Payment_tokens::get_subscription_payment_meta()` we get the subscription meta we are going to pass to `WC_Subscriptions_Change_Payment_Gateway::update_payment_method()` and it contains the old/previous source ID ending with the other subscriptions being updated incorrectly.

```
$ wp plugin list --status=active
+------------------------------+--------+--------+-----------+
| name                         | status | update | version   |
+------------------------------+--------+--------+-----------+
| woocommerce                  | active | none   | 7.3.0     |
| woo-gutenberg-products-block | active | none   | 9.4.1     |
| woocommerce-gateway-stripe   | active | none   | 7.0.2     |
| woocommerce-subscriptions    | active | none   | 4.8.0-dev |
| wordpress-importer           | active | none   | 0.8       |
+------------------------------+--------+--------+-----------+
```

Here's a short video where we can see the issue more clearly:


https://user-images.githubusercontent.com/1025173/214762531-2cfbd27d-5104-4aa9-9b44-278964bedfb2.mov

Notice the `_stripe_source_id` has changed in the DB but `WCS_Payment_tokens::get_subscription_payment_meta()` returns the previous source ID.

**Comment by cesarcosta99** [comment]
The flow "Merchant - Subscriptions - Renew subscription automatically" is actually working as expected, no fixes needed. We confirmed that the issues occurred in that flow are unrelated to the Subscriptions extension and HPOS.
