### ISSUE TITLE
Auto accept terms and conditions when using google payment request api?

### ISSUE THREAD

**Issue by shawaj** [woocommerce/woocommerce-gateway-stripe#254]
Posted this over on WooCommerce main GitHub but was asked to put here too by @mikejolley - https://github.com/woocommerce/woocommerce/issues/15040

Using the official stripe plugin and using Apple Pay / Google Payment Request API from the cart page, the payment looks to be successful through the payment request API but then it returns an error and you get sent back to the cart page where it has an error message "You must accept our terms and conditions"

Is there a way to override the need to tick this box when using Apple Pay / Google Payment Request API? But have it still enabled when going through the full checkout?

Thanks

**Comment by shawaj** [comment]
FYI - this is in the support forum for stripe plugin too https://wordpress.org/support/topic/you-must-accept-our-terms-and-conditions-error-with-apple-pay-google-payment/

**Comment by shawaj** [comment]
With the PayPal Express plugin from Angelleye (https://en-gb.wordpress.org/plugins/paypal-for-woocommerce/ and https://github.com/angelleye/paypal-woocommerce) the way it works is that after confirming payment on PayPal it then redirects you to a "review order" page on the main website where you can then accept the Terms and Conditions and then complete the order.

Perhaps this can be done with Apple Pay and Google Payment Request API also?

Just a quick thought that popped into my head

**Comment by roykho** [comment]
@shawaj - I don't believe this effects Apple Pay. Perhaps only Payment Request. Can you confirm?

As for the fix for this, I am leaning towards bypassing the terms if they use Payment Request for checkout as the point of it is for a faster, more convenient UX. All that would be taken away if they have to return to the order received page to confirm the terms and submit.

**Comment by shawaj** [comment]
@roykho - with regard to Apple Pay, I tested it earlier and it seemed to have the same issue but it was early in the morning and I was rushing (I don't have any iDevices so was testing with my girlfriend's before she went to work!) Will try again over weekend.

Agreed that bypassing the terms altogether is a better option for the reasons you mention.

**Comment by roykho** [comment]
From my test Apple Pay works fine.

**Comment by shawaj** [comment]
Ok I'll test tomorrow and report back. Thanks for the quick fix
