### ISSUE TITLE
Enabling "New checkout experience" hides the Stripe Fee and Stripe Payout amounts

### ISSUE THREAD

**Issue by EjayhanFernandes** [woocommerce/woocommerce-gateway-stripe#2549]
**Describe the bug**

When the "New checkout experience" is enabled the `Stripe Fee` and `Stripe Payout` amounts are not displayed on all orders processed with Stripe.

**To Reproduce**
1. Go to WP Admin → WooCommerce → Settings → Payments → Stripe → Settings → Advanced Settings
2. Enable "New checkout experience"
3. Go to WP Admin → WooCommerce → Click on an order
4. See error:
![00VU0R.png](https://user-images.githubusercontent.com/81605775/217477856-44847bef-29fa-4c10-b4d1-f41b503af1d0.png)

**Expected behavior**

`Stripe Fee` and `Stripe Payout` amounts on orders processed with Stripe should be displayed: ![lzPwW4.png](https://user-images.githubusercontent.com/81605775/217478181-ee1e810a-182c-4537-9c84-ef4874e39e0c.png)

**Environment (please complete the following information):**
 - WordPress Version: `6.1.1`
 - WooCommerce Version: `7.3.0`
 - Stripe Plugin Version: `7.0.2`
 - Browser: `Chrome`
 - Any other plugins installed: `No other plugins Active`

**Additional context**
- Disabling "New checkout experience" displays the `Stripe Fee` and `Stripe Payout` amounts again. 
- 5934780-zd-woothemes

**Comment by pavlo-tk** [comment]
I'm also facing this issue.
We need the fee info back!

The versions of my setup are the same, except the Stripe plugin is newer: `7.1.0`.

**UPDATE**
Seems like the `\WC_Gateway_Stripe::display_order_fee()` function in the `/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php:541` is not called at all, and that's why there is no fee information on the order page.

**Comment by reykjalin** [comment]
Tagging with `impact: high` `priority: medium` cc @dougaitken @diegocurbelo

**Comment by ryanr14** [comment]
6083418-zen

**Comment by zoemyers** [comment]
[6083418-zen](https://woothemes.zendesk.com/agent/tickets/6083418) also on my test site

**Comment by marissaexplores** [comment]
another report of this [6464188-zen](6464188-zd-woothemes)

**Comment by stuartduff** [comment]
6464310-zen

**Comment by wyter** [comment]
6650618-zen

**Comment by anant1811** [comment]
#6754710-zen
