### ISSUE TITLE
Feature Request: Improve visibility for misconfigured or failed webhooks

### ISSUE THREAD

**Issue by maxlaf** [woocommerce/woocommerce-gateway-stripe#2551]
**Is your feature request related to a problem? Please describe.**
I frequently encounter support interactions for a variety of issues that are caused by webhooks not being properly configured or failing validation.

When this occurs, the Account Settings section reports the issue with Webhooks. The notices vary, depending on if no webhooks have been processed or if there's a validation issue. But they all have the same design like the following notice for failed validation:

![yw6yqv.png](https://user-images.githubusercontent.com/56649567/217631812-bd143838-e9ee-42f2-9572-eeb221bdb27d.png)

For comparison, this is what appears when there are no webhook issues:

![jqdLhG.png](https://user-images.githubusercontent.com/56649567/217632318-232e8d6f-3ad1-4b62-82dc-9407edea760d.png)

**Describe the solution you'd like**
Ideally, I'd like the visibility of any webhook misconfiguration or validation issues to be more noticeable. We could improve this with color or an icon to highlight the issue as we do for problems with payments/payouts. We could also link the [webhook configuration guide](https://woocommerce.com/document/stripe/#webhooks) to promote self-solving and reduce support requets.

**Comment by reykjalin** [comment]
Tagging with `impact: high` and `priority: medium` cc @diegocurbelo @dougaitken
