### ISSUE TITLE
Syntax error when card is declined

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce-gateway-stripe#256]
#### Affected ticket(s)

575091-zd-woothemes

#### What I expected

When a payment is made with **Stripe Checkout disabled** and when the **card is declined**, we should see a red notice saying "Card declined".

#### What happened instead

On the checkout page:

![](http://cld.wthms.co/YOAwm+)

#### Steps to reproduce the issue

- make sure **Stripe Checkout** is **disabled**
- add a product to cart
- go to the checkout page
- place the order using the following CC number `4000000000000002` (card declined)

Please note: I was able to replicate with latest WC and Stripe version, with PHP 7 and PHP 5.6. But for some reason it didn't happen when I ask @hannahswain to test on her Pressable site. My test was on a local install with Storefront enabled and no other plugins (with Flywheel).

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
I also was not able to replicate this. ![](http://cld.wthms.co/3SkWh+)

**Comment by corsonr** [comment]
Yes, that's what I said, Hannah wasn't either, but the I had some people having the same issue, and I can still replicate it on my local install. Also, the message is properly retrieved and stored in the log and in the order notes and only the notice fails.

**Comment by corsonr** [comment]
Also, it happens when I am logged in and logged out.

**Comment by roykho** [comment]
Best look at the response when you submit to see where it is failing.

**Comment by corsonr** [comment]
![](http://cld.wthms.co/4BEqP+)

**Comment by corsonr** [comment]
Linked to https://github.com/woocommerce/woocommerce/issues/14970 apparently

**Comment by roykho** [comment]
@corsonr ok so this issue is not really a Stripe issue then?

**Comment by corsonr** [comment]
@roykho Correct. I just tested Mike's commit and it fixes the issue. So not Stripe related.
