### ISSUE TITLE
Wrong Payment method name option on wp-admin for orders paid with cash on delivery

### ISSUE THREAD

**Issue by leonardola** [woocommerce/woocommerce-gateway-stripe#2560]
**Describe the bug**
A customer opened a ticket saying that when an order is paid using the cash on delivery payment method, the stripe payment option in the order edit page shows up with the wrong name.
Zendesk ticket: 5983020-zd-woothemes

<img width="607" alt="Screenshot 2023-03-01 at 2 26 31 PM" src="https://user-images.githubusercontent.com/6342964/222218911-0d39d22f-37ef-4883-8105-7cc41b6766f3.png">
<img width="340" alt="Screenshot 2023-03-01 at 2 25 49 PM" src="https://user-images.githubusercontent.com/6342964/222218918-292d4399-a179-4b48-aca9-cc09cc6963d3.png">

**To Reproduce**
- Activate Cash on delivery (I've renamed mine but this should not alter the result)
- As a shopper place an order using Cash on delivery payment method
- Go to wp-admin > Orders > Edit the order recently created > Edit the billing
- Click the payment method select
- Notice there are two Cash on delivery options and one of them is actually stripe

This is caused [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-payment-request.php#L464)

**Comment by dougaitken** [comment]
Pretty sure this is related or the same as #2100

**Comment by dougaitken** [comment]
Closing in favour of #2100
