### ISSUE TITLE
`payment_type` = `recurring` may be less than accurate

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#2565]
**Describe the bug**

Even if a site is set to accept manual payments and automatic payments are disabled, the payment type meta is set to 'recurring' here: Ωhttps://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L470-L474

6018332-zen

**To Reproduce**
1. Be a merchant in India
2. Try to work around https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2561 by enabling manual payments and disabling automatic payments.
3. Still sent to Stripe as recurring.

**Expected behavior**
For recurring to only be set if the payment is, indeed, recurring.

**Screenshots**
![UcwP79.jpg](https://user-images.githubusercontent.com/2127470/223021447-95c610c1-f489-497f-a171-2dabd259125c.jpg)

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**

**Comment by reykjalin** [comment]
I'm not sure I fully understand the use case here. Could you go into a little more detail on what turning on manual payments is supposed to achieve and why it's necessary?

**Comment by WillBrubaker** [comment]
Pretty sure we can close this. 

The report came from a merchant selling to India and they were concerned that even though they enabled manual payments that Stripe shows it as recurring.
