### ISSUE TITLE
Reduced code coupon 100% not work with stripe gateway

### ISSUE THREAD

**Issue by sign0** [woocommerce/woocommerce-gateway-stripe#257]
#### What I expected

_I do not know if the problem really concerns the plugin stripe / or rather woocommerce ... In doubt I share this here hoping that someone can help me ... Thanks :)_

![checkout_stipe_ok](https://cloud.githubusercontent.com/assets/6769414/26002821/1df3ce7e-3731-11e7-9aaa-23128082e325.png)

#### What happened instead

![checkout_stipe_bug](https://cloud.githubusercontent.com/assets/6769414/26002836/26e9d604-3731-11e7-9709-d0ff32e45bb1.png)

#### Steps to reproduce the issue

- Create a coupon code with 100% reduced rate
- Buy an product
- In the basket, add the coupon code
- On the checkout, we can't bypass the stripe gateway

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
I was not able to replicate. I would suggest you test again WC master branch and turn all your plugins off except latest Stripe and perhaps even switch your theme to a default theme and re-test.
