### ISSUE TITLE
With UPE enabled. Pre-orders paid for with a *not-saved* card are moved directly to the processing status with no payment taken 

### ISSUE THREAD

**Issue by Brianmitchtay** [woocommerce/woocommerce-gateway-stripe#2572]
**Describe the bug**
With Stripe UPE enabled. Pre-orders paid for with a not-saved card are moved directly to the processing status with no payment taken.

**To Reproduce**
1. Create a Pre-order product and set it to charge upon release
2. Set up the [Stripe](https://woocommerce.com/products/stripe/?aff=10486&cid=1131038) plugin for testing
3. Enable UPE
4. Purchase the product using the [Stripe Testing Card](https://stripe.com/docs/testing#use-test-cards) and save it for later use
5. See that your initial purchase is moved directly to `processing` as though it has been charged, but no payment is taken.
6. Purchase the product again, this time using the saved card
7. See that your order is correctly held in the pre-order status	

**Expected behavior**
Pre-orders should stay in the correct order status after being made, upon product being released pre-orders should be properly charged

**Actual Behavior**
When a pre-order is made with UPE enabled and a not-saved card, the status changes to `processing` and upon release no payment is taken.

In some instances no payment or setup information is saved to the order at all and so no charge can be made.

**Screenshots**
See a video of the behavior here -

https://user-images.githubusercontent.com/45057772/224432124-077c46cc-9b4d-4d72-b6c2-071851225b3c.mp4

First payment with a new, not-saved card is moved directly to the processing status when it should remain in the Pre-ordered Status

Second Payment with a saved card functions as intended and retains the correct status

**Environment (please complete the following information):**
 - WordPress Version 6.1.1
 - WooCommerce Version 7.4.1
 - Stripe Plugin Version 7.2.0
 - Any other plugins installed
  - Pre-orders, Jetpack.

**Additional context**
Due to other outstanding issues in the Pre-orders plugin I have yet to be able to verify whether the pre-orders incorrectly held in the processing status are correctly charged when the pre-ordered product is released. If the pre-order is manually completed then the charge is collected as expected.

A bug report with this same name exists in the pre-orders repo with more details.

**Comment by Brianmitchtay** [comment]
Further testing thus far seems to indicate that when pre-orders are released, these ones that have been erroneously placed as `Processing` are not charged and do not get completed
![MYrpLy.png](https://user-images.githubusercontent.com/45057772/224461139-4d1e5ebe-5af4-43b7-bd1c-426b1c55d57c.png)
![i1I2iA.png](https://user-images.githubusercontent.com/45057772/224461096-cfd00072-a718-4b00-b897-779c362ccdb4.png)

**Comment by wjrosa** [comment]
The pre-orders plugin used in this issue is available here https://github.com/woocommerce/woocommerce-pre-orders/releases

**Comment by wjrosa** [comment]
Additional information: the following error happens when using a new card:
```
Notice: Undefined property: stdClass::$latest_charge in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php on line 716 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php:716) in /var/www/html/wp-includes/functions.php on line 7049
```
