### ISSUE TITLE
Reoccurring payment fails on indian cards 

### ISSUE THREAD

**Issue by pappyJ** [woocommerce/woocommerce-gateway-stripe#2574]
I am using the stripe woocommerce plugin and all attempts to integrate recurring payments for india has failed because of India e mandates policy. Any workarounds please

**Comment by dougaitken** [comment]
Hi @pappyJ we're working on this current, see #2561 for technical details.

**Comment by reykjalin** [comment]
In terms of workarounds: customers should receive an email letting them know the payment failed and the email includes a link that brings them back to the store to complete the payment.

It's a lot of friction for the customer, but it means they can still continue to pay for the subscription, they just have to come back to the store to process the payment.

**Comment by pmjcreations** [comment]
I did this workaround, which almost equals customers placing an order. They need to be on-site and perform OTP-based payment completion 😐
