### ISSUE TITLE
Order statuses are wrong when UPE is enabled on pre-orders.

### ISSUE THREAD

**Issue by asumaran** [woocommerce/woocommerce-gateway-stripe#2577]
**Describe the bug**

> Users face some problems with Woo Stripe <-> Pre-Orders plugins pair. Sometimes, customers are not being charged for a pre-order product with the Stripe UPE payment method. On top of that, payment/setup intent information is not always available. At first glance, it seems that WC_Stripe_UPE_Payment_Method and WC_Stripe_Pre_Orders_Trait are the first places to look for an error.

See:

- p1678954960199869-slack-CHG7MTCAF
- 6008637-zd-woothemes

**To Reproduce**

- When Pre-orders meant to be charged upon release were placed with Stripe UPE, they moved right to the `processing` status instead of to `pre-ordered`.
- This caused them to not charge the customer upon release as expected.
- In testing we were able to collect payment by manually completing the pre-order, that has not worked for the customer in practice.
- In some cases no payment token or setup intent information was saved to the order at all (no clue why that is, haven't been able to reproduce this) Obviously in these cases the user needs to reach out to the customer with an explanation and ask for payment
- In other cases, payment tokens and setup intent info were saved and are stored on the order, but completing the pre-orders did not take payment (in our testing it does take payment, again we've not been able to reproduce)

**Expected behavior**
- Order should be processed correctly.
- Order status should be "Pre-Order" 

**Environment (please complete the following information):**
 - WordPress Version: 6.1.1
 - WooCommerce Version: 7.3.0
 - Stripe Plugin Version: 7.0.2
 - Browser [e.g. chrome, safari] and Version: Any
 - Any other plugins installed: See ticket.

**Comment by Brianmitchtay** [comment]
This may be a duplicate of the issue I opened about this last week #2572

**Comment by asumaran** [comment]
Closing in favor of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2572
