### ISSUE TITLE
Apple Pay and Sequential Order Numbers Pro Compatibility

### ISSUE THREAD

**Issue by joelwills** [woocommerce/woocommerce-gateway-stripe#258]
Stripe is currently listed as compatible with Sequential Order Number ([#](https://docs.woocommerce.com/document/sequential-order-numbers/#section-6)) which is correct, however it doesn't seem to be with Apple Pay.

![Screenshot](http://joelwills.com/KJfAS+)

Link to image: http://joelwills.com/KJfAS

Speaking with SkyVerge:

> On a hunch it looks like they might having cases using $order->get_id() (or $order->id on pre-WC3 handling) that should be replaced with $order->get_order_number() anywhere that the order number is displayed.

Thanks!

573495-zd-woothemes

**Comment by rwaynick** [comment]
Noting that User in 2307147-zen would like this feature.
