### ISSUE TITLE
Pre-orders: When order payment fails, subsequent payment bypasses preorder status when paid for

### ISSUE THREAD

**Issue by nicdwilson** [woocommerce/woocommerce-gateway-stripe#2592]
**Describe the bug**
This has been identified as a [Stripe issue by the Pre-Orders team here](https://github.com/woocommerce/woocommerce-pre-orders/issues/375). 

A failed payment, which is then later paid for from the "My Account" area will change directly to `processing` instead of `pre-ordered`, and the amount will be charged immediately, and not on release.

**To Reproduce**

The product needs to be charge on release. This does not happen with charge now products.

1.  Adds pre-order product to basket
2.  Checkout with `4000 0000 0000 0002`
3.  Card is declined
4.  Order is logged as pending payment
5.  Clear your cart
6.  Go to My Account -> Orders -> Order Pay
7.  Use a valid card `4242 4242 4242 4242`
8.  Order bypasses the "pre-ordered" stage, goes straight to processing and the card is billed

**Expected behavior**
The order paid from the My Account page should work in the same way as the order paid from the checkout page. The order should go to `pre-order` status and payment should be authorized but not immediately charged.

Please [see here for more information](https://github.com/woocommerce/woocommerce-pre-orders/issues/375#issuecomment-1495333204)

**Screenshots**

https://user-images.githubusercontent.com/3624025/223629470-ad3631e9-5a0f-4487-b166-ce8932156dfb.gif

**Environment (please complete the following information):**
 Updated status for site used in above recording

`
WordPress Environment

WordPress address (URL): http://debug-pre-order.local/
Site address (URL): http://debug-pre-order.local/
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –
Server Environment

Server Info: nginx/1.16.0
PHP Version: 8.1.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.84.0
(SecureTransport) OpenSSL/1.1.1q

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
Database

WC Database Version: 7.4.1
WC Database Prefix: wp_
Total Database Size: 4.76MB
Database Data Size: 3.23MB
Database Index Size: 1.53MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.09MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
Post Type Counts

attachment: 23
page: 7
post: 2
product: 18
product_variation: 7
Security

Secure connection (HTTPS): ❌
Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔
Active Plugins (5)

Code Snippets: by Code Snippets Pro – 3.2.2
WooCommerce Stripe Gateway: by WooCommerce – 7.1.0
WooCommerce Pre-Orders: by WooCommerce – 1.9.0
WooCommerce: by Automattic – 7.4.1
WP Crontrol: by John Blackbourn & crontributors – 1.15.1
Inactive Plugins (1)

Order Simulator for WooCommerce: by 75nineteen Media LLC – 1.0.2
Settings

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT
WC Pages

Shop base: https://github.com/woocommerce/woocommerce-pre-orders/issues/6 - /shop/
Cart: https://github.com/woocommerce/woocommerce-pre-orders/issues/7 - /cart/
Checkout: https://github.com/woocommerce/woocommerce-pre-orders/issues/8 - /checkout/
My account: https://github.com/woocommerce/woocommerce-pre-orders/issues/9 - /my-account/
Terms and conditions: ❌ Page not set
Theme

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔
Templates

Overrides: –
Admin

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
new-product-management-experience
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-03-08 20:35:38 +00:00
Options: ✔
Notes: 54
Onboarding: completed
Action Scheduler

Complete: 72
Oldest: 2023-02-10 21:12:31 +0000
Newest: 2023-03-08 05:22:51 +0000

Failed: 11
Oldest: 2023-02-20 23:04:37 +0000
Newest: 2023-03-08 05:39:21 +0000

Pending: 3
Oldest: 2023-03-08 06:39:21 +0000
Newest: 2023-03-09 03:31:01 +0000
Status report information

Generated at: 2023-03-08 05:48:44 +00:00

**Additional context**
This was originally reported as a bug in Pre-Orders.

**Comment by pehaa** [comment]
Affected user confirms that the issue persists with WooCommerce Pre-Orders 2.0.1

zen-6209474-zd-woothemes

**Comment by thenbrent** [comment]
Labeling this high priority given Stripe is taking payment at the wrong time. We have a pretty significant backlog of high priority issues (>30) so this priority doesn't mean it will be fixed immediately. We are working on various ways to fix that backlog of issues faster though.

**Comment by kaushikasomaiya** [comment]
6441301-zen
