### ISSUE TITLE
Unhelpful error message for small payment amounts involving currency conversion

### ISSUE THREAD

**Issue by rafaelzaleski** [woocommerce/woocommerce-gateway-stripe#2593]
**Describe the bug**
When a customer tries to make a payment for an amount less than $10.00 that involves currency conversion, the checkout process throws an error message that reads `Sorry, we are unable to process your payment at this time. Please retry later.` This error message is unhelpful because it doesn't explain the reason for the failure and offers no solution to the customer.

If the customer tries again later, the error will happen again because the amount is still below the minimum threshold for currency conversion. This issue was tested using a store set up using INR and trying to pay with a billing address in the US. The product amount was 18 INR with free shipping.

**To Reproduce**

1. Set up a store with a currency that requires conversion when the payment is made in a different currency.
2. Add a product to the cart that costs less than $10.00 in the store's currency.
3. Proceed to checkout and provide a billing address that's in a different currency than the store's currency.
4. Attempt to make a payment for the product with the provided billing address.
5. The checkout process throws an error message that reads "Sorry, we are unable to process your payment at this time. Please retry later.". The real error can be seen in the Stripe logs (you need to enable it in the advanced settings)

**Expected behavior**
A more helpful error message saying that the total amount is too small to process the payment.

**Additional context**
While this issue might not affect many users since the value threshold is small, it's still important to provide clear and concise error messages that offer solutions or explanations to the customer.

If you cannot reproduce this error, try with lower amounts (1 or 2 dollars after conversion). You can also check [this table](https://stripe.com/docs/currencies#minimum-and-maximum-charge-amounts).

Error log from the Stripe logs:
```
Error: stdClass Object
(
    [error] => stdClass Object
        (
            [code] => amount_too_small
            [doc_url] => https://stripe.com/docs/error-codes/amount-too-small
            [message] => Amount must convert to at least 1000 centavo. ₹18.00 converts to approximately $3.99.
            [request_log_url] => XXXXXXXXXXXXXXXXXXXXX
            [type] => invalid_request_error
        )

)
```

**Comment by annemirasol** [comment]
**Closing**, as the new checkout experience no longer allows you to continue with payment if the amount is too small.

<img width="1728" alt="Screenshot 2024-09-12 at 3 26 45 PM" src="https://github.com/user-attachments/assets/9c15ee48-9404-440c-9cb9-bd846a6c52b0">


If the customer ends up with the payment fields displayed but the amount is too small (e.g. they updated the cart in a different tab), the payment fails with the specific error displayed:

<img width="400" alt="Screenshot 2024-09-12 at 3 27 48 PM" src="https://github.com/user-attachments/assets/422c3e93-653f-45fe-b4ef-ece57ebf6c0d">
