### ISSUE TITLE
Critical error when renewing some subscriptions

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2595]
**Describe the bug**

Some subscriptions fail to be renewed with the following error entry in the logs.
```
CRITICAL Uncaught Error: Call to a member function get_meta() on bool in . . ./public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php:572
```
This logic was [included](https://github.com/woocommerce/woocommerce-gateway-stripe/compare/7.2.0...7.3.0#diff-516e329017ff60072191226cd6dfc80b4b9ca8ccccacd6c151c1598cf4179434R550) in Stripe 7.3.0. Things work well when downgrading to 7.2.0.

**To Reproduce**

TBD. Looks related to renewals of subscriptions created via the WP dashboard and not from a transaction. We've only got reports from merchants so far. 

**Expected behavior**

Valid subscriptions must be renewed without errors.

**Additional context**

Quoting @Brianmitchtay :

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/57471e3da5d96a0cb45dbc931941b2ed7bedb8eb/includes/compat/trait-wc-stripe-subscriptions.php#L572

In that line of code, I see that we're querying the `_stripe_mandate_id` from the parent order. On the merchant's site all of the renewals which are failing don't have parent orders, and subs with parent orders are continuing without issue. So I'm inclined to believe this is the reason. 
However, even the subs with no parent have been renewing for months on end now with no issue, and in the documentation I see that:
> As subscriptions are not necessarily created via a transaction, a subscription will not always have a Parent Order. For example, subscriptions created via the Add Subscription administration screen will not have a Parent Order unless such an order is also manually created.

In the case that a subscription doesn't have a parent order, is the `_stripe_mandate_id` stored elsewhere? That's where I get stuck here..
My guess at this moment is maybe that there's some kind of conflict that is causing that wc_get_order() call that sets the $parent_order variable on line 570 to return as `false` and so the error is thrown.

**Reports:**
- 6201336-zd-woothemes - p1681432310720319-slack-C7U3Y3VMY
- 6202766-zd-woothemes

**Comment by claudiulodro** [comment]
Some more detail in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2596 if needed.

**Comment by Brianmitchtay** [comment]
30140569-hc

**Comment by gabriel-fuentes** [comment]
41909609-hc

**Comment by ldr2273** [comment]
6208106-zen

**Comment by ryanr14** [comment]
6208502-zen

**Comment by contemplate** [comment]
We have 20k+ subscriptions and have seen this bug as well since upgrading two days ago.

**Comment by avantegarde** [comment]
42669100-hc

**Comment by fernmed** [comment]
42670637-hc

**Comment by avantegarde** [comment]
42250837-hc -> 6211018-zen

**Comment by igorhereira** [comment]
6203126-hc

**Comment by spigotdesign** [comment]
6211375-zen

**Comment by kaushikasomaiya** [comment]
6200645-zen

**Comment by jtobiesen** [comment]
42699999-hc

**Comment by imodouglas** [comment]
6203470-zen
6212081-zen
6211153-zen
6213555-zen
6213555-zen

**Comment by grig-23** [comment]
6211375-zen

**Comment by ChrissiePollock** [comment]
#6203864-zen

**Comment by rbgly** [comment]
6217204-zen

**Comment by maxlaf** [comment]
6202292-zen

**Comment by jaxr** [comment]
42769216-hc

**Comment by mouligreenlaw** [comment]
42779518-hc

**Comment by orhanfernandes** [comment]
42779202-hc

**Comment by mouligreenlaw** [comment]
6201629-zen

**Comment by grig-23** [comment]
6210122-zen

**Comment by lynnjat7** [comment]
6210943-zen

**Comment by maxlaf** [comment]
6216879-zen

**Comment by felipevelzani** [comment]
6233723-zen

**Comment by avantegarde** [comment]
6236349-zen

**Comment by drwpcom** [comment]
6062887-zen

**Comment by thuautp** [comment]
6236949-zen

**Comment by mouligreenlaw** [comment]
6238691-zen

**Comment by Mxchael** [comment]
6238731-zen

**Comment by thisissandip** [comment]
6242546-zen

**Comment by thisissandip** [comment]
6220121-zen
6235194-zen
6234934-zen

**Comment by xue28** [comment]
6242711-zen
Downgrading to `7.2.0` fixed the issue for now.

**Comment by gabriel-fuentes** [comment]
6254849-zen

**Comment by felipevelzani** [comment]
6256991-zen

**Comment by felipevelzani** [comment]
6239088-zen

**Comment by sverleis** [comment]
6259352-zen

**Comment by jaxr** [comment]
6264680-zen

**Comment by rafaelzaleski** [comment]
Upgrading to `7.4.0` should fix the issue.
