### ISSUE TITLE
[bug] Not safe to assume subscription has parent order

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce-gateway-stripe#2596]
**Describe the bug**

Following yesterday's release a few clients started reporting that subscription renewals were failing. The logs show this error:

```
04-13-2023 @ 16:02:13 - scheduled action 15645 (subscription payment) failed to finish processing due to the following error: Uncaught Error: Call to a member function get_meta() on bool in /srv/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php:572
Stack trace:
#0 /wordpress/core/6.2/wp-includes/class-wp-hook.php(308): WC_Stripe_Payment_Gateway->add_subscription_information_to_intent(Array, Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(stdClass))
#1 /wordpress/core/6.2/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#2 /srv/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php(1704): apply_filters('wc_stripe_gener...', Array, Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(stdClass))
#3 /srv/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php(285): WC_Stripe_Payment_Gateway->create_and_confirm_intent_for_off_session(Object(Automattic\WooCommerce\Admin\Overrides\Order), Object(stdClass), '9.00')
#4 /srv/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/trait-wc-stripe-subscriptions.php(189): WC_Stripe_Payment_Gateway->process_subscription_payment('9.00', Object(Automattic\WooCommerce\Admin\Overrides\Order), true, false)
...
```

In #2561, `add_subscription_information_to_intent` is introduced, [with these lines here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2561/files#diff-516e329017ff60072191226cd6dfc80b4b9ca8ccccacd6c151c1598cf4179434R569-R572):

```
$parent_order_id = $renewal_order->get_parent_id();
$parent_order    = wc_get_order( $parent_order_id );

$mandate = $parent_order->get_meta( '_stripe_mandate_id', true );
```

It's not very safe to assume that renewals will always have a parent order. Subscriptions that are programmatically created or created with the [Subscriptions Importer](https://github.com/woocommerce/woocommerce-subscriptions-importer-exporter) do not have a parent order; only subscriptions created by going through the on-site WooCommerce checkout will have one.

**To Reproduce**
1. Import a subscription using the Subscriptions Importer. Notice it has no parent order, just a stand-alone Subscription.
2. Run the scheduled action to process the renewal. Observe it fails with the above error.

**Expected behavior**
Subscriptions without a parent order should renew nicely. Adding a check to verify there is a parent order before calling `$parent_order->get_meta` should solve it.

**Screenshots**

<img width="1506" alt="Screenshot 2023-04-14 at 7 28 25 AM" src="https://user-images.githubusercontent.com/7317227/232072936-905480be-e7c7-463c-8f72-d09a1d3d0366.png">

**Environment (please complete the following information):**
 - WordPress Version: 6.2
 - WooCommerce Version: 7.6.0
 - WooCommerce Subscriptions Version: 5.0.1
 - Stripe Plugin Version: 7.3.0
 - Browser [e.g. chrome, safari] and Version: n/a
 - Any other plugins installed: Newspack, but that's not relevant here.

**Additional context**

**Comment by claudiulodro** [comment]
I'll leave assigning the official priority for the team, but I would rate this high priority since it breaks all renewal payments on sites that have migrated to WooCommerce from other systems. In the meantime, rolling the plugin back to 7.2.0 solves the problem.

**Comment by claudiulodro** [comment]
https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2595 was filed a couple mins before this one. Closing as dupe.

**Comment by ericfri** [comment]
6224182-zen

**Comment by fernmed** [comment]
6236922-zen
