### ISSUE TITLE
Add support for Stripe receipts - populate [receipt_email] and [receipt_number]

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce-gateway-stripe#260]
Currently, we do not populate the `[receipt_email]` and `[receipt_number]` fields when sending transactions to Stripe. Instead, we only pass this as metadata. Because of this, you aren't able to use Stripe's built in receipt function.

It would be a very handy feature to add as some users rely on the receipts from Stripe.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
There is a reason for this as it caused issues. So we opted to turn it off by default. If they want it, they can use this filter `wc_stripe_send_stripe_receipt` and have it return true.

**Comment by roykho** [comment]
See https://github.com/woocommerce/woocommerce-gateway-stripe-private/issues/58

**Comment by TommiHynynen** [comment]
Hi! Could tell what kind of issues this filter might cause? For b2b customers, Woocommerce's order confirmations aren't enough, and most of those customers need actual payment receipt.
