### ISSUE TITLE
Recurring Payment Problem - WC_Stripe_API::request( $this->wps_sfw_generate_payment_request( $order, $source ) )

### ISSUE THREAD

**Issue by icarstudio** [woocommerce/woocommerce-gateway-stripe#2612]
**Describe the bug**
The bug occur when I try to start the recurring payment action calling wps_sfw_renewal_order_on_scheduler() function of the Suscription For Woocommerce plugin. This fuction call the function WC Stripe API::request() that use by default the param $api='charge'. Stripe Api response message in this situation is: "You cannot create a charge with a PaymentMethod. Use the Payment Intents API instead."

On the other hand, the first pay is done throught the CheckOut page and it is successfully because the it use "payment_intents".

**Screenshots**
![image](https://user-images.githubusercontent.com/132575997/236209499-edda634b-d40b-4555-8094-4403f791d783.png)

![image](https://user-images.githubusercontent.com/132575997/236209729-a50dfd6e-b1c8-4867-9d09-3719ff72a915.png)

![image](https://user-images.githubusercontent.com/132575997/236209882-38d9f0c2-d2a7-49e8-894d-2f5e40d6c7fe.png)

**Environment (please complete the following information):**
 - WordPress 6.2
 - WooCommerce 7.6.1
 - WooCommerce Stripe Gateway 7.4.0
 - Subscriptions For WooCommerce 1.4.9

**Comment by Mayisha** [comment]
Hi @icarstudio 👋 

Stripe plugin has integrated the PaymentIntents API that uses PaymentMethod both on the frontend and backend. 

> This fuction call the function WC Stripe API::request() that use by default the param $api='charge'.

You have to change the request on the Subscription For Woocommerce plugin and ensure it uses the `payment_intents/` endpoint. For reference, the Stripe plugin uses [this endpoint](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/trunk/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L981) for payment with a saved payment method.

I hope this helps. I am closing this issue as no change is needed on the Stripe plugin side.
