### ISSUE TITLE
Deleting customer on staging site detaches tokens from customer at Stripe, breaking live site saved payment methods (and subscriptions)

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce-gateway-stripe#2614]
**Describe the bug**
I've been told that if an admin user deletes WordPress users on a staging site (or any other duplicate copy of the live site, like a local dev copy), payment method tokens will be detached from customers on Stripe's side. In the case of a store with WC Subscriptions running, this can break future renewal payments.

**To Reproduce**
1. Go to `wp-admin` dashboard for a site with Stripe plugin
1. Go to **Users > All Users**
1. Click on radio box next to a user that has a saved payment method with Stripe
1. Click on the **Bulk actions** select field
1. Click on **Delete** option
1. Click **Apply**
1. Go to Stripe.com and open the dashboard for the corresponding Stripe account
1. Confirm customer is missing payment tokens 

**Expected behavior**
The payment method deletion or disconnection is expected behaviour when users are deleted form a live site; however, a staging site's activities should not interupt the activity on the live site. Therefore Stripe.com data, like customers and payment methods, should not be deleted when deleting corresponding data from a staging site.

This should be the case regardless of whether WC Subscriptions is running or not, even though the expected behaviour is most immediately impacted when running WC Subscriptions.

**Additional context**

I haven't reproduced this yet, but wanted to open an issue for this to be investigated after @NickGreen mentioned the behaviour to me yesterday.

**Comment by NickGreen** [comment]
Some notes of clarification:

- We did duplicate this exact behavior using the 3rd-party Stripe plugin and the WC Payments plugin.
- We found that this behavior _could_ be possible when cloning a production site to localhost for development reasons, in that there are detatch functions in the code, but we did not fully duplicate with the exact conditions above with the WC Stripe plugin.
- There are some cases where detatching a payment method from a customer might be desirable. For example, if the customer removes the payment method from their profile in WooCommerce, you can assume that they won't want that payment method still attached to their user in Stripe either.

More specifically, if you grep for functions that include `detach_payment_method` in both the Stripe plugin and the WC Payments plugin, you can see how the payment method is actually detatched from the user in Stripe, e.g.

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/b154ad8c9f72721716ca2d761861be505871b48c/includes/class-wc-stripe-customer.php#L485-L506

____

In our particular case, the site manager was so worried about this happening again, that we just removed the action from WC Payments completely like this:

```
if ( 'productionsite.com' !== $domain ) {
    t51_remove_action_by_method_name( 'woocommerce_payment_token_deleted', 'woocommerce_payment_token_deleted', 10 );
}
```

____

A potential solution to this, and other possible development site shenanigans, is if the WC Stripe plugin (and WC Payments plugin) would have some sort of handling of staging sites. Whether that's checking for primary domain or environment constant, and shutting off the live API connection.

**Comment by thenbrent** [comment]
Noting there is an open Issue for same problematic behaviour in WC Pay here https://github.com/Automattic/woocommerce-payments/issues/5384
