### ISSUE TITLE
Subscription Order With No Renewal Fee Fails With Stripe 7.4.0

### ISSUE THREAD

**Issue by theabhig** [woocommerce/woocommerce-gateway-stripe#2623]
**Describe the bug**

The specific use case is that a product is set up using WooCommerce Subscriptions and the product has a sign up fee, but no renewal fee.

For example:

![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/75635198/db39c86c-fb58-4b65-8678-4a4c305eb63d)

Using the latest version of WooCommerce Subscriptions, with the latest version of Stripe (7.4.0), this payment fails at checkout. 

**To Reproduce**

1. Set up a subscription product which has a sign up fee but 0 monthly renewal fee
2. Attempt to checkout with this product
3. It will generate a similar error to the following in Stripe:

![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/75635198/67005b01-db19-4c70-b496-413a0deec9a7)

4. Rollback Stripe to a previous version (I had tested with 7.0.1 originally) and see if the same product can be purchased successfully at checkout

**Expected behavior**

I would expect checkout to be completed and payment to be successful. This does work with previous versions of Stripe - I had tested with 7.0.1.

**Environment (please complete the following information):**

`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 7.7.0
REST API Version: ✔ 7.7.0
WC Blocks Version: ✔ 10.0.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.33
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.1.2
WC Database Prefix: wp_
Total Database Size: 57.92MB
Database Data Size: 42.46MB
Database Index Size: 15.46MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.16MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 2.52MB + Index: 0.91MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 2.52MB + Index: 1.05MB + Engine InnoDB
wp_FmeCCFA_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.27MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.27MB + Index: 2.08MB + Engine InnoDB
wp_postmeta: Data: 10.52MB + Index: 7.00MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 0.73MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.36MB + Index: 0.27MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.13MB + Index: 0.19MB + Engine InnoDB
wp_wc_order_stats: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.11MB + Index: 0.19MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 19.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1697
aw_workflow: 7
bookable_person: 4
bookable_resource: 10
custom-css-js: 1
fgf_rules: 1
follow_up_email: 5
global_product_addon: 1
gtw_custom_fields: 3
gtw_rules: 3
page: 14
post: 1
product: 381
product_variation: 420
revision: 32
shipping_package: 2
shop_coupon: 91
shop_order: 818
shop_order_refund: 4
shop_subscription: 67
wc_booking: 29
wc_membership_plan: 2
wp_global_styles: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Facebook for WooCommerce: by Facebook – 3.0.5
Jetpack: by Automattic – 12.2-a.9
WooCommerce Stripe Gateway: by WooCommerce – 7.4.0
WooCommerce Subscriptions: by WooCommerce – 5.1.2
WooCommerce: by Automattic – 7.7.0

### Inactive Plugins (74) ###

Akismet Anti-Spam: by Automattic – 5.1
AutomateWoo: by WooCommerce – 5.4.2
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.6.1
Bookings Helper: by WooCommerce – 1.0.3
Braintree for WooCommerce Payment Gateway: by WooCommerce – 2.6.1 (update to version 3.0.1 is available)
Bundle Builder For WooCommerce: by HighAddons – 1.0.0
Code Snippets: by Code Snippets Pro – 3.2.0
Codisto Channel Cloud: by Codisto – 1.3.61
Conditional Checkout Fields for WooCommerce: by FME Addons – 1.1.7
Follow-Up Emails: by WooCommerce – 4.9.22 (update to version 4.9.50 is available)
Free Gifts for WooCommerce: by FantasticPlugins – 6.8
Gift Wrapper for WooCommerce: by FantasticPlugins – 3.0
Login as User: by Web357 – 1.4.2
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
Minimum Periods for WooCommerce Subscriptions: by WP Extend – 1.4.0
Pinterest for WooCommerce: by WooCommerce – 1.2.2 (update to version 1.2.21 is available)
Printful Integration for WooCommerce: by Printful – 2.1.25
Product Bundle Discount: by Codup – 1.1.3.11
Simple Custom CSS and JS: by SilkyPress.com – 3.36
Smart Product Bundles For WooCommerce: by wpexpertsio – 1.1.4
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.42 (update to version 4.3.7 is available)
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.24 (update to version 1.1.40 is available)
WooCommerce Additional Variation Images: by WooCommerce – 1.9.0 (update to version 2.3.2 is available)
WooCommerce Admin: by WooCommerce – 3.3.2
WooCommerce Advanced Notifications: by WooCommerce – 1.2.30 (update to version 1.4.1 is available)
WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.8 (update to version 1.1.10 is available)
WooCommerce All Products For Subscriptions: by WooCommerce – 3.2.0 (update to version 4.0.6 is available)
WooCommerce Amazon S3 Storage: by WooCommerce – 2.1.22 (update to version 2.5.1 is available)
WooCommerce Blocks: by Automattic – 5.1.1
WooCommerce Bookings: by WooCommerce – 1.15.57 (update to version 1.16.0 is available)
WooCommerce Bookings Availability: by WooCommerce – 1.1.19
WooCommerce Box Office: by WooCommerce – 1.1.35 (update to version 1.1.51 is available)
WooCommerce Brands: by WooCommerce – 1.6.26 (update to version 1.6.49 is available)
WooCommerce Cart Add-Ons: by WooCommerce – 2.0.0
WooCommerce Checkout Field Editor: by WooCommerce – 1.7.2 (update to version 1.7.9 is available)
WooCommerce Composite Products: by SomewhereWarm – 8.1.2 (update to version 8.7.6 is available)
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.9.3 (update to version 1.14.6 is available)
WooCommerce Currency Converter: by WooCommerce – 1.6.27 (update to version 2.0.1 is available)
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.3.2 (update to version 5.4.1 is available)
WooCommerce Deposits: by WooCommerce – 1.5.6 (update to version 2.1.5 is available)
WooCommerce Distance Rate Shipping: by WooCommerce – 1.0.36 (update to version 1.3.0 is available)
WooCommerce Dynamic Pricing: by Element Stark – 3.1.26 (update to version 3.2.2 is available)
WooCommerce EU VAT Number: by WooCommerce – 2.4.0 (update to version 2.8.3 is available)
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.14 (update to version 2.5.5 is available)
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.1
WooCommerce Memberships: by SkyVerge – 1.22.0 (update to version 1.24.0 is available)
WooCommerce Min/Max Quantities: by WooCommerce – 4.0.7
WooCommerce Mix and Match Products: by Kathy Darling – 1.11.2 (update to version 2.4.5 is available)
WooCommerce Name Your Price: by Kathy Darling – 3.2.3 (update to version 3.5.3 is available)
WooCommerce One Page Checkout: by Automattic – 1.7.11 (update to version 2.3.0 is available)
WooCommerce PayFast Gateway: by WooCommerce – 1.4.18 (update to version 1.5.2 is available)
WooCommerce Payments: by Automattic – 3.5.0 (update to version 5.9.0 is available)
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1 (update to version 2.1.3 is available)
WooCommerce PayPal Payments: by WooCommerce – 1.3.1 (update to version 2.0.4 is available)
WooCommerce PDF Invoices: by Andrew Benbow – 4.13.3 (update to version 4.17.2 is available)
WooCommerce Points and Rewards: by WooCommerce – 1.6.43 (update to version 1.7.33 is available)
WooCommerce Pre-Orders: by WooCommerce – 1.7.1 (update to version 2.0.1 is available)
WooCommerce Product Add-ons: by WooCommerce – 4.1.0 (update to version 6.2.0 is available)
WooCommerce Product Bundles: by WooCommerce – 6.18.5 (update to version 6.18.6 is available)
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.54 (update to version 1.10.58 is available)
WooCommerce Product Vendors: by WooCommerce – 2.1.58 (update to version 2.1.78 is available)
WooCommerce Shipping & Tax: by WooCommerce – 1.25.22 (update to version 2.2.4 is available)
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.18 (update to version 2.5.0 is available)
WooCommerce Smart Coupons: by StoreApps – 4.19.0 (update to version 7.10.0 is available)
WooCommerce Square: by WooCommerce – 3.8.1
WooCommerce Subscriptions - Delete Cancel Subscription Confirmation: by Prospress Inc. – 1.0
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.1.0
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.3 (update to version 2.7.0 is available)
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.30 (update to version 3.1.1 is available)
WooCommerce UPS Shipping: by WooCommerce – 3.2.37 (update to version 3.4.2 is available)
WooCommerce USPS Shipping: by WooCommerce – 4.4.50 (update to version 4.6.3 is available)
WooCommerce Waitlist: by Neil Pie – 2.2.5 (update to version 2.3.8 is available)
WooCommerce Xero Integration: by WooCommerce – 1.7.37 (update to version 1.7.57 is available)
WP Mail Logging: by Wysija – 1.10.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
bundle_product (bundle_product)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.9.1 (update to version 4.2.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://theabhigwoofit.mystagingwebsite.com
Subscriptions-core Library Version: 5.7.1
Subscription Statuses: wc-active: 1
wc-expired: 2
wc-pending: 7
wc-on-hold: 50
wc-cancelled: 7

WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Alabama

### Subscriptions by Payment Gateway ###

Direct bank transfer: wc-on-hold: 2
other: wc-on-hold: 2
PayPal Standard: wc-cancelled: 1
wc-on-hold: 2

Stripe: wc-active: 1
wc-cancelled: 5
wc-expired: 1
wc-on-hold: 37
wc-pending: 7

### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions

PayPal Standard: subscription_payment_method_change_customer
subscription_payment_method_change_admin
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_delayed_change
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
products
refunds

PayPal Reference Transactions Enabled: ✔ Yes
Direct bank transfer: products
Check payments: products
Cash on delivery: products

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: product-block-editor
minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-22 06:29:04 +00:00
Options: ✔
Notes: 150
Onboarding: completed

### Action Scheduler ###

Complete: 171
Oldest: 2023-04-24 11:18:53 +0000
Newest: 2023-05-22 05:38:44 +0000

Pending: 9
Oldest: 2023-05-22 05:39:43 +0000
Newest: 2023-06-14 14:08:53 +0000

Failed: 8
Oldest: 2022-06-01 07:12:58 +0000
Newest: 2023-05-22 05:21:26 +0000

### Status report information ###

Generated at: 2023-05-22 05:38:49 +00:00
`

**Additional context**

6299029-zen

**Comment by paulostp** [comment]
6315769-zen

**Comment by Brianmitchtay** [comment]
This is essentially the same issue as #2607 and a fix to one should resolve both. Seems to be rooted in the Mandates functionality that was included in 7.3

**Comment by Brianmitchtay** [comment]
Closing in favor of #2607
