### ISSUE TITLE
VAT/taxes applied after checkout process even if customer exempted

### ISSUE THREAD

**Issue by dademaru** [woocommerce/woocommerce-gateway-stripe#2625]
**Describe the bug**
If a payment intent for a customer with **VAT exemption** fails and another payment is retried (maybe choosing a different source/card), **VAT/taxes are applied** generating a new ('processing') order instead of changing current order status from 'failed' to 'processing' _without applying VAT_.
The worst is that VAT is not applied during checkout process but when the payment intent happens, so the customer is charged for a total different from the one seen at Checkout when submitting order/payment.  

This is a very serious problem because the Shop Manager has to refund VAT/taxes to all users who are encountering this problem.

**To Reproduce**
It is assumed that taxes have been set in WC Settings.

1. Add the following code to enable tax exemption on checkout according to billing_postcode (for example, but you can use any condition you prefer):
```
add_action( 'woocommerce_checkout_update_order_review', 'dm_set_vat_exemption' );
 
function dm_set_vat_exemption( $post_data ) {
    WC()->customer->set_is_vat_exempt( false );
    parse_str( $post_data, $output );
    if ( $output['billing_postcode'] === '11111' ) WC()->customer->set_is_vat_exempt( true );
}
```
2. On checkout, once you enter 11111 as billing postcode (or satisfied any other condition set), taxes (VAT) are removed from order totals.
3. Try to pay with Stripe with a failing card (see https://stripe.com/docs/testing#three-ds-cards)
4. Once you get the failed message, try to pay again with a working card (e.g. test mode card)
5. While at checkout it still doesn't display taxes, on Thank You page you will see a different total, with taxes applied.

**Expected behavior**
Customer with VAT exemption must be exempted also on payment retries.
If the order total is the same, the 'failed' order changes to 'processing', without generating a new 'processing' order.

**Screenshots**
Before entering 'exemption postcode', VAT is applied:

<img width="988" alt="" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/1826139/50d8e1a8-8a16-4b1e-af70-e4f1b1a26315">

After entering 11111 as billing postcode, VAT is removed:

<img width="395" alt="" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/1826139/e398a28d-0189-45fd-b66a-d4f67742a110">

The VAT is applied on Thank You page, so the total paid by customer is different from the one seen at Checkout:

<img width="687" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/1826139/7e6d618d-b6e5-4b22-9c96-efec14f3d5b8">

**Environment:**
 - WordPress Version: 6.2.2
 - WooCommerce Version: 7.7.0
 - Stripe Plugin Version: 7.4.0
 - Storefront Theme Version 4.3.0 
 - Browser Chrome 113.0.5672.126

I think it's easy to reproduce the bug. Otherwise I will provide further details.

I suppose the error occurs in `WC_Gateway_Stripe::verify_intent_after_checkout`
when you clear cached session data (included `vat_exemption`) with `clean_post_cache( $order->get_id() );`.

As a solution, I think you must check if failed order has vat exemption and re-apply it after clearing session data:

```
if ( $order->get_meta( 'is_vat_exempt' ) ) {
	WC()->customer->set_is_vat_exempt( true );
}
```

Hope it could be fixed soon since our client is experiencing big losses, having to refund all the taxes wrongly charged every time an order with Stripe fails and then is completed.

Thanks

**Comment by wjrosa** [comment]
I think the issue might be with the snippet itself. Your snippet was hooked into `woocommerce_checkout_update_order_review`, which is not executed during the regular checkout flow (at any type of checkout). That is executed only when the checkout form changes (like the zip code field).

The snippet runs when you set your zip code to `11111`, setting `set_is_vat_exempt` to `true`. Then, when you try using a failed card, the flag is reset. Trying again does not trigger the `woocommerce_checkout_update_order_review` to set the flag again.

You can achieve what you want by hooking into another action (and keeping the original above):

```php
add_action( 'woocommerce_checkout_create_order', 'dm_set_vat_exemption_create_order', 100, 2 );

function dm_set_vat_exemption_create_order( $order, $data ) {
	WC()->customer->set_is_vat_exempt( false );
	$order->add_meta_data( 'is_vat_exempt', false, true );
	if ( $data['billing_postcode'] === '11111' ) {
		WC()->customer->set_is_vat_exempt(true);
		$order->add_meta_data( 'is_vat_exempt', true, true );
	}
	$order->save();
}
```

We are also updating the order meta directly because the `woocommerce_checkout_create_order` hook is triggered after the meta is saved (inside `WC_Checkout::set_data_from_cart`).

**Comment by wjrosa** [comment]
I will be closing this for now. Let us know if we should re-open it.
