### ISSUE TITLE
Order: Showing user paid $0, Stripe charged correct amount, not delivering digital product

### ISSUE THREAD

**Issue by klongdesigns** [woocommerce/woocommerce-gateway-stripe#263]
#### What I expected

A user places an order and pays via Stripe. Upon successful completion of order, it delivers the downloadable product to them.

#### What happened instead

A user places an order and pays via Stripe. The get a successful completion of order, but the product is never delivered to them.  The reciept page doesn't have the link to the file. When I looked at the order, under the line items, it shows the product costing $0.00, but the total and total charged is the correct amount:

Product Name                   $0.00   × 0       $0.00

 Discount:		$0.00
 Shipping:		$0.00
Order total:		$5.00

We also have paypal active, and when they pay via paypal, this issue doesn't happen, so we've narrowed it down to the Stripe plugin. NOt sure why it's happening or how to fix it.

**Comment by roykho** [comment]
Please provide more detail such as what WC version, what Stripe version. Are you using Stripe checkout or regular Stripe form. Are you using delay capture or not. What theme are you using? Have you tested by deactivating all plugins except WC and Stripe? Have you switch a theme to see if there is a conflict?

**Comment by klongdesigns** [comment]
WC version: 3.0.7
Stripe Version: 3.1.8
Using Capture charge immediately
Using Custom Theme

Used default theme and disabled all plugins. Issue still happened on order. When I looked at the order, at the bottom, under "Downloadable Printable Products", there are none listed, but the order clearly shows it. We then processed the same order but through paypal, and product showed up there.

It seems like what is happening is that the order is being completed, but the product isn't being released to download.

**Comment by roykho** [comment]
No issues here.
![](http://cld.wthms.co/L0vtx+)

**Comment by PBNG** [comment]
I have the same exact issue. Order showing 0€ on item, full price on total, and not allowing the customer to download the digital product. As klongdesigns, capture inmediately. With Paypal, no problem

WOOCOM Version 3.2.3
Stripe Gateway Version 3.2.3
Custom Theme.

Any toughts?

The web is www.miriamtirado.com

**Comment by roykho** [comment]
@PBNG try turning off your cache and re-test.
