### ISSUE TITLE
Check $source_id for possible null values before passing to add_source() 

### ISSUE THREAD

**Issue by kaushikasomaiya** [woocommerce/woocommerce-gateway-stripe#2632]
Opening as directed in p1685693515635679-slack-C7U3Y3VMY

6319718-zen

Merchant reported the following fatal error while adding SEPA Payment method from Payment Methods page:

> Fatal error: Uncaught TypeError: WC_Stripe_API::get_payment_method(): Argument #1 ($payment_method_id) must be of type string, null given, called in /Applications/MAMP/htdocs/woogenerator/sites/wp-8311966/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-customer.php on line 300 and defined in /Applications/MAMP/htdocs/woogenerator/sites/wp-8311966/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-api.php:284 

> Stack trace: #0 /Applications/MAMP/htdocs/woogenerator/sites/wp-8311966/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-customer.php(300): WC_Stripe_API::get_payment_method(NULL) #1 /Applications/MAMP/htdocs/woogenerator/sites/wp-8311966/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php(1178): WC_Stripe_Customer->add_source(NULL) 

Original from merchant's site:

![https://d.pr/i/jSkENA](https://d.pr/i/jSkENA+) 
Full Size: https://d.pr/i/jSkENA

It appears that the null value might be coming from the $source_object 

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/720acf1ccf90fbc56ce74f2d85ff6dacce2eb7b1/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L1178

Opening this for investigation.

**Comment by kaushikasomaiya** [comment]
Also reported:

- https://wordpress.org/support/topic/php-8-2-fatal-error-2/
- 6250222-zen
- 6364760-zen
- 6233823-zen

**Comment by kaushikasomaiya** [comment]
6353556-zen

**Comment by mouligreenlaw** [comment]
6492719-zen

**Comment by Babylon1999** [comment]
zd-6498748 

Asking them if this happens with cards, bank payments or both.


EDIT: They confirmed it happens with both.

**Comment by therealgilles** [comment]
This is majorly broken in v7.4.2.

I reverted to v7.4.1. and somehow got a file permission issue on this file, but maybe that was due to the revert (I use `git` locally):
  wp-content/plugins/woocommerce-gateway-stripe/assets/js/stripe.min.js
