### ISSUE TITLE
Undefined property errors in process_response for WP_Error->id et al

### ISSUE THREAD

**Issue by javorszky** [woocommerce/woocommerce-gateway-stripe#265]
#### What I expected

That the plugin works in trivial situations without throwing php notices.

#### What happened instead

When an order uses a customer token that doesn't exist in the Stripe account, the `$response` variable passed to `process_response` [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L850) is going to be an instance of WP_Error instead of whatever Stripe would return. From the logs:

```
05-19-2017 @ 13:37:05 - Processing response: WP_Error Object
(
    [errors] => Array
        (
            [stripe_error] => Array
                (
                    [0] => No such customer: cus_AgXkqNYGIwCKSv__
                )

        )

    [error_data] => Array
        (
        )

)
``` 

#### Steps to reproduce the issue

1. have `WP_DEBUG` be turned on on the site.
1. have Subscriptions, sign up for a subscription.
2. take a note of the customer token
3. either go into your Stripe dashboard (test) and delete the customer with that token, OR change the token to something else. You might also need to delete the card token / change that token too.
4. go back to the edit subscription screen, and from the actions select "Process renewal", which will attempt to pay for the renewal order, but which will fail.
5. take a look at your debug.log file

#### Environment

* WC 3.0.7 (release)
* Stripe 3.1.8 (release)
* Subs https://github.com/Prospress/woocommerce-subscriptions/commit/12a9a97feabf67c2ff7cf30910f64220d0d278fd (basically latest master at the time of writing)

Potentially related issue: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/252

**Comment by roykho** [comment]
This is already fixed in master.
