### ISSUE TITLE
HTML tags are not striped  in the MultiBanco confirmation email

### ISSUE THREAD

**Issue by Babylon1999** [woocommerce/woocommerce-gateway-stripe#2651]
**Describe the bug**
The Multibanco confirmation email is adding HTML tags to the transaction details.

<img src="https://d.pr/i/SrzVK7+" alt="">
Link to image: https://d.pr/i/SrzVK7

**To Reproduce**
Order using Stripe [Multibanco](https://www.multibanco.pt/)

<img src="https://d.pr/i/QOVAil+" alt="">
Link to image: https://d.pr/i/QOVAil

**Expected behavior**

The HTML tags to be stripped out.

**Environment (please complete the following information):**
WC Version: 7.8.2
WP Version: 6.2.2
Stripe plugin 7.4.1

**Comment by Babylon1999** [comment]
reported in zd-6483684

**Comment by anastas10s-afk** [comment]
Another report, about it affecting both front-end and emails:
https://wordpress.org/support/topic/stripe-multibanco-class-issue/

**Comment by anastas10s-afk** [comment]
Related issue: #2641

**Comment by xue28** [comment]
Another report here: 7295641-zd (Internal)
