### ISSUE TITLE
Apple Pay errors do not show up on Checkout page with many themes, including Storefront

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce-gateway-stripe#2658]
**Describe the bug**
When a customer tries to pay using Apple Pay and they come across an error (such as https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2618) they will not see any errors on some themes.

**To Reproduce**
1. On a clean install, enable Stripe and Storefront
2. Add a product to your cart and go to checkout
3. Pick a country that doesn't have Counties, for example Romania
4. Try to pay using Apple Pay

**Expected behavior**
The default woo validation expects you to enter a shipping and billing county, but they do not exist for the selected Country, so an error should come up.

**Actual behavior**
On storefront and any other theme that doesn't have `.shop_table.cart`, the error will not show up.

https://github.com/woocommerce/woocommerce/blob/7.8.2/plugins/woocommerce/templates/checkout/form-checkout.php#L58-L60

in this function https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/assets/js/stripe-payment-request.js#L157-L173 the code searches for where to place the error, and is looking for a cart shop table. that exists on the cart template (https://github.com/woocommerce/woocommerce/blob/7.8.2/plugins/woocommerce/templates/cart/cart.php#L25) but not on the checkout.

**Comment by thenbrent** [comment]
Thanks for the detailed steps to reproduce here @glagonikas. I'm going to give this a high priority label as I hope it is a relatively quick fix and something that can save errors on checkout (potentially causing lost sales).

**Comment by SvenMuellerDD** [comment]
Is there anything new? We really need it fixed soon. Thx 🙏

**Comment by jynxy** [comment]
any news or temp fix for this ?

**Comment by mattallan** [comment]
Closing this as it was fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2690. It was released in 7.7.0 on Nov 2023
