### ISSUE TITLE
WC 3.0 compatibility warnings 

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce-gateway-stripe#266]
#### Affected ticket(s)

https://woothemes.zendesk.com/agent/tickets/569950

There are a couple of instances of these warnings in the site's error log: 

```
stripe_customer_id was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_Stripe_Addons->process_payment, WC_Gateway_Stripe->process_payment, WC_Gateway_Stripe->process_response, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_changed'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Subscriptions_Renewal_Order::maybe_record_subscription_payment, do_action('woocommerce_subscriptions_paid_for_failed_renewal_order'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Subscriptions_Change_Payment_Gateway::change_failing_payment_method, do_action('woocommerce_subscription_failing_payment_method_updated_stripe'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Gateway_Stripe_Addons->update_failing_payment_method, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.,
```

Following the stack trace it leads to [`WC_Gateway_Stripe_Addons::update_failing_payment_method()`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe-addons.php#L312-L313). 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Hi @james-allan - Thanks for reporting. Do you have specific steps I can use to reproduce this?

**Comment by james-allan** [comment]
Hey @roykho, sorry here are the steps to replicate: 
1. Make sure you have the WCS automatic retry system disabled from **WC > Settings > Subscriptions** tab (https://cloudup.com/cHD9sCUueTw) 
2. Meddle with a subscription's payment meta to force a failed renewal (https://cloudup.com/cdrQ0rYotbO)
3. Process a renewal payment from the subscription actions dropdown (https://cloudup.com/cB0_bGF_min)
4. Go to the My Account page and manually pay for the failed order

It's quiet a finicky warning to replicate but it's quiet a simple fix. You'll just need to replace the 

```php
$renewal_order->stripe_customer_id
$renewal_order->stripe_card_id
```

with `get_post_meta()` calls or a WC 3.0 equivalent on these lines https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe-addons.php#L312-L313.
