### ISSUE TITLE
PaymentMethods of type card cannot be attached to Customers directly without 3DS due to Indian payment regulations.

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#2664]
**Describe the bug**
Recurring payments are not working for INR

**To Reproduce**
1. Shop location Inida, currency INR
2. Try to purchase a subscription

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**
p1682659323078299-slack-C7U3Y3VMY

6208763-zd-woothemes

**Comment by wyter** [comment]
Checking on the prioritization of the bug, or if anything else is needed from HEs

**Comment by ramshengale** [comment]
The following error comes with Woocommerce Subscriptions plugin when the currency is INR and selected country is India.

> PaymentMethods of type card cannot be attached to Customers directly without 3DS due to Indian payment regulations. Please instead provide the PaymentMethod and Customer alongside a SetupIntent or PaymentIntent with the `setup_future_usage` parameter. See https://support.stripe.com/questions/guide-for-saving-cards-in-india for more details.

**Comment by ramshengale** [comment]
Looking forward to getting this issue resolved as we're eagerly waiting for move all our Indian subscriptions to Stripe.

**Comment by Snaacks** [comment]
ZD-6745277

**Comment by Mehakkathpal** [comment]
working with test card data while using real card facing same issue . please look into this

**Comment by Mehakkathpal** [comment]
remove this from your code , maybe because this will exclude client verification to save card in stripe. It's working for me now.
stripe.PaymentMethod.attach(payment_method_id, customer=customer_id)

**Comment by pmjcreations** [comment]
If working with a test card and not with a real card means your card issuer is declining the payment.

**Comment by Mehakkathpal** [comment]
> If working with a test card and not with a real card means your card issuer is declining the payment.

It is working with real card as well now . @pmjcreations

**Comment by ramshengale** [comment]
Hello team, when is the fix planned to be released?

**Comment by chrism245** [comment]
7228839-zd

**Comment by pmjcreations** [comment]
Thank you, @Mayisha ❤️
