### ISSUE TITLE
Order put on-hold, a immediately moved back to processing when payment is marked for-review by radar rule

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#2679]
**Describe the bug**

Transactions are labeled as `for review` by Stripe radar rules and placed `on-hold` in WooCommerce, but then immediately set to `processing` likely because of a `charge.succeeded` webhook.

It might be a similar problem than https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2536

**To Reproduce**
No consistent way of reproducir the issue found.

**Expected behavior**
The order remains in `on-hold` status until the payment is reviewed in the Stripe Dashboard.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**
p1691657520301449-slack-C7U3Y3VMY

**Comment by mattdelliott** [comment]
I have also noticed a lot of strange behavior with Stripe payments in WooCommerce. 

For example:

We received a webhook where the subscription was `active` and the `date_modified_gmt` was `2023-09-11T15:19:00` but it says the `date_paid_gmt` is `2023-09-11T15:19:00`

Then a little less than an hour later, we got another where the status was `on-hold` and the `date_modified_gmt` was `2023-09-11T16:38:57` and the `date_paid_gmt` reverted to `2023-08-11T15:18:07`

What is really odd is the second webhook (the `on-hold` webhook) also had `next_payment_date_gmt` set to `2023-09-11T15:18:07` but the `last_payment_date_gmt` was set to `2023-09-11T16:38:57` so the next payment date was less than the last payment date. 

We never received a webhook when the status went back to `active`

**Comment by kingsleyinfo** [comment]
Another issue reported today

7858179-zd

**Comment by markwill890** [comment]
I reported this (latest) issue. If it helps, please be aware that I had two orders an hour apart from the same person. Both triggered the Stripe RADAR rule. However, one (the one I reported) was changed (inappropriately) to Processing by WooCommerce. The other order correctly remains at On Hold.
