### ISSUE TITLE
Can't refund

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#269]
#### Affected ticket(s)
ticket: 574646-zd-woothemes

#### What I expected
To be able to issue a refund

#### What happened instead
When attempting to issue a refund, get a message similar to "An error occurred while attempting to create the refund using the payment gateway API."

#### Steps to reproduce the issue

1. Stripe is set to authorize instead of capture
2. Go through the checkout process
3. Order is set to on-hold as expected
4. Change the order to processing
5. Initiate a refund, see message as noted above because the transaction id wasn't set when capturing the charge and so process_refund returns false here https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3.1.9/includes/class-wc-gateway-stripe.php#L937

@mattyza 

-------------------

- [ ] Issue assigned to next milestone.
- [ x] Issue assigned a priority (will be assessed by maintainers).

**Comment by room34** [comment]
It looks to me like this change will solve the problem on any _future_ orders placed after this code is in place, but it won't resolve the issue for earlier orders. I suppose there's not a way to obtain the `_transaction_id` value after the fact, so maybe there's nothing else that can be done.

**Comment by roykho** [comment]
This only affected authorized first capture later setups. Also yes you can still get the ID, it is under the meta name `Stripe Payment ID`.

**Comment by room34** [comment]
My client's site is set to capture later. They're running into this same error message when trying to process a refund. The orders in question have `Stripe Payment ID` meta data, but do not have `_transaction_id`. My understanding of this ticket is that it's describing the same scenario I'm seeing, and without `_transaction_id` the refund can't be processed. Is that incorrect?

**Comment by roykho** [comment]
That is correct. But again you can backfill the `_transaction_id` with the value found in the `Stripe Payment ID` and you will have a working auto refund. Note that you can still manually refund even without any id, it just becomes a two step process instead of one.

**Comment by room34** [comment]
Thanks. I will manually set that value and see if it resolves things. Still I'm wondering if there couldn't be a way to automate filling in `_transaction_id` if it's blank and `Stripe Payment ID` isn't, so this fix would work retroactively. (I started poking around the code for potential hooks but didn't see anything.)

**Comment by jessepearson** [comment]
@roykho @room34 From what I understand in these last comments, even if a store admin installs this new version, they are not able to refund older orders, correct?
