### ISSUE TITLE
Missing intent on orders paid via the `order-pay` endpoint with UPE active

### ISSUE THREAD

**Issue by ahegyes** [woocommerce/woocommerce-gateway-stripe#2693]
**Describe the bug**

When UPE is active, orders that are paid for via the `order-pay` endpoint never update their status. They either stay in `pending-payment` (if the order was created via the admin interface, e.g.), or in `failed` (if the order was created through a failed checkout experience).

**To Reproduce**
1. End up with an unpaid order in my-account, either through a failed checkout (e.g., because of a declined card) or by adding an order manually through the admin interface
2. Go to the pay-order endpoint of the (new) order awaiting payment
3. An AJAX request is sent to `?wc-ajax=wc_stripe_create_payment_intent` that always succeeds
4. After inputting the CC details and clicking on the Pay now button, an AJAX request is sent to `?wc-ajax=wc_stripe_update_payment_intent` that always fails with the error message `Unable to verify your request. Please reload the page and try again.`
5. Despite the error message, the customer is charged, Stripe shows the charge as successful, and the customer is redirected to the order-received endpoint … the order itself, however, stays in either the Failed or Pending payment status (depending on why the order needed payment, because of failed checkout or new admin order)

I followed the flow of the checkout attempt and discovered that the error message is coming from [this exception here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/88b180468c11b89d19fcdec7fcc0f0d6a63e72a0/includes/class-wc-stripe-intent-controller.php#L374). Indeed, the error log also contains the lines `Could not find order via intent ID: XYZ` and `Could not find order via charge ID: XYZ` at the same time. Orders created through the admin interface do not have the meta field _stripe_intent_id at all and those generated through a failed order have it, but it’s the “old” intent, not the one returned by `?wc-ajax=wc_stripe_create_payment_intent`.

**Expected behavior**
That if the customer was charged and Stripe processed everything successfully, the order updates in the status `processing`. As far as I can tell, the issue is that the intent ID generated by the call to ?wc-ajax=wc_stripe_create_payment_intent is never saved to the order itself thus causing the webhook delivery to fail once Stripe processes the payment.

This does not happen if I deactivate UPE, and everything works fine then.

**Additional context**
p1693558484043169-slack-CHG7MTCAF

**Comment by ecairol** [comment]
I wonder if this is somehow related to https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2536

**Comment by ahegyes** [comment]
> I wonder if this is somehow related to https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2536

Not sure because here the `_stripe_intent_id` meta is completely missing on the orders after payment is processed. So it's not a race condition 🤔

**Comment by ecairol** [comment]
@ahegyes that makes sense. To better express myself: I was wondering if the race condition reported on the other bug could find an explanation in the steps that you describe here, related to UPE and the `order-pay` endpoint.

When I saw "_webhook_", "_UPE_" and orders in "_pending_" status it rang a bell and I thought I'd cross-post the other GitHub issue just in case someone can kill two birds with one stone.

**Comment by wjrosa** [comment]
This issue cannot be reproduced currently on our deferred intent branch (`add/deferred-intent`). We will try again when that project is merged to see if the issue comes back before closing this.

**Comment by wjrosa** [comment]
With the release of [8.0.0](https://github.com/woocommerce/woocommerce-gateway-stripe/releases/tag/8.0.0), this issue cannot be reproduced anymore. Closing this.
