### ISSUE TITLE
Bank statement length validation isn't accurate when using non-Latin characters

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2696]
**Describe the bug**
When including non-Latin characters in the bank statement, a validation error is thrown, stating that the string is shorter than the expected length, even though it has the expected one.

**To Reproduce**
1. Go to the Stripe plugin settings page `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings`
2. Go to Payments & transactions -> Customer bank statement
3. Enable "Add customer order number to the bank statement" and save
4. Add a statement descriptor that contains a non-Latin character at the beginning of the string, like `جَdashop`, and save
5. Notice an error message shows up containing the error reason saying "Has between 5 and 22 characters"

**Expected behavior**
Because the string has the expected length, the validation error message must not mention the length.

**Screenshots**
![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/457c8a37-53b2-406b-9909-76057c4da5ad)

**Additional context**
Mentioned in the review of this other PR https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2682#pullrequestreview-1595217521

**Comment by diegocurbelo** [comment]
Closing this issue as recent plugin versions use the Bank statement defined in the Stripe dashboard.
