### ISSUE TITLE
Refunds arent beign processed because of the transaction ID

### ISSUE THREAD

**Issue by Lunatikzx** [woocommerce/woocommerce-gateway-stripe#270]
when we are trying to refund our customers on stripe the automated refund is not working. 
I found the cause, this is due to the transaction id not being inserted in the transaction, 

The plugin should process the refund automatically.

An alert box apperread with the error in the screenshot
![capture d ecran 2017-05-29 a 09 34 25](https://cloud.githubusercontent.com/assets/1518503/26584731/d61620ee-4517-11e7-8273-fbd0d6dc5b6a.png)

- Buy a product
- Pay with stripe
- Try to refund it automatically

Personnal note:
The bug is linked with the transaction id that does not get added to the order when the order is paid with stripe. 

So when in the process_refund method, the get_transaction id will never work.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Already fixed in master and will be released.
