### ISSUE TITLE
Error "Payment processing failed" with backend log "Error: stdClass Object"

### ISSUE THREAD

**Issue by edoardomazzon** [woocommerce/woocommerce-gateway-stripe#2719]
**Describe the bug**
It has happened to some users that when they click on the "Make payment" button with everything filled out correctly in the checkout, the payment fails and the "Payment processing failed" error appears. Looking at the woocommerce and woocommerce-stripe-gateway logs, it appears that the errors are stripe "Error: stdClass Object". Can someone help me? I would like to resolve this because it has been happening to some users for several weeks and I need to resolve the problem. I have always done the updates as soon as they come out to stay in line with any bugs but it doesn't seem to have worked.

**Screenshots**
<img width="355" alt="Schermata 2023-10-04 alle 17 12 43" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/58985370/5a3d6e13-e81b-447d-99b9-0f4a367907c9">
<img width="305" alt="Schermata 2023-10-04 alle 17 13 40" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/58985370/ab880722-c072-4629-acbf-e3700c4d8a78">

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version: 8.1.1
 - Stripe Plugin Version: 7.6.0
 - Browser [e.g. chrome, safari] and Version: Chrome Mobile 99.0.4844
 - Any other plugins installed: YITH WooCommerce Order & Shipment Tracking Premium (2.18.0) and Sequential Order Numbers for WooCommerce (1.5.5)

**Comment by kdingsa8c** [comment]
Also reported in 7569658-zd-a8c
