### ISSUE TITLE
Apple Pay doesn't include tax if no shipping zone is set

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce-gateway-stripe#272]
When shipping zones have not been set, as in the case of shops selling only virtual products, tax is not calculated.  This occurs even when tax is set to be calculated based on billing address.

1. Remove all shipping methods
2. Add a tax rate
3. Purchase a product with Apple Pay

With Shipping Method: 

![](http://cld.wthms.co/o5wz2r+)

Without Shipping Method:

![](http://cld.wthms.co/v4xQ7+)

**Comment by roykho** [comment]
@mdmoore is this with public release or with master branch?

**Comment by mdmoore** [comment]
This is with the public release.

**Comment by roykho** [comment]
@mdmoore would you mind testing master?

**Comment by mdmoore** [comment]
Works great!  Thanks @roykho!

**Comment by mdmoore** [comment]
I spoke too soon.  This is still present in master.

**Comment by roykho** [comment]
Ok after looking into this more, I don't think there is a solution to this. Apple Pay simply does not provide the billing address from the Apple Wallet account and therefore WC can't determine what the taxes will be without an address. This is assuming WC is set to no default location. WC can be set to "shop base" which means it will determine the tax based on the store's location. But this may not always be favorable.

I cannot think of a good work around for this. They can add the taxes to only the virtual products to be inclusive of taxes but that would mean everyone would be taxed on it regardless of their billing location.

cc @mattyza

**Comment by mattyza** [comment]
Thanks @roykho. I'll flag this with Apple Pay, and see if we can find an answer here.

**Comment by roykho** [comment]
This is not currently possible as no billing address is exposed when payment sheet opens. So the work around is that on product detail page final amount is pending and once they submit, then the address is exposed and we calculate the final amount then. This is what is suggested by Stripe as well.

**Comment by mikepalmeruk** [comment]
Hi there, I use Apple Pay from Stripe in my woocommerce setup but noticed the tax is not being added. Any ideas?

**Comment by roykho** [comment]
Hi @mikepalmeruk so this is not the place for support. But for repeatable documented steps. You should ask your questions here https://wordpress.org/support/plugin/woocommerce-gateway-stripe/
