### ISSUE TITLE
The charged amount is divided by 10 for three-decimal currencies

### ISSUE THREAD

**Issue by Babylon1999** [woocommerce/woocommerce-gateway-stripe#2720]
**Describe the bug**

Originally reported in zd-7121714

https://wordpress.org/support/topic/three-decimal-currencies-are-unsupported/

When the site currency is set one of the [three decimal currencies here](https://stripe.com/docs/currencies?presentment-currency=AE#three-decimal), the total will be divided by 10. So if an order total is 35.20, Stripe will only charge 3.5.

**To Reproduce**

- Switch your Stripe test account to a region that [supports these currencies](https://stripe.com/docs/currencies?presentment-currency=AE#three-decimal), such as the UAE. 

<img src="https://d.pr/i/VcCB6v+" alt="">

- Set the site currency to BHD (Bahraini or Jordanian Dinar).
- Try to place an order.
- Check the amount charged in Stripe.

<img src="https://d.pr/i/b13Ivp+" alt="">
Link to image: https://d.pr/i/b13Ivp

<img src="https://d.pr/i/KyQzxo+" alt="">
Link to image: https://d.pr/i/KyQzxo

**Expected behavior**
The order amount should be charged exactly as it is displayed in WooCommerce.

**Comment by Abd-Basaleh** [comment]
I need help with the K.W.D. currency. When processing an order with an amount such as 18.60 Kuwaiti dinars (KWD), the plugin should accurately charge the total amount. However, the plugin is sending the amount as 1.860 KWD, which is considerably lower than the correct amount and is unacceptable.

[Stripe Payment Details](https://ibb.co/89PmVmW)

[Website Order Details](https://ibb.co/KVqStRT)

**Comment by thomasjvu** [comment]
7728041-zen

**Comment by flagshippro** [comment]
I am facing the same issue with Jordanian Dinar. I am purchasing 9 JOD item in woo commerce but stripe is charging 0.9 JOD.

**Comment by umairali** [comment]
I am facing the same issue with the Jordanian Dinar. I am purchasing 9 JOD items in WooCommerce, but Stripe charges 0.9 JOD.
