### ISSUE TITLE
Double refunds still happening (triggered through web hook)

### ISSUE THREAD

**Issue by danielvonmitschke** [woocommerce/woocommerce-gateway-stripe#2724]
Despite this bugfix (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2581) I can still see double refunds in rare cases.
Above bugfix usually prevents this by comparing refund ids and aborting the web hook if the refund id equals an already existing refund.
But I think what might happen in rare cases is the following:
- A refund is created in WooCommerce and the stripe api is called returning the refund id.
- This refund id is then save with the order.
- If the response takes unusual long it can happen that the web hook (triggered by the api request) arrives before the api response is handled (and the refund id is saved) and therefore resulting in a double refund.

An easy but maybe not very elegant fix could be a simple `sleep(5)` in the first line of the [`process_webhook_refund()`](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/7483c210b0fc1655018526b3c8518a8241a8ce78/includes/class-wc-stripe-webhook-handler.php#L547) method.
This would give a bit more time for the original api response to be handled.

**Comment by danielvonmitschke** [comment]
This issue is still present

**Comment by DSCreative** [comment]
Still happening for me too well over 2 years after this was first reported. This really needs fixing. There are so many reports of this issue. Every time we process a partial refund, the system shows it twice, sends two emails, etc. Stripe only refunds the correct amount, but it is really messy.

**Comment by Mayisha** [comment]
This issue is fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3653
