### ISSUE TITLE
Authorized payment automatically captured despite settings

### ISSUE THREAD

**Issue by zyphlar** [woocommerce/woocommerce-gateway-stripe#2726]
**Describe the bug**
When placing a test order using the Stripe Test API and card, and WooCommerce Stripe set to authorize and capture separately, the test order is nonetheless captured without manual intervention.

**To Reproduce**
1. Install fresh Wordpress, Woocommerce, and Stripe plugin from Woocommerce.com
2. Set Stripe plugin to authorize and capture separately
3. Place a test order in test mode using a test card (note the order is for a physical good, not a subscription or digital product)
4. Note the order is captured instantly

Also note the behavior is the same with or without the New Checkout Experience.

**Expected behavior**
Orders should only be captured manually when selected

**Screenshots**
![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/48434/d2c87a9a-da37-4708-9439-79f561593673)

**Environment (please complete the following information):**
 - WordPress Version 6.2.2
 - WooCommerce Version 7.8.1
 - Stripe Plugin Version 7.6.0 (downloaded from woocommerce website)
 - Browser [e.g. chrome, safari] Firefox latest

**Additional context**
Two-step auth/capturing works for physical products when we use PayPal (AngellEye) but not for recurring/subscriptions, so there doesn't seem to be a reason it shouldn't work for Stripe, however I did just set up the Stripe account today and we're using a staging copy of the wordpress site.

**Comment by zyphlar** [comment]
I have no indication that it's not still happening; I was testing this plugin to see if a switch was possible and this is a dealbreaker, so I'd have to load up a whole environment and retest to verify. I presume it's still an issue.

**Comment by wjrosa** [comment]
Hey @zyphlar ! I just tested this behavior multiple times with different scenarios, and everything seems to be working as expected. We fixed a bunch of issues since this was opened, so I believe the bug was fixed since then. I will be closing this for now. If you have the chance to test it again, and it is still happening for you, let us know so we can reopen the issue.
