### ISSUE TITLE
[Settings] Implement the same Settings screen for both non-UPE and UPE integrations

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2734]
### Current screens

| Description | non-UPE | UPE |
|--------|--------|--------|
| Payment methods list | <img width="3264" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/22e0ec8a-1575-4138-90ba-9c54072e84d7">  <img width="3282" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/32be7cf4-c2e1-44d2-b23c-807b8d0f4c1c"> | <img width="3254" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/f84fcd07-cc0d-4f36-a3fd-e9497f0fc0ca"> <img width="2190" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/747344e2-042e-4b25-a9ba-e43b9d47185c"> |
| APM's configurations | <img width="3260" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/320b7150-792a-4972-abc3-3f0b70fc0c09"> | Don't exist |

### New design

- Both non-UPE and UPE implementations will share the following screen for configuring the payment methods
xVAk98kbRKUByVTrhPc98g-fi-693_31677
- The options specific to each payment method can be adjusted by clicking on the "Customize" button in each row xVAk98kbRKUByVTrhPc98g-fi-616_38223

### Some considerations
- The Link express method must continue to be available only for UPE
- When UPE is enabled, the "Customize" button must be hidden. It'll be displayed again during the new UPE implementation.
- As possible, the way the settings are stored should be backward compatible for the non-UPE implementation. For example, the title and description set for a payment method in this version must persist if the merchant returns to a previous version. And the settings from previous versions must persist when upgrading to this version. This should be true for:
  - Enabled payment methods
  - Specific options for each of the alternative payment methods

### Out of the scope of this issue
These functionalities will be handled in separate issues:
- Changing the display order of the payment methods. There's a button in the design named "Change display order".
- The banner titled "The new checkout experience will be available soon".
- The new interface for flagging whether a payment method requires activation or a specific currency.

**Comment by Mayisha** [comment]
As #2750, #2792 and #2811 PRs have been merged, we can consider this issue completed.
