### ISSUE TITLE
[Settings] Allow changing the display order of payment methods

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2735]
This issue is blocked by https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2734

### The design

- When clicking on the "Change display order" button, a merchant can drag and drop the payment methods to reorder them: xVAk98kbRKUByVTrhPc98g-fi-616_33462
- There's a dismissible banner on top of the Payment methods section xVAk98kbRKUByVTrhPc98g-fi-603_28309

### Some considerations

- When UPE is enabled, we'll disable reordering. This will be enabled again when split UPE is implemented.
- For non-UPE, the order defined here must be reflected on the checkout page.
- When a merchant upgrades from a previous version and non-UPE is enabled, the order of the payment methods from the WooCommerce -> Settings -> Payments page must persist.
- If possible, the display order of the non-UPE payment methods would be backward-compatible. The order would persist if the merchant rolls back to a previous version.

**Comment by Mayisha** [comment]
This can be closed with PR #2756 and #2808 merged
