### ISSUE TITLE
Apple Pay not pulling Product Add-Ons order information

### ISSUE THREAD

**Issue by stevetested** [woocommerce/woocommerce-gateway-stripe#274]
#### Affected ticket(s)

580506-zd-woothemes

#### What I expected
When using Apple Pay with Product Add-Ons the order should have a breakdown of the Add-Ons selected. The cart total should also include the cost of the Add-Ons. Although the total includes the Add-On cost, as it should, the add-on value and the add on label is not shown in the order breakdown.

http://cld.wthms.co/AHl14p
![](https://d1zjcuqflbd5k.cloudfront.net/files/acc_412693/AHl14p?response-content-disposition=inline;%20filename=Screen_Shot_2017-06-06_at_10.34.12.png&Expires=1496770831&Signature=LZMAd1XBwQbkFLEYkvkXh4ZfOmUsh7eY8dcy1R031Jun9ASoul9e3CsVXNfjBwIEzGiMWAHxMP6uCVjhKZa3h0KF1JUKHXtik945H5QV3ckQvMwOmEI0sMcI6kagQKlypDWc1I6bfGfauwvCHx6REq1Qxd1epeeS5WmYGv3bx4g_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

#### What happened instead
When processing the same order using a Stripe credit card payment, the add-on value and the add-on label are shown properly.

http://cld.wthms.co/EEn88c
![](https://d1zjcuqflbd5k.cloudfront.net/files/acc_412693/EEn88c?response-content-disposition=inline;%20filename=Screen_Shot_2017-06-06_at_10.32.12.png&Expires=1496770781&Signature=eXP5xL-r6rZGzoQ8xN9trLcGJw7DObp3j688JUdi-fqCtMPHAoIQ1EH3sv1EgCJIt5Dtyek1kIOBA-7TwYPZq-3VG21dHdFAWpXjtq1T-l87oz8YDuWF75k686mg14WfRwbFIbLZU7Z-YhaNGfhf200Rszp4MaEJCv8SxhuE5hA_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

#### Steps to reproduce the issue

Although Pay purchases through a Stripe sandbox account get stuck on processing, I was able to at least get it to generate an incomplete order as shown in the first screen cap above. This was enough to replicate the issue.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Closed via #211
