### ISSUE TITLE
[Settings] Implement the new design for the Settings page

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2740]
### Current screen

This issue references the screen under WC -> Stripe -> Settings.

| | |
|--------|--------|
| <img width="2174" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/3540ecce-7220-423e-ad6d-5deec6a26a27"> | <img width="2154" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/bb474fe0-e346-4c62-b4c1-02de92461656"> | 

### New design

xVAk98kbRKUByVTrhPc98g-fi-641_70499

### Notes on the design

We may want to discuss these with design:

- The setting under "Debug mode" seems to have the wrong label. It reads "Enable the updated checkout experience", but looks like it should be "Log error messages" as per the current screen.
- Let's maintain the setting to toggle UPE (aka. the updated checkout experience). It's not in the design but we don't want to remove it yet.
- Let's not include the new option labeled 'Display "Powered by Stripe"'. This will be included with the new UPE implementation.
- For non-UPE, the option called “Enable separate credit card form” must show up.

**Comment by elizaan36** [comment]
@Mayisha and I chatted about this already but wanted to close the loop on this issue as well. The designs have been updated with your points above. The Advanced checkout settings should remain as is with the option to remove the accordion.

**Comment by a-danae** [comment]
Hey @elizaan36 👋 

Quick design check over here. When the Stripe account doesn't have an associated email, the account section looks like in the following screenshot. Are we okay with that?

Live mode:
<img width="700" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/7962895e-d0e3-46b6-93c3-ad58c6e5f81c">

Test mode:
<img width="700" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/7e251183-9d5d-44a6-a4af-2d1133b17582">

**Comment by elizaan36** [comment]
> When the Stripe account doesn't have an associated email, the account section looks like in the following screenshot. Are we okay with that?

How is the account identified without the email? There should be some placeholder there but I'm not sure how the account appears with no email in Stripe. @a-danae

**Comment by a-danae** [comment]
> How is the account identified without the email? There should be some placeholder there, but I'm not sure how the account appears with no email in Stripe.

Looks like there could be an email associated with the account but still not being returned when we retrieve this object. Why? Not sure. The [docs say](https://stripe.com/docs/api/accounts/object#account_object-email) the value of this property is nullable string, so we should expect this to be possible. Althought not sure how common it'd be.

Should I create a new issue to get the placeholder to use in this case? @elizaan36

**Comment by elizaan36** [comment]
Yes, for a placeholder we could use "Account" if there's no value returned.
