### ISSUE TITLE
WCPay multi-currency problem

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#2757]
**Describe the bug**

If WCPay multi-currency is enabled, we can end up with a case where subscription renewals fail with a message "The currency provided (usd) is invalid for one or more payment method types on this PaymentIntent"

**To Reproduce**
1. The shop currency is EUR and USD is available to customers
2. Activate WCPay and enable multi-currency
3. Make sure some Stripe local payment methods for EU are enabled (giropay, sepa)
4. Make a purchase of a subscription with USD
5. The renewal fails.

**Expected behavior**

For the renewal not to fail because it's trying to renew with the same currency it was purchased with.

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version 6.4.1
 - WooCommerce Version 8.2.2
 - Stripe Plugin Version 7.7.0
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed WCPay, Subscriptions

**Additional context**
See https://github.com/Automattic/woocommerce-payments/pull/6965

**Comment by annemirasol** [comment]
Unable to reproduce with the latest versions of WordPress 6.7.1, WooCommerce 9.4.3, Stripe 8.9.0, WooPayments 8.6.0 and Subscriptions 6.9.1.

Followed these steps:
 
1. The shop currency is EUR and USD is available to customers
2. Activate WCPay and enable multi-currency
3. Make sure some Stripe local payment methods for EU are enabled (giropay, sepa)
4. Make a purchase of a subscription with USD
   - Note: when "USD" is selected, EUR-only payment methods are not available, so I purchased these via Stripe `Credit / Debit card` payment method.
5. Process renewal succeeded.

**Comment by annemirasol** [comment]
Closing this issue as I am unable to reproduce. Please feel free to re-open and tag me if the issue persists with the latest plugin and extension versions.
