### ISSUE TITLE
Apple Pay does not include data from woocommerce

### ISSUE THREAD

**Issue by mhyman83** [woocommerce/woocommerce-gateway-stripe#276]
Apple pay does not include any data from addons plugin for custom text area. When customers input any text for our customized product, no data comes through on that order, causing us to email the customer to get all their info again.

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Please do a search.

**Comment by mhyman83** [comment]
I did, I didnt find anything for my specific problem.
