### ISSUE TITLE
[Deferred intent] Card - Allow saving a new card from My account -> Payment methods

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2762]
### Acceptance criteria
- Shoppers can save new payment methods from the My account -> Payment methods page
- These saved payment methods can be used for checking out in both the block and shortcode checkouts
- They can be removed from this page
- The following flows and their e2e tests must work as expected (use the behavior with the legacy PE implementation as a reference if in doubt)
  - [Shopper > Add new payment method](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#add-new-payment-method)
  - [Shopper > Delete payment method](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#delete-payment-method)

### Out of scope
- Adding 3DS cards

**Comment by mattallan** [comment]
Closed by #2791
