### ISSUE TITLE
[Deferred intent] Card - Process payments in the Pay for order page

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2766]
### Acceptance criteria

- The checkout flow must be completed as expected (use the legacy PE implementation as reference) with a new payment method
- Errors must be handled:
  - A relevant, user-friendly message must be shown to shoppers
  - A relevant note must be added to the order
  - A detailed message of the error must be logged to the log files if enabled
  - The order status must reflect the payment status
- The Legacy PE code that this implementation will replace must be removed if it's not used somewhere else

**Comment by james-allan** [comment]
closed via #2801
