### ISSUE TITLE
[Deferred intent] APMs - Process payments with iDEAL

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2767]
### Acceptance criteria

- Payments gets processed as expected (related critical flow: [Shopper > Checkout with iDEAL](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#checkout-with-ideal)) when paying through:
  - The shortcode checkout
  - ~The block checkout~
  - The Pay for order page
- If the payment method type is reusable, it can be saved from:
  - The shortcode checkout
  - ~The block checkout~
  - The Pay for order page
  - The My account -> Payment methods page - if supported
- Refunds must work - if supported
-  Errors are handled gracefully:
   - A relevant, user-friendly message must be shown to shoppers
   - A relevant note must be added to the order
   - A detailed message of the error must be logged to the log files if enabled
   - The order status must reflect the payment status

**Comment by mattallan** [comment]
After assigning myself to this issue I realised iDEAL is a reusable payment method which means it's still blocked until we finish implementing saved cards with deferred intents. Unassigning myself for now

**Comment by mattallan** [comment]
I've assigned myself this issue again 😅 as I realised all (or most) of the UPE payment methods that use the redirect flows were fixed by the PR I pushed up including iDEAL.

**Comment by mattallan** [comment]
Closed with #2803

**Comment by mattallan** [comment]
Whoops! I closed this one too early as we still need to test saving the payment method with deferred intents

**Comment by mattallan** [comment]
iDeal support with deferred intents along with saved payments & subscriptions support has been finalised in PR:https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2872

Closing this one.
