### ISSUE TITLE
Pop-up checkout not work in firefox

### ISSUE THREAD

**Issue by superbully** [woocommerce/woocommerce-gateway-stripe#277]
Hello, i use the plugin the stripe - woocmmerce and the checkout pop-up work fine in google chrome but not work in firefox and internet explorer.
Could you tell me how to solve ?

thank you.

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
This is not a place for support. Please post your support question on https://wordpress.org/plugins/woocommerce-gateway-stripe/
