### ISSUE TITLE
[Deferred intent] APMs - Process payments with Bancontact

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2770]
### Acceptance criteria

- Payments get processed as expected (related critical flow: [Shopper > Checkout with Bancontact](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#checkout-with-bancontact)) when paying through:
  - The shortcode checkout
  - ~The block checkout~
  - The Pay for order page
- If the payment method type is reusable, it can be saved from:
  - The shortcode checkout
  - ~The block checkout~
  - The Pay for order page
  - The My account -> Payment methods page
- Refunds must work - if supported
-  Errors are handled gracefully:
   - A relevant, user-friendly message must be shown to shoppers
   - A relevant note must be added to the order
   - A detailed message of the error must be logged to the log files if enabled
   - The order status must reflect the payment status

**Comment by mattallan** [comment]
> [!NOTE]
> I ran these tests on the latest changes from https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2926 (branch `fix/type-mismatch-creating-tokens`).

- [x] Payments get processed as expected (related critical flow: [Shopper > Checkout with Bancontact](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#checkout-with-bancontact)) when paying through:
  - [x] The shortcode checkout
  - [x] The block checkout
  - [x] The Pay for Order page
- [x] Saved cards
  - [x] saving a new card
  - [x] using an existing card
  - [x] removing a saved card
- [x] Subscriptions:
  - [x] purchase subscription from shortcode checkout
  - [x] purchase subscription from block checkout
  - [x] Process renewal order
- [x] Refund order
- [x] Errors are handled gracefully
