### ISSUE TITLE
[Deferred intent] APMs - Process payments with Przelewy24

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2771]
### Acceptance criteria

- Payments gets processed as expected (related critical flow: [Shopper > Checkout with Przelewy24](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#checkout-with-przelewy24)) when paying through:
  - The shortcode checkout
  - ~The block checkout~
  - The Pay for order page
- (Scratch this, P24 isn't reusable) ~If the payment method type is reusable, it can be saved from:~
  - ~The shortcode checkout~
  - ~The block checkout~
  - ~The Pay for order page~
  - ~The My account -> Payment methods page~
- Refunds must work if they're supported
-  Errors are handled gracefully:
   - A relevant, user-friendly message must be shown to shoppers
   - A relevant note must be added to the order
   - A detailed message of the error must be logged to the log files if enabled
   - The order status must reflect the payment status

**Comment by mattallan** [comment]
Closed with #2803
