### ISSUE TITLE
[Deferred intent] APMs - Process payments with SEPA

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2772]
### Acceptance criteria

- Payments gets processed as expected (related critical flow: [Shopper > Checkout with SEPA](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#checkout-with-sepa)) when paying through:
  - The shortcode checkout
  - The block checkout
  - The Pay for order page
- If the payment method type is reusable, it can be saved from:
  - The shortcode checkout
  - The block checkout
  - The Pay for order page
  - The My account -> Payment methods page
- Refunds must work if they're supported
- The flow [Test UPE form validation for credit card and SEPA](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-new-checkout-experience-(UPE)#test-upe-form-validation-for-credit-card-and-sepa) works as expected
-  Errors are handled gracefully:
   - A relevant, user-friendly message must be shown to shoppers
   - A relevant note must be added to the order
   - A detailed message of the error must be logged to the log files if enabled
   - The order status must reflect the payment status

**Comment by james-allan** [comment]
We've been testing SEPA amongst all other APMs as we've worked on this project. As a sort of final test, I ran through the tests listed in this issue and some additional ones too. With this in mind, I think this one is good to close. 

🟢 **Payments gets processed as expected (related critical flow: [Shopper > Checkout with SEPA](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#checkout-with-sepa)) when paying through:**
  - [x] The shortcode checkout
  - [x] The block checkout
  - [x] The Pay for order page

🟢 **If the payment method type is reusable, it can be saved from:**
  - [x] The shortcode checkout
  - [x] The block checkout
  - [x] The Pay for order page
  - [x] The My account -> Payment methods page

🟢 **Refunds must work if they're supported**
  - [x] Full Refund
  - [x] Partial Refund

🟢/🟡 Errors are handled gracefully:
   - [x] A relevant, user-friendly message must be shown to shoppers
      - Note: As SEPA is an async payment processor, payment related issues aren't displayed to the customer immediately. However, if you submit an incomplete or invalid IBAN form etc. those are displayed (see example below). 
   - [x] A relevant note must be added to the order (see screenshot below). 
   - [ ] ⚠️ A detailed message of the error must be logged to the log files if enabled
      - Note: The function which handles the failed payment webhook [[code link](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/7.9.0/includes/class-wc-stripe-webhook-handler.php#L480-L501)] doesn't log anything about the event in the Stripe logs. This isn't specific to Split PE or Deferred Intents so I wouldn't consider this a blocker for this issue. We may want to look at updating the `WC_Stripe_Webhook_Handler` more generally though logging of webhook events is light. 
   - [x] The order status must reflect the payment status

<p align="center">
<img width="500" alt="Screenshot 2024-02-22 at 2 48 54 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/0d92f448-f215-47ad-98e2-9b8e46d5fec3">
</br>
<sup>SEPA checkout element error</sup>
</br>
<img width="192" alt="Screenshot 2024-02-22 at 2 34 12 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/00dc4da0-518a-4daa-823c-e162316f21a7">
</br>
<sup>Order note recording payment failure</sup>
</p>

> **The flow [Test UPE form validation for credit card and SEPA](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-new-checkout-experience-(UPE)#test-upe-form-validation-for-credit-card-and-sepa) works as expected**

That link is broken and just sends me to a form to create the wiki page. 🤔 

----

### Additional tests

- [x] Guest customer
- [x] Block checkout - using a saved payment method.
- [x] Shortcode checkout - using a saved payment method.

**Subscription Purchases**
- [x] Simple subscription - block checkout
- [x] Simple subscription - shortcode checkout
- [x] Free trial - block checkout
- [x] Free trial - shortcode checkout

**Renewal orders**
- [x] Automatic Renewal orders
- [x] Manual renewal orders via Block Checkout
- [x] Manual renewal orders via Shortcode checkout.
