### ISSUE TITLE
[Deferred intent] APMs - Process payments with Alipay

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2774]
### Acceptance criteria

- Payments gets processed as expected (related critical flow: [Shopper > Checkout with Alipay](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#checkout-with-alipay)) when paying through:
  - The shortcode checkout
  - The block checkout
  - The Pay for order page
- If the payment method type is reusable, it can be saved from:
  - The shortcode checkout
  - The block checkout
  - The Pay for order page
  - The My account -> Payment methods page
- Refunds must work if they're supported
-  Errors are handled gracefully:
   - A relevant, user-friendly message must be shown to shoppers
   - A relevant note must be added to the order
   - A detailed message of the error must be logged to the log files if enabled
   - The order status must reflect the payment status

**Comment by mattallan** [comment]
Deferred intent support for Alipay has been implemented in #2803.

I've confirmed the following is working:
- [x] using Alipay with deferred intents on the shortcode checkout
- [x] using Alipay with deferred intents on the pay for order page
- [x] processing a refund on an alipay purchased with deferred intents
- [x] processing success and failure payments with errors correctly shown on checkout and logged (if enabled)

> If the payment method type is reusable, it can be saved from:

Alipay does not support saving the payment method as its `payment_fields()` function does not render any save payment method checkbox, so I've skipped over these tests.

Closing this one.
