### ISSUE TITLE
[Deferred intent] Subscriptions - Ensure that the subscriptions flows work as expected with deferred intent

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2777]
No changes may be needed here, but I'm creating this task to double-check. Feel free to create follow-up tasks as needed.

### Acceptance criteria

The following critical flows and related e2e tests must work as expected:
- [x] [Shopper > Purchase subscription product](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#purchase-subscription-product)
- [x] [Shopper > Purchase free trial subscription](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#purchase-free-trial-subscription)
- [x] [Shopper > Purchase multiple subscriptions](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#purchase-multiple-subscriptions)
- [x] [Shopper > Renew subscription](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#renew-subscription)
- [x] [Shopper > Change payment method to new card](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#change-payment-method-to-new-card)
- [x] [Shopper > Change payment method to saved card](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#change-payment-method-to-saved-card)
- [x] [Shopper > Change default payment method](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#change-default-payment-method)
- [x] [Shopper > Set default payment method](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#set-default-payment-method)
- [x] [Merchant > Renew subscription automatically](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#renew-subscription-automatically)
- [x] [Shopper > (Blocks) Purchase subscription product](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#blocks-purchase-subscription-product)
- [x] [Shopper > (Blocks) Purchase free trial subscription](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#blocks-purchase-free-trial-subscription)
- [x] [Shopper > (Blocks) Purchase multiple subscriptions](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#blocks-purchase-multiple-subscriptions)

**Comment by mattallan** [comment]
Closed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2866
