### ISSUE TITLE
[Deferred intent] PRBs - Ensure Payment Request buttons work as expected

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2778]
No changes may be needed here, but let's double-check it with this issue. Feel free to create others as needed.

### Acceptance criteria

- The three express checkouts we support work as expected:
  - Link
  - Google Pay
  - Apple Pay
- The payments get processed in:
  - The shortcode checkout: [Shopper > Checkout with Payment Request](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#checkout-with-payment-request) and [Shopper > Checkout with Payment Request (3DS card)](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#checkout-with-3ds-card) 
  - The block checkout: [Shopper > (Blocks) Checkout with Payment Request](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Testing-instructions-for-critical-flows-using-the-classic-checkout-experience#blocks-checkout-with-payment-request-button) and with a 3DS card too

**Comment by mattallan** [comment]
I ran the following tests on the `add/deferred-intent` base branch we're using:
- [x] Google Pay
  - [x] From the product page
  - [x] From the cart page
  - [x] From checkout page (shortcode + block)
  - [x] Subscription purchase
  - [ ] With a 3DS card
    - I couldn't add a test 3DS card to payments.google.com. I keep getting the following error: ![Screenshot on 20231218 at 104832png](https://cdn-std.droplr.net/files/acc_758525/wPqyte)  
- [x] Apple Pay - same tests as above
- [x] Link - same tests as above

Everything appears to be working which is to be expected as implementing deferred intents shouldn't have impacted how these Payment Request buttons work.

Closing this
