### ISSUE TITLE
Pull Statement Descriptor from account if empty? 

### ISSUE THREAD

**Issue by kaushikasomaiya** [woocommerce/woocommerce-gateway-stripe#2779]
Could be a low-priority one but just reporting it here for visibility.

At some places the statement descriptor is used from settings however that can be empty but set on Stripe Account:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/dfa39833e12aa4f40eccb2f998dff5c9042c2d69/includes/payment-methods/class-wc-gateway-stripe-sepa.php#L190

Wondering if we can pull it from the account if it is empty in settings.

![https://d.pr/i/Dh5Pei](https://d.pr/i/Dh5Pei+) 
Full Size: https://d.pr/i/Dh5Pei

**Comment by diegocurbelo** [comment]
Since version 8.0 (March 2024) the plugin uses the Statement Descriptor from the Stripe Dashboard.
