### ISSUE TITLE
Apple Pay: remove "via Woocommerce" text

### ISSUE THREAD

**Issue by alberto223** [woocommerce/woocommerce-gateway-stripe#278]
#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by alberto223** [comment]
How would possible to delete the text "via Woocommerce" in this plugin? In includes/class-wc-stripe-apple-pay.php i found the text "via Woocommerce" in two points but if i try to modify all website stop working

**Comment by roykho** [comment]
This is not a place for support. Please post your support question on https://wordpress.org/plugins/woocommerce-gateway-stripe/
