### ISSUE TITLE
[Deferred intent] Pre-Orders - Ensure paying for Pre-Order products work as expected

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2780]
No changes may be needed here, but let's double-check it with this issue. Feel free to create others as needed.

### Acceptance criteria

Stripe behaves as it currently does with the legacy PE implementation in the following critical flows:
 
- Manage > Complete pre-order customers, for both:
  - Product setting > When to charge > Upon release
  - Product setting > When to charge > Upfront
 
And Pre-order fees are included in the payment

Find the critical flows instructions in the repo wiki gh-woocommerce/woocommerce-pre-orders

**Comment by james-allan** [comment]
Fixed in #2933
