### ISSUE TITLE
Unable to release authorization

### ISSUE THREAD

**Issue by lawkwok** [woocommerce/woocommerce-gateway-stripe#279]
#### What I expected

When cancelling an "on-hold" order (meaning the charge is just authorized and not captured), you expect authorization to be released.

#### What happened instead

Instead, you get this order note:

> Unable to refund charge! You cannot partially refund an uncaptured charge. Instead, capture the charge for an amount less than the original amount

#### Steps to reproduce the issue

1. Uncheck "Capture charge immediately" in WooCommerce Stripe settings.
2. Create an order.
3. Change order status to Cancelled.

 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
I am unable to reproduce this. Please provide more details. What type of product it is, what is the amount used. Is tax inclusive? Are their shipping involved?

**Comment by lawkwok** [comment]
After some more testing, I've narrowed it down to two scenarios that trigger this message:

1. If a charge has already been released in Stripe (e.g. if over 7 days has passed since authorization)
2. If there the order amount was changed to anything greater than, or less than the original captured amount.

I am using variable products, tax is additional, shipping is either free or flat rate.

**Comment by roykho** [comment]
@lawkwok Ok so in both scenarios, it was out of the plugin's control as it was modified outside of WC. So the message you see then is indeed correct. How are you perceiving it to work if not that message?

**Comment by lawkwok** [comment]
Hmm, that's a tricky one since Stripe sends the same message for already-released payments and for orders that have modified totals.

- Scenario 1 is up to Stripe. Personally I think referring to a released payment as an "uncaptured charge" is confusing.
- Scenario 2: Perhaps for cancelled orders we can get the authorized amount from Stripe and refund that amount instead of using the modified order amount in WooCommerce.

**Comment by roykho** [comment]
I don't think anything needs to be done here right now. The error message is coming straight from Stripe when you try to release the funds of a pre-auth order when it has already been released either from past expiration of the auth or manually done. It is only a message in the order notes so it does not break anything.

Amounts shouldn't change after it has been auth on Stripe side. This could cause lots of issues. You can however refund partial on WC side and changes would reflect correctly on Stripe.

With that said, once we implement this feature here https://github.com/woocommerce/woocommerce-gateway-stripe/issues/128 then changes in Stripe can then sync back to the WC store.
