### ISSUE TITLE
[Split PE] Implement Split PE for APMs in the block checkout

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2790]
### Acceptance criteria

- When multiple payment method types are enabled, they must appear as different payment gateways in the classic checkout, as it happens when PE is disabled. Design xVAk98kbRKUByVTrhPc98g-fi-342_8806
- If already implemented before working on this, payment processing must also continue to work for APMs
- Changes must be covered by tests
- e2e tests must be adjusted to at least maintain the same coverage they had before split PE

### Notes

This might be handled in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2784. Confirm before grabbing this issue.

**Comment by james-allan** [comment]
https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2820 adds support for EU APMs (giropay, bancontact, iDEAL, EPS etc). I still need to add support for Latin American payment methods like Oxxo and Boleto.

**Comment by a-danae** [comment]
Closing as fixed by https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2789 and https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2820
