### ISSUE TITLE
Uncaught TypeError: t.addClass(…).block is not a function

### ISSUE THREAD

**Issue by ishyfishydishy** [woocommerce/woocommerce-gateway-stripe#2793]
**Describe the bug**
Our website developers have found a Console error which prevents important WooCommerce basket functionality, when the plugin WooCommerce Stripe Gateway is installed. The error is an ‘Uncaught TypeError: t.addClass(…).block is not a function’
See screenshot: https://snipboard.io/4PGpnd.jpg

This is stopping users from being able to update product quantities by clicking the ‘Update the basket’ button or delete the product lines.

We have completed a full plugin conflict test on our development site and have detected that the WooCommerce Stripe Gateway plugin is causing this problem when Elementor Pro is enabled. Disabling Elementor Pro enables the ‘Update Basket’ and ‘X’ (Delete product line) to function correctly.

We have contacted both WooCommerce Stripe Gateway and Elementor Pro support and they state that are aware of the issue. Both parties are stating a case should be logged on GitHub, hence why we are providing information here.

**To Reproduce**
1. Install Elementor Pro
2. Install WooCommerce
3. Install WooCommerce Stripe Gateway
4. Add a product to the basket
5. Attempt to change the product quantity and click 'update basket'
6. Check console for the ‘Uncaught TypeError: t.addClass(…).block is not a function’ error

**Expected behaviour**
- On the basket page, the update basket/cart should update the quantities and pricing. 
- The delete button on the product line should remove the product from the basket.

**Environment (please complete the following information):**
 - WordPress Version - 6.4.1
 - WooCommerce Version - 8.3.1 
 - Stripe Plugin Version - 7.7.0
 - Browser [e.g. chrome, safari] and Version - Chrome 119.0.6045.200

### WordPress Environment ###

WordPress address (URL): https://portal.scooterpac.com
Site address (URL): https://portal.scooterpac.com
WC Version: 8.3.1
REST API Version: ✔ 8.3.1
WC Blocks Version: ✔ 11.4.9
Action Scheduler Version: ✔ 3.6.4
Log Directory Writable: ✔
WP Version: 6.4.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 8.0.30
PHP Post Max Size: 128 MB
PHP Time Limit: 400
PHP Max Input Vars: 6000
cURL Version: 7.61.1
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 10.6.16-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.3.1
WC Database Prefix: 3iXm053_
Total Database Size: 332.33MB
Database Data Size: 319.73MB
Database Index Size: 12.60MB
3iXm053_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
3iXm053_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
3iXm053_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
3iXm053_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
3iXm053_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
3iXm053_cptslotsbk_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_cptslotsbk_icalexport: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_cptslotsbk_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
3iXm053_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
3iXm053_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
3iXm053_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
3iXm053_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
3iXm053_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_gf_form_meta: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
3iXm053_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
3iXm053_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_loginpress_limit_login_details: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_options: Data: 5.03MB + Index: 0.13MB + Engine InnoDB
3iXm053_pmxe_exports: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
3iXm053_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
3iXm053_pmxe_posts: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
3iXm053_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_pmxi_hash: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
3iXm053_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_pmxi_images: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
3iXm053_pmxi_imports: Data: 0.45MB + Index: 0.00MB + Engine InnoDB
3iXm053_pmxi_posts: Data: 0.27MB + Index: 0.00MB + Engine InnoDB
3iXm053_pmxi_templates: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
3iXm053_postmeta: Data: 219.55MB + Index: 6.94MB + Engine InnoDB
3iXm053_posts: Data: 89.53MB + Index: 2.53MB + Engine InnoDB
3iXm053_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_term_relationships: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
3iXm053_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_um_metadata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
3iXm053_usermeta: Data: 1.42MB + Index: 0.06MB + Engine InnoDB
3iXm053_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
3iXm053_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
3iXm053_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
3iXm053_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
3iXm053_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
3iXm053_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
3iXm053_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
3iXm053_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
3iXm053_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_wc_product_meta_lookup: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
3iXm053_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
3iXm053_wdp_orders: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
3iXm053_wdp_order_items: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
3iXm053_wdp_persistent_rules_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_wdp_rules: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
3iXm053_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
3iXm053_wpml_mails: Data: 0.25MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 3
acf-field-group: 1
amz_configurator: 11
attachment: 2269
custom_css: 2
custom-css-js: 1
elementor_library: 60
nav_menu_item: 1
oembed_cache: 1
page: 46
post: 4
product: 479
product_variation: 11
revision: 7775
um_directory: 1
um_form: 3
wp_navigation: 1
wp_template: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

Advanced Custom Fields: by WP Engine – 6.2.4
Advanced Dynamic Pricing for WooCommerce: by AlgolPlus – 4.5.3
All-in-One WP Migration Unlimited Extension: by ServMask – 2.54
All-in-One WP Migration: by ServMask – 7.79
Cabincar Skin for WP Configurator Pro: by WP Configurator – 1.2
Classic Editor: by WordPress Contributors – 1.6.3
Conditional Logic for WP Configurator Pro: by WP Configurator – 1.1
Contact Form 7: by Takayuki Miyoshi – 5.8.4
Duplicate Page: by mndpsingh287 – 4.5.3
Elementor Pro: by Elementor.com – 3.17.1
Elementor: by Elementor.com – 3.17.3
Gravity Forms: by Gravity Forms – 2.7.17
Gravity Forms Zapier Add-on: by Gravity Forms – 4.2.1
Login Logout Menu: by WPBrigade – 1.4.0
LoginPress - Customizing the WordPress Login Screen.: by WPBrigade – 1.8.0
Members: by MemberPress – 3.2.9
Min and Max Order Amount for Woo Payment Gateways: by Raihan – 1.0.2
Premium Addons for Elementor: by Leap13 – 4.10.15
Premium Addons PRO: by Leap13 – 2.9.9
Redis Object Cache: by Till Krüss – 2.5.0
Styles & Layouts Gravity Forms: by Sushil Kumar – 4.3.11
Ultimate Addons for Elementor: by Brainstorm Force – 1.36.26
WooCommerce Stripe Gateway: by WooCommerce – 7.7.0
WooCommerce Product Table: by Barn2 Plugins – 3.1.3
WooCommerce Role Based Methods: by WPBackOffice – 2.4.3
WooCommerce: by Automattic – 8.3.1
WP All Export Pro: by Soflyy – 1.8.6
WP All Import Pro: by Soflyy – 4.8.5
WP Configurator Pro: by WP Configurator – 3.5.1
WP File Manager: by mndpsingh287 – 7.2.1
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WP All Export - User Export Add-On Pro: by Soflyy – 1.0.7
WP All Export - WooCommerce Export Add-On Pro: by Soflyy – 1.0.9
WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 4.0.0

### Inactive Plugins (1) ###

WooCommerce Wholesale and Tier Prices: by Addify – 1.2.1

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: ❌ Page not set
Basket: #93 - /basket/
Checkout: #94 - /checkout/
My account: #95 - /my-account/
Terms and conditions: #5320 - /terms-and-conditions/

### Theme ###

Name: Scooterpac Portal
Version: 1.0
Author URL: http://www.scooterpac.com
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.9.0
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: Scooterpac-Portal/woocommerce/emails/customer-completed-order.php
Scooterpac-Portal/woocommerce/emails/customer-processing-order.php

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-virtual-downloadable
product-external-affiliate
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-12-04 20:00:27 +00:00
Options: ✔
Notes: 47
Onboarding: skipped

### Action Scheduler ###

Complete: 129
Oldest: 2023-11-04 02:48:58 +0000
Newest: 2023-12-04 02:08:11 +0000

Failed: 45
Oldest: 2023-02-16 17:42:34 +0000
Newest: 2023-12-01 14:29:53 +0000

Pending: 1
Oldest: 2023-12-05 02:08:11 +0000
Newest: 2023-12-05 02:08:11 +0000

### Status report information ###

Generated at: 2023-12-04 10:26:30 +00:00

**Comment by annemirasol** [comment]
Closing -- unable to reproduce with latest Elementor, WC and Stripe extension versions.

Please feel free to re-open if issue still exists.
