### ISSUE TITLE
Investigate creating a Stripe payment element with mode 'payment' when loading the form on Add Payment Method page

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-gateway-stripe#2798]
### Description

While working on https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2791 which is adding deferred intent support to the **My Account > Payment methods > Add payment method** page, I noticed that when we're creating the Stripe PE, we are using the following options:

```
const amount = Number( getStripeServerData()?.cartTotal );
const options = {
	mode: amount < 1 ? 'setup' : 'payment',
	currency: getStripeServerData()?.currency.toLowerCase(),
	amount,
	paymentMethodCreation: 'manual',
	paymentMethodTypes,
	appearance: initializeUPEAppearance(),
	fonts: getFontRulesFromPage(),
};
```

Note that for the `mode` property we're setting it to either `'setup'` or `'payment'` depending on the `cartTotal` arg served to us from the backend. From my understanding, we want to be using "setup" mode for adding a payment method since no payment is going to be taken, however, if you add a product to your cart, then visit **My Account > Payment methods > Add payment method**, the Stripe PE will be loaded with `mode` set to payment.

From my testing, setting the mode to payment or setup doesn't have any impact on saving the payment method and from the Stripe docs, it looks like this 'mode' is just used for determining which payment methods to display: https://stripe.com/docs/js/elements_object/update#elements_update-options-mode

Given we're moving to split deferred intent, it might not matter what we set mode to.

This issue is to investigate this setting further and determine whether we need to force the mode to be 'setup' when on the add payment method page

> [!NOTE]
> WooPayments uses this same code that sets the mode based on the cart totale and it doesn't seem to be an issue for them on their Add Payment Method page so I suspect it's not problem.

**Comment by james-allan** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2918. In that PR I've set the cartTotal to 0 when on the Account payment methods page.
