### ISSUE TITLE
Subscriptions: "Change Payment" Updated Card Not Used For Renewals

### ISSUE THREAD

**Issue by ericboles** [woocommerce/woocommerce-gateway-stripe#281]
Using WooCommerce 3.0.8, Wordpress 4.8, WooCommerce Subscriptions 2.2.7, and WooCommerce Stripe Gateway 3.1.9 

**Steps to Reproduce**
- View an active subscription within My Account (one that has a pending renewal that has not failed).  
- Click on the "Change Payment" button on the view-subscription page.
- Provide the a new credit card via stripe on the "choose a new payment method" page.
- Press "change payment method"

**Expected Result**
- New credit card is added to the stripe customer record
- Stripe Card ID metadata within the parent subscription is updated to the new Stripe card ID
- "Next Payment" displayed in my account should reflect the new card type and last4
- Future renewals will be charged against the new credit card.

**Actual Result**
- New credit card is correctly added to the stripe customer record
- The metadata in the parent WooCommerce subscription is not updated with the new Stripe card ID
- "Next Payment" displayed in my account continues to reflect the previous card
- Future renewals continue to be attempted against the previous credit card
- When attempting to change payment again, the new card now appears within the list of potential cards.  However, selecting that card still does not update the metadata or change future renewals.

**Other things to note:**
- Manually updating the Stripe card ID for the parent subscription within the WordPress admin does cause future renewals to be charged to that card and for the "next payment" to display the correct card within My Account.  It seems the one thing breaking is the storage of that new Stripe card ID within the metadata.

- When the payment is updated to a new card following a failed renewal, the result is as expected--the new Stripe card ID is updated within the subscription metadata and it is accurately reflected within My Account

**Comment by roykho** [comment]
So is the issue only when manually changing the payment method on an active subscriptions?

**Comment by ericboles** [comment]
@roykho Hi there. Yes--the issue is when the _customer_ manually changes the payment method for active subscriptions. e.g. Providing a new credit card to replace one that has expired.

**Comment by roykho** [comment]
Hi @ericboles - could you please test master branch and see if your issue is fixed? Thanks!

**Comment by ericboles** [comment]
Thanks, @roykho.  I ran through my litany of tests and those 3 lines seem to have done the trick.  Thanks for the quick turnaround.

**Comment by roykho** [comment]
You're welcome and thanks for reporting!

**Comment by amlcreative** [comment]
Hi @roykho 

My site is experiencing the same issue as @ericboles has with Woocommerce Subscriptions but mine is with the Woocommerce Memberships plugin. When a customer changes the stored card it continues to charge the previously stored card.

Using WooCommerce 3.1.2, Wordpress 4.8.3, WooCommerce Memberships 1.9.1, and WooCommerce Stripe Gateway 3.2.3

**Comment by roykho** [comment]
Hi @amlcreative no two sites are the same as different sites have different configurations/settings and different plugins. Your issue is quite different from OP as you're not even using the same plugin. There are logic in place specifically to handle Subscriptions and perhaps not memberships so I would suggest you create a separate issue with exact settings/versions and detailed steps to reproduce the issue.

**Comment by kenjikato** [comment]
I'm seeing the same thing it appears. I have Woocommerce Subscriptions and Membership both active. When customers update their credit card it appears that the existing monthly subscript is not being updated to the new card. Using WooCommerce 3.3.1, Wordpress 4.9.4, WooCommerce Subscriptions 2.2.7., WooCommerce Membership 1.8.6., Stipe Gateway 4.0.5.
Should this fix be in the current version, or do I need to install something new?

**Comment by RileyGB** [comment]
Any updates on this? I'm actively experiencing this issue on WooCommerce 3.4.4, WooCommerce Subscriptions 2.2.19 and Stripe Gateway 4.1.8.

**Comment by FitMo90** [comment]
We have the same issue! 
Any Updates or a solution? @RileyGB @roykho 
Thanks

**Comment by samglover** [comment]
We’re also having this issue with Subscriptions and Memberships when a user tries to update their payment information and they have multiple subscriptions.

**Comment by fr3shbox** [comment]
I am also experiencing this problem. This is the same for accounts that are created for a customer manually and then the customer later goes in to add a payment method.

I have now discovered that the card details are being saved to the main stripe dashboard, but it then requires you to go back into the subscription in woocommerce and add back the stripe id and source id- one would  expect this to update automatically...

**Comment by WebservAUS** [comment]
I have  a very similar problem. I have just just added webhook endpoints in my stripe account. I hope this will now take care of that issue for the future. Did you guys have the webhooks endpoints set up?

**Comment by egsdavinci** [comment]
@ericboles @roykho 


> I ran through my litany of tests and those 3 lines seem to have done the trick. Thanks for the quick turnaround.

Hi, Can you please elaborate on the 3 lines you are referring to? We have the same issue

**Comment by Entretoize** [comment]
The bug seems still there, customer updating credit card's details doesn't stop failing payments.

**Comment by memyselfandm** [comment]
> Some findings:
> 
> * In Stripe, I determined that WooCommerce was trying to use the wrong source token to charge the customer.
> * I went into the database and found all occurrences of the old token, the only occurrences were in the **postmeta** table.
> * I changed all of these meta values (with keys of **_stripe_source_id**) to the new correct source token as found on Stripe.
> * I ran the renewal again and it succeeded.
> 
> Therefore, it seems like it must be using one of these values to acquire the user's token as opposed to using the vaue in **woocommerce_payment_tokens** (which is properly updated).

I had the same issue. A customer's renewal payment failed, and they updated their credit card information. When I tried to retry the new renewal payment it failed. I found the same information from the same troubleshooting steps above and took the steps above to fix it.

However, it should be stressed that you should **NOT** under any circumstances (including desperation) access your site's database and change this information unless you are 120% certain you know exactly what you're doing. This is your customers' (plural, as in ALL of them, not just the one you're having problems with) payment information you're messing with. It's **REALLY** easy to make a **catastrophic** mistake here if you don't know what you're doing. 

Rather see a proper fix for this issue.

**Comment by raindeer** [comment]
Has this been fixed or is it still an issue?

**Comment by Entretoize** [comment]
Sorry I can't tell...
