### ISSUE TITLE
Credit card form clears after address change

### ISSUE THREAD

**Issue by pvlvsk** [woocommerce/woocommerce-gateway-stripe#282]
Plugin version: 3.1.9

Hello,

there is a problem with my checkout routine using this plugin. 

- user fills in his address and credit card data
- user finds an error in his adress data and corrects his address
- the stripe area of the checkout refreshes and the credit card data is gone

This is a very frustrating behavior. Is it on purpose or have I something brocken on my checkout page?

Thank you.

**Comment by roykho** [comment]
I am unable to reproduce this. Please give more details as to how to replicate the issue including what field was not correct to begin with, was shipping enabled, if so which shipping plugin are you using, what theme are you using, have you deactivated everything except WC and Stripe and see if its a conflict...etc.

**Comment by mattyza** [comment]
@pvlvsk - Thanks for reporting this. A screencast or animated GIF of this happening would be very helpful, if possible.

I suspect this may be intentional, if not an unintentional bug, as credit card form availability may change if the address is changed (for example, if certain countries aren't supported by the payment processor).

I believe there is definitely some refinement to be done, whether or not this is a bug. Thus, I've logged this as a bug for now, so we can ensure this gets the attention it deserves.

**Comment by roykho** [comment]
Closing this as we can't replicate and  no response from OP.

**Comment by lkraav** [comment]
4.1.13: @roykho I'm not sure how this got to "can't replicate", as it seems fairly easy to run into it. Just had another customer checkout incident with this yesterday - one character typo fix in "Street address" field wiped out CC info. For busy enterprise people this experience is always super-annoying.

Screencast https://conversionxl.com/wp-content/uploads/2019/03/2019-03-01-13-09-11.mp4

> I suspect this may be intentional, if not an unintentional bug, as credit card form availability may change if the address is changed (for example, if certain countries aren't supported by the payment processor).

a) even if so, always must ask for user confirmation before destroying her work
b) clear field operation trigger should be limited to one specific field where it's actually necessary - changing a single character in "Street address" field use case is a perfect example of the current algorithm weakness

Your thoughts? I vote re-open.

**Comment by lkraav** [comment]
Hello @roykho could you let me know please if you've seen the screencast, or who else may be the appropriate person to have technical insight on this issue? UX of this flow is clearly subpar, and I doubt that's the actual design goal.

**Comment by kmindi** [comment]
I also have customers that are frustrated by having to input the SEPA/creditcard details again after form validation errors (captcha/adress/account already existing)

**Comment by lkraav** [comment]
Maybe we're at-mentioning the wrong person. @RadoslavGeorgiev is doing active work in `sca/master` branch, but also maybe all available resources are busy with SCA work.
