### ISSUE TITLE
[Settings] Remove UPE-specific items when UPE is disabled

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2828]
**Describe the bug**
There are a couple of elements in the Payment Methods tab that are meant for the new checkout experience (UPE), but are displayed when UPE is disabled.

**To Reproduce**
1. Check out `task/updated-settings-page`
2. Disable UPE. Stripe settings page (`siteurl/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings`) > Advanced settings > Enable the updated checkout experience
3. Go to the Stripe Payment methods page (`siteurl/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods`)
4. Notice that:
  - The're a pill saying "Early Access" ![nO3ftZ.png](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/440ff0fe-befa-4bc2-b1c6-7afbf2ba9ac3)
  - There's an option saying "Disable", which is meant to disable UPE ![k7giRk.png](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/fbcd29ec-f8bc-4a25-8984-15823919d837)

**Expected behavior**
The "Early access" pill and the "Disable" option must only appear when UPE is enabled.

**Comment by wjrosa** [comment]
I did multiple tests enabling and disabling UPE on the same branch (`task/updated-settings-page`). I could not reproduce the issue. I believe it might have been fixed shortly after this issue was created.

**Comment by wjrosa** [comment]
I was able to reproduce the issue with @a-danae 's help. Draft PR with the fix is [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2838).
