### ISSUE TITLE
Always create a customer object

### ISSUE THREAD

**Issue by sergchernata** [woocommerce/woocommerce-gateway-stripe#283]
It seems as though currently the customer object is not created unless the customer chooses to save his card for later use.

It is more beneficial to have a customer object be created in all cases, not just when choosing to save the card.

Customer objects enable merchants to create other charges and have better control from within Stripe Dashboard.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
I believe this is more of a privacy/legal issue. I am not sure of all the laws and policies of each country but if I was the customer, I would be very unhappy if your store saved my payment information without my consent. It should be an "opt-in".

With that said, you can always filter it to always true using this `add_filter( 'wc_stripe_force_customer_creation', '__return_true' );`

**Comment by miguejarias** [comment]
This code seems to be no longer working. The customer does not get created on Stripe even with this code.

**Comment by roykho** [comment]
@miguejarias try `add_filter( 'wc_stripe_force_save_source', '__return_true' );`

**Comment by lebonze** [comment]
thanks
indeed that filter had stopped working

**Comment by sergchernata** [comment]
Is there a fix?

**Comment by miguejarias** [comment]
@roykho Thanks that worked!

**Comment by UmbrellaProject** [comment]
Hey Guys, can you share where exactly should I add that filter?
