### ISSUE TITLE
Enable card brand choice

### ISSUE THREAD

**Issue by allie500** [woocommerce/woocommerce-gateway-stripe#2844]
**Is your feature request related to a problem? Please describe.**

Currently it is not possible for a customer to choose which card brand they want to use when paying with a co-branded card.

**Describe the solution you'd like**

When using a co-branded card, a customer should have the option to select which brand they want to run the payment through. The feature should also allow a merchant to set a default brand to use if the customer doesn't make a choice.

For additional information, please see Stripe's [card brand choice documentation](https://stripe.com/docs/card-brand-choice). This documentation includes details for implementing card brand choice within payment elements such as those used in this extension. At the bottom of the doc, you will find two co-brand test cards for testing during development. 

**Describe alternatives you've considered**

No alternatives have been reviewed in relation to this. This request came in from a pre-sales request from a potential merchant. 

**Additional context**

Please see this Slack thread for additional context and discussion:
p1705610246121619-slack-C7U3Y3VMY

**Comment by ryanr14** [comment]
Brought to us by a merchant in 7598919-zen.

Thanks for creating this and looking into it!

**Comment by csmcneill** [comment]
We received communications from Stripe related to this issue on 13 February 2024 (emphasis mine):

> A number of your Stripe accounts are currently processing card payments through [Cartes Bancaires](https://stripe.com/docs/payments/cartes-bancaires), which is often co-branded with Visa or Mastercard. EU regulations relating to co-branded card payments may require you to update your integration, depending on the Stripe products you use to accept payments.
> 
> Specifically, the regulations state that customers must be able to choose their preferred card brand when paying with co-branded cards. You will need to take steps to ensure your integration offers this choice to your customers. 
> 
> **Note that continued non-compliance with these rules can result in fines, penalties, and other actions from card networks, regulators, and Stripe**, so it’s important to confirm that your account is compliant as soon as possible, but no later than **September 2024**.

**Comment by rbgly** [comment]
7847222-zen

**Comment by m0untaingoat** [comment]
7850855-zen

**Comment by kgeorgee** [comment]
7869071-zen

**Comment by zoemyers** [comment]
7856731-zen

**Comment by imodouglas** [comment]
7936566-zen

**Comment by shrutimoorthy** [comment]
7922998-zen

**Comment by sverleis** [comment]
Merchant requesting an update, via 7956419-zen

@wjrosa can you bump up the priority on this, as it may negatively affect many merchants.

**Comment by Esyda** [comment]
It is very important for sellers that this issue be resolved as soon as possible.

**Comment by carolframen** [comment]
8118207-zen

**Comment by alevals** [comment]
+1

**Comment by OmarFPG** [comment]
8119243-zd

**Comment by wjrosa** [comment]
This feature will be available when using WooCommerce 8.9.0 (released today) and WooCommerce Gateway Stripe version 8.3.0 (to be released this week). I am closing this as completed.

**Comment by xoogu** [comment]
> This feature will be available when using WooCommerce 8.9.0 (released today) and WooCommerce Gateway Stripe version 8.3.0 (to be released this week). I am closing this as completed.

Could you confirm what the change is? If you turn off 'Legacy checkout experience' in the Stripe gateway settings it will already show the co-branded card selection on Checkout. Is this current implementation not compliant? Or is it just the change adds the same functionality with the 'Legacy checkout experience'?

**Comment by wjrosa** [comment]
@xoogu The new version 8.3.0 will add some metrics features and solve some issues when trying to use them without the new checkout experience (legacy version enabled, should not be possible). But yeah, the feature itself was already working for a while in previous versions.

**Comment by raifd** [comment]
Hi @wjrosa! Thank you for the update. Running WooCommerce 8.9.1 and Stripe 8.3.1 with Legacy _Enable the legacy checkout experience_ unchecked/disabled, there isn't an option to choose [using Stripe's test cards](https://docs.stripe.com/co-badged-cards-compliance).

Here is a screenshot:
![Screenshot on 2024-06-03 at 12-37-03](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/23462281/b9c9435f-6305-4466-931c-fc575c48d181)

Internal reference: 8183081-zen

**Comment by wjrosa** [comment]
Hi @raifd ! This is intended, as co-badged cards [are not compatible with the Sources API](https://docs.stripe.com/co-badged-cards-compliance?type=custom-integration#pass-network-preference-to-api) (which is used in the legacy checkout).

**Comment by raifd** [comment]
Thank you @wjrosa! But they should show when "Enable the legacy checkout experience" is unchecked/disabled on the Stripe extension settings, right?

**Comment by wjrosa** [comment]
> Thank you @wjrosa! But they should show when "Enable the legacy checkout experience" is unchecked/disabled on the Stripe extension settings, right?

Yes, that's right.
