### ISSUE TITLE
SEPA Transfer and Giropay hidden (when store currency isn't EUR)

### ISSUE THREAD

**Issue by maltfield** [woocommerce/woocommerce-gateway-stripe#2846]
**Describe the bug**

I tried to enable these two payment methods in my woocommerce settings (with `woocommerce-gateway-stripe`):

1. Stripe SEPA Direct Debit
2. Stripe giropay

Unfortunately, after enabling these payment options both in my Stripe dashboard and in wooommerce, my wordpress site displays the following errors:

```
Stripe SEPA Direct Debit is enabled - it requires store currency to be set to EUR
Stripe giropay is enabled - it requires store currency to be set to EUR

SEPA Direct Debit won't be visible to your customers until you add EUR to your store.
giropay won't be visible to your customers until you add EUR to your store.
```

This is, of course, not a technical limitation; it's a bug.

My Stripe account is in EUR and my woocommerce store is in USD. This is not an issue for other payment methods like credit-cards, which get their currency converted at payment time.

**To Reproduce**

1. Set woocommerce store currency to USD
2. Enable payment method `Stripe SEPA Direct Debit` in woocommerce settings
2. Enable payment method `Stripe giropay` in woocommerce settings
3. Add item to cart, attempt to pay with SEPA or giropay
4. Fail to find option to pay with the newly enabled payment methods

**Expected behavior**

I should be able to enable payment methods `Stripe SEPA Direct Debit` and `Stripe giropay` in a store in any currency, because the currency gets converted to EUR at checkout time.

**Comment by maltfield** [comment]
This issue is still relevant.

**Comment by annemirasol** [comment]
The currency restriction is dictated by Stripe: https://docs.stripe.com/payments/sepa-debit (See **Presentment Currency** under **Payment method properties**).

I verified this and tried to send off a SEPA request to Stripe for a USD purchase and got this response: "The currency provided (usd) is invalid. Payments with sepa_debit support the following currencies: eur."

Same with Giropay, the presentment currency is restricted to EUR: https://docs.stripe.com/payments/giropay

**Comment by annemirasol** [comment]
Closing this issue for now, subject to re-opening when Stripe adds support for other presentment currencies.

**Comment by maltfield** [comment]
Sorry, why can't we have the client (wordpress/woocommerce) convert the numerical quantity to EUR before querying Stripe?

I don't see why this is blocked by upstream.

Please re-open this ticket, amending the "Solution" to this bug to include converting the payment's total from the store's default currency to EUR before querying Stripe.
