### ISSUE TITLE
How to remove Apple Pay function on Shop Single Page?

### ISSUE THREAD

**Issue by williamlwu** [woocommerce/woocommerce-gateway-stripe#285]
#### What I expected

Apple Pay function to be removed from Shop single page

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
This is not a support channel but for bug reports only. Please use this instead https://wordpress.org/plugins/woocommerce-gateway-stripe/
