### ISSUE TITLE
Split UPE - Add support for Subscription payments with eligible APMs

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce-gateway-stripe#2872]
**Describe the bug**

The https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2866 PR adds support for taking subscription payments using cards. As part of this issue, we'll look into adding support for the other APMs that support subscription payments. 

- [x] [Bancontact](https://stripe.com/docs/payments/bancontact)
- [x] [iDEAL](https://stripe.com/docs/payments/ideal)
- [x] [SEPA](https://stripe.com/docs/payments/sepa-debit)

> [!important]
> As outlined in Stripe docs, these payment methods are only capable of recurring payments by creating a reusable SEPA debit token. This happens on Stripe's end when you attempt to create a reusable token. See the `process_order_for_confirmed_intent()` function for inspiration as to how this is handled.

These payment methods were previously supported using the the unified UPE element and so should continue to work as split payment methods with deferred intents. 

<p align="center">
<img width="300" alt="Screenshot 2024-02-02 at 3 30 50 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/3d4330f1-91ca-4d85-bef2-80a91a770fed">
</br>
<sup>SEPA, Bancontact, and iDEAL APMs available while purchasing a subscription</sup>
</p>

**Testing instructions**
1. Checkout the `add/deferred-intent` branch. 
2. Enable UPE in the Stripe plugin advanced settings.
3. Enter Stripe API credentials for an account that has these EU payment method enabled. 
4. Enable SEPA, Bancontact, and iDEAL from the payment methods list
5. Enable the Woo Subscriptions plugin. 
6. Create at least 1 subscription product. 
7. Add the subscription product to the cart.
8. On checkout confirm you can take payments with Bancontact, SEPA, and iDEAL and make sure automatic recurring payments work as expected. ie renewing the subscription raises a charge using the underlying SEPA debit token.

**Comment by mattallan** [comment]
Closed by #2883 🎉 Thanks James for all your work on this one!
