### ISSUE TITLE
No option to enable/disable Link in the Payment Element

### ISSUE THREAD

**Issue by csmcneill** [woocommerce/woocommerce-gateway-stripe#2880]
**Describe the bug**
Stripe is now allowing Link to be displayed in the Payment Element. This means that, when the new checkout experience is enabled, Link will show as an option, regardless of whether or not Link is enabled as an express checkout option.

According to Stripe:

> If you would like to turn it off, you can navigate to your Stripe Dashboard and within your payment methods settings, you will be able to turn off Link for your integration from within the Link section.

However, if an account is connected via OAuth, the merchant cannot manage their payment methods at https://dashboard.stripe.com/settings/link or https://dashboard.stripe.com/settings/payment_methods since they're controlled by the Stripe WooCommerce Extension.

This essentially means that merchants who onboard via OAuth are locked into offering Link by Stripe.

**To Reproduce**
1. Connect a Stripe account via OAuth.
2. Enable the new checkout experience.
3. Disable Stripe Link in the express checkouts settings.
4. Attempt to purchase a product.
5. Notice that Link is offered in the Payment Element.

**Expected behavior**
Either:
1. Enabling/disabling the Link option in express checkouts will also prevent Link from rendering in the payment element.
2. There is a separate option for enabling/disabling Link in the payment element.

**Screenshots**
![link disabled still rendering](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/82999806/9c1c9db4-4f6c-444a-b5ed-ffdd370a665a)

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**
pc4etw-ID-p2

**Comment by tonygil** [comment]
I have the same problem . I do not want this to appear. I used css in chrome but gets overridden by Stripe. Have set all the options  in stripe dashboard  , not to show it but still appears.
Any suggestons ?

**Comment by diegocurbelo** [comment]
After 8.0.0 Link is no longer displayed during checkout if it's disabled in the plugin settings (Express checkouts section)

**Comment by millzee01** [comment]
ive didsbaled link on my payment methods settings, and also added disablelink : true to my options however I just cannot stop the link being displayed.  Its beginning to irritate me seeing this link shite.

**Comment by vishalnagv** [comment]
Hi, I have finally found a solution for this.

- Go to https://dashboard.stripe.com/test/settings/payment_methods on your dashboard
- Choose the payment method configuration you're using
- Click on Link
- Beside "Active" click on the button with 3 dots
- Click on Supported integrations
- Toggle "Payment Element" off (Or any integration you want to disable it for)

Hope this works. Happy coding!

**Comment by cremigerhonig** [comment]
@vishalnagv 
no, this is not working. 
I deactivated Link all over the stripe dashboard and its still there

**Comment by cbarbier** [comment]
I was disabling in the production payment method configuration .
Mind the 'test'in the url [https://dashboard.stripe.com/test/settings/payment_methods](https://dashboard.stripe.com/test/settings/payment_methodsw) 

Spent 2 days on this ahah ^^

**Comment by cremigerhonig** [comment]
@cbarbier 
no its not working. I disabled link all over stripe dashboard, in test mode and live mode. 
https://imgur.com/iPmdC0E

stripe is telling me its handled by checkout plugin.
see here: https://wordpress.org/support/topic/link-advertising-during-payment/#post-18322996

but checkout plugin does not have any settings regarding link

**Comment by sblatnick** [comment]
I see this same problem.  Link.com just recently started to appear, without our consent.  Every avenue to disable is either ineffective (from woo commerce) or disabled (from in stripe).

1. Woo Commerce -> Settings -> Payments -> Link by Stripe -> uncheck and "Save changes".  Doesn't work, and if I navigate back to the page, it appears checked again.
2. Stripe Payments Methods -> click on WooCommerce row -> click on Link row -> "Disabled" button is grayed out
3. Stripe Payments Methods -> click on WooCommerce row -> click on Link row -> Availability -> Customize -> Supported integrations -> turn off each switch -> "Save changes" button is grayed out

Has anyone reported this problem to Stripe?  I'm asking their AI chat bot and it starts with saying I can't do this within Woo Commerce settings, that I need to manage the setting from within stripe.  I tell them that the disable button is grayed out, and they tell me I can't do this from Stripe settings, I need to do this from Woo Commerce!  They say alternatively to:

> If you process any payments directly through Stripe (not through WooCommerce), you can manage Link for those payments by going to Payment method settings and selecting "no platform" from the dropdown menu at the top of the page.

But I see no such drop down anywhere, and I don't want to disable card payments.

I don't even have permissions to reopen this issue?  Even the button here is disabled!
