### ISSUE TITLE
[Split PE] Unable to pay for a failed renewal order using a saved card on the block checkout

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-gateway-stripe#2904]
**Describe the bug**

On our deferred intents base branch (`add/deferred-intent`) there's an issue where customers cannot pay for a failed renewal order using an existing saved card while on the checkout block.

Here's the error they're presented on checkout:

![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/2275145/33d31454-3e50-4a6a-8d9d-b4a5aebf8a3a)

<details><summary>View full Stripe logs:</summary>
<pre>
2024-02-15T04:01:40+00:00 DEBUG 
====Stripe Version: 7.9.1====
====Start Log====
payment_intents/seti_1OjvEnG0R5hw25lMLuxpYZYA request: Array
(
    [payment_method] => pm_1OjuZsG0R5hw25lM4FLyePbr
    [payment_method_types] => Array
        (
            [0] => card
            [1] => sepa_debit
        )

    [amount] => 1600
    [currency] => eur
    [description] => Woo - Order 3591
    [metadata] => Array
        (
            [customer_name] => Matt Example
            [customer_email] => test1@example.com
            [order_id] => 3591
            [site_url] => https://woo.localhost
            [payment_type] => recurring
        )

    [customer] => cus_PQpGYW162Pd0F3
    [shipping] => Array
        (
            [name] => Matt Example
            [address] => Array
                (
                    [line1] => 969 Market Street
                    [line2] => 
                    [city] => 94103
                    [country] => US
                    [postal_code] => 94103
                    [state] => CA
                )

        )

    [setup_future_usage] => off_session
    [payment_method_options] => Array
        (
            [card] => Array
                (
                    [mandate_options] => Array
                        (
                            [amount_type] => fixed
                            [interval] => month
                            [interval_count] => 1
                            [amount] => 1600
                            [reference] => 3591
                            [start_date] => 1707966204
                            [supported_types] => Array
                                (
                                    [0] => india
                                )

                        )

                )

        )

)

====End Log====

2024-02-15T04:01:41+00:00 DEBUG 
====Stripe Version: 7.9.1====
====Start Log====
Error: stdClass Object
(
    [error] => stdClass Object
        (
            [code] => resource_missing
            [doc_url] => https://stripe.com/docs/error-codes/resource-missing
            [message] => No such payment_intent: 'seti_1OjvEnG0R5hw25lMLuxpYZYA'
            [param] => intent
            [request_log_url] => https://dashboard.stripe.com/test/logs/req_qXoRHZIEslTHM2?t=1707969701
            [type] => invalid_request_error
        )

)

====End Log====
</pre>
</details> 

Using the stripe logs, it looks like the issue is caused by our code sending a `payment_intents/` request with a setup intent ID (`payment_intents/seti_1OjvEnG0R5hw25lMLuxpYZYA`).

**To Reproduce**

1. Enable UPE gateway and checkout `add/deferred-intent` branch
2. Set a block checkout as your default checkout
3. Purchase a subscription using a successful card (i.e. 4242)
4. From the My Account > View subscription, change the payment method on this subscription to a card that will fail on next renewal: `4000000000000341`
5. Process a renewal order from the WP Admin Edit Subscription actions
6. Go to My Account > Orders and click on "Pay" next to the most recent failed order
7. Attempt to use the saved 4242 card to fix up the failed renewal order
8. Notice the checkout fails.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version
 - WooCommerce Version
 - Stripe Plugin Version
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed

**Additional context**

**Comment by james-allan** [comment]
FWIW I haven't been able to replicate this error.

**Comment by mattallan** [comment]
> FWIW I haven't been able to replicate this error.

Spoke about this in Slack, but for posterity, in order to reproduce the issue you need to go through the "My Account > View Subscription > Change payment" flow as this is incorrectly setting a `_stripe_setup_intent` meta on the subscription.

When the renewal order is created, this setup intent is being copied from the parent subscription.

Then inside `process_payment_with_saved_payment_method()`, it's getting any intent from the order using `$intent = $this->get_intent_from_order( $order );` which is returning the setup intent copied from the subscription, which then results in the `"payment_intents/{setup_intent->id}"` being incorrectly used.

There are two main issues:
- When we change a subscriptions payment method, we shouldn't store the setup intent on the subscription
- When we use a saved card on the block checkout, we shouldn't be calling `process_payment_with_saved_payment_method()`. This issue is caused by incorrect logic in `add_payment_request_order_meta()` causing `wc-stripe-is-deferred-intent` data to not be set.

**Comment by mattallan** [comment]
Closed by #2906
