### ISSUE TITLE
[Split PE] Payment methods can't be added via My Account > Payment Methods

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2907]
**Describe the bug**

An error is displayed, and no local token is created when adding a new payment method via My Account > Payment methods. The payment method is created in Stripe.

**To Reproduce**
1. As a shopper, go to My Account > Payment Methods > Add Payment Method http://localhost:8082/my-account/add-payment-method/
2. Save a new card `4242424242424242`
3. Notice that:
- You get an error message saying "Cannot read properties of undefined (reading 'error')"
<img width="400" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/350648b6-c5ba-44ba-be9d-1af2aae78f14">

- There's an error message in the debug log saying
```
PHP Notice:  Undefined index: return_url in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-intent-controller.php on line 959
```
- No local token is created
- A payment method gets created in Stripe

**Expected behavior**
A local token and a remote payment method must be created when saving a card via the My Account > Payment Methods page. No error message must be displayed and there must not be any entries in the debug log.

**Comment by james-allan** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2918.
