### ISSUE TITLE
[Split PE] The PE fails to be rendered on the Block checkout when shopping as a guest

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2919]
**Describe the bug**
When going to the Block checkout page as a guest, the PE isn't rendered. 

<img width="700" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/602f35af-e448-4e2e-b985-6338e030783f">

**To Reproduce**
1. Check out `add/deferred-intent`
2. Visit the store as a guest
3. Add a product to the cart and proceed to the Block checkout
4. Under Payment options, select Credit / Debit card
5. Notice that the fields for entering the card details aren't displayed
6. Open the browser console
7. Notice the following error is displayed there:

```
upe_blocks.js?ver=958e17fd142ddc6b92539d0d73ab8eb9:1 Uncaught ReferenceError: wc_stripe_upe_params is not defined
```

**Expected behavior**
The Payment Element must be rendered when checking out as a guest. No errors must be triggered.

**Comment by james-allan** [comment]
Hey @a-danae. I'm unable to replicate this issue. 

When I view the checkout page as a guest user the payment forms load as expected. I've recorded a short video of what I see on my local incase that helps explain what I'm missing. 


https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/4cac7337-d293-46c6-b1ae-2727c7314c71

The only way I can see the `wc_stripe_upe_params` parameter not being loaded is if [one of these conditions pass](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/add/deferred-intent/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php#L255-L269) but none of them look like turn on whether the user is logged in or a guest user. 🤔

**Comment by a-danae** [comment]
Makes sense 🤔 and I can't replicate it anymore. Not sure what could have caused it at the time. I'll open this again if I see this behavior again. Thanks for checking @james-allan !
