### ISSUE TITLE
Error Saving Changes

### ISSUE THREAD

**Issue by Maxtab** [woocommerce/woocommerce-gateway-stripe#2921]
Hi,

I noticed a very annoying problem which prevents me from saving the module configuration changes. I'm not sure about the steps to reproduce and Surprisingly, I found a solution for this problem somewhat by chance but I think it needs a fix.

**Here is what was expected:**
You change any settings, you click on "Save" and it updates the settings.

**What was happening:**
You modify plugin settings (Activate or deactivate test mode, or any other option) and by clicking on "Save", the notification indicates that the settings cannot be saved ("Error saving changes"). By refreshing the page, no changes have actually been taken into account.

Looking in the browser console, I was seeing a 400 or 401 error when clicking the save changes button.

I did this under Wordpress 6.4.3 and Woocommerce 8.6 (but I already had this bug under Woocommerce 8.2.2).

I tried to activate only Woocommerce and the Woocommerce Stripe Gateway module, on the Storefront theme (no other plugin) and I got the same problem.

A bit by chance, I managed to solve this. In the plugin settings, and **even if you do not use Google Pay / Apple Pay**, click on "Customize" and check that in the "Appearance" section, one of the button size options is checked (in my case none of the 3 options "Small/Medium/Large" was checked). I selected one of the options, saved the change, and it worked. Then everything else worked normally again.

I would like to point out that this bug only impacted the saving of settings, payments were functional).

**Environment:**
 - WordPress Version 6.4.2
 - WooCommerce Version 8.6.0 (but was already existing with 8.2.2)
 - Stripe Plugin Version 7.9.3 (but already existing with 7.7.0)
 - Browser [e.g. chrome, safari] and Version All
 - Any other plugins installed Tested with no other plugins activated, and with Storefront theme

Below, no options was selected at all for the size of the button. Once an option is selected, everything works as expected and we can save the settings.

![2024-02-19 14 47 53 dev aunomdelaroseitalia com 064e561f29fa](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/16206268/8e1c6fe4-2e23-459e-8526-5ec2bb48c138)

**Comment by Maxtab** [comment]
Also discussed on the plugin support forum on wordpress.org with more details about the error message that we can see in the console : 
https://wordpress.org/support/topic/urgent-error-saving-settings-not-working/page/2/#post-17436702


![Screenshot-139](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/16206268/1dd3f345-0645-45f3-8a4e-92b566f6cae2)

**Comment by shameemreza** [comment]
Resolved following this workaround: 7762019-zen

**Comment by shameemreza** [comment]
Another report here: 7811022-zen
Thread link: https://wordpress.org/support/topic/cannot-save-settings-26/

The shared workaround didn't work.

**Comment by ldr2273** [comment]
8157090-zen but resolved with workaround

**Comment by thuautp** [comment]
Issue happened again in Stripe v.8.8.2 in 9011224-zen. I used the workaround and it worked.

**Comment by Mayisha** [comment]
@thuautp in 9011224-zd-a8c was it the same issue with button size?
