### ISSUE TITLE
[Split PE] SEPA not being displayed under My Account > Add Payment Method

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2922]
**Describe the bug**
When the Updated Checkout Experience and SEPA are enabled, SEPA isn't displayed under My Account > Add Payment Method, even though it's reusable.

**To Reproduce**
1. Checkout the `add/deferred-intent` branch
2. Under WooCommerce > Settings > General, set the store currency to EUR
3. Under the Stripe Settings tab, enable the Updated Checkout Experience
4. Under the Stripe Payment methods tab, enable SEPA
5. As a shopper, go to My Account > Payment Methods > Add Payment Method
6. Notice SEPA isn't displayed within the available payment method types to be added

<img width="700" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/aae9aae9-7041-420b-bc24-d4140f9e0a1a">

**Expected behavior**
Since SEPA is reusable, it must be displayed under My Account > Payment Methods > Add Payment Method.

**Comment by james-allan** [comment]
I think this should be fixed with https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2918.

**Comment by james-allan** [comment]
> I think this should be fixed with https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2918.

I've confirmed that SEPA is now shown on the Add payment methods page. Closing this one. :) 

<img width="700" alt="Screenshot 2024-02-20 at 12 42 55 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/5e84934f-8d59-4e34-8aee-68b2594e25dd">
