### ISSUE TITLE
Split UPE w' Deferred Intent - APMs shown on classic checkout with auth and capture enabled

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce-gateway-stripe#2923]
**Describe the bug**
With Auth and Capture enabled, APMs are being shown on the classic checkout. With auth and capture enabled, only card payments are allowed. 

| <img width="272" alt="Screenshot 2024-02-20 at 11 35 12 am" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/c2209917-45ce-4f4d-a428-3a19692ccbda"> | <img width="565" alt="Screenshot 2024-02-20 at 11 35 42 am" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/d6051ab9-38c8-4593-a471-94a36da2bf66"> |
|--------|--------|

**To Reproduce**

1. Checkout the `add/deferred-intent` branch
2. Under **WooCommerce > Settings > General**, set the store currency to EUR
3. Under the Stripe Payment methods tab, enable all available APMs. 
4. Under the Stripe Settings tab, enable the Updated Checkout Experience and the _'authorization on checkout, and capture later'_ setting.
6. As a shopper, add a product to your cart and go to the classic checkout. 
7. Notice all APMs are displayed. 

<img width="300" alt="Screenshot 2024-02-20 at 11 42 21 am" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/155afbce-cc24-42a9-8408-31cf66fa36f8">

**Expected behavior**
Only cards should be available under this situation.

**Comment by mattallan** [comment]
Closed with #2924
