### ISSUE TITLE
[Split PE] Returning to the store after Bancontact, iDEAL, or Sofort doesn't save the payment method

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce-gateway-stripe#2928]
**Describe the bug**

When you opt to save a payment method and you use a payment method like Bancontact, iDEAL or Sofort, when you return to the store after authenticating the payment, the payment method isn't saved. 

**To Reproduce**

1. Check out **add/deferred-intent**
1. Select EUR as the store currency
2. Under the Stripe settings, enable UPE and enable Bancontact, iDEAL, Sofort
3. As a shopper, go to the checkout page
3. Select "Use a new payment method"
4. Select Bancontact, iDEAL or Sofort
5. Check the box to save the payment method
6. Place the order
7. Authorize the payment
8. When you are returned to the store, open the database `wp_woocommerce_payment_tokens` table and notice that no `stripe_` token was created for that saved payment method. 

**Expected behavior**
The token should be saved on returning to the store as it has now been authorized and converted to a saveable token (reusable SEPA in this case).

**Comment by mattallan** [comment]
Closed by #2929
