### ISSUE TITLE
New settings page issue

### ISSUE THREAD

**Issue by Mayisha** [woocommerce/woocommerce-gateway-stripe#2932]
**Describe the bug**
While reviewing https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2870 @mattallan discovered a few issues with payment methods when UPE is disabled.
- In order edit page, the payment method name is wrong. If the order is paid with `EPS` it is showing `Payment via stripe_eps` instead of `Payment via EPS` (same for all other methods)
- ~~In the checkout page for a subscription order, all the stripe methods are showing up~~ (This is the same behavior as the trunk, so not a bug. The subscriptions are created as manually renewing subscriptions for payment methods using source)

**Expected behavior**
- If the order is paid with `EPS`  in order edit page it should show `Payment via EPS` (same for all other methods)
- ~~In the checkout page for a subscription order, only the supported methods should be displayed.~~

**Comment by a-danae** [comment]
This should have been fixed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2934

**Comment by a-danae** [comment]
This should have been fixed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2934
