### ISSUE TITLE
Allow going through the oAuth flow in test mode

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2936]
**Describe the bug**

When connecting a website to Stripe for the first time, the "Create or connect an account" button takes you through the live flow. The "Enter account keys (advanced)" is only displayed if connecting through oAuth isn't available. 

When using a Jurassic Ninja site, or any other site that can use oAuth, we'll need to use a test account.

This behavior was updated in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2704

**To Reproduce**
1. Disconnect your Stripe account if you have one connected to your site. Or install the extension on a fresh site
2. Go to the Stripe settings page
3. Click on "Create or connect an account"
4. Follow the steps
5. Notice you're on a live flow. There's no way to go through in test mode

In the meantime, the workaround is to go back to the store after selecting an account, and then edit the saved keys, but this isn't ideal.

**Expected behavior**
There must be a way to connect the store to a test account.

**Comment by AashikP** [comment]
Yes, please! ~There's no way for someone with no live account to test Stripe as of now.~

**Edit:** 

Until this is fixed, we can try the following workaround:

1. [Download older version of Stripe (7.9.3)](https://downloads.wordpress.org/plugin/woocommerce-gateway-stripe.7.9.3.zip)
2. Use test account Keys:

    
    <img width="950" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/17475174/e40016a0-254e-412c-8ce6-2d8768af9f07">

3. Update Stripe to latest version post configuration

**Comment by a-danae** [comment]
Hey @AashikP ! Thanks for providing instructions on how to sort out this limitation 🙂 

In case it's of help, there's also this other workaround that wouldn't involve downgrading the extension version.

Copied from our Wiki > [Manual plugin installation and setup](https://github.com/woocommerce/woocommerce-gateway-stripe/wiki/Critical-flows-%E2%80%90-Instructions#manual-plugin-installation-and-setup) > Step 3 

- Click on the "Create or connect an account" button.
    - Select or create an account.
    - On the left sidebar, click "Return to WooCommerce Inc."
    <img width="300" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/25b10afe-c04b-4371-a328-fb832e5c21a0">

    - Enable **Test mode** and save
    <img width="500" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/8c5c2f38-4ee2-4db2-8f9d-c1b89f9a59a1">

    - Go to **Edit account keys > Test** and manually enter the test keys from your account
    <img width="500" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/a8a23775-6f80-41f9-869c-87b7d87eb5aa">

**Comment by AashikP** [comment]
Thank you! @a-danae

**Comment by a-danae** [comment]
Closing this issue in favor of #3291 . We'll handle this functionality over there.
