### ISSUE TITLE
Unexpected date in the past for the mandate's start_date when renewing a subscription

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#2946]
**Describe the bug**

Under some conditions, the following error is triggered when renewing a subscription:

> Mandate or subscription cannot have start date before yesterday in IST. Expected start_date to be at or after 2024-02-20 18:30 UTC ([1708453800](tel:1708453800)) but was 2024-01-21 17:37 UTC ([1705858639](tel:1705858639)).

**To Reproduce**

1. Install Woo Subscriptions. 
2. Create a subscription product if you don't already have one.
3. Go to **WooCommerce → Subscriptions**
4. Click **"Add new"** 
5. Enter a start date more than 3 days ago. 
6. Add an item and a customer etc. 
7. Save. 
8. From the Actions dropdown create pending **parent** order. 

<p align="center">
<img width="317" alt="Screenshot 2024-03-14 at 1 33 35 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/549fdcf0-0995-4ea1-a54e-bf6fea9124da">
</p>

8. From the Actions dropdown create pending **renewal** order. 
9. Attempt to pay for the renewal using Stipe.
10. This should technically result in the error because the timestamp passed to Stripe is well in the past.

| <img width="274" alt="Screenshot 2024-03-14 at 1 44 53 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/e57c180c-e228-4c9d-a2a8-0ae7b3545928"> | <code>1696131460 => 1 October 2023 03:37:40</code> |
|--------|--------|

**Expected behavior**

**Additional context**

This property is set in `WC_Stripe_Subscriptions_Trait::create_mandate_options_for_order()`. [Ref](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/release/7.9.3/includes/compat/trait-wc-stripe-subscriptions.php#L671).

The user worked around it by modifying this line to use the current time instead of the subscription's start date.

Reported in 7774448-zd-a8c
Slack conversation p1708954998853999-slack-C055WHLA98D

**Comment by james-allan** [comment]
I've updated the issue description with steps I believe can lead this error. I wasn't able to replicate personally but we've had reports of this occurring for merchants not based in India or using cards issued in India.

**Comment by maxrice** [comment]
As I mentioned in #2988, this happens for every (imported) subscription renewal on our site where the start date is in the past but a payment mandate wasn't previously created. I've fixed it by filtering `woocommerce_stripe_request_body` and setting `$request['payment_method_options']['card']['mandate_options']['start_date'] = time();` only for the imported subscriptions.

**Comment by Mayisha** [comment]
Another report 7973530-zd-a8c

**Comment by wyter** [comment]
7945947-zen

**Comment by shohanhossainnab** [comment]
7974065-zen

**Comment by kaushikasomaiya** [comment]
7984192-zen

**Comment by Mayisha** [comment]
The fix has been shipped in `8.1.1`.
