### ISSUE TITLE
[Split PE] Error attempting to reuse a payment intent that requires action or confirmation

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-gateway-stripe#2950]
## Describe the bug

When I use a UPE payment method that requires redirect or a 3DS card that requires confirmation, I get the following error when I attempt to process the checkout again:

![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/2275145/2a6325c4-26c4-40f5-b887-81b4116770ba)

What's causing this is we're trying to reuse the payment intent that we stored on the order, and pass it to a `/payment_intents/pi_123/confirm`, and Stripe is throwing an error due to the intent not being in a valid state for confirming it via their API.

### With a 3DS card

1. Add a product to your cart and navigate to the checkout page
2. Purchase using a 3DS card: `4000000000003220`
3. When the pop-up appears, refresh your checkout page
4. Attempt to checkout again using the same card `4000000000003220`
5. Notice the error on checkout ![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/2275145/faf10bde-866b-4c37-825a-f49dfd275d54)

### With a UPE redirecting payment method

1. Set your currency to EUR and eable EPS
2. Add a product to your cart and navigate to the checkout page
3. Select EPS on the checkout and place order
4. Once you've been redirected off-site to the EPS payment page, don't click on any buttons and manually navigate back to your dev store checkout page (i.e. `https://woo.local/checkout`)
6. Attempt to checkout again using EPS
7. Notice the same error on checkout

**Comment by a-danae** [comment]
This should have been fixed by #2952
