### ISSUE TITLE
Unable to save plugin settings when existent bank descriptor is no longer valid

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#2971]
**Describe the bug**

Unable to save changes on the plugin settings page when there is a valid bank statement descriptor previously saved in the plugin settings.

With the change to use the statement descriptor from the Stripe account, in some cases the old bank statement descriptor editable through the plugin settings were not deleted; causing an error when validating the settings prior to saving the changes.

**To Reproduce**
1. Use WP CLI to save an invalid bank statement descriptor:
    `wp option patch update woocommerce_stripe_settings statement_descriptor 'long character description'`
2. Go to `WP-Admin > WooCoomerce > Settings > Payments` 
3. Click on the `Stripe` gateway
4. Click `Save changes`
5. See error

**Expected behavior**
The statement descriptor should not be in the plugin saved settings anymore (it fetched from Stripe)

**Screenshots**
![gB3Woj](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/407542/1c06eefa-d61b-45ec-a73c-c7a12ad684b1)

**Comment by shameemreza** [comment]
Reported here: 7827807-zen
Thread link: https://wordpress.org/support/topic/statement-descriptor-error/

**Comment by carolframen** [comment]
7858598-zen

**Comment by rogercoathup** [comment]
Any update on this -- unable to configure a new test server, as we can't save the Stripe settings.  
Note in our case the descriptor includes an apostrophe (') which is part of the business name.

Update:  After running the wp option patch -- name remains the same in settings (The Golfer's Journal), but we can now save the settings.
