### ISSUE TITLE
Google Pay not working in 8.0.0

### ISSUE THREAD

**Issue by tarkan123** [woocommerce/woocommerce-gateway-stripe#2978]
**Describe the bug**
When I updated the plugin to version 8.0.0, the Google Pay is not shown on the cart or checkout pages.

Log does not show any information.

**To Reproduce**
1. Install version 8.0.0
2. Visit website using Chrome browser, and checkout does not show the G-Pay button
3. Downgrade plugin to version 7.9.3
4. Visit website using Chrome browser, G-Pay button is shown as a payment option

**Expected behavior**
Google Pay to work with plugin version 8.0.0

**Environment (please complete the following information):**
 - WordPress Version   6.4.3
 - WooCommerce Version 8.6.1
 - Stripe Plugin Version 8.0.0
 - Browser [e.g. chrome, safari] and Version  Latest Chrome
 - Any other plugins installed

**Comment by wjrosa** [comment]
hi @tarkan123! Can you try again using the current version ([8.0.1](https://github.com/woocommerce/woocommerce-gateway-stripe/releases/tag/8.0.1))? I just tested it, and I can see the G-Pay button:
![Screenshot_20240318_165913_Chrome](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/10187816/609e1b15-16ca-4e3c-82b4-5a905057f99c)

**Comment by tarkan123** [comment]
Nope does not work for me.

Install 8.0.1, refresh cart - G Pay missing.

Re-install 7.9.3, refresh cart - G Pay appears.

Still broken for me.

**Comment by wjrosa** [comment]
> Nope does not work for me.
> 
> Install 8.0.1, refresh cart - G Pay missing.
> 
> Re-install 7.9.3, refresh cart - G Pay appears.
> 
> Still broken for me.

I just tested it again with both the block checkout and the shortcode checkout. Also tested with block and shortcode carts. Do you have other plugins installed? Are you trying it on your desktop or mobile device? (If desktop, can you try mobile or vice-versa?). Also, can you please send a screenshot? It can help us to better identify your configuration.

**Comment by tarkan123** [comment]
@wjrosa I am testing on mobile. It is the same on our local  development site as well. I have disabled all the  customizations (i.e. removed functions.php), deactivated all woocommerce connected plugins (paypal plugin, eu vat, country based pricing, etc). Still the same thing install 8.0.1 refresh cart no G-Pay button, back to 7.9.3 and G-Pay re-appears.

Let me know what you think I can do to help debug? cannot see any issues in the stripe log (woocommerce-gateway-stripe).

Do you think after installing 8.0.1 should delete all transient caches and maybe restart php? would that help?

**Comment by tarkan123** [comment]
I should add I switched to Storefront theme, in case it was theme related.

**Comment by tarkan123** [comment]
Re-installed 8.0.1 and it seems to be working now - not sure if we had a network issue causing the problem which did not seem to effect 7.9.3. Closing for now.

**Comment by wjrosa** [comment]
Awesome! Thanks for letting me know.
