### ISSUE TITLE
Request to Reimplement Apple/Google Pay on Variable Products

### ISSUE THREAD

**Issue by alanvitek** [woocommerce/woocommerce-gateway-stripe#2992]
**Describe the bug**
Hi! I would like to suggest a change with how Apple/Google Pay buttons are presented on variable product pages. With the recent update [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2886), Apple Pay and Google Pay buttons do not appear on variable product pages, and only show up on the final checkout page. This design was intended to mitigate issues with required fields, but changes the UX benefits of Apple/Google Pay buttons by moving it to the final step in the checkout process, removing the ability to bypass the standard checkout flow.

**Expected behavior**
As an example, let's say I'm selling a variable product like a t-shirt (color & size variations).

On the previous version, when clicking the Apple/Google Pay button on a variable product **before** all options had been selected (color/size), a browser alert was displayed to the user asking them to finalize all fields. 

Then, once all fields were completed, the Apple/Google Pay button would process the order as expected.

**Suggestions**
- Create an option to allow Apple/Google Pay button for variable products in Settings with required fields
- Hide or disable Apple/Google Pay button until all fields are completed on variable product, then enable it

**Environment (please complete the following information):**
 - WordPress Version: 6.4.3
 - WooCommerce Version: 8.6.1
 - Stripe Plugin Version: 8.0.1
 - Browser: Safari
 - Any other plugins installed

Thank you for your consideration!

**Comment by Mayisha** [comment]
@alanvitek the Apple/Google pay button is available on the variable product page. It is only unavailable if you have any additional required fields (for example, a required `company` field or a custom required text field) on the checkout page. 

> On the previous version, when clicking the Apple/Google Pay button on a variable product before all options had been selected (color/size), a browser alert was displayed to the user asking them to finalize all fields.

This statement is still true for the variable product page unless you have any additional required fields on the checkout page.

**Comment by alanvitek** [comment]
@Mayisha thank you clarifying! I don't believe I have any additional required fields on checkout or any hidden variations/fields on the product. There must be something else in my setup that's interfering with the Apple/Google Pay buttons from being shown. Thanks again :)

**Comment by Mayisha** [comment]
@alanvitek You should be able to see the Google/Apple Pay button on your cart and product page again as we are no longer hiding them because of the required custom checkout fields. The changes have been shipped in version `8.1.1`.

**Comment by alanvitek** [comment]
@Mayisha updated to version 8.1.1 and I see the Google/Apple Pay buttons again! Thank you :)
