### ISSUE TITLE
Apple Pay: Stuck 'Processing' before failure

### ISSUE THREAD

**Issue by alexryans** [woocommerce/woocommerce-gateway-stripe#300]
#### What I expected

Payment via Apple Pay should complete successfully

#### What happened instead

Apple Pay status stuck in 'Processing' for a long time, before failing silently.

#### Steps to reproduce the issue

I am using two environments to test a new Apple Pay integration into one of my WooCommerce stores. The 'Staging' and 'Production' environments are identical, other than Stripe's 'Test Mode' is enabled on 'Staging' and not on 'Production'. Testing Apple Pay on 'Staging' works absolutely fine and the process completes perfectly, however on 'Production', the Apple Pay sheet simply hangs as 'Processing', before the sheet minimises with no error.

The payment does not complete successfully, but does also not visually present any form of failure on the front-end of the site to users. The order is placed in the 'Orders' section of WooCommerce in WordPress Admin, but doesn't have any details assigned to it and is marked as 'Pending payment'.

![screen shot 2017-06-26 at 11 12 37](https://user-images.githubusercontent.com/3007053/27534900-6bd25bea-5a60-11e7-8407-0b21583fd216.png)

I have also tried disabling 'Test Mode' on the 'Staging' environment and the payment completes as expected.

Paying via a 'normal' payment method through Stripe also completes successfully on both environments.

Both the 'Staging' and 'Production' domains are verified successfully through the Stripe Dashboard as being available for Apple Pay use.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Did you enable logging? The logs usually will tell you what went wrong. They're in WC system status->logs

**Comment by alexryans** [comment]
Yes, logs are enabled, but no logs pertaining to Apple Pay or this issue are being logged.

**Comment by roykho** [comment]
Did you check JS console to see anything there? Finally did you check PHP error log? If it works for test it should definitely work for live as they're using the same code just different keys.

**Comment by alexryans** [comment]
Ah yes, the JS console has thrown a 500 error about a `wc_stripe_apple_pay` file.

![screen shot 2017-06-26 at 14 14 08](https://user-images.githubusercontent.com/3007053/27540907-cba5d088-5a79-11e7-834b-22c7162ab785.png)

**Comment by roykho** [comment]
I would recommend you turn all other plugins off except WC and Stripe and even switch to a default WP theme and re-test.

**Comment by alexryans** [comment]
Will do, thanks Roy!

**Comment by alexryans** [comment]
I'm a little confused how this is happening - both the 'Staging' and 'Production' environments are completely consistent in terms of their settings and plugins etc (as we manage all our dependencies via Composer and Git, to ensure the environments are the same), so there should be absolutely no reason why this shouldn't work on one environment and not the other, under the same circumstances.

Obviously, I cannot disable plugins/switch theme on the live, transactional production site, where the issue is apparent, and there are no conflicts and I cannot reproduce the error in the 'Staging' environment. Could you please assist further in diagnosing this issue?

**Comment by roykho** [comment]
Unfortunately those are all the steps I can think of. I am not able to replicate this issue. Closing this for now but feel free to reply if you have further questions.
