### ISSUE TITLE
[UPE] Remove interface items from the Payment methods tab when UPE is enabled

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#3005]
Due to the transition to UPE as the experience enabled by default, we want to remove the following items from the Payment Methods tab, along with their related functionality:

1. "Early access" label.
2. "Disable" option from the dropdown menu
<img width="1000" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/ab00179d-d3b7-498f-950d-1e22d6188576">

**Open question**
Is the "Refresh payment methods" button functionality still relevant for UPE?

**Comment by Mayisha** [comment]
> **Open question**
Is the "Refresh payment methods" button functionality still relevant for UPE?

So far it is still relevant for UPE. For `live` mode, the payment methods are rendered [based on their capabilities](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/92cdf93c41cd36c41d4c2967e4f07632a729424d/client/settings/general-settings-section/payment-methods-list.js#L191) in the Stripe account. If the user adds/activates a payment method in their Stripe account making the capability available (the capability of which was absent before in the account data), this `Refresh payment methods` then helps to refresh the account data and bring the latest capabilities object from the Stripe account.
