### ISSUE TITLE
BTC Outdated and NOT working.

### ISSUE THREAD

**Issue by BTCSTRIPE** [woocommerce/woocommerce-gateway-stripe#301]
Hello,

Your Stripe plugin is outdated with BTC payments.

Please see reply from Stripe for what the issue is ->

I was able to take a look into the error you're receiving and it appears to be the related to the use of the old Bitcoin endpoint. Because v1/bitcoin/receivers is being deprecated in favor of v1/sources in the coming month, I'm afraid onboarding has been discontinued for this endpoint.

Now although this is the case, it does appear that you have successfully onboarded into the the new Source endpoint [0] and as a result will have the ability to create a Bitcoin receiver using this flow. In case you haven't already found this, I would suggest reviewing at our documentation on how to implement this payment method here:

https://stripe.com/docs/bitcoin

In the event you don't have control over your integration and are using a third party plugin to create these charges, I would suggest reaching out to the team that created this plugin to see if they can utilize the Source flow for Bitcoin.

Thank you.

**Comment by roykho** [comment]
Yes we are already aware of this and will be worked on in the coming future.
