### ISSUE TITLE
Apple Pay will not work with Product Bundles

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce-gateway-stripe#302]
#### Affected ticket(s)

592580-zd-woothemes

#### What I expected

Create a product bundle, place in cart, be able to use Apple pay

#### What happened instead

Apple Pay option appears on single product pages as expected, but not on Bundled Product. If I place a bundled product in the shopping cart, Apple Pay is not available on the cart or checkout page. If I remove bundled product from shopping cart and have regular item, it appears again as expected on cart and checkout pages.

#### Steps to reproduce the issue

1. Create bundled product. For my test, I had two items, each with a regular price (no free items) and gave the bundle one price. (User in ticket had a free item in the bundle, and we wondered if that was the cause, it was not).

2. Configure Apple Pay and confirm that it works with regular items (yes) and checkout with regular items (yes)

3. Test with purchasing Bundled item, no Apple Pay Button.

Use notes that he also tried this with https://yithemes.com/themes/plugins/yith-woocommerce-product-bundles/ with the same results.

Tested with
WooCommerce 3.1.0
Product Bundles 5.3.1
Stripe 3.2.1
Storefront 2.2.4

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Closed in favor of #211
