### ISSUE TITLE
Hooks not working with new checkout experience.

### ISSUE THREAD

**Issue by tarkan123** [woocommerce/woocommerce-gateway-stripe#3021]
Stripe plugin version 8.0.1

Enabling the updated checkout experience stops the following hooks.

wc_stripe_payment_metadata

wc_stripe_generate_payment_request

**Comment by tarkan123** [comment]
Found a workaround, another hook in the code to modify metadata, which works with UPE enabled.

add_filter('wc_stripe_intent_metadata', 'your_payment_metadata_function', 10, 2);

function your_payment_metadata_function ($metadata, $order) {

}

**Comment by adam-adapt** [comment]
I can confirm that the `wc_stripe_payment_metadata` filter does NOT when using the New Checkout Experience.

The workaround using the `wc_stripe_intent_metadata` filter instead does not work.

**Comment by agenceKanvas** [comment]
Any workaround if I need to still use this filter ? It's not the metadata I need to work on but the address :/

**Comment by dougaitken** [comment]
Related internal Slack link - p1717479398669929-slack-C7U3Y3VMY

**Comment by aheckler** [comment]
We have updated [this docs page](https://woocommerce.com/document/stripe/customization/products-as-metadata/) to include an example code snippet that should work for any combination of new vs. legacy checkout experience and shortcode vs. block checkout.

If this is not working for you, we can _try_ to help, but we'll need exact error messages you're seeing in your logs, etc.

**Comment by wjrosa** [comment]
Can you try the above and let us know if it worked, @tarkan123 ?

**Comment by tarkan123** [comment]
I have been using wc_stripe_intent_metadata since April with the UPE and it has been working fine for me.

**Comment by wjrosa** [comment]
Cool! Thanks for the update @tarkan123 ! Also, thank you for the docs update, @aheckler . I will be closing this then
