### ISSUE TITLE
Apple Pay: Not displaying fees/surcharges...

### ISSUE THREAD

**Issue by spiffyguy** [woocommerce/woocommerce-gateway-stripe#304]
#### Affected ticket(s)

Current Version: 3.2.1

#### What I expected

The fee to show up and add to the total for Apple Pay.

#### What happened instead

No Fee showed up.  The total price is cheaper with Apple Pay.... (Good for customer, bad for merchant)

#### Steps to reproduce the issue

I have a hook setup in my functions.php to add a fee based on their state.  It works fine in the normal checkout but in Apple Pay, the fee does not show up.

Simple example I have tried:

```
<?php

add_filter('woocommerce_cart_calculate_fees', 'calculate_state_fee');

function calculate_state_fee() {
     global $woocommerce;
     $woocommerce->cart->remove_taxes();

     $woocommerce->cart->add_fee("State Fee: $50.23", 50.23, true, '');
}

?>
```
That $50.23 does not show up anywhere in the Apple Pay screen yet it shows up if I fill out the checkout fields and use normal stripe on the right side of the page.

Something like this needs to be added to the "class-wc-stripe-apple-pay.php" file 

```
      $currentFees= WC()->cart->get_fees();
      $currentFeesTotal= 0.0;
      foreach ($currentFees as $currentFeeKey => $currentFeeValue) {
            $currentFeesTotal+= $currentFeeValue->amount;
     }

     $item_total  = wc_format_decimal( WC()->cart->cart_contents_total, $this->dp ) + $discounts + $currentFeesTotal;
```

Is it possible to get fees added to the Apple Pay Checkout?

Thanks for your help,

- Matt

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Ref: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/211
