### ISSUE TITLE
Apple Pay Button Showing up in Chrome

### ISSUE THREAD

**Issue by psasser** [woocommerce/woocommerce-gateway-stripe#305]
I'm seeing the Apple Pay button show up in Chrome when it shouldn't be there.  Here is a screenshot of it... https://puu.sh/wCo4n/09475e8d79.png.  Here is a link to the page in action....https://goo.gl/UnHGsy.  

Digging into the code of the plugin it looks like the CSS to hide the Apple pay isn't being loaded on that page.  The CSS is only loaded on pages that are "single" templates and this is just a standard page (https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-apple-pay.php#L266-L269).  

This is a page with product shortcode in it.  It has shortcode like this in it [product_page id="2781"].

**Comment by roykho** [comment]
@psasser - please give the master branch a test to see if it fixes your issue.
