### ISSUE TITLE
Consider replacing FILTER_SANITIZE_STRING, since it is deprecated as of PHP 8.1.0

### ISSUE THREAD

**Issue by anastas10s-afk** [woocommerce/woocommerce-gateway-stripe#3056]
**Describe the bug**
Came across a report on the forums, where the site's logs report the following:
PHP Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-customer.php on line 189

As it appears, it would be beneficial to use [htmlspecialchars()](https://www.php.net/manual/en/function.htmlspecialchars.php) instead, as [FILTER_SANITIZE_STRING](https://www.php.net/manual/en/filter.constants.php#constant.filter-sanitize-string) ([int](https://www.php.net/manual/en/language.types.integer.php)) ID of “string” filter is deprecated as of PHP 8.1.0.

**Additional context**
Per the [search results, linked here](https://github.com/search?q=repo%3Awoocommerce%2Fwoocommerce-gateway-stripe%20FILTER_SANITIZE_STRING&type=code), it appears in the files:

- includes/class-wc-stripe-customer.php
- includes/payment-methods/class-wc-stripe-payment-request.php

Moreover [htmlspecialchars()](https://www.php.net/manual/en/function.htmlspecialchars.php) is compatible with current and future PHP versions, as I understand.

For context:

- https://wordpress.org/support/topic/filter_sanitize_string-is-deprecated-3/
- 8014265-zen

#hc

**Comment by anastas10s-afk** [comment]
cc @a-danae 🙂

**Comment by a-danae** [comment]
Ack. Thanks for the heads up @anastas10s-afk ! 🙂

**Comment by mattallan** [comment]
Oh sorry @a-danae ! I just found this issue after opening a PR and noticed you assigned yourself to it a month ago. It was only a small change but I hope you weren't also in the middle of fixing it

PR here: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3144

**Comment by a-danae** [comment]
No way, thanks for fixing this @mattallan ! 🙌
