### ISSUE TITLE
Apple pay css overriding theme styles

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce-gateway-stripe#306]
Not sure if this is something that can be changed or not. Customer in below forum thread says that our css is overriding styles within their theme and that we should have prefixes on our elements as to not affect other theme/plugin styles. 

#### Affected ticket(s)

https://wordpress.org/support/topic/add-prefix-class-css-for-apple-pay/

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Need more information. What exactly is overriding. Any links?

**Comment by jessepearson** [comment]
Just asked for more info in the thread, will close until an example is provided.

**Comment by anhdq1801** [comment]
Hi @jessepearson  @roykho 

You css override default stye woocommerce element when Apple Pay still disabled.
https://monosnap.com/file/tmUAzgxUr5RrzAOwWccjwLa0bSVoo5#

It override our theme style on normal state. 

It better if  you add your prefix class new when Apple Pay enable and your css write with prefix class
https://monosnap.com/file/GaxC88UBmGu5DGEhk8pelyJzZMMMUi#

Thanks
![ribbed-panel slub knit top gecko 2017-07-08 01-46-22](https://user-images.githubusercontent.com/10084855/27972390-6856d33c-6380-11e7-898b-5619b956daaf.jpg)

**Comment by roykho** [comment]
@anhdq1801 please show screenshot of the affected area not the CSS in question. And what theme are you using?

**Comment by anhdq1801** [comment]
Now we issue on my local, this issue have on only Safari.
@roykho 
I checked on 2 themes
https://themeforest.net/item/gecko-powerful-ajax-woocommerce-theme/15863658
https://themeforest.net/item/flatsome-multipurpose-responsive-woocommerce-theme/5484319

I attached 4 screens when enable and disable Stripe.


![disabled-stripe](https://user-images.githubusercontent.com/10084855/27982521-7eef50cc-63cd-11e7-9ef2-261cb168e070.jpg)
![gecko-disable](https://user-images.githubusercontent.com/10084855/27982520-7eee0460-63cd-11e7-888a-fdae4a02383b.jpg)
![gecko-enable-stripe](https://user-images.githubusercontent.com/10084855/27982519-7eedfa24-63cd-11e7-8671-e67bfe182cb9.jpg)
![when-enable-stripe](https://user-images.githubusercontent.com/10084855/27982518-7eed9b2e-63cd-11e7-9680-89b3d25cb30d.jpg)

**Comment by roykho** [comment]
Are you using Apple Pay?

**Comment by anhdq1801** [comment]
Yes, my customer use Apple Pay and saw this issue.

**Comment by anhdq1801** [comment]
Now have another issue when I still activate plugin Stripe but don't enable Stripe payment method.  https://monosnap.com/file/9wVJUrOr13UKeYLp32K4UNhEdYQLDG#

The CSS of Stripe still load
https://monosnap.com/file/k1raZcT7bQA2Q29kI9q0YJwMJx4H6b#

The issue on only Safari on Mac.

Thanks
