### ISSUE TITLE
Remove "via WooCommerce" from Apple Pay descriptor

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-gateway-stripe#307]
This was brought up in a live chat with sales at throwninstone dot co dot uk on July 10th:

Can we add the ability to disable the "via WooCommerce" text from the site descriptor in Apple Pay:

!["via WooCommerce" text to remove](http://cld.wthms.co/GMSbI+)
Direct Link: http://cld.wthms.co/GMSbI 

`'label' => $this->statement_descriptor . ' (via WooCommerce)',`

in file /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-apple-pay.php

**Comment by roykho** [comment]
@pmaiorana @mattyza - do we want to allow them to remove that? Another words is there any agreement we have that requires that to be there?

**Comment by mattyza** [comment]
@roykho - Yep, this is required.

This text shouldn't show anywhere other than the Macbook Touchbar, according to Apple Pay.

Showing this text in the payment sheet doesn't seem too bad, to me.

cc @zwiesman31 @pmaiorana

**Comment by roykho** [comment]
This will show up on the payment sheet as well.

**Comment by mattyza** [comment]
@roykho - that's fine. We can speak with Apple Pay and see if there is a different parameter we can use. Perhaps they can add one. Not a high priority item right now, in my opinion.

**Comment by AJerm** [comment]
It's a shame this can't be removed. I'm not sure why it has to say it seeing as WooCommerce doesn't process the payment, do they? Apple does all that.

I've been playing with the new browser based payment button in the 4.0 beta, they also say this in Chrome (and I assume other browsers)

Can it be removed from these? If anything I would have though those would have to say 'via stripe', seeing as they're the one's processing the payment in these cases.

Just seems odd to me that it effectively says "Via my ecommerce solution"

**Comment by roykho** [comment]
@AJerm in 4.0 there is a filter to remove it please do a search in code for "via woocommerce" and you will find the filter.

**Comment by fetchgit** [comment]
You don't have to introduce customer to new terms at the time of checkout, WooCommerce is not visible anywhere and suddenly it is on my credit card transaction popup,
It should say either via Stripe or just keep up with a website url 
Thank you

**Comment by donaldking** [comment]
How can I remove this? I can't find the file referenced in the first post ```in file /wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-apple-pay.php```

**Comment by donaldking** [comment]
Fixed it. For anyone interested: https://gist.github.com/madeincosmos/4e9c047c8433bccce931f0facb4dbe41

**Comment by AJerm** [comment]
Does that work for you in the latest version @donaldking? 

I just tried putting it in my functions.php file on two sites, and it doesn't seem to have removed it from either.

**Comment by donaldking** [comment]
@AJerm Yes, it did work for me just fine for me. If you have any cache plugin installed, make sure you clear any saved cache.
