### ISSUE TITLE
[Klarna] Improve handling of unsupported merchant account countries

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#3070]
When Klarna isn't available for the merchant Stripe account's country, the experience isn't ideal:
- Klarna is displayed as available on the Payment Methods tab in Stripe settings, at `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods`
- When visiting the checkout page, Klarna is displayed as a payment method option, but the Payment Element fails to be rendered with the following error

```
Unhandled payment Element loaderror 
{
    "type": "invalid_request_error",
    "message": "The currency provided (usd) is invalid. Payments with klarna support the following currencies: .",
    "param": "deferred_intent.payment_method_types",
    "request_log_url": "https://dashboard.stripe.com/test/logs/req_6Jk9s5YmEKYLVI?t=1712860995",
    "status": 400
}
```

<img width="700" alt="image" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/78e1e9bb-dd8e-4055-81c0-88d3eac8e9e8">

**Describe the solution you'd like**

TBD. Maybe add a note on the payment methods tab and don't display the payment method on the checkout page. Similar to what we do when the store currency isn't supported by the payment method.

Let's take the merchant country limitations of other payment methods into account when considering how to approach this.

**Additional context**

[List of merchant country availability](https://docs.stripe.com/payments/klarna#:~:text=Merchant%20country%20availability) for Klarna.

**Comment by james-allan** [comment]
> TBD. Maybe add a note on the payment methods tab and don't display the payment method on the checkout page. Similar to what we do when the store currency isn't supported by the payment method.

Yeah I think that makes sense. FWIW, WooPayments do the same thing - they display Klarna and in the description it says that only transactions in USD are accepted. 

<img width="708" alt="Screenshot 2024-04-16 at 3 22 15 pm" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/5272d72f-b33e-4f9a-a2cd-6b9cec5f22e5">

> Let's take the merchant country limitations of other payment methods into account when considering how to approach this.

I don't know if I've misunderstood this comment but it was my understanding that other payment methods (like GiroPay) require the store currency to be set to Euros to be enabled. That is different from how WooPayments works. They let you enable anything and then only show eligible payment methods on the checkout.

I think ideally we'd do something similar for all our payment methods. I think I recall talking about this at the meetup but there's a seperate issue for that here: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2970

**Comment by a-danae** [comment]
Thanks for the insights here, @james-allan ! 

> I don't know if I've misunderstood this comment but it was my understanding that other payment methods (like GiroPay) require the store currency to be set to Euros to be enabled.

Yup, that's true. Besides the currency requirement, some payment methods (at least [BNPLs](https://docs.stripe.com/payments/buy-now-pay-later#product-support)) are only available for merchants using a Stripe account from a specific country.

So, I tried to keep other payment methods in mind when we work on this, so it's not Klarna-specific if this limitation is present for other payment methods. Yeah, probably something we'd keep in mind anyway 🙂 Please feel free to update the issue description if it could be clearer!

👀 Aaaaaand, now that I think of this again, we're already handling Stripe account country limitations for payment methods for OXXO and Boleto. We could keep the behavior we have for those.

> They let you enable anything and then only show eligible payment methods on the checkout.

Right! And this is also how we handled the currency limitation before 8.0.0, if I recall correctly, which is what the issue you referenced asks for, in #2970.

I'm not sure how they handle the Stripe account country limitation, though. 

> I think ideally we'd do something similar for all our payment methods.

I fully agree.

**Comment by Mayisha** [comment]
I can not reproduce this issue anymore. Both of the cases are already fixed in other PRs. 

> Klarna is displayed as available on the Payment Methods tab in Stripe settings, at /wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods

This was fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3114. 
If I connect to a Stripe account of any unsupported country (for example Mexico), I do not see Klarna in the settings page.

> When visiting the checkout page, Klarna is displayed as a payment method option, but the Payment Element fails to be rendered with the following error

This was fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3108.
If I connect to a US Stripe account and set the store currency to Euro, Klarna is present on the settings page but it is not rendered on the checkout page. On the checkout page, it is discarded by the `has_domestic_transactions_restrictions` function so we do not have the console error anymore.  The only outstanding issue here is, we should probably show the currency requirement pill for the above scenario.
