### ISSUE TITLE
Stripe Refund Webhook not setting order to Refunded

### ISSUE THREAD

**Issue by LiamSarsfieldWPE** [woocommerce/woocommerce-gateway-stripe#3073]
**Describe the bug**
If a merchant attempts to refund a payment via their Stripe dashboard, the order does not change within WP Admin to Refunded after 8.0.0 for specific payment methods.

**To Reproduce**
1. Ensure site has Stripe test mode configured and Stripe's webhook is pointing to the site.
2. Make a successful test payment with a payment method that is not card/Express Checkout (e.g. giropay).
2. Refund the payment via the Stripe dashboard
3. Site successfully receives refund webhook, however does not set the order to Refunded

**Expected behavior**
Order's status is set to Refunded and a note within the order explaining the refunded was processed via the Stripe dashboard

**Example**
[Video example](https://drive.google.com/file/d/1wLdiMKLE0de1J-1NzRUPhKsFZ2hq_Gzg/view)

**Environment (please complete the following information):**
 - WordPress Version: 6.4.3
 - WooCommerce Version: 8.7.0
 - Stripe Plugin Version: 8.2.0
 - Browser: Chrome (Mac)

**Additional context**
When the order is placed in `wp_wc_orders`, the `payment_method` is set to `stripe_eps` (for example).
The webhook handler is only checking for 'stripe' `payment_method` [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/285959e4166e5f66370083e2d2ab27c5f1071d63/includes/class-wc-stripe-webhook-handler.php#L563).
I believe any checks regardingorder's get_payment_method should be changed to if it starts with 'stripe'

**Comment by mattallan** [comment]
Thanks @LiamSarsfieldWPE for the report, I've got a PR up to fix this. See https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3075
