### ISSUE TITLE
Apple Pay doesn't apply coupons

### ISSUE THREAD

**Issue by zandyring** [woocommerce/woocommerce-gateway-stripe#308]
#### Affected ticket(s)

woothemes-zd-598848

#### What I expected

When a customer applies a coupon to their order, I would expect any payment gateway to respect the coupon.

#### What happened instead

When a customer applies a coupon and checks out via Apple Pay, the coupon is not applied. Stripe applies it correctly, however.

This is a screenshot of a STRIPE order ($10 order, $1 coupon = $9 total):
![screen shot 2017-07-10 at 3 00 34 pm](https://user-images.githubusercontent.com/7304712/28034900-9e990238-6580-11e7-9ac3-72cbef9275b8.png)

This is a screenshot of an APPLE PAY order ($10 order, $1 coupon = $10 total):
![screen shot 2017-07-10 at 3 00 41 pm](https://user-images.githubusercontent.com/7304712/28034945-c1f365ac-6580-11e7-83b2-0bc6f8a0b8bb.png)

This is a further issue with the flat rate shipping not being applied to an Apple Pay order:
![screen shot 2017-07-10 at 3 00 49 pm](https://user-images.githubusercontent.com/7304712/28034958-d0f234d4-6580-11e7-9059-8641f0bc4a7c.png)

#### Steps to reproduce the issue

With WooCommerce and Stripe enabled, be sure that you have Apple Pay set up. Create a coupon, and apply the coupon to an order. Check out using Apple Pay. Review the order on the back end and the Order Confirmation screen.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@zandyring  What are you seeing in the Apple Pay payment sheet?

**Comment by roykho** [comment]
This is what I am seeing with shipping and discount applied ![](http://cld.wthms.co/yztSTG+)

**Comment by zandyring** [comment]
@roykho the customer sees the discount applied on the Apple Pay screen, as you do. But then when the order is processed, it doesn't actually apply the coupon.

@yukikatayama is helping me, and here's a screenshot she took to illustrate:
![screen shot 2017-07-10 at 3 47 01 pm](https://user-images.githubusercontent.com/7304712/28036726-2053be48-6587-11e7-904f-de391b3c15af.png)

Then, on the order itself (shipping did correctly apply this time):
![screen shot 2017-07-10 at 3 48 09 pm](https://user-images.githubusercontent.com/7304712/28036763-3de1d5ee-6587-11e7-9ede-052ca0773245.png)

**Comment by roykho** [comment]
@zandyring ok thanks for the screenshots. So just to confirm, this is only affecting coupons and not shipping correct?

**Comment by zandyring** [comment]
@roykho Yep, that's correct. The shipping issue seems to not be real. Just coupons not properly applying.

**Comment by roykho** [comment]
@zandyring ok thanks for confirming. Can you please test again with master and let me know if this fixes it?

**Comment by zandyring** [comment]
@roykho Ok, that does work! The only issue is that the original price at the top is still showing as the discounted price:
![screen shot 2017-07-10 at 4 35 42 pm](https://user-images.githubusercontent.com/7304712/28038756-f2da4714-658d-11e7-81b2-a043efdb5cc4.png)

**Comment by roykho** [comment]
@zandyring not sure I follow 100%. Here is a screenshot of an order place with just Stripe ( not Apple Pay ) and I see this ![](http://cld.wthms.co/rsaMrf+) So in your screenshot its $10 original and with 10% discount I am guessing so it shows $9. Is there something wrong with that calculation?

**Comment by zandyring** [comment]
@roykho No the calculation is correct, you're right. I didn't realize that it showed the discounted price, then the (-$2.00) (or whatever the discount is) underneath that. I had assumed that it would show the full price, the minus price, and then the total at the bottom in all cases.
