### ISSUE TITLE
[Klarna] Render the Klarna payments page in the store locale

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#3087]
**Is your feature request related to a problem? Please describe.**

By default, the Klarna payments page will be rendered in the billing country’s default locale (for example, en_GB for the United Kingdom). This locale could be different from the store's locale. 

As a shopper, I'd expect my whole payment processing flow to use the same locale along the way for a consistent experience.

**Describe the solution you'd like**

Render the Klarna payments page in the store's locale.

**Describe alternatives you've considered**

We could leave the current behavior as is.

**Additional context**
API reference - [Localizing the Klarna payment page](https://docs.stripe.com/payments/klarna/accept-a-payment?web-or-mobile=web&payments-ui-type=direct-api#kpp-preferred-locale)

**Comment by james-allan** [comment]
I've had a brief look at this but have been unable to get the Klarna payment page to be displayed in my preferred locale. 

eg passing these additional args I would expect the payment page to be in German. However it's still presented in English to me. I'm not sure what I'm missing, but I'm going to move on to other higher priority issues but wanted to make this comment in case further clarification is required. 

<table>
<tbody>
  <tr>
    <td><pre>[payment_method_options] =&gt; Array<br>        (<br>            [klarna] =&gt; Array<br>                (<br>                    [preferred_locale] =&gt; de-DE<br>                )<br><br>        )</pre></td>
    <td><img width="300" alt="Screenshot 2024-05-01 at 2 25 12 PM" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/8490476/b5b6c867-44c1-48d9-b638-a8ca5d99ab47"></td>
  </tr>
</tbody>
</table>

**Comment by annemirasol** [comment]
According to Stripe in https://docs.stripe.com/payments/klarna/migrate:

> `payment_method_options[klarna][preferred_locale]` ... [is] validated against the billing details country (for example, fr-FR in the US isn’t a valid combination). 

I tested this as well. `es-US` displays the Klarna page in Spanish, while `fr-FR` is ignored for the billing country `United States`.

Here is the table of supported locales per billing country: https://docs.stripe.com/payments/klarna/accept-a-payment?web-or-mobile=web&payments-ui-type=direct-api#supported-locales-and-currencies
