### ISSUE TITLE
[Affirm] No error shown when payment is abandoned on the block checkout

### ISSUE THREAD

**Issue by wjrosa** [woocommerce/woocommerce-gateway-stripe#3089]
See: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3083#issuecomment-2071553976

**Comment by a-danae** [comment]
This looks like the same behavior described in this other issue, but for Affirm, isn't it? 
https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3060

If so, we could make that issue more generic to cover all BNPLs, and close this one as a duplicate.

**Comment by wjrosa** [comment]
> This looks like the same behavior described in this other issue, but for Affirm, isn't it? #3060
> 
> If so, we could make that issue more generic to cover all BNPLs, and close this one as a duplicate.

Yeah, I agree 👍
