### ISSUE TITLE
[4.0][Gateways]Implement Alipay

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gateway-stripe#309]
For China market.

**Comment by roykho** [comment]
Done via https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0

**Comment by stianmartinsen** [comment]
Does anyone know when 4.0 will be out?

And will the plugin support Alipay for webshops that aren't in China or the US now that Stripe [offers support for Alipay globally](https://stripe.com/blog/hong-kong)?
