### ISSUE TITLE
Unexpected HTML on the shortcode checkout error message when Link is enabled

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#3099]
**Describe the bug**

When Link is enabled, some unexpected HTML is included in the error message for the required email address field. This is only happening on the shortcode checkout.

**To Reproduce**

1. Ensure that the Legacy checkout experience is disabled under the Stripe settings tab, at `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings`
2. Ensure Link is enabled under the Payment Methods tab, at `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=methods`
3. Create a page that contains the shortcode checkout, if you don't have one already
4. As a shopper, add a product to the cart and go to the shortcode checkout page
5. Ensure that the email address field is empty
6. Click on Place Order
7. Notice the error message contains `<button class="stripe-gateway-stripelink-modal-trigger"></button>`

<img width=500 src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/41606954/957507ad-6b9b-475c-8235-3086d0560cf1">

**Expected behavior**
The error message must not contain `<button class="stripe-gateway-stripelink-modal-trigger"></button>`.

**Comment by shameemreza** [comment]
Another report here: 8371467-zen
Thread link: https://wordpress.org/support/topic/woo-checkout-page-prints-error-codes/

**Comment by PayaPets** [comment]
When a fix does come around, will you guys post it here?
