### ISSUE TITLE
Cannot select alipay as payment method using 'new' checkout experience + 404 on support page.

### ISSUE THREAD

**Issue by pjrobertson** [woocommerce/woocommerce-gateway-stripe#3105]
**Describe the bug**
If I enable the 'new' checkout experience, I cannot select Alipay as the payment method. I have confirmed that Alipay is enabled on my acocunt (see screenshots below).

If I click the link '[Enable Alipay in WooCommerce](https://docs.stripe.com/plugins/wordpress#woocommerce)' on the Stripe support site, it leads to a 404 page:

**To Reproduce**
1. Enable the 'new' checkout experience
2. Enable alipay on your account
3. Go to Stripe Settings > Payent Methods and try to add alipay. There is only a link at the bottom that says. '[Get more payment methods](https://dashboard.stripe.com/settings/payments)' - 
4. If I click the link, it says alipay is active, and provides a link on how to set up, but the page leads to a 404

**Expected behavior**
Set up alipay

**Screenshots**
<img width="1116" alt="Screen Region 2024-04-30 at 17 03 01" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/150431/b6563671-f74a-4d2d-8c9d-2d31f87f5c47">
<img width="1053" alt="Screen Region 2024-04-30 at 17 02 51" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/150431/5f7a6d33-79cc-4e2f-a1a5-99f95a528198">

**Environment (please complete the following information):**
Wordpress: 6.5.2
Plugin: 8.2.0
WooCommerce:
Browser: Firefox & Chrome
Caching: Tried disabling, same

**Comment by darryXw** [comment]
same here

**Comment by carolframen** [comment]
Got some other reports on 8427350-zen, 8391457-zen and **[this thread](https://wordpress.org/support/topic/cant-activate-alipay-with-new-checkout-experience/)**. At least some of them are able to see it on test mode, but not live mode.

**Comment by OmarFPG** [comment]
8351460-zen

**Comment by JamesBortolus** [comment]
We are having the same issue. We have enabled Alipay in stripe. 

We can't get it to appear as a payment method option in the WooCommerce > Settings > Payments > Stripe > Payment Methods section. We can only see Alipay if we enable legacy checkout.

**Comment by RiaanKnoetze** [comment]
Related: https://wordpress.org/support/topic/after-changing-the-new-checkout-experience-some-payment-methods-cant-use

**Comment by backlux** [comment]
this should be fixed, as stripe is forcing new checkout. Please update

**Comment by backlux** [comment]
Test mode works because of this , please fix normal mode.

	public function is_capability_active() {
		// Treat all capabilities as active when in test mode.
		$plugin_settings   = WC_Stripe_Helper::get_stripe_settings();
		$test_mode_setting = ! empty( $plugin_settings['testmode'] ) ? $plugin_settings['testmode'] : 'no';

		if ( 'yes' === $test_mode_setting ) {
			return true;
		}

**Comment by daniyalahmadk** [comment]
8782393-zen

**Comment by wjrosa** [comment]
Hello @pjrobertson! In the last few weeks, Stripe made some changes on their side that fixed the issue when trying to use Alipay as a method with the new checkout experience enabled (live/production mode). Can you please confirm if this is working as expected now?

As for the 404 error, it looks like an issue with their website, so I suggest contacting them at https://stripe.com/contact

**Comment by wjrosa** [comment]
I will be closing this issue now, @pjrobertson. Please open it again with additional information in case the problem persists.
