### ISSUE TITLE
[Klarna] Only display it when the presentment currency matches the currency of the customer’s country

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#3118]
**Describe the bug**

For transactions between the EEA, UK, and Switzerland, the presentment currency [must match the currency of the customer’s country](https://docs.stripe.com/payments/klarna#:~:text=Swedish%20business%20can%20present%20in%20EUR%20to%20accept%20Klarna%20from%20a%20buyer%20in%20Germany).

Currently, we display this payment method on the checkout page for all these billing countries, but the presentment currency matches the Stripe account's country, not the customer's.

When this happens, the following error is displayed on the checkout page:

```There was an error processing the payment: The provided PaymentMethod cannot be attached. To reuse a PaymentMethod, you must attach it to a Customer first.```

And this Stripe's response body of this request that fails with a 400:

```
{
  "error": {
    "message": "The provided PaymentMethod cannot be attached. To reuse a PaymentMethod, you must attach it to a Customer first.",
    "request_log_url": "https://dashboard.stripe.com/test/logs/req_xyz",
    "type": "invalid_request_error"
  }
}
```

**To Reproduce**
1. Connect a Stripe account from the UK
2. Select Pound sterling as the store currency
3. Enable Klarna
4. As a shopper, add a product to the page and proceed to checkout
5. Select France as the billing country
6. Notice Klarna continues to be displayed as an available payment method
7. Place the order using Klarna
8. Notice the error message mentioned about is displayed

**Expected behavior**
Klarna must only be displayed on checkout for cross-border payments when the order currency matches the currency of the customer's country.

For example:
- A Swedish business can present Klarna for a buyer in the EEA when the store currency is EUR
- A business in the EEA can present Klarna for a buyer in the UK when the store currency is GBP

**Additional context**
We'll need to update the checks related to [domestic transactions](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/payment-methods/class-wc-stripe-upe-payment-method.php#L237-L246) and to customer's billing country.

**Comment by Mayisha** [comment]
Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3235.
