### ISSUE TITLE
[Wallets] Accept CashApp payments

### ISSUE THREAD

**Issue by wjrosa** [woocommerce/woocommerce-gateway-stripe#3131]
Allow shoppers to pay with [CashApp](https://docs.stripe.com/payments/cash-app-pay).

This payment method _isn't_ available on the Legacy checkout experience.

### Acceptance criteria

- [x] Display this payment method under the Settings page. Scenarios to take into account:
  - [x] When the payment method isn't available for the Stripe account country
  - [x] When the store currency isn't supported by the payment method
  - [x] When the transaction isn't a domestic one - CashApp [limitations details](https://docs.stripe.com/payments/cash-app-pay#get-started)
- [x] Display this payment method to shoppers. It must be displayed on
  - [x] The shortcode checkout
  - [x] The block checkout
  - [x] The pay for order page
- [x] #3141
- [x] Handle denied transactions
  - [x] The shortcode checkout
  - [x] The block checkout
  - [x] The pay for order page
- [x] Handle failed payments
- [x] Handle post-payment events if necessary
- [ ] ~~Handle [method limits](https://docs.stripe.com/payments/cash-app-pay#payment-limits-and-options)~~
    - From the documentation, these limits are handled on the app side so there's nothing we can do from the plugin. While this didn't come up in testing, I suspect it behaves just like failed payments. _edit by: @james-allan_ 
- [x] Handle refunds
  - [x] Partial refunds
  - [x] Full refunds

**Comment by wjrosa** [comment]
Hey @james-allan ! Can we close this issue or do you think there's still something missing for the main Cash App implementation?

**Comment by james-allan** [comment]
Yep, I've been meaning to close this.
