### ISSUE TITLE
SEPA payments fail when using Sources tokens with the Payment Methods API

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-gateway-stripe#3134]
**Describe the bug**

The following flows fail when using a SEPA source with the Payment Methods API (we also have to check the behavior for cards):

- Regular purchase

> There was an error processing the payment: Using a SEPA Debit Source in the `payment_method` field has been deprecated and is no longer a valid integration path. Please migrate your Source objects to PaymentMethods using the Dashboard migration tooling here: https://dashboard.stripe.com/sources-migration

- Purchasing a subscription

> There was an error processing the payment: Using a SEPA Debit Source in the `payment_method` field has been deprecated and is no longer a valid integration path. Please migrate your Source objects to PaymentMethods using the Dashboard migration tooling here: https://dashboard.stripe.com/sources-migration

- Purchasing a subscription with a free trial

> SEPA Debit Sources used as a PaymentMethod are not supported with the Setup Intents API. These Sources have mandate information and thus are already "set up"

- Changing the payment method of a subscription as a shopper

> SEPA Debit Sources used as a PaymentMethod are not supported with the Setup Intents API. These Sources have mandate information and thus are already "set up".

A merchant reported the following error, but I haven't been able to replicate it so far:

> SEPA Debit Sources used as a PaymentMethod have mandate information already stored. You cannot pass the `mandate_data` or `mandate` parameters. Please re-confirm without those parameters.

**To Reproduce**
1. Check out 8.0.1. There's an error in later versions where SEPA payment methods can't be saved on the Legacy experience
2. As a merchant, enable the Legacy experience
3. As a shopper, add a product to the page and go to the checkout page
4. Check off "Save payment method for future purchases"
5. Use a SEPA src_ payment method to complete the purchase. Like AT611904300234573201
6. Checkout the latest Stripe version
7. As a merchant, disable the Legacy experience. This will make requests go through the Payment Methods API
8. As a shopper, add a product to your cart and go to the checkout page
9. Use the SEPA payment methods you saved previously
10. Notice the payment fails, and the following error is displayed:

> There was an error processing the payment: Using a SEPA Debit Source in the `payment_method` field has been deprecated and is no longer a valid integration path. Please migrate your Source objects to PaymentMethods using the Dashboard migration tooling here: https://dashboard.stripe.com/sources-migration

**Expected behavior**

TBD.

a. Don't display src_ payment methods when the Legacy experience is disabled?
- This could affect subscription renewals, which do work with src_
- It wouldn't be a smooth transition for shoppers, who would find all of they payment methods gone once the merchant disabled the Legacy experience. Although the payment methods they see today won't work anyway, so maybe this wouldn't be a problem.

b. Migrate src_ tokens to pm_?
- We'll depend on the merchant to run the migration on their end

**Reports**
- 7886598-zd-a8c
- https://wordpress.org/support/topic/no-sepa-payment-with-new-checkout-experience/
- 8119078-zd-a8c
- 8090629-zd-a8c
- 8130440-zd-a8c
- https://wordpress.org/support/topic/using-a-sepa-debit-source-in-the-payment_method-field-has-been-deprecated/
- 8115012-zd-a8c
- 8049601-zd-a8c
- 8168237-zd-a8c

**Comment by sophiegyo** [comment]
I think we might have a case of this in 8581082-zen too.

I understand the fix is merged in #3241 is merged in and it looks like #3194 is in progress. Is there any kind of workaround for subscription purchases in the meantime?
