### ISSUE TITLE
Copyright notice in plugin header commentar 

### ISSUE THREAD

**Issue by Drivingralle** [woocommerce/woocommerce-gateway-stripe#315]
#### What I expected
I was debugging the plugin for a project and noticed the following line:
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/woocommerce-gateway-stripe.php#L14

As far as I understand the GPL the (c) copyright notice is not allowed:
https://developer.wordpress.org/plugins/the-basics/including-a-software-license/

#### Steps to reproduce the issue
Remove the line and add:
`License:     GPL2`

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
This will be adjusted in next release 4.0.0.
