### ISSUE TITLE
New Update Not working

### ISSUE THREAD

**Issue by atiqrahmanfeni** [woocommerce/woocommerce-gateway-stripe#3151]
Hi,

i have updated 8.3.0 and getting critical error on my site. Below is error details.

```An error of type E_ERROR was caused in line 142 of the file /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php. Error message: Uncaught ArgumentCountError: Too few arguments to function WC_Stripe_UPE_Payment_Gateway::__construct(), 0 passed in /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php on line 103 and exactly 1 expected in /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-upe-payment-gateway.php:142 Stack trace: #0 /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(103): WC_Stripe_UPE_Payment_Gateway->__construct() #1 /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(76): WC_Payment_Gateways->init() #2 /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(49): WC_Payment_Gateways->__construct() #3 /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(1040): WC_Payment_Gateways::instance() #4 /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(212): WooCommerce->payment_gateways() #5 /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(97): WCML_Currencies_Payment_Gateways->get_available_payment_gateways() #6 /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-includes/class-wp-hook.php(324): WCML_Currencies_Payment_Gateways->init_gateways() #7 /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #8 /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #9 /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-settings.php(717): do_action() #10 /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-config.php(98): require_once('/home/1187255.c...') #11 /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-load.php(50): require_once('/home/1187255.c...') #12 /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-admin/admin.php(34): require_once('/home/1187255.c...') #13 /home/1187255.cloudwaysapps.com/kmxazkygvn/public_html/wp-admin/plugins.php(10): require_once('/home/1187255.c...') #14 {main} thrown```

Please solve it. Ihave tried by change theme also same error.

Thank you

**Comment by a-danae** [comment]
Hey @atiq50619 ! Thanks for the report. We're on this.

We see what the problem is based on your stack trace, thanks for that! We're still unable to replicate it on our end, even having [WooCommerce Multilingual ](https://wordpress.org/plugins/woocommerce-multilingual/)enabled with the multicurrency setup.

Would you please confirm whether disabling WooCommerce Multilingual resolves the problem?

Also, would you please provide the steps to replicate this, including any details on the settings used for the WooCommerce Multilingual extension?

**Comment by shameemreza** [comment]
Another report: 8230129-zen
Thread: https://wordpress.org/support/topic/8-3-0-crashes-my-woocommerce-site

**Note:** Several users have reported this issue, but I've been unable to reproduce it locally or on my testing site.

**Comment by a-danae** [comment]
We've created this[ 3.8.1-test](https://github.com/woocommerce/woocommerce-gateway-stripe/releases/tag/8.3.1-test) pre-release in GH.

Would you please confirm if this package solves the problem for the affected stores? @atiq50619, @shameemreza

**Comment by atiqrahmanfeni** [comment]
Hi,
I Installed test version Working Well for me.

Thanks
