### ISSUE TITLE
Nothing happens when I try to make a refund

### ISSUE THREAD

**Issue by tsunaday** [woocommerce/woocommerce-gateway-stripe#3158]
**Describe the bug**
I use Stripe for Woocommerce and either with a manual or automatical refund, nothing happens. There is no event in the order comments. I succeded with refunding in Stripe but cannot make any change in woocommerce

**To Reproduce**
1. Go to Orders
2. Click on Refund
3. Select the quantity of a product I want to refund
4. Check the checkbox for stock
5. Page charges, no error, nothing happens. 

**Expected behavior**
stock change, refund taken into account

<img width="1273" alt="Capture d’écran 2024-05-28 à 11 33 39" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/147451000/8df90950-302e-4405-b301-ac973a58fbe1">
<img width="1119" alt="Capture d’écran 2024-05-28 à 11 33 55" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/147451000/2a058292-ccb4-4d74-9224-9423531137e0">
<img width="823" alt="Capture d’écran 2024-05-28 à 11 34 27" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/147451000/1329b55e-f84d-4949-870a-bfefae74466a">
<img width="1280" alt="Capture d’écran 2024-05-28 à 11 34 30" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/147451000/e51121b7-f79a-4f5b-8348-011960b45333">

**Environment (please complete the following information):**
 - WordPress Version 6.5.3
 - WooCommerce Version 8.9.1
 - Stripe Plugin Version 8.3.0
 - Browser [e.g. chrome, safari] and Version Chrome 116.0.5845.187
 - Any other plugins installed WPML, WCmultishipping, MailChimp, Updraftplus,wp fastest cache, yoast, wordfence...

**Comment by wjrosa** [comment]
Hey @tsunaday! I tried reproducing the issue using our latest extension version without success. Are you still experiencing this bug? Did you connect your Stripe account correctly? Is the "legacy checkout experience" option disabled on your store?

Also, as you are probably aware, when you decide to refund an order manually, you are expected to refund it again on the Stripe dashboard.

**Comment by wjrosa** [comment]
I will be closing this for now. Please, let us know if this still happens to you so we can reopen the issue.
