### ISSUE TITLE
Modify Email Validation Rules In Stripe To Include Non Standard Email IDs

### ISSUE THREAD

**Issue by harishankerr** [woocommerce/woocommerce-gateway-stripe#316]
#### The Issue

Currently, customers with non-standard email id's (like `'my-email-id'@emailprovider.com`- which have apostraphes or other special characters preceding the `@` symbol fail while trying to check out using our Stripe extension. Just to clarify, special characters are allowed in email addresses provided they are located before the `@` symbol. Email addresses like these are common in many parts of the world, like Ireland. More on this here: https://en.wikipedia.org/wiki/Email_address#Local-part

#### Affected ticket(s)

603360-zd-woothemes (where the customer has explained in detail regarding the issue)

#### Steps To Reproduce The Issue

1. In a site with WooCommerce 3.1.1 and Stripe 3.2.2 installed, try checking out using a non standard email id (e.g. `'email-address'@email-provider.com`) - through Stripe.
2. You will notice that the check out simply will not happen, with an error message in the checkout screen. 

#### Some Suggestions

Essentially the troubles here are because, the  [current regular expression for email validation in our extension](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/bd180dec57c40358291dccdcab60c315c13a8f1a/assets/js/stripe-checkout.js#L72) in our Stripe extension does not support the `'` character before the `@` sign in emails. Our current regex goes somewhat like this:  https://github.com/woocommerce/woocommerce-gateway-stripe/blob/bd180dec57c40358291dccdcab60c315c13a8f1a/assets/js/stripe-checkout.js#L72
`var re = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;`

So, currently, only letters between `a-z`, `A-Z`, `0-9`, and some symbols like `_`, `+`, and `-` are the only ones that are supported. However, this prevents a significant percentage of people from making purchases using the WooCommerce Stripe extensions - people who use non-standard email id's that is. e.g. `o'connor@gmail.com`, or `o'quinn@yahoo.com`. 

It would be great if we could expand the regular expression to include more special/ASCII characters. Some of these characters/rules can be seen here: https://en.wikipedia.org/wiki/Email_address#Local-part

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0
