### ISSUE TITLE
Discount & Fees won't be applied to Apple Pay

### ISSUE THREAD

**Issue by furiohlm** [woocommerce/woocommerce-gateway-stripe#3163]
**Describe the bug**
I've been utilizing the "WooCommerce Stripe Payment Gateway" for transactions. However, I've encountered an issue specifically related to Apple Pay usage. It appears that discounts or fees are not being applied when customers opt for Apple Pay. Despite experimenting with custom code solutions, other payment methods seem unaffected, but Apple Pay consistently fails to accept any form of discount or fee adjustment. It only seems to acknowledge coupons. Consequently, when using Apple Pay, the cart total displays without factoring in any applied discounts or fees.

**To Reproduce**
1. Create a discount or fee by custom code( using Woocommerce hooks ).
2. check the Woocommerce checkout page ( it should be applied to the cart )
3. Try to pay in the apple pay ( the discount or fees won't be added to apple pay )

**Expected behavior**
The precise applied discount or fees on the cart should be included in Apple Pay.

Note: Only coupons will be applied to Apple Pay.

**Screenshots**
Order: https://prnt.sc/HhrP3zAGRMwM
Payment Amount in Apple Pay: https://prnt.sc/KxCd06MyZymd

**Environment (please complete the following information):**
 - WordPress Version: 6.5.3
 - WooCommerce Version: 8.9.1
 - Stripe Plugin Version: 8.3.0
 - Browser: Safari  17.4.1 - iPhone
 - Any other plugins installed: Elementor, Elementor Pro

**Comment by nielslange** [comment]
Closing this issue in benefit of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1146.
