### ISSUE TITLE
Remove the text OR for express checkout buttons in cart and checkout page if the browser doesn't support Apple Pay

### ISSUE THREAD

**Issue by tsetend** [woocommerce/woocommerce-gateway-stripe#3172]
**Describe the bug**
There is the text `OR` in the bottom when the browser doesn't have Apple Pay configured in the cart and checkout page.

![screenshot](https://d.pr/i/QsVeAa+) **Image Link:** https://d.pr/i/QsVeAa

**To Reproduce**
1. Make sure you have express checkout enabled in Stripe settings
2. Disable Apple Pay if you have configured it or use a browser that doesn't have Apple Pay configured like Chrome
3. Add a product in cart and go to the cart or the checkout page
4. You will notice there is no buttons but `OR` is still shown

**Expected behavior**
It would be great to disable or hide `OR` if there is no express checkout option in the browser

**Comment by annemirasol** [comment]
Closing, as I am no longer able to reproduce with both PRB and ECE.
