### ISSUE TITLE
Change button text 'Activate stripe account' when other payment methods require activation in the Stripe dashboard. 

### ISSUE THREAD

**Issue by m0untaingoat** [woocommerce/woocommerce-gateway-stripe#3188]
**Describe the bug**

- When other payment methods require activation in the Stripe dashboard, a notice appears that reads 'Payment methods require activation in your Stripe dashboard. Activate stripe account.'
- The button's text `Activate stripe account` has caused some confusion among merchants thinking they still need to activate their Stripe accounts. 

**To Reproduce**
1. Install WooCommerce
2. Install and set up Stripe gateway
3. Navigate to WooCommerce > Settings > Payments > Stripe
4. See notice

**Expected behavior**
- The text on `line 62` of `client/settings/account-activation-notice/index.js` reads `Activate stripe account`,
- Consider changing this text to read something along the lines of `Activate other payment methods`

**Screenshots**

![Screen Shot on 2024-06-07 at 06-47-31](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/151637014/e9285729-ee06-4dd4-b2dd-792780f19788)

**Environment (please complete the following information):**
 - WordPress Version: 6.5.3
 - WooCommerce Version 8.9.1
 - Stripe Plugin Version 8.3.1

**Comment by m0untaingoat** [comment]
8260414-zd-a8c
8264437-zd-a8c
8167387-zd-a8c
7919773-zd-a8c

https://wordpress.org/support/topic/payment-methods-require-activation-in-your-stripe-dashboard/

**Comment by nicholasjeberlin** [comment]
8442583-zen

**Comment by m0untaingoat** [comment]
8475756-zen
