### ISSUE TITLE
[HC] Logs report outdated Stripe API version by default?

### ISSUE THREAD

**Issue by anastas10s-afk** [woocommerce/woocommerce-gateway-stripe#3191]
**Describe the bug**
It appears that the reporting of Stripe API version within the plugin's logs is not correct, as it defaults to `Stripe Plugin API Version: 2019-09-09`.

**To Reproduce**
1. Have the latest version of the Stripe plugin installed
2. Enable logging
3. Make sure the latest, or a recent, Stripe API is in use when setting up webhooks and keys for connecting the plugin
4. See the logs reporting `Stripe Plugin API Version: 2019-09-09` — despite the actual Stripe API version in use.

**Expected behavior**
The correct date of the Stripe API in use to be reported.

**Screenshots**

<img width="252" alt="Screenshot 2024-06-09 at 12 45 18" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/73900974/94103607-a7cc-4fbe-bc9f-20d0281d5008">

<img width="759" alt="Screenshot 2024-06-09 at 12 43 33" src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/73900974/68db4f98-aed0-4e50-b97c-6e80c37a279f">

**Environment (please complete the following information):**
 - WordPress Version → 6.5.4
 - WooCommerce Version → 8.9.2
 - Stripe Plugin Version → 8.3.1
 - Browser [e.g. chrome, safari] and Version → Chrome Version 125.0.6422.142 (Official Build) (arm64)

**Additional context**
For further context, see here:
- https://wordpress.org/support/topic/payment-pending-but-payment-succeeded/#post-17810839
- 8287133-zen

**Comment by Mayisha** [comment]
Hi @anastas10s-afk :wave: 

> See the logs reporting Stripe Plugin API Version: 2019-09-09 — despite the actual Stripe API version in use.

The log is correct as the intention is to log the API version used on the plugin side (the version used to make requests from the Stripe plugin to the Stripe platform). We are not logging the API version of the client's Stripe dashboard.

**Comment by anastas10s-afk** [comment]
Hi @Mayisha 👋 
Noted, thank you for clarifying. Marking as closed then. 🙂
