### ISSUE TITLE
Appending description with test mode instruction in constructor may result in unexpected REST API response

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce-gateway-stripe#320]
#### Affected ticket(s)

N/A

Found this while testing on REST-related thing.

See this [lines](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/23d8d4baaa60881d3a94fc5fd6b1ddf0efd4e201/includes/class-wc-gateway-stripe.php#L175-L178).

#### What I expected

The description should be returned as it's when requested via API.

#### What happened instead

The description is appended with test mode instruction. In some cases, when updating the payment gateway settings via REST API it might get appended again and again.

Ideally, this test mode instruction can be appended into the description via filter when the payment gateway description is rendered in the checkout page.

/cc @allendav 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Close via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/d3e5cc251a8bd0a99e477ae31720a2ad0e4de57b
