### ISSUE TITLE
Getting a lot of blocked payments from customer due to high risk[CVC check Unavailable Street check Unavailable Zip check Unavailable]

### ISSUE THREAD

**Issue by SajidRah71** [woocommerce/woocommerce-gateway-stripe#3214]
**Describe the bug**
When customers pay via link or apple pay or google pay everything works fine but as soon as they pay using card, their payment gets flagged as highest risks and it shows
CVC check
Unavailable
Street check
Unavailable
Zip check
Unavailable

it's not saying that the values are wrong(they aren't i have confirmed with customers) but rather that the checking for these values are unavailable. I don't know what's causing this issue.

**Expected behavior**
I just want the payments to be seemless. idk what's the issue. is it with my website or the plugin or the stripe itself.
**Screenshots**
![image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/140899788/3bd37c9a-dab7-458a-9b60-cee169bbbedc)

**Environment (please complete the following information):**
 - WordPress Version 6.5.4 
 - WooCommerce Version 9.0.0
 - Stripe Plugin Version 8.4.0
 - Browser any;
 - Any other plugins installed

Please help with the issue

**Comment by aheckler** [comment]
If there's not a confirmed bug in the code itself yet, this issue will get addressed quicker as a support request. Please [go here](https://woocommerce.com/my-account/create-a-ticket?select=18627) to contact our Happiness team, who can help you troubleshoot the problem and file a bug if indeed this is one. :) Thanks!
