### ISSUE TITLE
"Missing required param: mandate_data" error prevents adding card payment method to My Account page while Link is enabled

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce-gateway-stripe#3224]
**Describe the bug**
Adding a payment method on My Account shows an error: "Missing required param: mandate_data"

**To Reproduce**
1. Go to My Account -> Payment Methods
2. Try to add a new payment method
3. See the error comes up and the method is not added.

**Expected behavior**
The method should be added and saved.

**Screenshots**

<img src="https://github.com/woocommerce/woocommerce-gateway-stripe/assets/5656702/bd4f80c9-bb93-47ff-89d1-49d4cc9d7741" width="700" />

**Environment (please complete the following information):**
 - WordPress Version: 6.6
 - WooCommerce Version: 9.1
 - Stripe Plugin Version 8.4
 - Browser [e.g. chrome, safari] and Version: Edge
 - Any other plugins installed: None besides WordPress Beta tester and WC Core.

**Comment by aheckler** [comment]
This error is not happening on my test site with the steps you posted. I suspect there may be something about your Stripe configuration that's causing this. Given that it's not a confirmed bug in our code, your best way forward is to [reach out to our support staff](https://woocommerce.com/my-account/create-a-ticket?select=18627) and have them dig into the issue. Thanks!

**Comment by csmcneill** [comment]
I can reproduce this on my test site. The missing step is that Link needs to be enabled.

1. Enable Link by Stripe
2. Go to My Account -> Payment Methods
3. Try to add a new payment method
4. See the error comes up and the method is not added.

Reopening and changing the title.

**Comment by opr** [comment]
Thanks @csmcneill ! I had set it up on my other site (which didn't have link enabled) and wasn't able to reproduce, so chalked it up to something being wrong with my setup. Thanks for looking into this further 🙇🏼
