### ISSUE TITLE
[4.0] Capitalisation of payment method names

### ISSUE THREAD

**Issue by thorsten-stripe** [woocommerce/woocommerce-gateway-stripe#323]
@roykho Some of the payment methods have special spelling, can you change the following:

* SOFORT (all uppercase)
* iDEAL (lowercase i, rest uppercase)
* SEPA Direct Debit ( can we put "Lastschrift" in brackets behind it for German installations? Or replace Direct Debit with Lastschrift for German installations?) 

You can see the recommended spelling for all of them in this Guide: https://stripe.com/payments/payment-methods-guide

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Yes I've made these translatable thanks!
