### ISSUE TITLE
[4.0] Additional Information in payment method settings

### ISSUE THREAD

**Issue by thorsten-stripe** [woocommerce/woocommerce-gateway-stripe#324]
@roykho can we add additional information each setting section, specifically:

* RELEVANT PAYER GEOGRAPHY (can you take this from each section of our guide[0])
* Link to the relevant method in the guide[0], e.g. https://stripe.com/payments/payment-methods-guide#ideal for iDEAL
* Link to activation page in the Stripe Dashboard[1]

If you don't get around to this I can take a pass at it next weekend

[0] https://stripe.com/payments/payment-methods-guide
[1] https://dashboard.stripe.com/account/payments/settings
-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
This is done.
