### ISSUE TITLE
Express checkout not sending all address fields to shipping

### ISSUE THREAD

**Issue by icepicknz** [woocommerce/woocommerce-gateway-stripe#3251]
**Describe the bug**
If I complete standard checkout procedure such as add to cart, view cart, checkout, enter address, the shipping plugin receives all the data required to provide shipping costs, these being:
$order->get_shipping_address_1()
$order->get_shipping_address_2()
$order->get_shipping_city()
$order->get_shipping_state()
get_shipping_country()
get_shipping_postcode()

When using express checkout, in my case Apple Pay, I get "Update Postal Address" in "Ship to" field.
Debug of the aforementioned variables shows get_shipping_address_1 and get_shipping_address_2 are missing values, only  get_shipping_city, get_shipping_state, get_shipping_country and get_shipping_postcode are provided.

I have zone setup correctly for shipping and a catch all "rest of the world" with the same settings.

This appears to be an issue for New Zealand that doesn't have "States" but rather "Regions".

If I try to an address in Australia, it allows me to get to a chargeable state, but rather than sending the "Ship To" address its sending the "Billing Address" from the card. This was verified in the stripe event and actually failed the WooCommerce transaction because of the state/region field.

**To Reproduce**
1. Go to product
2. Click on Apple Pay express checkout
3. Enter a New Zealand address like "40 Tia Street, Waikato, Atiamuri, 3078"

**Expected behavior**
The "Ship to" address to be passed to the order from Apple Pay rather than Billing Address" associated with the card.

**Screenshots**

**Environment (please complete the following information):**
 - WordPress Version: 6.5.5
 - WooCommerce Version: 9.0.2
 - Stripe Plugin Version: 8.4.0
 - Browser Safari
 - Any other plugins installed
WooCommerce New Zealand Post

**Additional context**

**Comment by wjrosa** [comment]
Hey @icepicknz! Would you mind sharing a screenshot of your issue? I did some testing here, following the steps you provided, but I don't see the "Ship to" field you mentioned.

**Comment by icepicknz** [comment]
I found a workaround with the following code snippet, this resolved the issue for "New Zealand" which doesnt have "state" as a shipping field

```
function wc_remove_state_field( $fields ) {
      unset( $fields['state'] );
      return $fields;
}

add_filter( 'woocommerce_default_address_fields', 'wc_remove_state_field' );

```

Let me know if you find a fix and if you want me to test it

**Comment by wjrosa** [comment]
Thanks for sharing the snippet, @icepicknz ! Your issue might be related to an older version of WooCommerce. Here's what I see when checking out using the latest one:
![Image](https://github.com/user-attachments/assets/13d71361-080a-4749-a5e3-a2a82b4790d5)

We already have regions instead of states when selecting New Zealand. That being said, I will be closing this for now. If you try the latest version and still have issues, let us know here so we can reopen the issue.
