### ISSUE TITLE
"Use a New Payment Method" Button Incorrectly Appears During Checkout in WooCommerce Stripe Gateway Plugin

### ISSUE THREAD

**Issue by shohanhossainnab** [woocommerce/woocommerce-gateway-stripe#3252]
**Describe the bug**
The "Use a new payment method" radio button incorrectly appears during the checkout process under specific conditions, causing order failures when not selected by the customer.

**To Reproduce**
1. Ensure "New Checkout Experience" is enabled.
2. Create a free product with 0 price, but make sure shipping is enabled
3. Create two shipping zones: 1. With free shipping(Should be your default address so that the checkout page has that selected automatically), 2. With a shipping fee (This is the one we will select on the checkout page to trigger the bug)
4. Ensure the customer is not logged in.
5. Add the free product to the car
6. Go to the checkout page (cart total shows $0.00).
7. Check the behavior with address the address where free shipping is enabled.
8. Now, change the address to match the paid shipping zone.
9. Cart total will update with a $XX charge
10. Observe the "Use a new payment method" radio button appearing next to the credit card block

**Expected behavior**
The "Use a new payment method" radio button should only appear when "Enable payment methods via saved card" is enabled and the customer is logged in with an existing saved card.

**Screenshots**
![J2rFm1.png](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/73883014/53b9132f-74d1-4c37-99b8-c9e2675f2df8)

**Environment (please complete the following information):**
 - WordPress Version 6.5.5
 - WooCommerce Version 9.0.2
 - Stripe Plugin Version 8.4.0
 - Browser [e.g. chrome, safari] and Version Can be reproduced in any browser and version
 - Any other plugins installed Tested with everything disabled.

**Additional context**
Initial report 8367652-zen

**Comment by ryanr14** [comment]
I know this may be an unlikely edge case, but I wanted to check in for our merchant. Especially since there hasn't been a human review on this so far that I can see. :)

I added the bug label.
