### ISSUE TITLE
Create Stripe Marketplace App

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#3254]
What's a Stripe Marketplace App? and why do we need one?

![Image](https://github.com/woocommerce/woocommerce-gateway-stripe/assets/407542/9288ffb4-9c86-41b9-865c-b6174dbbc373)
Source: https://docs.stripe.com/stripe-apps

We need to create a Stripe Marketplace App to add support the OAuth 2.0 account connection flow.

Stripe OAuth 2.0 App guide:
https://docs.stripe.com/stripe-apps/api-authentication/oauth

**Comment by james-allan** [comment]
@diegocurbelo we're good to close this one now right? I'm going to close it, but please reopen if that's incorrect. :)
