### ISSUE TITLE
Address QIT Security test errors

### ISSUE THREAD

**Issue by vikrampm1** [woocommerce/woocommerce-gateway-stripe#3255]
As identified in the [Phase 1 assessment](https://10upwoo.wordpress.com/2024/07/01/woocommerce-extension-assessment-woocommerce-stripe-payment-gateway/), Woo QIT is not being checked or enforced on this extension. However, when the QIT Activation tests are run on the develop branch manually, the tests [fail](https://qit.woo.com/?qit_results=4621964.Wii3vfqyWhFGWE23aOq3FUzFNydtYaYeHZEaSCR0OdMkFgoum1QtGt7YNNEwXDrA) with 17 File Errors. 

The goal of this task is to add Woo QIT as a GitHub Action to check security tests on PRs, and then to resolve any errors to ensure the test passes on the develop branch.

**Comment by qasumitbagthariya** [comment]
QA Update ✅
---
working as expected and I've added a Detail comment [here](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3268#issuecomment-2259919888).
