### ISSUE TITLE
[4.0] Associate single use source charge with customer if logged in

### ISSUE THREAD

**Issue by thorsten-stripe** [woocommerce/woocommerce-gateway-stripe#326]
[Nice to have] A single use source can be associated with a customer object at the time of charging without adding it to the customer's list of sources: https://stripe.com/docs/sources/customers#single-use-sources

This allows for the charge to be referenced with the customer in the Stripe Dashboard
-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by thorsten-stripe** [comment]
@roykho maybe even go as far as creating a customer object in Stripe (if not guest checkout) even if a single_use method was selected. That way the payment would be associated with a customer object in the Stripe Dashboard. Wdyt?

**Comment by roykho** [comment]
@thorsten-stripe yeah we could do that.

**Comment by roykho** [comment]
They have to either already have an account with stripe customer id in the meta or opted to save account and/or if new customer, have opted to "create account"

**Comment by thorsten-stripe** [comment]
Yes the stripe customer object gets created and is also referenced in the `wp_usermeta` table, but it not submitted in the charge request for the single_use source.

**Comment by roykho** [comment]
Perhaps its 3d secure thats why. Try this CC # 378282246310005

**Comment by thorsten-stripe** [comment]
378282246310005 is an Amex test card and therefore reusable. I'm trying with Bancontact

**Comment by roykho** [comment]
This is working but just not for redirect payments

**Comment by roykho** [comment]
Redirect payment works as well now. Please try latest 4.0.0 branch.

**Comment by thorsten-stripe** [comment]
Yes, works like a charm, thank you :)
