### ISSUE TITLE
[4.0] Show descriptive error message if payment method isn't activated

### ISSUE THREAD

**Issue by thorsten-stripe** [woocommerce/woocommerce-gateway-stripe#327]
We don't yet have a way to retrieve through the API which payment methods have been activated, but I was wondering if we could add a descriptive error message on the checkout page if a payment method hasn't been activated in the Dashboard.

E.g. for new Stripe account it currently simply returns

* SEPA Direct Debit: "Could not find payment information.": https://www.dropbox.com/s/zqtdfe2x88vb2hn/Screenshot%202017-08-02%2023.19.36.png?dl=0

Or do you think showing a generic reference to https://dashboard.stripe.com/account/payments/settings in the payment method setting is enough?

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Unless there is a way to distinguish that exact message because I believe that message is returned in other cases too. Perhaps a source that was once there but since been deleted..etc. If that is the case there is no real way to know.

**Comment by thorsten-stripe** [comment]
Let's stick with the "Must be activated from your Stripe Dashboard Settings here" message in the settings for now. I will update this issue once we have a way to programmatically retrieve the list of activated and available but inactive payment methods.
