### ISSUE TITLE
The duplicate "complete" order notes are causing duplicate tickets.

### ISSUE THREAD

**Issue by dmezaromero** [woocommerce/woocommerce-gateway-stripe#3273]
**Describe the bug**
My problem is that I am seeing duplicate order notes, this is affecting the plugin called FooEvents as it is creating a ticket for each note that says complete. In a single day I have been able to find over 100 orders with this problem. 

The plugin developer say: "...that the duplicate tickets were caused by having your payment gateway complete the order twice at the same time."

**Expected behavior**

**Screenshots**
https://ibb.co/Z22k51T

**Environment (please complete the following information):**
 - WordPress Version  6.5.5
 - WooCommerce Version 8.9.1
 - Stripe Plugin Version 8.4.0
 - Browser [e.g. chrome, safari] and Version
 - Any other plugins installed 
 
FooEvents for WooCommerce |   | by FooEvents – 1.19.22
FooEvents Bookings |   | by FooEvents – 1.7.10
FooEvents Multi-Day |   | by FooEvents – 1.7.4
FooEvents PDF Tickets |   | by FooEvents – 1.10.2

**Additional context**
<img width="271" alt="Screenshot 2024-07-12 at 11 27 43 AM" src="https://github.com/user-attachments/assets/43ca04fb-3599-4261-b395-aa47a6274714">

**Comment by aheckler** [comment]
Potentially related?

- https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2331
- https://github.com/woocommerce/woocommerce-gateway-stripe/issues/2463

**Comment by AlexGThess** [comment]
same issue here....two emails for every status of stripe payments... :(

**Comment by OmarFPG** [comment]
8533089-zen, possibly related, though the charge_id was different here. I'm asking the merchant for more details and enabling debug mode in Stripe to learn more when new orders come in.

**Comment by aureliusm** [comment]
I have exactly the same issue. Two payment charges for the same order. It is very annoying - hopefully gets fixed soon.

**Comment by WCSolution** [comment]
I have the same issue... Please fix it ASAP

**Comment by a-danae** [comment]
Closing this as a duplicate of the following issues
- #2463
- #2331
- #2536

Which are grouped under the Epic 
- #3327 

Please subscribe to the Epic notifications to stay updated with the progress around this problem.
