### ISSUE TITLE
_stripe_net and _stripe_fee missing on Subscriptions renewal

### ISSUE THREAD

**Issue by danieleperilli** [woocommerce/woocommerce-gateway-stripe#3274]
**Describe the bug**
After upgrading to version 8.5.1, the Stripe fee and Stripe net are no longer saved in the orders meta.
This happens only with subscriptions renewals (using WooSubscriptions), not regular orders.
Our custom plugins use that information to integrate and create Journal Entries on QuickBooks, so this is very important for us.

Please refer to the same issue reported here: https://wordpress.org/support/topic/no-longer-shows-stripe-fee-and-payout/

**Comment by aheckler** [comment]
I tested this just now and can confirm there is a bug. Interestingly, I see duplicate meta on the _initial_ subscription order:

![Screenshot taken on 2024-07-15 at 11 41 39 UTC@2x](https://github.com/user-attachments/assets/11747c6b-ad90-41f2-a451-e025f8ed3aa1)

That meta is missing from the renewal:

![Screenshot taken on 2024-07-15 at 11 43 08 UTC@2x](https://github.com/user-attachments/assets/b0b6172b-8878-453d-9dfc-3638efc35115)

**Comment by OmarFPG** [comment]
8472579-zd

**Comment by james-allan** [comment]
It looks like this could be related to the Stripe API version bump included in 8.5.0. 

After making a subscription charge, we use to receive from Stripe a response that included a `balance_transaction`. That balance transaction is what we used to process the fee data.

Stripe API version `2019-09-09` response includes the charge object with a balance transaction ID directly: 

<img width="399" alt="Screenshot 2024-07-17 at 1 03 15 PM" src="https://github.com/user-attachments/assets/ad5d1985-8f47-48c5-b6bf-b8bce0ecba26">

That's no longer the case though. In the `2024-06-20` version, the `charges` arg doesn't exist, we have a `latest_charge` but when you fetch the charge, the balance transaction is empty. 

<img width="318" alt="Screenshot 2024-07-17 at 1 05 14 PM" src="https://github.com/user-attachments/assets/66af0827-a172-4ff4-a0b8-503ffea2a98b">
<img width="287" alt="Screenshot 2024-07-17 at 1 07 01 PM" src="https://github.com/user-attachments/assets/721aa109-a8f0-47ad-a3be-a6a6ea93b1be">

What I haven't yet worked out is why the balance transaction is missing when processing subscription payments, but aren't missing when you process payments on the front end. 🤔

**Comment by james-allan** [comment]
Just following up, I've confirmed it's definitely related to the api version change. I switched out the API version used when `create_and_confirm_intent_for_off_session()` is called and that resolved it. 

I'd still like to look at what could be causing the difference between checkout payments and subscription payments. All I have been able to tell so far, is that Stripe updates the charge with the balance transaction after it has succeeded so there's a short delay (3ms).  

<img width="1056" alt="Screenshot 2024-07-17 at 3 52 36 PM" src="https://github.com/user-attachments/assets/02ed3ad6-09e4-403d-b510-fcf8cd47a76b">

The only potential fix that comes to mind is listening to that `charge.updated` webhook or scheduling an async job to go update the order fee from the balance information shortly after the transaction has been processed.

**Comment by james-allan** [comment]
> I'd still like to look at what could be causing the difference between checkout payments and subscription payments.

I think I found what the difference is and what will fix it. Subscription payments don't have the `capture_method` set to `automatic`. I'll submit a PR later tonight.

**Comment by james-allan** [comment]
FWIW this is the relevant change to the API: 

<p align="center">
<img width="857" alt="Screenshot 2024-07-17 at 6 17 18 PM" src="https://github.com/user-attachments/assets/be3c63aa-3194-4f63-8727-4b72101eccb8">
</br><small>Ref: <a href="https://docs.stripe.com/upgrades#2024-04-10">https://docs.stripe.com/upgrades#2024-04-10</a></small>
</p> 

In the `2024-04-10` version they changed the default payment intent `capture_method` to async so we don't get charge information immediately. As I mentioned above changing it to automatic will cause the payment to be captured as soon as it is raised and we will receive charge information.

**Comment by chouseal** [comment]
**It's not just with subscription payments.** No orders since updating to 8.5.1 have included the Stripe fees in the admin order details, and I'm seeing this consistently across several sites on different servers.

Some of my clients use this fee information in their accounting, so it's important.
