### ISSUE TITLE
Issue related to return_url?

### ISSUE THREAD

**Issue by dcx15** [woocommerce/woocommerce-gateway-stripe#3275]
Since updating to version 8.5.1, I received this email from Stripe:

> We noticed that your livemode Stripe integration is experiencing payment failures because you’re not providing a return_url in your SetupIntent. The return_url is where your customer is directed after they complete their payment, and is required at SetupIntent confirmation. 
> 
> To prevent future payment failures, include a return_url when confirming the payment. To learn more about how to include a return URL, visit our docs.

https://docs.stripe.com/upgrades/manage-payment-methods

**Comment by aheckler** [comment]
Can you provide some more detailed steps on how to replicate this please? Is this happening for all payments, or just some? Are you seeing a related error [in the Stripe plugin logs](https://woocommerce.com/document/stripe/setup-and-configuration/settings-guide/#advanced-settings), or in the Stripe dashboard itself, or both?

**Comment by leogermani** [comment]
Confirmed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3285 and fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3285
