### ISSUE TITLE
[4.0] Error message for invalid currency

### ISSUE THREAD

**Issue by thorsten-stripe** [woocommerce/woocommerce-gateway-stripe#328]
The payment methods are restricted to certain currencies. E.g. many of the European payment methods only support EUR, and Bitcoin currently only supports USD: https://www.dropbox.com/s/4pnqd1uhcgg8sui/Screenshot%202017-08-02%2023.51.54.png?dl=0

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Done.
