### ISSUE TITLE
[4.0] Specific handling of failed sources 

### ISSUE THREAD

**Issue by thorsten-stripe** [woocommerce/woocommerce-gateway-stripe#329]
@roykho would it be possible to specifically handle failed sources in both the redirect[0] and the webhook[1] handlers?

Ideally after the redirect, if the source status is failed we'd want to show an error message and ask the customer to start over with the checkout but with the same cart session?

In the webhook handler we'd probably want to mark the order as failed, wdyt? 

[0] https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.0.0/includes/class-wc-stripe-order-handler.php#L81-L83
[1] https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.0.0/includes/class-wc-stripe-webhook-handler.php#L373-L376

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Can you please give me a test example? Because currently it already does handle failed payments. If the charge fails during checkout, customer is presented with an error and they stay on the checkout page.

**Comment by thorsten-stripe** [comment]
@roykho it works well for cards that are getting declined, but not for redirect sources that get canceled by the customer within the redirect, see[0].

After the redirect could you check if the source's status is `failed` OR `canceled` and in that case return the customer back to to the check out view to try to pay again?

[0] https://drive.google.com/file/d/0B0coCoIHPYOWYXdma2thSkt4cFk/view?usp=sharing
