### ISSUE TITLE
Missing Payment Method: Twint

### ISSUE THREAD

**Issue by masteradhoc** [woocommerce/woocommerce-gateway-stripe#3297]
**Is your feature request related to a problem? Please describe.**
Hi there
Based on this information: https://woocommerce.com/document/stripe/setup-and-configuration/additional-payment-methods/#which-apms even if twint payment method is activated inside stripe with the plugin the payment method is not shown on checkout.

**Describe the solution you'd like**
Allow Twint to be used as payment method within the stripe plugin. As everything is setup inside stripe as a user i expect it to be also available in the official plugin for woocommerce.

**Additional context**
In the meantime i would be nice if you could make this more clear in the plugin that this method is active in stripe but not yet supported to be used.

**Comment by aheckler** [comment]
This is more of a feature request, so my suggestion would be to vote for it here:

https://woocommerce.com/feature-request/accept-twint-as-a-payment-method-in-the-woocommerce-stripe-payment-gateway/

I'm going to close this issue as this is not a bug really.
