### ISSUE TITLE
Merchant Message Visible on Checkout Page

### ISSUE THREAD

**Issue by julinedossantos** [woocommerce/woocommerce-gateway-stripe#3305]
**Describe the bug**
On the checkout page, a message that says "let your customers pay without leaving the store" appears in the credit card payment section. This message is intended for merchants and should not be visible to customers.

**To Reproduce**

1. Go to the checkout page with the new checkout experience enabled.
2. Ensure the Stripe credit card payment method is active.
3. Use a default theme.
4. See the message "let your customers pay without leaving the store" in the credit card payment section.

**Expected behavior**
The message intended for merchants should not be displayed to customers on the checkout page.

**Screenshots**
<img width="1198" alt="image" src="https://github.com/user-attachments/assets/32826585-4012-45dd-9a02-9403049397fc">

**Environment (please complete the following information):**
WordPress Version: 6.5.5
WooCommerce Version: 9.1.2
Stripe Plugin Version: 8.5.1
Browser: Chrome

**Comment by james-allan** [comment]
Thanks for filing the issue @julinedossantos. 

This was introduced in v8.5.0 via https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3176. 

In that PR payment method descriptions are customizable and are now included the payment method's description on the front end. 

There's another issue (https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3272) that has been filed for this too so I'll close this as a duplicate.
