### ISSUE TITLE
[HC] - Disabling the CC option makes Stripe APMs show up first, not respecting the order set in the overall WooCommerce Payment settings

### ISSUE THREAD

**Issue by OmarFPG** [woocommerce/woocommerce-gateway-stripe#3308]
**Describe the bug**
Disabling the credit card option in Stripe and keeping Additional Payment Methods makes the Stripe APMs show up first on the checkout page, not respecting the order respective to other payment methods set in the WooCommerce payment settings.

This happens with either Legacy or UPE.

Sidenote: with Legacy the Stripe payment method shows as disabled in the WooCommerce payment options, but it still shows the APMs in the checkout.

**To Reproduce**
Enable multiple payment methods in WooCommerce, it can be the core payment gateways  + Stripe.
Enable a few APMs in Stripe, and disable CC options.
Rearrange your WooCommerce Payment methods and set Stripe anywhere else but first.

**Expected behavior**
The payment options at checkout should show in the order as defined.

**Actual behavior**
Stripe APMs show first, then the other payment methods.
If I reenable the CC options then the full order is respected.

**Screenshots**
![image](https://github.com/user-attachments/assets/1619c3e3-d6a2-4aad-a3b1-d5d521427b59)
![image](https://github.com/user-attachments/assets/2914be57-2c69-4302-a6ae-c4efed25d35e)
![image](https://github.com/user-attachments/assets/0c56c5f0-5da7-4096-80a7-85d5814703d0)

**Environment (please complete the following information):**
<details><summary>Details</summary>
<p>
### WordPress Environment ###

WordPress address (URL): https://happinesscontractor.wpcomstaging.com
Site address (URL): https://happinesscontractor.wpcomstaging.com
WC Version: 9.1.2
Legacy REST API Package Version: The Legacy REST API plugin is not installed on this site.
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.7.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 10.6.15-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 9.1.2
WC Database Prefix: wp_
Total Database Size: 8.46MB
Database Data Size: 5.35MB
Database Index Size: 3.11MB
wp_woocommerce_sessions: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.33MB + Index: 0.23MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jetpack_sync_queue: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.09MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.34MB + Index: 0.19MB + Engine InnoDB
wp_posts: Data: 0.50MB + Index: 0.06MB + Engine InnoDB
wp_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 46
customize_changeset: 12
custom_css: 3
et_body_layout: 1
et_template: 2
jetpack_migration: 2
jp_img_sitemap: 7
jp_sitemap: 7
jp_sitemap_master: 7
jp_vid_sitemap: 7
nav_menu_item: 1
page: 18
post: 3
product: 39
product_variation: 23
revision: 44
shop_coupon: 7
shop_order_placehold: 11
wp_block: 1
wp_global_styles: 8
wp_navigation: 1
wp_template_part: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3.3
Jetpack: by Automattic – 13.7-a.3
WooCommerce Stripe Gateway: by WooCommerce – 8.5.2
WooCommerce: by Automattic – 9.1.2

### Inactive Plugins (27) ###

AutomateWoo: by WooCommerce – 6.0.27 (update to version 6.0.29 is available)
Classic Editor: by WordPress Contributors – 1.6.4
Code Snippets: by Code Snippets Pro – 3.6.5.1
Crowdsignal Forms: by Automattic – 1.7.2
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.1.1

Facebook for WooCommerce: by Facebook – 3.2.6
Google Listings and Ads: by WooCommerce – 2.7.6
Gutenberg: by Gutenberg Team – 18.8.0
JSM Show Post Metadata: by JS Morisset – 4.3.0
Layout Grid: by Automattic – 1.8.4
Page Optimize: by Automattic – 0.5.5
Printful Integration for WooCommerce: by Printful – 2.2.10
Rank Math SEO: by Rank Math – 1.0.223
Say What?: by Ademti Software – 2.2.3
Site Kit by Google: by Google – 1.131.0
String Locator: by InstaWP – 2.6.5
WooCommerce Legacy REST API: by WooCommerce – 1.0.4
WooCommerce PayPal Payments: by WooCommerce – 2.8.2
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.71
WooCommerce Shipping & Tax: by WooCommerce – 2.6.2
WooCommerce Square: by WooCommerce – 4.7.1
WooCommerce Subscriptions: by WooCommerce – 6.4.1 (update to version 6.5.0 is available)
WooPayments: by WooCommerce – 7.9.2
WordPress.com Editing Toolkit: by Automattic – 4.28277
WPC Composite Products for WooCommerce: by WPClever – 7.3.4
WPIDE - File Manager & Code Editor: by XplodedThemes – 3.4.9
Yoast SEO: by Team Yoast – 23.1

### Dropin Plugins () ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

wpcomsh-loader.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 1 MB

### WC Pages ###

Shop base: #68 - /shop/
Cart: #69 - /cart/ -  Contains the [woocommerce_cart] shortcode
Checkout: #70 - /checkout/ -  Contains the [woocommerce_checkout] shortcode
My account: #71 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 4.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: experimental-blocks
minified-js
pattern-toolkit-full-composability
product-pre-publish-modal
printful
settings
async-product-editor-category-field
launch-your-store
product-editor-template-system

Daily Cron: ✔ Next scheduled: 2024-07-23 21:14:19 -04:00
Options: ✔
Notes: 86
Onboarding: completed

### Action Scheduler ###

Canceled: 1
Oldest: 2024-07-01 11:11:09 -0400
Newest: 2024-07-01 11:11:09 -0400

Complete: 534
Oldest: 2024-06-22 17:59:40 -0400
Newest: 2024-07-23 16:57:38 -0400

Failed: 36
Oldest: 2024-02-15 22:03:43 -0400
Newest: 2024-07-23 09:22:11 -0400

Pending: 5
Oldest: 2024-07-23 23:00:00 -0400
Newest: 2029-07-12 17:31:09 -0400

### Status report information ###

Generated at: 2024-07-23 17:04:37 -04:00
</p>
</details>

**Additional context**
Reported here: https://wordpress.org/support/topic/bug-disabling-credit-card/
8516355-zd

**Comment by annemirasol** [comment]
Fixed by #3222 and #3460
