### ISSUE TITLE
Getting Unexpected error in the Block checkout page

### ISSUE THREAD

**Issue by qasumitbagthariya** [woocommerce/woocommerce-gateway-stripe#3324]
**Describe the bug**
Getting Unexpected errors in the checkout page when using Boleto and OXXO, In the block checkout

**To Reproduce**
1. Enable Boleto and OXXO payment method
2. Add to cart product and process for checkout
3. On the checkout page select Boleto and OXXO and then select the credit card or debit card option

**Expected behavior**
Users should be able to select both payment methods without encountering errors.

**Screenshots**

https://github.com/user-attachments/assets/ace7990f-8e28-4666-b1cc-5f3e39ec9430

**Environment (please complete the following information):**
 - WordPress Version 6.6.1
 - WooCommerce Version 9.1.4
 - Stripe Plugin Version 8.5.2
 - Browser Chrome
 - Any other plugins installed - NO

**Comment by Mayisha** [comment]
I have tested the checkout flow with both OXXO and Boleto in block checkout. Everything is working fine in the latest version of Stripe (`8.9.0`).

✅  **OXXO**
- Connected to a Stripe account based in Mexico.
- Enabled Card, OXXO and Boleto in the Stripe settings page.
- Set the store currency to MXN.
- As a logged-in shopper, I added a product to the cart and went to the block checkout page. (the video in the description shows the checkout page for a logged in shopper)
- Used a billing address in Mexico.
- Selected OXXO. The payment method element loads properly.
- Switched to the card method. The credit card element loads properly.
- Completed the checkout with OXXO.
- Completed another checkout with a card.
- Set the store currency to USD.
- As a logged-in shopper, I added a product to the cart and went to the block checkout page. OXXO is not offered as a payment method (as the currency is not supported)
- No error scenarios. 

✅  **Boleto**
- Connected to a Stripe account based in Brazil.
- Enabled Card, OXXO and Boleto in the Stripe settings page.
- Set the store currency to BRL.
- As a logged-in shopper, I added a product to the cart and went to the block checkout page. (the video in the description shows the checkout page for a logged in shopper)
- Used a billing address in Brazil.
- Selected Boleto. The payment method element loads properly.
- Switched to the card method. The credit card element loads properly.
- Completed the checkout with Boleto.
- Completed another checkout with a card.
- Set the store currency to USD.
- As a logged-in shopper, I added a product to the cart and went to the block checkout page. Boleto is not offered as a payment method (as the currency is not supported)
- No error scenarios. 

I am closing this issue as the error described is no longer reproducible, and we did not receive any further reports on it.
