### ISSUE TITLE
Apple Pay diaglog only shows in "Private" mode within Safari

### ISSUE THREAD

**Issue by Fr3shMint** [woocommerce/woocommerce-gateway-stripe#333]
#### Affected ticket(s)

Expected Apple Pay to work in Safari on 10.3.3 on iPhone 7 plus.

Apple pay does not show in "regular" browsing mode in Safari, however in Private browsing mode, the button shows but the dialog quickly disappears when trying to use it.

1. Open Safari 
2. Go to Minimael.com in normal browsing mode
3. Notice no apple pay on product pages
4. Go to minimael.com in "private" mode.
5. Notice button appears but quickly disappears after pushing it.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
It clearly says in the browser console that you didn't register for Apple Domain yet.

**Comment by Fr3shMint** [comment]
@roykho The domain is registered within strip for Apple Pay and the  apple-developer-merchantid-domain-association is installed in its proper location

http://imgur.com/a/hFv0g

I would appreciate if you can point me in the proper direction if something else is missing on my end.

**Comment by roykho** [comment]
Did you do this manually or let the plugin do it automatically? Try removing it from your Stripe dashboard, then in your site, uncheck "enable Apple Pay" and save. Then enable it again and save. If all that fails, I would suggest you contact support as this is not a support channel. ( https://woocommerce.com)
