### ISSUE TITLE
Stripe supports Google Payment Request notice keeps reappearing

### ISSUE THREAD

**Issue by msdesign21** [woocommerce/woocommerce-gateway-stripe#334]
> New Feature! Stripe now supports Google Payment Request. Your customers can now use mobile phones with supported browsers such as Chrome to make purchases easier and faster.

#### What I expected

When I select to close a prompt like this I expect it to close and not come back. 
<img src="http://cld.wthms.co/iB5JBx+"/>

#### What happened instead

If you close the prompt selecting the X the notice will return when you navigate to a new page in the settings or if you save settings on a page. 

Video example here: http://cld.wthms.co/UuWQUI

#### Steps to reproduce the issue

1. See notice
2. Dismiss notice
3. Save settings on a page or navigate to a new one
4. See notice again
5. (╯°□°)╯︵ ┻━┻ in fit of never ending notice rage. 

Not sure how long this new feature has been around and how long we planned to keep it around but we have too much notice fatigue (and subsequent blindness) going on in WP. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by msdesign21** [comment]
I'd also like to be able to dismiss the Stripe API keys notice. It seems like there is no way to get this to disappear, even with Stripe disabled.

**Comment by roykho** [comment]
@msdesign21 - can you please provide me admin login and FTP access privately? I am not able to replicate this on my end.

**Comment by roykho** [comment]
@mattyza are these notices still needed for 4.0?

**Comment by roykho** [comment]
Fixed via https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0

**Comment by mattyza** [comment]
These notices can definitely be removed in 4.0.0. :)
