### ISSUE TITLE
Payment Tokens with prefix "src_" are being deleted resulting in missing credit card details

### ISSUE THREAD

**Issue by phillipswdc** [woocommerce/woocommerce-gateway-stripe#3347]
**Describe the bug**
when accessing /my-account/payment-methods/ payment tokens starting with the prefix src_ are deleted locally from the *_woocommerce_payment_tokens and the *_woocommerce_payment_tokenmeta tables. The CC is not deleted from Stripe

**To Reproduce**

1. ensure that new checkout experience is enabled by going to...
/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings
and checking that "Enable the legacy checkout experience" is not checked
2. go to *_woocommerce_payment_token table and grab a user id with the src_ prefixed payment token
3. find user change password
4. Open another browser type or a private browser log in as user and navigate to the /my-account/payment-methods/ for this user and it should remove ANY payment method that uses the src_ prefix

tokens with the card_ and pm_ prefix are not removed

if you enable the legacy checkout this no longer happens

**Expected behavior**
payment tokens with src_ prefix are not deleted

**Screenshots**
This is a screenshot of mysql work bench of the payment token table isolating a users payment tokens

before opening users /my-account/payment-methods/
<img width="1136" alt="Screenshot 2024-08-08 at 6 32 26 PM" src="https://github.com/user-attachments/assets/761da9c7-0826-43ba-b19b-415d78771eb2">

after opening users /my-account/payment-methods/
<img width="1261" alt="Screenshot 2024-08-08 at 6 32 58 PM" src="https://github.com/user-attachments/assets/9d28df92-2e64-4552-ae33-5af136f7533b">

**Environment (please complete the following information):**
 - WordPress Version - 6.6.1
 - WooCommerce Version - 9.1.4
 - Stripe Plugin Version - 8.5.2
 - Browser [e.g. chrome, safari] and Version - Chrome, FireFox and Safari lates versions
 - Any other plugins installed No and theme is latest version of Store front

**Additional context**
This was discovered in our production environment confirmed in our staging environment both with all of our plugins and custom theme.

I took a backup of the current production environment and installed locally in Docker removed all plugins except Woo and Stripe and deactivated our custom theme installing storefront. 

I believe that this issue started after updating to the latest version of this trip gateway plugin

**Comment by phillipswdc** [comment]
Update it is deleted when you go to the checkout also

**Comment by phillipswdc** [comment]
Looks like this may have been fixed with latest version of plugin.

**Comment by a-danae** [comment]
Hey @phillipswdc ! Thanks for the report!

> Looks like this may have been fixed with latest version of plugin.

Would you please confirm if this is the case? 

Also, would you please confirm whether the tokens continue having an ID that begins with `src_`?

**Comment by phillipswdc** [comment]
New tokens have pm_ it is only our old tokens that remain src_ I did test with latest version and it does look like it is clear. 

Do you know what version of the plugin started with this issue?

**Comment by Mayisha** [comment]
This issue is fixed by PR https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3513.

Additionally, previously deleted tokens with `src_` will be re-created after the customer visits the checkout page or `My Account > Payment methods` page.

Thank you @mattallan for the fix.
