### ISSUE TITLE
Order Status on Failed Capture question

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#335]
#### Affected ticket(s)
ticket: 609245-zen

#### What I expected
If Stripe is configured to authorize instead of capture, when I then set an order to processing, if the capture fails, I would expect the order to go to a failed status

#### What happened instead
The order is set to processing.

#### Steps to reproduce the issue
1. Configure Stripe to authorize instead of capture
2. Go through the purchase process
3. Login to the Stripe merchant dashboard and release the charge
4. Back to WooCommerce order screen and set the order to a processing status
5. Attempt at capturing the charge fails (expected) but the order remains in a processing status.

I could certainly see an argument in favor of the order remaining in a processing status since this does require the shop manager to manually change the order status so the order is respecting what has been done, but this is a bit problematic when Subscriptions is thrown into the mix as the order status change activates the subscription.

I guess my question comes down to two things:

1. What is the consensus view of the correct behavior in this case. Should the Stripe gateway plugin change the order to a failed status or should that be left to the shop manager?
2. If the order should remain in a processing status and not be changed automatically, could a setting be added to cause the order to automatically transition to a failed status if a capture fails?

@roykho 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@WillBrubaker Stating here just for completeness I believe if an order is authorize only, then the order status initially should be "on-hold". Thereafter, "manually" they can capture it by moving the order status to either "processing" or "completed".

With that flow, assuming the payment captures successfully the order status should then be moved to either one of the mentioned statuses above. If it fails the capture, in my opinion, the order status should be moved to "failed".

**Comment by WillBrubaker** [comment]
Yep the above is correct, sorry I didn't present the whole picture earlier.

**Comment by roykho** [comment]
@WillBrubaker actually come to think of it, for subs, there is no authorize then capture. Subs order will capture regardless of the settings.

**Comment by WillBrubaker** [comment]
@roykho That doesn't seem to be the case in my testing (nor the ticket submitter's) the charge is authorized, not captured. Haven't tested specifically against renewal orders yet but orders done via checkout authorize.

**Comment by WillBrubaker** [comment]
just went back and tested a renewal and indeed the renewal order captures regardless of the setting.

**Comment by roykho** [comment]
Ok in any case, the order status should now go into "failed" if capture is not successful via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/68e93d0c2d3e276fd258e4c7819e0f60ce76c3c0

**Comment by WillBrubaker** [comment]
Just tried to test against that branch and it's causing me heaps of problems - guess it's a WIP but I get a failure to process - this is in the Stripe log:

```
08-10-2017 @ 15:29:41 - ====Start Log====
Error: Payment processing failed. Please retry.
====End Log====
```

Also, with braintree active 

```
Catchable fatal error: Object of class WC_Gateway_Braintree_Credit_Card could not be converted to string in woocommerce-gateway-stripe/woocommerce-gateway-stripe.php on line 380
```

**Comment by roykho** [comment]
Yes its WIP however you shouldn't get any errors. The braintree issue is on their end I believe as it is loading the whole class object into payment gateways instead of just the class name. Have you tried deactivating that and re-test?

**Comment by WillBrubaker** [comment]
I have stripped things down to only WooCommerce and Stripe, still get "Payment processing failed. Please retry." with the same thing in the Stripe log - that's on 68e93d

**Comment by roykho** [comment]
If you could show me the exact settings you have in Stripe, I will try to replicate based on your settings.

**Comment by WillBrubaker** [comment]
Sure thing:
![see screen shot](http://cld.wthms.co/KUx22U+)

![see screen shot](http://cld.wthms.co/sMPpTn+)

and the system status report
<details>
### WordPress Environment ###

Home URL: http://subscriptions-test-site.dev
Site URL: http://subscriptions-test-site.dev
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 4.0.0
WooCommerce: by Automattic – 3.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by roykho** [comment]
@WillBrubaker Thanks for that. Did you see anything in the JS console by chance?

**Comment by WillBrubaker** [comment]
@roykho nothing in the console :(

**Comment by tommybds** [comment]
Hello, same problem on the 4.0.0 rc1 with 3d secure activated. I added the webhook in stripe but doesn't work, it keep saying "PAYMENT PROCESSING FAILED. PLEASE RETRY." in test or live mode.

**Comment by ActionScripted** [comment]
Same issue here. Everything was great until we updated.

**Comment by ActionScripted** [comment]
Same issue here. Everything was great until we updated. Why is this issue closed? We've seen several stores with issues relating to newer versions of this plugin.

There aren't any errors in JS/server. The only error is what's been outlined above and everything was working until we updated.

**Comment by mcyger** [comment]
Same issue here.

**Comment by djangoboi** [comment]
Here as well.

**Comment by djangoboi** [comment]
@roykho has this issue been resolved?

**Comment by djangoboi** [comment]
What was the solution?

**Comment by will-ashworth** [comment]
Also wondering? No details here, so...
