### ISSUE TITLE
Show one notification at a time, instead of all of them at once

### ISSUE THREAD

**Issue by nabsul** [woocommerce/woocommerce-gateway-stripe#336]
Store owners' wp-admin is very frequently filled with multiple notifications from different plugins. Stripe appears to even do multiple notices at the same time.

Could we make it so that only one notification is shown at a time? Once one is dismissed / resolved we could show the next one, in order priority...

![image](https://user-images.githubusercontent.com/11143071/29148956-7fe0d3ea-7d25-11e7-93af-501f739ca731.png)

**Comment by roykho** [comment]
Those are all dismissible from 4.0.0 on.

**Comment by nabsul** [comment]
I'm suggesting that even though they're dismissable, it's probably better to not show them all at once.

Especially when you consider the bottom notification "Setup your stripe account". Wouldn't it be better to show that by itself, and then show the informational ads after stripe is setup?

I think that would reduce the likelihood of a user just dismissing all three at once.

**Comment by roykho** [comment]
I am fine with either approach. cc @mattyza

**Comment by mattyza** [comment]
We'll be removing the "informational" notices as of 4.0.0, so the focus can be on the "set up your Stripe account" notice. We can make that a green notice as well, for additional clarification.
