### ISSUE TITLE
Insert Metadata on charge

### ISSUE THREAD

**Issue by katsar0v** [woocommerce/woocommerce-gateway-stripe#337]
#### What I expected

Issue: When charged, the address information and additional metadata is not sent to stripe. Is it possible to send it?

#### What happened instead

Few metadata just got sent

**Comment by roykho** [comment]
You can add your own information to the metadata by using the hook. https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L621

**Comment by chrisknose** [comment]
Line 621 seems to have moved. Can you update with reference or hook?
