### ISSUE TITLE
PHP Warning: Undefined array key 0 in class-wc-stripe-customer.php on line 241

### ISSUE THREAD

**Issue by slaFFik** [woocommerce/woocommerce-gateway-stripe#3372]
**Describe the bug**

I see this record in the error log:

```
PHP Warning: Undefined array key 0 in .../plugins/woocommerce-gateway-stripe/includes/class-wc-stripe-customer.php on line 241
```

**To Reproduce**

Unfortunately, I don't know how to reproduce it.

**Expected behavior**

There should be no PHP Warnings.

**Environment (please complete the following information):**
 - WordPress Version: 6.6.1
 - WooCommerce Version: 9.1.4
 - Stripe Plugin Version: 8.6.1

**Comment by james-allan** [comment]
Thanks for submitting the bug @slaFFik. I was able to replicate by placing an order while in guest checkout mode using an email not linked to any account in Stripe.

**Comment by hayley-king** [comment]
Similar issue reported in 8639528-zen
