### ISSUE TITLE
Remove Keys from settings after uninstalling the plugin

### ISSUE THREAD

**Issue by diegocurbelo** [woocommerce/woocommerce-gateway-stripe#3384]

**Comment by dcx15** [comment]
Why not simply remove all settings on uninstall?

**Comment by diegocurbelo** [comment]
> Why not simply remove all settings on uninstall?

The plugin behaves like WooCommerce; this change aims to remove only sensitive data from the settings: 

"The WooCommerce plugin can be uninstalled like any other WordPress plugin. By default, the WooCommerce data is left in place though."
- [Uninstall and remove all WooCommerce Data](https://developer.woocommerce.com/docs/uninstall-and-remove-all-woocommerce-data/)
