### ISSUE TITLE
[4.0] Order status processing when charge pending

### ISSUE THREAD

**Issue by thorsten-stripe** [woocommerce/woocommerce-gateway-stripe#340]
@roykho can we set the order status to pending payment if the charge status comes back as pending after the charge request? https://stripe.com/docs/sources#synchronous-or-asynchronous-confirmation

Currently e.g. for SOFORT or SEPA the order is marked as processing after the charge request has been created which could mislead the user to think that their money has arrived for this order.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/1d97fa7e6e2218f40c171cbe59ea1e286534ab20
