### ISSUE TITLE
[ECE] Implement ECE for payment processing on block cart page

### ISSUE THREAD

**Issue by Mayisha** [woocommerce/woocommerce-gateway-stripe#3408]
### Description
Display the ECE button and process payment with the button on the block cart page.

### Acceptance Criteria
- ECE buttons are rendered on the block cart page.
- You can successfully process payment with the ECE button from the block cart page.
- Both success and failure cases are handled including necessary notices.

**Comment by annemirasol** [comment]
Should be mostly covered by #3439

**Comment by Mayisha** [comment]
I have tested the flows on the Block cart page and checkout with ECE buttons are working correctly.
Closing this issue as the implementation is already handled and merged via https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3439.
