### ISSUE TITLE
[ECE] Implement ECE for payment processing on shortcode cart page

### ISSUE THREAD

**Issue by Mayisha** [woocommerce/woocommerce-gateway-stripe#3409]
### Description
Display the ECE button and process payment with the button on the shortcode cart page.

### Acceptance Criteria
- ECE buttons are rendered on the shortcode cart page.
- You can successfully process payment with the ECE button from the shortcode cart page.
- Both success and failure cases are handled including necessary notices.

**Comment by james-allan** [comment]
Just noting that the cart integration is the same as the checkout integration being built in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3436. I'm going to leave this one for now and wait until that PR is merged. 

**Blocked** by: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3436

**Comment by james-allan** [comment]
https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3436 has been merged now so I'm unblocking this. 

I think this issue will need to take an approach of did the work in #3436 also implement it for the shortcode cart page.
