### ISSUE TITLE
cashapp description is white

### ISSUE THREAD

**Issue by Cral-Cactus** [woocommerce/woocommerce-gateway-stripe#3416]
**Describe the bug**
So the bug is that cashapp payment method description is invisible!

**To Reproduce**
1. Go to 'checkout'
2. Click on 'cashapp'
3. Scroll down to 'cashapp'

**Expected behavior**
it is expected to be black so it doesnt look bad

**Screenshots**
![image](https://github.com/user-attachments/assets/849f407e-8299-4926-8fab-83f2bda0adb1)

**Environment (please complete the following information):**
 - WordPress Version - latest
 - WooCommerce Version - latest
 - Stripe Plugin Version - latest
 - Browser [e.g. chrome, safari] and Version - brave  - latest
 - Any other plugins installed

**Comment by csmcneill** [comment]
Howdy @Cral-Cactus! Thanks for reporting!

I'm unable to reproduce this on a test site with the Twenty Twenty Four theme:

![CleanShot 2024-09-18 at 21 22 08](https://github.com/user-attachments/assets/14987bbf-e932-4494-a091-b624efda281b)

I took a peek at the changes you proposed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3417/ but the original RGB value (`109, 109, 109`) should be [a medium gray](https://rgb.to/rgb/109,109,109) — not white. Changing this value to `0, 0, 0` (or [black](https://rgb.to/rgb/0,0,0)) likely won't resolve the issue.

It also seems like your proposed PR to resolve this focuses on the `index.js` file in the `__tests__` folder, which is likely for E2E testing. You may want to look at [this index.js file](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/781d73e9269d4916148d2f0899f674af7cd4bbc8/client/styles/upe/index.js) instead:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/781d73e9269d4916148d2f0899f674af7cd4bbc8/client/styles/upe/index.js#L360

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/781d73e9269d4916148d2f0899f674af7cd4bbc8/client/styles/upe/index.js#L329-L332

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/781d73e9269d4916148d2f0899f674af7cd4bbc8/client/styles/upe/index.js#L25

**Comment by Cral-Cactus** [comment]
uh yea looks like some issue from my end sorry
