### ISSUE TITLE
[4.0] Increase min-width of payment method selection accordion

### ISSUE THREAD

**Issue by thorsten-stripe** [woocommerce/woocommerce-gateway-stripe#342]
On a desktop device the payment method selection accordion is quite narrow, causing, for example, a lot of breaks in the SEPA mandate text: https://www.dropbox.com/s/8hpfj8oh89t268t/Screenshot%202017-08-11%2022.54.29.png?dl=0

The page is responsive but the thresholds for switching to a stacked vertical view is at too narrow a page, causing overlap of the `Card number` and `MM / YY` placeholder: https://www.dropbox.com/s/dt29oope0e7gh3b/Screenshot%202017-08-11%2022.55.22.png?dl=0

Would you be able to enforce a wider min-width for the payment method selection or widen the stacking threshold? Also, is this something you could enforce across third-party store themes?

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
This will be theme/designer dependent so leaving it for them to apply CSS.
