### ISSUE TITLE
The theme design breaks on iPhone when Plugin is activated.

### ISSUE THREAD

**Issue by cheonmux** [woocommerce/woocommerce-gateway-stripe#343]
Hi.

I use Flatsome Theme with Woocommerce plugin. But if I activated WooCommerce Stripe Payment Gateway plugin and check it on iPhone,

the theme design breaks like this ->  
![image](https://user-images.githubusercontent.com/15154697/29417426-17e5bd16-83a4-11e7-94be-b4692e6cf515.png)

![image](https://user-images.githubusercontent.com/15154697/29417408-111d3a54-83a4-11e7-886c-d6947d1638d4.png)
  . But when I check it on Windows PC, it is normal. 

Tell me what I should do.

Thank you

**Comment by roykho** [comment]
Apple Pay has its own specific styles that overrides your theme. You can use CSS to override it again with `!important`.
