### ISSUE TITLE
Checkout fails when using Google Pay with UAE shipping address

### ISSUE THREAD

**Issue by annemirasol** [woocommerce/woocommerce-gateway-stripe#3430]
**Describe the bug**
When using Google Pay with a UAE shipping address, we get the error "Shipping Town / City is a required field." on checkout.

**To Reproduce**
1. Add a UAE address in your Google Pay account: https://payments.google.com/gp/w/u/0/home/addressbook
   - For example: PO Box 12345, Abu Dhabi, United Arab Emirates
2. Make sure you are NOT in the Google Pay API Test Cards allowlist: https://groups.google.com/g/googlepay-test-mode-stub-data
   - If you are in the allowlist Google group, you will have access to the test address data set only, which does not include UAE.
3. Make sure test mode is enabled in Stripe, to avoid actual charges: `wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe&panel=settings`
4. As a shopper, add a product to your cart, and go to checkout.
   - **Important**: Make sure the shipping and biling form fields are clear. If they are pre-populated (due to autofill), clear them out first. Reason: We have added behavior in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2886 to pull in data from the checkout form for required fields. If you have been testing with a different address that has a city, this may get pulled in.
7. Click the "Buy with Google Pay" button to open the modal.
8. Make sure to choose the UAE address as the shipping address in the Google Pay modal.
9. Click Pay.
10. Notice the payment fails with the error "Shipping Town / City is a required field."

<img width="888" alt="Screenshot 2024-09-10 at 3 52 12 PM" src="https://github.com/user-attachments/assets/b85e778a-8106-4665-b05a-83c4c47f9ba1">

**Expected behavior**
Google Pay should work for all supported shipping locations, including UAE.

**Screenshots**

**Environment (please complete the following information):**
 - WooCommerce Version 9.2.3
 - Stripe Plugin Version 8.6.1
 
**Additional context**
Flagged by @imodouglas in p1725444234401429/1725281800.433019-slack-C055WHLA98D

**Comment by shohanhossainnab** [comment]
8630834-zen
