### ISSUE TITLE
Apple Pay incompatible with CloudFlare

### ISSUE THREAD

**Issue by tommyshellberg** [woocommerce/woocommerce-gateway-stripe#344]
We have the following response to customers but I cannot find any conversations between us and Cloudflare:

> CloudFlare breaks Apple Pay: currently waiting for a feedback from CloudFlare on this

#### Affected ticket(s)

630448-zd-woothemes
586791-zd-woothemes

From an affected customer: 

> This only happens on my LIVE domain, and not my production/staging website. This led me to believe it was an issue with Cloudflare (after inspecting the DOM), however, Cloudflare says the issue lies with the plugin, not the network.

@mattyza pinging you as a result of our previous conversation. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by mattyza** [comment]
@tommyshellberg - thanks. Did CloudFlare perhaps provide more information about how/why the plugin is at fault here?

**Comment by tommyshellberg** [comment]
I'm afraid that I haven't had any communication with CloudFlare myself; I came across this in our payments internal communication and was trying to track down where the communication occurred. Does @mdmoore or @corsonr or @spraveenitpro have anything to contribute here?

**Comment by roykho** [comment]
Closing this for now as I don't have access to Cloudflare and no new issues of this. Please re-open if new issues arise.

**Comment by joelwills** [comment]
@tommyshellberg Did you ever find where we contacted Cloudflare about this?

**Comment by WPprodigy** [comment]
Just ran into a Cloudflare issue on a site. Disabling Cloudlfare solved the issue. This started happening after the 4.0 update for them.

JavaScript error reported by customer:

> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://js.stripe.com”). Source: ;!function(){var t=0,e=function(t,e){ret....

The result was the Stripe checkout form sometimes not showing up. They found it to be a problem in Firefox but not Chrome. 

I took this screenshot in Firefox on their site: http://cld.wthms.co/bbbCBW.

____

From what I can read, it didn't sound like Cloudflare added a CSP: https://support.cloudflare.com/hc/en-us/articles/216537517-What-is-Content-Security-Policy-CSP-and-how-can-I-use-it-with-Cloudflare-. But they must be doing something.

Maybe our plugin could check for CSP, and do what Stripe recommend here: https://stripe.com/docs/security#content-security-policy ?

**Comment by roykho** [comment]
@WPprodigy What Stripe recommends there is done on server level. I don't believe we could add that in plugin?

**Comment by WPprodigy** [comment]
The `<meta>` head element is frontend technically. I don't know much about this though - there might not be much we can do.

If that's the case, would be good to find out what settings exactly need to be disabled in CloudFlare so we can add an FAQ on this.

**Comment by roykho** [comment]
If we could add it plugin level, that would be good.

**Comment by roykho** [comment]
Closing this in favor of this workaround https://wordpress.org/support/topic/stripe-payment-is-not-working-on-google-chrome/#post-10026055
