### ISSUE TITLE
Using woocommerce_new_order_item Incorrectly

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce-gateway-stripe#345]
#### Affected ticket(s)

https://woothemes.zendesk.com/agent/tickets/645660

#### What I expected

The [second parameter passed here is wrong](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-apple-pay.php#L932).

1. `wc_get_product( $item_id )` won't work with an item ID
2. This shouldn't be a product object anyway.

#### What happened instead

This filter should [conform to the same args as WC core](https://github.com/woocommerce/woocommerce/blob/4101e313bb18c588d3e7dbd5170e6d19ad275b53/includes/data-stores/abstract-wc-order-item-type-data-store.php#L50)  and pass a `WC_Order_Item` object to avoid fatal errors in other plugins that get the object downstream.

#### Steps to reproduce the issue

Use anything plugin that hooks into this action after Stripe. As outlined in that ticket, in this case it's Checkout Add-ons, which expects an order item object and doesn't get it, resulting in a fatal error when we call `$item->get_type()`

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by bekarice** [comment]
@Luminus potentially one you want to follow up on since the issue is in Stripe?

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/0a0239df5b5e8f78e1251f1700010dd232fcc60a

**Comment by Luminus** [comment]
Thanks for the heads up @bekarice and for the fix @roykho.

I'll follow up with the user right away.

**Comment by Luminus** [comment]
Hey @roykho, it looks like this fix only implemented in the 4.0.0 branch. I can't share a pre-release of this with the user just yet, can I?

I'm assuming this is because 4.0.0 will be out in the wild soon. Do we have an ETA? It would help with messaging. Thanks

**Comment by roykho** [comment]
Hi @Luminus - I will make a patch release today.
