### ISSUE TITLE
Payment for Pay Later Pre-Order completed orders via the payment link are not completing.

### ISSUE THREAD

**Issue by imodouglas** [woocommerce/woocommerce-gateway-stripe#3455]
**Describe the bug**

When a pre-order product with a pay upon-release option is purchased and later completed, a payment link is sent to the customer via email to complete the payment. However, when they try to make the payment they get the ["pre-order has been received" screen](https://d.pr/i/R6HPpv), and the payment does not go through.

**To Reproduce**
1. Create a pre-order product with a pay upon-release option on a site with Stripe as payment method.
2. Purchase the order with the Pay Later payment method.
3. Go to WooCommerce > Pre-Orders and complete the pre-order to get the payment link.
4. Try making payment via the link with the credit card.

**Expected behavior**

Payment should be taken and the customer should see the thank you page.

**Comment by imodouglas** [comment]
8751993-a8c-zd

**Comment by slash1andy** [comment]
What notes show in the order for the payment? Does this happen with any other gateway?
