### ISSUE TITLE
[ECE] Fix payment method title for orders paid with ECE button 

### ISSUE THREAD

**Issue by Mayisha** [woocommerce/woocommerce-gateway-stripe#3469]
The payment method title is set to `Credit/Debit Card` instead of `Apple Pay` or `Google Pay` when purchased via the express checkout button.

### Steps to reproduce
- Enable the ECE feature flag (return `true` from `is_stripe_ece_enabled` function or in your database add an option `_wcstripe_feature_ece` and set `yes` as the value).
- Checkout to the branch of either https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3439 or https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3436 (checkout to `develop` if any of the mentioned PR is merged)
- As a shopper add a product to your cart and go to the checkout page. 
- Complete the purchase with Google/Apple pay button.
- Notice that on the order confirmation page, the payment method is `Credit/Debit Card` instead of `Apple Pay` or `Google Pay`.

<img width="984" alt="370430056-cf76c96b-d7fb-47c4-8b37-0778d296ed4e" src="https://github.com/user-attachments/assets/acc6ef9b-bbee-49a2-962a-92fc86dfc5ed">

- As an admin, go to the order edit page and notice that the payment method is `Card`.

<img width="870" alt="Screenshot 2024-09-25 at 4 31 44 PM" src="https://github.com/user-attachments/assets/e430ce1d-6022-402d-9084-b5d7348f69e7">

### Expected behavior
- The payment method title should be Google Pay or Apple Pay similar to how it is set when paid with PRB buttons. 

<img width="870" alt="Screenshot 2024-09-25 at 4 31 32 PM" src="https://github.com/user-attachments/assets/47785852-febb-423e-bb2a-37e93ced5c3b">

**Comment by james-allan** [comment]
I fixed this issue on my Pay For Order PR https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3440. In that PR I added a new helper to map the payment button type to a payment method title. 

I'll take this one.
