### ISSUE TITLE
United Kingdom not being passed as country even with valid address

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce-gateway-stripe#349]
#### Affected ticket(s)

631285-zd-woothemes

#### What I expected

When I use a United Kingdom address in Apple Pay - it should.. uhh... use that address and not make up a different one.

#### What happened instead

Address entered:

61 Willifield Road, Roath, CARDIFF CF24 3DG, United Kingdom (UK)

Address that shows up in the Order Screen:

61 Willifield Road, Roath, CARDIFF CF24 3DG, United States (US)

![screen shot 2017-08-25 at 11 05 23 am](https://user-images.githubusercontent.com/3220162/29726631-54590c3a-8985-11e7-81b4-f32645e824ba.png)
![screen shot 2017-08-25 at 11 06 44 am 1](https://user-images.githubusercontent.com/3220162/29726672-8136f186-8985-11e7-8f8a-2762b2aa4819.png)

#### Steps to reproduce the issue

Enter in a valid UK address and make a purchase using Apple Pay. 
The ticket above has a staging site already created where you can see the problem yourself.  You can see htaccess and login details in the sidebar.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/58d05784af704a6a00b33acf84b07e8de7943150
