### ISSUE TITLE
POST /wp-json/wc/v2/orders/{orderID}/refunds 500s if API keys are missing

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#350]
#### Affected ticket(s)

None

#### What I expected

Maybe well-formed JSON with a code 503 and with something like `Invalid Stripe API Key in settings` in the response?

#### What happened instead

Got a 500 as HTML from the site in response to the refund request. (See following comment)

#### Steps to reproduce the issue

1) Set up the extension properly, including API keys (test keys are fine)
2) Create an order for a non-trivial amount and use Stripe to pay for it
3) Delete your API keys
4) Use POSTMAN or the tool of your choice to attempt to POST a refund request for the order
5) Behold the madness

Problem: Errors like this make it especially hard to debug on API clients like Jetpack/Calypso.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by allendav** [comment]
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title> 500 Error code from your website </title>
        <meta name="description" content="">
        <meta name="author" content="">
        <!-- styles -->
        <style>
    body {
        background-color: #f8f8f8;
        font: 12px/18px "helvetica neue",helvetica,arial;
    }
    .container {
      	width: 940px;
 		margin-left: auto;
  		margin-right: auto;
  		*zoom: 1;
	}
	.centerdiv {
		text-align: center;
		border-radius: 5px;
		position: relative;
		width: 750px;
		margin: auto;
		margin-top: 120px;
		padding: 30px;
		background-color: #fff;
		-webkit-box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.3);
		-moz-box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.3);
		box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.3);
	}
	.logo {
		margin-bottom: 20px;
	}
	.title {
		font-size: 45px;
		font-weight: bold;
		color: #333;
		line-height: 1;
		margin-bottom: 25px;
	}
	.subtitle {
		font-size: 22px;
		font-weight: bold;
		color: #999;
		line-height: 1;
		margin-bottom: 25px;
	}
	p {
		color: #666;
		line-height: 1.5;
		text-align: left;
	}
	.from {
		text-align: left;
		color: #666;
	}

    </style>
    </head>
    <body>
        <div class="container">
            <div class="centerdiv">
                <div class="title">
				Error 500
			</div>
                <div class="subtitle">
			The server encountered a syntax error, and could not complete your request.
			</div>
                <p>  Website owner? 
                    <strong> check your code, and your debug log</strong>, you may find a 'parse' error in there.
                    <br />
                </p>
                <p>
				Visitor? Try and reload it in a few minutes.
			</p>
            </div>
        </div>
    </div>
    <!-- /container -->


  
</body>
</html>
```

**Comment by dambrogia** [comment]
Awesome find and writeup! 

Might want to consider to have this return a `401` error versus the `503` you mentioned.

Taken directly from [wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes):

    401 Unauthorized (RFC 7235)

> Similar to 403 Forbidden, but specifically for use when authentication is required and has failed or has not yet been provided.  [ ... ] 401 semantically means "unauthenticated",[34] i.e. the user does not have the necessary credentials.


    503 Service Unavailable

> The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state.[63]


Just my quick 2 cents from the peanut gallery, feel free to constructively criticize. I agree that returning an error message rather than raw html would be extremely beneficial!

**Comment by dwainm** [comment]
Agreed, we should return valid JSON for a JSON request.

Though deleting the API keys is a critical issue, therefore, I'm in favour of returning a 503 error, with the details: invalid payment gateway validation.

503 means we(site) did something wrong vs 403, you(client) did something wrong.

Let me know if this will work for you @allendav ( not sure if you're still working on this integration ).

**Comment by dwainm** [comment]
This is resolved in the latest version. 

With Postman, when I POST `http://localhost/wp-json/wc/v2/orders/1597/refunds`

I get:
```
{
    "code": "woocommerce_rest_cannot_create_order_refund",
    "message": "Invalid API Key provided: ",
    "data": 500
}
```

Seems to no longer be an issue in WC 3.2 or the latest version of strip.
