### ISSUE TITLE
Missing Shipping information and state 

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce-gateway-stripe#355]
Missing Shipping information and state

#### What I expected

I have the full billing and shipping information when customer paid by Apple Pay.

#### What happened instead

The state was missing for Canadian customer and the shipping information was empty. The order was paid by Apple Pay

#### Steps to reproduce the issue

Customer purchased product by using Apple Pay.

![screen shot 2017-09-01 at 2 47 29 pm](https://user-images.githubusercontent.com/2909982/29983785-6cc8f3c0-8f25-11e7-8590-5a8671230d1d.png)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Hi @kevin25 - could you please specify the version of Stripe you're using?

**Comment by kevin25** [comment]
@roykho It's version 3.2.3 with WooCommerce 3.1.2

**Comment by roykho** [comment]
@kevin25 - if you want to give this branch a try https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0 note it is still in beta though so best to test on a staging.

**Comment by kevin25** [comment]
@roykho Thank you. I'll try it. When will this version be released?

**Comment by roykho** [comment]
@kevin25 I don't have any ETA at this time but it is already in our internal beta testing so it shouldn't be too long from now.

**Comment by kevin25** [comment]
@roykho Great to hear that. Thank you!

**Comment by kevin25** [comment]
@roykho Is SEPA available to Public now or just invited account can use it?

**Comment by melindahelt** [comment]
zd-675922 reporting a similar issue, with shipping information missing, and billing Address 1 missing. Using WooCommerce 3.1.1 and Stripe 3.2.3

**Comment by roykho** [comment]
@kevin25 - best to contact Stripe about that.

Closing this issue as I have tested 4.0 branch and it is working there.
