### ISSUE TITLE
Apple Pay and Subscriptions

### ISSUE THREAD

**Issue by rezzz-dev** [woocommerce/woocommerce-gateway-stripe#356]
I know that this plugin doesn't support Apply Pay Subscriptions, however, I'm curious as to the reason.

That may sound a bit demanding, or out of line and I apologize I don't mean that in any way at all.

I'm opening up the discussion because I've had several conversations around this with several people, both developers and clients. The latest can be found on [Twitter here](https://twitter.com/Prospress/status/905841583882330113).

My ultimate question really is this. If Apply Pay natively supports subscriptions, Stripe natively supports subscriptions, WooCommerce has Subscriptions to enable this, what is needed to connect all the dots to allow sites running WooCommerce Subscriptions the ability to use Apply Pay for subscriptions?

**Comment by rezzz-dev** [comment]
Thanks @seb86 -- I will certainly test that and see if it works.

Only reason I opened it for discussion was that Brent didn't seem confident that was the solution. Maybe I should've given it a try first. 

I'll report back.

**Comment by rezzz-dev** [comment]
Just to follow up - This didn't work - in fact, it bypassed the Subscription functionality and just charged it as a one-off product. 

(Actually, not sure if it's Apple Pay's functionality or not, but when the charge was created it didn't take into account tax)

**Comment by seb86** [comment]
I suggest having a look at the Stripe documentation for Apple Pay.

**Comment by roykho** [comment]
Closed in favor of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/566
