### ISSUE TITLE
Remove the "A Source is used for renewals but could not be updated to PaymentMethods" subscription order note

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce-gateway-stripe#3565]
### Describe the bug

In 8.5.0 (https://github.com/woocommerce/woocommerce-gateway-stripe/pull/3249) we added a function which would attempt to migrate subscriptions using `src_` tokens to the PaymentMethods API. This included all source objects.

Stripe have since clarified that they don't intend to migrate **card** source objects. Given that, we should remove this subscription note because migration is not likely to ever occur and it can confuse merchants into thinking there is an issue.

<p align="center">
<img width="300" src="https://github.com/user-attachments/assets/e786442a-67ed-4e04-a684-c4bfb6a6820c" alt="Image">
</br>
<sup>Note added to a subscription after failing to migrate a source to a payment method.</sup>
</p>

### To Reproduce

**GETTING A SOURCE CARD**
If you already have a source card object, skip these steps. 

1. **Checkout of Stripe 8.7.0**
   - `git checkout 8.7.0`
   - `npm run build`
   - ❗ This is important because in 8.8 we updated express payment methods to use `pm_xxx`
2. Purchase a subscription product using an express checkout method like Google pay.
   - Make sure to disable ECE if you have that feature flag enabled.
3. You should end up with a subscription with a source object.
   - You can verify either via the database or via the edit subscription admin screen.

<p align="center">
<img width="500"src="https://github.com/user-attachments/assets/ac965885-0bac-4a94-9311-ecd5dc19d073" alt="Image">
</p> 

**THE NOTE**

1. Renew the subscription by choosing the[ **Process Renewal** action on the Edit Subscription screen](https://woocommerce.com/document/subscriptions/add-or-modify-a-subscription/update-an-existing-subscription/#process-a-renewal) or via the Scheduled Actions. 
2. In the subscriptions, notes you should see the notice mentioned at the top of this issue. 

### Expected behavior

This notice should not be added for sources which are cards. Cards are not being migrated, only APM sources like SEPA.

**Comment by contemplate** [comment]
I have already had few merchants concerned that there is an issue even though the subscriptions renews fine.  Removing this makes sense for Cards.
