### ISSUE TITLE
Sending Metadata of Product ID to Stripe

### ISSUE THREAD

**Issue by kwilliams9i6** [woocommerce/woocommerce-gateway-stripe#358]
#### Affected ticket(s)

#681915

New Feature:

I want to be able to send metadata of Product ID's to stripe on the charge request. This will enable to me to integrate that information into Stripe Radar rules for fraud detection. This feature would be very beneficial to businesses. It would give the business owner control to set fraud rules for specific products. As certain products have a higher cost in the event of fraud, due to labor, costs, etc. 

I would think that it would go here on class-wc-gateway-stripe, in the generate payment request function. 

<img width="890" alt="screen shot 2017-09-18 at 12 02 32 pm" src="https://user-images.githubusercontent.com/31019707/30559442-8581e380-9c69-11e7-9048-b9783e84412c.png">

Anyone have additional thoughts on how to accomplish this?

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
You can use `wc_stripe_payment_metadata` filter when 4.0 is released.

**Comment by kwilliams9i6** [comment]
Thank you. Is 4.0 is open beta?
