### ISSUE TITLE
Feature Request: Redirect to standard checkout on PaymentRequest cancel

### ISSUE THREAD

**Issue by mattwomple** [woocommerce/woocommerce-gateway-stripe#360]
#### What I expected

If a user cancels the PaymentRequest API dialog, I expected them to be redirected to standard checkout where they could see all payment options available to them.

#### What happened instead

The PaymentRequest dialog just closes.

#### Steps to reproduce the issue

1. Enable Payment Request API (note: there shouldn't be a space between _Payment_ and _Request_)
2. Begin checkout from a device which [supports](https://www.chromestatus.com/feature/5639348045217792) the PaymentRequest API
3. When the PaymentRequest dialog shows, hit cancel
4. The dialog closes without redirecting to standard checkout

[Screenshot](https://android.cmphys.com/temp/PaymentRequest-dialog.png)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
In 4.0, there will be two buttons one for regular checkout and one with the PaymentRequest.
