### ISSUE TITLE
WordPress 6.7 Compatibility - Translations triggered too early

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce-gateway-stripe#3604]
**Describe the bug**
After updating to WordPress 6.7 and swapping your language to a non-english language (i.e. Spanish) you will start seeing the following notices:
![Image](https://github.com/user-attachments/assets/62d0e7aa-03b4-4546-ad5e-5ef5b9c95d79)

I haven't yet sourced where which area of Stripe specifically is causing this, however, as of WP 6.7, we shouldn't translate anything any earlier than the `init` hook.

Considering that our main `WC_Stripe` plugin instance is instantiated on `plugins_loaded` which is well before the `init` hook (see [hook reference/order](https://developer.wordpress.org/apis/hooks/action-reference/)) we'll need to go through all files/classes loaded within our `WC_Stripe->init()` and ensure any translated strings are ran after `init`.

**To Reproduce**
1. Install WordPress 6.7
1. Go to your Edit User Profile page and set your language to Español![Image](https://github.com/user-attachments/assets/2290aa6c-2be8-4d65-af3d-41c2eb062b1f)
1. Save the settings and reload any admin page
2. You should see the following notice calling out Stripe at the top of the page:![Image](https://github.com/user-attachments/assets/9efc4c4a-f05a-479b-84d5-ca309225134b)

**Comment by danieleperilli** [comment]
I have the same problem without any active translation. Can we expect a solution soon?

**Comment by mattpfeffer** [comment]
Yep, same here. Although in my setup the notice is causing headers to be sent too early which triggers a wider issue.

**Comment by mattallan** [comment]
Hey @danieleperilli and @mattpfeffer, thanks for reaching out.

The fix for this issue has been merged but since we hadn't received any reports of this, and given it only impacts stores with `WP_DEBUG` enabled, we didn't have plans to rush this fix out in patch release.

Now that we have two reports, I'll pass this along to the rest of team to discuss doing a patch release. 

In the meantime, I've uploaded a pre-release zip for v8.9.1 which is just 8.9.0 + these fixes.
As with all releases, please upload this to a development or staging site first to test: [woocommerce-gateway-stripe.zip](https://github.com/user-attachments/files/17929086/woocommerce-gateway-stripe.zip)

**Comment by danieleperilli** [comment]
Thanks @mattallan. In the meantime, I disabled E_USER_NOTICE in the configuration, as the log was being flooded with those logs and growing to MB in a few minutes :(

**Comment by thisissandip** [comment]
9091816-zen

**Comment by perrelet** [comment]
@mattallan Do we have a release date for this yet?

**Comment by LARAMediaGroup** [comment]
Any updates? This is messy, impacting several of our products and platforms.
