### ISSUE TITLE
Feature Request: Option to skip PaymentRequest if !canmakepayment()

### ISSUE THREAD

**Issue by mattwomple** [woocommerce/woocommerce-gateway-stripe#361]
#### What I expected

When PaymentRequest API support is enabled, it would be nice if there was an option to only show the PaymentRequest dialog if users have payment information stored in their browser. This can be accomplished through use of [canmakepayment()](https://w3c.github.io/payment-request/#canmakepayment()-method).

#### What happened instead

The PaymentRequest dialog is shown regardless of whether users have payment information stored in their browser, sometimes discouraging checkout completion.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Already in 4.0
