### ISSUE TITLE
Strips Dashboard says API out Of Date

### ISSUE THREAD

**Issue by TomasHurtz** [woocommerce/woocommerce-gateway-stripe#362]
In Stripe Dashboard:

dashboard.stripe.com/account/apikeys

You're using API version 2016-10-19 OUT OF DATE  

Will upgrading this break Woocommerce Version 3.2.3 ?

**Comment by mattyza** [comment]
Hi @TomasHurtz - we're working on using the newest version of the Stripe API in an upcoming release. That said, if there's a button you can click to update your API reference/keys somewhere on your Stripe dashboard, that shouldn't affect the code used on your store.

**Comment by mattyza** [comment]
Please do re-open this if you encounter any issues when doing this.
