### ISSUE TITLE
Always fails capturing in JPY

### ISSUE THREAD

**Issue by fumikito** [woocommerce/woocommerce-gateway-stripe#363]
When option is set `capture` as `no`, capturing request always fails. Because amount is 10 times bigger than charge request. I guess below is the code:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/woocommerce-gateway-stripe.php#L467

You should check currency code here.

Here is my screen shots.

![charge-request](https://user-images.githubusercontent.com/84587/30910648-95d6001e-a3c0-11e7-8233-98e188edce18.png)

![amount-100times](https://user-images.githubusercontent.com/84587/30910653-9b2a231a-a3c0-11e7-9dcc-0188e030d38d.png)

**Comment by roykho** [comment]
This is already fixed in 4.0 branch which you test here https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0
