### ISSUE TITLE
Missing amount with different currency.

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce-gateway-stripe#365]
Our store accepts multiple currencies. The issue doesn't happen with US Dollar. 

Here is what the total amount customer should have paid: (130.76)

![screen shot 2017-09-28 at 12 32 28 pm](https://user-images.githubusercontent.com/2909982/30979086-91253ae6-a44a-11e7-8491-ad14b071fe15.png)
![screen shot 2017-09-28 at 12 32 33 pm](https://user-images.githubusercontent.com/2909982/30979085-911da09c-a44a-11e7-8591-71c507eb57a6.png)

This customer was from Italia. We supposed he used Euro. This also happened with Paypal.

But We only received 104.96

![screen shot 2017-09-28 at 12 34 40 pm](https://user-images.githubusercontent.com/2909982/30979239-22c01fa2-a44b-11e7-93a2-66a8299a2860.png)

**Comment by mattyza** [comment]
Hi @kevin25 - what method are you using to offer multi-currency support on your store?

There may be an issue in there.

**Comment by kevin25** [comment]
@mattyza  I'm using the add-one from the theme. They have new update and I'm monitoring it.

**Comment by mattyza** [comment]
@kevin25 - thanks. This doesn't sound like something we can support within the Stripe gateway, and would best be handled by the multi-currency method you're using.
