### ISSUE TITLE
Display charged amount in the order note.

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce-gateway-stripe#366]
#### Affected ticket(s)

N/A

Found this will be helpful when there are other fees or discounts that affect order total. Consider following order items:

<img width="1369" alt="screen shot 2017-09-29 at 9 57 20 am" src="https://user-images.githubusercontent.com/78313/30999162-9b7deb7e-a4fd-11e7-8849-4d9ccd4f2e5f.png">

As a merchant, I need to go to Stripe's dashboard to verify the charged amount.

Currently, the order note only displays something like:

```
Stripe charge complete (Charge ID: ch_xxx)
```

It'd be helpful to display the charged amount as well.

#### What I expected

It'd be helpful to display the charged amount as well. Maybe a simple addition like:

```
Stripe charge ($58,00) complete (Charge ID: ch_xxx)
```

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@gedex so the total is already shown in the screen you showed. Isn't that representation of what Stripe charged? Or are you saying people get confused between the `Order Total` and `Order Total after Funds used` ?

**Comment by gedex** [comment]
Order total in the edit screen might be updated over time like from adding/removing fee, refund, etc. The charged transaction that happens in Stripe at particular time is not, so if store owner wants to see charged amount by Stripe, which appears in order note, they need to go to Stripe dashboard to get that.

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/pull/527
