### ISSUE TITLE
[4.0] Webhook handler not charging receiver sources (e.g. Bitcoin)

### ISSUE THREAD

**Issue by thorsten-stripe** [woocommerce/woocommerce-gateway-stripe#367]
For Bitcoin we're setting the order status to on hold[0] while we wait for the source to become chargeable (funds arriving in the receiver), however in the webhook handler we are ignoring orders where the status is `on-hold` causing Bitcoin sources to never be charged[1].

I'd propose something like

```
$not_pending_receiver = ( 'on-hold' === $order->get_status() && 'receiver' != $notification->data->object->flow );
		try {
			if ( 'processing' === $order->get_status() || 'completed' === $order->get_status() || $not_pending_receiver ) {
				return;
			}
```

Or do you have an idea for a more efficient way of doing this?

[0] https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.0.0/includes/payment-methods/class-wc-gateway-stripe-bitcoin.php#L397-L398
[1] https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.0.0/includes/class-wc-stripe-webhook-handler.php#L123-L125

**Comment by roykho** [comment]
Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0
