### ISSUE TITLE
Hide Apple Pay for WooCommerce Pre-order products

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce-gateway-stripe#368]
Stripe Apple Pay doesn't yet support WooCommerce Pre-orders.  Orders that should charge upon release of the pre-order are charged upfront.  Can we hide the Apple Pay button when the pre-order is set to upon release, or hide Apple Pay altogether on pre-order products? 

![](http://cld.wthms.co/iwc4xy+)
http://cld.wthms.co/iwc4xy+

**Comment by roykho** [comment]
Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0
