### ISSUE TITLE
[4.0] Deprecate Stripe.js V2

### ISSUE THREAD

**Issue by thorsten-stripe** [woocommerce/woocommerce-gateway-stripe#369]
@roykho we just released a payment request button within Stripe.js V3 which encapsulates ApplePay.js as well as the payment request API for in-browser stored card details and Android Pay[0]. 

With the new release can we please use this new Element so we can deprecate any dependencies to Stripe.js V2?

[0] https://stripe.com/docs/elements/payment-request-button

**Comment by roykho** [comment]
In 4.0 branch.
