### ISSUE TITLE
Refund amount rounded due to "number of decimals" setting instead of actual charge amount

### ISSUE THREAD

**Issue by webster** [woocommerce/woocommerce-gateway-stripe#370]
#### What happened

When viewing an order that totaled $1234.56 after tax, the WooCommerce admin area (wp-admin/WooCommerce/Orders) displayed the order as $1235; it rounded up because the “Number of decimals” setting in WooCommerce was set to zero. When clicking “Refund”, WooCommerce submitted the refund to Stripe in the amount of $1235.00, which of course caused an error:

`"message": "Refund amount ($1,235.00) is greater than charge amount ($1,234.56)",`

This plugin should always refund the actual charged amount and ignore any front-end rounding/decimal settings.

#### Steps to reproduce the issue

1. Place order that is not an even decimal amount
2. Ensure WooCommerce "number of decimal" settings is set to zero
3. View order in wp-admin
4. Attempt to refund order
5. Observe error message

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

WordPress 4.8.2, Plugin 3.2.3

**Comment by roykho** [comment]
Hi @webster Are you saying Stripe rounds it before processing or are you saying WooCommerce does this? If so, perhaps this should be opened on WooCommerce repo?

**Comment by roykho** [comment]
Tested this to be a non issue. This will only happen if you had orders that had decimals and later you changed the decimals to say zero and tried to refund after the fact.
