### ISSUE TITLE
Enhancement: Add Bookings compatibility with Apple Pay

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce-gateway-stripe#371]
Right now Apple Pay only works with Simple and Variable products.  We've seen requests from users to add compatibility with other product types, specifically Bookings.

**Comment by seb86** [comment]
I put a [pull request](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/394) that should give any extension with its own product type the ability to support it.

**Comment by mikeyarce** [comment]
@seb86 I don't think that will be enough for Bookings, because of how the product type works.

**Comment by rossviviano** [comment]
Requested here: https://www.olark.com/transcripts/pDEretR4ke2uMj0U3W3JT0O03JEbAaN1

**Comment by roykho** [comment]
Closed in favor of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/566
