### ISSUE TITLE
Stripe Payment Request API interacts with Chrome Autofill

### ISSUE THREAD

**Issue by ValeDeOro** [woocommerce/woocommerce-gateway-stripe#373]
Reported in [forum](https://wordpress.org/support/topic/woocommerce-support-ticket-page-script-error/): 

When enabling the option “Stripe Payment Request API” in the Stripe settings, the autofill in Chrome 61 will kick in when the Checkout button on the Cart page is clicked…

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by RavanH** [comment]
Here's a screen print from a cart page (in French) with the browser dialog that comes up after hitting the Checkout button. The dialog is asking for missing info and choices to make such as which address and pre-configured payement method to use... While at that stage, the Stipe checkout option has not even been selected yet!

This does not happen in Firefox where it just moves on to the checkout page.

![schermafdruk van 2017-10-06 09-12-50](https://user-images.githubusercontent.com/1184853/31266938-94b76472-aa76-11e7-8a15-97107e7d348a.png)

**Comment by roykho** [comment]
That is correct behavior. When PaymentRequest is enabled, it will default to using that if available and will popular the payment sheet with info that is stored on your Chrome browser

**Comment by RavanH** [comment]
Yes, but the point is that the user has to go through this motion to be able to get to the next step where he then might not even wish to choose Stripe as payment method... Kind of annoying, no? Should this not be happening when a buyer actively chooses Stripe?

**Comment by roykho** [comment]
In 4.0.0, there will be a separate button in cart to choose to continue with checkout or with Payment Request.

**Comment by RavanH** [comment]
Sounds like an excellent improvement :)
