### ISSUE TITLE
Not redirecting after deposit payment via Woocommerce Deposits

### ISSUE THREAD

**Issue by karlmt** [woocommerce/woocommerce-gateway-stripe#374]
#### What I expected

When customer places an order using the deposit option the payment is taken but the customer is not redirected to the thank you page. 

When the customer pays in full it works fine. 

#### What happened instead

Customer is left hanging on the checkout page and is making multiple payments

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
I was not able to replicate your issue on my end. I would suggest you open an issue ticket on woocommerce.com so someone can help you troubleshoot the issue.
