### ISSUE TITLE
Upgrade to newer Stripe API version?

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce-gateway-stripe#375]
#### Affected ticket(s)

It was a chat.

#### API update request

The user contacted Stripe related to the version number of the API. Their Stripe account gave an error notice with the request to update their API version. After contacting Stripe, Stripe told them that a lot of changes had been made since the last version that Woo is using (API version 2015-04-07).

This is part of Stripe's reply:

> I've taken a good look at your account and I can see that you're running API version 2016-03-07 with WooCommerce plugin version 3.1.2. and that everything looks fine. There have been a good number of updates since version 2016-03-07, however, if you decide that they aren't hugely importance to you then there's no pressing need to update your API! You can check out those changes here: https://stripe.com/docs/upgrades#api-changelog

Especially the "There have been a good number of updates since version 2016-03-07" seems to suggest it's time for our extension to maybe consider an update as well. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Hi Job. Already done in 4.0.0 which is in beta now

**Comment by jobthomas** [comment]
Perfect. Thanks.
