### ISSUE TITLE
Notice overload on activation

### ISSUE THREAD

**Issue by warrendholmes** [woocommerce/woocommerce-gateway-stripe#376]
#### What I expected

After activating Stripe (done automatically through the onboarding wizard), Stripe adds 3 notices - https://cloudup.com/c0kxZM1QDwM

That's overkill when I've just started my store - it would be useful to only display the information about activation and (only if absolutely necessary) show the other notices **after** I've added credentials.

#### Steps to reproduce the issue

Activate Stripe.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Those are already removed ( apple pay/payment request ) in 4.0 which is coming out soon.
