### ISSUE TITLE
Feature request: list ordered items in stripe transaction note

### ISSUE THREAD

**Issue by galbaras** [woocommerce/woocommerce-gateway-stripe#377]
In order to keep track of business income, I print the Stripe transactions related to orders. If that printout also had the items ordered, I wouldn't have to cross reference this to the WooCommerce order and everything would be in one document.

If this is a feature of the Stripe API, can ordered items be added to the transaction as a note?

**Comment by roykho** [comment]
You can do that via this filter `wc_stripe_payment_metadata`

**Comment by galbaras** [comment]
Is it too much trouble to have it as a setting? Please?
