### ISSUE TITLE
Stripe Gateway Payment not tested with Woocommerce version 3.2

### ISSUE THREAD

**Issue by ateliersimon** [woocommerce/woocommerce-gateway-stripe#378]
Hello,

I updated my Woocommerce to version 3.2, and I discover that Stripe Gateway Payment is apparently not tested with this version of Woocommerce. I proceed to test a payment, and I didn't see any problems. But the warning still show up. 

Is it normal ? 

Thank you,

Simon

**Comment by roykho** [comment]
It has been tested but the check feature is newly added so we just haven't updated the Stripe plugin yet in anticipation of version 4.0 coming out soon.
