### ISSUE TITLE
Expiration date changes and Meta missing in Stripe dashboard when using Apple Pay

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce-gateway-stripe#383]
#### Affected ticket(s)

663143-zd-woothemes

#### What I expected

When using Apple Pay the recorded expiration date ( year ) changes in the Stripe dashboard; however, the payment is accepted as expected. Also the _Customer Name_ and _Customer Email_ as no longer passed in the **Metadata** section.

**Using Apple Pay:**
<img width="410" alt="keuosv" src="https://user-images.githubusercontent.com/2876178/31896497-8d385920-b7d9-11e7-9367-b2575ddb20e3.png">

**Using Stripe Credit Card:**
<img width="364" alt="0sadqd" src="https://user-images.githubusercontent.com/2876178/31896450-6b5ee828-b7d9-11e7-8632-bb092260d4c0.png">

#### Steps to reproduce the issue

1. Setup Apple Pay and confirm card's actual expiration date.
2. Make a purchase using Safari from a desktop.
3. Log into Stripe dashboard and confirm payment's recorded data.

The data in the dashboard should reflect a date different than an the actual date printed on the card. For the two cards I've tested only the year of the expiration date is incorrect.

It's also reported that the _Country_ field under the **Card** section returns the United States and invalid zip code regardless of the actual zip and country attached to the card. I do not have a method to confirm this but maybe you could look into this further.

Again, the payment processes as expected. The issue is only regarding the data that is recorded in the Stripe dashboard.

Thanks!

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@johndcoy Ok so here is the explanation from Stripe about the discrepancies on the credit card.

> The reason why you're seeing this discrepancy between the saved credit card in the ApplyPay Wallet and what's being displayed in the Dashboard is because ApplePay sends info for a virtual card. It's expected that it won't match the actual card.

> That is, because you're using ApplePay for this, a new card object will be created each time. Any time new card details are used to check out - a new card object is also created. Because Apple pay works by masking the original credit card information and creating new unique payments details each time it is used, new card objects are subsequently created in Stripe as well.

> This means the 'origin' you're seeing is the generated virtual card's origin. 

Rest of the issue you mentioned is not an issue in 4.0 so we can disregard them.
