### ISSUE TITLE
Apple Pay not compatible with Smart Coupons

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-gateway-stripe#384]
#### Affected ticket(s)

737572-zd-woothemes

#### What I expected

That any Smart Coupon created with its `Store Credit/Gift Certificate` "Discount Type" would work with Apple Pay to discount that amount from the order total.

#### What happened instead

Apple Pay isn't currently compatible with anything but the three standard WooCommerce coupon "Discount Types" s listed here: http://docs.woocommerce.com/document/coupon-management/ (Percentage discount, Fixed cart discount, Fixed product discount).

The additional coupon type of `Store Credit/Gift Certificate` added by the [Smart Coupons](https://www.woocommerce.com/products/smart-coupons/) extension doesn't work to discount the total when paying with Apple Pay.

Changing any Smart Coupon `Store Credit/Gift Certificate` "Discount Type" back to a default type it then works fine.

Smart Coupon `Store Credit/Gift Certificate` coupon:
![http://cld.wthms.co/0GIcTN](http://cld.wthms.co/0GIcTN+)

![http://cld.wthms.co/eTGxVC](http://cld.wthms.co/eTGxVC+)

Using a default coupon "Discount Type":
![http://cld.wthms.co/GWMaAL](http://cld.wthms.co/GWMaAL+)

![http://cld.wthms.co/T2A3Za](http://cld.wthms.co/T2A3Za+)

#### Steps to reproduce the issue

1. Install and Setup Apple pay
2. Install and Setup Smart Coupons
3. Create any "Store Credit/Gift Certificate" coupon type
4. Add products to cart, apply discount, try to pay with Apple Pay

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by Luminus** [comment]
Howdy @roykho, just checking if we have any movement on this or feedback that would be useful for the user.

**Comment by roykho** [comment]
Hey @Luminus - probably won't be anytime soon.

**Comment by Luminus** [comment]
Thanks for the heads up @roykho.

**Comment by roykho** [comment]
Closed in favor of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/566
