### ISSUE TITLE
Order: Payment fails - missing source/token

### ISSUE THREAD

**Issue by heichel** [woocommerce/woocommerce-gateway-stripe#385]
# Affected ticket(s)

#712933

# What I expected

#### *(Stripe 4.0.0-beta)*
When checking out, payment meta and source (token) should be transmitted to stripe via the payment API. Stripe should then process the payment and return the details.

# What happened instead

The payment source (token) seems to be missing in the API request body. Stripe is declining the payment with the error *'Must provide source or customer'*. See screenshots.

# Steps to reproduce the issue

- Install latest version of Wordpress, WooCommerce and Stripe Gateway (by 24.10.2017).
- Provide Stripe API Keys (test or live keys) and activate 'Stripe Checkout'.
- Choose a product and try to checkout via credit card. 
- Receive error *'Payment processing failed. Please retry.'*.
- Check log (in Stripe account) for details.

# My system

#### Installation
WC Version: 3.2.1
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔

WooCommerce Stripe Gateway: von WooCommerce – 4.0.0-beta-1
WooCommerce: von Automattic – 3.2.1

#### Server
Server Info: Apache
PHP Version: 7.0.24
PHP Post Max Size: 16 MB
PHP Time Limit: 300
PHP Max Input Vars: 1500
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.20
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

# Screenshots

#### Working payment (Stripe 3.x)
![screenshot-2017-10-23 test dashboard 1](https://user-images.githubusercontent.com/30001239/31992159-cee13670-b979-11e7-8f4a-0e7b01cadf7e.png)

#### Failed payment (Stripe 4.0.0-beta)
![screenshot-2017-10-23 test dashboard](https://user-images.githubusercontent.com/30001239/31992181-e0357332-b979-11e7-80eb-66e18157c582.png)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Please provide more information such as the settings you have in your Stripe. What other plugins you're using. What theme are you using...etc.

**Comment by heichel** [comment]
Hi roykho! I'm using the Storefront theme on the test installation. There are no other plugins installed, it's a blank wordpress installation just for test purpose. Those are the stripe settings:

![screenshot-2017-10-25 woocommerce einstellungen test buchungssystem wordpress](https://user-images.githubusercontent.com/30001239/32023404-769ef1ae-b9d9-11e7-8de3-ca41e94a5d29.png)

On my live system I'm using a self-developed theme and a few other plugins, but as the error occurs on both systems, I think that doesn't make a difference. Please tell me what other informations I can provide you with.

**Comment by roykho** [comment]
So according to your settings, you're using the modal popup and you're typing in your test credit card there in the popup box?

**Comment by heichel** [comment]
I am using the modal popup, but with 4.0.0-beta, it doesn't even open. Page is just jumping up to the error when clicking the pay now button.

**Comment by roykho** [comment]
Well that would explain it. If you have the popup enabled, you can only use that to checkout. You can no longer use the fields that are embedded on your checkout form. The fact that it doesn't open is another matter though which I am not able to reproduce. I would suggest you look at your browser console to see if there are any errors.

**Comment by heichel** [comment]
I think I didn't state that correctly. I tried both:

- Activating the modal, just clicking pay now as there are no credit card fields
- Deactivating the modal and filling out the credit card fields with test data, then clicking pay now

In both cases the error occurs. Obviously, I don't fill out a credit card field when the modal is activated (as it's not shown).

**Comment by roykho** [comment]
When is the last time you download 4.0? If it is more than a week or two ago, I would suggest you do it again as active development is going on. Also as stated previously, please show your console to see if there are errors.

**Comment by heichel** [comment]
I'm using the latest commit. I found something in the console though. A same-origin policy seems to block the connection to stripe somehow.

*m.stripe.network/inner.html#url=https%3A%2F%2Fbdev.(...)&muid=d1ec0(...)5804e2&preview=false:1 XMLHttpRequest cannot load https://m.stripe.com/4. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://m.stripe.network' is therefore not allowed access. The response had HTTP status code 499.*

Do you think that has something to do with the error? I tested multiple devices and browsers, same issue.

**Comment by roykho** [comment]
It could be related to your host/domain. Are you running behind a proxy or any security items running on these hosts?

**Comment by heichel** [comment]
I don't use a proxy or cdn. The domain is directly linked to my servers ip and secured with a lets encrypt certificate. There's the basic Plesk firewall. I'm using FastCGI served by apache.

I think that's it, what else could be important?

**Comment by roykho** [comment]
Try the public master branch instead of 4.0 and see if that works for you. It could be something in 4.0 that is not compatible with your server.

**Comment by heichel** [comment]
As I stated in the initial comment, the master branch does work fine. I'm using it on the live site and my client successfully receives payments. They need to use SEPA in the future, though. That's why I downloaded the 4.0 beta. So it has to be something that changed in 4.0 that produces the error.

I'd be happy to give you any further information, just tell me what you need.

**Comment by roykho** [comment]
Unfortunately i can't think of anything at this time that would cause this. We have other people actively testing this including Stripe developers themselves and we have not had issues. I will keep an eye out though if I find anything I will post here.

**Comment by roykho** [comment]
Ok one thing came to mind for the beta is `saved cards` which is still using the legacy tokens. It needs to be sources. So for now, turn on `saved cards` and see if that fixes your issue.

**Comment by heichel** [comment]
The workaround does solve it for the moment, thanks!

Another thing I noticed is that it only works with accounts activated for SEPA. I mean that makes sense but even in test mode it just aborts with other accounts and there's no meaningful error message (*Could not find payment information*). Maybe that could be an improvement for the future.

If I can help you with that or with smashing that bug somehow, just tell me. I'd be happy to do so.

**Comment by roykho** [comment]
I am not sure if there is any more specific message that comes back from Stripe about that but I will ask them thanks!
