### ISSUE TITLE
[4.0] Make version 4.0 work locally

### ISSUE THREAD

**Issue by rvola** [woocommerce/woocommerce-gateway-stripe#386]
Hello @roykho

I'm trying to run 4.0.0 (last) locally on MAMP and I can not get it working. I still receive the notification during a test payment: "Payment processing failed.

I even tried using Ngrok to simulate webhooks.

The question is: can we run version 4.0.0 locally as the current version?

**Comment by roykho** [comment]
When did you last download from 4.0? Try download again now and see.

**Comment by rvola** [comment]
Hello @roykho
bravo it works now ;)
