### ISSUE TITLE
Guest Checkout: Stripe payment does not work

### ISSUE THREAD

**Issue by rollsappletree** [woocommerce/woocommerce-gateway-stripe#387]
#### CONFIGURATION 
WP 4.8.2
WC 3.2.1
Stripe plugin version  3.2.3 

Stripe Plugin Configuration:
* Enabled Test Mode
* Enable Capture charge immediately
* Enabled Stripe Checkout
-- disabled bitcoin and apple pay
-- tried with both Enable/Disable Payment via Saved Card

#### What I expected

I expect my guest user being able to purchase my goods with credit card via Stripe even if are not registered on my store.

#### What happened instead

Instead a error is triggered (the wording is really misleading though)
http://screencloud.net/v/sxCS3

The problem is in this code:
http://screencloud.net/v/p1p91

function process_payment
(includes/class-wc-gateway-stripe.php, Line 741)

#### Steps to reproduce the issue
Activate guest checkout, then
simply try to buy something in your store via stripe.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Try deactivating all plugins except WC and Stripe. Then switch your theme to a default theme like Twenty Sixteen. Re-test.

**Comment by rollsappletree** [comment]
Hi @roykho , thanks for having taken in charge this issue.

I'll try, but here the question seems code-related, not coming from any integration with other plugins or theme...
In fact the code states clearly:

```
$order  = wc_get_order( $order_id ); //ok, return my current order id
$source = $this->get_source( get_current_user_id(), $force_customer );

if ( empty( $source->source ) && empty( $source->customer ) ) {
	$error_msg = __( 'Please enter your card details to make a payment.', 'woocommerce-gateway-stripe' );
	$error_msg .= ' ' . __( 'Developers: Please make sure that you are including jQuery and there are no JavaScript errors on the page.', 'woocommerce-gateway-stripe' );
	throw new Exception( $error_msg );

}
```

of course having no user, `get_current_user_id` return 0, thus customer is empty.

**Comment by roykho** [comment]
Hi @rollsappletree so I have tested this and I am able to checkout as a guest both with Stripe Checkout enabled and disabled.

**Comment by evandiamond** [comment]
@roykho I just noticed you closed my ticket and pointed me over here. I've been trying to debug this, I read the comments above and a clean run with no plugins except the few you mentioned on top of TwentySeventeen worked. So then I continued to snoop and noticed jQuery 1.12.4 on TwentySeventeen.

I removed jQuery 3.2.1 which was on my installation, and swapped it for **1.12.4** and this plugin **worked**.

The WooCommerce Gateway plugin does not work with jQuery 3.2.1 - is this something you might be updating soon? Can you take a look into that?

**Comment by roykho** [comment]
@evandiamond I am not too sure what you mean by you removed jQuery. You should always use what comes with WordPress.

**Comment by evandiamond** [comment]
Yes, you are correct. But, I was using an updated version not the default
version.


*Evan*

**Comment by roykho** [comment]
Yeah so just use what comes with WP and all will be right.
