### ISSUE TITLE
Invalid Integer on certain prices when checking out

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce-gateway-stripe#388]
#### Affected ticket(s)
739914-zd-woothemes

#### What I expected

I am not able to check out with some products.  I get the following error:
<img width="587" alt="screen shot 2017-10-26 at 22 01 48" src="https://user-images.githubusercontent.com/3220162/32111610-cecbd074-baef-11e7-84b9-2966a2554532.png">

#### Steps to reproduce the issue

I wasn't able to reproduce this on my own test site, but I did come across someone else who had the same issue: https://wordpress.org/support/topic/invalid-integer-3/

It looks like this is only happening on _LiteSpeed_ servers when the price is rounded with percents.  For example when Tax is added to a number defined to the hundredth percent, it has this error. If tax is 10% and it's a $10 product, the error doesn't happen.  But if you add shipping that costs $9.35, the error then occurs.  It sounds like a LiteSpeed rounding issue, but I don't have a LiteSpeed 
-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by SiR-DanieL** [comment]
@mattyza any update? the customer is asking

**Comment by mattyza** [comment]
@SiR-DanieL - no movement here yet. @roykho - could I bug you to take a look when you have a moment, please?

**Comment by roykho** [comment]
@mattyza sure however I don't have access to LiteSpeed servers to be able to test this. I tried just with my local host but was not able to reproduce nor is Akeda.

**Comment by SiR-DanieL** [comment]
Can we maybe get a test account from LiteSpeed?

**Comment by mattyza** [comment]
@SiR-DanieL  - Litspeed is a server technology (like Apache), rather than a specific hosting company.

Do one of our affected customers perhaps have a staging environment we could use?

**Comment by SiR-DanieL** [comment]
Yes @mattyza, #739914-zen is a staging site (creds in the sidebar).

**Comment by roykho** [comment]
@SiR-DanieL this should be fixed on customer's site. Can you please have customer test this out?

**Comment by roykho** [comment]
Issue resolved.

**Comment by kognito** [comment]
Hi @roykho, could you please let me know how you fixed this? I commented in the Wordpress forum thread linked above, but unfortunately to no avail.

We've been having the same issue for about a year now. The site is currently running on Woocommerce 3.2.5/Wordpress 4.9.1 and the issue as similar to above – some customers can't check out with some products using Stripe, however Paypal will always go through. 

Many thanks in advance for your help!


Cheers
Clemens

**Comment by roykho** [comment]
@kognito This will come in version 4.0 most likely next month.

**Comment by kognito** [comment]
Thanks @roykho for the prompt reply! That's really good to hear.

So it's a known issue and you're already working on a fix? That would be awesome!
