### ISSUE TITLE
[4.0] Card fields responsiveness on mobile

### ISSUE THREAD

**Issue by trilame** [woocommerce/woocommerce-gateway-stripe#390]
Hello,
I'm testing the 4.0 beta to see the new features.

I noticed a new box for entering card information, which I really like, but it doesn't work well on mobile.
I tried with the the Twenty Fifteen, and the fields are overlapping, which makes it uneasy to fill.

With the theme I am actually using, it even worst, as shown on the screenshot

#### What I expected

Easily enter card information on payment page with a mobile device.

#### What happened instead

The space for card number overlaps on CVC, or more.

#### Steps to reproduce the issue

- Theme: Twenty Fifteen
- Simply add a product, proceed payment.

Thank you!

![capture d ecran 2017-10-28 a 20 54 44](https://user-images.githubusercontent.com/19934242/32137567-cc27925c-bc22-11e7-8289-07f4680cdca9.png)
![capture d ecran 2017-10-28 a 20 57 41](https://user-images.githubusercontent.com/19934242/32137568-cc433da4-bc22-11e7-8711-894e874d1f6c.png)

**Comment by roykho** [comment]
I have already notify Stripe about this and unfortunately there is nothing we can do make it more aware. So the only solution I could advise is to use CSS to make the width of that area wider.

**Comment by trilame** [comment]
Well, this is surprising from Stripe: they recommend explicitly this "card" element, but doesn't work well on mobile. I tried myself to get information on this, but doesn't seems to annoy anyone.

Still, I prefer to have a cleaner experience on mobile, so I replaced on your plugin the card element with the other ones (cardNumber, cardExpiry, cardCvc) and stylizing with other examples they provide (as show [here](https://stripe.com/elements/examples)).

Do you think you can consider this option for the plugin?

**Comment by emoed** [comment]
I was having this same issue - can't believe Stripe has not fixed this in nearly 3 years. I figured out a workaround via CSS - am posting here in case it helps others. I made a video of the problem and result of the CSS solution - [https://www.youtube.com/watch?v=_raqY2whGHA](url) 

Below is the CSS which I believe is specific to Woocommerce vs the theme or Stripe:

`/* fix stripe cc/expiry/cvc field overlap on mobile */`

`@media only screen and (max-width: 375px) {`
	`#add_payment_method #payment ul.payment_methods, .woocommerce-cart #payment ul.payment_methods, .woocommerce-checkout #payment ul.payment_methods {padding: 0 !important}`
	
	`#add_payment_method #payment div.payment_box, .woocommerce-cart #payment div.payment_box, .woocommerce-checkout #payment div.payment_box {padding: 0 !important;width:100%}`

       `#add_payment_method #payment div.payment_box::before, .woocommerce-cart #payment div.payment_box::before, .woocommerce-checkout #payment div.payment_box::before {display:none}`

`#add_payment_method #payment ul.payment_methods li, .woocommerce-cart #payment ul.payment_methods li, .woocommerce-checkout #payment ul.payment_methods li {text-align:center !important}`

`.wc-stripe-card-icons-container, .wc-stripe-paymentRequest-icons-container{float:none !important; display:block !important} `   

`}`
