### ISSUE TITLE
Pending Payment Order Status when card is Declined (and missing order notes)

### ISSUE THREAD

**Issue by todditron** [woocommerce/woocommerce-gateway-stripe#392]
#### What I expected
We have four orders with declined cards and would expect order status to be automatically set to `Failed`. (I did a bunch of research on this, and can't tell if this is actually the desired behavior, but seems like if the CC is declined, the order should fail.) 

 In addition, we are flat-out missing order notes for three of the declined card transactions. 

#### What happened instead
All four orders are stuck in `payment pending` status.  Thee of the orders are missing order notes.

#### Steps to reproduce the issue
Here is an example of failed order with `pending payment` status that is also missing order notes
![jd-missing-order-notes](https://user-images.githubusercontent.com/1143370/32208842-bc13a94c-bdca-11e7-8661-3a63ef6a1010.PNG)

And the corresponding transaction in Stripe:

![jd-stripe-order](https://user-images.githubusercontent.com/1143370/32208640-5adb4f64-bdc9-11e7-931d-b9b1b395d7af.PNG)

I did notice that there was not a "official" declined event listed for this transaction in the Stripe dashboard.

#### Notes
- We have processed around 1k transactions successfully, so this is not a systemic problem.  
- The occurrences have been spread over several months, so it isn't just a recent thing.  
- These orders are for subscription products, in case that matters

I apologize if there is something that I am missing conceptually here.  I also realize this could be an issue with this plugin, the WC core, the Subscription plugin or Stripe itself, this just seemed the most directly related.  

Thanks for your help

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Hi @todditron so without having reproducible steps, it would be hard to know exactly what is going on for you however when you get orders that are in pending and with no notes, it usually means Stripe hasn't even gotten the chance to process it. WooCommerce's first order status is pending.

**Comment by todditron** [comment]
Thanks for reviewing this request.  Sorry that I can't provide any steps.  As I mentioned it is pretty rare, and ultimately a fringe case.  

In one of the cases where we did actually get a formal 'declined' note back from Stripe, the order status remained `Payment Pending` instead of converting to `Failed`.  That seems like a bug to me, but perhaps is a feature.  Anyway, something to keep on the radar if anyone else piles on with similar issues.

Thanks again.

**Comment by roykho** [comment]
@todditron you mentioned this only happens when Subscriptions is involved? Does it ever happen with non Subscriptions? Also what version of each plugin are you using?

**Comment by todditron** [comment]
We are only selling subscription products, so we don't have any physical products to compare

The plugins should all be fairly recent.  We built the site in June and have run updates 2 or 3 times since then.  The incidents are spread over several months, so it would take a little digging to figure out what configuration we had at the time of each event, and it would be different for at least half of them.  Ultimately, I am fine with no action if this seems to be an isolated incident and no one else piles on.  I could write a little clean-up cron script that checks for these scenarios and assigns `failed` order status to anything stuck in this `pending payment` state.  So I personally have options for resolution.

However, I do suspect there might be two bugs at play

1. Some scenario in which stripe returns an 'unusual' 402 response that this plugin is not handling (see the second screenshot of the response body)
2. Some scenario in which a declined card is not converted to a failed order. This might not be the full responsibility of this plugin, and may not even be a true bug.  I could see wanting to keep the order status `pending` while the user had an active session, and only convert it to `failed` if the user abandoned their session.  So there is some nuance as to when the order status should be updated, and I could see why this might not happen automagically.

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/aded182f1e230c99e8853c3c94421259540b926d

**Comment by lcrcinc** [comment]
we are experiencing this problem and it is 2 years later.
