### ISSUE TITLE
Expiry issue on Phone

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce-gateway-stripe#393]
#### What I expected

It should automatically add / between MM and YY

#### What happened instead

Customers contacted me about this issue. So I tested on iOS 11.0.3 and it wasn't automatically added. 

#### Steps to reproduce the issue

Go to Checkout on mobile. Click on Pay With Stripe. Type Month and year.

WooCommerce 3.1.2
Stripe 3.2.3

![img_5380](https://user-images.githubusercontent.com/2909982/32283669-6b20d258-befb-11e7-9185-4a8df077d895.PNG)

**Comment by roykho** [comment]
Non issue in 4.0 as the fields are hosted by Stripe.
