### ISSUE TITLE
Stripe Checkout Fails when Guest tries to checkout

### ISSUE THREAD

**Issue by evandiamond** [woocommerce/woocommerce-gateway-stripe#395]
#### What I expected

I expected the unregistered or guest to be able to check out. The "Use a New Payment Method" seems to be causing issues. If a payment type is already saved, it checks out fine.

#### What happened instead
I get a Console error...

```
stripe-checkout.min.js?ver=3.2.3:1 Uncaught TypeError: b.form.unblock is not a function
    at Object.unblock (stripe-checkout.min.js?ver=3.2.3:1)
    at Object.onClose (stripe-checkout.min.js?ver=3.2.3:1)
    at HTMLInputElement.onSubmit (stripe-checkout.min.js?ver=3.2.3:1)
    at HTMLFormElement.dispatch (vendor.js?ver=1.0:1294)
    at HTMLFormElement.q.handle (vendor.js?ver=1.0:1262)
```

#### Steps to reproduce the issue

I have deactivated all plugins except WooCommerce and Stripe WooCommerce Plugin and my Shipping Method plugin. 

When I get to the checkout page, I try to checkout by selecting "Use a new payment method". When I click "Continue to Payment" I guess the above error. 

https://www.dropbox.com/s/29t1i6etdsmbqi0/Screenshot%202017-11-04%2000.32.02.png?dl=0

I am running the latest version of WordPress, WooCommerce and the Gateway Stripe plugin.

Please help.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Duplicate #387
