### ISSUE TITLE
Feature Request: Add get_headers() function and hook to v3

### ISSUE THREAD

**Issue by JulienMelissas** [woocommerce/woocommerce-gateway-stripe#396]
Hello!

I am working on a plugin (which I hope to open source after tested and working) that extends the functionality of this plugin and allows the usage of Stripe's [direct charges](https://stripe.com/docs/connect/direct-charges#collecting-fees) via Stripe Connect. The idea is that the site administrator (of a single site or multisite) could charge an application fee and take a non-refundable percentage or fixed fee off the top of each transaction.

So I'm using the `wc_stripe_generate_payment_request` hook and using that to calculate the `application_fee` key that Stripe requires. Problem is, I need to now modify the headers sent in the code [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/10f2d59b8f0d3b7bf80555f838b72908c9944498/includes/class-wc-stripe-api.php#L61-L64) in `WC_Stripe_API::request()`.

It looks like in the v4 branch folks have already thought of this, and provide a hook called `woocommerce_stripe_request_headers` [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.0.0/includes/class-wc-stripe-api.php#L81-L85).

I guess what I'm wondering is: if it's going to take more than a few weeks for v4 to come out, is it possible to add the `WC_Stripe_API::get_headers()` and hook functionality into a small feature release of this plugin? **I'm happy to write a PR.**

Thanks so much!

**Comment by roykho** [comment]
Hello, no ETA as of yet but it will not be likely we will do any point releases until 4.0 is out.

**Comment by JulienMelissas** [comment]
...so I assume that immediate close is a no on adding it beforehand? and you would just recommend me modify the plugin code? (I try as much as possible to not modify). Thanks.
