### ISSUE TITLE
Android 'scan new card' feature inconsistency

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#397]
#### Affected ticket(s)
Live chat report

#### What I expected
There is an android feature which detects CC fields and allows the user to use their camera to 'scan' the card. When this is done, I would expect the expiration year to be two digits as prompted by the input.

https://productforums.google.com/forum/#!msg/chrome/9CdW4uF_3BE/LbZE5rtnAgAJ

#### What happened instead
The scanned expiry date inserts a 4 digit year - screenshot here: https://imgur.com/a/KM65Y

#### Steps to reproduce the issue
Use an android device and the 'scan new card' feature. 

I have asked the person who reported this in live chat to monitor and respond if needed to this issue.

-------------------

- [ ] Issue assigned to next milestone.
- [x ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Thanks for the report however this is not something we can change/control in the upcoming 4.0. The field is generated/validated by Stripe. But I do think it should work when that comes out because just in my test of copy/paste, it automatically formatted it to two digit for me.
