### ISSUE TITLE
Memberships: "Change Payment" Updated But Card Not Used For Renewals

### ISSUE THREAD

**Issue by amlcreative** [woocommerce/woocommerce-gateway-stripe#400]
Using WooCommerce 3.1.2, Wordpress 4.8.3, WooCommerce Memberships 1.9.1, and WooCommerce Stripe Gateway 3.2.3

**Steps to Reproduce**
- View an active membership within My Account (one that has a pending renewal).
- From My Account click on Payment Methods then click on Add Payment Method
- Provide the a new credit card via stripe
- Click Add Payment Method
- New card is set as default
- Expected Result

**New credit card is added to the stripe customer record**
- Stripe Card ID metadata within the parent subscription is updated to the new Stripe card ID
- Future renewals will be charged against the new credit card.

**Actual Result**
- New credit card is correctly added to the stripe customer record
- The metadata in the parent WooCommerce subscription is not updated with the new Stripe card ID
- Default card still set to new card
- Future renewals continue to be attempted against the previous credit card
- When attempting to change payment again, the new card now appears within the list of potential cards. However, selecting that card still does not update the metadata or change future renewals.

Thanks for your help.

**Comment by roykho** [comment]
I think that is the expected behavior. Unless there is a "change payment" function within Memberships. Subscriptions have that function.

**Comment by roykho** [comment]
Closing for now due to lack of activity. Feel free to add/reply if necessary.
