### ISSUE TITLE
Add Alipay to payment options. 

### ISSUE THREAD

**Issue by tenzinngodup** [woocommerce/woocommerce-gateway-stripe#401]
#### Affected ticket(s)

Alipay is enabled by stripe, but plugin currently doesn't support it. 

#### What I expected
Feature to enable skype payment. 

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Already in 4.0

**Comment by tenzinngodup** [comment]
perfect! Any plan to add WeChat in future release?
