### ISSUE TITLE
'Invalid positive integer' JS alert when refund amount is left empty

### ISSUE THREAD

**Issue by jnachtigall** [woocommerce/woocommerce-gateway-stripe#402]
Using Stripe (my own Visa for testing against live keys) I wanted to do a Refund in the WooCommerce backend but forgot to enter the number to be refunded:

![image](https://user-images.githubusercontent.com/3307404/32736508-edf56dd8-c897-11e7-8077-d690fdbed6cd.png)

This resulted in the above popup (using Firefox 58). Instead there should be a user friendly warning when the refund amount is accidentically left empty.

After entering the right amount (here 5,40 €) it worked.

Using current latest stable plugin version.

**Comment by roykho** [comment]
Hello, thanks for the report however this not controlled by the payment gateway. WC handles what is filled in the field and then passes it to the payment gateway for processing.
