### ISSUE TITLE
Enhancement: Validate CVC when buying using a saved card

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce-gateway-stripe#404]
We've received a few customer suggestions/complaints saying they'd prefer a bit more security with saved cards.

Considering each store is different and we always save the cards for all orders, it would probably make sense to make this new feature optional.

Most stores offering such validation, would request the CVC before a new transaction is made. Some (like Amazon) will only do this if the shipping address changes, but this would complicate this enhancement.

My suggestion would be to add a new option on the settings and when activated, show an CVC input field when a saved card is selected on checkout. The CVC should then be validated with Stripe.r.

For automatic payments (subscriptions) this enhancement should have no effect.

**Comment by laurendavissmith** [comment]
Moved to the ideas board for further evaluation, http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/34518673-validate-cvc-when-buying-using-a-saved-card
