### ISSUE TITLE
Order status changed to 'On Hold' on failed renewal after payment method update

### ISSUE THREAD

**Issue by NickGreen** [woocommerce/woocommerce-gateway-stripe#405]
#### Affected ticket(s)

Internal Prospress customer ticket. Feel free to reach out to us for ticket details.

#### What I expected

When a failed renewal retry fails, order should be set only to `pending payment` then `failed`, as in this screenshot:
![](https://cldup.com/5EUyAksHYj.thumb.png)

This would trigger only the `failed order` emails, as seen here:
![](https://cldup.com/P0Q-br7AeG-3000x3000.png)

#### What happened instead

Order is changed to `on hold`, then `pending payment` then `failed` as shown in this screenshot:
![](https://cldup.com/LNVlHF4lwZ.png)

This means that the `new order` emails are also sent out, which is a problem and causes confusion:
![](https://cldup.com/dEJbTVRf7p-3000x3000.png)

#### Steps to reproduce the issue

We have reproduced on customer live site, customer staging site, and locally on a test site with:
- WooCommerce 3.2.4
- Stripe 3.2.3
- Subscriptions 2.2.15

How to reproduce:

1. ​Turn on Subscriptions failed payment retry and put Stripe in test mode
2. Purchase subscription product with 4242424242424242 card # 
3. Change payment method to 4000000000000341 (test credit card # for failure) and run renewal (fails as expected)
4. Change payment method to 4242424242424242
5. Change payment method back to 4000000000000341 and run renewal retry scheduled action(fails, but also changes to incorrect order status momentarily) 👎 
6. Order status is changed to 'on hold', then 'pending payment' and then to 'failed.' Note the unusual "Stripe charge authorized" note: https://cloudup.com/ctkIqF-NTLH
7. This means that the 'new order' emails are triggered erroneously, causing confusion: https://cloudup.com/ctKApLi8ezc

____

Customer duplicated with these steps. I'm including the full detail, in case it helps:

1. Go to [customer site redacted] and buy a product, with 4 Payment Plan Payment method. Put your registration info and press "Add to cart"
2. On cart page Proceed to chackout
3. On Checkout page enter test credit card data: 4242424242424242, with expiry 12/20 and cvc 222.
4. Accept the terms & conditions on the bottom and press "Place Order". As a result, product has been purchased successfully.
5. Considering that I had to test recurring payment with expired credit card data, then I went to /my-account/
6. On "Payment methods", I added another credit card data, with card number 4000000000000341 (test credit card data for failure), with 11/21 and 111 as expiry date and cvc.
7. I made new credit card data as default and deleted previous used one, with 4242424242424242 card number. In this way, I managed to reproduce the case which we had on the live site: when recurring payment triggered, card was declined.
8. Considering that my subscription number is 5287, I went to Tools->Scheduled Actions and I manually triggered pending subscription payment (now with credit card data for failure)
9. As a result, recurring payment was failed and admin got just one, correct email about failed recurring payment.
10. Considering that our customer got new credit card (because his previous one was expired), he went to my-account page and added his new credit card data and made that as default. So, to reproduce that, I went to /my-account/ and added the correct credit card data 4242424242424242 and made that one as default one and deleted the wrong one.
11. I went to the failed renewal order within admin dashboard and triggered "Retry renewal payment" manually. Order was set as completed and subscription was set to Active again.
12. The next month we had a situation when customer credit card was OK, but with insufficient funds. So, to reproduce that, I had to add test credit card data for failure (4000000000000341) once again and set it as default.
13. Once again I manually trigger pending recurring payment within Tools-> Scheduled Actions.
14. As a result, admin got two emails, one for "New Subscription Renewal Order" and second one for "Automatic payment Failed".

The problem is that order statuses are set as within screen shot (see attachment).

I think you will be able to reproduce this. Maybe there is an easier way to reproduce this, but this was my way. In real life what happened is that:

1. Customer did initial purchase for subscription product
2. After few months his credit card was expired, so recurring payment was failed
3. He added new credit card data within my-account page and set it as default
4. Admin triggered "Retry Renewal Payment" for failed order and it ended as completed, with subscription set as active.
5. After one month, the same customer had insufficient funds on his new credit card data, so recurring payment/renewal order failed.
6. As a result, admin got two emails, "New Subscription Renewal Order" and "Automatic payment Failed" emails.

____

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Closed ref #247
