### ISSUE TITLE
Issue after upgrading Stripe to 4.0 beta

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce-gateway-stripe#406]
I can't see any menu. I also got these error:

> PHP message: PHP Warning:  include(): Failed opening 'settings-stripe.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /home/domain/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 421
PHP message: PHP Warning:  array_map(): Argument #2 should be an array in /home/domain/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php on line 61
PHP message: PHP Warning:  array_map(): Argument #2 should be an array in /home/domain/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php on line 61
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/domain/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php on line 295" while reading response header from upstream, client: 107.152.98.163, server: thewholesaletshirts.com, request: "GET /wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "thewholesaletshirts.com"
2017/11/22 04:19:27 [error] 14608#0: *36857 FastCGI sent in stderr: "PHP message: PHP Warning:  include(settings-stripe.php): failed to open stream: No such file or directory in /home/domain/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 421
PHP message: PHP Warning:  include(settings-stripe.php): failed to open stream: No such file or directory in /home/domain/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 421
PHP message: PHP Warning:  include(): Failed opening 'settings-stripe.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /home/domain/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php on line 421
PHP message: PHP Warning:  array_map(): Argument #2 should be an array in /home/domain/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php on line 61
PHP message: PHP Warning:  array_map(): Argument #2 should be an array in /home/domain/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php on line 61
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/domain/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php on line 295" while reading response header from upstream, client: 107.152.98.163, server: thewholesaletshirts.com, request: "GET /wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "thewholesaletshirts.com"

<img width="1318" alt="screen shot 2017-11-22 at 4 18 19 am" src="https://user-images.githubusercontent.com/2909982/33149690-a2c2f534-cf9e-11e7-93d7-10ac26163f3e.png">

Do I need to compile it with composer?

**Comment by roykho** [comment]
No issues here. I suggest you recheck if you have uploaded all the files to your server and that you're using Stripe RC-1 and not Beta.

**Comment by kevin25** [comment]
I use wget to download it from 4.0.0 brand and unzip it on server. I don't think there were missing files but i will check it again tonight. Thank you!

**Comment by mattyza** [comment]
@kevin25 - it's also worth checking the directory names in use. It may be that WordPress is looking for `woocommerce-gateway-stripe`, while the code is at `woocommerce-gateway-stripe-4.0.0`.

**Comment by kevin25** [comment]
I moved its name to woocommerce-gateway-stripe. It seemed to be messed with permission. I had to chown the correct owner and it worked. Thank you!
