### ISSUE TITLE
Don't allow Statement Descriptor of more than 22 chars

### ISSUE THREAD

**Issue by robin-scott** [woocommerce/woocommerce-gateway-stripe#407]
#### What I expected

Client had an issue with statement descriptor not showing up despite being entered into the Stripe settings under Settings > Checkout > Stripe.

#### What happened instead

Descriptor was showing as "Stripe" in customer card statements. Descriptor client had used was 24 chars long (included 2 spaces).

Stripe has a maximum length of 22 chars for descriptor, as described here:

https://stripe.com/docs/connect/statement-descriptors

#### Steps to reproduce the issue

Install woocommerce + Stripe gateway, add a descriptor of more than 22 chars and save.

Proposed solution is:

a) max length of 22 chars on the "Statement Descriptor" input
b) Mention 22 char limit in the tooltip alongside
c) Bonus points for mentioning this full statement, which all would be helpful! `Statement descriptors are limited to 22 characters, cannot use the special characters <, >, ', or ", and must not consist solely of numbers.`

Can fire up a PR on this later. Please note that this alone is not the sole root cause of the "Stripe" showing as descriptor in this case... Stripe itself also does not restrict the length of descriptor so that set for the account could not replace it.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by robin-scott** [comment]
Glad I added this end bit as my client has now informed me they were using a special character in their payment descriptor until recently... So its just the "don't allow more than 22 chars" in this input part - and also the tooltip (or actually rejecting the invalid input).

**Comment by roykho** [comment]
Thanks for great feedback. This is implemented in 4.0

**Comment by robin-scott** [comment]
Wow quick. Was prepared to do this when my Black Friday Cyber Monday list is empty... :|
