### ISSUE TITLE
Refunded amount is not reflected in "Net Revenue From Stripe" custom field

### ISSUE THREAD

**Issue by lawkwok** [woocommerce/woocommerce-gateway-stripe#408]
#### What I expected

For our store, orders are placed On-hold, and Completed only after we ship. Sometimes order totals change from what was original captured. An example would be when customer finds a coupon code and ask us to apply it after the order was placed.

I expect refunds from the coupon code to be reflected in the "Net Revenue From Stripe" custom field.

#### What happened instead

The Net Revenue From Stripe value shows the original, non-discounted, order total.

#### Steps to reproduce the issue

1. Say a customer places an order whose total is $130.
2. I apply a coupon code to the order. The order total is now $110.
3. When the order is complete, the meta data saved to the order is the original, non-discounted amount New Revenue From Stripe (i.e. $130 - Stripe fee)

Going into the Stripe dashboard, you can see there is an "amount_refunded" key in the payment capture POST response body, so the data is definitely there.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Hello,

How do you apply discount after the order is made?

**Comment by lawkwok** [comment]
Using the "Apply coupon" button on the edit order screen.

**Comment by roykho** [comment]
Can you please show me a screenshot of that?

**Comment by roykho** [comment]
Ok I see what you mean only when on-hold you are able to apply the coupon after the transaction. This is not available unfortunately as you can't change it after the fact. However you can do a refund and I would suggest you use that method but you have to wait until 4.0 release as the updated fee/net is implemented in 4.0

**Comment by lawkwok** [comment]
Even marking the order as complete and refunding does not update "Net Revenue From Stripe" with the current version of this plugin. I look forward to v4.0
