### ISSUE TITLE
Apple pay losing shipping address and names under load.

### ISSUE THREAD

**Issue by cdesewell** [woocommerce/woocommerce-gateway-stripe#409]
Hi all

My Woocommerce store gets a large number of orders with missing shipping information (names and addresses) from Apple Pay orders. I can't recreate the steps to produce the problem as it only seems to occur in production and there is no clear common denominator other than they are all apple pay orders. Our site runs in AWS in an elastic beanstalk with a CloudFront CDN. Has anyone else experienced an issue like this when their store is under load?

**Comment by roykho** [comment]
Hi,

In the future could you please post your support questions here https://wordpress.org/support/plugin/woocommerce-gateway-stripe This is a place to open repeatable bugs with steps for replication.

I would suggest you include every detail stating with your system status, paste it here. You can get to it via menu woocommerce->status.

**Comment by lawkwok** [comment]
I also have issues with the shipping country, state/county, and city being dropped for Apple Pay orders.

Furthermore, very often the country dropdown is not selected. When this happens, the State/County field shows the abbreviation of the shipping state. As soon as I select the appropriate country from the dropdown, the State/County becomes the correct 

![screen-shot-2017-11-28-at-8 40 33-am](https://user-images.githubusercontent.com/11021583/33332224-85ad6db6-d418-11e7-9fba-a1047a6fad53.jpg)

**Comment by roykho** [comment]
@lawkwok Apple Pay doesn't work with Canada addresses or UK address ( perhaps more ) when certain shipping methods are used.

**Comment by cdesewell** [comment]
@roykho can you point me to a detailed explanation/documentation of this limitation?

**Comment by roykho** [comment]
@cdesewell I am not sure if your issue is same as @lawkwok as you didn't provide any details but for more explanation, you would have to contact Apple Pay.

Closing this for now as it is not something we can fix on our side.

**Comment by cdesewell** [comment]
@roykho I have supplied system details. Does this gateway perform any order validation based on addresses?

**Comment by roykho** [comment]
@cdesewell no it does not. WC handles that once it process the order. As mentioned thus far, I've only seen this issue when shipping is enabled and the shipping address is either in the UK or Canada.
