### ISSUE TITLE
Remove "New Feature" banners for Apple Pay and Web Payments API

### ISSUE THREAD

**Issue by pmaiorana** [woocommerce/woocommerce-gateway-stripe#410]
The banners for Apple Pay and Web Payments support should probably be removed in a release in the near future as they're no longer "new":

http://cld.wthms.co/Il2Hk

**Comment by roykho** [comment]
They should already been removed. Where are you seeing that in 4.0 branch?

**Comment by pmaiorana** [comment]
Oh, cool! I just saw it with the current release and hadn't realized it was already on someone's radar :) Closing.
