### ISSUE TITLE
Credit card payments rejected (4.0.0-rc1)

### ISSUE THREAD

**Issue by bettinafj** [woocommerce/woocommerce-gateway-stripe#412]
Plain credit card payments are rejected. Other payment gateways like GIROPAY work.

When I check the log from Stripe I see following:

![github](https://user-images.githubusercontent.com/34143708/33457833-1b10be0a-d624-11e7-90bf-99c92c8fc8be.PNG)

So payment and currency seems to be null?

- When I replace the plugin with the latest from master (3.x) - the payment works!
- Giropay and other payment gateways do work!

Using latest WP and woocommerce 3.2.5

`
### WordPress Environment ###

Home URL: https://www.fjella.world
Site URL: https://www.fjella.world
WC Version: 3.2.5
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.23
PHP Post Max Size: 130 MB
PHP Time Limit: 300
PHP Max Input Vars: 16000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.5
WC Database Prefix: mod453_
MaxMind GeoIP Database: ❌ Die MaxMind GeoIP Datenbank existiert nicht - Die Ortung (Geolokalisierung) wird nicht funktionieren. Du kannst sie manuell installieren von http://dev.maxmind.com/geoip/legacy/geolite/ zu dem Pfad: . Scrolle einfach nach unten bis zu "Downloads" und lade die Datei "Binary / gzip" vom Typ "GeoLite Country" herunter. Denke bitte daran
die Datei GeoIP.dat.gz zu entpacken und nur die entpackte Datei GeoIP.dat hochzuladen.

Datenbank-Gesamtgröße: 18.81MB
Datenbank-Datengröße: 17.40MB
Datenbank-Indexgröße: 1.41MB
mod453_woocommerce_sessions: Daten: 0.05MB + Index: 0.02MB
mod453_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
mod453_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB
mod453_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.05MB
mod453_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB
mod453_woocommerce_order_itemmeta: Daten: 0.06MB + Index: 0.06MB
mod453_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB
mod453_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB
mod453_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
mod453_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB
mod453_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
mod453_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
mod453_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
mod453_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
mod453_commentmeta: Daten: 0.02MB + Index: 0.03MB
mod453_comments: Daten: 0.08MB + Index: 0.09MB
mod453_failed_jobs: Daten: 0.02MB + Index: 0.00MB
mod453_gdbc_attempts: Daten: 0.02MB + Index: 0.02MB
mod453_links: Daten: 0.02MB + Index: 0.02MB
mod453_mailchimp_carts: Daten: 0.02MB + Index: 0.00MB
mod453_options: Daten: 2.11MB + Index: 0.13MB
mod453_postmeta: Daten: 7.20MB + Index: 0.38MB
mod453_posts: Daten: 7.14MB + Index: 0.14MB
mod453_queue: Daten: 0.02MB + Index: 0.00MB
mod453_termmeta: Daten: 0.02MB + Index: 0.03MB
mod453_terms: Daten: 0.02MB + Index: 0.03MB
mod453_term_relationships: Daten: 0.02MB + Index: 0.02MB
mod453_term_taxonomy: Daten: 0.02MB + Index: 0.03MB
mod453_tinvwl_items: Daten: 0.02MB + Index: 0.00MB
mod453_tinvwl_lists: Daten: 0.02MB + Index: 0.00MB
mod453_usermeta: Daten: 0.06MB + Index: 0.03MB
mod453_users: Daten: 0.02MB + Index: 0.05MB
mod453_wpgmza: Daten: 0.02MB + Index: 0.00MB
mod453_wpgmza_categories: Daten: 0.02MB + Index: 0.00MB
mod453_wpgmza_category_maps: Daten: 0.02MB + Index: 0.00MB
mod453_wpgmza_maps: Daten: 0.02MB + Index: 0.00MB
mod453_wpgmza_polygon: Daten: 0.02MB + Index: 0.00MB
mod453_wpgmza_polylines: Daten: 0.02MB + Index: 0.00MB
mod453_yoast_seo_links: Daten: 0.06MB + Index: 0.02MB
mod453_yoast_seo_meta: Daten: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 273
custom_css: 1
customize_changeset: 40
flare: 3
foogallery: 2
jetpack_migration: 2
mc4wp-form: 3
nav_menu_item: 27
page: 28
popup: 1
popup_theme: 6
post: 8
product: 7
product_variation: 19
revision: 385
shop_coupon: 3
shop_order: 71
shop_order_refund: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

WPBruiser: von Mihai Chelaru – 3.1.11
Contact Form 7: von Takayuki Miyoshi – 4.9.1
Cookie Notice: von dFactory – 1.2.40
Envato Market: von Derek Herman – 1.0.0-RC2
Jetpack von WordPress.com: von Automattic – 5.5.1
Kirki Toolkit: von Aristeides Stathopoulos – 3.0.16
Loco Translate: von Tim Whitlock – 2.0.16
MailChimp for WooCommerce: von MailChimp – 2.1.2 – Nicht mit der aktiven Version von WooCommerce getestet
MailChimp for WordPress: von ibericode – 4.1.11
Pinterest Pin It Button On Image Hover And After Post & Page Content: von Weblizar – 2.5
Popup Maker: von WP Popup Maker – 1.6.6
Primrose: SiteOrigin Widgets: von SingleStroke – 1.3.2
Safe SVG: von Daryll Doyle – 1.5.3
SingleStroke: Post Formats: von SingleStroke – 1.2.0
Page Builder by SiteOrigin: von SiteOrigin – 2.5.16
SiteOrigin Widgets Bundle: von SiteOrigin – 1.11.2
WooCommerce Stripe Gateway: von WooCommerce – 4.0.0-rc-1 – Nicht mit der aktiven Version von WooCommerce getestet
German Market: von MarketPress – 3.5.1 – Nicht mit der aktiven Version von WooCommerce getestet
WooCommerce Google Analytics Integration: von WooCommerce – 1.4.3 – Nicht mit der aktiven Version von WooCommerce getestet
WooCommerce: von Automattic – 3.2.5
Yoast SEO: von Team Yoast – 5.8
WP Fastest Cache: von Emre Vona – 0.8.7.4
WP Google Maps: von WP Google Maps – 6.4.06
WP Instagram Widget: von Scott Evans – 2.0.0
WP Retina 2x: von Jordy Meow – 5.2.0
YITH WooCommerce Order Tracking: von YITHEMES – 1.1.3 – Nicht mit der aktiven Version von WooCommerce getestet

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #16 - /shop/
Warenkorb: #504 - /cart/
Kasse: #18 - /kasse/
Mein Konto: #19 - /mein-konto/
Geschäftsbedingungen: #732 - /agb/

### Theme ###

Name: Primrose Child
Version: 1.0.0
Author URL: http://singlestroke.io/
Child Theme: ✔
Parent Theme Name: Primrose
Parent Theme Version: 1.3.5
Parent Theme Author URL: http://singlestroke.io/
WooCommerce Support: ✔

### Templates ###

Overrides: primrose-child/woocommerce/emails/admin-new-order.php
primrose-child/woocommerce/emails/customer-completed-order.php
primrose-child/woocommerce/emails/customer-new-account.php
primrose-child/woocommerce/emails/customer-note.php
primrose-child/woocommerce/emails/customer-on-hold-order.php
primrose-child/woocommerce/emails/customer-processing-order.php

`

**Comment by roykho** [comment]
When submitting a bug report, please paste your WooCommerce system status we we may know more about your setup.

**Comment by bettinafj** [comment]
Thanks! Did it!

**Comment by roykho** [comment]
First thing I would try to change the theme to default WP theme and see if that works. If not, then turn all plugins off except WC and Stripe re-test.

**Comment by crudolf** [comment]
Hi, I am seeing the same issues here. Using version 3 of this plugin, credit card payment works, using 4 it doesn't. Will provide more information soon, maybe related to german locale.

**Comment by roykho** [comment]
@crudolf same answer for you as well. Please try to change the theme to default WP theme and see if that works. If not, then turn all plugins off except WC and Stripe re-test.

**Comment by crudolf** [comment]
You are correct about an incompatibility with a plugin. The plugin name is:

https://marketpress.de/shop/plugins/woocommerce-german-market/

If installed credit card payment does not work. However the plugin is compatible with 3.x branch.

**Comment by roykho** [comment]
@crudolf have you contacted them to see if they added any particular support for WooCommerce Stripe for 3.x.x versions and if so, perhaps they can do the same for 4.0? If not, can you pass me the latest plugin and I will take a look. Just tell me the exact setup I need to use to replicate the problem. roy.ho [at] automattic [dot] com

**Comment by crudolf** [comment]
The plugin adds an additional confirmation page to the payment process. So, after entering stripe data, there is an additional page showing all entered data. This is required because of some special german laws. 

I guess because of this split the "stripe_source" POST parameter is variable empty. I expect another answer from the plugin creators (unfortunately this is not a free plugin, but costs about 90$ per year so I cannot send you a copy of it) by the end of the day. 

However you can definitely set up a clean wordpress, install:
- woocommerce
- german market plugin
- woocommerce-gateway-stripe 4.0

And buy anything. The payment using credit card will fail.

**Comment by roykho** [comment]
@crudolf So I am unsure about that specific plugin as I don't have a copy of it however I did test another free plugin and it works fine. Plugin in question https://wordpress.org/plugins/woocommerce-germanized/

**Comment by crudolf** [comment]
@roykho Thanks for for your effort!
I will double check whether this plugin would be sufficient to use. I am also waiting for feedback from the mentioned plugin above.

**Comment by crudolf** [comment]
OK i got the reason: The plugin is printing the required parameter into hidden-POST fields:

> <input type="hidden" name="stripe_source" value="{\"id\":\"YYY\",\"object\":\"source\",\"amount\":null,\"client_secret\":\"XXXX\",\"created\":1512470365,\"currency\":null,\"flow\":\"none\",\"livemode\":false,\"metadata\":{},\"owner\":{\"address\":{\"city\":\"asdf\",\"country\":\"DE\",\"line1\":\"asdf asdf\",\"line2\":\"\",\"postal_code\":\"79111\",\"state\":\"\"},\"email\":\"ASDF\",\"name\":\"asdf asdf\",\"phone\":\"+adsf\",\"verified_address\":null,\"verified_email\":null,\"verified_name\":null,\"verified_phone\":null},\"statement_descriptor\":null,\"status\":\"chargeable\",\"type\":\"card\",\"usage\":\"reusable\",\"card\":{\"exp_month\":12,\"exp_year\":2034,\"address_line1_check\":\"unchecked\",\"address_zip_check\":\"unchecked\",\"brand\":\"Visa\",\"country\":\"US\",\"cvc_check\":\"unchecked\",\"funding\":\"credit\",\"last4\":\"4242\",\"three_d_secure\":\"optional\",\"tokenization_method\":null,\"dynamic_last4\":null}}" />

If this hidden field is submitted only "{\" is the value of 'stripe_source' and everything fails.

As you can see the quotes are wrongly encoded. I fixed this by doing some hack special to this variable (replacing \” with some special character like "!" and doing the reversal before decoding). Then everything works smooth. 

However 2 questions remains open here:

1. In the previous version there was only a key provided, so no plain data was sent into hidden fields. Can this be changed?

2. Can sending plain information be a security flaw, since the client_secret can be seen in the form? Or is this client secret not the oriigina

Thanks in advance!

**Comment by crudolf** [comment]
The hack I am using from now is to encode the stripe_source using base64 and decoding before using.

**Comment by roykho** [comment]
@crudolf so the client_secret is not the same as your secret key so no real issue there. And also Stripe doesn't work without SSL so all communication should be already encrypted.

However thinking about this more, we don't actually need all the information given to us by Stripe in the source object so perhaps we can streamline this. We can technically keep `stripe_source` as just the source ID like we had in 3.0 version and generate separate hidden inputs of items we still need to pass. Perhaps that may be cleaner. Just thinking out loud.

**Comment by crudolf** [comment]
Yes, that would be the awesome! 

I think if only the id is provided, it should be the least errorprone for other plugins to interact.  Unfortunately I am not able to do a PR for this. However shall I create a new ticket for this?

**Comment by roykho** [comment]
No need, already looking into it.

**Comment by crudolf** [comment]
Just a note: I saw you reduced the data to be transferred (for the other ticket, I know). But the problem remains. You have reduced the amount of transferred data, but since its a JSON object, the serialization is a problem, if it is sent through HIDDEN fields. 

Just a note. Thanks

**Comment by roykho** [comment]
@crudolf yeah unfortunately after looking into this more there are too many fields to add and some of them are dynamic and may or may not exist so sending it in one field combine is the proper way to go. Perhaps the real issue is looking at why the posted json fails when using the German Market plugin. You mentioned it returns only `{/` for you?

**Comment by roykho** [comment]
@crudolf just to give you heads up, I've made the changes to use only the source ID and thought about retrieving the source AFTER it hits the server so I have all the source info I needed. See if the master branch will work for you.
