### ISSUE TITLE
Issue #247 not solved for the new versions of WooCommerce Stripe gataway plugin

### ISSUE THREAD

**Issue by majdagithub** [woocommerce/woocommerce-gateway-stripe#414]
Issue #247 is not fixed for the newest version of Stripe plugin. See #405 issue as well (I am a customer who opened a ticket). @roykho  added a fix, but his fix is within "compat" folder that do not exist within the newest version of Stripe plugin. How to fix this issue within newest version of Stripe plugin?

**Comment by roykho** [comment]
Please wait for 4.0 to be release.

**Comment by majdagithub** [comment]
OK, thank you.
