### ISSUE TITLE
Feature: Support Amex Checkout

### ISSUE THREAD

**Issue by offenb** [woocommerce/woocommerce-gateway-stripe#415]
Add support for Amex Checkout 

see https://stripe.com/amex-express-checkout

https://stripe.com/docs/amex-express-checkout

**Comment by kevin25** [comment]
Any update on this feature?

**Comment by laurendavissmith** [comment]
Moved to the ideas board for further evaluation, http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/34518667-support-amex-checkout
