### ISSUE TITLE
Feature: Block moving to Processing when Stripe fails to capture charge

### ISSUE THREAD

**Issue by joelwills** [woocommerce/woocommerce-gateway-stripe#422]
#### Affected ticket(s)

Live chat, for discussion

#### What I expected

User moves order from On-hold to Processing, but when Stripe fails to capture the payment (error with expiry date or whatever) the order stays on Processing. The change of status is successful making it appear the payment was successful. 

#### What happened instead

The user believes that when an order fails to capture, the order should not move to Processing and return to On-hold.

This would signal a problem.

However I can't think of anything that blocks a store admin from changing the status to whatever they want them to (that would cause a lot of problems). 

On the other hand it would be useful to know that the payment has failed and not to ship the item instead of successfully moving to Processing and appearing to be successful (unless you pay close attention). A trigger could possibly move the order back to On-hold if payment is not captured, or a warning message could appear?

Thanks!

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
This won't be an issue in 4.0.

**Comment by joelwills** [comment]
@roykho In what way? As in, 4.0 will block moving to Processing if it fails to capture?

**Comment by roykho** [comment]
@joelwills if it fails to capture the order will go into payment failed status.

**Comment by joelwills** [comment]
Thanks Roy
