### ISSUE TITLE
Missing Shipping Cost

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce-gateway-stripe#423]
I forked the latest version, compiled it. I tested it with Chrome Payment Request and found out that the Shipping method was missing

<img width="508" alt="screen shot 2017-12-11 at 13 14 24" src="https://user-images.githubusercontent.com/2909982/33849503-d2786478-de7e-11e7-8348-a5a8075d57e4.png">

<img width="1661" alt="screen shot 2017-12-11 at 11 39 09" src="https://user-images.githubusercontent.com/2909982/33849590-11caec18-de7f-11e7-83f0-1ddb6f92d928.png">

Can you avoid using DOM HTML. It's hard for us to customize it with out theme.

<img width="555" alt="screen shot 2017-12-11 at 13 06 55" src="https://user-images.githubusercontent.com/2909982/33849641-3077160a-de7f-11e7-9f32-6c98dca0f5eb.png">

**Comment by roykho** [comment]
Its not missing, you have to first select shipping address.

**Comment by kevin25** [comment]
Thank you. How about the error on the second picture?

**Comment by roykho** [comment]
Not getting that on my end. Perhaps you need to refresh your copy?

**Comment by kevin25** [comment]
I did but till got the same error. 
I also faced with the DOM HTML and can't style the Chrome Payment request as expected.

**Comment by roykho** [comment]
Try deactivating all plugins except WC and Stripe and change your theme to default WP theme. Re-test.

**Comment by kevin25** [comment]
Thank you for your suggestion. I'll test it after Christmas. I rolled it back to the beta version.

**Comment by kevin25** [comment]
Regarding to DOM HTML and style. Can you please make them easier for us to customize it? Once the Chrome Payment Request and Apply appear, everything is in mess and hard to customize them with themes.

**Comment by roykho** [comment]
Sorry that is not control by this plugin.
