### ISSUE TITLE
Order:  Order Creation in Admin, Logged in Admin Email Used to Create Token Stipe

### ISSUE THREAD

**Issue by jtw372** [woocommerce/woocommerce-gateway-stripe#424]
#### What I expected

When creating a manual order (logged in an using admin) the customers email address should be used as token in Stripe transaction.

#### What happened instead

Admin's email (logged in Admin for example) who is creating the order is sent to Stripe and used in transaction.

#### Steps to reproduce the issue

1.  Login to Woocommerce store as admin
2.  Click "Woocommerce > Orders > Add Order"
3.  Fill out customer shipping and billing information (use actual customer's or different email address than the admin email).
4.  Add items 
5.  Create Order.
6.  Click "Customer Payment Page" (located just above Order Status box)
7.  You should then be directed to /checkout page for that order
8.  Select radio button for Stripe and then "Continue to Payment" button
9.  Stripe box pops up where you enter customer credit card details.  You will notice that the entered customers email address is not showing under the store name..it shows the logged in admin's email.
10.  Submit payment
See steps 8-10
![2017-12-11_17-18-10](https://user-images.githubusercontent.com/6796078/33857354-41dabc0c-de99-11e7-847e-c44f009495e7.png)

Next, go to Stripe and look at the payment.  You will notice that the customer contact information will successfully show in the "meta data" section.  However, when you look at the "card" section, it shows the logged in admin's (who created the order) email address next to the transaction details.

See this screenshot to see information in stripe:
![2017-12-11_17-17-17](https://user-images.githubusercontent.com/6796078/33857366-4c5b02ae-de99-11e7-9fa4-2a8dccb97fa2.png)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by jtw372** [comment]
Okay, let me take a look

**Comment by jtw372** [comment]
edited and added screenshots

**Comment by jtw372** [comment]
Another screenshot to clarify "manual order through admin"
![2017-12-11_17-42-14](https://user-images.githubusercontent.com/6796078/33857680-ac7c4aca-de9a-11e7-8fc8-aa652af03f49.png)

**Comment by roykho** [comment]
Thanks for reporting. Fixed in Stripe 4.0.

**Comment by jtw372** [comment]
That's great.  Do you know when I can expect the update to be published?

**Comment by roykho** [comment]
No hard ETA at this time sorry.

**Comment by jtw372** [comment]
Okay, thanks for the assistance.  Just a FYI, Woocommerce as zero idea that this is a known issue with a fix due.  I was told that manual orders using Admin is not common and I should simply logout and use the front-end.
