### ISSUE TITLE
Card info (Address and name) not sent to Stripe - Can't do Street and Zip check

### ISSUE THREAD

**Issue by formosattic** [woocommerce/woocommerce-gateway-stripe#426]
#### Affected ticket(s)

840305-zen

#### What I expected

To have card address details passed along to Stripe, so that it can do the  Street check and Zip check.

Here's how it looked on an old transaction where the address details were passed on to Stripe:

<img width="324" alt="screen shot 2017-12-14 at 17 08 32" src="https://user-images.githubusercontent.com/15944096/33984110-7805dd3e-e0f1-11e7-8e56-d2c5b31d523b.png">
<img width="813" alt="screen shot 2017-12-14 at 17 07 57" src="https://user-images.githubusercontent.com/15944096/33984118-7a9c2774-e0f1-11e7-8810-ff9d2395c47b.png">

#### What happened instead

Tested on WooCommerce 3.2.6, with Stripe 3.2.3 (no other plugins running, using Storefont):

- Card address info sent
- Card name sends email address 

<img width="313" alt="screen shot 2017-12-14 at 17 05 38" src="https://user-images.githubusercontent.com/15944096/33984033-31813c8c-e0f1-11e7-8c48-c03a1fd306bd.png">
<img width="849" alt="screen shot 2017-12-14 at 17 06 33" src="https://user-images.githubusercontent.com/15944096/33984039-3639c74e-e0f1-11e7-954e-d8cfb9bc015c.png">

#### Steps to reproduce the issue
- enable test mode in Stripe
- run a test purchase with all required checkout fields filled-out

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by formosattic** [comment]
Hold on this. Will do additional testing!

**Comment by dougaitken** [comment]
This only happens with the "Stripe Checkout" option (as @formosattic found out in their testing).

Useful for search ability for future queries though!

cc @formosattic @spraveenitpro

**Comment by formosattic** [comment]
Thanks @dougaitken.

Some complementary information gathered from the WordPress.org forum ([#](https://wordpress.org/support/topic/woocommerce-is-not-passing-address-info-to-stripe/#post-8682091), [#](https://wordpress.org/support/topic/how-do-i-send-billing-and-shipping-address-to-stripe/#post-8424723)):

- Stripe Checkout doesn't pass on the address by default (by design from Stripe)
- for those who still want to force the address to be passed, it can be done by adding the following to the child theme’s functions.php file: 
`add_filter( 'wc_stripe_checkout_require_billing_address', '__return_true' );`
- but note that having customers re-enter address info can cause bad experience resulting in possible cart abandonment, hence the reason why address fields aren't implemented in the modal popup
