### ISSUE TITLE
[4.0.0] Stripe Elements: No way to style element fields?

### ISSUE THREAD

**Issue by am3000** [woocommerce/woocommerce-gateway-stripe#427]
With Stripe Elements you should be able to use your own custom elements and styles,
but from what I´ve seen in the code, this is all hard coded in stripe.js

How to apply custom fields and styles then?

**Comment by roykho** [comment]
There are filters for that https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.0.0/includes/class-wc-gateway-stripe.php#L577-L578
