### ISSUE TITLE
Blank Screen When clicking Payment Methods in WooCommerce My Account

### ISSUE THREAD

**Issue by poolet08** [woocommerce/woocommerce-gateway-stripe#431]
#### What I expected

Screen should load and show the payment methods a customer has on file.

#### What happened instead

The page does not load fully. Please see attached files. Here is the error:

[19-Dec-2017 22:40:38 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Invalid or missing payment token fields.' in /var/www/travelingmailbox.com/wp-content/plugins/woocommerce/includes/data-stores/class-wc-payment-token-data-store.php:37
Stack trace:
#0 /var/www/travelingmailbox.com/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(157): WC_Payment_Token_Data_Store->create(Object(WC_Payment_Token_CC))
#1 /var/www/travelingmailbox.com/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php(201): WC_Data_Store->create(Object(WC_Payment_Token_CC))
#2 /var/www/travelingmailbox.com/wp-content/plugins/woocommerce-gateway-stripe/woocommerce-gateway-stripe.php(546): WC_Data->save()
#3 [internal function]: WC_Stripe->woocommerce_get_customer_payment_tokens(Array, 16332, 'stripe')
#4 /var/www/travelingmailbox.com/wp-includes/class-wp-hook.php(286): call_user_func_array(Array, Array)
#5 /var/www/travelingmailbox.com/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#6 /var/www/travelingmailbox.com/wp in /var/www/travelingmailbox.com/wp-content/plugins/woocommerce/includes/data-stores/class-wc-payment-token-data-store.php on line 37

Note: This does not happen with every customer. For some customers the payment methods page loads fine. For others, it does not.
![mikewhitescreen](https://user-images.githubusercontent.com/34723732/34228832-23395886-e5a0-11e7-9fdd-783361983e3d.jpg)

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
This is usually due to an incompatible theme or plugin. Please check those first.

**Comment by poolet08** [comment]
Hi Roy,


If thats the case, why would it work for some customers and not others?


Travis G. Poole

President, Traveling Mailbox

Affiliate Program Coordinator


Direct Line: 919-897-2081

Sales & Support: 855-749-1737

Email: Support@TravelingMailbox.com

________________________________

**Comment by roykho** [comment]
When you have a theme or plugin that requires scripts to load, some taking lots of resources will take time and if your server is not up to it or the connection with the person using the form is not speedy enough, will cause other scripts down the chain to have issues such as not being able to generate the token field. Or some type of error causing the field to not create in the first place.

**Comment by poolet08** [comment]
Okay thanks Roy. We will investigate further.


Travis G. Poole

President, Traveling Mailbox

Affiliate Program Coordinator


Direct Line: 919-897-2081

Sales & Support: 855-749-1737

Email: Support@TravelingMailbox.com

________________________________
