### ISSUE TITLE
[4.0.0] 3DSecure source chargeable webhook hanlder

### ISSUE THREAD

**Issue by cosmass** [woocommerce/woocommerce-gateway-stripe#433]
Hello!

I was just taking a look at the code to review your 3DSecure implementation on 4.0.0, since It would be great to have it on WC. I noted something worth to mention.

After a 3dsecure source is created, and the user redirected to the issuer bank for authorization, the next step would be to wait for the source to be updated to "chargeable" on stripe's servers. As far as I know, that should be accomplished by handling incoming webhooks notifications, with source.chargeable

However, I fail to understand the logic of the webhook handler for source.chargeable:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.0.0/includes/class-wc-stripe-webhook-handler.php

```php
public function process_webhook_payment( $notification, $retry = true ) {
    // The following 2 payment methods are syncronous so does not need to be handle via webhook.
    if ( 'card' === $notification->data->object->type || 'three_d_secure' === $notification->data->object->type || 'sepa_debit' === $notification->data->object->type ) {
        return;
    }
    ...
```

Is this correct? Shouldn't this notification be used to send the final charge request? Or is it handled in some other way?

Official doc (Step 5: Charge the Source)
https://stripe.com/docs/sources/three-d-secure#charge-request

Thanks for your time & work..!
Regards

**Comment by roykho** [comment]
Hello,

According to the docs it is synchronous and we get results right away seen here ![](http://cld.wthms.co/uKcRAn+) So we implemented it as such. Another words we don't use webhooks for it. Although now thinking about it, what if customer pays after logging in to their bank and closes the browser after that.

**Comment by cosmass** [comment]
Hi @roykho, thanks for getting back. 

You are right, docs say that 3dsecure payment is synchronous. But they are talking about the last request, the "charge" request in the end. That request is synchronous in a sense that stripe always respondsto the charge request, with a fail or succeed payment.

However, we are talking about the previous step. The transition of the source to "chargeable", after the users succesfully (or not) authenticates at their bank website, and its redirected back to the merchant store. That process is NOT synchronous! See below the main two reasons to use the hooks, one being the "closed browser" you mentioned:

> Once the customer has authenticated the payment, the source’s status transitions to chargeable and it can be used to make a charge request. **This transition happens asynchronously and may occur after the customer was redirected back to your website.**
> 
> Customers may also assume that the order process is complete once they have completed the 3D Secure authentication flow. **This can result in the customers closing their browser instead of completing the redirection back to your app or website.**
> 
> **For these reasons it is essential that your integration rely on webhooks** to determine when the source becomes chargeable in order to create a charge. Please refer to our best practices for more details on how to best integrate payment methods using webhooks.

Let me know if I can help
Thanks!

**Comment by roykho** [comment]
Have you tested this? In my testing, albeit in test mode, 3D secure always comes back to me right away as `chargeable` and the plugin will handle it right away instead of waiting for the webhook. Are you seeing something different from your test?

**Comment by cosmass** [comment]
Hi @roykho, I did not test it, sorry, just looking at the code. 

We already integrated stripe sources on our custom platform a few months ago. The workflow we used to get it working with 3dsecure was something like this:

1. Redirect the user to their bank website
2. Wait for the webhook that tells us that the source has transitioned to "chargeable".
3. When the hook is received, we make the final charge request. Stripe answers with the final succeed or fail response. Then we update our application accordingly, mark payment as succeed, send emails... etc

Happening at the same time, the user was redirected back from the bank site to our own website, but we dont do anything, he is kept waiting in our website with a message of "Your payment is being processed, please, wait a few seconds". Client browser keeps polling our app with JS, until the payment is marked as succeed or failed by the webhook handler. At that moment, the user is redirected to the succeed or fail endpoints of our app.

Regards!

**Comment by roykho** [comment]
Yeah so in our implementation when customer is redirected to the site, it processes the charge then.

**Comment by tschaeff** [comment]
@roykho it would be good to also listen to the webhook to catch customers who don't successfully return back to the page. Our classification as synchronous means that the charge request will succeed or fail synchronously (no charge pending) however since the source activation happens within the redirect listening to source.chargeable is recommended.

**Comment by roykho** [comment]
Yup I agree hence this is still open.

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/16d42724cf8556dfad77f1de2062fa02a989e839
