### ISSUE TITLE
Apple Pay button doesn't work on Single Product pages

### ISSUE THREAD

**Issue by showwayer** [woocommerce/woocommerce-gateway-stripe#434]
Hi all,

I just enabled Apple Pay on my site and found the Pay button doesn't work on single product pages. It works on Cart page and Checkout page though.

With a few simple debug lines in "class-wc-stripe-apple-pay.php" file, it appears to me the subtotal and total amounts are set to "0" from json response in generate_apple_pay_single() function, causing the amount pending on Apple Pay screen and timed out eventually.

Below are my plugin & theme versions:

WordPress: 4.8.4
WooCommerce: 3.2.6
WooCommerce Stripe Gateway: 3.2.3
StoreFront Theme: 2.2.5

I disabled all other plugins to ensure there is no plugin conflict before reporting this issue.

Does this issue occur on your sites too?

**Comment by roykho** [comment]
No issues here. What is the URL to your site?

**Comment by nburch** [comment]
Same issue here. Bump.

**Comment by whpcreative** [comment]
Yep same here, same result with storefront theme too, on iphone and safari.

**Comment by dougaitken** [comment]
@nburch @whpcreative @showwayer 

can you comment with product page links please to test?

**Comment by roykho** [comment]
Try 4.0 https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0
