### ISSUE TITLE
Order: Unable to refund in Japanese Yen

### ISSUE THREAD

**Issue by valmedia** [woocommerce/woocommerce-gateway-stripe#435]
#### What happened instead

Debug message from Stripe.
{
  "error": {
    "type": "invalid_request_error",
    "message": "Refund amount (¥989,900) is greater than charge amount (¥9,899)",
    "param": "amount"
  }
}

#### Steps to reproduce the issue

Just refund in Japanese Yen and it will fail.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Not seeing any issues with this. ![](http://cld.wthms.co/Ue1mL6+)

Perhaps you changed your currency between charge and refund.

**Comment by websnail** [comment]
roykho... Recommend you look again at your own screenie... There's a disparity between the Y10 refund and the Y1,000 amount refunded.

It looks a lot like the figure is being multiplied by 100 to bounce the decimal point and while I think that's normal for other currencies, isn't Yen different in some way..

I could be missing something here but I thought I'd highlight how it looks from outside the forest.

**Comment by roykho** [comment]
Sorry I should have included more information. This is what Stripe account looks like in the event log ![](http://cld.wthms.co/GYCPed+) So the point being you stated it gives you error when trying to refund. But I am not able to replicate the error you stated and my refunds goes through and the correct amount.
