### ISSUE TITLE
[4.0.0] Order: Mobile Checkout Error

### ISSUE THREAD

**Issue by Ryan-Lai** [woocommerce/woocommerce-gateway-stripe#436]
#### What I expected
User couldn't checkout when they use mobile device with error responses after form submission.

#### What happened instead

After form submission, it displays the error on top of the page and release the mask for users to retype the information again.

#### Steps to reproduce the issue

1. Add any product to the cart on mobile device
2. Process to checkout page
3. Leave some fields like billing address blank
4. Hit Place Order button
5. Display the error messages on top and scroll to top.
6. Form didn't reset the status and remain on mask status

#### Possible resolved conflicts

Fix the stripe.js block function
`block: function() {
			if ( wc_stripe_form.isMobile() ) {
				$.blockUI({
					message: null,
					overlayCSS: {
						background: '#fff',
						opacity: 0.6
					}
				});
			} else {
				wc_stripe_form.form.block({
					message: null,
					overlayCSS: {
						background: '#fff',
						opacity: 0.6
					}
				});
			}
		}`

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Please post your stripe settings.

**Comment by Ryan-Lai** [comment]
![Alt text](https://lh3.googleusercontent.com/DbeXZsf0vRaRB2URpaqRZEngP6BWZyw_QJy-r-iHszvCZ6bd_6BiWg0Domfaj1oYbg3h_PbsKRnOh4RSnN2d=w1920-h849-rw?raw=true "Optional Title")

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/277b5d5cecdfc10b1bde774f6ecd6a40ca045799

**Comment by Liang** [comment]
@roykho This bug can occur when Alipay is enabled, and the required fields are not completed with error state. I think that is something "wc_stripe_form.unblock();" may need to trigger again?

**Comment by roykho** [comment]
@Liang not sure what you mean. Please provide reproduce steps.

**Comment by Liang** [comment]
@roykho 
**Steps to reproduce the issue**

1. Add the item to the cart.
2. Go to checkout page
3. Leave some required fields blank
4. Select the payment method as "Alipay"
5. The overlay blockUI didn't get reset and allow the users to re-fill the form

**Screenshot**
![alipay_error](https://user-images.githubusercontent.com/78797/35133459-2abfb654-fd0b-11e7-8512-198f42f00410.jpg | width=400)

**Comment by roykho** [comment]
@Liang just tested this, no issues for me. Are you using latest 4.0.3 version?

**Comment by Liang** [comment]
@roykho I am stilling using 4.0.2. I just noticed you release the new 4.0.3 today.
Let me try the new version today.

**Comment by Liang** [comment]
@roykho I am still able to reproduce the issue under 4.0.3.
It is weird that Credit Card payment method has been fixed, but not on Alipay.

**Comment by roykho** [comment]
@Liang ok I will look more into this.
