### ISSUE TITLE
Translation bug credit card form ""Credit or debit card"

### ISSUE THREAD

**Issue by florianbepunkt** [woocommerce/woocommerce-gateway-stripe#437]
There seems to be a hard coded translations in the credit card form in v 4.0. The label "Credit or debit card" is in english regardless of language setting. 
<img width="1920" alt="bildschirmfoto 2018-01-09 um 17 50 52" src="https://user-images.githubusercontent.com/8314202/34732551-e58604b4-f565-11e7-85b9-92cfed7b822a.png">

**Comment by roykho** [comment]
If a text appears only in English it means there is currently no translations for it and not that it is hardcoded. You can contribute by going here https://translate.wordpress.org/projects/wp-plugins/woocommerce-gateway-stripe

Most appreciated.

**Comment by oftara** [comment]
I cant find those strings in the translation files, nor in the plugin files. There are such text fields in the WooCommerce translation file, but they are still in English. Any Idea where do these fields come from?

**Comment by PopCornCommunication** [comment]
I just had the support of woocommerce. They said that the sentence "credit card / debit card" is not translatable. We must find a way to do it in functions.php
