### ISSUE TITLE
Apple Pay

### ISSUE THREAD

**Issue by ateliersimon** [woocommerce/woocommerce-gateway-stripe#439]
Hello,

I see two warnings when I update Stripe Gateway to version 4.0 :  
- Before you can start using Apple Pay on the Web, you must first accept Apple's Terms of Service. You can do so through the Stripe Dashboard here: https://dashboard.stripe.com/account/apple_pay.
- The verification of the Apple Pay domain failed. Check the log to see the problem. (Registration must be enabled to view saved logs)

But I don't want to accept ApplePay on my website. Is there a way to remove these warning ?

Thank you,

Simon

**Comment by jyourstone** [comment]
This is probably more of a support issue: https://wordpress.org/support/plugin/woocommerce-gateway-stripe

But you can probably fix this by simply unchecking the box to use Payment Request in Stripe plugin settings.

**Comment by ateliersimon** [comment]
I uncheck the box to use Payment Request, and it solves the issue. Thanks !
