### ISSUE TITLE
Payment API Buttons Do Now Show at Checkout (Enabled in Admin)

### ISSUE THREAD

**Issue by co50** [woocommerce/woocommerce-gateway-stripe#440]
#### Affected ticket(s)

Huh?

#### What I expected

Enabling Payment Request Buttons in 4.0 should make them show at checkout.

#### What happened instead

Only the new Stripe CC fields appear. No payment gateway buttons are to be found anywhere.

#### Steps to reproduce the issue

1) Visit mantispinball.com which uses the new Stripe 4.0 plugin and has the Payment Request Buttons option enabled.  
2) Add something to cart and go to checkout.
3) Observe.

![capture](https://user-images.githubusercontent.com/11934431/34781427-cd628a86-f5f3-11e7-9ada-d5e007e626d5.PNG)
![capture2](https://user-images.githubusercontent.com/11934431/34781428-cd6ec3c8-f5f3-11e7-90b5-4af73497771e.PNG)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
4.0 only shows in cart.

**Comment by co50** [comment]
Notta.
![capture](https://user-images.githubusercontent.com/11934431/34781574-2bb23c9e-f5f4-11e7-8c36-fd8e2e346157.PNG)

**Comment by co50** [comment]
Notta. 
![capture3](https://user-images.githubusercontent.com/11934431/34781603-424332ec-f5f4-11e7-8871-bcd504ee844a.PNG)

**Comment by roykho** [comment]
Check your error logs.

**Comment by co50** [comment]
Wow, what a mess. See attached console errors. These occur even with ONLY the WooCommerce and WooCommerce Stripe plugins activated - everything else disabled. Same errors also occur with both the active theme (Pro) and the Twenty Sixteen theme.

Worse is that the API keys being used are keys for the latest API. I even rolled new ones anyway which begin with the prefixes indicated (the original ones did as well). 
![capture](https://user-images.githubusercontent.com/11934431/34782794-bd6ead2c-f5f7-11e7-8cc5-0673ea4aa135.PNG)

**Comment by co50** [comment]
Turning off "Enable Payment Request Buttons..." causes all of these console errors to vanish.

**Comment by roykho** [comment]
No errors here on my test. Looking at your error it seems its caused by the keys. Then everything else fails after that. Perhaps you have caching? Try clearing the cache. Close the browser and re-open. Re-test.

**Comment by co50** [comment]
Disabled the caching plugin (WP Rocket), used 3 different browsers (Chrome, IE, FF). All do not show the Payment Request buttons but all show the same Console errors with Payment Request buttons enabled. I disabled the feature (if you tested at mantispinball.com, you won't get errors as its now disabled) and will revisit if it gets fixed.

**Comment by co50** [comment]
Upgraded Stripe plugin to 4.0 on two other sites to see if this was isolated. Same issue....no payment request buttons and same console errors.

**Comment by roykho** [comment]
You should deactivate all plugins except Stripe and WooCommerce and change to default WP theme or Storefront and re-test.

**Comment by co50** [comment]
![capture](https://user-images.githubusercontent.com/11934431/34784969-be6ced00-f5fd-11e7-87cc-059c8d007999.PNG)

**Comment by roykho** [comment]
Please link to the site with all plugins deactivated and default WP theme and I will take a look.

**Comment by co50** [comment]
These are live production sites but since you're responding so fast, I've enabled what you've requested for mcgreevygroup.com, for the next 5 minutes.

**Comment by roykho** [comment]
So I still see your key as the issue. `It looks like you're using an older Stripe key. In order to use this API, you'll need to use a modern API key, which is prefixed`

You may want to contact Stripe to see if the keys you're using is correct.

**Comment by co50** [comment]
Not worth the trouble. I already am using the latest API and newly generated keys with 3 different sites/accounts just to be absolutely sure - and they all produce the same errors. I'm just disabling the Payment Request API feature and moving on with my life.

**Comment by roykho** [comment]
You can check my test site here https://royho.ninja

**Comment by co50** [comment]
I don't doubt it works on your test site, and many others - otherwise I assume it wouldn't have been released. But ultimately it needs to work on most sites, right?

However, having see the implementation on your test site and how it confusingly adds the button to Single Product pages, we would have turned it off regardless.  Sorry for the trouble.

**Comment by roykho** [comment]
You can filter it out from showing on single product page. But what I am getting at is this issue is isolated to your sites for some reason.

**Comment by co50** [comment]
OK, good to know. Yeah, wish I could help there. Not sure would could be blocking it. Previous iteration worked perfectly fine (except the issue where payment req api blocked out normal checkout ability). All accounts use the same hosting company, SOAP client is not enabled (but Stripe worked fine w/o it before)...not sure what else.

**Comment by roykho** [comment]
I would suggest you open up a ticket https://woocommerce.com/my-account/tickets/
