### ISSUE TITLE
apple pay not matching correct shipping zone

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#441]
#### Affected ticket(s)
ticket: 877088-zen

#### What I expected
When paying via Apple Pay, for the shipping zone matching to work as it would via normal checkout

#### What happened instead
Seems that post code matching is disregarded and will match for the first country or region based zone.

#### Steps to reproduce the issue
1. 2 shipping zones exist, both for the same country (UK in this case). The one at the top of the list is restricted to a group of post codes, the other is a "catch the rest" type setup.
2. Configure a shipping address in Apple Pay that would not match for post codes configured
3. Press the apple pay button - see that the wrong zone is matched:
![see screen shot](http://cld.wthms.co/D1iqht+)

vs. regular checkout:
![see screen shot](http://cld.wthms.co/L25EKY+)

There is a test case for this set up here: https://wctesting.club/product/woo-logo-3/ and instructions for how to access the dashboard in the ticket sidebar.

-------------------

- [ ] Issue assigned to next milestone.
- [x ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Not able to replicate myself. Is customer using latest 4.0 version?

**Comment by WillBrubaker** [comment]
I know that when the ticket was created the customer was on 3.2.3 - can't say for sure that they are on 4.0 or not now, but it is happening with 4.0 on the test site that I am using.

**Comment by roykho** [comment]
So I did another test again for this today on both Apple Pay and Chrome Payment Request and both worked as expected. Please re-open if we get any new issues for this.
