### ISSUE TITLE
Conflict with Campaign Monitor for WooCommerce 1.3.2 transactions fail

### ISSUE THREAD

**Issue by PaulKaan** [woocommerce/woocommerce-gateway-stripe#442]
#### What I expected

The transaction to complete

#### What happened instead

1. The transaction failed with error message 'Payment Processing Failed. Please Retry'. 2. The order was placed in the backend with a status 'Pending payment'. 3. A failed order email was sent to Store Manager with the message 'Failed order
Payment for order #4777 from Crash Test has failed. The order was as follows:'

#### Steps to reproduce the issue

The stage site was switched to Twenty Seventeen and all plugins were deactivated accept necessary. The error did not occur plugins were added back until the error occurred. The only plugin to create the error was [Campaign Monitor for WooCommerce 1.3.2
](https://wordpress.org/plugins/campaign-monitor-for-woocommerce/)

With the sites Theme activated and all other plugins active the error did not occur. As soon as Campaign Monitor for WooCommerce was activated the error occurred.

Campaign Monitor last updated the plugin 12 months ago and have no roadmap for an update.

The site with the issue is winedecoded.com.au

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by bradydan** [comment]
+1 We have the same issue

**Comment by roykho** [comment]
I see a bunch of errors in the Campaign Monitor plugin just within the settings page. I am not convinced this is an issue with Stripe so closing this for now.
