### ISSUE TITLE
Unable to add new saved cards to my-account page

### ISSUE THREAD

**Issue by spraveenitpro** [woocommerce/woocommerce-gateway-stripe#443]
#### Affected ticket(s)

893574-zen

#### What I expected

Successfully add new saved cards to my-account page

#### What happened instead:

Got an error `You must accept terms and conditions`

![](http://cld.wthms.co/Eqw8t0+)
[Direct Link](http://cld.wthms.co/Eqw8t0+)

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).
@roykho

**Comment by roykho** [comment]
Already fixed.
