### ISSUE TITLE
New owner with empty phone leads to bad request 400

### ISSUE THREAD

**Issue by TSkills** [woocommerce/woocommerce-gateway-stripe#444]
#### Affected ticket(s)

Maybe #391 

#### What I expected

The payment to work with a new owner account and an empty phone number.

#### What happened instead

Bad request (400)
Below is what I can find in stripe log. Please check it out.

>> POST /v1/sources
Version 2017-12-14 (latest)

>> REQUEST BODY (xxxxxxxxxxx for confidential data)
{
  "type": "card",
  "owner": {
    "name": "xxxxxxxxxxx",
    "address": {
      "line1": "xxxxxxxxxxx",
      "line2": "",
      "state": "",
      "city": "xxxxxxxxxxx",
      "postal_code": "xxxxxxxxxxx",
      "country": "FR"
    },
    "email": "xxxxxxxxxxx",
    **"phone": ""**
  },
  "card": {
    "number": "************4444",
    "cvc": "***",
    "exp_month": "10",
    "exp_year": "20"
  },
  "guid": "xxxxxxxxxxx",
  "muid": "xxxxxxxxxxx",
  "sid": "xxxxxxxxxxx",
  "payment_user_agent": "xxxxxxxxxxx",
  "referrer": "xxxxxxxxxxx",
  "key": "xxxxxxxxxxx",
  "pasted_fields": "number"
}

>> RESPONSE (status 400)
{
  "error": {
    "type": "invalid_request_error",
    "message": "You passed an empty string for 'owner[phone]'. We assume empty values are an attempt to unset a parameter; however 'owner[phone]' cannot be unset. You should remove 'owner[phone]' from your request or supply a non-empty value.",
    "param": "owner[phone]"
  }
}

I understand that one should always get owner data from Stripe first, in order to know wether the phone number is vaccant or empty on their side, isnt'it ?

#### Steps to reproduce the issue

Try to pay with a new owner account leaving the phone field empty.

**Comment by roykho** [comment]
Hi @TSkills thanks for reporting. Do you want to give master branch a test to see if this fixes your issues?

**Comment by TSkills** [comment]
Are you thinking about something new in the master branch that could solve the issue ?

I saw on /includes/class-wc-stripe-order-handler.php line 404, that the billing_phone is attended to be a required field, although my form doesn't show it as required, and Stripe allows it to be null.

I think owner[phone] should be removed from the json sent if the field is empty.
