### ISSUE TITLE
Icon enhancement request

### ISSUE THREAD

**Issue by LaurenaRehbein** [woocommerce/woocommerce-gateway-stripe#445]
What I expected: Icons to appear in color as they did in the last version. Instead, these are grey. 

![http://cld.wthms.co/PfvEVI](http://cld.wthms.co/PfvEVI+)
Full Image: http://cld.wthms.co/PfvEVI+ 

![http://cld.wthms.co/yiGjRE](http://cld.wthms.co/yiGjRE+)
Full Image: http://cld.wthms.co/yiGjRE+ 

I understand this is not a bug and documentation is pending, but wanted to note it here after receiving an inquiry.

**Comment by roykho** [comment]
Because of the addition of many other EU payment methods we can't source each icon from different places. We now use a set that contains all seen here https://paymentfont.com/#icons

These are all scalable which was why we're using it. If there were a complete set that was in color, we would have used that however there weren't.

**Comment by LaurenaRehbein** [comment]
Thank you for the clarification, Roy! I've updated the requestor.

**Comment by douglsmith** [comment]
The icons are all in a font now, which can't contain color.

Unfortunately, other payment gateway plugins are still using color icons. So when used together this makes those others stand out more as if the store is featuring some payment methods as a preferred choice even though that is not the intention.

For example, it's common to use Stripe and PayPal together. Now that the Stripe icons are black and white it looks like we're emphasizing PayPal.

I'm using CSS to make the others I use black and white so it's at least somewhat consistent for the customer.

**Comment by LaurenaRehbein** [comment]
Thanks to @roykho the documentation has been updated to include a fix for this: https://docs.woocommerce.com/document/stripe/#section-30

I've written it up as a tutorial here: https://laurena.blog/woocommerce-stripe-4-0-icons/

**Comment by jranavas** [comment]
Maybe this payment methods font is good for development, but is very bad to final customer, who sees some icons in colour (other methods) and Stripe in grey.

By default, every option can have a small png image and be required as needed vía <img> tag, like the filter does.

If one concrete method don't have a brand-colored png, we can contact them or search an option.

**Comment by roykho** [comment]
This is added to 4.1.
