### ISSUE TITLE
Stripe 3D Secure Issue

### ISSUE THREAD

**Issue by robman87** [woocommerce/woocommerce-gateway-stripe#448]
#### Affected ticket(s)

Stripe 3D Secure Issue #893909

#### What I expected

Expected to be redirected to 3D Secure confirmation page after filling in Stripe test credit card number that requires 3D Secure on checkout page.

#### What happened instead

Message on top of checkout page that says "Your card was declined.",
no Sources created for customer in Stripe Account Dashboard.

#### Steps to reproduce the issue

1. Add product to cart
2. Go to checkout page
3. Fill in all required fields, Address, telephone number etc.
4. Choose "Credit card (stripe)" as payment method
5. Submit form.
6. Fill in test credit card requiring 3D Secure in modal from Stripe.
7. Click Pay US$##
8. Button turns green with checkmark.
9. Payment fails, no source created, no redirect to 3D Secure confirmation page, "Your card was declined." error message appears on top of page.

Twenty Sixteen Theme used, other plugins disabled except WooCommerce and this plugin.

#### Additional information

The code creating Stripe source seems to never be reached in our testing.

We can have a screensharing session if that helps.

Link to screenshots and log file for plugin:
https://www.dropbox.com/sh/dque68k9rtuq9fs/AAD0MIb3_QsGzqBxwcs5AFoia?dl=0

**Comment by roykho** [comment]
Which test card number did you use?

**Comment by robman87** [comment]
I used the card which requires 3D Secure, 4000 0000 0000 3063.
https://stripe.com/docs/testing#3ds-cards

**Comment by roykho** [comment]
Hi @thorsten-stripe - when using Stripe Checkout ( popup modal ) can credit card that supports 3DS be used? If so, is there documentation on how to handle the flow or can we just use the same way we do with Elements?

**Comment by roykho** [comment]
@robman87 so 3DS is  not supported by our plugin with Stripe Checkout at this time. We will look into this in the near future. For now if you need to support 3DS, you need to disable Stripe Checkout and use the embedded credit card form on checkout.

**Comment by roykho** [comment]
Hi @robman87 please give master branch a test to see if 3DS cards now work for you. Thanks!

**Comment by robman87** [comment]
@roykho @thorsten-stripe Thank you so much for clearly answering this so quickly and fixing it very promptly. It seems to work well with modal now. Thanks again!

**Comment by Nakash23** [comment]
Hello,

i am not a expert about that but please i need help.
I setup stripe on my website and ticked 3d secure in the setup page. I didn't do anything else.
I tried the test with the same credit card above.
It seems to work.

Can i go in live? If a customer pay with master card or visa, will 3DS come? 
How can i check?
Please i am desperate, i need 3DS working for all payments with master card or visa on my website.

Thanks a lot/.

**Comment by roykho** [comment]
Hi @Nakash23 so this is not a support channel. Please use this instead https://wordpress.org/plugins/woocommerce-gateway-stripe/
