### ISSUE TITLE
Bug in changed card methods when no method exists

### ISSUE THREAD

**Issue by chrisknose** [woocommerce/woocommerce-gateway-stripe#449]
Error is thrown when customer no longer is using card payment. In this instance customer successfully made card payments. The card ceased to exist however,

Notice: Undefined variable: card in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/class-wc-stripe-compat.php on line 388
Notice: Trying to get property of non-object in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/class-wc-stripe-compat.php on line 388

Via N/A card ending in

Code block around 388
if ( $source->id === $stripe_source_id ) {
	$found_source = true;
	/* translators: 1) card brand 2) last 4 digits */
	$payment_method_to_display = sprintf( __( 'Via %1$s card ending in %2$s', 'woocommerce-gateway-stripe' ), ( isset( $card->brand ) ? $card->brand : __( 'N/A', 'woocommerce-gateway-stripe' ) ), $card->last4 );
	break;
}

#### Affected ticket(s)

unknown

#### What I expected

I noticed this after going into /my-account/ and trialing shortcode [subscriptions].
It normally says a 'date' then via 'payment method'. 

#### What happened instead
This error was shown in the 'next payment' field after the next payment was render which instructs the payment method to be used at next payment.

In 55 mins	
Notice: Undefined variable: card in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/class-wc-stripe-compat.php on line 388

Notice: Trying to get property of non-object in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/class-wc-stripe-compat.php on line 388

Via N/A card ending in

#### Steps to reproduce the issue
1. Create subscription
2. Use stripe card for payment
3. Deleted card from account (I think I deleted via stripe itself).
4. Error thrown.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Hi, are you using version 4.0+ of this plugin? If so there is no way to delete a source that I know of from the Stripe account. You can however delete the customer which in turn deletes the source. I did that in my testing but I don't see the error you mentioned?

Perhaps there is another reproducible steps you took?

**Comment by roykho** [comment]
I tried deleting the source from the subscription itself but still fail to reproduce the error. So I will just add in a check to see if the `$card` is an object to prevent this from possibly happening.

**Comment by chrisknose** [comment]
@roykho  This or similar has comeback in /my-account/view-subscription/ 
The customer is legacy stripe subscription using stripe_card_id to make payments. I suspect something within stripe moving to 'source'.

Payment source column reads:
April 6, 2018	
Notice: Undefined property: stdClass::$type in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/class-wc-stripe-compat.php on line 487
Via MasterCard card ending in 3414

**Comment by roykho** [comment]
@chrisknose are the steps to replicate the same as before? So I have to have a card saved from pre Stripe 4.0?

**Comment by chrisknose** [comment]
Steps to replicate:
I imported the subscriber using woosubscription importer setting payments to stripe and data above. The customer successfully processed first renewal 3 days ago via stripe (payment worked fine).

The customer has stripe field inputs
Subscription.Payment (postmeta)
customer_id = cus_xxx
card_id = does not exist
Stripe Source ID = blank

User meta
customer_id = does not exist (and adding does not assist)

The customer doesn't have a source_id/card_id stored in woocommerce.

This error also presents the right data being:
"April 6, 2018" (at start)
"Via MasterCard card ending in 3414" (at end)
Just has the PHP error notice in the middle.

Customers with source_id have no issue. 
Eg Payment Source column says:
March 19, 2018	
Via Visa card ending in 8077

**Comment by roykho** [comment]
I think that is where the issue is. The customer should not have both card id and stripe source. When you import, you specify both fields?

**Comment by chrisknose** [comment]
I think I've identified the issue as laid out below. 
The issue when attempting to register a payment method using 'stripe_card_id'.

I get the php notices on /view-subscription.
So I inserted the '_stripe_card_id' into subscription.postmeta for the subscription.
This solved the issue on /view-subscription.

When I look at /my-account/payment-methods the customer has no registered payment method and displays 'no saved methods found'.
I looked further and card_id hasn't been a registered as a payment-token to the user.

I'd recommend having the card option available in billing info that stores and tokens.

Sorry I remembered as i was doing this after import the stripe details didn't work so i had to manually add the 'customer_id' to imported subscriptions but left source_id blank and card_id is no longer available from billing-payment section.

This explains the issue (hope it makes sense). 
Simply no method exists to register legacy stripe_card_ids properly.

**Comment by roykho** [comment]
That's correct. We no longer have methods that add legacy card. So if you need to bulk import, you need to manually add them as `_stripe_card_id` instead of `_stripe_source_id`.  It will later then be updated to `_stripe_source_id` after using.

**Comment by chrisknose** [comment]
Ok. Hurts for migrations. 
When it updates to source does it add the source as a payment token or do i need script that in?

**Comment by roykho** [comment]
Only the meta name is updated. You don't need to update the actual card token value.

**Comment by jcanales** [comment]
Same issue here, when payment method exists in a users profile and trying to add new one I get this error, any toughts?

Notice: Undefined property: stdClass::$id in /var/www/html/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php on line 1118

Notice: Trying to access array offset on value of type null in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php on line 529

Notice: Trying to access array offset on value of type null in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php on line 533
