### ISSUE TITLE
Validation is skipped on mobile

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-gateway-stripe#450]
When checking out on a mobile device, the validation is skipped (handled after the payment fields).

If I do not enter any of the required fields and click the Continue to payment button. The payment fields show up without any warning. I'm also asked to enter the email address, which is usually pre-populated after entering the checkout fields

![image](https://user-images.githubusercontent.com/11388669/34875224-499ed9d2-f794-11e7-8392-b524810fe175.png)

If I do the same on a desktop, I get the following validation errors before being allowed to enter payment details:

```
First name cannot be empty
Last name cannot be empty
Street address cannot be empty
Town / City cannot be empty
County cannot be empty
Phone cannot be empty
Email address cannot be empty
```

Tested with:
- WooCommerce 3.2.6
- Stripe 4.0.1
- Storefront 2.2.5

Affected ticket: 894822-zen

**Comment by roykho** [comment]
Yes that is correct, nothing we can do about this one on mobile.
