### ISSUE TITLE
Conflict with "Campaign Monitor for WooCommerce" plugin

### ISSUE THREAD

**Issue by peterpaulcycliqcom** [woocommerce/woocommerce-gateway-stripe#452]
If "Campaign Monitor for WooCommerce" plugin is installed and after updated the "WooCommerce Stripe Gateway" to v4.0.0/v4.0.1 I can't checkout because of an error “Payment processing failed. Please retry.”

**Comment by roykho** [comment]
https://github.com/woocommerce/woocommerce-gateway-stripe/issues/442
