### ISSUE TITLE
SOFORT sends Admin Name (person) instead of Business Name to SOFORT.com

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce-gateway-stripe#453]
#### Affected ticket(s)

zd-901067

#### Issue

User reported in live chat

> There is a bug in the Stripe Plugin. Using SOFORT as Payment the Plugin transmit not the Business Name of the Stripe Account. It use the Admin Name. Stripe Support say it is a Plugin bug. 2 other User with the same config (Stripe 4.0.1 and Woo) have the same problem. 

Confirmed that issue has been discussed in German Woocommece Forum on Facebook

User supplied:

![](http://cld.wthms.co/3gav1i+)Image Link: http://cld.wthms.co/3gav1i

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@melindahelt did they set the Statement Descriptor setting? ![](http://cld.wthms.co/9bxjlu+)

**Comment by thorsten-stripe** [comment]
@melindahelt if I'm not mistaken this depends on how the Stripe Account is activated. If the Stripe Accounts is correctly activated as a Business Account it will show the business credentials, e.g. see:
![image](https://user-images.githubusercontent.com/23213994/34955248-7b396122-fa1b-11e7-82fb-90dfbaf1f1ee.png)
Terribly sorry that our team seems to have advised the user incorrectly. Could you asked them to write back in to support@stripe.com with this detailed information about the issue?

**Comment by thorsten-stripe** [comment]
@roykho the statement descriptor is shown underneath when the details are expanded:
![image](https://user-images.githubusercontent.com/23213994/34955315-c2a33042-fa1b-11e7-9e56-0d83dc3a0508.png)

**Comment by melindahelt** [comment]
Thanks for the update. Will follow up with user!
