### ISSUE TITLE
"Customer not found" - Stripe Transaction Failed from Wordpress site after updating official plugin

### ISSUE THREAD

**Issue by edgariscoding** [woocommerce/woocommerce-gateway-stripe#455]
After updating the Stripe plugin for Wordpress, automatic subscription charges started failing for this customer. I looked at the parent subscription and it looked like it was missing the customer ID and source ID, I didnt make any changes and I'm the only one with access to the admin dashboard. I tried adding the information by copying from Stripe.com but the transaction still fails.

I do not see anything about the transaction within Stripe's logs. The previous monthly charge, as well as most if not all charges for the past few years, have gone through smoothly.

The error I get on WordPress/Woocommerce is:

> Stripe Transaction Failed (Customer not found) Order status changed from Pending payment to Failed.

#### What I expected

I expected for the subscription to be renewed just like it had the previous month and like all other subscriptions on my site.

#### What happened instead

Failed transaction emails and a note within Woocommerce saying that the Customer was not found. 

#### Software versions:

Wordpress: 4.9.1
Woocommerce: 3.2.6
Woocommerce Subscriptions: 2.2.13
Woocommerce Stripe Gateway: 4.0.1

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
You should check if the customer id actually exists. For the order in question check if there is a meta of `_stripe_customer_id` and that it has a value.

**Comment by edgariscoding** [comment]
@roykho the customer ID does exist on Stripe.com and when I scroll down on the customer page within Stripe.com, I can see that the last charge was on 12/13/2017. 

When I go to the subscription in question and click on `edit` for the billing information, it now shows the Stripe Customer ID from Stripe.com in the Stripe Customer ID text field. 

It also shows the card_### value under the Stripe Source ID text field. This is the same ID string shown for the customer's card within Stripe.com.

**Comment by roykho** [comment]
So I wasn't referring to on Stripe side. But in your WooCommerce site's database. You mentioned "for this customer". Does that mean you have other subscriptions in place prior to 4.0 that does work after updating?

If it shows all the information you need in billing information, can you try to run "Process Renewal" to see if it now goes through for the charge?

**Comment by edgariscoding** [comment]
Ah ok, so I currently have three subscriptions active.

His is the first subscription that has attempted to renew this month. The next one will be renewed on the 25th. I'm not sure if it'll get processed successfully. I could wait but that means im losing out on the money from this current customer. 

I tried updating Woocommerce Subscriptions to the latest version, I also just updated my Stripe API version to the latest version (made sure it matched the version in use by the Stripe Gateway plugin). I tried renewing the subscription and it failed again. 

![img](https://i.imgur.com/wMKLeoU.png)

**Comment by roykho** [comment]
I would suggest you open up a ticket with us so we can look into your site. https://woocommerce.com/my-account/create-a-ticket

**Comment by roykho** [comment]
Also a good thing to note is what version of the Stripe plugin were you using before you updated to 4.0.1?

**Comment by edgariscoding** [comment]
Got it, I'll try having the customer re enter payment information instead of using the stored payment method, and if that doesn't work I'll create a ticket.

I was using 4.0.0 previously. I always keep the plugin up to date. 
I do notice that there's a 4.0.2 version that's about to be released which fixes "Possible 404 if getting customer source if no id was found.". Does that have anything to do with this?

**Comment by roykho** [comment]
I don't think that is related because if customer is not found, you won't be able to charge as that is correct and that seems like your case here. Are you certain in your parent subscription that the customer ID is matching the one you see on Stripe?

Its quite hard to help unless we can login to your site and check all settings..etc for ourselves hence I asked for you to open a ticket.

**Comment by edgariscoding** [comment]
So it just worked. I logged in as the user himself and went to his My Account page, then went through the checkout process. I noticed that the billing address on the checkout page was properly capitalized, and the address shown for that card within Stripe.com was all lower case. I changed the address on Stripe.com to match the correct capitalization. 

I then clicked on pay, keeping the saved card checked, and the payment went through fine.

I guess we'll see what happens with the other subscriptions later this month or with this same subscription next month when it tries renewing again.

Thanks for all the help/advice. I'll be sure to come back and post if it breaks again.

Feel free to close this Issue unless you have any other questions for me.

**Comment by roykho** [comment]
Ok I will close this for now. Please continue to post here if anything new arises.

**Comment by jorge-saldana** [comment]
Hi @edgariscoding, I’m having the same issue. Did updating address resolve it? If not how did you resolve?

**Comment by jorge-saldana** [comment]
Oh man, thanks for the quick reply. Did having the customer resign up the subscription manually fix the recurring payment? I have multiple customer subscriptions/customers. Gulp, I’ll start with stripe.com ticket.
