### ISSUE TITLE
Confusing error message with only one payment method

### ISSUE THREAD

**Issue by jranavas** [woocommerce/woocommerce-gateway-stripe#456]
#### What I expected

When there is only one payment method (e.g. Card), and the user click on "Place order" button without add payment data, appears this error message:

_Could not find payment information._

#### What happened instead

This error message:

_Could not find payment information. Please try with another payment method._

Is not important, but can be confusing.

#### Steps to reproduce the issue

Try to place an order without entering payment data and with only one payment method avaliable.

**Comment by roykho** [comment]
Sorry is this a bug or just a message issue?

**Comment by jranavas** [comment]
If is a conditional message (dependant of payment methods quantity available), it's a bug.

I prefer removing "Please try with another payment method." in all cases to clarify the UX.

**Comment by roykho** [comment]
So you're saying if there are more than one payment method, then you don't get the same error message is that correct?

**Comment by roykho** [comment]
Also are you using public release 4.0.1? Or master branch? In master branch, with only one payment method (credit card) and if I place order without entering anything, I see this ![](http://cld.wthms.co/vbwM8X+)

**Comment by jranavas** [comment]
Sorry @roykho, updated to master branch, all tested, solved! Thanks
