### ISSUE TITLE
Plugin frontend broken

### ISSUE THREAD

**Issue by knivesandforks** [woocommerce/woocommerce-gateway-stripe#462]
After updating to plugin version 4.0.1 the fields for the gateway have broken on checkout. I have since updated to the latest version 4.0.2, however this has now removed any <input> element from the DOM and the frontend now only show's a div with a comment inside.

Please see: https://smilespowder.staging.wpengine.com/checkout/

**Comment by roykho** [comment]
So this is not a support channel. Please use https://wordpress.org/support/plugin/woocommerce-gateway-stripe/

I did however checked your site and see this error. So something is not setup on your site correctly or there is a conflict with another plugin.
http://cld.wthms.co/xfUy8n
