### ISSUE TITLE
SEPA Mandate Notifications

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gateway-stripe#469]
Reported here https://wordpress.org/support/topic/sepa-mandate-email-missing/#post-9881617

According to the user, they said there needs to be a notification sent to the buyer/customer when SEPA is used. Currently we have a mandate agreement shown on the checkout page that says they accept this if they purchase from the store. However according to the reported user, this is not enough and we need to actually send out an email or notification of some sort of the mandate especially when it is recurring/subscription based order.

Ref: https://stripe.com/docs/sources/sepa-debit#prerequisite
Ref: https://stripe.com/docs/sources/sepa-debit#notifying-customers-of-recurring-payments

**Comment by thorsten-stripe** [comment]
@roykho we've added the ability to have them pre-notification emails sent by Stripe directly: https://stripe.com/docs/sources/sepa-debit#using-webhooks-or-automated-emails

**Comment by roykho** [comment]
@thorsten-stripe ok then nothing needs to be done on our end?

**Comment by thorsten-stripe** [comment]
@roykho by default no email is sent. You will need to set the `mandate[notification_method]` parameter to `email` when creating a `sepa_debit` source: https://stripe.com/docs/sources/sepa-debit#using-webhooks-or-automated-emails

**Comment by roykho** [comment]
@thorsten-stripe just noticed a typo while reading it http://cld.wthms.co/mBEEqe

**Comment by thorsten-stripe** [comment]
@roykho good catch, thanks for flagging!
