### ISSUE TITLE
Pass the Stripe Source in the order meta instead of in a post parameter

### ISSUE THREAD

**Issue by jesucarr** [woocommerce/woocommerce-gateway-stripe#470]
At the moment the process_payment function checks if the $_POST['stripe_source'] parameter is set, but we could store the stripe_source in a meta field of the order, and check if that is set instead. This way, plugins could simply call the process_payment function in a standard way without the need of setting additional post parameters for this plugin to work.

**Comment by roykho** [comment]
Are you doing something custom that requires you to call process_payment?

**Comment by jesucarr** [comment]
Yes, I'm creating an order outside of the checkout flow and sending it to the process_payment function

**Comment by roykho** [comment]
Yeah we're not going to change that at this time. Saving it to meta is not the best option as source object changes and having to go back in to update them is not ideal.

**Comment by jesucarr** [comment]
So what is the best option to save the source in the order, rather than passing it via a post parameter (forcing plugins to customize their code for this plugin)?
