### ISSUE TITLE
Better handling for mixed up keys.

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce-gateway-stripe#471]
If you have live keys entered as test keys and are in test mode, you get an error like this: http://cld.wthms.co/sK0EKR

Wondering if we could catch this more specific error to display something more helpful for store admins?

I believe the error was different in older versions of Stripe as well, per https://docs.woocommerce.com/document/stripe#section-37

**Comment by roykho** [comment]
There could be simple validation to check if it is test mode the value needs to start with `pk_test` and live mode `pk_live` but beyond that we have no way of knowing if they're actually valid.

**Comment by WPprodigy** [comment]
Yea, that sounds like a good option.

> but beyond that we have no way of knowing if they're actually valid

Well, I mentioned this because stripe is treating it differently in their response. Invalid keys get their own error message, live keys while in test mode gets the above more generic answer.
