### ISSUE TITLE
Apple Pay Button Too Wide on Product Pages

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-gateway-stripe#472]
#### Affected ticket(s)

904668-zen

#### Issue

It would be great if the Apple Pay button was able to have the width/alignment adjusted within the settings for the extension under  WooCommerce > Settings > Stripe.

Right now, it looks like this on some customers' sites, which is way too wide and looks clunky:

![http://cld.wthms.co/KEta02](http://cld.wthms.co/KEta02+)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
They can adjust the style with CSS `#wc-stripe-payment-request-button`

**Comment by dougaitken** [comment]
Added to docs - https://docs.woocommerce.com/document/stripe/#section-37 (for now, anchor section number may change)
