### ISSUE TITLE
When using Payment Request, the "Total" label is not very indicative

### ISSUE THREAD

**Issue by madmath** [woocommerce/woocommerce-gateway-stripe#474]
See screenshot. Used test site woocommerce.paymentrequest.show on the 4.0.3 version of the plugin.

![prtotal](https://user-images.githubusercontent.com/499162/35168794-4da575e2-fd28-11e7-876b-20d74810ead8.png)

#### What I expected

I was expecting the "Total" line to be a little more descriptive.

#### What happened instead

The website name shows up instead of something like "Total"

#### Steps to reproduce the issue

Buy something with Payment Request, notice the "Total" line.

Note: it seems to happen at this [code location](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8591ac2120e741eccaeae20d992ef13fca4fc575/includes/payment-methods/class-wc-stripe-payment-request.php#L63)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Right so the design is intended to show statement descriptor name and prefix of `via WooCommerce`.

Perhaps the difference is we modeled this using Apple Pay and for that it is more clear as seen here ![](http://cld.wthms.co/bb5HMi+)

PS: I've been wanting to test paymentRequest via desktop. Do you have a link that shows how to add "dummy" Google account and/or dummy credit card data?

**Comment by madmath** [comment]
Sure! Just add some dummy info at chrome://settings/autofill (no need for google account). 4242 4242... Is a card that works well with stripe test as you know

**Comment by roykho** [comment]
Ok so on your test site, I think if you fill in your statement descriptor setting then it would be nicer? Have you tried that?

**Comment by roykho** [comment]
On my test site ![](http://cld.wthms.co/CINaU8+)

**Comment by madmath** [comment]
Would most people have the default? Not sure what the descriptor is.

Most other implementers are using 'Total' as the label for the total object. It may also localize better.

**Comment by roykho** [comment]
Yes so most people use the statement descriptor because that is the name customer's will see on their bank statement. Here is the setting for that ![](http://cld.wthms.co/aB1vl0+)

**Comment by roykho** [comment]
In the next release, I will add a hook so people can change the `total` field to what they would like. Hook name `wc_stripe_payment_request_product_data`
