### ISSUE TITLE
WooCommerce Conflict

### ISSUE THREAD

**Issue by serolfcire** [woocommerce/woocommerce-gateway-stripe#475]
Version 4.0.0 and upward are causing a conflict with some variable products on my site.  When adding the product to cart after choosing options - product cannot be added.  An error says "choose product options"
 I had to revert to version 3.2.3 so that I could put some variable products on my site successfully

**Comment by roykho** [comment]
This is not a support channel. Please use the forums here https://wordpress.org/plugins/woocommerce-gateway-stripe/
