### ISSUE TITLE
No more bitcoin

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce-gateway-stripe#477]
https://twitter.com/stripe/status/955878329785053184

**Comment by roykho** [comment]
Hi @thorsten-stripe Should we remove bitcoin method from our plugin both in Stripe Checkout and Element?

**Comment by dougaitken** [comment]
FYI - I've included a link to the blog post in the Stripe docs at the part about bitcoin https://docs.woocommerce.com/document/stripe/#section-28

**Comment by thorsten-stripe** [comment]
@roykho yes, sorry for the delay in notifying you. Please deprecate until April 23, 2018.

**Comment by roykho** [comment]
Closed via master.
