### ISSUE TITLE
Payment issue with 4.0.3

### ISSUE THREAD

**Issue by kaleidografik** [woocommerce/woocommerce-gateway-stripe#480]
Hello. Having updated this morning from v4.0.0 to 4.0.3 we were no longer able to receive payments on our store. I have rolled back to 4.0.0 and all works correctly again.

Please see attached screen grab for the error code shown in 4.0.3

We are using the inline credit card form.

Many thanks.

<img width="1269" alt="screen shot 2018-01-24 at 20 48 48" src="https://user-images.githubusercontent.com/33453090/35357234-d634a498-014a-11e8-98e7-076aef6ce83a.png">

**Comment by roykho** [comment]
This is not a support channel, please post your support question https://wordpress.org/plugins/woocommerce-gateway-stripe/

**Comment by kaleidografik** [comment]
Reporting a bug, not specifically looking for support.

**Comment by roykho** [comment]
Bug reports requires full status report and versions and including steps to reproduce..etc.

**Comment by kaleidografik** [comment]
Hi Roy.

Please see details below. The previous screenshot shows the error, which is reproduced by trying to purchase an item via the checkout.

Wordpress: 4.9.2
WooCommerce: 3.2.6
WooCommerce Stripe Gateway: 4.0.3

Report:
`
### WordPress Environment ###

Home URL: https://2mealday.com
Site URL: https://2mealday.com
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 200 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Flywheel/4.1.0
PHP Version: 7.1.12-3+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 300 MB
PHP Time Limit: 30
PHP Max Input Vars: 4000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 60.41MB
Database Data Size: 33.82MB
Database Index Size: 26.59MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.05MB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.45MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
columns_priv: Data: 0.00MB + Index: 0.00MB
db: Data: 0.00MB + Index: 0.00MB
event: Data: 0.00MB + Index: 0.00MB
func: Data: 0.00MB + Index: 0.00MB
help_category: Data: 0.00MB + Index: 0.00MB
help_keyword: Data: 0.10MB + Index: 0.02MB
help_relation: Data: 0.01MB + Index: 0.02MB
help_topic: Data: 0.46MB + Index: 0.02MB
host: Data: 0.00MB + Index: 0.00MB
ndb_binlog_index: Data: 0.00MB + Index: 0.00MB
plugin: Data: 0.00MB + Index: 0.00MB
proc: Data: 0.00MB + Index: 0.00MB
procs_priv: Data: 0.00MB + Index: 0.00MB
proxies_priv: Data: 0.00MB + Index: 0.00MB
servers: Data: 0.00MB + Index: 0.00MB
tables_priv: Data: 0.00MB + Index: 0.00MB
time_zone: Data: 0.00MB + Index: 0.00MB
time_zone_leap_second: Data: 0.00MB + Index: 0.00MB
time_zone_name: Data: 0.00MB + Index: 0.00MB
time_zone_transition: Data: 0.00MB + Index: 0.00MB
time_zone_transition_type: Data: 0.00MB + Index: 0.00MB
user: Data: 0.00MB + Index: 0.00MB
wp_automatewoo_abandoned_carts: Data: 0.05MB + Index: 0.08MB
wp_automatewoo_customers: Data: 0.08MB + Index: 0.16MB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.03MB
wp_automatewoo_guest_meta: Data: 0.05MB + Index: 0.03MB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.06MB
wp_commentmeta: Data: 0.06MB + Index: 0.09MB
wp_comments: Data: 0.45MB + Index: 0.48MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.06MB + Index: 0.06MB
wp_postmeta: Data: 15.11MB + Index: 10.22MB
wp_posts: Data: 2.50MB + Index: 0.84MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 10.44MB + Index: 13.00MB
wp_users: Data: 0.13MB + Index: 0.14MB
wp_wpb2d_excluded_files: Data: 0.02MB + Index: 0.00MB
wp_wpb2d_options: Data: 0.02MB + Index: 0.00MB
wp_wpb2d_processed_dbtables: Data: 0.02MB + Index: 0.00MB
wp_wpb2d_processed_files: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 320
acf-field-group: 49
amn_smtp: 1
attachment: 2816
aw_workflow: 4
intermittent_fasting: 8
mc4wp-form: 1
nav_menu_item: 17
page: 19
post: 41
product: 2
revision: 513
shop_coupon: 16
shop_order: 738
shop_order_refund: 1
transformations: 12
wc_membership_plan: 2
wc_user_membership: 824

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

2 Meal Day: by Sev Furneaux – 1.0
Advanced Custom Fields PRO: by Elliot Condon – 5.6.7
WP Offload S3 Lite: by Delicious Brains – 1.2.1
Amazon Web Services: by Delicious Brains – 1.0.4
AutomateWoo - Referrals Add-on: by AutomateWoo – 1.7.10
AutomateWoo: by AutomateWoo – 3.5.0
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.2.1.2 – Not tested with the active version of WooCommerce
Google XML Sitemaps: by Arne Brachhold – 4.0.9
Intuitive Custom Post Order: by hijiri – 3.1.0
Safe SVG: by Daryll Doyle – 1.6.0
WooCommerce Stripe Gateway: by WooCommerce – 4.0.0
WooCommerce MailChimp: by Saint Systems – 2.1.4 – Not tested with the active version of WooCommerce
WooCommerce Memberships: by SkyVerge – 1.8.5 – 1.9.6 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.6
WordPress Backup to Dropbox: by Michael De Wildt – 4.7.1
Yoast SEO: by Team Yoast – 6.2
WP Crontrol: by John Blackbourn & contributors – 1.6.2
WP Mail SMTP: by WPForms – 1.2.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page not set
Basket: ❌ Page not set
Checkout: #29 - /checkout/
My account: #30 - /my-account/
Terms and conditions: #905 - /terms-conditions/

### Theme ###

Name: 2 Meal Day
Version: 1.0.0
Author URL: http://oakdesignstudio.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: 2-meal-day/woocommerce/checkout/form-billing.php
2-meal-day/woocommerce/checkout/form-checkout.php
2-meal-day/woocommerce/checkout/form-coupon.php
2-meal-day/woocommerce/checkout/payment-method.php
2-meal-day/woocommerce/checkout/payment.php
2-meal-day/woocommerce/checkout/review-order.php
2-meal-day/woocommerce/checkout/terms.php
2-meal-day/woocommerce/checkout/thankyou.php
2-meal-day/woocommerce/emails/customer-completed-order.php
2-meal-day/woocommerce/emails/customer-note.php
2-meal-day/woocommerce/emails/customer-processing-order.php
2-meal-day/woocommerce/emails/customer-refunded-order.php
2-meal-day/woocommerce/emails/customer-reset-password.php
2-meal-day/woocommerce/emails/email-footer.php
2-meal-day/woocommerce/emails/email-header.php
2-meal-day/woocommerce/emails/email-styles.php
2-meal-day/woocommerce/myaccount/form-login.php
2-meal-day/woocommerce/myaccount/form-lost-password.php
2-meal-day/woocommerce/myaccount/form-reset-password.php
2-meal-day/woocommerce/myaccount/lost-password-confirmation.php
2-meal-day/woocommerce/order/order-details-customer.php
2-meal-day/woocommerce/single-product.php

`

**Comment by roykho** [comment]
Your report shows 4.0.0 of Stripe. Please update.

**Comment by kaleidografik** [comment]
Updating to 4.0.3 causes the issue. I have rolled back to enable payments.

**Comment by roykho** [comment]
I understand that but you cannot fix the issue if you stay with 4.0. I suggest you clear any cache you may have on server level or plugin level and re-test.
