### ISSUE TITLE
Payment Issue in 4.0.3

### ISSUE THREAD

**Issue by stevegrant1983** [woocommerce/woocommerce-gateway-stripe#481]
#### What I expected

Customer payment to be processed via Stripe.

#### What happened instead

Customer payment not processed, error message output:

`No such source: {\"id\":\"src_1BnmNsEx4h4XoMce5zN9fgoJ\",\"card\":{\"exp_month\":12,\"exp_year\":2018,\"brand\":\"MasterCard\",\"card_automatically_updated\":false,\"country\":\"ES\",\"cvc_check\":\"pass\",\"funding\":\"debit\",\"last4\":\"9013\",\"three_d_secure\":\"optional\",\"address_line1_check\":null,\"address_zip_check\":null,\"tokenization_method\":null,\"dynamic_last4\":null},\"bitcoin\":\"\",\"flow\":\"none\",\"object\":\"source\",\"status\":\"chargeable\",\"type\":\"card\",\"usage\":\"reusable\"}`

#### Steps to reproduce the issue

Proceed through checkout process, entering details as requested. Enter payment details on Stripe modal. Error message then displays.

#### Status Report

`
### WordPress Environment ###

Home URL: https://elephant.art
Site URL: https://elephant.art
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.12.2
PHP Version: 7.0.26
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.28.4

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 620.58MB
Database Data Size: 439.88MB
Database Index Size: 180.70MB
wp_woocommerce_sessions: Data: 72.14MB + Index: 1.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.25MB + Index: 0.11MB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 3.02MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.08MB + Index: 0.09MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.36MB + Index: 0.03MB
wp_comments: Data: 2.52MB + Index: 1.50MB
wp_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.08MB + Index: 0.00MB
wp_options: Data: 6.20MB + Index: 1.08MB
wp_postmeta: Data: 246.75MB + Index: 149.64MB
wp_posts: Data: 90.30MB + Index: 8.38MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_redirection_404: Data: 3.02MB + Index: 2.14MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.08MB
wp_redirection_logs: Data: 0.05MB + Index: 0.08MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 1.52MB + Index: 3.03MB
wp_term_relationships: Data: 3.52MB + Index: 1.41MB
wp_term_taxonomy: Data: 1.52MB + Index: 1.98MB
wp_usermeta: Data: 2.52MB + Index: 2.98MB
wp_users: Data: 0.13MB + Index: 0.08MB
wp_w3tc_cdn_queue: Data: 0.02MB + Index: 0.02MB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_wfConfig: Data: 0.06MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 1.52MB + Index: 0.00MB
wp_wfHits: Data: 1.52MB + Index: 0.27MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.00MB
wp_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.11MB + Index: 0.03MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfStatus: Data: 0.13MB + Index: 0.09MB
wp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB
wp_yarpp_related_cache: Data: 1.38MB + Index: 2.81MB
wp_yoast_seo_links: Data: 0.17MB + Index: 0.06MB
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

acf: 4
article: 1
attachment: 9790
nav_menu_item: 43
oembed_cache: 1
page: 20
post: 900
product: 73
product_variation: 22
revision: 11147
scheduled-action: 254
shop_coupon: 29
shop_order: 1235
shop_order_refund: 11
shop_subscription: 261
shop_webhook: 2
sidebar: 1
stores: 1
vecb_editor_buttons: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (52) ###

Gravity Forms: by rocketgenius – 2.2.1.3
Admin Menu Editor: by Janis Elsts – 1.8.1
Advanced Custom Fields: by Elliot Condon – 4.4.12
Black Studio TinyMCE Widget: by Black Studio – 2.6.1
Admin Columns: by AdminColumns.com – 3.0.7
Convert Plus: by Brainstorm Force – 3.1.3
Cookie Law Info: by Richard Ashby – 1.5.3
Cron GUI: by Simon Wheatley – 1.03
Duplicate Post: by Enrico Battocchi – 3.2.1
Easy WP SMTP: by wpecommerce – 1.3.5
Edit Flow: by Daniel Bachhuber
Scott Bressler
Mohammad Jangda
Automattic
and others – 0.8.2

Elephant Convertor: by Tobias Russell – 1.0
Elephant Image Style Picker: by Steve Grant – 1.0
Elephant Most Popular: by Tobias Russell – 1.0
Elephant Pull Quote: by Toby Russell (99% derived from Simple Pull Quote by Toby Cryns) – 1.5
Feed Modifier: by Toby Russell – 1.0
Gravity Forms MailChimp Add-On: by rocketgenius – 4.2
MailChimp for WooCommerce: by MailChimp – 2.1.3 – Not tested with the active version of WooCommerce
PixelYourSite PRO: by PixelYourSite – 6.3.5 – Not tested with the active version of WooCommerce
Post Thumbnail Editor: by sewpafly – 2.4.8
Redirection: by John Godley – 3.0.1
Simple Tags: by Amaury BALMER – 2.4.7
Page Builder by SiteOrigin: by SiteOrigin – 2.6.2
SiteOrigin Widgets Bundle: by SiteOrigin – 1.11.3
SumoMe: by SumoMe – 1.27
Taxonomy Templated: by Tobias Russell – 1.0
TinyMCE Advanced: by Andrew Ozz – 4.6.7
User Role Editor: by Vladimir Garagulya – 4.39
W3 Total Cache: by Frederick Townes – 0.9.6
Widget Logic: by wpchefgadget
alanft – 5.9.0

WooCommerce Address Validation: by SkyVerge – 2.2.0 – 2.3.0 is available – Not tested with the active version of WooCommerce
WooCommerce Checkout Add-Ons: by SkyVerge – 1.11.0 – 1.12.0 is available – Not tested with the active version of WooCommerce
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.3.6 – 4.4.2 is available – Not tested with the active version of WooCommerce
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.4 – 2.4.7 is available – Not tested with the active version of WooCommerce
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.4.7 – 4.4.11 is available – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.0.3
WooCommerce Google Analytics Pro: by SkyVerge – 1.3.4 – 1.3.6 is available – Not tested with the active version of WooCommerce
WooCommerce One Page Checkout: by Prospress Inc. – 1.5.2 – 1.5.3 is available – Not tested with the active version of WooCommerce
WooCommerce POS: by kilbot – 0.4.17
WooCommerce Price Based on Country Pro Add-on: by Oscar Gare – 2.1.2 – Not tested with the active version of WooCommerce
WooCommerce Product Add-ons: by WooCommerce – 2.9.0 – 2.9.1 is available – Not tested with the active version of WooCommerce
WooCommerce Google Product Feed: by Lee Willis – 7.1.5 – 7.4.2 is available – Not tested with the active version of WooCommerce
WooCommerce Price Based on Country (Basic): by Oscar Gare – 1.6.22
WooCommerce Social Login: by SkyVerge – 2.3.1 – 2.4.0 is available – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Prospress Inc. – 2.2.8 – 2.2.16 is available – Not tested with the active version of WooCommerce
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.0.3 – 3.0.5 is available – Not tested with the active version of WooCommerce
WooCommerce Xero Integration: by WooCommerce – 1.7.9 – 1.7.10 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.6
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO Premium: by Team Yoast – 6.1.2
WP Smush Pro: by WPMU DEV – 2.7.3
Yet Another Related Posts Plugin: by Adknowledge – 4.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #7164 - /shop/
Cart: #7165 - /basket/
Checkout: #7166 - /checkout/
My account: #7167 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Elephant Website Theme
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: UnderStrap
Parent Theme Version: 0.6.2 – 0.7.0 is available
Parent Theme Author URL: http://www.holgerkoenemann.de
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: elephant/woocommerce/archive-product.php
elephant/woocommerce/cart/cart-empty.php
elephant/woocommerce/cart/cart-shipping.php version 3.1.0 is out of date. The core version is 3.2.0
elephant/woocommerce/cart/cart-totals.php
elephant/woocommerce/cart/cart.php
understrap/woocommerce/cart/mini-cart.php version 2.5.0 is out of date. The core version is 3.2.0
elephant/woocommerce/cart/proceed-to-checkout-button.php
elephant/woocommerce/cart/shipping-calculator.php version 2.0.8 is out of date. The core version is 3.2.0
elephant/woocommerce/checkout/form-billing.php
elephant/woocommerce/checkout/form-checkout.php
elephant/woocommerce/checkout/form-coupon.php
understrap/woocommerce/checkout/form-pay.php
elephant/woocommerce/checkout/form-shipping.php
elephant/woocommerce/checkout/payment-method.php
elephant/woocommerce/checkout/payment.php
elephant/woocommerce/checkout/review-order.php
elephant/woocommerce/checkout/thankyou.php version 3.0.0 is out of date. The core version is 3.2.0
elephant/woocommerce/content-product.php
elephant/woocommerce/content-single-product.php
understrap/woocommerce/global/form-login.php
elephant/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 3.2.0
understrap/woocommerce/global/wrapper-end.php
understrap/woocommerce/global/wrapper-start.php
elephant/woocommerce/loop/add-to-cart.php
elephant/woocommerce/loop/loop-end.php
elephant/woocommerce/loop/loop-start.php
elephant/woocommerce/loop/orderby.php
elephant/woocommerce/loop/price.php
elephant/woocommerce/loop/result-count.php
elephant/woocommerce/myaccount/dashboard.php
understrap/woocommerce/myaccount/downloads.php version 3.0.0 is out of date. The core version is 3.2.0
understrap/woocommerce/myaccount/form-edit-account.php
understrap/woocommerce/myaccount/form-edit-address.php version 3.0.0 is out of date. The core version is 3.0.9
understrap/woocommerce/myaccount/form-login.php version 2.6.0 is out of date. The core version is 3.2.0
understrap/woocommerce/myaccount/form-lost-password.php
understrap/woocommerce/myaccount/form-reset-password.php
elephant/woocommerce/myaccount/my-account.php
understrap/woocommerce/myaccount/my-address.php
understrap/woocommerce/myaccount/my-orders.php
understrap/woocommerce/myaccount/navigation.php
elephant/woocommerce/myaccount/orders.php version 3.0.0 is out of date. The core version is 3.2.0
elephant/woocommerce/order/order-details-customer.php version 3.0.0 is out of date. The core version is 3.2.0
elephant/woocommerce/order/order-details-item.php
elephant/woocommerce/order/order-details.php version 3.0.0 is out of date. The core version is 3.2.0
elephant/woocommerce/single-product/add-to-cart/simple.php
elephant/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
elephant/woocommerce/single-product/price.php
elephant/woocommerce/single-product/product-image.php
understrap/woocommerce/single-product/product-thumbnails.php version 3.0.2 is out of date. The core version is 3.1.0
understrap/woocommerce/single-product/rating.php version 2.3.2 is out of date. The core version is 3.1.0
elephant/woocommerce/single-product/related.php
understrap/woocommerce/single-product/review-rating.php version 3.0.0 is out of date. The core version is 3.1.0
elephant/woocommerce/single-product/short-description.php
elephant/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update

### PBC Settings ###

Base location: GB
Price Based On: billing
Shipping: –
Test mode: –
Test country: –
Currency format: [symbol][price]

### Zone Pricing Euro Zone ###

slug: euro-zone
name: Euro Zone
countries: AT | BA | BE | BG | CH | CZ | DE | DK | EE | ES | FI | FR | GR | HR | HU | IE | IT | LI | LT | LU | LV | MC | ME | MK | MT | NL | NO | PL | PT | RO | SE | SI | SK | SM
currency: EUR
auto_exchange_rate: yes
exchange_rate: 1.1405
currency_format: 
price_thousand_sep: ,
price_decimal_sep: .
price_num_decimals: 2

### Zone Pricing US Dollar Zone ###

slug: us-dollar-zone
name: US Dollar Zone
countries: CA | MX | PR | UM | US | VI
currency: USD
auto_exchange_rate: yes
exchange_rate: 1.329
currency_format: 
price_thousand_sep: ,
price_decimal_sep: .
price_num_decimals: 2

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Customer/Order CSV Export ###

Order Export Format: default_one_row_per_item
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled
`

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
This is a caching issue, you need to clear your cache on server level and/or plugin level.
