### ISSUE TITLE
Please choose product options… - Stripe in live mode but single product page not https

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#483]
#### Affected ticket(s)
ticket: 919577-zen

#### What I expected
To be able to add variable products to the cart

#### What happened instead
Some product configurations seem to prevent that if Stripe is enabled, payment request buttons are enabled and the single product page is not served over https

#### Steps to reproduce the issue

1. Import this example product from the site where this was reported 
[ticket 919577 product export.csv.zip](https://github.com/woocommerce/woocommerce-gateway-stripe/files/1666082/ticket.919577.product.export.csv.zip) - this problem happens consistently with this product on the customer's site as well as on my local testing site but it is not consistent across all variable products
2. Ensure that Stripe payment request buttons are enabled
3. Stripe is in live mode
4. Visit the http version of the single product page for the imported product
5. Try to add to cart (default selection)
6. Get a "Please choose product options…" message
![see screen shot](http://cld.wthms.co/xkSQVZ+)

-------------------

- [ ] Issue assigned to next milestone.
- [ x] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Stripe requires SSL wherever it is loaded so nothing we can do.
