### ISSUE TITLE
Error message on checkout page

### ISSUE THREAD

**Issue by Picpool** [woocommerce/woocommerce-gateway-stripe#484]
#### What I expected

Proceed to payment and go to checkout page

#### What happened instead

Error message in Woocomcer notification zone at the top of the checkout page : 
No such source {\"id...

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
If this is a bug report, please provide full status and information of the issue. If you're asking for support please post here https://wordpress.org/support/plugin/woocommerce-gateway-stripe
