### ISSUE TITLE
Design and usability of new european payment gateways...

### ISSUE THREAD

**Issue by storeofideas** [woocommerce/woocommerce-gateway-stripe#486]
I just installed the new 4.0.1 version of the stripe plugin and love the fact that you have added support for the European Payment Gateways. However I can't use them yet, because they look a bit weird on my end and that might irritate some visitors...

SEPA-Lastschrift: 
If you pay via SEPA-Lastschrift normally it looks like that (https://pasteboard.co/H2InZQ7.png) or like that (https://pasteboard.co/H2Ioecx.png) with real time validation. Would it be possible to change the current design to something like on the screenshots with the next update?

Android Pay: 
Is it already possible to offer Android Pay? If not, will you add support for that in the future?

I would love to use your Plugin in the future. However it would be great if the new payment gateways looked a bit more "familar" and professional to european customers, so they can trust my website.

**Comment by roykho** [comment]
cc @thorsten-stripe on the realtime validation question.

**Comment by thorsten-stripe** [comment]
@roykho we're working on an IBAN Element with real-time validation. I'll keep you posted on that.

**Comment by storeofideas** [comment]
Are there any updates planned on this in the next time?

**Comment by kmindi** [comment]
Keep in mind that it is still required to show the required information for a SEPA mandate. I'm no rights expert if it is allowed to only link to the information as @storeofideas screenshoted pages do. The form must show 
- the adress and name of the creditor
- creditor ID
- (if assinged later => optional) the mandate reference
- if it is given for a recurring payement
- the mandate text that is currently in place https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/payment-methods/class-wc-gateway-stripe-sepa.php#L238 should get a checkbox  (http://single-euro-payments-area.de/beispiele-fuer-sepa-mandat-erteilung-im-internet)
---

- [ ] The adress could be taken from the woocommerce store general settings 
- [ ] The creditor ID should be available via the stripe API or could be entered in an additonal field in the stripe sepa settings

**Comment by storeofideas** [comment]
Any updates on that? Does the IBAN field have real time validation now? Do you plan to work on the design and to make the mandate reference as a checkbox with link for a popup?

**Comment by storeofideas** [comment]
@thorsten-stripe are you still working on that? Are there any updates or a release date already? Thank you in advance.

**Comment by thorsten-stripe** [comment]
We've just released our IBAN Element: https://stripe.com/docs/stripe-js/elements/iban

@roykho would be great if you could add that when it suits. 

Regarding adding a checkbox, afaik this isn't necessarily required, and after source creation we provide a hosted mandate link with the necessary information which by default is also emailed to the customer.
