### ISSUE TITLE
Add support for custom fonts (and locale)

### ISSUE THREAD

**Issue by profoX** [woocommerce/woocommerce-gateway-stripe#487]
#### Affected ticket(s)

None

#### What I expected

I want to define custom fonts (and perhaps also locale).

#### What happened instead

I was not able to define custom fonts (or locale).

#### Steps to reproduce the issue

Custom fonts need to be defined in the options parameter of the stripe.elements(options) call.
Right now, the plugin always uses an empty options object.
It might be a nice addition if a WP filter would be added to set/modify the options array.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Please search the code in the future. There are already hooks for it `wc_stripe_elements_styling`

**Comment by profoX** [comment]
@roykho With all due respect, but I did research the code quite well. I know `wc_stripe_elements_styling` exists. I also know that this hook **does not** allow me to add **custom** fonts.

I did create a workaround by overriding the Stripe class a bit on the fly, but ideally support for custom fonts should be added by this plugin.

PS: _Please read my issue better in the future._ ;-)

**Comment by profoX** [comment]
I believe (but please do correct me if I'm really wrong) that the problem is caused in the stripe.js where you do `var elements = stripe.elements()`

If I understand the Stripe Elements documentation correctly, custom fonts need to be added as a property of the optional options object in the stripe.elements() call, but right now there's no way to put anything there*. It would be great if there was something like a `wc_stripe_elements_options` filter (or maybe even something more high level for the fonts and locale).

I could create a pull request if this would help? (But I think you guys/girls might have a better idea of how to implement this in the best way possible.)

_* unless we inject it by modifying the elements() call by changing the Stripe object in our JS or something like that, but that's just a hack_

**Comment by roykho** [comment]
Please have a look ![](http://cld.wthms.co/dtBTJZ+)

**Comment by profoX** [comment]
Hi Roy, thanks for your reply, but as you probably know, the `fontFamily` property will not allow you to use any custom font. We can only choose from the available fonts. And this means fonts that are available from the iframe. If we want to use a custom font, we need to add it first by defining it inside of the `fonts` property of an `options` object that is an (optional) argument for the `stripe.elements(options)` function.

I really think that you are not getting what I mean. Please try to use a custom font (this means one that is not available by default) and if you can show me how to do this with the current code, then I admit that I might be blind :-) But right now, I really do think that I can't use my own custom font because of the reason I have stated before. Please double-check.

Also check out https://stripe.com/docs/stripe-js/reference#stripe-elements

![custom-fonts](https://user-images.githubusercontent.com/30413/35488648-f910e82a-048b-11e8-843d-8de04c6d7954.png)

Thanks.

**Comment by roykho** [comment]
I am responding to how I read and understood the docs. You're saying you can't use the styles elements but would need to use options to do this? Just to be clear you're trying to change the fonts within the CC fields correct? Like when people type inside for credit card or expiration date?

**Comment by profoX** [comment]
Yes. I will try to explain again: You cannot use any custom font if you can only change the `fontFamily` property of an element's style. You also need to add the font when creating an 'elements' instance by using `stripe.elements()`.

_And you are correct. My client does not like it that the font looks different from their custom font that is being used in the other input fields. I fixed this for him by injecting it into `stripe.elements()` when an 'elements' instance is created. But of course this is just a hack. I cannot add custom fonts to the iframe any other way (because of CORS)._

**Comment by roykho** [comment]
I was under the impression that you can load custom fonts in your theme. Then just call that fontFamily in the styles.

If I added a hook into the elements options, can you please show me what your code would look like? Provide a real example so I can see what is needed.

**Comment by profoX** [comment]
Hi Roy, you have to keep in mind that Stripe Elements loads in an iframe and that there's also CORS. I don't believe we can just reference our own custom fonts inside a third party iframe.

Here's an example of how I would envision using this hook:

```
function issue487_example($options) {
    $options['fonts'] = array(
        array(
            'cssSrc' => 'https://fonts.googleapis.com/css?family=Open+Sans',
        ),
        array(
            'family' => 'avenir-light',
            'src' => "local('avenir-light'), url('https://example.com/Avenir-Light.eot') format('embedded-opentype'), url('https://example.com/Avenir-Light.woff') format('woff')"
        ),
    );
    return $options;
}
add_filter('wc_stripe_elements_options', 'issue487_example');
```

This should be the easiest to implement. But a `wc_stripe_elements_fonts` would work just as well. But I'm thinking it might be nice if you could also access other properties if necessary (`locale` being the other right now).

For implementation, you could add it to `wc_stripe_params` in the same way that `elements_styling` is being added. And then you can add the options when creating the instance at `var elements = stripe.elements(options)` What do you think?

**Comment by roykho** [comment]
This is how I have it now ![](http://cld.wthms.co/ClamVX+) ![](http://cld.wthms.co/bPX43q+)

**Comment by roykho** [comment]
Will that work for you?

**Comment by profoX** [comment]
Hi Roy, yes that will do just fine (I think) and that should make it possible to really use custom fonts in the Stripe Elements :-)

_One small note: I would pass an empty array to the filter instead of an empty string but I can work with this too if this is the preferred/accepted coding style._

**Comment by zzbeck** [comment]
Did this get solved? I am trying to use a custom font, so the font would be the same in the card fields as on the website.

**Comment by dottodot** [comment]
Should the example above work as I'm not having any joy. Here's what I have

```
function custom_add_stripe_options($options) {
    $options['fonts'] = array(
        array(
            'family' => 'pt-sans',
            'src' => "url('http://example.com/shop/wp-content/themes/my_theme/fonts/PTN57F-webfont.woff') format('woff')"
        ),
    );
    return $options;
}
add_filter('wc_stripe_elements_options', 'custom_add_stripe_options');


function custom_add_stripe_elements_styles($array) {
	$array = array(
		'base' => array( 
			'color' 	=> '#02253f',
			'fontFamily' 	=> 'pt-sans',
            'fontSize' 	=> '30px',
            'textTransform' => 'uppercase'
		),
		'invalid' => array(
			'color'		=> '#0099e5'
		)
	);
	return $array;
}
add_filter( 'wc_stripe_elements_styling', 'custom_add_stripe_elements_styles');
```

**Comment by KeironLowe92** [comment]
Looks like this isn't working properly, when I try to pass a custom font to `wc_stripe_elements_options` I get the `Uncaught Error: Invalid value for elements(): fonts should be array. You specified: [object Object].` javascript error

**Comment by roykho** [comment]
@KeironLowe92 what version of Stripe are you using and what does your code look like?

**Comment by daveyjones** [comment]
Hi @roykho — do you know the status of this? I tried the following and it doesn't seem to be working (I'm on the latest version of the plugin).
```
add_filter("wc_stripe_elements_options", "customize_stripe_fonts");
function customize_stripe_fonts($options) {
  $options["fonts"] = array(
    array(
      "family" => "FontName",
        "src" => "fontpath.woff"
      )
  );
  return $options;
}
```
I also tried casting the inner array as an object, but that didn't work either.

**Comment by daveyjones** [comment]
For those getting here from Google, here's a working example:
```
// Customize Stripe options
add_filter("wc_stripe_elements_options", "customize_stripe_options");
function customize_stripe_options($options) {
  $options["fonts"] = array(
    array(
      "family" => "Font Name",
      "src" => "url(https://example.com/font.woff) format(woff)"
    )
  );
  return $options;
}

// Customize Stripe styles
add_filter("wc_stripe_elements_styling", "customize_stripe_styles");
function customize_stripe_styles($styles) {
  $styles = array(
    "base" => array( 
      "fontFamily" => "Font Name",
      "fontSize" => "16px",
      "color" => "black"
    )
  );
  return $styles;
}
```

**Comment by synio-wesley** [comment]
Hi, it looks like the woocommerce-gateway-stripe team did indeed implement this filter, as originally proposed. Great!

Then indeed it *should* work like this:

```php
add_filter('wc_stripe_elements_options', function ($options) {
  $options['fonts'] = [
    [
      'family' => 'avenir-light',
      'src' => "local('avenir-light'), url('https://example.com/Avenir-Light.eot') format('embedded-opentype'), url('https://example.com/Avenir-Light.woff') format('woff')",
    ],
  ];
  return $options;
});

add_filter('wc_stripe_elements_styling', function ($styles) {
  $styles['base'] = [
    'fontFamily' => 'avenir-light',
    'fontSize' => '16px',
    'color' => 'blue',
  ];
  return $styles;
});
```

I think the code by @daveyjones should also work then.

Also many thanks to @roykho for fixing this issue back in 2018 when I reported it 👍😄
