### ISSUE TITLE
Add "Cancel" button to the Payment Method update page

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce-gateway-stripe#491]
#### Affected ticket(s)
929026-zd-woothemes

#### What I expected
When a customer clicks to add a new payment method from **"My Account",** if they change there mind there should be a "Cancel" button to signify that they have aborted the process.

Currently, there isn't one and although you can simply navigate away from the page, some customers get confused if they've entered information that they no longer want saved.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@FreshPhil so the page actually comes from WC core. Payment gateway is just declaring support for it. So I am not sure if the "cancel" button should be added to a payment gateway.

**Comment by FreshPhil** [comment]
Ah, good to know thanks @roykho
