### ISSUE TITLE
3DS reuse issue

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gateway-stripe#497]
Currently cards that has 3DS required and/or that goes through 3DS verification can checkout fine. However they can't currently be reused either from adding it as a payment method in `my account` or via subscriptions. Any subsequent charges to that card will fail.

**Comment by thorsten-stripe** [comment]
Just as a note, many notes that require 3DS can be used for subsequent recurrent charges as long as the initial payment was successfully authorized via 3D Secure.

**Comment by roykho** [comment]
@thorsten-stripe I updated our shared docs on that not sure if you saw it yet. But using the "test" card, I was not able to get this to work though I followed all the steps of the flow.

**Comment by roykho** [comment]
Closed as this only happens with the test 3DS card as it is design to always require 3DS for testing.
