### ISSUE TITLE
SOFORT not working after update

### ISSUE THREAD

**Issue by antoinehenrich** [woocommerce/woocommerce-gateway-stripe#498]
After updating to new WooCommerce and Stripe SOFORT is not passing any country. It will not replace the [country] code... Help please! :)

**Comment by roykho** [comment]
Not seeing issues with this ![](http://cld.wthms.co/i4MUiX+)

I suggest you deactivate all plugins and change to default theme and re-test.

**Comment by antoinehenrich** [comment]
Okay thanks! Problem was/is I'm not using the billing_country field on checkout-page. I now at least added the hidden input and it works!
