### ISSUE TITLE
Payment methods: Lack of ability to add payment for other customer

### ISSUE THREAD

**Issue by bradleymoore111** [woocommerce/woocommerce-gateway-stripe#499]
Hey, so I was wondering as a support agent what would the recommended approach be for adding a card on another client's behalf? We have a lot of clients and currently hold their credit card information, but the code that actually adds the card doesn't contain filters/actions anywhere for modifying the customer's ID, and without getting hacky, I'm not seeing a solution.

How do you recommend I go about this programmatically/properly?

**Comment by roykho** [comment]
Unfortunately this is not something we want to support at this time as it is outside the realm of this plugin. You can easily build a custom plugin to call the Stripe APIs to do this.
