### ISSUE TITLE
POT file for translations missing from installation package

### ISSUE THREAD

**Issue by The3IC** [woocommerce/woocommerce-gateway-stripe#501]
The installation package and the latest repository both seem to lack an up-to-date version of the .pot file.

**Comment by roykho** [comment]
Please refer to this https://wordpress.org/support/topic/translations-after-version-4-0/

**Comment by The3IC** [comment]
I'm not looking for the actual translations, the .pot file that is very helpful to generate updates to existing translations is missing.

**Comment by roykho** [comment]
If you really need that, you can use a POT generator. PO Edit comes to mind.

**Comment by The3IC** [comment]
POEdit does not support (afaik) reverse engineering POT files? What is the problem with including the .pot file in the distribution? It used to be there?

**Comment by roykho** [comment]
POEdit will work. That's how we create it in the past as well.

**Comment by The3IC** [comment]
From the full sources, yes. That is not a non-developer task. Normal practice with all other wp extensions is to generate the .pot file and include it in the distribution package (even base Woocommerce does this), why not stripe??

**Comment by roykho** [comment]
Will include one in next release.

**Comment by The3IC** [comment]
thanks
