### ISSUE TITLE
Consistent "Name" use between Stripe Checkout and standard checkout flow

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce-gateway-stripe#502]
#### Affected ticket(s)
934792-zd-woothemes

#### What I expected
When using the standard checkout experience, or the Stripe Checkout modal both should require the same information.

#### What happened instead
The First/Last name fields are **not** required in order to submit a transaction through Stripe Checkout

The First/Last name fields **are** required when using the default checkout flow

#### Steps to reproduce the issue
- As an admin, manually create an order and do not populate the First Name or Last Name fields under Billing Details.
- Send the invoice to the customer for payment
- With the **Stripe Checkout** option turned off, try to checkout. The payment will fail and you'll get the following console message.
![](http://cld.wthms.co/LC8zty+)
Image Link: http://cld.wthms.co/LC8zty

- With **Stripe Checkout** enabled, try to pay the same order and the payment will go through.

Through Stripe Checkout, the First/Last name are not being required, but they are when using the standard checkout flow.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/7fb4092cf5ba3523e91f5b3bb27e58e0b4c25596
