### ISSUE TITLE
Translation: woocommerce-gateway-stripe.pot file (translation template) is missing in 4.x.x

### ISSUE THREAD

**Issue by agaleski** [woocommerce/woocommerce-gateway-stripe#504]
#### What I expected

A pot file to be able to translate language strings like this example => 
`$message = __( 'WooCommerce Stripe - The minimum PHP version required for this plugin is %1$s. You are running %2$s.', 'woocommerce-gateway-stripe' );`

The translation domain is there, the strings too but the pot file is missing.

The pot file generation seems to be missing since it was removed from the Gruntfile here => 
https://github.com/woocommerce/woocommerce-gateway-stripe/commit/e7707f919f5d04d59c34d901ae76a93fded6a3d7#diff-35b4a816e0441e6a375cd925af50752c

#### What happened instead

No translations possible without altering the plugin files.

#### Steps to reproduce the issue

No steps required. Essential file is missing.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Already added will be in next version.
