### ISSUE TITLE
When removing a 100% coupon at checkout doesn't allow users to fill out the fields

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce-gateway-stripe#505]
#### Affected ticket(s)
933889-zd

#### What I expected

If 100% coupon, for some reason, is removed at checkout, that customer would be able to add cc details in the fields.
 

#### What happened instead

Cannot type into the fields. 

#### Steps to reproduce the issue

The steps are pretty particular:

1. Create a 100% coupon and any product.
2. Add product to cart and add the coupon at _cart_ (not checkout)
3. At checkout, customer decides to remove the coupon. Stripe gateway refreshes, but now you are not able to add any cc information.
4. This happens whether inline is disabled or not.
5. This is not an issue when the coupon is not 100%

![](http://cld.wthms.co/JQKX0z+)
Link to screenshot: http://cld.wthms.co/JQKX0z

**Comment by roykho** [comment]
This if fixed in master and will be in next release.
