### ISSUE TITLE
Payment processing failed. Please retry.

### ISSUE THREAD

**Issue by dansku** [woocommerce/woocommerce-gateway-stripe#506]
Without no updates on the code or plugin, it stopped working.
Every time someone tries to use Stripe on WooCommerce it shows the message:

`Payment processing failed. Please retry.`

When I enable logging, this is the error message.
Any idea where to start debugging it?

> 02-05-2018 @ 20:57:31 - ====Start Log====
> Error: stdClass Object
> (
>     [token_id] => 
>     [customer] => 
>     [source] => 
> )
> 
> ====End Log====

WooCommerce -> Version 3.2.6 
Stripe Gateway -> Version 4.0.5

Thank you

**Comment by roykho** [comment]
Please use the support channel here https://wordpress.org/support/plugin/woocommerce-gateway-stripe

**Comment by foxhound87** [comment]
Same issue here!

When I disable the `force ssl` option, in the console I also get `Error: Live Stripe.js integrations must use HTTPS.`

All is working using SSL.

**Comment by foxhound87** [comment]
Solved this, I was using wrong stripe test keys in my local env.

**Comment by Spriithy** [comment]
Hi guys, bumping up this thread,

I have the same issue and all the above proposed fixes didn't work for me. In my test env, I have set the correct Stripe API keys, SSL enabled. There are no JS errors on the page.

Woocommerce version 3.2.6
WooCommerce Stripe Gateway Version 4.0.7 

Does anyone have a deeper insight in the issue ? Thanks in advance !

**Comment by MightyGadget** [comment]
Same issue here. SSL is installed with no errors, but Stripe says it requires and SSL in the logs.
It will, however, accept payments through the chrome buy now function, just not via checkout

**Comment by jahau** [comment]
Any news on this? I'm using latest and the greatest versions of WordPress, WooCommerce, and Stripe. I get the error Payment processing failed. Please retry.

**Comment by martinsotirov** [comment]
Same error for me with the latest WooCommerce, WordPress and Stripe plugin.
