### ISSUE TITLE
Card details get deleted when shipping/billing details are changed

### ISSUE THREAD

**Issue by jjcoffee** [woocommerce/woocommerce-gateway-stripe#507]
#### What I expected

Card details shouldn't get deleted, this is not expected behaviour. A customer might realise their card is registered to a different address after entering it and want to change the billing address, for example.

#### What happened instead

If the tickbox to enable a different shipping address is toggled, the card details are removed. Same if post code and other fields are changed

#### Steps to reproduce the issue

1. Fill in billing details
2. Fill in card details
3. Tick ship to a different address
4. Note that the card details get annihilated

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Closing this one for now as the fields gets reset/regen'd on the WC update trigger and would be hard to know if it was for a legitimate reason or not.

**Comment by PatrickBauer** [comment]
@roykho I would like to reopen this ticket.
In regards to https://github.com/woocommerce/woocommerce/issues/12713  and https://github.com/woocommerce/woocommerce/pull/12821 we would only need to provide IDs for the CC input fields and WooCommerces checkout.js script would reenter all data.

**Comment by templeman** [comment]
I second @PatrickBauer on reopening. In additional to changing shipping/billing details, entering a coupon code can also result in credit card details being erased. In my case I have a checkout page where the coupon field has been moved to be one of the last fields on the page, after the credit card details. When a customer enters a coupon code it nukes the credit card details that were entered earlier in the flow and they must be re-entered.

**Comment by templeman** [comment]
@roykho Any thoughts on reopening given the WooCommerce changes referenced in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/507#issuecomment-391149898?

**Comment by joliverwestbrook** [comment]
This issue is driving one of my clients to consider moving to shopify. I'm looking at the code now and will most likely customize the js for them, but it seems like an important issue to address in a release.

**Comment by jimyaghi** [comment]
i want a resolution for this issue also. When working with Cartflows plugin and using order bumps, this also triggers an update and the fragment replaces the entire stripe form which is counter intuitive. a person should not have to retype that information when nothing was wrong in the first place. the only time payment information needs to get a replaced fragment is when the payment method changes. i don't see any other reason. i also thought to do some custom code to capture the filled out fields and refill them before replacing but it looks like it may not be possible as stripe keeps that sensitive data private. what other solutions might work? i'm thinking to clone the entire section before update and then replace it when the update trigger is done

**Comment by allendav** [comment]
Seems like this could affect a lot of merchants. Moving this to high.

**Comment by dechov** [comment]
https://github.com/woocommerce/woocommerce-gateway-stripe/pull/927 is merged in support of this issue but the fix depends on https://github.com/woocommerce/woocommerce/pull/24227.

**Comment by dechov** [comment]
The latter PR is now merged (slated for 3.9 release) so I'll go ahead and close this up again.
