### ISSUE TITLE
Using the non-inline form doesn't show the relevant logo as you enter the number

### ISSUE THREAD

**Issue by jjcoffee** [woocommerce/woocommerce-gateway-stripe#509]
#### What I expected

As with the inline form (and the old version of the plugin), the card issuer logo relevant to the number you're typing appears to the right. This increases user confidence in the security of the form with the brand recognition of the card issuer, as well as providing more immediate feedback that the user is typing in the right number.

#### What happened instead

No feedback at all until the user clicks away from the number input field.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
You need to contact Stripe about that. It is implemented by them.
