### ISSUE TITLE
sale amount not split into tax plus subtotal.

### ISSUE THREAD

**Issue by rbrcurtis** [woocommerce/woocommerce-gateway-stripe#513]
#### Affected ticket(s)

NA

#### What I expected

When reviewing orders in Stripe which were placed in woocommerce with this plugin, I would like to see the breakdown of what portion of the sale was tax. Tested with 3.2.3 and 4.0.5.

#### What happened instead

Taxes are not split out in the order summary.

#### Steps to reproduce the issue

Place an order which has tax, then review in stripe.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
What is passed to Stripe is the exact amount being charged.

**Comment by rbrcurtis** [comment]
So, if I understand correctly, the stripe api does not support sending the amount as multiple parts including subtotal and tax?

**Comment by roykho** [comment]
Nope. Only one parameter "Amount". However you can send your own metadata.

**Comment by rbrcurtis** [comment]
Ok, thank you.
