### ISSUE TITLE
Payment Button display issue in combination with flexbox

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-gateway-stripe#514]
When a theme / plugins change the CSS for the `form.cart` element on a single product page to use a flexbox then the payment button shows as just one line, because the `width: 100%` doesn't apply.

![image](https://user-images.githubusercontent.com/11388669/35966128-d786a204-0cb4-11e8-874b-b28f89673ee8.png)

Because the buttons are injected into the HTML and they contain quite a bit of inline CSS with !important it's quite hard to override this layout.

One solution is to add the following CSS rule:

```
#wc-stripe-payment-request-button > div {
    min-width: 100px;
}
```

In this case it's the Fusion Builder from the Avada theme that uses a flexbox, but there could be other themes which also use a flexbox. To test this on any other theme including Storefront, you can just add the following CSS rule to the single product page:

```
form.cart { display: flex; }
```

Is this something which could be added for better theme compatibility?

Affected ticket: 913648-zen

**Comment by roykho** [comment]
Hi @mikkamp is that not something they can just add to their theme CSS? Because I tested this with your proposed CSS solution and it works fine from my theme's CSS file.

**Comment by mikkamp** [comment]
Yes ideally it would be fixed by the themes. I guess this was mainly a query if we thought it would be necessary to add greater compatibility for themes that don't do this.

**Comment by roykho** [comment]
Yeah I think it is best to leave it for themes because during my test with different themes, sometimes the button is squashed with `100px` and sometimes its ok. So it really depends on the theme. So they would have to override it anyways.
