### ISSUE TITLE
White transparent overlay doesn't disappear when card has been refused on Safari iphone

### ISSUE THREAD

**Issue by Alvan-Judi** [woocommerce/woocommerce-gateway-stripe#517]
On the checkout page, when we click on the order button and if the entered credit card is wrong, it display an overlay on the whole page to see that the order is processing. After that, it's scrolling up so we can see the message that said that the credit card has been refused, but the overlay doesn't disappear so we can't do anything. 

I get this issue only on Safari with an iPhone and I don't get any js error in the console when I inspect the page.

EDIT : The white container that is not removed is the .blockUI.blockOverlay created by WooCommerce.

**Comment by Alvan-Judi** [comment]
Excuse me, you closed it because it now resolve or because you don't have this issue ?
I tested it on 2 different site with differents plugin but all with stripe for woocommerce and i got the same issue

**Comment by roykho** [comment]
Resolved. Its in master already and will be in next release.

**Comment by Alvan-Judi** [comment]
Thank you so much, you're perfect !
