### ISSUE TITLE
Process order: Force customer creation no longer working

### ISSUE THREAD

**Issue by townofdon** [woocommerce/woocommerce-gateway-stripe#518]
Hi there!

I have a client who uses the Woocommerce Stripe plugin - their business model is unique in that they need to re-charge customers who purchase items on their Wordpress site, even if the customer does not create an account.

Previously, I was able to add the previous code to force customer creation to always happen:

```
add_filter( 'wc_stripe_force_customer_creation',  '__return_true' );
```

Unfortunately it looks like the 'wc_stripe_force_customer_creation' hook was removed and this is no longer possible. After looking through the code it wasn't immediately obvious if there was another hook.

Is there another way to force customer creation to always occur on payment_process?

Thanks!

**Comment by roykho** [comment]
So this is not a support channel. Please use this for support https://wordpress.org/plugins/woocommerce-gateway-stripe/

**Comment by townofdon** [comment]
Will do, thanks.
