### ISSUE TITLE
Missing translations on inline credit card form

### ISSUE THREAD

**Issue by jranavas** [woocommerce/woocommerce-gateway-stripe#521]
On inline credit card form, the "Card Number", "MM / YY" and "CVC" placeholders have no translations avaliable for translate.

![image](https://user-images.githubusercontent.com/26978267/36011466-b0f32330-0d57-11e8-9810-5ab0cf515533.png)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
This is set by Stripe. I believe it is auto localized based on browser. Also you can hook in a filter to specifically pass a locale.

**Comment by roykho** [comment]
You can try this hook `wc_stripe_elements_options` and documentation is here https://stripe.com/docs/stripe-js/reference#stripe-elements

**Comment by v18** [comment]
To do:
- [ ] check to see if we're sending `auto` for locale, based on this doc: https://stripe.com/docs/stripe-js/reference#stripe-elements
- [ ] write up an example of how to use the above hook ^.

**Comment by allendav** [comment]
Re-opening this issue for the sake of adding a code snippet demonstrating using the hook

**Comment by dougaitken** [comment]
I believe we can add these strings to the POT file or to the Translation project? https://translate.wordpress.org/projects/wp-plugins/woocommerce-gateway-stripe

However, changing my browser to a few languages does auto-translate the placeholder strings such as `Card Number` and `MM / YY`.

**Comment by v18** [comment]
I opened PR #1090 to fix this, and I updated the docs to include a useful snippet:

https://docs.woocommerce.com/document/stripe/#section-32

**Comment by dechov** [comment]
@DanReyLop noted in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/929#issuecomment-519895856 that the default (browser language, as noted and confirmed above) _may_ be preferable after all. Personally I'm not sure what's best, but do we have reason to believe store language is likely to be more suitable?

**Comment by v18** [comment]
Marking this issue closed because those strings in the Stripe credit cards elements are translatable by using the `wc_stripe_elements_options` filter. Documentation for how to use it is here, under the heading "How can I translate the placeholders text inside the credit card form?":

https://docs.woocommerce.com/document/stripe/#section-34
