### ISSUE TITLE
Looping error and unstyled error page: Cannot cancel or delete Subscriptions with a start date in the future.

### ISSUE THREAD

**Issue by s3w47m88** [woocommerce/woocommerce-gateway-stripe#523]
#### What I expected
I created a Subscription. Chose today as the date. And selected Create. Then I had to cancel and delete the Subscription.

#### What happened instead
Instead, I got an error on an unstyled white screen with black text that outputs:

`exception 'Exception' with message 'The cancelled date must occur after the start date. The end date must occur after the start date.' in /home/mysite/public_html/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscription.php:2331 Stack trace: #0 /home/mysite/public_html/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscription.php(1202): WC_Subscription->validate_date_updates() #1 /home/mysite/public_html/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscription.php(500): WC_Subscription->update_dates() #2 /home/mysite/public_html/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscriptions-manager.php(788): WC_Subscription->update_status() #3 /home/mysite/public_html/wp-includes/class-wp-hook.php(286): WC_Subscriptions_Manager::maybe_cancel_subscription() #4 /home/mysite/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters() #5 /home/mysite/public_html/wp-includes/plugin.php(453): WP_Hook->do_action() #6 /home/mysite/public_html/wp-includes/post.php(2661): do_action() #7 /home/mysite/public_html/wp-admin/post.php(222): wp_trash_post() #8 {main}`

However, I did not choose a future date, I chose today's date and it still set the time one hour in the future. As a result I cannot cancel the Subscription.

I don't believe I should get this error at all, and if I have to then it should at least be printed in a proper WP admin notice.

#### Steps to reproduce the issue

See above.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Doesn't seem related to this plugin. Please provide more information as to how you think this is related to Stripe and I will reopen.
