### ISSUE TITLE
Cannot set payment method for Subscription to Stripe card.

### ISSUE THREAD

**Issue by s3w47m88** [woocommerce/woocommerce-gateway-stripe#524]
#### What I expected

When creating or editing a Subscription in WooCommerce > Subscriptions menu there is an option to choose Payment Method. For me, I have Manual and Pay by Card with Stripe enabled. I selected Pay by Card and entered the Stripe Customer ID and the Stripe Source ID for a customer, then completed all other details and attempted to create the order.

#### What happened instead

However, upon saving / creating it always outputs this error: `Error updating some information: A "Stripe Customer ID" value is required.` despite entering a value, and a correct one. Thus I cannot process the transaction.

#### Steps to reproduce the issue

See above.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@s3w47m88 I am not seeing the issue. I just tested and I am able to edit the subscriptions and save NEW data seen here ![](http://cld.wthms.co/jvqVGQ+)

**Comment by roykho** [comment]
Please provide more information and I will reopen if necessary.

**Comment by s3w47m88** [comment]
Hi Roy, thanks for testing. That's interesting that you get a different experience than me. The only thing I can think is that it's related to the specific customer or their src. I will submit this same message to Stripe support and see if they can add anything.

**Comment by itsmrwalsh** [comment]
@s3w47m88 I'm having this same issue, I'm testing changing the payment method on a WooCommerce subscription and despite entering a value stripe Customer ID and Source, I get that message too.

Did you ever get any insight from Stripe support?

**Comment by s3w47m88** [comment]
@itsmrwalsh sadly no. I am convinced this issue is with the Plugin and not Stripe.

**Comment by itsmrwalsh** [comment]
@s3w47m88 what's the rest of your codebase like? Are you fully up to date with WP/Woo/WooSubs?

**Comment by itsmrwalsh** [comment]
@s3w47m88 I ask, as I have just updated the subscriptions plugin, and this solved the issue.
