### ISSUE TITLE
Billing Details not saving to User Profile for future Orders or Subscriptions

### ISSUE THREAD

**Issue by s3w47m88** [woocommerce/woocommerce-gateway-stripe#525]
#### What I expected

If you create a new Subscription and edit the persons Billing or Shipping details, then click Create or Save. Then create or edit another Subscription the user expects the previously entered details to populate.

#### What happened instead

The details appear to be saved to the Subscription but not to the actual User Profile. Therefore they are not loaded the next time.

#### Steps to reproduce the issue

See above.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Sorry can you please explain more? How is this related to Stripe?

**Comment by s3w47m88** [comment]
Hi Roy - I'm happy to but I'm not sure what I can say to be clearer. I included step by step instructions on how to replicate the issue. Hopefully this doesn't sound sarcastic or rude - I appreciate your time and support! :)
