### ISSUE TITLE
Make Stripe Checkout collect Billing Address information

### ISSUE THREAD

**Issue by Luminus** [woocommerce/woocommerce-gateway-stripe#533]
Stripe Checkout (modal) only sends along email address and the token. Apparently, it has the capability to send along the billing details as well but the default setting set by Stripe is for this to be false.

![stripe checkout](https://user-images.githubusercontent.com/248077/36145600-c1b9d556-10a9-11e8-824b-9e67b97ae70d.jpg)

We should enable billing details to be sent by default as it makes it possible to use AVS even if you're using Stripe Checkout and will help deal with issues of Fraud.

Setting `data-billing-address` to **true** as indicated here seems like the way to go about this -  https://stripe.com/docs/checkout#integration-options-billing-address.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Filter already exists for this `wc_stripe_checkout_require_billing_address` just return true on it.

**Comment by joe-westcott** [comment]
@roykho , if we return true for `wc_stripe_checkout_require_billing_address`, Stripe prompts the user for the billing address, state, and ZIP; however, the user just entered this information on the WooCommerce checkout page, so this seems redundant.

Is there a way to change this behavior, and instead use the billing information that the user entered into WooCommerce?

![stripe-collects-address-info-again](https://user-images.githubusercontent.com/13838392/37123507-82b5980a-2232-11e8-916e-47691306962e.png)

**Comment by roykho** [comment]
@joe-westcott not that I know of.

**Comment by joe-westcott** [comment]
Gotcha, thank you. Is there a way to place a feature request, to have Stripe collect the address information from WooCommerce? Asking customers to enter their billing address twice seems problematic -- it's wasteful of the user's time, and it seems likely to lower conversions and increase support requests.

**Comment by roykho** [comment]
@joe-westcott this is not possible is what I am saying. AFAIK. Hence we disabled this feature by default.

**Comment by joe-westcott** [comment]
Stripe collects the customer name and email from WooCommerce fields ... for addresses, is it a limitation of Stripe, where Stripe cannot collect field values from Woo besides those ones? Or is Stripe able to collect additional data, but this a limitation of WooCommerce?

**Comment by joe-westcott** [comment]
You're right! Stripe will collect the customer address when Stripe Checkout is disabled (facepalm) and 'wc_stripe_checkout_require_billing_address' is set to TRUE.

In case anyone else else searches for this information like I did, and comes across this thread:

Stripe will save the customer billing address in an Event in Stripe.

When Stripe Checkout is disabled, Stripe collects credit card information on the WooCommerce checkout page instead of a modal window/dialog. Just writing this down to clarify; I'm sure that most people realize this.

Thanks, @roykho !

**Comment by mikopolis** [comment]
So a year later, I see this is still an "issue". Speaking to WC chat, there are no plans to address this issue. As I see it, the only options are the use the embedded checkout form (bad security implementations) or require the user to enter their address AGAIN (bad UX)... Seems odd to me that this is not considered a big issue.
