### ISSUE TITLE
WCS scheduled action time out of sync with WC Membership

### ISSUE THREAD

**Issue by wscheinhart** [woocommerce/woocommerce-gateway-stripe#538]
WCS v2.2.18 and WC Membership v1.9.6 configured so that Membership duration (expiration) is synced with WCS.

Client purchases new subscription from front-end. WC order complete. Scheduled Action for WCS expiration and WC Membership 'expiring_soon' and 'expiry' are off by 31 minutes and 30 sec (if I have done the math correctly-:).

In the screenshot WCS #25731 and WC Membership #25742 belong the new subscription with v2.2.18.

The other WCS #25697 and WC Membership #25701 was created with v2.2.16 and shows that WCS & WC Membership expiration time is synced even though off by 1 hour from the actual monthly renewal time.

![schedule sync issue between wcs and wc membership](https://user-images.githubusercontent.com/36291155/36181722-eb393bfc-10da-11e8-8bf1-3e1bed4dab64.jpg)

**Comment by roykho** [comment]
Sorry I am not sure I understand the issue fully. Are you saying Stripe is causing an issue here?

**Comment by wscheinhart** [comment]
My bad... posted to the wrong GitHub.. you can remove the ticket.
