### ISSUE TITLE
Seemingly double charge on WC

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gateway-stripe#542]
While testing, I found sometimes the order in WC is logged with double charges. So in the order note it will show it got charged twice but in fact on Stripe, there was only one charge although the logs will show we tried to charge a second time.

In WC order notes.
![](http://cld.wthms.co/EPszNW+)

On Stripe.
![](http://cld.wthms.co/r1egcH+)

![](http://cld.wthms.co/U2hfsX+)
![](http://cld.wthms.co/qYoe6+)

This potentially will sent out emails to customer twice about the order which may cause them to think they've been charged twice! This seems to be related to a race condition between the redirect handler and the webhook. So sending idempotency key to Stripe prevents double charge, however on WC side, it seems we also need to somehow check for "in progress" status so we can lock the order when one process is going on.

cc @thorsten-stripe

**Comment by thorsten-stripe** [comment]
@roykho these are added after a successful charge request, right? In this case you can compare`Original-Request` & `Request-Id` headers in the response, and only add the order notes if they have the same ID.
e.g. 
```
Original-Request: req_AN5GQzQVMKWQxB
Request-Id: req_DnEOJwl4wYgm2K
```
identifies a subsequent request made with the same idempotency key, whereas
```
Original-Request: req_AN5GQzQVMKWQxB
Request-Id: req_AN5GQzQVMKWQxB
```
identifies the original request.

**Comment by roykho** [comment]
Yeah if the parameters are in the headers, it may be a cumbersome to work with. Currently we're just passing the json decoded body after we get the response. To incorporate this check, we would need to restructure the logic a bit. However if this is the only solution, then we would have no choice.
