### ISSUE TITLE
More 3D Secure settings

### ISSUE THREAD

**Issue by jyourstone** [woocommerce/woocommerce-gateway-stripe#543]
#### Affected ticket(s)

None

#### What I expected

To be able to change all settings related to 3D Secure

#### What happened instead

Can only change between require 3D Secure or not.

#### Steps to reproduce the issue

Since Stripe API version 2018-02-06 there are 4 values you can use for the 3D Secure property; recommended, not supported, optional, and required.

It would be great to be able to choose these from a dropdown menu in the Stripe settings, where the 3D Secure checkbox option is now.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@jyourstone can you please link to the info for that on Stripe?

**Comment by jyourstone** [comment]
From their documentation:

Step 2: Determine if the card supports or requires 3D Secure
The behavior of, and support for, 3D Secure can vary across card networks and types. For cards that are not supported, perform a regular card payment instead.

Some card issuers, however, require the use of 3D Secure to reduce the risk for fraud, declining all charges that do not use this process. So you can best handle these different situations, check the card.three_d_secure attribute value of the card source before continuing with the 3D Secure process.

VALUE	DESCRIPTION
required	3D Secure is required. The process must be completed for a charge to be successful.
recommended	3D Secure is recommended. The process is not required, but you can be covered by liability shift with a minimal impact to your conversion rate.
optional	3D Secure is optional. The process isn’t required but can be performed to help reduce the likelihood of fraud.
not_supported	3D Secure is not supported on this card. Proceed with a regular card payment instead.
At this stage, you can either proceed with the rest of the 3D Secure process below or perform a regular card payment (if 3D Secure is not supported). If you need to make use of subscriptions, continue to our 3D Secure and Subscriptions documentation.

Page link: https://stripe.com/docs/sources/three-d-secure

**Comment by jyourstone** [comment]
According to the Stripe documentation, optional is different from recommended.

What I propose is to simply add the recommended option in the Stripe plugin settings.

**Comment by roykho** [comment]
I don't mean Stripe says optional and recommended are same. I mean our plugin treats it as the same. So if you have it on "required", it will put both recommended type and optional type through the 3DS auth.

**Comment by jyourstone** [comment]
I see. 

Personally I'd like to have the recommended option as well though, since I don't want to force 3D Secure if it isn't recommended but don't want to skip it either because of liability.

**Comment by roykho** [comment]
So your gripe here is that you rather NOT put cards that are optional through the 3DS auth but do want it for "recommended" type cards is that correct?

The way it is now is we're erring on the side of protection hence if set to required, we would like to put both recommended types and optional types through the 3DS auth as in the documentation says "..helps to reduce fraud".

**Comment by roykho** [comment]
In addition, are you seeing issues here is why this was raised? Are you getting conversion issues with optional types not seeing through the checkout process?

**Comment by jyourstone** [comment]
So your gripe here is that you rather NOT put cards that are optional through the 3DS auth but do want it for "recommended" type cards is that correct?

Yes that is correct. 

I'm not having any issues atm but if "Recommended" was an option I would choose that. So it's a low priority feature request.

**Comment by roykho** [comment]
This has been added to 4.1.

**Comment by jyourstone** [comment]
That's great! Thank you!
