### ISSUE TITLE
Order status not changing to Failed

### ISSUE THREAD

**Issue by jyourstone** [woocommerce/woocommerce-gateway-stripe#544]
#### Affected ticket(s)

None

#### What I expected

When a purchase fails for some reason, the order status should be set to "Failed" in WooCommerce.

#### What happened instead

When a purchase fails, the status in WooCommerce never changes from "Pending payment".

#### Steps to reproduce the issue

Make a test purchase with a card that is declined (card number 4000000000000002) and the order status never changes to "Failed".

I've tested both live and test keys and also added the webhook in the Stripe Dashboard according to the settings, but still no luck. I've also disabled cache, cleared cache and disabled my anti spam plugin.

The strange this is that I do receive an e-mail that an order was failed, so everything seems to work except that the order status never changes from "Pending payment" to "Failed" and the WooCommerce log files does not display any errors.

#### Using

WordPress 4.9.4
WooCommerce 3.3.1
WooCommerce Stripe 4.0.5
Stripe API 2018-02-06

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@jyourstone I have tested this according to your steps and this is what I get. ![](http://cld.wthms.co/xahnWL+) ![](http://cld.wthms.co/lnCEst+)

**Comment by jyourstone** [comment]
I'll do some more testing to try and figure out why the status isn't set to Failed for me.

**Comment by roykho** [comment]
Closing for now. Feel free to add more information to this and I will reopen.

**Comment by jyourstone** [comment]
@roykho I did some more testing and found out that if the setting "Require 3D Secure when applicable" is unchecked, then the order status never changes when a payment fails.

If I activate that setting, then the order status changes to failed.

**Comment by jyourstone** [comment]
Also, I didn't have logging enabled in Stripe settings so that's why I couldn't see any logs in WooCommerce for Stripe. Here's a log for a failed transaction when the option I mentioned isn't checked.

02-19-2018 @ 14:13:10 - ====Start Log====
sources/src_1BxES9B65dpkNq3zDIbkUCya
====End Log====


02-19-2018 @ 14:13:11 - ====Start Log====
Info: Begin processing payment for order 2343 for the amount of 140.00
====End Log====


02-19-2018 @ 14:13:11 - ====Start Log====
charges request: Array
(
    [currency] => sek
    [amount] => 14000
    [description] => Yourstone Keramik Staging - Order 2343
    [statement_descriptor] => Yourstone Keramik Stag
    [capture] => true
    [expand[]] => balance_transaction
    [metadata] => Array
        (
            [kundens_namn] => ***
            [kundens_epost] => ***
            [order_id] => 2343
        )

    [customer] => cus_AAS5tyT8yFfZg0
    [source] => src_1BxES9B65dpkNq3zDIbkUCya
)

====End Log====


02-19-2018 @ 14:13:13 - ====Start Log====
Error: stdClass Object
(
    [error] => stdClass Object
        (
            [message] => Your card was declined.
            [type] => card_error
            [code] => card_declined
            [decline_code] => generic_decline
            [charge] => ch_1BxESCB65dpkNq3zij1JOOJA
        )

)

====End Log====


02-19-2018 @ 14:13:17 - ====Start Log====
Could not find order via charge ID: ch_1BxESCB65dpkNq3zij1JOOJA
====End Log====
