### ISSUE TITLE
When saving settings, error notices don't appear until subsequent page load

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-gateway-stripe#546]
Settings errors aren't appearing upon saving the settings — only on the next page load.

To reproduce, set live key to something invalid (e.g. 'abc'), save, and there is no error. Remove live key, save, and an error pertaining to the invalid key appears: _"[...] your test keys may not be valid."_:

<img width="1023" alt="screen shot 2018-02-15 at 4 26 24 pm" src="https://user-images.githubusercontent.com/1867547/36281823-10d29762-126d-11e8-86fd-576069361e31.png">

(Simply refreshing also properly updates the notice.)

**Comment by roykho** [comment]
@dechov happy to wait for your PR to fix this. :)
