### ISSUE TITLE
Add Option to accept Sofort.com immediately

### ISSUE THREAD

**Issue by tilocgn** [woocommerce/woocommerce-gateway-stripe#547]
This is more a feature request than an issue. 

Could you please add an option to immediately accept Sofort Banking payments. Right now it takes a couple of hours to a day for the payment being marked as accepted and that is not what the user expects and what the brand name "Sofort" suggests. 

Right now I'm using the Marketpress Sofort plugin which offers this very feature but i would love to consolidate the payment options to stripe. This is a screenshot of the option in their plugin:

![grafik](https://user-images.githubusercontent.com/11157110/36304398-ce263f1a-130f-11e8-8079-41d408b841ff.png)

Anyways, Thanks a lot for your work and the great plugin and especially for v. 4.0!

**Comment by roykho** [comment]
cc @thorsten-stripe is this possible?

**Comment by thorsten-stripe** [comment]
@tilocgn @roykho I'm afraid that there is a chance for SOFORT charges failing (although it's fairly small ~0.2% of transactions). However, because of this, SOFORT is modeled as an asynchronous method, initially pending and then resolving to either succeeded or failed.

Theoretically you could mark an order with a pending SOFORT charge as succeeded/processing, however this means that the merchant would have to take on the risk of sending out products for a charge that might fail.

**Comment by roykho** [comment]
Yeah I don't think it is a good idea to change an order to "payment completed" when it really is not. For now if you really need to change the behavior of this, you can use the hook here to manipulate the order status https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L338

**Comment by tiloru** [comment]
@roykho @thorsten-stripe Are there maybe any news on this? I see a lot of people online [complaing](https://wordpress.org/support/topic/sofort-payment-not-being-registered-order-stays-on-hold/) about this very problem and i think it would be fair to let the shop owner decide if they want to take the risk of losing ~0.2% of their sofort orders payments. After a short research i feel like this could be "fixed" really fast.

PS. Did you know that approximately 4.1% of all US death sentences are wrongfully convicted ([source](http://time.com/79572/more-innocent-people-on-death-row-than-estimated-study/)) and yet they are still doing it!

**Comment by optimiertes** [comment]
I absolutely agree with @tiloru 
The whole purpose of SOFORT is lost. The purpose is to not wait until the bank transaction is actually completed, but the SOFORT process is to make sure the transaction is correctly initiated. 
This is similar to asking

**Comment by optimiertes** [comment]
@roykho Would you be willing to share a code snippet with the filter to achieve this?

**Comment by optimiertes** [comment]
I am now using this code in the `functions.php` to automatically mark orders which were paid with Stripe Sofort as completed. I wish this is also useful to others. 

```
add_action( 'woocommerce_thankyou', 'custom_woocommerce_auto_complete_order' );
function custom_woocommerce_auto_complete_order( $order_id ) { 
    if ( ! $order_id ) {
        return;  
    }

    $order = wc_get_order( $order_id );  

    if($order->get_status() == 'on-hold' && $order->get_payment_method() == 'stripe_sofort')    {
         $order->update_status( 'completed' );
    }   
}
```

**Comment by tiloru** [comment]
Thanks for sharing! I've also been building my own code but i had not shared it yet because i wasn't able to test it. But i'll also share it so we can come up with the best possible solution for everybody. 

It's pretty much the same, i just feel like `$order->payment_complete()` might be better to use than `$order->update_status( 'processing' )`. 

```
add_action( 'woocommerce_thankyou', 'sofort_auto_complete_order' );
function sofort_auto_complete_order( $order_id ) {
    
    // Return if order id is missing
    if ( ! $order_id ) {
        return;
    }
    
    // $order = new WC_Order( $order_id );
    $order = wc_get_order( $order_id );
    
    // Return if payment method is not stripe_sofort or if order status is not on-hold
    if ( 'stripe_sofort' !== $order->get_payment_method() || 'on-hold' !== $order->get_status() ) {
        return;
    }    
        
    // Complete order payment
    // other possible option: $order->update_status( 'processing' );
    $order_payment_complete = $order->payment_complete();
    
    // Add an order note
    if ($order_payment_complete === TRUE) {
        $order->add_order_note( __( 'Sofort Payment completed automatically.', 'woocommerce' ) );
    } else {
        $order->add_order_note( __( 'Sofort Payment failed automatic completion.', 'woocommerce' ) );
    }

}

```

**Comment by BastianBoehm** [comment]
Thank you very much for this @tiloru and @optimiertes !

I just had to add a high priority to the action, since otherwise it only fired after manually refreshing the thank you page:
add_action( 'woocommerce_thankyou', 'sofort_auto_complete_order', 1, 1 );

SOFORT really should change their name to DEMNÄCHST or something, this way it's just confusing.


Cheers

**Comment by XdekHckr** [comment]
> @tilocgn @roykho I'm afraid that there is a chance for SOFORT charges failing (although it's fairly small ~0.2% of transactions). However, because of this, SOFORT is modeled as an asynchronous method, initially pending and then resolving to either succeeded or failed.
> 
> Theoretically you could mark an order with a pending SOFORT charge as succeeded/processing, however this means that the merchant would have to take on the risk of sending out products for a charge that might fail.

Is there still chance that sofort payment might fail? I think I have never seen sofort payment that failed in stripe. I saw only payments that are "incompleted" or "expired".
