### ISSUE TITLE
Internal server error after update to 4.05

### ISSUE THREAD

**Issue by tvrhossain** [woocommerce/woocommerce-gateway-stripe#548]
#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by tvrhossain** [comment]
it was just working well last day with STRIPE TEST mode, suddenly it is now giving me Internal Server Error after I try to pay.

**Comment by roykho** [comment]
Not a support channel. Please post your support question here https://wordpress.org/plugins/woocommerce-gateway-stripe/
