### ISSUE TITLE
Striped Checkout Issue: "Payment processing failed. Please retry."

### ISSUE THREAD

**Issue by vannigoc** [woocommerce/woocommerce-gateway-stripe#549]
I get an error when I try to checkout with Stripe. 
Error message: "Payment processing failed. Please retry."
This is the first time I've having this issue and it started just after I downgraded to woocommerce 3.2.6 (after an [abnormal cpu usuage issue caused by woocommerce 3.3.2](https://github.com/woocommerce/woocommerce/issues/19008) regenerating thumbnails).

Steps I took to try to solve this:
Downgraded to older versions of Woocommerce Stripe Gateway
Deactivated all plugins
Changed Themes
Clear Cache
Updated API
Changed API Keys

Error log:
02-18-2018 @ 08:16:08 - ====Start Log====
Error: stdClass Object
(
    [token_id] => 
    [customer] => 
    [source] => 
)

====End Log====

02-18-2018 @ 09:11:32 - ====Start Log====
Error: stdClass Object
(
    [token_id] => 
    [customer] => 
    [source] => 
)

====End Log====

**Comment by alimoshen** [comment]
Are you loading the checkout page via AJAX by any chance? I was getting the same issue because loading the shortcode in an AJAX loaded page won't load all the necessary JS files and Stripe won't work.
