### ISSUE TITLE
SEPA emails get sent only in English from support@stripe.com, no option to change this or disable email notifications from Stripe

### ISSUE THREAD

**Issue by germanoronoz** [woocommerce/woocommerce-gateway-stripe#550]
When creating the mandate there are some parameters that can be sent to Stripe's API, like disabling the email notifications from them or setting up the notification language.

After contacting Stripe, they referred me to this docs:
https://stripe.com/docs/sources/sepa-debit#prerequisite

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Please post your support question here https://wordpress.org/plugins/woocommerce-gateway-stripe/

**Comment by germanoronoz** [comment]
​Ok, but this is a development issue, what was wrong?

Sorry for any inconvenience.

Regards​


2018-02-19 16:54 GMT+01:00 Roy Ho <notifications@github.com>:

> Please post your support question here https://wordpress.org/plugins/
> woocommerce-gateway-stripe/
> <https://mailtrack.io/trace/link/2c39e3f85a885b8d4e8034c8062df2c2bdab6fa1?url=https%3A%2F%2Fwordpress.org%2Fplugins%2Fwoocommerce-gateway-stripe%2F&userId=1542364&signature=67f547171059a55b>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/b9c2ce0512be2ab427d8b46be239ba2eedcb60a1?url=https%3A%2F%2Fgithub.com%2Fwoocommerce%2Fwoocommerce-gateway-stripe%2Fissues%2F550%23issuecomment-366733148&userId=1542364&signature=74dc824b7429d2ca>,
> or mute the thread
> <https://mailtrack.io/trace/link/8c76247c605437a8d855d696a423308101220712?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATuQDHp3UsPP0fvkkzhZsqZRaO9lzjIxks5tWZk1gaJpZM4SKwla&userId=1542364&signature=26f114cbaac08f52>
> .
>



-- 
Germán Oronoz CEO

-- 
 


   


    Ctra. N-1 KM.444 Polígono Ubegun, 
    Pabellón ISARO, 20150 *Villabona, Gipuzkoa* 

    *T* | 943 693 158    *F* | 943 696 220 




    *pom.es* <https://pom.es/>   |   *pomstandard.com* 
<https://pomstandard.com/> 

   <https://www.instagram.com/pomdiseno/> 
<https://www.facebook.com/pomdiseno> <https://twitter.com/pomdiseno/> 
<https://www.youtube.com/channel/UCnkHztkqcQQeOYXlY--2QYg> 
<https://www.linkedin.com/company/pom-dise-o-integral> 



* Este correo electrónico se dirige únicamente a la persona o la entidad 
arriba indicados y la información incluida es confidencial. Si usted no es 
el receptor, debe saber que la divulgación, copia, distribución, o 
cualquier otro uso de la información contenida queda estrictamente 
prohibido. Si usted ha recibido esta transmisión por error, por favor 
notifíqueselo al remitente inmediatamente por correo electrónico a la 
dirección del encabezado y elimínelo de su sistema. El contenido del 
mensaje y/o anexos no reflejan necesariamente la opinión de la entidad de 
origen, el remitente o sus representados. El correo electrónico no permite 
asegurar la confidencialidad de los mensajes que se transmiten ni su 
integridad o correcta recepción. El remitente no asume responsabilidad por 
estas circunstancias. This e-mail transmission is intended only for the use 
of the individual or entity named above and the contain information is 
confidential, privileged, and/or exempt from disclosure under applicable 
law. If you are not the intended recipient, you are hereby notified that 
any review, disclosure, copying, distribution, or other use of any of the 
information contained in this transmission is strictly prohibited. If you 
have received this transmission in error, please immediately notify the 
sender by e-mail at the above address and delete it from your computer 
system; you should not copy the message or disclose its contents to anyone. 
The content of the message and or attachments may not reflect the view and 
opinions of the originating company or any party it is representing. The 
electronic mail neither guarantees the confidentiality of the messages, nor 
the integrity, or correct receipt. The sender does not assume any liability 
for those circumstances. *
