### ISSUE TITLE
3ds on saved cards

### ISSUE THREAD

**Issue by offenb** [woocommerce/woocommerce-gateway-stripe#552]
As standard Stripe does not attempt 3ds on saved cards (so their docs and support tell me)

Support advise the following to have 3ds on transactions that use saved cards:

"when you create a charge on a saved 3D Secure card we do not by default authenticate the card each time a new charge is created. You do, however, have the option of creating a 3DS source and authenticating each time the customer goes to purchase. To do this you create a new 3DS source from the stored card source as you would for a new card source, using the stored card source object in place of a new card source:

- https://stripe.com/docs/sources/three-d-secure#create-3ds-source

**Comment by roykho** [comment]
We will not implement that at this time as I believe it defeats the purpose of a saved card if they have to go through the 3DS auth again. Might as well just punch in the CC # again then. Also this does not work well with subscription based models where recurring charges need to occur.

**Comment by offenb** [comment]
Your belief is not shared by the biggest retailers in UK where 3DS is very established.   Two I have seen recently, Tesco (a walmart like retailer) and British Airways both do 3DS on stored cards.   

I didn't post Stripe's full response which went on to say it didn't impact subscriptions - here it is:

"The time where this doesn't happen is where a subscription is charged to a 3DS card. When that's the case, the customer isn't actively making the charge at the time of billing and doesn't have the ability to authenticate the card. In this case you charge the card without creating a 3DS source first. Because it has already been authenticated when creating the first charge, issuers are willing to forgo the authentication requirement for subsequent subscription charges since these represent the same amount at regular intervals."

**Comment by roykho** [comment]
I completely understand others may be doing it. Hence I said, we will not be implementing at this time. So perhaps in the future.

**Comment by offenb** [comment]
Just so you are aware there are a whole load of cards (albeit outside the US) that  3d secure is mandatory for.    

Maybe woocommerce is just intended for use in North America?

The ones I am aware of mandating 3DS include Maestro debit cards (mastercard debit brand) in the EU, Italian visa cards and all Indian debit cards.

Half of EU debit cards and all Indian debit cards could be as many as 1.2 billion card holders who will be unable to checkout on woocommerce stores that save cards.....

**Comment by roykho** [comment]
Yes I understand hence this will be considered but won't be until at least version 4.1.

**Comment by roykho** [comment]
This has been implemented and will be in 4.1 release.
