### ISSUE TITLE
Perf: Cache bypassing due to cookie on every page load

### ISSUE THREAD

**Issue by mvpspl619** [woocommerce/woocommerce-gateway-stripe#556]
#### Affected ticket(s)

No ticket created via WooCommerce support.

#### What I expected

That the WooCommerce session cookie is set only when needed.

#### What happened instead

This extension is setting session cookie on `woocommerce_init` action, which triggers on every page load. This will disable certain types of cache including Varnish and ones set by hosting like Pagely.

#### Steps to reproduce the issue

1. Run `curl -I https://ameda.mabblystaging.site`
2. You will see `set-cookie` header
3. Go to https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/payment-methods/class-wc-stripe-payment-request.php#L103 to verify this code. 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@mvpspl619 thanks for reporting and this is already known issue. But no solution at this time. Do you have any ideas?

**Comment by mvpspl619** [comment]
@roykho I'm afraid to suggest any solutions, but looks like WooCommerce only sets the session cookie when adding products to cart using the action `woocommerce_set_cart_cookies`. 

Why does the Stripe Gateway plugin need to have the session cookie anywhere else apart from the Checkout page? Or maybe find a way to know if a given page is loading the Stripe gateway extension and then add the cookie if it doesn't exist?

**Comment by roykho** [comment]
Because in order to use nonce via AJAX, you need to have a user session. And Payment Request Button requires AJAX on page load. Sure we could limit it to the product page however that would only solve part of the problem.

**Comment by mvpspl619** [comment]
You’re right that the setting cookie only from Product Pages would solve part of the problem. But that would definitely help.

Are there other ways of using AJAX without having to set a cookie?

Thanks,
Raju

Want to meet with me?

**Comment by roykho** [comment]
In order to verify nonce, there has to be a session created.

**Comment by mvpspl619** [comment]
How about we start with only setting it from the Product Page?

**Comment by mvpspl619** [comment]
Thank you @roykho

**Comment by mvpspl619** [comment]
@roykho Any idea when this will be deployed with `4.0.8`? We are getting closer to launch and would to take necessary precautions for caching if we're unable to use this version with launch

**Comment by roykho** [comment]
@mvpspl619 no ETA at this time however if urgent, you can always use it off master branch.

**Comment by mikeyarce** [comment]
@roykho this also fixes another issue I found today.  
On some hosts, if you go to `http://yourgroovydomain.com/cart/?add-to-cart=8` on a fresh browser with no cookies or sessions - it would just redirect to show you an empty cart.   When I apply this fix it does add an item to the cart properly.
