### ISSUE TITLE
Descriptions Box Will Not Disappear When Empty on Checkout Page

### ISSUE THREAD

**Issue by EricaKuschel** [woocommerce/woocommerce-gateway-stripe#558]
#### Affected ticket(s)

977822

#### What I expected

When clearing out the Description box in the Stripe settings, it removes the Description field on the Checkout page.

#### What happened instead

A box/field appears under the Stripe credit card icons on the Checkout page. All other payment gateways remove the box when there is no description.

COD with no description: 

![image](https://user-images.githubusercontent.com/6961918/36635452-801be92a-197a-11e8-8b43-739fe1aa0038.png)

Stripe with no description: 

![image](https://user-images.githubusercontent.com/6961918/36635462-a60b3c1c-197a-11e8-9126-e983da9dec2f.png)

#### Steps to reproduce the issue

1. Select Stripe as your payment gateway.
2. Clear out the description field. 
3. Save.

Reproduced on my test site with Storefront, WooCommerce, and Stripe only.

Thanks!

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@EricaKuschel are you referring to the background color over extending? Could this be because Stripe is last on the list? Have you tried putting COD as the last one without description?

**Comment by roykho** [comment]
@EricaKuschel nvm, I see what you're referring to now however this is not something we can fix as WC core generates a div container that in turn is controlled by JS to slide in/out when the gateway is selected. COD doesn't have that issue is because it doesn't have payment_fields method like Stripe does.

**Comment by EricaKuschel** [comment]
Thank you for that explanation, @roykho!
