### ISSUE TITLE
Required fields will not be validated before Stripe Modal Checkout

### ISSUE THREAD

**Issue by thomas-zg** [woocommerce/woocommerce-gateway-stripe#559]
#### What I expected

The required checkout fields will not be validated in WC 3.3. The popup will be shown but the e.g. phone number is empty.

#### Steps to reproduce the issue

1. Clean install of Woocommerce and the Stripe plugin, enable Stripe Checkout
2. Install Storefront as default theme
3. Add some products
4. Add a product to the cart and go through the checkout, let a required field empty
5. Stripe modal window will be shown, the validation of the empty required field will not be processed

<img width="989" alt="grafik" src="https://user-images.githubusercontent.com/25877146/36642717-f8a312d2-1a43-11e8-979b-c2964f1e8aa6.png">

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Please have a read here and in the changelog.txt file.
