### ISSUE TITLE
Add 3D Secure

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gateway-stripe#56]
As of this writing, 3D secure is in beta. Adding this would be a good feature.

**Comment by quasel** [comment]
example from stripe - https://jsfiddle.net/ywain/1j9om08b/

**Comment by romful** [comment]
Yes it would be a very good feature, specially for European countries !  Got many requests for adding 3D Secure to Stripe..

**Comment by quasel** [comment]
https://github.com/tschaeff/3d-secure-stripe-demo/blob/gh-pages/3d-secure-demo.js

any progress?

**Comment by quasel** [comment]
I can now request 3DSecure for my account - any progress? 💯

**Comment by jyourstone** [comment]
I can also request 3DSecure for my account now and would like to have this as an option.

**Comment by manudbustamante** [comment]
Will be great to have 3D secure in Stripe for Woocommerce Plugin.

**Comment by noordawod** [comment]
+1

**Comment by aelsharawi** [comment]
Any progress?

**Comment by soulstyle** [comment]
+1 This is starting to be a problem for my customers. More and more cards are declined.

**Comment by deichmann** [comment]
@aelsharawi @soulstyle i used the WooStripe.com extension and it worked perfectly for 3D Secure

**Comment by kesonite** [comment]
+1 This is a must, many cards are being declined because of this

**Comment by aelsharawi** [comment]
yes, this shall be most priority please

**Comment by hedqvist** [comment]
+1 this is a must-have. Any news on this?

**Comment by spraveenitpro** [comment]
Some more interest on this in the forums https://wordpress.org/support/topic/3d-secure-6/ @mattyza  @roykho

**Comment by roykho** [comment]
Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0

**Comment by tommybds** [comment]
Hello, when do the 4.0.0 branch will be in final version ? I want 3dsecure too but with the beta I have a "PAYMENT PROCESSING FAILED. PLEASE RETRY." message, either in test or live mode.

**Comment by roykho** [comment]
@tommybds when did you last download from 4.0 branch? If it is more than 1 week ago, then it is already stale. Try downloading it today and re-test.

**Comment by tommybds** [comment]
I downloaded it yesterday

**Comment by Sb10127** [comment]
@roykho @tommybds  does version 4.0 force 3d secure on payments? and is it stable?

**Comment by jyourstone** [comment]
There's an option to force 3D Secure for all cards that support it, otherwise it seems that it's only used for cards that require 3D Secure.
It's still in Beta so I wouldn't use it on a live site.

**Comment by Sb10127** [comment]
@jyourstone thanks for the clarification. Any idea on a general release for version 4.0?

**Comment by Cafnio** [comment]
Any ETA on the release of this one? Or is there any way to test out the beta myself, to check if it's good for live?

**Comment by simon-3t** [comment]
You can try the last released 4.0.0-rc-1 . I am using it on my website, 3D secure work. No problem

**Comment by Cafnio** [comment]
@simon-3t how can I do it? Thanks!

**Comment by jyourstone** [comment]
You can download it from here: https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0
Just click "Clone or download" and then "Download ZIP" and upload the files to your webserver.
Keep in mind that it's a beta though, so there could be issues.
