### ISSUE TITLE
Enhancement: show Stripe fees on new order admin email notification

### ISSUE THREAD

**Issue by galbaras** [woocommerce/woocommerce-gateway-stripe#562]
Can you please add the Stripe fees, which are already available in the order meta data, somewhere on the order notification email sent to the store administrator?

Of course, the customer should never see this information.

Thank you!

**Comment by roykho** [comment]
Can you please post this here http://ideas.woocommerce.com/forums/133476-woocommerce

**Comment by galbaras** [comment]
This idea is not for WooCommerce. It's for the Stripe gateway.

Could you maybe suggest some email action code to use in the meantime? For some reason, although the plugin adds custom meta fields for the net revenue and fees, these are not picked up by the woocommerce_email_order_meta action (see [here](https://github.com/woocommerce/woocommerce/blob/f5492cc50a1c4b9ba96edecb6ab55da93ee81c72/includes/class-wc-emails.php)).

It looks like I could use the woocommerce_email_order_meta_fields filter to add the Stripe keys, but I'm not sure how to do this, so a little help will be highly appreciated.

**Comment by roykho** [comment]
Please go to that link and look at the sidebar. You will see its not just for WC core.

**Comment by galbaras** [comment]
Please suggest the filter/action code and let's test it. Other people may not like this idea, but I need it and would appreciate the help.
