### ISSUE TITLE
Copy on SEPA subscriptions/pre-orders page should reference SEPA IBAN and not card

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#565]
#### Affected ticket(s)

978890-zen

#### What I expected

When using SEPA as a Subscription or Pre-Order payment method, I expect any reference to it to be about the SEPA rather than a payment card method

#### What happened instead

Text on payment methods page has this text ```Via ... card ending in ....```

#### Steps to reproduce the issue

Use SEPA for Subscription or Pre-Order and it will use this file woocommerce/woocommerce-gateway-stripe/blob/master/includes/compat/class-wc-stripe-sepa-compat.php#L409

Can we update any copy when using SEPA to mention something like ```Via ... SEPA IBAN ending in %2$s``` ?

cc @hannahswain @rynaldos 
-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@dougaitken can you please show me a screenshot of this?
