### ISSUE TITLE
Option to disable SEPA mandate notifications

### ISSUE THREAD

**Issue by pzecher** [woocommerce/woocommerce-gateway-stripe#567]
Follow up for https://github.com/woocommerce/woocommerce-gateway-stripe/issues/469

Please add the option to set `mandate[notification_method]` to `none` for business that have their own emailing system and would like to use internal templates

**Comment by roykho** [comment]
There is already an option for that https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L442

**Comment by thorsten-stripe** [comment]
@roykho Maybe it's worth adding this to the `Stripe SEPA Direct Debit` admin settings?

**Comment by roykho** [comment]
@thorsten-stripe we don't add options unless there is a high demand for the feature usually captured by our ideas board.
