### ISSUE TITLE
Error: Payment processing failed. Please retry.

### ISSUE THREAD

**Issue by broc93** [woocommerce/woocommerce-gateway-stripe#569]
Hello,
I'm testing Stripe integration with the latest version of Woocommerce, Wordpress and the Stripe plugin. I set everything up and I get this error each time I try to complete a test payment: **Payment processing failed. Please retry.**

I enabled debugging and here is what I see in the logs:

```
03-06-2018 @ 21:56:54 - ====Start Log====
Error: stdClass Object
(
    [token_id] => 
    [customer] => 
    [source] => 
    [source_object] => 
)

====End Log====
```

I tried disabling all plugins and it still doesn't work.
I see no JS errors on the checkout page also.
Can you please help?

The website in question is prodotti-dietahlife.it

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Not a support channel.
