### ISSUE TITLE
Partial refund is processed twice.

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gateway-stripe#570]
Reported here https://wordpress.org/support/topic/shipping-refund-email/#post-10058028

**Comment by roykho** [comment]
Did many testing and unable to replicate the customer's issue. Will re-open if needed.

**Comment by MANOJMANI07** [comment]
I had also come across a similar issue. We did partial refund through woocommerce admin order page via stripe option for refund. Although it resulted in partial refund on stripe but in woocommerce order page, the refund has been shown twice and status of the order has been changed to refunded as according to woocommerce the whole amount has been refunded. So there is two refunds in the woocommerce, one with refund reason as we mentioned and other with a reason as refund via stripe dashboard. In the private note of the order also, there are two notes referring for same stripe transaction id for refund but with a different reason as mentioned earlier.
