### ISSUE TITLE
order_id should use custom order numbers (if available)

### ISSUE THREAD

**Issue by tarkan123** [woocommerce/woocommerce-gateway-stripe#571]
Hi,

Just started to use this plugin and stripe.

I noticed that this plugin sends the post_id of the order as the order_id in the charge request array.

We use the Sequential Order Numbers plugin so the post_id does not mean anything to us and when we try to reconcile stripe (using their csv export) against our orders on woocommerce the order numbers do not match.

I suggest the order_id sent in the charge request should be the sequential order number used by woocommerce.

Each metadata entry in request is given a row on the export CSV - which then allows us to reference the order. 

Currently we are stripping the description field to get to the sequential order number for reconcile purposes.

e.g.
***************************************
charges request: Array
(
    [currency] => gbp
    [amount] => 2300
    [description] => domain.com- Order 1109107   <- ** sequential order number
    [statement_descriptor] => CompanyName
    [capture] => false
    [expand[]] => balance_transaction
    [metadata] => Array
        (
            [customer_name] => Name Surname
            [customer_email] => my.email@domain.com
            [order_id] => 76150     <- ** this should be sequential order number
        )

    [source] => src_1******************
)

**Comment by roykho** [comment]
Thanks for reporting. Fixed. Will be in next release.
