### ISSUE TITLE
Billing address not saved as part of source when using Stripe modal.

### ISSUE THREAD

**Issue by robman87** [woocommerce/woocommerce-gateway-stripe#572]
The reason to include it is to be able to use it in Radar rules for AVC validation to prevent fraudulent payments.

I believe it could be because owner info which contains billing address is not passed to stripe.createSource when using modal or am I missing something?

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/e3a5fe2261247edac2fe1fd6348cd7cc54d3f9df/assets/js/stripe.js#L311

stripe.createSource( {
	type: 'card',
	token: res.id,
} ).then( wc_stripe_form.sourceResponse );

Here the info is passed.

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/e3a5fe2261247edac2fe1fd6348cd7cc54d3f9df/assets/js/stripe.js#L400

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/e3a5fe2261247edac2fe1fd6348cd7cc54d3f9df/assets/js/stripe.js#L432

It's important to send as much information as possible to Stripe so their systems can perform checks and detect frauds.

Thanks for your great work with this plugin, really like that it's improved and updated frequently.

**Comment by roykho** [comment]
As far as I know/tested in the past, there is no way to pass that info when using Stripe Checkout. The only way is to enable the address fields but that makes for poor UX as customers would have to type their info twice. If you know a way, comment back and I will re-open this.

**Comment by joe-westcott** [comment]
Regarding the poor user experience, here are two potential workarounds:

1. One could collect addresses in Stripe Checkout, and not collect them in WooCommerce. The `woocommerce_billing_fields` filter lets you remove the address fields from WooCommerce, so the user only has to enter their information once, in Stripe Checkout.

@roykho , in theory it's possible to add an option to the Stripe gateway plugin, prompting the site admin to disable address collection in Woo, if the Stripe Checkout option is enabled.

2. Or if one needs to save addresses in WooCommerce, but wants the look and feel of Stripe checkout, then it would be possible to update the WooCommerce checkout form to ask for billing address and credit card info in a modal ("pop-up") window.

It would be possible to create a modal window in WooCommerce, using JavaScript and CSS, which looks like Stripe Checkout, but is actually just the WooCommerce checkout form.

This could help improve sales and donations for site owners, compared to the standard inline checkout options in Stripe for WooCommerce. I say this based on conversion testing I've done with other forms, in which the two-step form almost always yielded better conversions, in a statistically significant way.

---

I suppose this is sort of a feature request, to add these features to the Stripe for WooCommerce plugin.

Although it's possible for developers to create these workarounds themselves, it would be wonderful if these were a core part of the Stripe for WooCommerce plugin, to address the need that several people have expressed for the ability to collect addresses into Stripe.

(Passing thought: are you hiring for on-demand help? I could build these workarounds for you.)

**Comment by roykho** [comment]
> One could collect addresses in Stripe Checkout, and not collect them in WooCommerce. The woocommerce_billing_fields filter lets you remove the address fields from WooCommerce, so the user only has to enter their information once, in Stripe Checkout.

Not sure how that would because what about shipping address? Do they then fill out the shipping on the checkout form and later fill out billing on the popup?

Stripe checkout is definitely not a favorable checkout flow within WC context. We may even decide to remove this feature in the future.

**Comment by roykho** [comment]
Although not entirely related as this issue is about passing address for Radar check, still some relevance https://github.com/woocommerce/woocommerce-gateway-stripe/issues/578

**Comment by joe-westcott** [comment]
If you enable _both_ shippingAddress: true and billingAddress: true , then Stripe can collect both billing and shipping address. It will even ask whether billing and shipping are the same, to save the customer / donor from extra work.
