### ISSUE TITLE
Payment method rendering: display expiration date

### ISSUE THREAD

**Issue by Xowap** [woocommerce/woocommerce-gateway-stripe#573]
## Feature request

When the payment method is rendered, it displays the `last4` field (which are the last 4 digits of the card). I'm specifically talking about the output of `\WC_Stripe_Compat::maybe_render_subscription_payment_method`

An option to choose between displaying the last 4 numbers and the expiration date would be welcome, as this seems to be a good practice as well (by example, Amazon does it).

I would gladly implement it myself, but I want to discuss it here before going the wrong way.

- Would it make sense for this project to have this feature?
- If so, where would you put the settings and under which form?

Thanks!

**Comment by roykho** [comment]
Unfortunately this is not practical. People can have more than one card with same exp. date. How do you tell them apart?
