### ISSUE TITLE
Wrong error message about base currency when using multi-currency plugins

### ISSUE THREAD

**Issue by extrapixel** [woocommerce/woocommerce-gateway-stripe#574]
#### What I expected

When a currency is enable via a multi-currency plugin (e.g. Aelia Currency Switcher), the error messages in the admin backend should not be shown. Even when shop base currency is USD, EUR could be accepted via a plugin.

#### What happened instead

Instead, a list of error messages is shown, e.g.
"SOFORT is enabled - it requires store currency to be set to Euros."

The error message is wrong, because in the frontend it works flawlessly. The Aelia Currency switcher handles the logic for what payment method is visible for the respective currency.

The most simple solution would be to make these error messages "dismissable". Otherwise, they will always be there and clutter the admin UI. 

#### Steps to reproduce the issue

Install a multi-currency plugin (e.g. Aelia Currency Switcher), enable multiple currencies. Install Stripe.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Notices will be dismissible in 4.1.
