### ISSUE TITLE
Charge request - improvements to Description field

### ISSUE THREAD

**Issue by tarkan123** [woocommerce/woocommerce-gateway-stripe#575]
The description field in the charge request I think can be improved.

The main issue is in the stripe dashboard the description field is quite prominent and pretty much the sole human readable field, so I think it should be adjustable so it fits in with the users method of working and contains the information they need to see at a glance.

Currently -

charges request: Array
(
...
**[description] => domain.com- Order 1109107**
...

and for a refunded orders it is
**[description] => REFUND FOR CHARGE (domain.com - Order 1109107)**

The refunded description field is pretty bad, as the Order number then dissappears on the stripe dashboard due to the length of the text. So at a glance you only see REFUND FOR CHARGE...

I suggest allowing the description field format to be adjustable in the plugin settings or via a hook/filter.

A real improvement would be allowing the use of placeholders e.g.    
DESCRIPTION Field   %order_number - domain.com  %order_status , 

Currently the best fixed format (I think) would be  **Order_Number - domain.com ( Charge_Status )**

**Comment by roykho** [comment]
It is already filterable with `wc_stripe_generate_payment_request` As for the refund, I don't think that comes from the plugin but maybe on Stripe side.

**Comment by tarkan123** [comment]
Oh great :)

Learn something everyday!!

**Comment by tarkan123** [comment]
@roykho Thanks I got a filter setup using  wc_stripe_generate_payment_request  to modify the description, and add some more metadata information from the order.

However, I am also trying to use wc_stripe_refund_request, but for some reason it does not expose $order as I want to add the order_id  to the metadata of the refund request.

Any pointers? thanks.

**Comment by roykho** [comment]
Please have a look at https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L768

**Comment by tarkan123** [comment]
@roykho I had a look at all the code, the wc_stripe_generate_payment_request is exposing the order stuff - so my filter is working great.  I cannot even retrieve the order_id to put in the return request meta_data.

Maybe I am doing something wrong with the refund request hook.

My code is

```
add_filter( 'wc_stripe_refund_request', 'modify_payment_refund' );

function modify_payment_refund ($refund_data, $order) {
        // get existing meta data
        $meta_data = $refund_data['metadata'];

	$order_id = $order->get_id()
	$shipping_country = $order->shipping_country;
        // modify it
        $meta_data += array(
                      	'order_id' => $order_id,
			'shipping_country' => $shipping_country,
                );
        //load it back in to refund data
        $refund_data['metadata'] = $meta_data;

        return $refund_data;
}
```

**Comment by tarkan123** [comment]
Sorry ignore me!! totally forgot to tell the filter that we are sending two args!!!!  brain freeze :)
