### ISSUE TITLE
Stripe requires SSL Error

### ISSUE THREAD

**Issue by chrissylvester** [woocommerce/woocommerce-gateway-stripe#577]
Hi, 

While charging the payment using WooCommerce Stripe Gateway plugin, I am getting the below
error in logs.

I have searched alot on the internet but could not find any solution.

My Site Details are as follows.

WooCommerce Stripe Gateway Version : 4.0.7
WC version: 3.3.3
WP version: 4.9.4
PHP version: 5.6.34

SSL Version: TLS 1.2

**On Checkout Page:**
![image](https://user-images.githubusercontent.com/19723074/37454003-52eb985e-2831-11e8-897b-188864552807.png)

**In Logs:**
![image](https://user-images.githubusercontent.com/19723074/37453688-65c3862c-2830-11e8-9006-cf20b095e329.png)

**Comment by roykho** [comment]
This is not a support channel. Please use https://wordpress.org/plugins/woocommerce-gateway-stripe/
