### ISSUE TITLE
Radar - Under review

### ISSUE THREAD

**Issue by DustinHartzler** [woocommerce/woocommerce-gateway-stripe#579]
#### Affected ticket(s)

1943959-hc

#### What I expected

> If Stripe placed a payment under review in the past, the default position was that, unless we decided to refund the order (which we never have) the subscriber continued to have access to the paid content from the moment Stripe sent them a receipt to say they had received their payment.

And with a subscription payment, they are seeing issues with running the cards again even though Stripe has already processed the initial payment.

#### What happened instead

The payments are getting placed on hold and not renewing properly, so the store owner needs to manually approve the transaction in Stripe and in WooCommerce for the customer to continue to have access.

**Comment by roykho** [comment]
They can use this filter and return it false if they wish the status to not change `wc_stripe_webhook_review_change_order_status`
