### ISSUE TITLE
When using Apple Pay from Basket, if you change shipping options the change doesn't get passed to Apple Pay and you have to make the change again in the Apple Pay Modal

### ISSUE THREAD

**Issue by AJerm** [woocommerce/woocommerce-gateway-stripe#580]
#### What I expected

The default shipping option is free local collection

I change the shipping method to enable postage, this adds a shipping charge and the button refreshes.

I tap the Apple Pay button, the modal appears and I can see the shipping charge visible while it thinks for a second, the modal then updates and shipping reverts to the default option (free in my case), this reduces the cost in the basket and if the user doesn't carefully check and alter the shipping a second time, then it will be very easy to accidentally process their order incorrectly with wrong shipping info.

#### Steps to reproduce the issue

Try apple pay from the basket with any item from this shop. Change the shipping option before tapping to pay.

https://cycleprintworks.co.uk/product/shop

It happens on iphone and safari for me.

1. Selection postage

![image](https://user-images.githubusercontent.com/1643439/37683302-195776c4-2c84-11e8-81c3-6e184132749c.png)

2. Apple Pay modal appears and seems to have the correct value to begin with while thinking

![image](https://user-images.githubusercontent.com/1643439/37683339-3b2724ac-2c84-11e8-9fab-86c9fc68499f.png)

3. A few seconds later the modal updates with the wrong shipping selection, having reverted to the default

![image](https://user-images.githubusercontent.com/1643439/37683392-61e7362c-2c84-11e8-99f1-4a62b1baecbe.png)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
That is correct as all interactions has to be done in the Apple Pay. However if a shipping method was selected and a page refresh was done, then Apple Pay picks it up. Unfortunately nothing we can do about that right now.

**Comment by AJerm** [comment]
When you switch shipping methods in the basket, all the buttons do refresh on the page at the same time as the amount on screen. When you click on Apple Pay the shipping cost is passed in and initially picked up by apple pay, but a few seconds after apple pay is initialised it gets reset to the default shipping. 

Is that really expected? That feels like a bug, why would Apple Pay default back to a different shipping method half way through the process?

**Comment by roykho** [comment]
It "resets" the shipping when the popup comes up. Not saying its not a bug. Its just not an easy fix right now. We already have plans in the future to revamp how it works so this issue is not needed. This is already known.

**Comment by AJerm** [comment]
Okay fair play, just trying to understand :)
Thanks for all your help, I'm sure you guys will figure it out, keep up the great work 👍
