### ISSUE TITLE
Stripe Requires SSL

### ISSUE THREAD

**Issue by TomasHurtz** [woocommerce/woocommerce-gateway-stripe#581]
go to > woocommerce settings > logs woocommerce-gateway-stripe

I have many entries with the following, despite my site having a valid SSL cert, admin with SSL and https set in site address and also in Stripe settings I have https 

I have tried with Force SSL and also without that option ticked.

-------------------

03-22-2018 @ 21:28:00 - ====Start Log====
Stripe requires SSL.
====End Log====

03-22-2018 @ 21:28:21 - ====Start Log====
Stripe requires SSL.
====End Log====

03-22-2018 @ 21:28:24 - ====Start Log====
Stripe requires SSL.
====End Log====

03-22-2018 @ 21:28:30 - ====Start Log====
Stripe requires SSL.
====End Log====

**Comment by roykho** [comment]
Is Stripe not working because of this for you?

**Comment by roykho** [comment]
We will remove the required `is_ssl()` check as this is not 100% accurate on all sites to detect SSL. Instead we will just log it but not stop Stripe from functioning. In addition, if you want to remove this log message all together, you can use the filter which we will provide in 4.1 release. The hook name will be in the readme.txt changelog.

**Comment by contremaitre** [comment]
Hello
I also have this issue, but I would like to keep stripe logs. Is it possible to remove this ssl message from logs ?
