### ISSUE TITLE
Email asked twice 

### ISSUE THREAD

**Issue by ikyamoet** [woocommerce/woocommerce-gateway-stripe#583]
I use the 4.1 Stripe gateway to force fields validations

#### What I expected

When customer choose to pay without creating an account, he's asked to insert Email during the 1st step of the checkout process, stripe should validate its email and not asking him in the modal

#### What happened instead

Stripe modal ask the email again and force customer to specify it a second time

#### Steps to reproduce the issue

The issue is only when customer choose to pay without creating an account.

**Comment by roykho** [comment]
Fixed in 4.1 branch.
