### ISSUE TITLE
[4.1 Beta-1] Sort payment methods in header

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-stripe#584]
There are now a lot of different possible methods for Stripe, and they add a lot of clutter to the Settings >  Checkout header options:

![Checkout settings header](http://cld.wthms.co/7vKaRC+)

Would it be possible to sort the Stripe methods, for example in alphabetical order? That would make it look more structured.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Closed in favor of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/490
