### ISSUE TITLE
[4.1 Beta-1] Stripe fees and reporting

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-stripe#587]
In 4.1, the Stripe fees are now shown on the order details: 

![Order with Stripe fees](http://cld.wthms.co/kyAFDg+)

When you go to the reports, the gross and net numbers are showing the order totals, but don't account for Stripe fees at all: 

![Reporting](http://cld.wthms.co/G1wDMo+)

Is this correct?

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
It was not intended to show in reports, just the order. I will see if I can hide those from there.

**Comment by roykho** [comment]
Read this issue wrong. I thought the added details were being shown on reports. So this has always been like that since version 1. Net for WC core is for core and not to be calculated with Stripe.
