### ISSUE TITLE
[4.1 Beta-1] Stripe fees in a different currency?

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-stripe#588]
I'm not sure if this is a bug or not, but it looks very strange. 

The shop's currency is set to Euro, and somehow the Stripe fees are showing up in kr. 

![Order details](http://cld.wthms.co/qm9XNU+)

The shop location is set to  Sweden, but I wouldn't expect this to affect the Stripe fees: 

![Shop location](http://cld.wthms.co/iZFzrw+)

My location is set to Sweden in the Stripe dashboard.

![Stripe dashboard](http://cld.wthms.co/HWvOwS+)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
This is correct.
