### ISSUE TITLE
[4.1 Beta-1] Multibanco image missing

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-stripe#590]
At checkout, the Multibanco image is missing:

![Multibanco at checkout](http://cld.wthms.co/eSEMwX+)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Capitalization issue. Should be fixed in 4.1 branch.
