### ISSUE TITLE
[4.1 Beta-1] Able to see and use Multibanco outside of Portugal

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-stripe#591]
The Multibanco description states: `Relevant Payer Geography: Portugal`

However, I could both see the payment option and do a test checkout with it when my location was not set to Portugal.

![Checkout not Portugal](http://cld.wthms.co/Wgq7Ha+) 

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
That is correct behavior as the payment method is only concerned with the currency used in store.
