### ISSUE TITLE
[4.1 Beta-1] Multibanco test payment set to on-hold with "an unknown error occurred"

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-stripe#592]
Using a simple product, check out with Multibanco. The order confirmation shows up correctly.

However, the order goes from `pending` to `on-hold`:

![Order notes](http://cld.wthms.co/X7ZcM0+)

Here's the Stripe log: 

```
03-28-2018 @ 13:30:35 - 
====Stripe Version: 4.1.0-beta-1====
====Start Log====
Info: (Webhook) Begin processing payment for order 982 for the amount of 32.00
====End Log====


03-28-2018 @ 13:30:35 - 
====Stripe Version: 4.1.0-beta-1====
====Start Log====
charges request: Array
(
    [currency] => eur
    [amount] => 3200
    [description] => WooCommerce Demo - Order 982
    [expand[]] => balance_transaction
    [metadata] => Array
        (
            [customer_name] => John Doe
            [customer_email] => hannah@automattic.com
            [order_id] => 982
        )

    [customer] => cus_9uazRClt1HY15V
    [source] => src_1CAeLzAoUSmq4CQfU9lfOdTu
)

====End Log====


03-28-2018 @ 13:30:36 - 
====Stripe Version: 4.1.0-beta-1====
====Start Log====
Error: stdClass Object
(
    [error] => stdClass Object
        (
            [type] => api_error
            [message] => An unknown error occurred
        )

)

====End Log====
```

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Do you have webhooks set? It requires webhook to work.

**Comment by hannahswain** [comment]
All of the other test payments went through correctly, using that same webhook. 

![Webhooks](http://cld.wthms.co/iYtbKz+)

**Comment by roykho** [comment]
Do you mind testing it again to see if it isn't just a one off issue? I am unable to replicate on my end.

**Comment by hannahswain** [comment]
I did test twice, just to make sure, before reporting the issue. 

* physical product and flat rate shipping - same issue, order is set to `on-hold`.
* physical product and free shipping - same issue
* Updated the webhook URL in Stripe and made another order - same issue
* Updated to latest webhook version (2018-02-28) and made another order - same issue
* Updated to default webhook version (2016-07-06) and made another order - same issue
* Changed billing country to Portugal and made another order - same issue

Checked the logs to see if anything changed: 

```
03-28-2018 @ 14:08:55 - 
====Stripe Version: 4.1.0-beta-1====
====Start Log====
Error: stdClass Object
(
    [error] => stdClass Object
        (
            [type] => api_error
            [message] => An unknown error occurred
        )

)

====End Log====
```

**Comment by amandasjackson** [comment]
I just tested this again and it went through

![](http://cld.wthms.co/JwAAfU+)Image Link: http://cld.wthms.co/JwAAfU
