### ISSUE TITLE
Credit card form: Card type detection fail bug

### ISSUE THREAD

**Issue by safeerahmed555** [woocommerce/woocommerce-gateway-stripe#593]
I currently use 4.0.7 version on staging website and found a serious bug in credit card form, when I type card number it doesn't detect the card type like weather it's visa card or master card etc like pre 4.0 versions.

**What I expected**

When customer enter card number in field, it should detect the card type like pre 4.0 versions.
plugin WooCommerce Stripe Gateway version 3.2.1 when it was working fine, following screenshots I took with different themes with plugin version 3.2.1 to show how it was working.

working correctly with my child theme (storefront parent theme) https://prnt.sc/iypg2v
working correctly with storefront theme https://prnt.sc/iypggo
working correctly with bulk theme https://prnt.sc/iyph2g
working correctly with Belise Lite theme https://prnt.sc/iyphf5

**What happened instead**

When I tried credit card form with version 4.0.7 with same above themes, it showed bug like following screenshots where it doesn't detect card type.

Buggy scenario with my child theme https://prnt.sc/iypbrg
Buggy scenario with storefront theme http://prntscr.com/iypcb8
Buggy scenario with Bulk theme https://prnt.sc/iypclu
Buggy scenario with Belise Lite theme https://prnt.sc/iypdbj

**Steps to reproduce the issue**

This issue can be reproduce with any 4.0.X version of WooCommerce Stripe Gateway on any theme.
I reproduced this issue with default storefront theme also when all plugins (except woocomemrce version 3.3.4, woocommerce subscriptions version 2.2.18 and WooCommerce Stripe Gateway 4.0.7) deactivated.

I further checked about this issue and found that it was working fine till 3.2.3 version but its having card type detection fail bug since 4.0.0 version.

**Comment by roykho** [comment]
Not a bug. If you want that feature, you need to enabled "Inline form" in the settings.

**Comment by safeerahmed555** [comment]
Hi roykho.

We already use default credit card form (version 3.2.3 ) on 3 to 4 websites where it detect the card type.
We have tested inline form and it doesn't look good specially on mobile devices, its not much user friendly.

we prefer to do not use Inline form and want to use earlier credit card form.
If it would be possible to get back the card lookup also for the non-inline option? 

Since it was already use to have it, it should be possible to put it back there for non-inline option also?
It will be great if you people can put it back so we can use earlier layout of form, thanks.

**Comment by roykho** [comment]
Unfortunately that is not possible for us to change in the plugin. The new form introduced in 4.0 is hosted on Stripe's server. Perhaps the better question to ask here is why does the "inline form" not look good for you? Please see some very nice examples here https://stripe.github.io/elements-examples/

**Comment by safeerahmed555** [comment]
Hi roykho, the reason is my client dont like inline-form and me too as its not much user friendly, it will be better to have separate fields with card type lookup/detection.

It will be more better if you support both forms with card type detection like inline form do so clients/developers can choose whichever form they feel more better?

 I checked in readme file that older credit card form ( pre version 4.0.0 ) will be completely removed by version 5.0, Can you clarify about which older credit card form will be completed remove by version 5.0 ? Is this is the non-inline form with 3 separate fields for card number, expiry date and cvc?

Which credit card form is hosted at stripe server, inline form or separate fields credit card form? Because one form support card type detection and one form doesn't.

Can I customize the separate credit card field form so it detect the card type like inline form? Or is there any possibility stripe add that functionality back if that form is at stripe server?

Because we want to use non-inline form with separate fields after some customization so it detect the card type (like it detect in inline form) when user enter card number, would it will be possible for us?

Please advise us, should we try our custom code to make non-inline form with card type detection and non-inline form will be in use in future versions also?

Thanks.

**Comment by roykho** [comment]
The older form is deprecated and should not be used and will be removed completely tomorrow. I would not suggest you use the older style form for security reasons. The "new" hosted form is the new way forward.

**Comment by safeerahmed555** [comment]
Ok thanks for letting us know about older form security reasons.

There is one confusion still, when you say older form, it means pre version 4.0 seprate fields form or do you mean tomorrow we will have only inline form options in new 4.1 version?

and current non-inline form (separate fields form as I can see in version 4.0.7) is new form?

And can we try our custom code to make non-inline form / separate fields form (of version 4.07 or version 4.1 ) with card type detection ?

**Comment by roykho** [comment]
Yes I mean pre 4.0 form. Tomorrow, on there is only inline form and the individual fields form which are both Stripe hosted.

**Comment by safeerahmed555** [comment]
Ok so individual fields form (stripe hosted) will remain in future versions as well?

and last question, can I (as developer) can make changes so individual fields form also show card type detection as inline form doing? Because both are stripe hosted so both can have a card type lookup/detection functionality ?

**Comment by thorsten-stripe** [comment]
@safeerahmed555 you can get the card brand from the change event handler. See an example here: https://jsfiddle.net/ywain/L96q8uj5/

**Comment by roykho** [comment]
@thorsten-stripe thanks for the reference. Was this in the Elements documentation? I didn't see it there. Perhaps this should be added to the core plugin for better user experience?

**Comment by thorsten-stripe** [comment]
@roykho exposing the brand in the change event was added comparatively recently: https://stripe.com/docs/stripe-js/reference#element-on

And yes, agreed that this might be good to include in the plugin for everyone as we currently don't have plans to include in the cardNumber Element.

**Comment by safeerahmed555** [comment]
@roykho , @thorsten-stripe .
Yes, that will good to include in the plugin for everyone and it will be better user experience.
I hope so you people will plan it for next release. Thanks.

**Comment by safeerahmed555** [comment]
@roykho , @thorsten-stripe 
Thanks for adding card brand detection on credit card form.
I just checked it with 4.1.1 release and its working fine. Thanks a lot.
