### ISSUE TITLE
Description in Stripe's Payment Details show site title and order #

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce-gateway-stripe#594]
#### Affected ticket(s)

1062385-zd-woothemes

Not 100% sure if this is expected behavior or a bug.

#### What I expected/Steps to reproduce

Purchase a product with Stripe, go to your Stripe account to view the payments made. I think the expectation is that the description under payment details would show product's details.

#### What happened instead

Instead, shows site title and order number:

![](http://cld.wthms.co/npSGY2+)
Link to screenshot: http://cld.wthms.co/npSGY2

Another question is whether product details should even be used here, esp when multiple products are being purchased.

**Comment by roykho** [comment]
It is not a bug. We have never put items ordered in the description field. If they want to add their own description, they can always use the filter `wc_stripe_generate_payment_request`
