### ISSUE TITLE
Use i18n placeholders whenever possible

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce-gateway-stripe#595]
I'm an editor for the "Portuguese (Portugal)" translation of the WooCommerce Stripe Payment Gateway on the wordpress.org Glotpress, and I'm working the translations in order to get at least to 95% project translated, so they're downloaded by the Portuguese WordPress installs.

In this process, I found a lot of strings that could use i18n placeholders, like the ones below, for example:

![image](https://user-images.githubusercontent.com/6853605/38421662-c54bf77a-399f-11e8-9583-8db3bccb90b0.png)
![image](https://user-images.githubusercontent.com/6853605/38421678-d0ceee5e-399f-11e8-87df-945fa5425b11.png)
![image](https://user-images.githubusercontent.com/6853605/38421686-dd601e22-399f-11e8-99ae-2a7fc652fc7c.png)

Placeholders should be used on this kind of strings.
https://codex.wordpress.org/I18n_for_WordPress_Developers#Placeholders

Also, related to i18n but not this topic subject:

1) As a general rule no HTML should be used on translatable strings;

2) I'm not sure these should be translated at all:
![image](https://user-images.githubusercontent.com/6853605/38421789-3fcf7666-39a0-11e8-827f-ecb4e16fd499.png)

**Comment by roykho** [comment]
PR is always welcomed. Please do this against release/4.1 branch.
