### ISSUE TITLE
Upgrade Radar 2.0

### ISSUE THREAD

**Issue by gtechahmed** [woocommerce/woocommerce-gateway-stripe#598]
#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

Stripe Radar **2.0** required integration which does not meet when placing order with Woocommerce Stripe Payment Gateway plugin. Please take a look at screenshot: http://prntscr.com/j0s1m5.

I want to know if there is a plan to release update with Radar **2.0** integration. Or i need to find another solution ?

**Comment by roykho** [comment]
Hello so this issue is an issue on Stripe's side and they're aware of it and being worked on as we speak. Please check back with them to get an update on it.
