### ISSUE TITLE
Dynamic Pricing rules ignored by Buy Now button

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce-gateway-stripe#599]
#### Affected ticket(s)

#1081113-zen

#### What happened instead

The Buy Now button ignores the discount rules created with Dynamic Pricing.

#### Steps to reproduce the issue

Create a rule like this

![](http://d.wedj.at/mtOwlU+)
**Image Link**: http://d.wedj.at/mtOwlU+

Choose 3 quantity of the product on the product page and click on Buy Now. The price will ignore the discount rule.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
What is buy now button? Do you mean Payment Request?

**Comment by laurendavissmith** [comment]
Moved to the ideas board: http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/34518658-dynamic-pricing-compatibility-with-buy-now-button
