### ISSUE TITLE
Webhook handler updates status without applying `woocommerce_payment_complete_order_status` filter

### ISSUE THREAD

**Issue by tamarazuk** [woocommerce/woocommerce-gateway-stripe#601]
The webhook handler updates an order status to processing/completed but doesn't apply the `woocommerce_payment_complete_order_status` filter as WC core does [here](https://github.com/woocommerce/woocommerce/blob/49e93bc7554f2f61ee7a0bbfa12edeb114cee417/includes/class-wc-order.php#L120). 

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/95cffcc08f0db90b3168015436f7d067f8c8c9fd/includes/class-wc-stripe-webhook-handler.php#L308

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/95cffcc08f0db90b3168015436f7d067f8c8c9fd/includes/class-wc-stripe-webhook-handler.php#L359

Due to this merchants Stripe payment methods which rely on the webhook handler can't take full advantage of Order Status Control (OSC), which relies on `woocommerce_payment_complete_order_status`. I looked into using a filter within the `$order->needs_processing()` method, however this won't work for OSC as we need to know the default order status for one of our settings.

Is this filter something the Stripe gateway can implement? Thanks :)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by hedqvist** [comment]
This should probably use ```$order->payment_complete($transaction_id)``` instead of forcing a order_status_changed, since the above function will do this.

**Comment by roykho** [comment]
Hi @tamarazuk can you please see if this commit will work for you? https://github.com/woocommerce/woocommerce-gateway-stripe/commit/46ab39aa072ea1a73337ff452890952f265dcf7a

**Comment by tamarazuk** [comment]
@roykho thanks! This will definitely work for us! I thought there was some specific reason payment_complete() wasn’t being called so I suggested a different solution. With this change the plugin will be compatible with many more third-party extensions :smile:
