### ISSUE TITLE
Sofort, Giropay:  Terms and conditions not checked on Place Order does an AJAX request first, then a refresh

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce-gateway-stripe#602]
#### Affected ticket(s)

1082544-zd-woothemes

#### What I expected

Whenever I do a Place Order, that it would validate through AJAX instead of doing a page refresh.

#### What happened instead

The first time I click "Place Order" it does an Ajax check and returns errors, the second time it just refreshes the page and shows the error at the top.  

#### Steps to reproduce the issue

1. Enable Giropay or SOFORT
2. I had to set my store to Germany and Euros
3. Make sure your store has a Terms and Conditions page required
4. Go to checkout
5. Select SOFORT or Giropay
6. Place Order 

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Hi @mikeyarce would you mind giving this branch a test https://github.com/woocommerce/woocommerce-gateway-stripe/tree/fix/issue-602
