### ISSUE TITLE
Tweak - Stripe Checkout Popup Modal will validate checkout before proceeding to payment step.

### ISSUE THREAD

**Issue by streamworksaudio** [woocommerce/woocommerce-gateway-stripe#603]
Is it this new Tweak:

Tweak - Stripe Checkout Popup Modal will validate checkout before proceeding to payment step.

Responsible for having clicking on the 'Continue to Payment' button go to an new page with an order summary and a 'Place Order' button (instead of the Strip Modal box appear)?  If so, I think we need a way to customize this page.

As it stands now, I think would be jarring and alarming to a customer as there is no information that this is a 'confirmation' page and to 'process' the order.  Just a summary or the order, and a button.  How can edit this page to give some more info as to what this page is (for the customer's benefit).

Cheers

**Comment by roykho** [comment]
Yes there is, please read the hooks section of the documentation page https://docs.woocommerce.com/document/stripe/

**Comment by streamworksaudio** [comment]
Can you perhaps throw me a bone as to which hook I need to look at for customizing this page?

**Comment by roykho** [comment]
Sure, so these are the ones you'll probably use ![](http://cld.wthms.co/g49Yde+)

**Comment by streamworksaudio** [comment]
Much appreciated.
