### ISSUE TITLE
Card image alignment issues

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce-gateway-stripe#604]
There are some alignment issues with the card images I'm seeing:

![screen shot 2018-04-12 at 11 15 28 am](https://user-images.githubusercontent.com/3220162/38696057-e6c442fc-3e42-11e8-830f-acf4e020f260.png)
![screen shot 2018-04-12 at 11 10 05 am](https://user-images.githubusercontent.com/3220162/38696063-e88caef8-3e42-11e8-8be6-72c8d7e207f6.png)

IE 11 report that I am not able to reproduce:
![screen shot 2018-04-12 at 11 17 35 am](https://user-images.githubusercontent.com/3220162/38696148-232c9906-3e43-11e8-966d-d5008cf1feb7.png)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
These are very theme/browser dependent so I am not sure we'll have a fix for this. It is best to provide CSS for their own use case. `.stripe-icon` is the CSS classname they can target.

**Comment by mikeyarce** [comment]
@roykho the two top ones are just using the default Storefront theme - should we add this as an issue in Storefront, or add some styles in here for that?  cc @tiagonoronha

**Comment by roykho** [comment]
@mikeyarce hmmm my Storefront looks like this ![](http://cld.wthms.co/wkQUIK+)

**Comment by mikeyarce** [comment]
Try setting your country to Germany?  I had mine set to Germany and Euros.

**Comment by roykho** [comment]
@mikeyarce I think in your screenshot the icons simply doesn't fit hence one of them is bumped down. So the fix for that is only to reduce the size of the icons OR make the widget wider.
