### ISSUE TITLE
Payer locale aware payment methods

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gateway-stripe#606]
So in the past maybe around 3 years ago, we have discussed the idea of having payment gateways aware of where the customer/buyer is from by watching for the billing address country. In our discussion, we came to the conclusion that there may be some gotchas (which I can't remember exactly what) and thus this idea was put in the back burner.

Since now Stripe supports various payment methods that are served globally, perhaps we should revisit this idea again. Having a way to target the payment method specific to the customer/buyer may yield a good user experience.

For example if they selected a billing country of Belgium, it would automatically hide the payment methods that does not support that country and show the ones that do.

Since more and more online shops do business globally, this may be a good fit for them.

**Comment by websnail** [comment]
I know you're going to hate this but I'd like to suggest we go one further and add in mulit-currency. I've worked on true multi-currency for a while now and hacked one of the Stripe addons to do this.

Stripe allows you to register and accept additional currencies but it treats each as a separate account with separate API keys. I've already forked this project and have started applying the code lessons from my earlier hack but I could really use some help with the UI/Ajax needed to input the additional API keys in the admin settings.

Adding multiple currencies sounds like a HUGE project but it's not when you look at it properly and like I said, I just need help with the admin settings and making that user friendly. So, if anyone can help with the Admin UI I can do the rest although other input, tidying up would be welcomed.

.. and to come back to your original point Roykho, I agree, the functionality you're suggesting is definitely recommended I certainly want to add it in.

**Comment by tarkan123** [comment]
We do this at the moment it is not that hard.

Our multi-currency plugin handles pricing for the 3 currencies we accept, and then few lines of code in the functions.php adjusts the payment methods available depending on customers shipping address ( and for payment currency).

Multi-currency is not something that should be handled in the payment gateway plugin as it is a store wide change.

However it would be nice to have the ability to filter countries for the payments using an admin interface for payment gateway.

**Comment by websnail** [comment]
> Multi-currency is not something that should be handled in the payment gateway plugin as it is a store wide change.

I'm not suggesting the bulk of multi-currency support be added through a single plugin as it is indeed a site wide problem, not something that's Stripe specific. There are already plugins like Aelia Currency Selector that do a very good job of handling this anyway so better to use those for the heavy lifting.

That said, as I pointed out, there are Stripe specific aspects that require this (or a forked version) to handle the different API keys.

Given that this is a settings UI issue which can be resolved later I'm just going to include hard coded key options for now and pursue that as a separate thread.

**Comment by tarkan123** [comment]
I have seen mention of this having different API keys, which confuses me as we are a multi-currency company and Stripe provides multi-currency settlement using one API key - so payments made in EUR are settled in to our EUR bank account, and the same for USD & GBP.

**Comment by websnail** [comment]
> I have seen mention of this having different API keys, which confuses me as we are a multi-currency company and Stripe provides multi-currency settlement using one API key - so payments made in EUR are settled in to our EUR bank account, and the same for USD & GBP.

Do you mean you settle everything to EUR or that you have a USD account for USD, GBP for GBP, etc...?

**Comment by tarkan123** [comment]
So European customer visits site - prices are in EUR,  pays order in EUR - and Stripe settles payment in EUR to our EUR bank account.

So British customer visits site - prices are in GBP pays order in GBP - and Stripe settles payment in GBP to our GBP account.

Same again with USD.   This is using a single Stripe account, with one API key.

**Comment by websnail** [comment]
Hold that... I've just found what I've missed for the past 2+ years... 

Balance > Settings > Bank accounts

I hadn't realised that Stripes "Add Account" was to allow separate stores/income streams rather than for adding different bank accounts... 

Well that's years of code hacking wasted... Thank-you for pointing this out... *&$%^£!

**Comment by tarkan123** [comment]
Ok that explains all the confusion!!  :+1:

**Comment by laurendavissmith** [comment]
Original idea has been moved to the ideas board for further evaluation: http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/34518655-payer-locale-aware-payment-methods
