### ISSUE TITLE
Compatibility with Radar 2.0

### ISSUE THREAD

**Issue by robman87** [woocommerce/woocommerce-gateway-stripe#615]
Are there any plans on making the plugin work with Radar 2.0?
It helps to prevent fraud using machine learning, anything that can reduce fraud is great.

![radar-2 0](https://user-images.githubusercontent.com/5516214/38972922-94a223a2-43a3-11e8-866f-8e9c87dd66b2.png)

This is using WooCommerce v3.3.5 and woo commerce-gateway-stripe v4.1.1.

Seems that a few changes are needed
* Create payments using the customer object
* Provide customer name

**Comment by roykho** [comment]
Fixed in master.

**Comment by stelladex** [comment]
Hi
I'm now seeing this again, so can't update to Radar 2
Same failures, same versions, 3.3.5 and 4.1.1.
We use subscriptions and memberships with recurring billing.

Our site has been running for a year so we definitely have recurring payments using cards stored via older versions of the plug in, and have had some issues before.  Could this be related?

We were getting full integration at some point but now get the failures on create payments using the customer object and provide customer name.

Our other identical site works fine with radar integration, but is much newer (live Feb 18) so doesn't have any stored cards using old processes.

Many thanks
