### ISSUE TITLE
Redirect to order-pay page

### ISSUE THREAD

**Issue by robman87** [woocommerce/woocommerce-gateway-stripe#616]
roykho with all due respect, the design decision you made is not adding any value. 

I can't find any advantages with it, only disadvantages for our paying members, for us as a company and for you as a provider.

Are there any technical reasons to redirect to a second page? 
If so, we will gladly help to come up with a solution to skip this extra step.

Please revert this, as it's obviously not adding any value to us nor our customers.

It's just an empty page with information people already got on the first page and a button they need to click on again "Place order" and then enter in card details and then again click on a button in the stripe modal to pay.

Please fix this asap as this has really destroyed the natural flow of the payment and as quickandeasyce mentioned in #613 people recognize Stripe and are more willing to do business knowing they are paying through Stripe.

Sorry for bringing up a locked issue, but I feel this issue needs to be discussed and clarified.

Thanks for a great job so far and I know you will do the right decision for us as a user and also for the services you provide.

**Comment by roykho** [comment]
Dup of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/613

**Comment by robman87** [comment]
Please stop closing tickets that you haven’t answered properly. 
Stop being rude and listen to feedback, you are developing this for us (your users) not for yourself. 

How do we remove this extremely unnecessary step “order-pay” that has been added in the recent update? 
We really don’t want to use the inline form.

Can you please explain what technical reason(s) there are for solving it with a separate page or at least explain the thinking/reasoning behind this design decision?

Please answer us we need help and stop closing tickets, we need to get rid of this page and that ASAP.

**Comment by roykho** [comment]
We are doing it for the users. Before you complain please do your research first to see why it was done. This GH issue has been opened for a little while along with many other issues raised where people debated. Please read here and all the mentioned threads https://github.com/woocommerce/woocommerce-gateway-stripe/issues/578

**Comment by robman87** [comment]
Thank you so much for the link, it was exactly the information that I was looking for. 
I read the thread some a while ago, now there is more information.

I understand now, didn't know that Stripe recommends the inline form now since using elements.

Sorry for being pushy, just thought that the "best" way was the modal and we want the best experience for our customers, which since reading up on it might actually be the inline form.

Thanks again and keep up the great work :)

**Comment by thorsten-stripe** [comment]
@roykho maybe it would be worth adding a "Secure transactions Powered by Stripe" badge[0] in the card collection section to give consumers more confidence? Wdyt?

@robman87 do you think something like that would be a valuable addition that you'd be interested in?

[0] https://stripe.com/about/resources

**Comment by robman87** [comment]
Sure Thor, anything that can increase customer confidence is good. Great idea! Thanks for all the great work you do.

**Comment by roykho** [comment]
@thorsten-stripe we're trying to gather data on people that use the Checkout vs inline and see why those people are using it. We may retire the checkout completely depending on the findings.

There are already hooks in place for people to add content to that page so they can certainly do that on their end. If we deem that people just want to use a popup, then we will act accordingly.

**Comment by douglsmith** [comment]
I suspect many initially used Checkout because it was a much better experience than what was built into WC. And now they don't realize that there's another option and have stuck with what was working.

I found it confusing that there were multiple choices when I was first getting set up because there wasn't anything providing the knowledge to make an informed choice. It seems like a good place to simplify with convention over configuration.

**Comment by roykho** [comment]
Me, personally, I think the confusion was the name of the setting "Stripe Checkout". This is what Stripe called it and we went along with it. In hindsight, this setting should have been called "Modal Popup Checkout" or something along those lines. Because it was named in such an undescriptive way, people thought it had to be enabled for Stripe to work even though the first setting clearly says "Enabled...".
