### ISSUE TITLE
Stop scripts & styles loading from other pages then checkout

### ISSUE THREAD

**Issue by KrystianErgotopia** [woocommerce/woocommerce-gateway-stripe#618]
Hi I am wondering why stripe-plugin scripts are loading on every page? What is the reason for that? I thought your plugin should only load in checkout as its otherwise slowing down every site. Do you plan to improve that or is there any hook for this?

see here: https://tools.pingdom.com/#!/c3yUA3/https://www.ergotopia.de/blog/stress

I tried this, but its only working for another plugin (one-click-upsell) which is also using stripe gateway:
```
//removes stripe scripts for all but checkout 
function is_handsome_checkout(){
    if( get_post_type() == 'handsome-checkout' ){
        return true;
    }
    return false;
}

add_action( 'wp_footer', 'wc_dequeue_scripts', 10 );

function wc_dequeue_scripts() {
    if ( ! is_checkout() && ! is_account_page() && ! is_handsome_checkout() ) {
        wp_dequeue_script( 'stripe' );
        wp_dequeue_script( 'ocustripe' );
    }
} 
```

How to adjust this code, so its working for your plugin as well? Or do you maybe plan an option for this in wp-admin?

**Comment by roykho** [comment]
It doesn't load it on every page. But in fact we should as Stripe recommends this.

**Comment by KrystianErgotopia** [comment]
I havent enabled this. And pls have a look. It is loading, check yourself: https://www.ergotopia.de/blog/stress

![2018-04-23_10h36_48](https://user-images.githubusercontent.com/38551566/39115566-5aabdc14-46e2-11e8-99e0-0bfaf115f75c.png)

**Comment by KrystianErgotopia** [comment]
If this is yours, yes: https://docs.woocommerce.com/document/stripe/   Version 4.0.7 we will update on weekend.
I am also using this, which is using stripe as well, as mentioned at the beginning, and the code they provided is deleting their scripts (see first post): https://woocurve.com/1-click-upsells-for-woocommerce/

**Comment by roykho** [comment]
I just went to a random page on my site and viewed the source and this is what I get ![](http://cld.wthms.co/pg0Rhl+)
