### ISSUE TITLE
Customer email update in WP / My Account broke lookup/searching relationship b/w WP & Stripe Info

### ISSUE THREAD

**Issue by safeerahmed555** [woocommerce/woocommerce-gateway-stripe#619]
We have been using WooCommerce / WooSubscriptions and your Stripe plugin for one year now, and it is generally working really well. However, we have one observation / question. 
The "CUSTOMER" that gets registered with Stripe through the plugin is the user's "E-mail" from WordPress, NOT the users "Username". 

The issue with this is that the user CAN change their email in WP. The only field that is NOT changeable is the Username - that field is locked in WP. That means that if a user changes their email, the easy lookup of the same customer between WP and Stripe is broken. 

We think it would be better if your plugin used the Username = Customer, to lock down this relationship for good (as the Username in WP cannot be changed), and then passed on the Email as well, as a second parameter.

In Customers menu of https://dashboard.stripe.com we can only see Customer Email , even if we click on click customer, it don't show customer Username (Unique Username in WP) like screenshot https://prnt.sc/j8nyie at stripe dashboard.

So can we have Username at stripe dashboard so that we can search by Username which will always be same for user/customer in WP?

**Comment by roykho** [comment]
If you're using the Stripe Checkout (modal popup) it sends email. If you want the name, you need to use the embedded inline checkout.

**Comment by safeerahmed555** [comment]
Hi roykho, 

I've tested it a lot with different options of modal popup, inline form and normal checkout form with 3 different fields of credit card, expiry date, cvc code but it don't sent username in any case at stripe.
It send email of user.
How can we send username at stripe dashboard? 
So I can check payments/customers there by username instead of email which can be changed by user at checkout page or Edit Account page.

I've tested it before enabling Radar 2.0 at stripe dashboard and also tested after enabling Radar 2.0.

But I don't see username in any case.

I'm using latest woocommerce, latest woocommerce subscriptions,  latest woocommerce gateway stripe plugin.

Please let me know how we can send customer username (username is permanent and users can't change this value) to stripe dashboard as well?
