### ISSUE TITLE
Call to undefined method WC_Stripe_Customer::is_no_such_customer_error() when i paid

### ISSUE THREAD

**Issue by alicedoe** [woocommerce/woocommerce-gateway-stripe#620]
#### Affected ticket(s)

none

#### What I expected

Paiement completed

#### What happened instead

Call to undefined method WC_Stripe_Customer::is_no_such_customer_error() in developper console response
On customer screen : wc notice error: SyntaxError: Unexpected token < in JSON as position 0 instead of an error or a successfull paiement

#### Steps to reproduce the issue
Use version 4.1.1 or 4.1.0
Add item to cart
Checkout using Stripe
Use Stripe test card 4242424242424242

This is the same issue than #614 except i'm doing a successfull paiement

I switch back to 4.0.7 it's working but i can't use this new release

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Try 4.2.1 release.
