### ISSUE TITLE
Provide an option to force 3ds redirect if the card supports 3ds but is optional vs. required

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#623]
#### Affected ticket(s)
1045506-zen

#### What I expected

To be able to use 3ds even if the card has the 'optional' flag vs. required

#### What happened instead

Cards that support 3ds aren't redirected and there is no option to require 3ds

#### Steps to reproduce the issue
Stripe in test mode, 3ds enabled and use card number 4000000000003055 which the Stripe docs say:

>3D Secure is supported but not required on this card. The value of the card source's card.three_d_secure attribute is optional. Charges succeed whether 3D Secure is used or not.

Under those conditions, there is no redirect to the 3ds page.

-------------------

- [ ] Issue assigned to next milestone.
- [x ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
They can use this filter which is in the docs. `wc_stripe_require_3ds` to return true.
