### ISSUE TITLE
Please add a better readable SEPA icon

### ISSUE THREAD

**Issue by gerdneuman** [woocommerce/woocommerce-gateway-stripe#624]
The Sepa logo with the substrings are not reabable at all. Please just use the normal logo, e.g. like other providers do. For instance I just book a ferry and they used this:

https://screenshots.firefox.com/fcrVNBfjcorF1wKX/booking.helgoline.de

So just a simple image: https://booking.helgoline.de/web/img/sepa.png

![image](https://user-images.githubusercontent.com/12525563/39353014-c736f446-4a06-11e8-9bf5-cd9c31ef2b02.png)

Not this german and english texts below it that are not readable anyways when it comes to 50x20px.

**Comment by roykho** [comment]
I am not sure what you mean? Please explain.

**Comment by roykho** [comment]
Closing due to lack of response.

**Comment by gerdneuman** [comment]
@roykho Sorry, been on vacations :) What I mean is that the Sepa icon on checkout looks like this:
![image](https://user-images.githubusercontent.com/12525563/39513246-04e82a12-4df4-11e8-8277-4ea007bc8985.png)

The two bottom lines (the ones that spell out the `SEPA` acronym in English and German) are not readable anyways. So they should be removed from the svg. So that it could be like this:
![image](https://user-images.githubusercontent.com/12525563/39513304-33555000-4df4-11e8-91f1-31b9fb507237.png)

The relevant file is https://github.com/woocommerce/woocommerce-gateway-stripe/blob/60eba679d59ac1a225c7ce6f5a08ea2db7ca1003/assets/images/sepa.svg

**Comment by gerdneuman** [comment]
FWIW, compare to the unfortunately only grey logo of SEPA at https://paymentfont.com/#pf-sepa It's also without the two bottom lines.

**Comment by roykho** [comment]
Ok understood. Should be removed by next version.
