### ISSUE TITLE
Bug in 4.1.2 with WC 2.6.14 (making refunds)

### ISSUE THREAD

**Issue by danielvonmitschke** [woocommerce/woocommerce-gateway-stripe#625]
The refund code tries to use WC_Order::get_currency(), but in WC 2.6.14 there is only ::get_order_currency() defined.
You might want to check if get_currency() exists and use get_order_currency() otherwise.

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/06a170d12af9c0d8ac0d300f00f2188669606aa5
