### ISSUE TITLE
Duplicate failed order emails sent when processing failed renewal orders

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce-gateway-stripe#627]
#### What I expected

When an order payment fails, admin should receive 1 Failed order email.

#### What happened instead

They receive 2 emails.

#### Steps to reproduce the issue
With the latest version of the two plugins - Stripe 4.1.2 and WC Subscriptions 2.2.19

1. Purchase any subscription product using Stripe as the payment gateway
2. Change the subscription's payment tokens to cause a failed payment (https://cloudup.com/coBTsjhV9pR)
3. Process a subscription renewal by selecting "Process renewal" from the subscription actions dropdown (https://cloudup.com/cVfxuUr_qMQ)
4. The renewal payment should fail and your admin user email should be sent two failed order emails. (https://cldup.com/LqSiYeX8Zb.png)

The duplicate email appears to be coming from this line: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.1.2/includes/compat/class-wc-stripe-subs-compat.php#L268. 

What's the reason behind Stripe sending the email manually like that? Setting the order status to failed like it does a couple of lines above ([here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.1.2/includes/compat/class-wc-stripe-subs-compat.php#L265)) should cause the failed order email to be sent and so Stripe also sending the email is causing a duplicate. 

There's another issue with sending the email in that way, from our opinion. Subscriptions when processing renewal order payment retries will unhook the functions which send core WC order emails. By trigging the email directly (by calling `WC_Stripe_Subs_Compat::send_failed_order_email()` which triggers the email by calling `$emails['WC_Email_Failed_Order']->trigger()`) there's no opportunity for us and other third-parties to stop that email from being sent.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by poolet08** [comment]
Hello,

Would it be possible to get the code to correct this or get an update out pretty soon please? The multiple email notifications regarding a failed order every time a payment fails clutters things up for us and it makes it harder to determine which customers need to be deactivated in our system. 

Thanks!
