### ISSUE TITLE
JS error triggered on all WooCommerce pages when WooCommerce country is not a Stripe one

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-stripe#628]
#### Affected ticket(s)
N/A (reported in chat)

#### What I expected
For WooCommerce to work normally if WooCommerce country is not supported by Stripe

#### What happened instead
There's a JS error triggered on all pages that blocks all JS actions (AJAX requests, reloading shipping costs, etc):

```
Uncaught Error: Invalid value for paymentRequest(): country should be one of the following strings: AT, AU, BE, BR, CA, CH, DE, DK, EE, ES, FI, FR, GB, HK, IE, IN, IT, JP, LT, LU, LV, MX, NL, NZ, NO, PH, PL, PT, RO, SE, SG, SK, US. You specified: TH.
```

![Screenshot](http://cld.wthms.co/yQEF3Z+)
Screenshot: http://cld.wthms.co/yQEF3Z

#### Steps to reproduce the issue
1. In WooCommerce > Settings > General, choose a country that's not supported by Stripe, such as Thailand.
2. Save settings and observe there's no warning in WP Admin.
3. Open any product page and try to switch between product tabs, select a variation, etc - they all become unresponsive due to the JS error above.

Reproduced on Pressable, with Stripe 4.1.2 & WC 3.3.5

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Hi @thorsten-stripe - given the above error, is it better for us to disable Stripe for use completely if the country setting in WooCommerce is set to a unsupported country seen in the following screenshot ![](http://cld.wthms.co/MQ6Dov+)

I am sometimes confused if supported countries meaning the store or where the customer is purchasing from or both.

**Comment by roykho** [comment]
@thorsten-stripe I guess they installed it for the first time not knowing? That is my guess. Going with that assumption, would you recommend we check the country they're setting in the WC store and we do a check against that and if it is in an unsupported country, we throw a notice in the backend and don't continue to the load the plugin...How does that sound? Essentially is to protect them from themselves.

**Comment by thorsten-stripe** [comment]
@roykho sorry for the delay. What would be ideal and most reliable is if you could retrieve the country of the Stripe account and persist that any time the sk changes:

```curl https://api.stripe.com/v1/account \
   -u sk_xxx:```

The resulting account object response has a country param which is the country code of the Stripe account. 

Wdyt?

**Comment by roykho** [comment]
@thorsten-stripe what I found is this issue is only related to Payment Request and the setting in WC. When set to a country it doesn't support, it will throw that error and break everything else that comes after it. But if the currency is supported, the normal checkout will still work and process. So the fix I put in is to only target Payment Request. If it is not one that it supports, it will just bail and not load the JS after it.

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/06a170d12af9c0d8ac0d300f00f2188669606aa5
