### ISSUE TITLE
Additional page with Stripe Checkout enabled

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce-gateway-stripe#632]
#### Affected ticket(s)

1133182 - zd-woothemes and at least a few more

#### What I expected

With WooCommerce Stripe gateway 4.1.0 version, this new feature was introduced:

Stripe Checkout Popup Modal will validate checkout before proceeding to payment step.

![screenshot](http://cld.wthms.co/jxIJsr.jpg) **Image Link:** http://cld.wthms.co/jxIJsr

This means an additional checkout step where shop owners can lose the customers. I've seen quite a few customers who are unhappy about this. Is it possible to do the checkout validation in the background, without redirecting the customer to a new page? 

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
It is not possible at this time.

**Comment by Frique** [comment]
This is quite terrible indeed and wasn't the case in previous versions of the plugin.
