### ISSUE TITLE
Suggestion: Add payment request/apple pay buttons available on checkout page for emailed invoices

### ISSUE THREAD

**Issue by AJerm** [woocommerce/woocommerce-gateway-stripe#633]
When invoicing clients for custom orders I can generate an order in WooCommerce, then send it to them using the 'email invoice' order action in the admin control panel.

This generates an email with a clickable link that brings the customer straight to a checkout page with all the order info pre populated.

Unfortunately, because it's a checkout page as opposed to the normal basket page, the customer is only presented with the normal checkbox checkout options. In my case credit card via stipe or paypal.

What would be great is if the payment request buttons could also be available on this page, so that the customer can pay for that invoice using a payment request button without having to type anything in.

This would mean a client could get an email in their inbox, open it, click to load the shop and view the complete order, then it would only be a final click or two to use the payment request button and pay the invoice.

This is particularly desirable on this page as it would make it a million times easier for clients to pay if they open the email and click the link on mobile, where it's more of a hassle to enter card details than on desktop.

**Comment by roykho** [comment]
Thanks. Please post your ideas here http://ideas.woocommerce.com/forums/133476-woocommerce

**Comment by AJerm** [comment]
Thanks, didn't realise that existed, cross posted there :)
