### ISSUE TITLE
Failing Charge webhook function does return without notification if order status is not "on-hold"

### ISSUE THREAD

**Issue by kmindi** [woocommerce/woocommerce-gateway-stripe#638]
The function `process_webhook_charge_failed` returns without any information if the order status is not "on-hold" (https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-webhook-handler.php#L386) and the following code is not executed. 
As it is possible to change the order-status to any other status manually the shop owner will not be notified of a failing charge not even a log entry is made?!

I would expect that the order status is always updated to "failed" regardless of the previous status.
Also I would expect that in any case an order-note is added and an E-Mail is sent to the shop admins.

One approach for correcting this is to change the function to ignore the order status and always set it to failed.
Another way would be to provide a hook in the `process_webhook` function so custom code can be developed.

**Comment by roykho** [comment]
That is correct. All the methods that are asynchronous will get an on-hold status initially. The failing webhook listener only works with the asynchronous methods so it only needs to look for on-hold statuses and ignore everything else which won't have on-hold status to begin with.

So the question then becomes why are you changing the status from on-hold for an asynchronous payment?

**Comment by kmindi** [comment]
Because I would like to trust the customer in providing the correct payment information and that the payment will succeed, so I set (or better let a plugin automatically set https://github.com/kmindi/wc-stripe-asynchronous-payments-pending-to-payment-complete (as described in #636 ) "payment complete" wich changes the order status. 

I hope this is not a discussion about why one would do that, but **it is possible and is being done apparently**. So the function should be more robust IMHO.

Is it important if the order is not in "on-hold" status? Which status of an order would you not update, if the payment failed?

**Comment by kmindi** [comment]
SEPA direct debit is Asynchronous and that is handled via webhook. 
Or are you saying asynchronous payments will fail either as the charge is created or do not fail? (I guess this is not the case, as a sepa direct debit can fail because the account has not enough funds to be debited, and then it will fail, and then the webhook will be called).

This is referring to SEPA direct debit, which is one of the most common payment methods in Germany, and I want to change the order status to payment complete, because I want the customer to get access to subscription/member area right after he finished the order and the payment is being processed.

**Comment by roykho** [comment]
Sorry that was a typo, I meant "Synchronous does not need webhook...". I will think more about this and see if there are any improvements that can be made.
