### ISSUE TITLE
Stripe Checkout + Apple Pay results in unexpected/incorrect behavior

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#640]
#### Affected ticket(s)
ticket: 1130467-zen

#### What I expected
For Apple Pay to work regardless of whether the modal checkout option is selected or not.

#### What happened instead
Try to pay with Apple Pay but end up redirected to the "pay for order" page and then prompted for credit card details.

#### Steps to reproduce the issue
1. Payment request buttons are enabled
2. Stripe checkout enabled
3. Press the Apple Pay button on a single product page
4. Try to pay

These are the steps in Safari on my laptop. Haven't tried with a phone.

-------------------

- [ ] Issue assigned to next milestone.
- [ x] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@WillBrubaker is this issue happening "after" the Apple Pay payment sheet that slides down? Or as soon as you click on the Apple Pay button on the site?

**Comment by WillBrubaker** [comment]
It's after the sheet slides down, here's a quick screencast of it happening with the simulator http://cld.wthms.co/te47LC and you can see it in action here: https://wctesting.club/product/woo-single-2/

**Comment by roykho** [comment]
When you get a chance, please test this branch https://github.com/woocommerce/woocommerce-gateway-stripe/tree/fix/issue-640 to see if it fixes the issue for you. Thanks!
