### ISSUE TITLE
Email as Username identifier in Stripe not ideal

### ISSUE THREAD

**Issue by githubyaya** [woocommerce/woocommerce-gateway-stripe#643]
Thank you first of all for a great plugin! We have been using Wordpress / WooCommerce with  Stripe for some time now, and it works excellent. There is one issue though, that I am hoping to highlight with this ticket.

When a new Customer is created in Stripe via this plugin, the Email address from Wordpress is used as the Customer name in Strip (and not the Username from Wordpress). The issue with this approach is that a user can at a later stage change the Email in Wordpress to something completely different. That means the shop owner, who wants to locate a payment in Stripe, might search for an incorrect email address in Stripe (the new email address found in WP), whereas in fact the customer is still recorded with the old email address as identifier in Stripe.

It would therefore be better if the Username field in Wordpress was used as the Customer name in Stripe. The reason why this would be better is that the Username cannot be changed in Wordpress. Once a user is created they can never change their name - its not even possible from WP-Admin. This would create an unbreakable 1-1 identifier bond between the Wordpress identifier data, and the Stripe identifier data. The email information could still be passed along as meta data, so that the email is still available in the Stripe Customer card.

There are other implications here as well, such as the new GDPR directive. If a client asks for his personal identifiable information to be deleted, a web shop owner will HAVE to delete the email. But a random, non personal username will not need to be changed. So to base the Stripe customer identifier on Username is better from this perspective too.

Please let us know your thoughts on this, and if you would like any clarification on the above? We can send screen shots to clarify, and also show you examples of exactly what happens if a user does change their email, and then makes a second payment, and what that looks like in Stripe and in the backend of Wordpress.

With hope that this small modification can be made, and making a great plugin even better!

With best regards/
Fredrik

**Comment by roykho** [comment]
This has already been discussed. It only happens if you're using Stripe Modal Checkout.

**Comment by githubyaya** [comment]
Ok, thank you for clarifying that. May I ask three follow up questions:

- What is "Stripe Modal Checkout"? 
- If the Username *is* used as the identifier when customer cards are created in Stripe in some scenarios by the plugin, why is it not used in all scenarios?
- Do you share the view that it is better if the Stripe customer cards are created with Username rather than Email as the customer name?

**Comment by roykho** [comment]
> What is "Stripe Modal Checkout"?

This is where you're using the POPUP that comes up for payment

> If the Username is used as the identifier when customer cards are created in Stripe in some scenarios by the plugin, why is it not used in all scenarios?

I believe this is the limitation on Stripe not our plugin.

> Do you share the view that it is better if the Stripe customer cards are created with Username rather than Email as the customer name?

Yes and that is why is done this way when not using Stripe Checkout.

**Comment by githubyaya** [comment]
Thank you for clarifying. But curiously, we are not using any pop-up - we are using the default Stripe form that gets embedded in the WooCommerce checkout page. To clarify; we do NOT have the box "Enable Stripe Checkout" ticked - this is unticked in our Stripe plugin settings. If I understand you correctly, then the Username SHOULD be used as the Stripe Customer name? How can we investigate why it is not?

On a possibly related side note, we recently upgraded to Radar 2.0 on Stripe, but even then the Username is not seen anywhere on our Stripe customer cards. Neither as the Stripe Customer Name (here the email is still shown), nor anywhere else on the Stripe Customer card.

**Comment by githubyaya** [comment]
![image](https://user-images.githubusercontent.com/39340924/40132652-46ad156a-5935-11e8-82d3-ec6eecbfcd9b.png)

**Comment by githubyaya** [comment]
This is that same user on Stripe - as you can see from the top marked in red, the Customer is named after his first email (when the first order was made). And the Username from WP (just "test2018050802dd") is nowhere to be found on this Stripe Usercard. This is Radar 2.0.

**Comment by githubyaya** [comment]
If we then look at his latest payment in Stripe (after the email address was changed), we can see the new email being recorded for this payment (even though the Stripe payment card is still under the old email). And the meta data field "customer_name" is empty.

**Comment by githubyaya** [comment]
![image](https://user-images.githubusercontent.com/39340924/40133217-fdf447a6-5936-11e8-8c8d-ee6abfb9f8c2.png)

**Comment by githubyaya** [comment]
If we then look at his latest payment in Stripe (after the email address was changed), we can see the new email being recorded for this payment (even though the Stripe payment card is still under the old email). And the meta data field "customer_name" is empty.

**Comment by githubyaya** [comment]
![image](https://user-images.githubusercontent.com/39340924/40133232-0b1ba67c-5937-11e8-95cd-94cfe9d79cd2.png)

**Comment by githubyaya** [comment]
However, further down on that same Stripe Payment page, we see a link to the Stripe Customer Card, and here agin you can see the old email is used as the identifier of this customer.

**Comment by githubyaya** [comment]
![image](https://user-images.githubusercontent.com/39340924/40133326-486719f8-5937-11e8-9e6b-227c377575fc.png)

**Comment by githubyaya** [comment]
Finally, when you search for this customer in Stripe, you will see the Customer's main identifier seems to be the first Email address from WP, not the Username from WP.

**Comment by githubyaya** [comment]
![image](https://user-images.githubusercontent.com/39340924/40133423-9fa3bff0-5937-11e8-85ea-7cad9281eb99.png)

**Comment by githubyaya** [comment]
Hope all of this can help shed some further clarity of the issue we are seeing. Happy to get on a SKype call if you think that would help.

**Comment by roykho** [comment]
As for the customer card reference, that is not related to the plugin. That is how Stripe works. If you go to your Stripe dashboard and click ADD NEW customer you're presented with this dialog ![](http://cld.wthms.co/KYhl3v+) After you finish, you will see the name has the email on it.

**Comment by githubyaya** [comment]
You are correct that we were talking about different things, and thank you, I was not aware that Stripe asked for email as the "main customer identifier". I will ask the Stripe support about this, since I still feel it is a weakness that a user in WP can change email, thereby breaking the 1:1 visual connection to the identifier in Stripe. Many sites in WP are using Stripe.

With the above in mind, I have one small ask/idea for you and the plugin. Could the plugin populate the "Description" field in Stripe with the Username from WP? I notice that today when using your plugin, the Description field on the Stripe customer card is left empty. This could be a good place to put the Username from WP, so that at least it is somewhere in Stripe. What do you think about that idea?

**Comment by githubyaya** [comment]
![image](https://user-images.githubusercontent.com/39340924/40139984-8c525f6c-5949-11e8-831e-0a8deccd3002.png)

**Comment by roykho** [comment]
It already does that. ![](http://cld.wthms.co/tmRDK3+)

**Comment by githubyaya** [comment]
Hmm, does it possibly take the Firstname and Lastname from WP and put it here, but not the Username? The Username is the only field that cannot be changed in WP, and therefore the most "permanent" information to link between WP and Stripe. 

In the examples I have sent you, this is the user we are using in WP (see screen shot below). As you can see from the previous screenshot (above), the Description is empty for us.

**Comment by githubyaya** [comment]
![image](https://user-images.githubusercontent.com/39340924/40140548-230581ae-594b-11e8-8033-9a2cb332ce7a.png)

**Comment by roykho** [comment]
Yes it takes the billing firstname and lastname.

**Comment by roykho** [comment]
You can always pass your own data through using this filter `wc_stripe_customer_metadata`

**Comment by githubyaya** [comment]
Would it be possible to change this, and take the Username instead of Firstname + Lastname (based on this being the only information that cannot change in WP)? By using Email, Firstname and Lastname, there is a possibility that if the user changes all three in WP, no information will be teh same in WP and Stripe. So you could argue that Username would be better to put here?

**Comment by githubyaya** [comment]
To clarify, what I meant by "Would it be possible to change this" is: would you consider changing the plugin, so that is uses Username instead to populate the Description field? Based on the reasoning above - that it might be better with a permanent identifier?

**Comment by roykho** [comment]
Not at this time no. People requested the billing name to be added there in the past.

**Comment by githubyaya** [comment]
OK. With your more detailed knowledge of Stripe and WP, is there possibly another Stripe field where the plugin could populate the Username from WP? I am sure you see the benefit of using the one information that cannot be changed as part of the information exchange.

**Comment by thorsten-stripe** [comment]
@roykho it sounds like this would be useful for all users, though, no? Could you evaluate adding the wordpress username as separate metadata on the customer and charge objects and potentially appending it to the description as well?

**Comment by roykho** [comment]
@thorsten-stripe This is the first time hearing about a request like this. And it is already possible by using filter `wc_stripe_customer_metadata` as mentioned above.

**Comment by githubyaya** [comment]
I understand it is doable with the wc_stripe_customer_metadata somehow. But most Wordpress implementations will use this plugin together with WooCommerce "out of the box", i.e. they will use this plugin just as it is - with no modifications. 

I will give you a real case scenario of when this would be a problem with the current functionality.

A website is using WP + WooCommerce + WooSubscriptions with automatic renewals. A customer signs up to a new subscription with monthly auto renewal the following information in WP:
Username: superwoman
Firstname: Sara
Lastname: Petersen
Email: sara.petersen@gmail.com

The Stripe customer card will have the following details: "sara.petersen@gmail.com, Sara Petersen".

A few months pass, and the customer gets married. She changes her name to Sara Hoffman. She changes her details on the website as follows:
Username: superwoman (which can never be changed in WP)
Firstname: Sara
Lastname: Hoffman
Email: sara.hoffman@hotmail.com

The autorenewal of her subscription continues as normal after that, but the only detail now matching her WP profile and her Stripe profile  is "Sara". And this website has many of clients named Sara, so it's difficult to search for only "Sara" in Stripe - it will produce many matches.

A few months later Sara contacts the customer support of the website. The person working at customer support only has access to WP-Admin, not direct SQL access to the WP database, and is therefore unable to locate any "deep" information such as the "Customer ID" on the format cus_CuhiuLDYyyMcXW. So this agent can only access Saras NEW customer card in WP. Sara asks about a full history of her payments, and refers to the GDPR directive. The customer services agent can only search on sara.hoffman@hotmail.com in Stripe, and cannot easily find the older payments done with Sara's old email in Stripe.

If the customer agent would have been able to search for "superwoman", they would have been able to find all previous payments in Stripe.

WooCommerce is a great platform, and Stripe is a great payment platform, and this plugin is great too. I do not understand the hesitation to make it even better / safer / more user friendly out of the box?

**Comment by roykho** [comment]
Re-reading your concern, I see you mentioned GDPR. Please note that the whole WP ecosystem around GDPR will be based off of the email used. Not username.

**Comment by roykho** [comment]
@githubyaya after looking into the code some more, this change will not affect current users so I went ahead and added in the description `Name: John Doe Username: john_doe` etc. I hope that helps.

**Comment by githubyaya** [comment]
That is really good news - thank you so much. I am sure it will benefit all users of WooCommerce and Stripe. Which version will the change be released in? 

I will also go ahead and delete the images I submitted in this thread, not that they disclose much, but just for some added privacy protection. 

Thanks again for a great plugin!
