### ISSUE TITLE
Adding Apple Pay / Payment Requests back to the checkout page

### ISSUE THREAD

**Issue by clifgriffin** [woocommerce/woocommerce-gateway-stripe#644]
In 4.0, the Apple Pay button was removed from the checkout page. 

This was noted in a support topic here:
https://wordpress.org/support/topic/allow-apple-pay-or-google-pay-in-checkout-page/

I've done testing with the latest version and looked through the change logs. It looks like this hasn't made the cut in subsequent releases.

Is this still in the works?

**Comment by roykho** [comment]
No we will not put that back. It doesn't make sense to show it there by default. Filters are available if you want to put it back.

**Comment by clifgriffin** [comment]
@roykho Ok, just asking since it was suggested it would be added back. I'll look for said filters, thanks.
