### ISSUE TITLE
Stripe customer Description field empty when using Chrome Payment request

### ISSUE THREAD

**Issue by therealgilles** [woocommerce/woocommerce-gateway-stripe#645]
#### What I expected

With other payment methods, the Stripe customer Description field (under Connections) contains the customer name.

#### What happened instead

When using Stripe Chrome Payment request, the customer Description field is empty instead (or maybe a blank space).

I think it would be nice to have a consistent behavior. Found out this issue because it ended up creating an issue with one of the side services I used to reconcile Stripe transactions in Xero.

**Comment by roykho** [comment]
I don't believe there is a description parameter to pass. cc @thorsten-stripe to confirm.

**Comment by therealgilles** [comment]
Looking at other transactions, it does not seem to be related to Chrome Payment request after all. Below is are the Details of one of my customers in Stripe and the extract of the request that created the customer:

![screen shot 2018-05-17 at 1 41 49 am](https://user-images.githubusercontent.com/18076992/40166650-e9fafea6-5973-11e8-81b3-2ad4591f7b18.png)

![screen shot 2018-05-17 at 1 53 30 am](https://user-images.githubusercontent.com/18076992/40167186-38e54ea8-5975-11e8-9a98-30dcf6b0dc01.png)

You can see the Description field is a blank space string.

**Comment by therealgilles** [comment]
Here is the POST request that created the customer with the blank space description:

![screen shot 2018-05-17 at 1 55 40 am](https://user-images.githubusercontent.com/18076992/40167320-9dfbbe9e-5975-11e8-85de-6faea8273180.png)

Maybe this bug has already been fixed?

**Comment by therealgilles** [comment]
The code creating the customer (below) does not seem to check whether $billing_first_name and $billing_last_name are not empty strings and creates a description with an empty string in such case:

`	public function create_customer( $args = array() ) {
		$billing_email = isset( $_POST['billing_email'] ) ? filter_var( $_POST['billing_email'], FILTER_SANITIZE_EMAIL ) : '';
		$user = $this->get_user();
		if ( $user ) {
			$billing_first_name = get_user_meta( $user->ID, 'billing_first_name', true );
			$billing_last_name  = get_user_meta( $user->ID, 'billing_last_name', true );
			$defaults = array(
				'email'       => $user->user_email,
				'description' => $billing_first_name . ' ' . $billing_last_name,
			);
		} else {
			$defaults = array(
				'email'       => $billing_email,
				'description' => '',
			);
		}`

Maybe you will consider that this is not a bug?

**Comment by therealgilles** [comment]
After reviewing all my customers with a blank space Description field, they all seem to have been created in 2017, so I am guessing the behavior has since been fixed.
