### ISSUE TITLE
Support for multiple Stripe accounts

### ISSUE THREAD

**Issue by dmseaton** [woocommerce/woocommerce-gateway-stripe#646]
I'm working on something at the moment that would benefit from multiple account support - in my implementation, a different key pair is assigned depending on the user's billing country. It needs some additional work before it'd be suitable for contributing, so I wanted to check:

- Are there existing plans to support multiple authentication key pairs?
- Do you know of any reason why this might not be possible with the Stripe API?

The main issue I've run into is the Stripe source ID being mismatched following a change to the key, I assume because the source has been generated based on whatever key was set on checkout load. Any input on this would be helpful, and I'll create a PR for anything I get working successfully (assuming it's desirable).

**Comment by roykho** [comment]
Please post ideas here http://ideas.woocommerce.com/forums/133476-woocommerce
