### ISSUE TITLE
Only redirect if source.redirect.status is pending

### ISSUE THREAD

**Issue by thorsten-stripe** [woocommerce/woocommerce-gateway-stripe#647]
@roykho can you add the following check?

1) before redirecting[0] check that `redirect.status` === pending

I believe that the lack of this is causing an issue that was flagged by a user:

* after 3DS source creation the source is returned with `status:chargeable` and `redirect.status:not_required`[1]
* webhook charges the source which sets the source to consumed, however the charge fails
* upon redirect return the status of the source is consumed causing `process_redirect_payment` to return without error, which I believe then causes their LMS plugin to grant access to the user although the charge failed.

Unfortunately we currently do not have a test card for this scenario so this is somewhat speculative, however, the addition of the redirect status pending check should be valuable nonetheless.

[0] https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L726-L731
[1] https://stripe.com/docs/api#source_object-redirect-status

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Is that normal for that to happen? In what cases does a 3DS required card synchronously come back as `chargeable` and not require you to redirect to bank for login? Isn't that defying the purpose of a 3DS security?

But assuming we do this check. What is the flow if it indeed comes back chargeable? Do we just make the charge request right there and then and not do the redirect?
