### ISSUE TITLE
Stripe Checkout ( popup modal ) "Place Order" button translatable?

### ISSUE THREAD

**Issue by spawn100** [woocommerce/woocommerce-gateway-stripe#648]
Hi,
I actually like the Stripe Checkout popup modal. It looks great on a smartphone (80% of my customer use smartphones). It also translates to Japanese (the language of my customers), but the page before the popup doesn't translate the "Place Order" button. I also can't find it in Loco Translate.
Can someone help me change the Place Order button to Japanese?

**Comment by roykho** [comment]
This is not a support channel. Please post here https://wordpress.org/plugins/woocommerce-gateway-stripe/
