### ISSUE TITLE
GDPR: Export empty for customer data

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-gateway-stripe#651]
Reported here: https://github.com/woocommerce/woocommerce/issues/20196#issue-326119740 I've not tried to replicate, just passing it on :)

---

**Describe the bug**
Tested the data export functionality of 3.4 + 4.9.6. When exporting, nothing is show for Stripe.

**To Reproduce**
Make some purchases using Stripe
Request User data to be exported using 4.9.6 functions
Open data, Stripe section open
stripe in sec data

Note:

Testing done on site that uses Stripe only in test mode, is this the reason?
Stripe V4.1.4

**Comment by roykho** [comment]
Those two particular fields are only exported if there is a saved customer/saved payment method. As I recall, empty fields should not be exported by core.

**Comment by mikejolley** [comment]
@roykho "core"? The returned export data is handled in Stripe no? In WooCommerce we simply skip empty values and don't add to response.

**Comment by mikejolley** [comment]
So why is it shown in that report's screenshot ^ :p See https://github.com/woocommerce/woocommerce/issues/20196#issue-326119740

**Comment by bor0** [comment]
Let's see what happens with [#44215](https://core.trac.wordpress.org/ticket/44215) in core.
