### ISSUE TITLE
Add idempotency key to logged failed request

### ISSUE THREAD

**Issue by javorszky** [woocommerce/woocommerce-gateway-stripe#655]
Had a back and forth with Stripe support, and they were super happy I included the idempotency keys in the logs I gave them, as it helps them look things up.

Based on that, I think it's a good idea to include that as well - if exists - into the logged failure.

Related: #652 

PR incoming

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Is this only in particular to API request failure like empty responses and timeouts..etc?

**Comment by javorszky** [comment]
Not necessarily. The problem I'm solving on a client site by modifying core plugin files (they're on 3.0.2, and won't be updating because the site is getting sunset) is that I need to correlate failures to requests.

From the support rep's answers, it seems like it's easy for them to look up requests grouped by the idempotency keys.

Any of the requests can fail btw, charge, customer, refund... also probably all requests that CAN fail (ie all of them) should have the idempotency key, not just the POST charges

Not sure if this answered your question.

**Comment by javorszky** [comment]
And uh... no, I think this could also be used if Stripe actually successfully sends an error response back, so it fails on their end instead of on the network layer.

They still need to investigate it, and every little bit helps :)

**Comment by javorszky** [comment]
Oh gotcha. You mean why isn't it in the `WC_Gateway_Stripe::process_payment` method?

I guess at that time there's enough other logs and handling that it's useful whereas a request failure due to some technical issue is a lot harder.

So given that, yes, this is in particular to the actual API call
