### ISSUE TITLE
Radar 2.0 Integration

### ISSUE THREAD

**Issue by cosmass** [woocommerce/woocommerce-gateway-stripe#658]
Hello!

Is there a way to be compliant with RADAR 2.0 using this plugin? See attached a screenshot of my live radar integration checklist. My wordpresss / woocommerce and plugin are all up-to-date.

Thanks in advance.

![captura de pantalla 2018-05-25 a las 22 45 34](https://user-images.githubusercontent.com/3669514/40565623-8d54d41e-606d-11e8-99d2-c5a6c8f8bcdb.jpg)

**Comment by roykho** [comment]
Please post those types of support questions here https://wordpress.org/plugins/woocommerce-gateway-stripe/
