### ISSUE TITLE
Extra indentation with the default checkout styling

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce-gateway-stripe#661]
The Stripe method has extra indentation. Using latest version of just WooCommerce and Stripe.

Twenty Seventeen:

![](https://cld.wthms.co/rPVGVZ+)

Storefront:

![](https://cld.wthms.co/qjwpu9+)

Here is the offending CSS: http://cld.wthms.co/eOe3eO

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/assets/css/stripe-styles.css#L73

CC @roykho 

Quick fix for support requests:

```
#add_payment_method #payment .payment_method_stripe label[for=payment_method_stripe],
.woocommerce-checkout #payment .payment_method_stripe label[for=payment_method_stripe] { 
    padding-left: 0 !important;
}
```

**Comment by liviopv** [comment]
also reported in 1184418-zen

**Comment by WPprodigy** [comment]
Introduced in https://github.com/woocommerce/woocommerce-gateway-stripe/commit/8c85d904bde2fc67f9f478e6645398300a2428cd#diff-edf049b38c9d61e8b6b3f472833de141

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/commit/0bc0609d21f9133afb888b74272ad0eca7f06ebb

**Comment by roykho** [comment]
In fixing this, it broke other themes! This fix worked for me in 2017 and Storefront as seen here ![](https://cld.wthms.co/kXVCe3+)

But on customer site they see this https://ibb.co/jmeJYJ

Customer complained here https://wordpress.org/support/topic/stripe-check-box-after-last-update/

**Comment by roykho** [comment]
This is because in some themes, it hides the radio input field and adds its own radio button style to the label. Other themes, it does not.

**Comment by WPprodigy** [comment]
Well, I think working in default themes, Storefront, and Divi is a better indicator that something is wrong in those themes that they need to fix.

Why doesn't this happen with other gateways in those themes?

**Comment by roykho** [comment]
@madeincosmos you can remove the `absolute` and `block` but you will quickly find issues in other places/themes. I've been looking at this whole morning and can't come up with a solution that will satisfy all parties. If you can solve this, I would like to see your solution.

**Comment by madeincosmos** [comment]
One more user with the same problem in 1191853-zen

**Comment by madeincosmos** [comment]
BTW I tried removing lines 41-42 & 71-72 from here: 

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/assets/css/stripe-styles.css#L41-L42

This fixed the radio button without affecting the floating icons in any way, both on full screen and in mobile.

Do the icons need some special handling in some particular theme?

**Comment by roykho** [comment]
@madeincosmos its not just the icons. Its a number of things happening. Now test your changes in "add payment method" page and also test it on Storefront/TwentySeventeen checkout page/add payment page. Or a theme that does not have special style for radio buttons.

**Comment by madeincosmos** [comment]
One more user of the same problem: 1189182-zen

**Comment by corsonr** [comment]
I had this issue a couple times too, and I had to provide some custom CSS to fix it. Adding myself to the loop ;-)

**Comment by dougaitken** [comment]
To loop this back into here - I tested #666, works for Flatsome
