### ISSUE TITLE
Radio button for Stripe misplaced on the checkout page

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-stripe#665]
#### Affected ticket(s)

1189303-zen

#### What I expected

To use Stripe with a theme that doesn't have special styling for WooCommerce.

#### What happened instead

The radio button for Stripe on the checkout page overlaps with method label. This doesn't happen for WooCommerce core payment methods.

Here is how it looks like with Twenty Twelve:

![Screenshot](http://cld.wthms.co/Z8GkDu+)
Screenshot: http://cld.wthms.co/Z8GkDu

Twenty Thirteen:

![Screenshot](http://cld.wthms.co/fBRYyE+)
Screenshot: http://cld.wthms.co/fBRYyE

Genesis:

![Screenshot](http://cld.wthms.co/OJU7FO+)
Screenshot: http://cld.wthms.co/OJU7FO

Note that this problem doesn't happen with Storefront or Twenty Seventeen as both have additional styles for the checkout form.

#### Steps to reproduce the issue

1. Enable a theme that doesn't have special CSS for WooCommerce (such as Twenty Twelve),
2. Go to the checkout page and compare Stripe with WooCommerce core payment methods.

These two styles seem to make the difference - disabling them makes the button align correctly with the rest:

```
.woocommerce-checkout #payment input#payment_method_stripe, #add_payment_method #payment input#payment_method_stripe {
    position: absolute;
}

.woocommerce-checkout #payment .payment_method_stripe label[for=payment_method_stripe], #add_payment_method #payment .payment_method_stripe label[for=payment_method_stripe] {
    display: block;
}
```

Other Stripe payment methods (Sofort, SEPA, etc) might have the same problem too.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Closed in favor of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/661
