### ISSUE TITLE
"Stripe is enabled, but a SSL certificate is not detected" showing incorrectly.

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce-gateway-stripe#667]
This notice is showing on a customer site incorrectly: ![](http://cld.wthms.co/UA7uRJ+)

The condition in Stripe is just this now https://github.com/woocommerce/woocommerce-gateway-stripe/blob/d67475365dee9ef73ebcb06ddd1a96f0b729fc3b/includes/admin/class-wc-stripe-admin-notices.php#L178

And that function comes from WC and is simply: https://github.com/woocommerce/woocommerce/blob/228b888ab6162692392d3e49829a8e64f6b5dc88/includes/wc-conditional-functions.php#L397

Did some quick debugging, and it looks like `function_exists( 'wc_site_is_https' )` is failing by itself in the Stripe conditional.

But if I add a `die()` in that function in WC core on my test site, it does affect the loading of admin pages. So, quite odd?

Any ideas on what to check next?

CC @roykho 

1189777-zd

**Comment by roykho** [comment]
This was already fixed here https://github.com/woocommerce/woocommerce-gateway-stripe/commit/d4d2ed00e5f1ec89a0b45b1e8548811398bd228d
