### ISSUE TITLE
Feature Request: Support for Webhook Signing

### ISSUE THREAD

**Issue by jeremiahbenes** [woocommerce/woocommerce-gateway-stripe#668]
#### What I expected

Stripe has the ability to sign webhook responses ensuring events are sent by Stripe and not a third party. All that's required to enable this is adding the webhook signing secret. ([link to documentation](https://stripe.com/docs/webhooks/signatures))

Other Stripe integrations such as the one for Gravity Forms support this. While optional, this would be a good way to increase a site's overall security posture.

For reference, here's an example image of the signing secret in the Stripe panel.

![Stripe Signing Secret](https://image.ibb.co/cLt3Ly/stripe_webhook_signing.jpg)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by laurendavissmith** [comment]
Moved to the ideas board: http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/34518652-support-for-webhook-signing
