### ISSUE TITLE
Fatal error: Class 'WC_Payment_Gateway_CC' not found in Woocommerce site

### ISSUE THREAD

**Issue by nicoleneves** [woocommerce/woocommerce-gateway-stripe#669]
Hi there

I am having the above issue on my woocommerce site (the-blankproject.com). The page is just blank with this error message:

Fatal error: Class ‘WC_Payment_Gateway_CC’ not found in /home/blank232/public_html/wp-content/plugins/woocommerce-gateway-stripe/includes/abstracts/abstract-wc-stripe-payment-gateway.php on line 13

I can’t access my admin site either.

I haven’t installed or edited anything new lately so this is coming out of the blue.

I have accessed my file manager and located the error address but I don’t know what to do with it.

Can someone shed a light please? I’m starting to panic a bit.

THANK YOU SO MUCH!
Nicole

**Comment by roykho** [comment]
It
