### ISSUE TITLE
Need method for testing succeeded/failed payments with SOFORT

### ISSUE THREAD

**Issue by manwithpowers** [woocommerce/woocommerce-gateway-stripe#670]
Stripe's documentation for testing a successful/failed payment using SOFORT states:
>  You can mimic a successful or failed charge by creating a test source with one of the following values for the owner[name] parameter. Use this source to create a test charge that either succeeds or fails.
> 
>     succeeding_charge: The charge status transitions from pending to succeeded
>     failing_charge: The charge status transitions from pending to failed

Unfortunately, I've found no way to input this, as both the frontend checkout form for WooCommerce/Storefront and the backend `get_owner_details` function require a First _and_ Last Name and I'm unable to enter in Stripe's requested name. Even when I'm able to get around the First and Last Name validation check on the frontend form, the `get_owner_details` function adds a blank space (Line 517 in [abstract-wc-stripe-payment-gateway.php](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/abstracts/abstract-wc-stripe-payment-gateway.php)).

Is there a method for testing a successful/failed SOFORT charge? Is there some way to allow for using a test `owner[name]` when Stripe is in Test Mode? I'm open to any suggestions, we just need a relatively easy way to thoroughly test the SOFORT payment path.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Please post all support questions here https://wordpress.org/support/plugin/woocommerce-gateway-stripe/
