### ISSUE TITLE
Stripe Double Charge

### ISSUE THREAD

**Issue by s7ech** [woocommerce/woocommerce-gateway-stripe#674]
Hello,
I would like to report about a major issue that we and I believe others who use Stripe have the same problem with double charging our customers.

Here is the notes log: https://s.nimbusweb.me/share/1785599/r0mwlqdb9wzttpoib599
Here is the Stripe log: https://s.nimbusweb.me/share/1785585/al429tqoikiz56triq5v
Here is the Stripe settings: http://nimb.ws/ViQcfz

Our IT Dept. investigation results;

1. Some customers are using mobile devices to pay
2. The customers are pressing the payment button once
3. Some of them have a low Internet connections (WiFi and Mobile Data)

Can you tell me why and how to solve it?

**Comment by roykho** [comment]
Please provide more information.

* Is this reproducible every time?
* Does this only happen with a bookable product?
* Have you tested this yourself?
* Are you using webhooks?
* What payment method was used? Credit card? Payment request? or something else?

**Comment by s7ech** [comment]
1. - From 100 payments 5-6+ will be double charged
2. - Only with a bookable products
3. - Every test is successful and no double charges with me
4. - I am not using webhooks
5. - Credit Card
6. - Version 4.1.6

**Comment by roykho** [comment]
Ok since this cannot be replicated, it requires more digging into your site. I would suggest you open up a ticket on woocommerce.com. Go to the support section.

**Comment by s7ech** [comment]
The support told me to post the issue here, you are telling me to go back at woocommerce... what should I do man?

**Comment by roykho** [comment]
Do you have a ticket #?

**Comment by s7ech** [comment]
No. The support from the chat said to submit all the info here.

**Comment by roykho** [comment]
Ok sorry for the run around but we can't diagnosis this here unfortunately as it requires access to your site. So please get with woocommerce.com support and ask that they open up a ticket for you. You can then supply your site information and someone will be able to have a look.
