### ISSUE TITLE
Incompatibility with instagram feed plugin?

### ISSUE THREAD

**Issue by 24misi** [woocommerce/woocommerce-gateway-stripe#680]
#### What I expected
When I access the "Checkout" page, I should be able to write my credit card number in the stripe checkout field. And then make the payment successfully.

#### What happened instead
Whenever the Instagram feed Plugin is activated, the field to introduce the credit card number doesn't appear, so you cannot introduce your credit card number and make the payment. 
If you deactivate the Instagram feed Plugin, the field appears again and you can introduce your credit card number.

#### Steps to reproduce the issue
1. Activate Instagram Feed Plugin (https://es.wordpress.org/plugins/instagram-feed/)
2. Add some items to your cart
3. Proceed to checkout page and scroll down until the payment area

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Thanks, but please post your idea here http://ideas.woocommerce.com/forums/133476-woocommerce

**Comment by 24misi** [comment]
Thanks, it wasn't an idea. I just wanted to know if it was a problem of woocommerce gateway stripe plugin or if it's a problem of the Instagram plugin (in order to write to them). 
Thanks for your answer in advance

**Comment by roykho** [comment]
So your title stated "incompatibility". Compatibility between plugins are considered a feature here and not a bug. So posting it on ideas board would help validate if people are using these specific two plugins together and that ultimately drives the question of if we should take action or not.
