### ISSUE TITLE
3DS not_required response triggers webhook

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-gateway-stripe#684]
In this scenario we have 3DS enabled and we are making use of webhooks. The following filter is also being used to require optional 3DS payments (but this doesn't change the behaviour):

```
add_filter( 'wc_stripe_require_3ds', '__return_true' );
```

The scenario which I'm seeing with a live transaction is the following (copied from the log with some data removed):

```
01. 17:27:46 Info: Begin creating 3DS source...
02. 17:27:46 sources request: ...
03. 17:27:47 Info: Begin processing payment for order 8090 for the amount of 10.00
04. 17:27:47 charges request: ... Idempotent key 8090-src_ABCi0OLexAc2QLzfj396YvPZ
05. 17:27:51 Info: (Webhook) Begin processing payment for order 8090 for the amount of 10.00
06. 17:27:51 charges request: ... Idempotent key 8090-src_ABCi0dLexAc2QLzfxWVHx89R
07. 17:27:51 Processing response: ... ch_ABCi0eLexAc2QLzfQA1a09ay
08. 17:27:54 Error: (
    [error] => (
            [charge] => ch_ABCi0hLexAc2QLzfsce2VSHH
            [code] => card_declined
            [decline_code] => do_not_honor
            [doc_url] => https://stripe.com/docs/error-codes/card-declined
            [message] => Your card was declined.
            [type] => card_error
        )
)
```

In step 2 we get a response back from Stripe that 3DS is `not_required`. This is different then is stated in the documentation and what I get on my test site with sandbox mode: https://stripe.com/docs/sources/three-d-secure#check-requirement

It seems that in step 5 it is responding to a webhook event type `source.chargeable`. On my test site with sandbox mode I can also see this webhook being sent when a card is not supported. However these are the main differences between the webhook events:

Live site:

```
object > redirect > status = not_required
object > type = three_d_secure
```

Test site:

```
object > card > three_d_secure = not_supported
object > type = card
```

There aren't any test cards to replicate the scenario of not_required, so they are slightly different. For the test scenario we can see that the webhook handler skips object > type card, see: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.1.7/includes/class-wc-stripe-webhook-handler.php#L125-L128

But the scenario on the live site is not caught so it tries to process a second charge.It looks like this is caught further up and then returns a card_error. This causes both the card declined message and the successful payment to be logged in the order notes.

In this case it seems it should also be ignoring the webhook and only process the payment normally. Here is the full log of the event sent by stripe (removed private data):

```
{
  "object": {
    "id": "src_ABCi0dLexAc2QLzfxWVHx89R",
    "object": "source",
    "amount": 142568,
    "client_secret": "src_client_secret_CzhPp2Wry07P0vcI8Uh7XABC",
    "created": 1528216067,
    "currency": "gbp",
    "flow": "redirect",
    "livemode": true,
    "metadata": {
    },
    "owner": {
      "address": {
        "city": "City",
        "country": "EU",
        "line1": "Address",
        "line2": "",
        "postal_code": "12345",
        "state": "ST"
      },
      "email": "abc@gmail.com",
      "name": "First Last",
      "phone": "+12345",
      "verified_address": null,
      "verified_email": null,
      "verified_name": null,
      "verified_phone": null
    },
    "redirect": {
      "failure_reason": null,
      "return_url": "https://domain.com/checkout/order-received/8090/?key=wc_order_abc6b9f9e1808&utm_nooverride=1&order_id=8090",
      "status": "not_required",
      "url": "https://hooks.stripe.com/redirect/authenticate/src_ABCi0dLexAc2QLzfxWVHx89R?client_secret=src_client_secret_CzhPp2Wry07P0vcI8Uh7XABC"
    },
    "statement_descriptor": null,
    "status": "chargeable",
    "three_d_secure": {
      "card": "src_ABCi0OLexAc2QLzfj396YvPZ",
      "customer": null,
      "authenticated": false
    },
    "type": "three_d_secure",
    "usage": "single_use"
  },
  "previous_attributes": null
}
```

Affected ticket: 1205731-zen

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce-gateway-stripe/pull/685
