### ISSUE TITLE
3DS optional doesn't handle the final redirect.

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-gateway-stripe#688]
If we enable 3DS in the payment settings. It will only try to the additional check if it's required or recommended.

However it's also possible that it returns optional. In this case Stripe recommends the following:

> The process isn’t required but can be performed to help reduce the likelihood of fraud.

If we want to attempt 3DS when it's optional we can use a filter something like:

```
add_filter( 'wc_stripe_require_3ds', '__return_true' );
```

This allows it to send the 3DS Source request. But we can get a different reply back which prevents it from doing the actual redirect. For example we get a reply back something like this (removed private data):

```
{
  "object": {
    "id": "src_ABCi0dLexAc2QLzfxWVHx89R",
    "object": "source",
    "amount": 142568,
    "client_secret": "src_client_secret_CzhPp2Wry07P0vcI8Uh7XABC",
    "created": 1528216067,
    "currency": "gbp",
    "flow": "redirect",
    "livemode": true,
    "metadata": {
    },
    "owner": {
      "address": {
        "city": "City",
        "country": "EU",
        "line1": "Address",
        "line2": "",
        "postal_code": "12345",
        "state": "ST"
      },
      "email": "abc@gmail.com",
      "name": "First Last",
      "phone": "+12345",
      "verified_address": null,
      "verified_email": null,
      "verified_name": null,
      "verified_phone": null
    },
    "redirect": {
      "failure_reason": null,
      "return_url": "https://domain.com/checkout/order-received/8090/?key=wc_order_abc6b9f9e1808&utm_nooverride=1&order_id=8090",
      "status": "not_required",
      "url": "https://hooks.stripe.com/redirect/authenticate/src_ABCi0dLexAc2QLzfxWVHx89R?client_secret=src_client_secret_CzhPp2Wry07P0vcI8Uh7XABC"
    },
    "statement_descriptor": null,
    "status": "chargeable",
    "three_d_secure": {
      "card": "src_ABCi0OLexAc2QLzfj396YvPZ",
      "customer": null,
      "authenticated": false
    },
    "type": "three_d_secure",
    "usage": "single_use"
  },
  "previous_attributes": null
}
```

Here we can see that the status is set to `chargeable` because the redirect is optional so we can charge the source right away as well. And the redirect.status is set to `not_required`, since it was optional to do the redirect.

The documentation covers a scenario where the status is chargeable here: https://stripe.com/docs/sources/three-d-secure#checking-if-verification-is-still-required
But it doesn't fully describe the scenario when it is optional.

In the Stripe code we will only proceed if the redirect.status is set to `pending`, which the documentation mentions is the most common status. See: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.1.7/includes/class-wc-gateway-stripe.php#L746

So the result is that even if it's optional to do the redirect we can't force it to continue and actually do the redirect. For some merchants, it can be important to allow these cards to use 3DS even it it's optional, because this can reduce fraud attempts.

**Comment by roykho** [comment]
Yeah so after our discussion, currently the implementation is to look for the redirect status of "pending". That is the only time we will actually redirect the customer. This is the recommended implementation by Stripe.

With that said, they're rolling out a new 3DS implementation and we may soon to adopt that.
