### ISSUE TITLE
Payment request button fails to process orders when additional checkout fields are required (i.e. "Create account password")

### ISSUE THREAD

**Issue by Mrmrprofessional** [woocommerce/woocommerce-gateway-stripe#692]
Payment request button fails to process orders when additional checkout fields are required (i.e. "Create account password")

#### What I expected

Payments go through and user is prompted to fill out additional required fields on checkout with payment request buttons.

#### What happened instead

Payments fail to go through and errors are shown to user stating additional fields are required with payment request buttons.

#### Steps to reproduce the issue

Require additional fields at checkout and use a payment request button.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Please provide more information. What version of WC and Stripe you're using. On what page are you pressing the Payment Request Button?

**Comment by Mrmrprofessional** [comment]
WC Version 3.2.6
Stripe Version 4.1.7 

The Payment Request Buttons only seem to be present on the product page and the shopping cart. The additional required fields are on the checkout page (i.e. "Create account password" and "Where did you hear about us"). Transaction fails in both locations

**Comment by roykho** [comment]
Payment Request is not meant to have any required fields on non checkout pages. It is meant to be a fast "express" checkout experience for the customer where they don't need to enter any information.
