### ISSUE TITLE
Payment Request buttons and Product Add-ons

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce-gateway-stripe#694]
#### Affected ticket(s)
https://wordpress.org/support/topic/chrome-payment-request-stripe-and-woocommerce-product-add-ons/

#### What I expected
When using a payment request button to purchase a product with a product add-on, the product add-on selections should be capture upon using the payment request button.

#### What happened instead
After making a product add-on selection, on first click of the Payment Request button the page will refresh to show the updated product price and information.
On the secondary press however, the order is placed with only the base product. The product add-on is excluded from the order.

This only happens when using the Payment Request button directly from the single product page. If you use the Payment Request button from the cart, it works normally.

#### Steps to reproduce the issue
- Set up a product with an optional Product Add-On
- Navigate to the product and add the optional product add-on
- Click the Payment Requests button

I tried this with Google Pay, but I imagine Apple Pay would have the same effect.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Hey @FreshPhil so this is actually a duplicate issue of https://github.com/woocommerce/woocommerce-gateway-stripe/issues/566 where we deemed it as an enhancement and we have posted it to the ideas board below.

http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/34518661-apple-pay-payment-request-to-support-custom-field
