### ISSUE TITLE
Can pay without selecting shipping method

### ISSUE THREAD

**Issue by yratof** [woocommerce/woocommerce-gateway-stripe#695]
Stripe doesn't listen to the checkout when using shipping methods that validate postcodes and return pickup locations.

Writing an invalid postcode brings an error with my shipping provider, but stripe allows the checkout to succeed.

Use Stripe with this plugin: https://wordpress.org/plugins/bring-fraktguiden-for-woocommerce/
Set postcode to 4848 to valid or 0000 for invalid, you can pay with stripe both methods.

Orders will come though without a collection point and without a method selected.

**Comment by roykho** [comment]
The plugin gets back whatever validation Stripe provides. In addition, WooCommerce core has some validation of the post code.
