### ISSUE TITLE
Missing filter for adding classes to :  wc-stripe-checkout-button 

### ISSUE THREAD

**Issue by Antoinebr** [woocommerce/woocommerce-gateway-stripe#696]
#### What I expected

Fin a hook to add my own classes 

#### What happened instead

No hooks 

#### Steps to reproduce the issue

Check : https://github.com/woocommerce/woocommerce-gateway-stripe/blob/3d0875fd029c262612399063bee7cb79cb974c0f/includes/class-wc-gateway-stripe.php#L587

**Comment by roykho** [comment]
We will not be adding classes to that button. You can target the class that is already there.
