### ISSUE TITLE
Wrong currency in admin UI if payout currency is not the same as order currency.

### ISSUE THREAD

**Issue by edvinbrobeck** [woocommerce/woocommerce-gateway-stripe#699]
#### What I expected

We have a multi language /currency setup (WPML / WCML) and our orders can be in either EUR, USD, or SEK. Our default currency in Stripe for payouts are in our local currrency SEK.

In one the latest updates admin labels were introduced showing the payout and fee amounts.
I would expect the currency symbol of the amounts to be correct.
#### What happened instead

These  values are converted to our local currency SEK, and the returned currency from the API `$response->balance_transaction->currency` is correct, but when rendering the fields it is wrong.

You can see the problem here:
https://imgfy.me/image/xek9

The original order value of €67.5 is converted by Stripe to 665.07(SEK) but shown in EUR.

#### Steps to reproduce the issue

1. Complete order in other currency than the defined payout currency in Stripe.
2. Visit order in Woocommerce admin

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by edvinbrobeck** [comment]
After further investigation this seems to be rather a problem with the plugin WPML applying a filter to `wc_price()` that does not respect the arguments.

**Comment by kkarpieszuk** [comment]
hi @edvinbrobeck , Konrad here from wpml compatibility team. Could you elaborate about those arguments? What is passed and not handled properly?

Also could you tell me when exactly this is fired so I will investigate it with xdebug

**Comment by kkarpieszuk** [comment]
hi @edvinbrobeck have you seen my previous comment? :)

**Comment by edvinbrobeck** [comment]
@kkarpieszuk Sorry for not responding. To illustrate the problem, i made the following changes to 
`woocommerce-gateway-stripe/includes/class-wc-gateway-stripe.php`

in the function `display_order_payout()` where it outputs the payout.
```

	public function display_order_payout( $order_id ) {
		if ( apply_filters( 'wc_stripe_hide_display_order_payout', false, $order_id ) ) {
			return;
		}

		$order = wc_get_order( $order_id );

		$net      = WC_Stripe_Helper::get_stripe_net( $order );
		$currency = WC_Stripe_Helper::get_stripe_currency( $order );

		if ( ! $net || ! $currency ) {
			return;
		}

		?>

		<tr>
			<td class="label stripe-payout">
				<?php echo wc_help_tip( __( 'This represents the net total that will be credited to your Stripe bank account. This may be in the currency that is set in your Stripe account.', 'woocommerce-gateway-stripe' ) ); // wpcs: xss ok. ?>
				<?php esc_html_e( 'Stripe Payout:', 'woocommerce-gateway-stripe' ); ?>
			</td>
			<td width="1%"></td>
			<td class="total">
				<!-- ADDED THIS LINE -->
				<?php echo $currency; ?> 
				<!-- END LINE -->

				<?php echo wc_price( $net, array( 'currency' => $currency ) ); // wpcs: xss ok. ?>
			</td>
		</tr>

		<?php
	}

```

See attached screendump for output result:
[Screen dump](https://pictshare.net/uxxzax.png)

Note that the string outputted first is "SEK" which is our "stripe" account currency, but the `wc_price()` gives me the Net value but with the EUR-character.

So the problem is that WPML is overriding the output in `wc_price()` to use the currency the order was placed in, whereas the stripe ouput value is in the currency selected in your stripe settings. I am not really sure if this is a bug in the WPML plugin, or the Stripe plugin - I guess you could argue for both.

Honestly, the more i think about it i believe the "proper" fix to this, would be if the WPML team would not override the currency when passed as an argument (as in the example above), but having some experience with working with that plugin for a long time i would say the chances of them fixing this anytime soon is slim to none.

**Comment by kkarpieszuk** [comment]
thank you! I will check if we can handle this

**Comment by kkarpieszuk** [comment]
Hi @edvinbrobeck sorry I am so late here but I missed this ticket

When you are platying with currencies, could you - before displaying them or assiging to variables to use later - pass it throught this filter?

https://wpml.org/wcml-hook/wcml_raw_price_amount/

this will update price to the one in current currency. 

If you find you need anything more, here is:
- our wcml hooks reference 
https://wpml.org/documentation/related-projects/woocommerce-multilingual/wcml-hooks-reference/
- our wpml hooks reference (but those I guess you won't need):
https://wpml.org/documentation/support/wpml-coding-api/wpml-hooks-reference/

**Comment by kkarpieszuk** [comment]
hi @edvinbrobeck did you have time to check my proposed solution?

**Comment by kkarpieszuk** [comment]
Hi @edvinbrobeck as we are getting more and more reports on this issue, I am back on this topic. 

I prepared a pull request with proposed changes, could you review and merge?
https://github.com/woocommerce/woocommerce-gateway-stripe/pull/2119

simply, you use `wc_price` function which at some point allows to filter the currency symbol. WCML is hooking in this filter, checks if this is order edit page and replaces it with the currency symbol defined for the order. We don't have a way to see it comes from Stripe plugin (it is just a call for `wc_price`) so we can't stop filtering this piece of html output.

I prepared a wrapper for call `wc_price` in your plugin which removes our filter and adds it back.

**Comment by kkarpieszuk** [comment]
Hi @edvinbrobeck did you have opportunity to check my comment above? :)
