### ISSUE TITLE
Will Support for ApplePay be added? 

### ISSUE THREAD

**Issue by keninbassart** [woocommerce/woocommerce-gateway-stripe#70]
Stripe supports ApplePay for the Web via stripe.js :https://stripe.com/docs/apple-pay

Support for Apple Pay is heavily requested on Ideas board as well: http://ideas.woothemes.com/forums/133476-woocommerce/suggestions/6430486-add-apple-pay-support-to-woocommerce

Is this planned for a future release?

**Comment by roykho** [comment]
Yes it is already planned although we didn't add it here yet. No ETA on the release though.

**Comment by keninbassart** [comment]
Thanks for the speedy response :)

**Comment by laralfield** [comment]
Adding my hope this is included in a new release soon. 🙂 With the release of the new MacBook Pros, payment on any laptop with fingerprint will be really easy, so this integration will open up a lot of potential new revenue for WooCommerce owners. I see It's added already added to 3.1.0 💯.  

Thank you very much for all of the excellent work your team contributes to maintain this plugin. Really looking forward to 3.1.0.

**Comment by roykho** [comment]
Added in this commit https://github.com/woocommerce/woocommerce-gateway-stripe/commit/f6035f7556d16986c5b0d27a2bf4fe61d4d62b67
