### ISSUE TITLE
Chrome autofill causes CVC errors

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce-gateway-stripe#705]
#### Affected ticket(s)

https://woothemes.zendesk.com/agent/tickets/1313777

#### What I expected

Headed to checkout via Chrome I should be able to use Autofill without issues.

#### What happened instead

When heading to checkout with just Stripe active it causes CVC/CVV errors when using with Chrome's autofill feature. I'm then not exactly sure how to solve it from there, or if there is a particular conflict with a Stripe feature and Chrome here.

#### Steps to reproduce the issue

Setup a card in Chrome to use for autopay, then with Stripe active go to checkout and use autofill. It doesn't fill in the CVC field but once you add the CVC and attempt to pay there will be a CVC error.

If you then again manually fill out the entire card form checkout will work, sans any autofill help.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
So I have tested this and I did not see any issues.

![](http://cld.wthms.co/oQlBr6+)

**Comment by roykho** [comment]
Please re-open if issue persists.
