### ISSUE TITLE
Payment Request Button Does Not Show Up Anymore?

### ISSUE THREAD

**Issue by Glen92** [woocommerce/woocommerce-gateway-stripe#707]
#### Affected ticket(s)
Connected Stripe Succesfull And I Have Seen The Payment Request Button But Somehow It's Gone Now. I Contacted Stripe And They Told Me I Need To Reach Out To Woocommerce So Here I Am. The Only Thing I Changed Was The Button Type And After That I Think It Is Gone So I Changed It Back But It Doesnt Show Up Anymore?

#### What I expected
That The Button Type Changed

#### What happened instead
Button gone

#### Steps to reproduce the issue
Setting Screenshot Maybe I Miss Something
[https://prnt.sc/keh5tv](url)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Hi,

Please post support questions here https://wordpress.org/plugins/woocommerce-gateway-stripe/
