### ISSUE TITLE
[BUG] Breaker Credit Card fields "collapsed" and not able to fill

### ISSUE THREAD

**Issue by exocode** [woocommerce/woocommerce-gateway-stripe#709]
#### What I expected

In order to pay with credit cards I wanna fill out the credit card form

#### What happened instead

The credit card fields are collapsed and - even I make them larger by cheating css - are not able to fill them out

Checkout:

![bildschirmfoto 2018-08-11 um 10 59 56](https://user-images.githubusercontent.com/1597621/43990086-b67dd8e2-9d56-11e8-9e13-9d2e4ff1850a.png)

After resizing CSS, still not able to fill the form:

![bildschirmfoto 2018-08-11 um 11 08 21](https://user-images.githubusercontent.com/1597621/43990102-03e07900-9d57-11e8-89a2-5069b913898b.png)

You can re-check here:

https://hempalaya.com/kasse/

#### Steps to reproduce the issue

- Wordpress Version 4.9.8
- WooCommerce Version 3.4.3
- WooCommerce Stripe-Gateway Version 4.1.8

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by lkraav** [comment]
Inspect your JS Console first. This is usually a side-effect of script blockers.

**Comment by exocode** [comment]
SOLVED:

By deactivating the "**Yoast SEO: Local for WooCommerce"** plugin
