### ISSUE TITLE
Stripe Checkout broken after extension update

### ISSUE THREAD

**Issue by douglsmith** [woocommerce/woocommerce-gateway-stripe#71]
#### What I expected

With Stripe Checkout enabled, click the _Proceed to payment_ button and the Stripe payment form appears as an overlay.

#### What happened instead

Click the _Proceed to payment_ button and the page scrolls to the top then shows the error:

> Please enter your card details to make a payment. Developers: Please make sure that you are including jQuery and there are no JavaScript errors on the page.

I'm also seeing a javascript error in Safari's web tools:

> ReferenceError: Can't find variable: $required_inputs

<img width="949" alt="stripe-checkout-error" src="https://cloud.githubusercontent.com/assets/2446310/18930523/fc713ade-858d-11e6-86c2-02c32cdeb7a8.png">

#### Steps to reproduce the issue

I disabled all plugins except WooCommerce and Stripe 3.0.4 then went through the checkout process. This was also happening in a prior version but I'm not sure if it was 3.0.2 or 3.0.3. The problem was fixed when I rolled back to version 3.0.0.

There's a post with a possible fix over in the WordPress support forums that looks like it could be this same issue. https://wordpress.org/support/topic/v3-0-4-breaks-checkout-button-developers-xxx/

**Comment by roykho** [comment]
Please checkout master. And re-test.

**Comment by douglsmith** [comment]
Yes, I can verify that fixed it.

I noticed the fixed version over at the WordPress repository doesn't have a new version number. I would recommend bumping the version so everyone who got 3.0.4 will see the update with the fix in their dashboard. I didn't even realize we had a problem until customers started complaining.

Thanks for the quick turnaround!

**Comment by roykho** [comment]
Yup 3.0.5 is out.

**Comment by douglsmith** [comment]
It's a cross posting kind of day. I see you already bumped the version. :-)

**Comment by Bcheets** [comment]
Hey, Im getting the same error with the latest version of the Woo Stripe Plugin, can you tell me what "checkout master and re-test" means exactly, Im not coder just a front end guy so its a bit over my head :)

**Comment by heyrm** [comment]
Also having the same bug now...

**Comment by circler** [comment]
Getting this same error with the latest version of the Stripe plugin and Safari. Works fine with Chrome.

**Comment by tomodian** [comment]
Same here, the error message `ReferenceError: Can't find variable: Stripe` only appears on Safari, works well in Chrome.
