### ISSUE TITLE
Order: Checkout hangs after submit, does not reach Thank You page. transaction in stripe does get processed.

### ISSUE THREAD

**Issue by lqdforce** [woocommerce/woocommerce-gateway-stripe#710]
Checkout hangs with Stripe plugin enabled. tried TEST KEYS and LIVE KEYS, tried playing with the settings and still no go. this only started a couple of days ago.
Perhaps this is a CURL/SSL error? Maybe Stripe API has been changed? this makes no sense.

No logged PHP errors, or backend nginx/apache.
can provide Stripe log in private, but it seems ok. order does process in stripe and marks as Completed in woocommerce.

this is the only reference of this error i am seeing –
SyntaxError: Unexpected token < in JSON at position 0

Note: when enabling WP_DEBUG, checkout does not hang loading after submitting the order. it does not reach thank you page or reloads the page however, just throws the error above for the client to see, in the checkout form.

Also, tried enabling the Stripe modal checkout.
it does not result in a page hang issue with js error, but instead redirects client to this url with a blank page:
https://emample.com/wc-api/WC_Stripe_Subs_Compat/

Please help me find out what is causing this. attached client-side error from console.

`checkout.min.js:1 Uncaught TypeError: Cannot read property 'reload' of null
    at Object.success (checkout.min.js:1)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at y (jquery.js:4)
    at XMLHttpRequest.c (jquery.js:4)
success @ checkout.min.js:1
i @ jquery.js:2
fireWith @ jquery.js:2
y @ jquery.js:4
c @ jquery.js:4
XMLHttpRequest.send (async)
send @ jquery.js:4
ajax @ jquery.js:4
submit @ checkout.min.js:1
dispatch @ jquery.js:3
r.handle @ jquery.js:3
trigger @ jquery.js:3
a.event.trigger @ jquery-migrate.min.js:2
(anonymous) @ jquery.js:3
each @ jquery.js:2
each @ jquery.js:2
trigger @ jquery.js:3
n.fn.(anonymous function) @ jquery.js:4
processStripeResponse @ stripe.min.js:1
sourceResponse @ stripe.min.js:1
Promise.then (async)
createSource @ stripe.min.js:1
onSubmit @ stripe.min.js:1
dispatch @ jquery.js:3
r.handle @ jquery.js:3
trigger @ jquery.js:3
a.event.trigger @ jquery-migrate.min.js:2
triggerHandler @ jquery.js:3
submit @ checkout.min.js:1
dispatch @ jquery.js:3
r.handle @ jquery.js:3`

**Comment by roykho** [comment]
Please post support questions here https://wordpress.org/plugins/woocommerce-gateway-stripe/
