### ISSUE TITLE
Apple pay

### ISSUE THREAD

**Issue by Sumit-Suman17** [woocommerce/woocommerce-gateway-stripe#712]
#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by Sumit-Suman17** [comment]
The payment request button is not visible in cart,  I did all the setup as required.
Need help with this.

**Comment by dougaitken** [comment]
Hi @Sumit-Suman17 please open a ticket to get support with Apple Pay & the Stripe extension - https://woocommerce.com/contact-us/
