### ISSUE TITLE
Stripe Custom fields (in WooCommerce orders) abruptly stopped being filled

### ISSUE THREAD

**Issue by kristofferR** [woocommerce/woocommerce-gateway-stripe#716]
#### What I expected

The custom WordPress fields "Net Revenue From Stripe" and "Stripe Fee" should be filled out automatically with each order.

#### What happened instead

In the orders of the last couple of weeks the custom fields are not being filled out. The values (Stripe Fee and Stripe Payout) are displayed correctly in the box above (in the order details), indicating that the missing custom fields is an issue with this plugin.

**Comment by roykho** [comment]
This was changed awhile ago since either version 4.0 or 4.1 I believe. We're no longer doing it that way.

**Comment by kristofferR** [comment]
What's the suggested way to export the values now that the old way has been broken? I need to export the Stripe values for accounting

**Comment by roykho** [comment]
Nothing's changed really other than the naming convention. It is still in the same place in the database as before.

stripe_fee => _stripe_fee
stripe_net => _stripe_net

And _stripe_currency was added later.

**Comment by kristofferR** [comment]
Thanks! Adding the meta keys above manually to "Advanced Order Export for WooCommerce" worked! 😁

However, why don't the new meta keys you mentioned show up automatically in the auto generated list, among the other Stripe meta keys (_stripe_card_id, _stripe_charge_captured, _stripe_charge_id, _stripe_customer_id)? 

I've confirmed that the order export plugin doesn't have any manual mention of the meta keys it displays, so it seems that the new meta keys probably could/should be declared somewhere so they show up automatically among the other Stripe meta keys :)

**Comment by kristofferR** [comment]
That doesn't makes sense as an explanation for this though, as the other _stripe_ meta keys I mentioned above and a ton of other underscore meta keys are visible. Anyway, it's not the most important thing, but it would be cool to make it as visible as other hidden meta keys (_order_, _shipping_, _billing_), so it wouldn't be that hard to add as it turned out to be here.

**Comment by Jackevangelides** [comment]
> Thanks! Adding the meta keys above manually to "Advanced Order Export for WooCommerce" worked! 😁
> 
> However, why don't the new meta keys you mentioned show up automatically in the auto generated list of meta keys, among the other Stripe meta keys (_stripe_card_id, _stripe_charge_captured, _stripe_charge_id, _stripe_customer_id)?
> 
> I've confirmed that the order export plugin doesn't have any manual mention of the meta keys it displays, so it seems that the new meta keys probably could/should be declared somewhere so they show up automatically among the other Stripe meta keys :)

Is this still working, I tried adding _stripe_fee to the "Advanced Order Export for WooCommerce" plugin and set the field format to "number" but my order exports just show a blank column for Stripe Fees.
