### ISSUE TITLE
Add a filter to change Payment Request Buttons locale

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-stripe#719]
#### Affected ticket(s)
1346305-zen

#### What I expected
To use Apple Pay in Hong Kong. Official languages in this country are Chinese (Traditional) and English, and one of these should be used for the Apple Pay button.

#### What happened instead
Even though the site locale is Chinese (Traditional), the Apple Pay button loads in Chinese (Simplified) instead. This is because Stripe API only accepts a two-character locale code, and `zh` stands there for Chinese (Simplified):

https://stripe.com/docs/stripe-js/reference#stripe-elements

This language is not used in Hong Kong, and so the button can be really confusing to the customers.

There are two ways how we can handle this problem:
1. Force the Apple Pay button to load in English when site locale is Chinese (Traditional), or
2. Add a filter to modify the payment button locale using custom code.

The second option sounds much better to me, as it doesn't come with any unexpected side effects.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Hi @madeincosmos sorry so I am not sure how this can be done? Stripe only supports ZH, how can we pass it something different? And also, we already have filters to change the locale, its in the documentation.

**Comment by madeincosmos** [comment]
Sorry, I should have made it clearer that the user wants to switch the button to English instead - currently the only way they can do that is by switching the whole site to English, which they don't want.

Also, I checked the `wc_stripe_checkout_locale` filter, but it seems to only affect the Stripe Checkout popup. For Payment Request Buttons, we're passing the first two characters of WordPress native `get_locale`, unfiltered:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/payment-methods/class-wc-stripe-payment-request.php#L521

Do you think we can use the same `wc_stripe_checkout_locale` filter in both cases, or should they rather be kept separate?

**Comment by roykho** [comment]
Ah that makes more sense now.

I think normally it would be ok to use the same filter however in this case because we specifically named it "wc_stripe_checkout_locale", it pertains to the modal popup. So we would probably need a different name perhaps "wc_stripe_payment_request_locale".
