### ISSUE TITLE
Errors after Woo update

### ISSUE THREAD

**Issue by Tigzy** [woocommerce/woocommerce-gateway-stripe#720]
Hey, after updating to latest Woocommerce, I have many errors. 

[27-Aug-2018 11:44:21 UTC] PHP Notice:  Undefined index: product_id in /var/www/vhosts/adlice.com/shop.adlice.com/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-payment-request.php on line 797
[27-Aug-2018 11:44:21 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_type() on boolean in /var/www/vhosts/adlice.com/shop.adlice.com/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-payment-request.php:802
Stack trace:
#0 /var/www/vhosts/website/wp-includes/class-wp-hook.php(286): WC_Stripe_Payment_Request->ajax_get_selected_product_data('')
#1 /var/www/vhosts/website/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /var/www/vhosts/website/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/vhosts/website/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(78): do_action('wc_ajax_wc_stri...')
#4 /var/www/vhosts/website/wp-includes/class-wp-hook.php(286): WC_AJAX::do_wc_ajax('')
#5 /var/www/vhosts/website/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(false, Array)
#6 /var/www/vhosts/website/wp-includes/plugi in /var/www/vhosts/website/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-payment-request.php on line 802

I haven't got any successful order since then, I'm reverting to a backup.

**Comment by Tigzy** [comment]
Woo: 3.4.4
Stripe: 4.1.8

**Comment by roykho** [comment]
No issues here for me. The only change in that file is here https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/payment-methods/class-wc-stripe-payment-request.php#L521

Have you tried clearing cache?

**Comment by Tigzy** [comment]
I just saw there's a 4.1.9 pushed today, and applied the script. 
I'm giving it a chance before reverting. 
@roykho Not a cache issue if you look at the given log

**Comment by roykho** [comment]
Yeah there is no issues that I can see with WC 3.4.4 and Stripe 4.1.8 or latest 4.1.9. I will close this issue for now however you can post back if you find something else.
