### ISSUE TITLE
Setting the Stripe Customer ID

### ISSUE THREAD

**Issue by bruun** [woocommerce/woocommerce-gateway-stripe#721]
Forgive me if this makes no sense at all, I'm new to both Wordpress and WooCommerce.

We have an existing service on another platform where each user has a Stripe customer. We are now experimenting with a new service under the same brand, and are testing WooCommerce as the platform. Users enter WooCommerce through the existing service with an access token, allowing us to associate the WooCommerce session with the user on the existing service. The goal is to use as much information as possible from the existing service (name, shipping address, payment information) to make the checkout experience as smooth as possible in WooCommerce. 

Specifically, we want to use the Stripe Customer from the existing service.

As far as I can tell, there is no documented way of doing that using this plugin. Browsing the code it seems the customer id is stored in a post meta as `_stripe_customer_id`. I assume overriding this is considered a bad workaround? Is there a proper way of achieving what we want, or is it outside the current scope of this plugin?

**Comment by roykho** [comment]
Hello, so this is not the place to get support. Perhaps you want to post your question here https://wordpress.org/plugins/woocommerce-gateway-stripe/
