### ISSUE TITLE
Subscriptions: "Change Payment" Updated Card Not Used For Renewals

### ISSUE THREAD

**Issue by FitMo90** [woocommerce/woocommerce-gateway-stripe#722]
Same Problem like here:
https://github.com/woocommerce/woocommerce-gateway-stripe/issues/281

**Scenario**
We have orders, where the Status is pending (manual renewal) or failed. Failed because the Creditcard is not correct or expired. So the customer has tu add a new payment method, a new card, and we want to charge these orders from the new card.

**Steps to Reproduce**

- View an active subscription within My Account 
- Click on the "Change Payment" button on the view-subscription page.
- Provide the a new credit card via stripe on the "choose a new payment method" page.
- Press "change payment method"

**Expected Result**

- New credit card is added to the stripe customer record
- Stripe Card ID metadata within the parent subscription is updated to the new Stripe card ID
- "Next Payment" displayed in my account should reflect the new card type and last4
- Future renewals will be charged against the new credit card.

**Actual Result**

- New credit card is correctly added to the stripe customer record
- The metadata in the parent WooCommerce subscription is not updated with the new Stripe card ID
- "Next Payment" displayed in my account continues to reflect the previous card
- If we click Retry Renewal payment for failed or pending orders - payment will fail
- Future renewals continue to be attempted against the previous credit card
- When attempting to change payment again, the new card now appears within the list of potential cards. However, selecting that card still does not update the metadata or change future renewals.

**Comment by roykho** [comment]
I've tested this several times with new card and with existing cards, both times I am able to update the card for future renewals. What version of Stripe and Subscriptions are you using?

**Comment by roykho** [comment]
Can you please give me the step by step on how to reproduce this issue?

**Comment by FitMo90** [comment]
1. scenario:
- active subscription. Payment for renewal-order failed because of a problem with the creditcard. For example declined.
- We let the customer know about it. 
- Customer will add a new payment source (new Creditcard) in his account
- after it we "retry renewal payment" for the failed order in order actions on the admin-order-detailpage.
- Payment fails again. The process tries to renewal the payment again with the old creditcard/source. Not the new one

2. Scenario:
- Customer added a new payment source
- We create in the subscription-Detail-Page a manuell renewal
- payment failed, because it tries to renewal the payment again with the old creditcard/source. Not the new one

**Comment by roykho** [comment]
> Customer will add a new payment source (new Creditcard) in his account

What are the steps here for them to add the card?

**Comment by roykho** [comment]
Closing this for now as I cannot replicate and no reply from author.
