### ISSUE TITLE
Hong Kong shipping and billing addresses are not accepted for Apple Pay

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce-gateway-stripe#723]
#### Affected ticket(s)

1377463-zen

#### What I expected

A customer can use Hong Kong billing and shipping addresses to pay with Apple Pay.

#### What happened instead

Error message: 

```
Billing Region is a required field.
Shipping Region is a required field.
```

#### Steps to reproduce the issue

- On my test site I activated Stripe and Apple Pay button and filled in Hong Kong billing and Shipping addresses:

![http://cld.wthms.co/kqtoYS](http://cld.wthms.co/kqtoYS+) 
Full Size: http://cld.wthms.co/kqtoYS

Received this error:

![http://cld.wthms.co/2oE5Pg](http://cld.wthms.co/2oE5Pg+) 
Full Size: http://cld.wthms.co/2oE5Pg

- Tried with US address:

![http://cld.wthms.co/dbAl5p](http://cld.wthms.co/dbAl5p+) 
Full Size: http://cld.wthms.co/dbAl5p

Test payment came through:

![http://cld.wthms.co/0BHdN9](http://cld.wthms.co/0BHdN9+) 
Full Size: http://cld.wthms.co/0BHdN9

The difference is that when you're trying to enter HK address, there is no ZIP code field, due to HK not using them - https://worldpostalcode.com/hong-kong/

Setting priority to High because there should be a lot of customers who are trying to Apple Pay from Hong Kong.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Close in favor of #568

**Comment by roykho** [comment]
@harishankerr - :wave: yeah its the same type of issue.
