### ISSUE TITLE
Getting JS error on missing #stripe-iban-element

### ISSUE THREAD

**Issue by therealgilles** [woocommerce/woocommerce-gateway-stripe#724]
I am getting this new error recently on my Woocommerce site:

```
Uncaught Error: The selector you specified (#stripe-iban-element) applies to no DOM elements that are currently on the page.
Make sure the element exists on the page before calling mount().
```

I do not use IBAN on my site, so I am a bit puzzled. Wondering if anyone else is seeing this too. I worked around the issue by adding a div with id stripe-iban-element to the checkout page and set its display to none.

**Comment by roykho** [comment]
Download the plugin again and see if it fixes your issue.

**Comment by therealgilles** [comment]
@roykho: why do you think that would solve the issue?

**Comment by therealgilles** [comment]
I have not tried. I do not see why reinstalling a plugin would solve anything.

**Comment by matoledo** [comment]
I got the same error, tried re-installing and it’s still appearing.
