### ISSUE TITLE
apply_filters missing on wp_localize_script 

### ISSUE THREAD

**Issue by 11digitlabs** [woocommerce/woocommerce-gateway-stripe#725]
Hey there @roykho   ! Thanks for the excellent work on this plugin!

We would like to have a different set of keys, based on some conditions on our site.

There are two points that I need to change them, and only one of them has an `apply_filters`

- https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L519
	- There is an `apply_filters`
- https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/payment-methods/class-wc-stripe-payment-request.php#L487 
	- No `apply_filters`

I'd be happy to submit a PR, but first wanted to validate it with you before I do.

Thanks
Panos

**Comment by roykho** [comment]
Hi Panos,

Sure go for it! Just mind coding standards and naming conventions.

**Comment by 11digitlabs** [comment]
Will do :) Thanks!

**Comment by 11digitlabs** [comment]
Morning @roykho . Just submitted my PR https://github.com/woocommerce/woocommerce-gateway-stripe/pull/729

Feel free to pull. Do you have any ideas when this will be made to the WordPress plugin repo? No rush :)
