### ISSUE TITLE
Missing billing_country causes Issue with Secondary Checkout

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-gateway-stripe#730]
#### Affected ticket(s)

#1406062-zd-woothemes

#### What I expected

When setting up a secondary checkout page, the Stripe "Card number" field works properly on both the regular and secondary checkout, even when the `billing_country` field is disabled.

#### What happened instead

With the `billing_country` field disabled, the Stripe "Card number" field works fine on the regular checkout page (set under `WooCommerce > Settings > Advanced > Checkout page`), but on the one with the `[woocommerce_checkout]` shortcode, the field does not display properly when the `billing_country` field is disabled.

**Screencast with Country field disabled:**

![http://cld.wthms.co/hwdydQ](http://cld.wthms.co/hwdydQ+)
Screencast link: http://cld.wthms.co/hwdydQ

**Screencast with Country field enabled:**

![http://cld.wthms.co/RqZBQ1](http://cld.wthms.co/RqZBQ1+)
Screencast link: http://cld.wthms.co/RqZBQ1

#### Steps to reproduce the issue

1. Setup the checkout page under `WooCommerce > Settings > Advanced > Checkout page`.
2. Setup another checkout page with the `[woocommerce_checkout]` shortcode.
3. Setup Stripe in any mode (live/test).
4. Remove the `billing_country` field.
5. "Card number" field on secondary checkout page with shortcode does not work.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
This is fixed in WC core https://github.com/woocommerce/woocommerce/pull/21328
