### ISSUE TITLE
source.cancelled is unable to find a matching order to update the status

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-gateway-stripe#734]
In this scenario we are using the payment option Przelewy24. According to the documentation if the source is in a pending state it will be cancelled after 1 hour, see: https://stripe.com/docs/sources/p24#sources-expiration

However when we receive the source.cancelled request from Stripe we see the following message in the log:

```
2018-09-20T08:22:37+00:00 DEBUG 
====Stripe Version: 4.1.10====
====Start Log====
Could not find order via charge ID: src_AAABBBCCCDDD
====End Log====
```

This is from the following function https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.1.10/includes/class-wc-stripe-webhook-handler.php#L404-L421

If I understand everything correctly it should be looking for the source ID instead of the charge ID, because at this point the charge hasn't gone through yet.

Here is a copy of the webhook which is sent by Stripe (partly redacted):

```
ID: evt_AAABBBCCC 
Date: 2018/09/20 09:22:35 
Type: source.canceled 
Source: Automatic 

{ 
	"object": { 
		"id": "src_AAABBBCCC",
		"object": "source", 
		"amount": 6900, 
		"client_secret": "src_client_secret_AAABBBCCC", 
		"created": 1537428141, 
		"currency": "pln", 
		"flow": "redirect", 
		"livemode": true, 
		"metadata": {}, 
		"owner": { 
			...
		}, 
		"p24": { 
			"reference": null 
		}, 
		"redirect": { 
			"failure_reason": null, 
			"return_url": "https://domain.shop/checkout/order-received/1111/?key=wc_order_abc&utm_nooverride=1&order_id=1111", 
			"status": "failed", 
			"url": "https://hooks.stripe.com/redirect/authenticate/src_AAABBBCCC?client_secret=src_client_secret_AAABBBCCC" 
		}, 
		"statement_descriptor": null, 
		"status": "canceled", 
		"type": "p24", 
		"usage": "single_use" 
	}, 
	"previous_attributes": null 
}
```

Also another part that isn't clear is what the order status should be, see: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4.1.10/includes/class-wc-stripe-webhook-handler.php#L414-L416
Is that handled differently for other payment types? With Przelewy24 the order status is `pending` when the source.cancelled webhook is received. Which would mean it would skip the status change to cancelled.

Affected ticket: 1418253-zen

**Comment by roykho** [comment]
Do you have steps to replicate this?

**Comment by mikkamp** [comment]
The closest I've gotten to replicate this is to setup the Payment method Przelewy24 in sandbox mode.
Then when the payment is handled on the test site it redirects to a Stripe test page where we can either Authorize or Fail the test payment. To get the source.cancelled we should do neither of those and wait for the timeout to be reached. According to the documentation that would be after an hour. But I haven't waited an hour to see if I get the correct webhook sent (or checked if it's even sent in sandbox mode).
