### ISSUE TITLE
Hard to test on a *.test staging system: "Error: Live Stripe.js integrations must use HTTPS"

### ISSUE THREAD

**Issue by gerdneuman** [woocommerce/woocommerce-gateway-stripe#735]
There's an uncaught JS Error when running the plugin on a http://*.test (test domains are always not routet, always internal only) staging server:

```
Error: Live Stripe.js integrations must use HTTPS. For more information: https://stripe.com/docs/stripe-js/elements/quickstart#http-requirements
```

![image](https://user-images.githubusercontent.com/12525563/45916383-6200e400-be65-11e8-9357-699f1aeab1e9.png)

This causes all subsequent JS to be not executed. So for instance, I noticed that some of our child theme javascript was not working on the staging server but worked on the live server. This is due to this JS Error, which seems to be not caught.

Not sure, maybe the situation could be improved by 
a) catching the Error so not all subsequent JS is broken
b) when a staging server is detected (like WooCommerce Subscriptions does already successfully) then use test keys or environment so this error does not happen at all

**Comment by lkraav** [comment]
I for one create self-signed certs for all my internal domains as well. There is pretty much 0 reason to do anything over `http`.

Is there a need to load Live mode stripe.js on staging? I understand the need to test, but in that case, switch to HTTPS on local sites as well.

**Comment by gerdneuman** [comment]
> I for one create self-signed certs for all my internal domains as well.

hmm, ok, propably I should just do this then... You are right.

I still keep this open, because I think it would be better to catch the Error. Anyway, @roykho please just close if there's nothing that can be done here.

**Comment by lkraav** [comment]
> I still keep this open, because I think it would be better to catch the Error.

Wouldn't this create a real security risk?

**Comment by roykho** [comment]
Added a `catch` so at least it won't break the rest of the JS that comes after but yet still will console log the issue for easier debugging.

**Comment by gerdneuman** [comment]
Thank you, I am closing. Reopen if this is inappropriate!
