### ISSUE TITLE
Partial refund on externally captured payments refunds the whole amount

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce-gateway-stripe#738]
#### Affected ticket(s)

1433423-zen

#### What I expected

To partially refund an order placed through Stripe with pre-authorization. The order was pre-authorized in WooCommerce and captured directly in Stripe dashboard.

#### What happened instead

Trying to partially refund the order in WooCommerce at a later time resulted in refunding the whole amount instead of the amount entered in WooCommerce.

#### Steps to reproduce the issue

1. In Stripe settings, set payment action to Authorize,
2. Purchase a product using Stripe and observe the order is On-Hold,
3. Open the payment in Stripe dashboard and manually capture the payment there:

![Screenshot](http://cld.wthms.co/uIeFOs+)
Screenshot: http://cld.wthms.co/uIeFOs

4. Go back to WooCommerce and change order status to Completed (it will change to 'Failed' with the error message `Unable to capture charge! Charge ch_1DDY1FEXfSIO2h6WAlqzI6PQ has already been captured. Order status changed from Completed to Failed.`).
5. Change order status to Completed once again.
6. Issue a partial refund in WooCommerce and observe the order is partially refunded there:

![Screenshot](http://cld.wthms.co/jmQUqk+)
Screenshot: http://cld.wthms.co/jmQUqk

7. Open the same payment in Stripe and observe it's fully refunded:
 
![Screenshot](http://cld.wthms.co/4rDRD4+)
Screenshot: http://cld.wthms.co/4rDRD4

I know capturing the payment in Stripe instead of WP Admin is not the default user flow. However in cases like this we should at least prevent the user from refunding through Stripe in WP Admin, instead of refunding the full amount.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Thanks for reporting @madeincosmos - do you want to give this branch a test? https://github.com/woocommerce/woocommerce-gateway-stripe/tree/fix/issue-738
