### ISSUE TITLE
Users can check out via Buy Now button with no option to accept Terms and Conditions

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce-gateway-stripe#741]
#### Affected ticket(s)

1452231-zen

#### What I expected

Users should accept Terms and Conditions when paying for orders via Stripe's Buy Now buttons. 

#### What happened instead

Users can place orders via Buy Now and there is no checkbox to accept Terms and Conditions

#### Steps to reproduce the issue

1) Activate payment buttons for your Stripe gateway.
2) Try to purchase a product with Buy Now button from product's or cart pages, you won't see an option to accept Terms and Conditions:

![http://cld.wthms.co/zuDISO](http://cld.wthms.co/zuDISO+) 
Full Size: http://cld.wthms.co/zuDISO

Is there any logic behind that? 
The user needs customers to check this box with any payment method they choose.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
So when using Payment Request, it's an express type checkout so that box is preselected for them. If that is a liability for them because it was not explicitly checked by user, then they just have to stop using Payment Request..
