### ISSUE TITLE
Stripe Fee and Net Revenue Missing from JSON Metadata

### ISSUE THREAD

**Issue by Shotster** [woocommerce/woocommerce-gateway-stripe#746]
I've been logging WC transactions since the beginning of the year by fetching the order detail using the WC REST API. As of a couple weeks ago (sometime between 9/26/2018 and 9/29/2018), the **Stripe Fee** and **Net Revenue From Stripe** metadata fields disappeared. I have confirmed that the data are no longer present in the JSON payload. Those values **do** still appear in the order detail of the admin dashboard, however.

Was this API change intentional? Am I missing something? Any info or insight would be appreciated!

-Steve

**Comment by roykho** [comment]
We don't control the payload that comes from Stripe. Have you tried contacting them about it?

**Comment by Shotster** [comment]
Thanks for the prompt response, @roykho, but there might be a misunderstanding. I'm referring to a **WooCommerce payload** - NOT a Stripe payload.

As I said, I'm using the WC REST API, but I assumed the Stripe plugin was adding the metadata to the order detail. Is it not?

**Comment by roykho** [comment]
The last release was 2018-09-17 so it sounds like something else is causing this for you?

**Comment by Shotster** [comment]
Not necessarily. Turns out I updated to the latest version on 9/28/2018, so I still suspect something changed in the Stripe plugin. Guess I'll have to dig.

I'll report back here if I learn anything.

**Comment by roykho** [comment]
If you previously was on a version prior to 4.1.0, then you may see this issue as we changed the meta names for that release as seen here https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/changelog.txt#L83

But that was 6+ months ago.

**Comment by Shotster** [comment]
Indeed!  I was just about to post back here. That's exactly what I have determined. Easy fix, but had me stumped for a bit. 🙂
