### ISSUE TITLE
Placehold "MONTH YEAR" visible in CSS notice

### ISSUE THREAD

**Issue by c-shultz** [woocommerce/woocommerce-gateway-stripe#747]
It looks like there's some placeholder text that needs to be filled out:
<img width="2371" alt="image" src="https://user-images.githubusercontent.com/6209518/47096231-960cc200-d1e3-11e8-9152-af2cbbe39501.png">

/cc @roykho 
-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Sorry I pushed up changes already.
