### ISSUE TITLE
Miniscule typo in admin alert about 2019 changes

### ISSUE THREAD

**Issue by dsmithweb** [woocommerce/woocommerce-gateway-stripe#748]
At woocommerce-gateway-stripe/includes/admin/class-wc-stripe-admin-notices.php line 130, 

"Action required: In January 2019 we will be introducing changes that could effect how Stripe looks in your checkout."

should be 

"Action required: In January 2019 we will be introducing changes that could **affect** how Stripe looks in your checkout."

**Comment by roykho** [comment]
Fixed in master.
