### ISSUE TITLE
Blank screen or "Catchable fatal error" when marking order as complete

### ISSUE THREAD

**Issue by zzbeck** [woocommerce/woocommerce-gateway-stripe#749]
When marking an order as "Complete" in WooCommerce, I get a blank screen.
When marking multiple Stripe orders and other gateways, and tries to mark them as complete, I get a "Catchable fatal error".

Happens after 4.1.11 update.

**Comment by roykho** [comment]
Can you please provide the PHP error log on this error?

**Comment by roykho** [comment]
Ok I think I see the issue. This only happens if you're using capture payment first correct?

**Comment by zzbeck** [comment]
I only capture the payment when I mark the order as complete or processing. Have attached a screenshot of my settings.
<img width="782" alt="skaermbillede 2018-10-19 kl 15 53 52" src="https://user-images.githubusercontent.com/35366575/47222529-4bdc3a00-d3b7-11e8-9a3d-6939749a2b15.png">

**Comment by roykho** [comment]
I see thanks. This is fixed.
