### ISSUE TITLE
Visa / Mastercard / Amex Checkout

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce-gateway-stripe#750]
Do you have any plan for Visa / Mastercard / Amex Checkout? 

<img width="749" alt="screen shot 2018-10-24 at 19 58 25" src="https://user-images.githubusercontent.com/2909982/47431995-5b002500-d7c7-11e8-997e-993b7884ba7f.png">

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by pmaiorana** [comment]
@kevin25 We don't have anything planned for these features at the moment. 

We're now tracking enhancements on the WooCommerce Ideas board, so I'm going to close this issue out—but please do add your votes to these ideas for tracking:

- [Visa](http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/17671372-add-one-click-checkout-with-services-such-as-visa)
- [AmEx](http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/9414555-add-amex-express-checkout-to-stripe)
- [Masterpass](http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/35835505-add-masterpass-payment-method)

Thanks,
Paul
