### ISSUE TITLE
Sofort logo update

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce-gateway-stripe#751]
There appears to be a new logo for Sofort which is apart of Klarna Group. Here is the official documentation on this. https://developer.klarna.com/en/gb/kco-v3/sofort-design-guidelines/how-to-display-sofort/

This raises the question if we change the logo to "Klarna", does that mean we also need to change the payment method name from SOFORT to Klarna? And subsequently all occurrences of it?

cc @pmaiorana

**Comment by pmaiorana** [comment]
Good questions @roykho—I'm not sure! @bmccotter Could you investigate best practices?

**Comment by bmccotter** [comment]
absolutely! I've emailed Klarna. I'll also connect with Stripe and confirm if we need to be mindful of the re-brand within Stripe's settings.

**Comment by bmccotter** [comment]
Hey @roykho  I've heard from the team at Klarna:

In general all orange badges are supposed to be changed to the pink one. 
Please use the pink pay now badge saying "Klarna" (see screenshot) 
<img width="473" alt="screen shot 2018-11-07 at 8 17 05 am" src="https://user-images.githubusercontent.com/41127493/48136561-91c54900-e265-11e8-984b-93d34c1dfca0.png">


Depending on your integration (Klarna Payments or Sofortüberweisung-integration) it might make sense to add "pay now" in the local language next to the payment method.
As you already found out, details and values are stored[ here](https://developer.klarna.com/en/gb/kco-v3/sofort-design-guidelines/how-to-display-sofort/)

cc @pmaiorana  for visibility; also waiting on confirmation from Quinn at Stripe.

**Comment by bmccotter** [comment]
@dougaitken  @roykho  just reconfirming via Stripe that we should utilize the Klarna pink logo and remove Sofort. @DanReyLop  for visibility; and I think this can stay as backlog @allendav, but perhaps something we should address before we launch payments.

**Comment by selectedselections** [comment]
reported in 32527600-hc

**Comment by selectedselections** [comment]
Reported in 35568545-hc

**Comment by diegocurbelo** [comment]
> Klarna is in the process of deprecating Sofort as a standalone payment method while reducing buyer geo coverage for Sofort.

More info available here: https://support.stripe.com/questions/sofort-is-being-deprecated-as-a-standalone-payment-method
