### ISSUE TITLE
Prevent canceling of orders if user abandons after creating source and uses another gateway

### ISSUE THREAD

**Issue by tommyshellberg** [woocommerce/woocommerce-gateway-stripe#754]
#### Affected ticket(s)

1517617-zen

What's happening:

There was a scenario in which a shopper was prompted for a 3DS verification but it failed(white screen), possibly because of a connection issue with the processor. In the current implementation, AFAIK there's not much they can do other than hitting the back button and trying again. 

After Stripe generates the card.source for 3DS, it will be canceled within an hour if left 'pending':

https://stripe.com/docs/sources/three-d-secure#source-expiration

This sends the "source canceled" webhook. The Stripe plugin handles this by looking for an order and canceling the order.

It looks like the check is done here:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/453f739d2df7316f1a60aeb37e8036a337de903a/includes/class-wc-stripe-webhook-handler.php#L416

What happened here is that the user checked out with a different gateway a few minutes after failing to use 3DS. The order was subsequently marked as Processing *before* the 1 hour mark and before the "source canceled" webhook was fired.

In previous versions it checked if the order status was *not* On Hold or *not* Canceled and bailed with a `return;` statement. Now, it only checks that the order is *not* Canceled and then cancels. I think we shouldn't indiscriminately cancel the order if we receive the "source canceled" webhook as the user could have picked a different gateway within that 1 hour, or called the store owner and handled it over the phone, etc.

Also, if 3DS initially failed and they hit the back button to try again, would another card.source be generated? If that succeeded, couldn't this still be canceled when the original source expires?

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by tommyshellberg** [comment]
@woocommerce/extendables can I get some thoughts on this one so we can determine if this is an enhancement? This ticket has popped back up again.

**Comment by superdav42** [comment]
Looks like a bug. The logic was changed in https://github.com/woocommerce/woocommerce-gateway-stripe/commit/bab90c99a2d598ba791ad435076f493099a18cda#diff-a6a1b2bf675b2304d82c395801bebc2bL414
To fix a different problem. @roykho may know more but for now we can call this a bug.

**Comment by superdav42** [comment]
Pretty sure line 416 should be changed to: 
```php
if ( 'on-hold' === $order->get_status() ) {
```

**Comment by danielvonmitschke** [comment]
I have the same problem:

- User tries to pay via credit card (3Ds is enabled in stripe settings) and is redirected to the 3Ds page
- User (for some reason) does not know his 3Ds code, clicks on "cancel" and is redirected to the checkout page
- User uses a different payment method (successfully)
- After about 1 hour stripe sends the payment cancelled event and the order gets cancelled (though it was in processing due to the other successful payment)

I think this is a mayor bug and should definitely not happen as this cancels otherwise valid and paid orders.

**Comment by danielvonmitschke** [comment]
> Pretty sure line 416 should be changed to:
> 
> ```
> if ( 'on-hold' === $order->get_status() ) {
> ```

I think we should only check for "NOT PENDING" in this case.
As all other order status will mean a different payment was used and the order should not be cancelable by stripe.

**Comment by roykho** [comment]
Or keep it the way it is now but in addition add a check if the order was processed through Stripe then continue otherwise do nothing.

**Comment by roykho** [comment]
Hi @danielvonmitschke do you want to give this PR a test? https://github.com/woocommerce/woocommerce-gateway-stripe/pull/816

**Comment by danielvonmitschke** [comment]
> Hi @danielvonmitschke do you want to give this PR a test? #816

Looking good! Seems to be working with this fix.
Thank you

**Comment by danielvonmitschke** [comment]
I can also confirm that this is working with an abandoned stripe payment and then using another stripe payment (e.g. another credit card).
