### ISSUE TITLE
Apple Pay incorrect shipping option passed

### ISSUE THREAD

**Issue by rwaynick** [woocommerce/woocommerce-gateway-stripe#755]
#### Affected ticket(s)

1550100-zen

#### What I expected

Apple Pay would show the shipping option that's selected instead of always the first one in the list.

#### What happened instead

The first option was passed to Apple Pay instead of the selected one.

#### Steps to reproduce the issue

1 - Setup Stripe and Enable the Request Payment Buttons.
2 - Add multiple shipping methods for the zone that you're testing in.
3 - Add a product to the cart in Safari on a device that has Apple Pay setup.
4 - Select the first shipping option and click "Buy with Apple Pay"
5 - Notice that the shipping is correct,

![screen_shot_2018-11-08_at_12_10_45_pm](https://user-images.githubusercontent.com/10882502/48215551-7d11af80-e350-11e8-9646-26fe361ad64c.jpg)

6 - Choose the second option and notice that the second option is briefly displayed while "processing",

![screen_shot_2018-11-08_at_12_11_01_pm](https://user-images.githubusercontent.com/10882502/48215564-869b1780-e350-11e8-8e65-0a4aa991dade.jpg)

but then goes back to the first option,

![screen_shot_2018-11-08_at_12_10_45_pm-3](https://user-images.githubusercontent.com/10882502/48215580-90bd1600-e350-11e8-8a61-507bae592c91.jpg)

#### Version
Tested on macOS 10.14.1 and Safari version 12.0.1 (latest)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by dougaitken** [comment]
Tested and see the same on iPhone 7 and same Safari/Mac details as Richard.

I tested with two flat rates, two flat rates and Royal Mail, and Royal Mail and flat rate.

Tagging high as I _believe_ this wasn't always the case. I'm sure shipping option was respected previously. Unsure if this is a WC change in templates or Stripe.

I have checked Google Pay and this respects the shipping option chosen.

**Comment by yukikatayama** [comment]
pinging @woocommerce/extendables for update

**Comment by juliaamosova** [comment]
Pinging @woocommerce/extendables as a follow-up. Thanks!

**Comment by rohittm** [comment]
@woocommerce/extendables The user in 1550100-zd is back asking for the updates. Thanks.

**Comment by LaurenaRehbein** [comment]
Also reported in 8530163-HC.

**Comment by dougaitken** [comment]
Retested this out of curiosity, this is still an issue for Apple Pay. Confirmed again that Google Pay respects the shipping option chosen.

**Comment by jrick1229** [comment]
Reported in: 6387579-hc

**Comment by arcangelini** [comment]
Same issue in 2931853-zen

[![Screenshot](https://d.pr/i/n82igA+)](https://d.pr/i/n82igA)

**Comment by benique** [comment]
There is still an issue with the shipping. When you are on a product page and use the Apple Pay button to pay, it won't show any shipping methods.
