### ISSUE TITLE
Force all order to 3d secure

### ISSUE THREAD

**Issue by Samreaksa** [woocommerce/woocommerce-gateway-stripe#759]
I’ve enabled 3D Secure checkbox for your Stripe plugin, cards with Required and Recommended 3DS will go through 3D Secure challenge but cards doesn’t have 3D Secure enabled at all, the payment will go through without 3D Secure challenge as “three_d_secure”: “optional” or not_support.

So i want to force all Optional to required for all payment by add filter add_filter( ‘wc_stripe_require_3ds’, ‘__return_true’ ) but it still doesn’t work. see below:

***********************************
“card”: {
“exp_month”: 4,
“exp_year”: 2021,
“brand”: “Visa”,
“country”: “US”,
“cvc_check”: “pass”,
“fingerprint”: “pXS2Ien0yymwRKg9”,
“funding”: “credit”,
“last4”: “4242”,
“three_d_secure”: “optional”,
“name”: null,
“address_line1_check”: null,
“address_zip_check”: null,
“tokenization_method”: null,
“dynamic_last4”: null
},
*******************************************
I also used add_filter( 'wc_stripe_require_3ds', '__return_true' ); in my child theme functions.php file but still not work.
This is the function that I’ve tried to force all payment to 3ds:

******************************************
add_action(‘woocommerce_cart_updated’, ‘wc_stripe_require_3ds’,10, 2);

function wc_stripe_require_3ds (){
global $woocommerce;
$maximum = 50;

if ( WC()->cart->subtotal > $maximum ) {

add_filter( ‘wc_stripe_require_3ds’, ‘__return_true’ );

}
}
******************************************

Would you be able to assist me please?

Thanks,
Sam

**Comment by roykho** [comment]
Not a support channel. Use https://wordpress.org/plugins/woocommerce-gateway-stripe/
