### ISSUE TITLE
Stripe checkout is broken when purchasing a subscription

### ISSUE THREAD

**Issue by cecrichlow** [woocommerce/woocommerce-gateway-stripe#761]
Not sure if anyone is aware of this being an issue yet, since I wasn't seeing any references in the open or closed issues so far, but just ran into this today and thought I'd post it here.

WooCommerce is throwing an error when checking out with a subscription: Call to undefined function wcs_user_has_subscription() in /www/wp-content/plugins/woocommerce-gateway-stripe/includes/compat/class-wc-stripe-subs-compat.php:88

Looks like this function reference got added in from this commit, but its definition never did: https://github.com/woocommerce/woocommerce-gateway-stripe/commit/b7df3a790b728f87901deda85f157464a939110e

I was able to get around this by commenting out line 23 in includes/compat/class-wc-stripe-subs-compat.php.

**Comment by roykho** [comment]
What version of Subscriptions are you using?

**Comment by cecrichlow** [comment]
3.0.0 is what's currently installed on the particular site I'm working on.

**Comment by roykho** [comment]
The latest version 2.4.4. Are you sure you have the official WooCommerce Subscriptions extension? Seen here https://woocommerce.com/products/woocommerce-subscriptions/

**Comment by cecrichlow** [comment]
Hmm. Apparently not. (Sorry, I've inherited this site from a different group of people). It's using this one: https://www.webtoffee.com/product/woocommerce-subscriptions/.

**Comment by roykho** [comment]
Then I would suggest you install a Stripe plugin that is compatible with that specific subscriptions plugin.
