### ISSUE TITLE
Stripe Checkout = no modal window for CC input

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#763]
#### Affected ticket(s)
https://wordpress.org/support/topic/failed-to-execute-postmessage-on-domwindow-error-at-checkout/

#### What I expected
To be able to pay for my order via Stripe Checkout

#### What happened instead
Can not pay for my order, pressing the "pay for order" button doesn't seem to do anything at all

#### Steps to reproduce the issue
1. Stripe checkout is enabled
2. Try to pay for an order

-------------------

- [ ] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

**Comment by RiaanKnoetze** [comment]
Another ticket here: #1679059-zd

Note, the customer on the forum thread did revert with the following:

> The Stripe account failed to update. That was the problem. Once a new API was put in, it started working again. Thank you.

**Comment by RiaanKnoetze** [comment]
This might also be helpful: https://github.com/stripe/react-stripe-elements/issues/98

**Comment by roykho** [comment]
I am unable to replicate the issue.

![](http://cld.wthms.co/JFgBNw+)

Please re-open if this continues to be a problem.
