### ISSUE TITLE
Checkbox for wc_stripe_display_update_subs_payment_method_card_checkbox is unchangeably always false by default

### ISSUE THREAD

**Issue by gerdneuman** [woocommerce/woocommerce-gateway-stripe#764]
Sorry, I think there's been a misunderstanding :) When I asked that the default value for the checkbox should be `false` in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/728#issuecomment-424263975 I thought that `wc_stripe_display_update_subs_payment_method_card_checkbox` would control the value of the checkbox (`checked` or not checked). That is, like `wcs_update_all_subscriptions_addresses_checked` in the woocommerce subscriptions plugin:

```php
                                // translators: $1: address type (Shipping Address / Billing Address), $2: opening <strong> tag, $3: closing </strong> tag
                                $label = sprintf( esc_html__( 'Update the %1$s used for %2$sall%3$s of my active subscriptions', 'woocommerce-subscriptions' ), wcs_get_address_type_to_display( $address_type ), '<strong>', '</strong>' );

                                woocommerce_form_field(
                                        'update_all_subscriptions_addresses',
                                        array(
                                                'type'    => 'checkbox',
                                                'class'   => array( 'form-row-wide' ),
                                                'label'   => $label,
                                                'default' => apply_filters( 'wcs_update_all_subscriptions_addresses_checked', false ),
                                        )
                                );

```

Well, but in 

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/453f739d2df7316f1a60aeb37e8036a337de903a/includes/compat/class-wc-stripe-sepa-subs-compat.php#L85-L100

and 

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/453f739d2df7316f1a60aeb37e8036a337de903a/includes/compat/class-wc-stripe-subs-compat.php#L85-L100

at the moment the `input type=checkbox` is always unchecked by default. (fwiw, also strange that there's duplicate code in 2 files ;)

**What would be expected instead:**

Please add a way (filter) so that the default value for this checkbox can be set to `checked` by default. I think the subscriptions plugin does it right here and using the `woocommerce_form_field` with ` 'type'    => 'checkbox',` is also much better since the CSS classes are all correctly inherited.

**Comment by glagonikas** [comment]
There doesn't seem to be much traction on this issue. @gerdneuman can you check if my PR resolves your issue?

**Comment by gerdneuman** [comment]
@glagonikas I am on holidays until end of August, so cannot test until then. Maybe someone else could? (Thanks for the PR!).

**Comment by glagonikas** [comment]
@roykho @DanReyLop @allendav @rynaldos apologies for mentioning all of you, but i'm not sure who's the best person to look and approve my PR?

**Comment by allendav** [comment]
@v18 - I assume this should be looked at for 4.3. If not, please move to a later release
