### ISSUE TITLE
Error with localization

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-stripe#77]
Wrong object returned from stripe is being used, causing localised error messages to not display.

stripe.js l:93

Broken:
```
if ( wc_stripe_params.hasOwnProperty( responseObject.response.error.code ) ) {
message = wc_stripe_params[ responseObject.response.error.code ];
}
```

Fixed:
```
if ( wc_stripe_params.hasOwnProperty( responseObject.response.error.type ) ) {
message = wc_stripe_params[ responseObject.response.error.type ];
}
```

Source: https://wordpress.org/support/topic/error-message-localization-broken/

**Comment by roykho** [comment]
`code` should be correct per Stripe's reference docs seen here https://stripe.com/docs/api#errors

**Comment by netplus** [comment]
I'm the original poster on the WP support area. - I've investigated this a little more. It ends up this only occurs on empty form submission.

If you submit an empty form to stripe, it returns an error message without a code.

Empty form response:
{
  "error": {
    "type": "invalid_request_error",
    "message": "Could not find payment information"
  }
}

If the form has any data it will return with a code

Example response:
{
  "error": {
    "message": "Your card's expiration year is invalid.",
    "type": "card_error",
    "param": "exp_year",
    "code": "invalid_expiry_year"
  }
}

The problem being it's not currently possible to localise the empty form error response.

**Comment by samuelaguilera** [comment]
@roykho you have added messages only for **card_error** type and assumed that any responseObject will have a code, but as you can see in the results pasted by @netplus and also in the Stripe docs, **there also additional error types and not all types have a code**, some of them only have a type and message. From the Stripe.com docs linked above:

> The type of error returned. Can be: api_connection_error, api_error, authentication_error, card_error, invalid_request_error, or rate_limit_error.

The appropriate solution would be check responseObject.response.error.type to determine what data contains the responseObject (e.g. it has a code or not?) and proceed accordingly. That is basically what Stripe.com is recommending with this:

> Handling errors
> Our API libraries raise exceptions for many reasons, such as a failed charge, invalid parameters, authentication errors, and network unavailability. **We recommend writing code that gracefully handles all possible API exceptions.**

**Comment by roykho** [comment]
@samuelaguilera - this has already been flagged a bug so it is known and will be fixed by next release.

**Comment by samuelaguilera** [comment]
@roykho great! just commented because of your comment after flagging it as a bug and also seeing that it was labeled as "needs author reply" days after that. Just wanted to add some light here :)
