### ISSUE TITLE
Feature: Allow Keys/Settings to be Defined in Constants

### ISSUE THREAD

**Issue by alexmacarthur** [woocommerce/woocommerce-gateway-stripe#770]
#### Feature Request
As a developer, I'd like the ability to define sensitive keys (and perhaps other settings) in PHP constants whose values are sourced from an external secrets manager. As far as I'm currently able to tell, the only place to store this sensitive information is within the database, which does not satisfy the security concerns of stakeholders. 

#### What This Might Look Like

If certain constants (following a naming convention) are provided, the respective settings inside the admin are disabled. 

```php
define('WOOCOMMERCE_STRIPE_TEST_PUBLISHABLE_KEY', 'pk_test_blahblahblah');
```

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by dwainm** [comment]
I've closed the PR that was open to this. It seems like a very nice feature for some users but has not been requested by anyone else. This can be done by extending the plugin. Please see my full reply here:
https://github.com/woocommerce/woocommerce-gateway-stripe/pull/771
