### ISSUE TITLE
[Docs] CSS admin notice 'Instructions' link does not link to instructions

### ISSUE THREAD

**Issue by willgorham** [woocommerce/woocommerce-gateway-stripe#777]
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/e0b7f3cb1c5342f681d9ee160963c5b5ae510b18/includes/admin/class-wc-stripe-admin-notices.php#L115-L119

The new admin notice about the recent CSS changes contains a link to the following URL: https://docs.woocommerce.com/document/stripe/#section-45. However, the page linked to doesn't contain any instructions about fixing the CSS, it's just the Questions and Feedback section of the FAQ docs.

**Comment by roykho** [comment]
Sorry it has since been moved. https://docs.woocommerce.com/document/stripe/#section-13
