### ISSUE TITLE
Impossible to input card number for Japanese iOS users

### ISSUE THREAD

**Issue by netplus** [woocommerce/woocommerce-gateway-stripe#78]
We've deployed this gateway for two Japanese websites and found it's impossible to input card numbers while using a Japanese iOS keyboard.

Please see following bug demo video.
[https://www.youtube.com/watch?v=MEpelmggcsE](https://www.youtube.com/watch?v=MEpelmggcsE)
I've typed 424242 but 4244242422 has appeared

**Comment by roykho** [comment]
I am not sure if this is a Stripe plugin issue. Can you please try the same with a different plugin?

**Comment by netplus** [comment]
You are correct, this is a core Woocommerce credit card form issue caused by their use of the jquery.payment.js I will raise it with them.

Thanks for the quick response, I will only bother you with one more bug today.
