### ISSUE TITLE
Stripe extension doesn't work on the checkout page if JavaScript is disabled

### ISSUE THREAD

**Issue by TommiHynynen** [woocommerce/woocommerce-gateway-stripe#780]
I'm not sure if this is a bug or just missing feature but looks like it's impossible to place an order if the JavaScript is disabled on your browser. Well, you can place an order but you can't fill up the credit card information, and the order is automatically failed. This is a bit annoying problem since some of our customers doesn't use JavaScript, and the plugin doesn't clearly inform on the checkout page what is wrong and why their order is failed. I recommend to include clear warnings with noscript tags or try to not rely on browser-side JavaScript.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by lkraav** [comment]
@TommiHynynen I'm fairly certain there's is about 0% chance of non-JS checkout solution here.

But a `<noscript>` warning would certainly be useful.

**Comment by dougaitken** [comment]
> I'm fairly certain there's is about 0% chance of non-JS checkout solution here.

Can confirm. This is due to the fact that the checkout form is generated via Stripe Elements, it is pure JavaScript being injected into the checkout page via their [Stripe JS](https://stripe.com/docs/stripe-js).

Marking as Enhancement and Question so the team can look at a possible `<noscript>` addition.

**Comment by roykho** [comment]
Closing this as it is already answered. Feel free to open another issue for a warning however I don't see too much value in adding it. With the text that WC core already shows, adding this additional warning will just get lost.
