### ISSUE TITLE
Payment processing failed. Please retry.

### ISSUE THREAD

**Issue by jahau** [woocommerce/woocommerce-gateway-stripe#783]
I'm using WooCommerce 3.5.4, WooCommerce Stripe Gateway 4.1.14 and of course the latest WordPress. I get the mentioned error "Payment processing failed. Please retry." with test mode enabled in Stripe account.

In the WooCommerce logs I don't see anything special but in the Stripe account the following data is available:

`Request POST body
{
  "url": "http://yeah/?wc-api=wc_stripe",
  "enabled_events": [
    "*"
  ],
  "connect": "false",
  "force_latest_version": "false"
}
Response body
{
  "id": "we_idididididididididididi",
  "object": "webhook_endpoint",
  "api_render_version": "2018-11-08",
  "application": null,
  "created": 1550307744,
  "enabled_events": [
    "*"
  ],
  "livemode": false,
  "secret": "whsec_***dddd",
  "status": "enabled",
  "url": "http://yeah/?wc-api=wc_stripe"
}`

I've noticed several other issues about the same thing but none of those were resolved. Anybody can manage to resolve this at this time? Thanks.

**Comment by dougaitken** [comment]
`"url": "http://yeah/?wc-api=wc_stripe"`

That isn't a valid domain, Stripe.com requires a valid domain, and I don't think even your local WP environment has that domain. Is that the webhook you have in your Stripe.com account? Match the webhook and your site domain, and see what happens in test mode @jahau

**Comment by jahau** [comment]
The url was proper, it's just "masked" to this thread. Could the reason be that the (test) site doesn't utilize https?

**Comment by dougaitken** [comment]
The Stripe extension will work on non-HTTPS in Test Mode only. That is the Stripe extension settings are set to your Test keys as well, not just your Stripe.com account.

But looking at that log, it does have `"livemode": false` so I'm not sure. 

Can you open a ticket for WooCommerce.com support, please?
