### ISSUE TITLE
Remove Legacy Checkout (Modal)

### ISSUE THREAD

**Issue by DanReyLop** [woocommerce/woocommerce-gateway-stripe#785]
Right now, in the Stripe settings, the merchant can choose between having the payment fields in the checkout page (the default), or using "Stripe Checkout", which opens a <del>completely separate page (similar to PayPal)</del> modal.

We should check if the Stripe Checkout works correctly with Payment Intents, and if it's not easy to make it work, consider removing it.

Edit: When removing the Legacy Checkout altogether, we'll need to remember to remove the warning notice added here: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/837/files#diff-bb6de50012b6937b8a786bcb0f70bdd7R119

**Comment by RadoslavGeorgiev** [comment]
The current decision is that Stripe Checkout will be handled at a later stage, and as a separate project.

With that in mind, https://github.com/woocommerce/woocommerce-gateway-stripe/pull/803 ensures that PaymentIntents will not interfere with the checkout modal.

I am removing `[Pri] High` and detaching the issue from the EEA SCA project, but leaving it open for later actions.

**Comment by allendav** [comment]
Update: With Stripe's prompting, we've decided to remove the legacy checkout modal in 4.2.0 - to avoid a rough user experience with modal checkout and SCA redirects.
