### ISSUE TITLE
SCA: Remove the old "three_d_secure" logic

### ISSUE THREAD

**Issue by DanReyLop** [woocommerce/woocommerce-gateway-stripe#788]
Since the 3D-Secure flow will be handled automatically by the Payment Intents flow, we should remove the old flow entirely. That includes the setting to enable it even for cards where it's optional.

With Payment Intents, now it's possible to define the "level of risk" acceptable in the Stripe dashboard itself, so a merchant can go there and configure Stripe to always ask for 3d Secure whenever the card "recommends" it, which would be equivalent to what the current option does now. More info: https://stripe.com/docs/payments/dynamic-3ds

Maybe we should explore keeping the old setting, for backwards-compatibility's sake. We should check if it's possible to "suggest" Stripe to use 3D Secure in the payment request itself, or if it needs to be defined in the merchant's dashboard.

**Comment by RadoslavGeorgiev** [comment]
Merging https://github.com/woocommerce/woocommerce-gateway-stripe/pull/795 should've closed this issue. Doing it manually...
