### ISSUE TITLE
SCA: Check if the PaymentIntent object always contain exactly 1 "Charge"

### ISSUE THREAD

**Issue by DanReyLop** [woocommerce/woocommerce-gateway-stripe#789]
See here: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/781/files#diff-2f62df4143b223ac0f7805c02376412eR808

Where the old, source-based system expected a Charge object, now we have a PaymentIntent object, so we've used `$intent->charges->data[0]` to get the Charge object associated to that intent.

That's an ok hack to get us by, but we should check if there's a possibility that the `charges` array will be empty or have more than 1 charge, and what to do in thos cases.

**Comment by RadoslavGeorgiev** [comment]
https://github.com/woocommerce/woocommerce-gateway-stripe/pull/808 should've closed this issue, doing it manually instead...
