### ISSUE TITLE
During payment processing spinner is not visible on mobile

### ISSUE THREAD

**Issue by netplus** [woocommerce/woocommerce-gateway-stripe#79]
## What I expected

On submitting the credit card form I expected to see a ui block with a spinner.
## What happened instead

A white overlay appears only blocking the form with no indication of activity. On themes with sticky headers this header is not blocked, header navigation is still possible.
## Steps to reproduce the issue

Checkout on mobile
## Suggestions

See \woocommerce-gateway-stripe\assets\js\stripe.js lines 70 ~ 150

Currently the UI block is applied to the form which is above the screen when pressing the checkout button.

Our solution is to create a second full UI blocking function (call blockUI without an element) and only use this function on submission of the form.

See our hacky solution below. I'm sure you can come up with something better!

Block functions:

block: function() {
            wc_stripe_form.form.block({
                message: null,
                overlayCSS: {
                    background: '#fff',
                    opacity: 0.6
                }
            });
        },

```
    fullBlock: function() {
        $.blockUI({
            message: null,
            overlayCSS: {
                background: '#fff',
                opacity: 0.6
            }
        });
    },

    unblock: function() {
        wc_stripe_form.form.unblock();
        $.unblockUI();
    },
```

During submit:

onSubmit: function( e ) {
            if ( wc_stripe_form.isStripeChosen() && ! wc_stripe_form.hasToken() ) {
                e.preventDefault();
                wc_stripe_form.fullBlock();

Detect event from Woocommerce:

```
$( document.body ).on( 'checkout_error', function() {
    $.unblockUI();
});
```

**Comment by roykho** [comment]
Fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0
