### ISSUE TITLE
SCA: Prepare a list of previous charges for subscriptions

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [woocommerce/woocommerce-gateway-stripe#793]
Context: The *What happens to recurring payments Set up before Sept 14* section of paIf5I-l-p2

For automatic subscription payments (each payment, but the first), use the order ID meta that is stored within Stripe in order to create an array with all previous charge IDs. The values of this array will be used to indicate to CC companies that the new charge is a part of a subscription, in order to avoid customers having to re-auth subscriptions because of SCA.

**Comment by DavidAnderson684** [comment]
I'm very interested in how you plan to do this. I've talked to Stripe support, and even shown them this issue directly to make sure that we're talking about the same thing, and they have said "there's no method for making past customers who were being charged with the Charges API and not the Billing API, exempt from authorization". I've asked them explicitly, making extra sure, and they say that there is not method "to avoid customers having to re-auth subscriptions because of SCA".

**Comment by allendav** [comment]
@RadoslavGeorgiev @dechov - I'm assigning this to the 4.3.0 milestone. Please let me know if a different milestone is more appropriate.

**Comment by yoandm** [comment]
Do you have news about that ? I need to do something similar to make payment in installments.
With SCA, actual method to save card in the plugin does not work. I'm currently studying the code to find a solution to change that. Maybe you're already working on it ?

**Comment by RadoslavGeorgiev** [comment]
> With SCA, actual method to save card in the plugin does not work

https://www.youtube.com/watch?v=3TUNSzbEypA What do you mean? I've used this a ton for testing and the card was always saved.

Otherwise https://stripe.com/docs/payments/cards/reusing-cards just got released today. The list of previous charges is not even needed 🎉

**Comment by yoandm** [comment]
Yes, the card is saved but if I try with a "SCA test card", I can't charge another time using the token.
Maybe I made a mistake.

**Comment by yoandm** [comment]
I get a "Your card was declined. This transaction requires authentication."

**Comment by RadoslavGeorgiev** [comment]
We will start adjusting our integration with WooCommerce Subscriptions very soon and you will be able to see the type of changes are required in order to enable SCA merchant-initiated transactions.

**Comment by yoandm** [comment]
Ok cool.
If you need help for testing (or other), don’t hesitate.


> Le 4 juil. 2019 à 10:26, Radoslav Georgiev <notifications@github.com> a écrit :
> 
> We will start adjusting our integration with WooCommerce Subscriptions very soon and you will be able to see the type of changes are required in order to enable SCA merchant-initiated transactions.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- 
Yoan De Macedo
yoandm.com

**Comment by yoandm** [comment]
Do you if card saved before SCA will need a new authentification ? It's difficult to find this kind of information about SCA. Maybe you have this ? Thank you ;)

**Comment by githubyaya** [comment]
I think this article from Stripe clarifies what is needed for reusing SCA cards, in an off-session context, specifically intended for merchants with subscription based services. https://stripe.com/docs/payments/cards/reusing-cards

**Comment by Aleksandar-Mitic** [comment]
We also have the problem with subscriptions renewals and Stripe, using test SCA card (4000000000003220). 
We get this error:        
[code] => authentication_required
[decline_code] => authentication_required
[message] => Your card was declined. This transaction requires authentication."

How we can fix this? We are using latest Stripe & WC-Subscriptions plugins.

**Comment by DanReyLop** [comment]
We have created issues to track this work. They're all under the `4.3.0` release milestone, which we're planning to release before September 14th: https://github.com/woocommerce/woocommerce-gateway-stripe/milestone/22

These are the main issues to look for: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/938 https://github.com/woocommerce/woocommerce-gateway-stripe/issues/937 https://github.com/woocommerce/woocommerce-gateway-stripe/issues/936 https://github.com/woocommerce/woocommerce-gateway-stripe/issues/935
