### ISSUE TITLE
Credit Card gateway "auto selected" on #payment form refresh when Card is saved in user account

### ISSUE THREAD

**Issue by FrancescoCarlucci** [woocommerce/woocommerce-gateway-stripe#80]
When a user already has a credit card saved in my account, Credit Card gateway is selected by default every time the payment form is refreshed.

Example:

- user select another gateway (eg. paypal)
- user change shipping method
- form is refreshed to calculate fee
- gateway automatically changes and Credit Card get selected automatically

This can be boring, but also an issue if using a plugin that triggers 'update_checkout' to apply gateway fees, making other gateways totally unselectable.

**Comment by roykho** [comment]
I believe this issue is with WC core. WC handles the default selection of that depending on context/situation.
