### ISSUE TITLE
SCA: Alter `WC_Stripe_Pre_Orders_Compat` to support payment intents.

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [woocommerce/woocommerce-gateway-stripe#802]
Currently if pre-orders are active, the gateway will save the source of a card, but not charge it immediately.

With PaymentIntents, this will not automatically work, as intents need to be captured within 7 days.

__Important:__ In order to implement this, we have to wait for Stripe to implement an API, which allows 3DS to happen "now" and auth + capture 30 days later.

**Comment by RadoslavGeorgiev** [comment]
Currently on hold, awaiting details on how to accomplish this through SCA

**Comment by allendav** [comment]
@RadoslavGeorgiev @dechov - I've assigned this to the 4.3.0 milestone. Please let me know if another milestone would be better.

**Comment by DanReyLop** [comment]
We're tracking this in https://github.com/woocommerce/woocommerce-gateway-stripe/issues/941
