### ISSUE TITLE
[On Hold] SCA: Save intent IDs when generating them and respond in webhooks.

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [woocommerce/woocommerce-gateway-stripe#804]
Currently we are not storing intents and relying on the checkout flow to retrieve the intent ID from a hidden field and proceed based on that.

We should figure out a way to save those intents and also handle intent-related webhooks.

**Comment by RadoslavGeorgiev** [comment]
#826 adds support for the following webhooks:

1. `payment_intent.succeeded`
2. `payment_intent.payment_failed`

After the PR is merged, this issue will be fixed.

**Comment by allendav** [comment]
@RadoslavGeorgiev @dechov - I'm assigning this to the 4.2.0 milestone. Please let me know if a different milestone is more appropriate.

**Comment by RadoslavGeorgiev** [comment]
The webhooks in `sca/master` already handle all needed actions. This issue should've been auto-closed by GH, doing it manually now.
