### ISSUE TITLE
[On Hold] SCA: Create an article that explains how to handle checkout with JavaScript and payment gateways.

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [woocommerce/woocommerce-gateway-stripe#809]
@allendav and I came to the conclusion that there are proper resources about handling multi-step (create, authorize, capture, etc.) in WooCommerce's docs, so we'd like to write an article about it.

**Comment by RadoslavGeorgiev** [comment]
@allendav in #826 it turned out that we have not really found the perfect approach for such cases yet, so we do not have good material for such an article. I'm putting this task on hold for now and removing it from the reserves board, but not closing the issue.

**Comment by v18** [comment]
Going to close for now, may re-open in the future depending on documentation requests.
