### ISSUE TITLE
[On Hold] SCA: Save payment intents in session

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [woocommerce/woocommerce-gateway-stripe#821]
Currently PaymentIntents are created when visitors try to complete the checkout process. This does not change, but in case visitors abandon the checkout process after a PI has been generated, that PI should still be updated & used later.

### Expected behavior

1. Add products to the cart
2. Open the checkout form and try submitting it. This will create a PI, but the payment will fail.
3. Close and re-open the website & checkout page.
4. Once everything has been filled in, the existing PI should be used instead of creating a new one.

IIRC the WC session class does not support arbitrary metadata (like the ID of the payment intent), but I might have missed something.

**Comment by RadoslavGeorgiev** [comment]
#826 handles this by utilizing the data saved in orders (incl. PaymentIntent IDs) in order to re-use the existing intent.

**Comment by allendav** [comment]
@RadoslavGeorgiev @dechov - I'm assigning this to the 4.2.0 milestone. Please let me know if a different milestone is more appropriate.

**Comment by RadoslavGeorgiev** [comment]
Closing this issue, it was included in the `Fixes` keywords within https://github.com/woocommerce/woocommerce-gateway-stripe/pull/826, but for some reason GitHub didn't catch that.
