### ISSUE TITLE
[On hold] SCA: Update PaymentIntents when costs change (ex. shipping)

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [woocommerce/woocommerce-gateway-stripe#822]
Currently Payment Intents are generated once and their amount never gets updated. This means that if additional costs (ex. shipping) change after the creation of a payment intent, those changes will never reach the intent.

**Comment by RadoslavGeorgiev** [comment]
This issue should be partially covered by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/826:

1. Costs cannot change after an order is created. Even if they do, WooCommerce will create a new order and I believe we have no hooks on which to transfer the event to the new order. Maybe @DanReyLop or @dechov would like to confirm this before we close the issue.
2. Even though (as mentioned in 1.) we will create a new PI (instead of updating an existing one), at least it will have the correct total amount.

**Comment by allendav** [comment]
@RadoslavGeorgiev @dechov - I'm assigning this to the 4.2.0 milestone (sorry!). Please let me know if a different milestone is more appropriate.

**Comment by RadoslavGeorgiev** [comment]
Thanks for reminding us for the issue @allendav!

The current code in `sca/master` addresses both points from my previous comment:

1. PaymentIntents are always updated within `process_payment` after submitting the checkout page. This includes shipping costs, etc.
2. As just mentioned, once an order has an associated PI, that PI will get updated. In case there is no order to load a PI from, a new one with the correct amount will be created.

I'm closing the issue as it has already been fixed.
