### ISSUE TITLE
Integrate PaymentIntents with Stripe

### ISSUE THREAD

**Issue by eozkan82** [woocommerce/woocommerce-gateway-stripe#824]
Hello;

How can we integrate Paymentintets with Woocommerce. As my current settings, I am using official Woocommerce Stripe plugin from wordpress. However it doesn't accept payments without 3Ds

**Comment by allendav** [comment]
Hi @eozkan82 - we are working on integrating PaymentIntents right now - you can follow our progress on this label: https://github.com/woocommerce/woocommerce-gateway-stripe/issues?q=is%3Aissue+is%3Aopen+label%3A%22PaymentIntents+%2F+SCA%22
