### ISSUE TITLE
You must specify a value for cross_border_classification

### ISSUE THREAD

**Issue by LavBhelloriya** [woocommerce/woocommerce-gateway-stripe#825]
I have a stripe India account and here we have to mandatorily pass a value of cross_border_classification=export to charge a customer. I am using this plugin but my payments are failing due to this issue. Where and how can I enter this value?
![stripe error](https://user-images.githubusercontent.com/28310307/55285536-c91aca80-53ab-11e9-8bb7-bedb7211ad01.PNG)
{
  "error": {
    "message": "You must specify a value for cross_border_classification.",
    "param": "cross_border_classification",
    "type": "invalid_request_error"
  }
}
This is the error.
![stripe sample](https://user-images.githubusercontent.com/28310307/55285544-de8ff480-53ab-11e9-9754-388253d3a977.PNG)
This image shows what we have to enter. 
Please help.
Thanks & Regards.

**Comment by allendav** [comment]
Hi @LavBhelloriya - there is no setting for this, but this filter may prove useful: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-api.php#L121

Please let us know if this doesn't help. Closing this issue for now.
