### ISSUE TITLE
SCA: Bring back 3DS support for Stripe Checkout

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [woocommerce/woocommerce-gateway-stripe#827]
#### What I expected

When using Stripe Checkout (legacy modal), I expected to enter a card that requires 3DS authentication and be redirected to confirm the payment.

#### What happened instead

There was no redirect to Stripe, instead the extension created a PaymentIntent, but did not redirect me to a page where I can see the authorization modal.

#### Suggestions

Either bring back some of the 3DS support that was removed in #795, or implement a redirect to the "Pay for Order" page, if #826 gets merged.

**Comment by allendav** [comment]
@DanReyLop @dechov - now that we are removing the legacy (modal) checkout in this same milestone (4.2.0) via #785 , does this issue or #826 need to change?

cc @RadoslavGeorgiev

**Comment by DanReyLop** [comment]
This issue no longer applies, because we're going to fully remove Stripe Checkout. Closing it.

I don't see any changes needed on #826 relating to this issue.
