### ISSUE TITLE
SCA: Make sure new SCA code properly tests for pre-3.0 WC if/where needed

### ISSUE THREAD

**Issue by RadoslavGeorgiev** [woocommerce/woocommerce-gateway-stripe#828]
While working on #826 I saw that @roykho has many lines of code like this:

```php
WC_Stripe_Helper::is_wc_lt( '3.0' ) ? update_post_meta( $order_id, '_transaction_id', $notification->data->object->id ) : $order->set_transaction_id( $notification->data->object->id );
```

What is the minimum version of WooCommerce that we currently support? If it is >= 3.0, then we should make sure that all code in `sca/master` is backwards-compatible before merging it.

**Comment by allendav** [comment]
I propose we include in 4.2.0 a warning that older WooCommerce support is ending for this extension ( #832 ) and then in 4.3.0 we remove pre-3.0 support ( #833 )

This means that, for SCA in 4.2.0, we will still need the `is_wc_lt( '3.0' )` code, including in the new SCA bits

This issue should be used to add in any missing `is_wc_lt( '3.0' )` checks

**Comment by allendav** [comment]
I'll have an update on Friday on how we want to proceed re pre-3.0 code.

**Comment by prethree** [comment]
PLEASE consider to add SCA compatibility to Stripe version 2.6.12 so it works with older versions of Woocommerce. Woocommerce 3 & above is very laggy and slow when a product has many variations, constantly waiting for the Ajax to change the selected options and main preview image (even with the latest PHP version on the server).

Woocommerce 2.3.7 is fast and renders product variation images instantly. So, PLEASE, when you're developing the Stripe Woocommerce plugin ready for September to work with SCA, PLEASE also update Stripe Woocommerce payments plugin 2.6.12 to work with older versions so as not to have to go to the trouble of migrating to another platform like shopify or magento.

**Comment by allendav** [comment]
> PLEASE consider to add SCA compatibility to Stripe version 2.6.12 so it works with older versions of Woocommerce

Hi @prethree - thank you for your thoughtful request. We will not, however, be adding SCA to that version. I recommend you open an issue on WooCommerce core with the variations problem you mention.

**Comment by prethree** [comment]
Thanks for responding so quickly Allen, I'm naturally disappointed as my current Woocommerce/Wordpress/Stripe configuration works like a speedy dream, but I'll do as you suggest and contact Wordpress Core (have googled it and assume you mean this: https://github.com/woocommerce/woocommerce )

**Comment by allendav** [comment]
@prethree wrote:

> have googled it and assume you mean this: https://github.com/woocommerce/woocommerce )

Yup - thank you :)

**Comment by v18** [comment]
We require minimum WC 3.0 now, so I'm closing this issue:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/c4acd556d7a67164bac8855cb2c5af296954f0f2/woocommerce-gateway-stripe.php#L11
