### ISSUE TITLE
Default Form Value price is not respected until after validation using ApplePay

### ISSUE THREAD

**Issue by amandasjackson** [woocommerce/woocommerce-gateway-stripe#829]
#### Affected ticket(s)

1924684-zd

#### What I expected

When a `Default Form Value` is set for a Variable product, when paying with ApplePay or Google Pay, the price displayed in the payment window should match that of the default variation product. 

#### What happened instead

When a `Default Form Value` is set for a Variable product, and you click `Pay Now` (Google Pay) or ApplePay, the price shown is the cheapest price of the variable products. 

![Screenshot](https://cld.wthms.co/B0TlLK+)
Screenshot direct link: https://cld.wthms.co/B0TlLK

#### Steps to reproduce the issue

1) Enable Apple Pay/ Google Pay
2) Create a variable product with different prices for the variations
![Screenshot](https://cld.wthms.co/d4Of3V+)
Screenshot direct link: https://cld.wthms.co/d4Of3V

3)Set the `default form value` to the most expensive variation
![Screenshot](https://cld.wthms.co/o9PBlX+)
Screenshot direct link: https://cld.wthms.co/o9PBlX

3)Go to product page, and click the Google Pay/ Apple Pay

4)Notice that the price displayed does not match the correct price of the variation until payment is verified. 

![Screenshot](https://cld.wthms.co/8KwFJY+)
Screenshot direct link: https://cld.wthms.co/8KwFJY

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by dougaitken** [comment]
I've tested this one myself and have replicated it. What I noticed is that if you confirm the shipping address, the modal changes to reflect the correct form value that was passed to Google Pay and Apple Pay.

**Comment by OxfordDigital** [comment]
Any update on this issue? It's still causing some UX confusion with customers.

**Comment by damiannep** [comment]
Another case of this in 3539695-zen. However, the difference is that in this case, there is no default form value set for the variation. I was able to replicate this on my test site as well.

**Comment by rossviviano** [comment]
Another report in 27117849-hc
