### ISSUE TITLE
Enable Stripe address fields

### ISSUE THREAD

**Issue by hannahswain** [woocommerce/woocommerce-gateway-stripe#83]
Customer has asked to enable the Stripe address fields.  This counters a problem with Memberships where the credit card address is different from the billing address.

Here's the suggestion from the customer: 

```
For now I have made the following change under /woocommerce-gateway-stripe/assets/js/stripe_checkout.js :

on line 96 I changed:

address: false,

to:

address: true,

This then includes the address fields on the 'Stripe Checkout' box.

Could you please add in the next update an admin option by the 'Enable Stripe Checkout' option? This might take maybe 5 - 10 minutes of your time.
```

How should we handle this further?

479470-zd-woothemes

**Comment by roykho** [comment]
A filter for this is already there see https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L404

**Comment by joe-westcott** [comment]
Hi Royko, you seem to be referring to the email address, but Hannah was referring to the physical address.

**Comment by roykho** [comment]
@joe-westcott just referenced wrong filter. https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L562
