### ISSUE TITLE
Orders: Duplicate Stripe charges for same order

### ISSUE THREAD

**Issue by dmpinder** [woocommerce/woocommerce-gateway-stripe#831]
#### What I expected

For a customer to be charged once when they order something.

#### What happened instead

In some cases (perhaps 1 in 50) the customer is charged twice for the same order, with unique Stripe charge IDs.

#### Steps to reproduce the issue

At the moment we can't reproduce the error, and it doesn't happen often.

Here are 3 screenshots showing duplicate Stripe charges for the same WC order ID:

![50134](https://user-images.githubusercontent.com/4732147/55712113-13243180-59e6-11e9-8659-2859acfaa0f1.png)
![50130](https://user-images.githubusercontent.com/4732147/55712114-13243180-59e6-11e9-8b89-45a33ae86ccb.png)
![50266](https://user-images.githubusercontent.com/4732147/55712117-13bcc800-59e6-11e9-9cad-32d510594611.png)

I've got the debug log snippet for Order 50266.

Here's the first charge:

(Apologies for the poor formatting, I can't seem to get the log to look right with Github's code block)

---

2019-03-29T11:12:42+00:00 DEBUG 
====Stripe Version: 4.1.15====
====Start Log====
Redirecting to Stripe Checkout page for order 50266
====End Log====

2019-03-29T11:13:26+00:00 DEBUG 
====Stripe Version: 4.1.15====
====Start Log====
sources/src_******************PFRH
====End Log====

2019-03-29T11:13:27+00:00 DEBUG 
====Stripe Version: 4.1.15====
====Start Log====
Info: Begin processing payment for order 50266 for the amount of 32.94
====End Log====

2019-03-29T11:13:27+00:00 DEBUG 
====Stripe Version: 4.1.15====
====Start Log====
charges request: Array
(
    [currency] => gbp
    [amount] => 3294
    [description] => REMOVED - Order 50266
    [statement_descriptor] => REMOVED
    [capture] => true
    [expand[]] => balance_transaction
    [metadata] => Array
        (
            [customer_name] => REMOVED
            [customer_email] => REMOVED
            [order_id] => 50266
        )

    [source] => src_******************PFRH
)

====End Log====

2019-03-29T11:13:29+00:00 DEBUG 
====Stripe Version: 4.1.15====
====Start Log====
Processing response: stdClass Object
(
    [id] => ch_******************xqda
    [object] => charge
    [amount] => 3294
    [amount_refunded] => 0
    [application] => 
    [application_fee] => 
    [application_fee_amount] => 
    [balance_transaction] => stdClass Object
        (
            [id] => txn_******************O3e1
            [object] => balance_transaction
            [amount] => 3294
            [available_on] => 1554422400
            [created] => 1553858008
            [currency] => gbp
            [description] => REMOVED - Order 50266
            [exchange_rate] => 
            [fee] => 66
            [fee_details] => Array
                (
                    [0] => stdClass Object
                        (
                            [amount] => 66
                            [application] => 
                            [currency] => gbp
                            [description] => Stripe processing fees
                            [type] => stripe_fee
                        )

                )

            [net] => 3228
            [source] => ch_******************xqda
            [status] => pending
            [type] => charge
        )

    [billing_details] => stdClass Object
        (
            [address] => stdClass Object
                (
                    [city] => 
                    [country] => 
                    [line1] => 
                    [line2] => 
                    [postal_code] => 
                    [state] => 
                )

            [email] => 
            [name] => REMOVED
            [phone] => 
        )

    [captured] => 1
    [created] => 1553858008
    [currency] => gbp
    [customer] => 
    [description] => REMOVED - Order 50266
    [destination] => 
    [dispute] => 
    [failure_code] => 
    [failure_message] => 
    [fraud_details] => stdClass Object
        (
        )

    [invoice] => 
    [livemode] => 1
    [metadata] => stdClass Object
        (
            [customer_name] => REMOVED
            [customer_email] => REMOVED
            [order_id] => 50266
        )

    [on_behalf_of] => 
    [order] => 
    [outcome] => stdClass Object
        (
            [network_status] => approved_by_network
            [reason] => 
            [risk_level] => normal
            [seller_message] => Payment complete.
            [type] => authorized
        )

    [paid] => 1
    [payment_intent] => 
    [payment_method_details] => stdClass Object
        (
            [card] => stdClass Object
                (
                    [brand] => visa
                    [checks] => stdClass Object
                        (
                            [address_line1_check] => 
                            [address_postal_code_check] => 
                            [cvc_check] => pass
                        )

                    [country] => GB
                    [exp_month] => REMOVED
                    [exp_year] => REMOVED
                    [fingerprint] => ***********fba
                    [funding] => debit
                    [last4] => REMOVED
                    [three_d_secure] => 
                    [wallet] => 
                )

            [type] => card
        )

    [receipt_email] => 
    [receipt_number] => 
    [receipt_url] => REMOVED
    [refunded] => 
    [refunds] => stdClass Object
        (
            [object] => list
            [data] => Array
                (
                )

            [has_more] => 
            [total_count] => 0
            [url] => /v1/charges/ch_******************xqda/refunds
        )

    [review] => 
    [shipping] => 
    [source] => stdClass Object
        (
            [id] => src_******************PFRH
            [object] => source
            [amount] => 
            [card] => stdClass Object
                (
                    [exp_month] => REMOVED
                    [exp_year] => REMOVED
                    [last4] => REMOVED
                    [country] => GB
                    [brand] => Visa
                    [cvc_check] => pass
                    [funding] => debit
                    [fingerprint] => **********fba
                    [three_d_secure] => optional
                    [name] => 
                    [address_line1_check] => 
                    [address_zip_check] => 
                    [tokenization_method] => 
                    [dynamic_last4] => 
                )

            [client_secret] => src_client_secret_******************uxst
            [created] => 1553858008
            [currency] => 
            [flow] => none
            [livemode] => 1
            [metadata] => stdClass Object
                (
                )

            [owner] => stdClass Object
                (
                    [address] => 
                    [email] => 
                    [name] => REMOVED
                    [phone] => 
                    [verified_address] => 
                    [verified_email] => 
                    [verified_name] => 
                    [verified_phone] => 
                )

            [statement_descriptor] => 
            [status] => consumed
            [type] => card
            [usage] => reusable
        )

    [source_transfer] => 
    [statement_descriptor] => REMOVED
    [status] => succeeded
    [transfer_data] => 
    [transfer_group] => 
)

====End Log====

---

And here's the 2nd charge:

---

2019-03-29T11:14:37+00:00 DEBUG 
====Stripe Version: 4.1.15====
====Start Log====
sources/src_******************MxcA
====End Log====

2019-03-29T11:14:38+00:00 DEBUG 
====Stripe Version: 4.1.15====
====Start Log====
Info: Begin processing payment for order 50266 for the amount of 32.94
====End Log====

2019-03-29T11:14:38+00:00 DEBUG 
====Stripe Version: 4.1.15====
====Start Log====
charges request: Array
(
    [currency] => gbp
    [amount] => 3294
    [description] => REMOVED - Order 50266
    [statement_descriptor] => REMOVED
    [capture] => true
    [expand[]] => balance_transaction
    [metadata] => Array
        (
            [customer_name] => REMOVED
            [customer_email] => REMOVED
            [order_id] => 50266
        )

    [source] => src_******************MxcA
)

====End Log====

2019-03-29T11:14:40+00:00 DEBUG 
====Stripe Version: 4.1.15====
====Start Log====
Processing response: stdClass Object
(
    [id] => ch_******************blKi
    [object] => charge
    [amount] => 3294
    [amount_refunded] => 0
    [application] => 
    [application_fee] => 
    [application_fee_amount] => 
    [balance_transaction] => stdClass Object
        (
            [id] => txn_******************giS0
            [object] => balance_transaction
            [amount] => 3294
            [available_on] => 1554422400
            [created] => 1553858078
            [currency] => gbp
            [description] => REMOVED - Order 50266
            [exchange_rate] => 
            [fee] => 66
            [fee_details] => Array
                (
                    [0] => stdClass Object
                        (
                            [amount] => 66
                            [application] => 
                            [currency] => gbp
                            [description] => Stripe processing fees
                            [type] => stripe_fee
                        )

                )

            [net] => 3228
            [source] => ch_******************blKi
            [status] => pending
            [type] => charge
        )

    [billing_details] => stdClass Object
        (
            [address] => stdClass Object
                (
                    [city] => 
                    [country] => 
                    [line1] => 
                    [line2] => 
                    [postal_code] => 
                    [state] => 
                )

            [email] => 
            [name] => REMOVED
            [phone] => 
        )

    [captured] => 1
    [created] => 1553858078
    [currency] => gbp
    [customer] => 
    [description] => REMOVED - Order 50266
    [destination] => 
    [dispute] => 
    [failure_code] => 
    [failure_message] => 
    [fraud_details] => stdClass Object
        (
        )

    [invoice] => 
    [livemode] => 1
    [metadata] => stdClass Object
        (
            [customer_name] => REMOVED
            [customer_email] => REMOVED
            [order_id] => 50266
        )

    [on_behalf_of] => 
    [order] => 
    [outcome] => stdClass Object
        (
            [network_status] => approved_by_network
            [reason] => 
            [risk_level] => normal
            [seller_message] => Payment complete.
            [type] => authorized
        )

    [paid] => 1
    [payment_intent] => 
    [payment_method_details] => stdClass Object
        (
            [card] => stdClass Object
                (
                    [brand] => visa
                    [checks] => stdClass Object
                        (
                            [address_line1_check] => 
                            [address_postal_code_check] => 
                            [cvc_check] => pass
                        )

                    [country] => GB
                    [exp_month] => REMOVED
                    [exp_year] => REMOVED
                    [fingerprint] => *******fba
                    [funding] => debit
                    [last4] => REMOVED
                    [three_d_secure] => 
                    [wallet] => 
                )

            [type] => card
        )

    [receipt_email] => 
    [receipt_number] => 
    [receipt_url] => REMOVED
    [refunded] => 
    [refunds] => stdClass Object
        (
            [object] => list
            [data] => Array
                (
                )

            [has_more] => 
            [total_count] => 0
            [url] => /v1/charges/ch_******************blKi/refunds
        )

    [review] => 
    [shipping] => 
    [source] => stdClass Object
        (
            [id] => src_******************MxcA
            [object] => source
            [amount] => 
            [card] => stdClass Object
                (
                    [exp_month] => REMOVED
                    [exp_year] => REMOVED
                    [last4] => REMOVED
                    [country] => GB
                    [brand] => Visa
                    [cvc_check] => pass
                    [funding] => debit
                    [fingerprint] => ********fba
                    [three_d_secure] => optional
                    [name] => 
                    [address_line1_check] => 
                    [address_zip_check] => 
                    [tokenization_method] => 
                    [dynamic_last4] => 
                )

            [client_secret] => src_client_secret_******************CKeA
            [created] => 1553858079
            [currency] => 
            [flow] => none
            [livemode] => 1
            [metadata] => stdClass Object
                (
                )

            [owner] => stdClass Object
                (
                    [address] => 
                    [email] => 
                    [name] => REMOVED
                    [phone] => 
                    [verified_address] => 
                    [verified_email] => 
                    [verified_name] => 
                    [verified_phone] => 
                )

            [statement_descriptor] => 
            [status] => consumed
            [type] => card
            [usage] => reusable
        )

    [source_transfer] => 
    [statement_descriptor] => REMOVED
    [status] => succeeded
    [transfer_data] => 
    [transfer_group] => 
)

====End Log====

---

I've removed any sensitive customer data and partially-removed IDs. You can see the cards share the same fingerprint, but the charge IDs are different.

One odd thing I did notice is that there was only one instance of `Redirecting to Stripe Checkout page for order 50266` at the start of the log.

Here's a screenshot of our Stripe settings:

![stripe-settings](https://user-images.githubusercontent.com/4732147/55714910-72d10b80-59eb-11e9-9a58-6b860f4de2e1.png)

If there's anything you can suggest I'd hugely appreciate it!

**Comment by 42pe** [comment]
We have the same issue on our site.

**Comment by dougaitken** [comment]
@dmpinder @42pe Can you reach out to us via the [WooCommerce.com ticket form](https://woocommerce.com/my-account/create-a-ticket?broken=primary&select=18627) please? We'll need more details to may need to log in to take a look. 

From my experience, double charges are linked to something else conflicting with the site as there is a method to stop this within the extension so out of the box this shouldn't happen. 

See #489 for some related chatter.

**Comment by dougaitken** [comment]
Closing this issue - please reach out to support if you haven't already so we can help identify what is causing this as it shouldn't happen "out of the box"

**Comment by dougaitken** [comment]
For follow-up, this was indeed an issue and was discussed and fixed via #489
