### ISSUE TITLE
Alert WC < 3.0 users that this is the last version of the extension to support pre-3.0 WooCommerce

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#832]
Related: #828 

Before we can remove 3.0 support, let's release a version that prompts administrators running pre-3.0 versions of WooCommerce that 4.2 this is the last version planned to support pre-3.0 WooCommerce.

**Comment by allendav** [comment]
Let's coordinate this with other plugins. Moving this to 4.3 (at the earliest)

**Comment by dougaitken** [comment]
Related to #855 

When we remove `3.0` support, that will affect this line:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/7427da93d2e124a4374e6f80acb6060dd575f364/includes/payment-methods/class-wc-stripe-payment-request.php#L182

Which, oddly, means that the Payment Request button will move position. 
It will go from:

![https://d.pr/V2l3f4](https://d.pr/V2l3f4+)
Image link: `https://d.pr/V2l3f4`

to this:

![https://cld.wthms.co/23RIPL](https://cld.wthms.co/23RIPL+)
Image link: `https://cld.wthms.co/23RIPL`

**Comment by prethree** [comment]
PLEASE consider to add SCA compatibility to Stripe version 2.6.12 so it works with older versions of Woocommerce. Woocommerce 3 & above is very laggy and slow when a product has many variations, constantly waiting for the Ajax to change the selected options and main preview image (even with the latest PHP version on the server).

Woocommerce 2.3.7 is fast and renders product variation images instantly. So, PLEASE, when you're developing the Stripe Woocommerce plugin ready for September to work with SCA, PLEASE also update Stripe Woocommerce payments plugin 2.6.12 to work with older versions so as not to have to go to the trouble of migrating to another platform like shopify or magento.

**Comment by allendav** [comment]
See also https://github.com/woocommerce/woocommerce-gateway-stripe/issues/828#issuecomment-490667496

**Comment by dechov** [comment]
> the Payment Request button will move position

@dougaitken I think that would only be true if we used the pre-3.0 predicate there, but if we are just removing pre-3.0 compatibility we would actually remove that predicate. I'm not sure which position is better, though the comment above that line refers to the spot after quantity as "the correct position".

Is there reason to think that having it after the button is preferable? (In the meantime, I've opened https://github.com/woocommerce/woocommerce-gateway-stripe/pull/959 to fix the alignment issue when there's no button.)

**Comment by dougaitken** [comment]
@dechov 

> Is there reason to think that having it after the button is preferable?

Honestly, no. Only that this has been the situation since Payment Request buttons came into play. 

Ideally, I like the layout of my second screenshot as the flow looks better so I'd prefer that with the quantity and add to cart button, _then_ the seperator _then_ the Payment Request button, but I'm unsure how this will be handled with other themes if they have styles to handle Payment Request buttons.
