### ISSUE TITLE
no 3d secure?

### ISSUE THREAD

**Issue by JohnJohn201** [woocommerce/woocommerce-gateway-stripe#839]
Hi, 

Im not sure if this is the right place for this but I need help. We nearly got caught for two fraudulent transactions over the past week totalling over €1000. Luckily we realised they were fraudulent before we shipped the items. 

I have just checked and 3d secure is no longer working and by the looks of it hasn't worked for a few months. 

Whats going on with it, stripe said things have changed on their end. It does not even try to redirect to the 3d secure page any more

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by JohnJohn201** [comment]
Update: Speaking to stripe again and they have advised using stripe connect, although this isn't an option for me with limited coding knowledge anyone have any idea what's going on here??

**Comment by allendav** [comment]
Hi @JohnJohn201 - sorry you're having trouble. I have a few questions that should help you help us.

Can you tell us more precisely when 3D Secure worked for you last?
Do you have the "Enable 3D Secure" setting checked in wp-admin > WooCommerce > Settings > Payments > ( Stripe https://docs.woocommerce.com/document/stripe/#section-2 )
What is the exact version of the Stripe extension that you are using now?
What is the exact version of WooCommerce that you are using now?
What theme are you using?

**Comment by JohnJohn201** [comment]
> Hi @JohnJohn201 - sorry you're having trouble. I have a few questions that should help you help us.
> 
> * Can you tell us more precisely when 3D Secure worked for you last?
> * Do you have the "Enable 3D Secure" setting checked in wp-admin > WooCommerce > Settings > Payments > ( Stripe https://docs.woocommerce.com/document/stripe/#section-2 )
> * Are you using Stripe (Modal) Checkout? That is also on that same settings page. You may want to try disabling it if you are and see if that helps.
> * What is the exact version of the Stripe extension that you are using now?
> * What is the exact version of WooCommerce that you are using now?
> * What theme are you using?

**Comment by JohnJohn201** [comment]
Hi @allendav, thanks for getting back to me, I know this is probably outside the scope of this forum. Answers below

> * Can you tell us more precisely when 3D Secure worked for you last?
This is tough to answer but definitely not in the last 60 days, and according to stripe it has not worked in months.

> * Do you have the "Enable 3D Secure" setting checked in wp-admin > WooCommerce > Settings > Payments > ( Stripe https://docs.woocommerce.com/document/stripe/#section-2 )
Yes

> * Are you using Stripe (Modal) Checkout? That is also on that same settings page. You may want to try disabling it if you are and see if that helps.
No, i initially found that the model did not triger a 3dsecure request, so i have always used the Inline Credit Card Form option which did. 

> * What is the exact version of the Stripe extension that you are using now?
Version 4.1.15

> * What is the exact version of WooCommerce that you are using now?
Version 3.5.7

> * What theme are you using?
Have been using this theme from the start with no issuses https://themeforest.net/item/robin-a-furniture-woocommerce-wordpress-theme/20045842

**Comment by JohnJohn201** [comment]
Just an update to this. Its happening across multiple with multiple themes. The 3d secure payment we processed on one site was April 07 2018 and on another site May 5th 2018. If I put the gateway in test mode and use one of stripes 3d secure test cards I don't get redirected to a 3d secure password box but when I go back to the stripe dashboard it says the test order was processed through 3d secure. 

Anyone have any ideas on this?

**Comment by JohnJohn201** [comment]
Also, API version is 2018-02-28 (DEFAULT) Do I just need to update to the 2019-03-14 (LATEST)? If that's the case I'm going to hang my head in shame :(

**Comment by JohnJohn201** [comment]
Ok so it's not the API'S that were an issue, the issue persists after the update. Does anyone have any ideas?

**Comment by dougaitken** [comment]
Hey @JohnJohn201 - I'd love to dive into this with you but GitHub isn't the best place for support - can you head over here and either create a ticket or open chat with us please [via this link](https://woocommerce.com/my-account/create-a-ticket/?broken=primary&select=18627)?

Thanks!

**Comment by JohnJohn201** [comment]
> Hey @JohnJohn201 - I'd love to dive into this with you but GitHub isn't the best place for support - can you head over here and either create a ticket or open chat with us please [via this link](https://woocommerce.com/my-account/create-a-ticket/?broken=primary&select=18627)?
> 
> Thanks!

Hey @dougaitken I have a ticket open there if you want to pick up on it Ticket: #1957353

**Comment by dougaitken** [comment]
👍 I'm on that one right now so I'll close this and we'll continue there!
