### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce-gateway-stripe#85]
#### What I expected
To be able to temporarily deactivate WooCommerce and not have my site whitescreen

#### What happened instead
With the Stripe payment gateway active and WooCommerce deactivated a fatal error is thrown

#### Steps to reproduce the issue
1. Stripe gateway extension is activated
2. WooCommerce is not active
3. Something similar to `PHP Fatal error:  Uncaught Error: Call to undefined function WC() in /srv/www/storefront/wp-content/plugins/woocommerce-gateway-stripe/woocommerce-gateway-stripe.php:227`

@roykho 

PR to follow

-------------------

- [x ] Issue assigned to next milestone.
- [ x] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
@WillBrubaker - so I am not able to replicate this issue. I have both WC and Stripe enabled and then I went and deactivated WC and I don't get any fatal errors. I see this ![](http://cld.wthms.co/1f4nE/3j6amYXT+)

**Comment by WillBrubaker** [comment]
There's something weird with my test environment - will re-open if I can identify what that might be - I get the same result as you on a different test environment @roykho
