### ISSUE TITLE
SCA: Stalled checkout after 3D Secure verification when charge uncaptured

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-gateway-stripe#850]
In `sca/master` branch, with "Capture charge immediately" unchecked in the settings, the **3D secure flow does not complete after processing the payment**, leaving the order with "Pending payment" status and the customer in an endless loading state. A subsequent checkout with the same cart triggers the success of the original checkout.

- Check out using a test card [[#](https://stripe.com/docs/testing#three-ds-cards)] requiring 3D secure (1 or 2)
- "Authorize test payment" from within the modal
- Observe stalled Checkout screen (i.e. no further update) after modal closes and "Payment pending" status for new order, despite uncaptured payment appearing on Stripe's end
- Without updating cart, check out again
- Observe "On hold" status for same order and no new order

The latter seems to occur **with any payment method** – when using any Stripe card, the "thank you" screen appears, but when using "Check payments", the Checkout screen is just stalled again.

**Comment by DanReyLop** [comment]
This issue is fixed by this commit: https://github.com/woocommerce/woocommerce-gateway-stripe/commit/604c4a8b239ff6e71df83532dcff5cc7b83e72e3
