### ISSUE TITLE
Webhook event from auth cancellation triggers extra order note

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-gateway-stripe#852]
When an authorization is cancelled via the Edit Order screen and the corresponding `charge.refunded` webhook notification comes in, it shows a misleading "Pre-Authorization Released via Stripe Dashboard" order note:

<img width="300" src="https://user-images.githubusercontent.com/1867547/56626601-58647800-6610-11e9-9c5b-24e13a7d244f.png">

(This was fixed for refunds in https://github.com/woocommerce/woocommerce-gateway-stripe/commit/165cb36c6eadfb7454a55d37a3f5023814fd18c1.)

**Comment by wjrosa** [comment]
This was fixed by https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1481. Closing this
