### ISSUE TITLE
Partial refund of uncaptured charge leads to inconsistent state

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-gateway-stripe#853]
A _partial_ refund of an _uncaptured_ charge – not possible with the Stripe API (or Dashboard) – shows a partial refund and keeps the "On hold" status in the WooCommerce order, while in fact cancelling the (entire) authorization.

Should / could the "Refund amount" be disabled for uncaptured orders?

**Comment by v18** [comment]
Fixed in #1481 for the portion related to the Stripe gateway. There will likely be a WC Core ticket opened for this at some point for a larger-picture change.
