### ISSUE TITLE
Enabling Payment Request button changes position of Add to cart button

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#855]
#### Affected ticket(s)

Forum post - https://wordpress.org/support/topic/apple-pay-button-is-pushing-down-into-cart-button

#### What I expected

Enabling the Payment Request buttons doesn't majorly alter the product page layout whether the Payment Request button is shown or whether hidden on unsupported browser

#### What happened instead

When active, the Payment Request button will be shown, then an "OR" space is show, and Add to cart is below this.
This is more prominent when viewing in an unsupported browser, i.e. Firefox:

![https://cld.wthms.co/T6Cs4a](https://cld.wthms.co/T6Cs4a+)
Image link: `https://cld.wthms.co/T6Cs4a`
![https://cld.wthms.co/CZQwv1](https://cld.wthms.co/CZQwv1+)
Image link: `https://cld.wthms.co/CZQwv1`

Notice the Add to cart button moves from the right of the quantity input box to below it.

As mentioned in the linked forum post:
> The div with the ID “wc-stripe-payment-request-wrapper” is always rendered in the DOM (also when Apple-Pay is not available) and causes the “Add-to-cart” Button to break. (==> CSS Rule: display:block

Ideally the "Add to cart" would be moved above the wrapper div? 

#### Steps to reproduce the issue

* Enable the Payment Request buttons on **WooCommerce > Settings > Payments > Stripe** `/wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe`
* View a Product Page using a supporte browser with a saved payment method
* View a Product Page on an unsupported browser
* Note same layout as in screenshots

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by lelas** [comment]
This affects a lot of sites who resorts to disabling the Payment Request button entirely = lower conversion rates = lower fee revenue for Stripe. Or spends quite a bit of time trying to fix the issue. Hoping this get prioritised soon.

Other than fixing this, an option to disable on product and cart pages (individually) would be very useful. It's often not ideal to encourage visitors to check out before they reach the cart.

**Comment by dsgolfside** [comment]
been wasting a lot of time trying to figure out why my add to cart button in elementor is broken ....narrowed down to this plugin and like mentioned the apple pay option enabled....if i disable that option button is ok again ...please advise on how to fix and still use apple pay? also it does make sense to only have apple pay button on checkout page yes?

**Comment by dougaitken** [comment]
Hi @dsgolfside 

Are you up to date with your theme and such? This change was part of the 4.2.4 release back in September. 

> been wasting a lot of time trying to figure out why my add to cart button in elementor is broken ....narrowed down to this plugin and like mentioned the apple pay option enabled....if i disable that option button is ok again

This sounds like a conflict related to Elementor so I'd recommend speaking to the team there as I've not heard of similar.

>  also it does make sense to only have apple pay button on checkout page yes?

The Payment Request buttons offer a quick checkout solution and if a customer does not want to use them on the product page or cart page then having it on the Checkout page is redundant.

You can add this back with a snippet - https://gist.github.com/dougaitken/4a2e9469dee1ed2a6e67ab3fbb947b3b
