### ISSUE TITLE
Create/Update a doc advising merchants how they can style Stripe Elements (embedded) fields

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#857]
To help users migrating from the style-able modal we are removing in 4.2.0, we should publish guidance on how they can customize the embedded fields.

e.g. perhaps a peer doc to https://docs.woocommerce.com/document/stripe/modal-checkout/ linked from the main stripe doc at https://docs.woocommerce.com/document/stripe/

**Comment by allendav** [comment]
Per https://stripe.com/docs/stripe-js/elements/quickstart#create-form Stripe supports two ways to style the fields:

1) elements.create accepts an object with style details to be constructed and passed into Stripe Elements. See https://stripe.com/docs/stripe-js/reference#stripe-elements.

2) Supply custom CSS to the container DOM element.

The latter is what we want to focus on supporting here via a doc / guide.

**Comment by dechov** [comment]
This could be useful for theme authors but I believe styling the checkout form is something we don't recommend to merchants – see [this doc section](https://docs.woocommerce.com/document/stripe/#section-45), linked from an admin notice within the plugin. (See also https://github.com/woocommerce/woocommerce-gateway-stripe/issues/702.)

**Comment by RadoslavGeorgiev** [comment]
@dechov, AFAICT the point of removing the styles from our extension is to allow theme authors _and_ merchants to style Stripe's Elements. If @allendav also means theme authors by "merchants", this doc would make sense.

> styling the checkout form is something we don't recommend to merchants

Is there a mention of this somewhere? Maybe you have more context than me, but I do not see us recommending merchants to avoid styling the form anywhere.

**Comment by allendav** [comment]
Ah. This (allowing merchants to style) was suggested, IIRC, by Stripe as a way of easing legacy modal users to using the embedded fields.

**Comment by RadoslavGeorgiev** [comment]
Just added the `[Status] Needs Review` label because the article is waiting for a review by @californiakat. I'll post an update here once the article is online.

**Comment by californiakat** [comment]
The delay is my fault. Radoslav gave me the doc on 10 May. It'll be done tonight or tomorrow latest.

**Comment by californiakat** [comment]
Your docs is published https://docs.woocommerce.com/document/stripe-styling-fields/

Great work! 🥇

**Comment by dechov** [comment]
@RadoslavGeorgiev Sorry, overlooked the ping that was during my AFK.

> Is there a mention of this somewhere? Maybe you have more context than me, but I do not see us recommending merchants to avoid styling the form anywhere.

I doubt I have much more context 😄 – I believe I was just referring to a line in that doc section:

> However, this is not recommended. It is best to remove any custom styles you or your theme author has applied for Stripe and let the core theme handle the styling.

**Comment by californiakat** [comment]
@dechov My understanding is we're saying conflicting things now about custom styling. Is there a way to make this right? Is it not ok with previous versions of Stripe and now ok with 4.2? 

4.1.14 https://docs.woocommerce.com/document/stripe/#section-45
Modal disabled https://docs.woocommerce.com/document/stripe/modal-checkout/
4.2 Styling credit card fields https://docs.woocommerce.com/document/stripe-styling-fields/

cc: @roykho @allendav

**Comment by roykho** [comment]
So the styling we removed here https://docs.woocommerce.com/document/stripe/#section-45 is more about the alignment of the fields and payment icons rather than the styling of the input element itself. If that helps clarify anything.

**Comment by dougaitken** [comment]
I feel we can remove section 45 and make this section a link to that styling doc page? 

We can also upload the gist with the @woogists account.

**Comment by RadoslavGeorgiev** [comment]
@dougaitken maybe just add "If you are a theme author, __this doc__ contains instructions on how to style your fields"?

**Comment by allendav** [comment]
I agree. Let's move that section (Stripe Version 4.1.14) and instead link to the styling doc using the text @RadoslavGeorgiev  has proposed? Sound good to you @californiakat  ?

**Comment by dougaitken** [comment]
I'm working on the Stripe doc in lieu of Kat, @allendav. I'll do that this week

**Comment by allendav** [comment]
Moving this to 4.2.2

**Comment by allendav** [comment]
@dougaitken - any updates? Moving this out of the milestone since it doesn't involve code changes in the plugin at this point

**Comment by dougaitken** [comment]
Happy to have this ready for 4.2.4 or would 4.3 be better? Most of the styling docs are live but the structure of the docs is the main thing to tidy up now so other work pending, this can be wrapped up in the next week.

**Comment by allendav** [comment]
@dougaitken 4.3 is fine

**Comment by v18** [comment]
@dougaitken hey wanted to follow up here - is there anything else we need to do to for the docs to be considered compelte?

**Comment by dougaitken** [comment]
Yes, let's close this one off. If there are new changes, reach out to the Docs Guild, otherwise we're good for now.
