### ISSUE TITLE
Evaluate and possibly update tar dependency

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#863]
https://github.com/woocommerce/woocommerce-gateway-stripe/network/alert/package-lock.json/tar/open

**Comment by RadoslavGeorgiev** [comment]
The packages `node-pre-gyp` and `node-gyp` require older versions of `tar`, however none of them have been updated yet.

Since this vulnerability only concerns local development, but none of the distributed files, I am moving this issue to the 4.3.0 milestone.

**Comment by v18** [comment]
There is no longer an open alert for this, so closing the issue.
