### ISSUE TITLE
Stripe Gateway Checkout Form - Place Order Button Disappear 2019 May 10

### ISSUE THREAD

**Issue by cgrwllc** [woocommerce/woocommerce-gateway-stripe#865]
#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [x] Issue assigned a priority (will be assessed by maintainers).

Hello, 

I have issue, 

Place Order Button Is disappeared after the wordpress was updated to the latest version, check image below http://prntscr.com/nn28uz,

**Comment by cgrwllc** [comment]
I have issue,

Place Order Button Is disappeared after the wordpress was updated to the latest version, check image below http://prntscr.com/nn28uz,

**Comment by dougaitken** [comment]
Hey @cgrwllc  - GitHub isn't the place for support, but let's see what we can do.

How odd, the button is literally missing from the page. Can you first check your theme is updated and all other plugins are updated, please? 

If you are still seeing the issue, can you open a ticket with WooCommerce.com Support, please including your full [Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/). You can open a ticket directly here - https://woocommerce.com/my-account/create-a-ticket/
