### ISSUE TITLE
Statement Descriptor is being prepended instead of overriding

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce-gateway-stripe#872]
Originally reported in https://wordpress.org/support/topic/statement-descriptor-2/

#### What I expected

When I fill in Statement Descriptor in WooCommerce > Settings > Stripe, I expect this descriptor to appear in Stripe transactions.

#### What happened instead

When I fill in Statement Descriptor in WooCommerce > Settings > Stripe, this descriptor is being prepended to Statement Descriptor from https://dashboard.stripe.com/account

#### Steps to reproduce the issue

Statement Descriptor in WooCommerce > Settings > Stripe:

![https://cld.wthms.co/30NhWR](https://cld.wthms.co/30NhWR+) 
Full Size: https://cld.wthms.co/30NhWR

Statement Descriptor from https://dashboard.stripe.com/account:

![https://cld.wthms.co/LNXQZX](https://cld.wthms.co/LNXQZX+) 
Full Size: https://cld.wthms.co/LNXQZX

Transaction:

![https://cld.wthms.co/olRudF](https://cld.wthms.co/olRudF+) 
Full Size: https://cld.wthms.co/olRudF

It turned out that it worked differently a few months back. This is @dougaitken's test transaction dated March 12:

![https://cld.wthms.co/2WKdpj](https://cld.wthms.co/2WKdpj+) 
Full Size: https://cld.wthms.co/2WKdpj

Here, it uses only Statement Descriptor from plugin's settings. Was the change in behavior introduced by this entry?

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/a7de1f4cb701dc4c6d7b0a1301fb90e2acc256f1/changelog.txt#L13

Looking at the plugin's code looks like both are appended on Stripe's end. Is this something that can be changed still?

The solution is not perfect for store owners who have several sites connected to their Stripe account.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by superdav42** [comment]
Not sure if it's something stripe changed but appending is what they are doing now. Read the doc for more details: https://stripe.com/docs/connect/statement-descriptors
Looks like we could have more control with [statement_descriptor_prefix](https://stripe.com/docs/api/accounts/object#account_object-settings-card_payments-statement_descriptor_prefix):
You could add a filter which should remove the prefix and just used the defined descriptor from the settings:
```php
add_filter( 'wc_stripe_generate_payment_request',
function( $post_data ) {
    $post_data['statement_descriptor_prefix'] = ''; // Or something short like 'WC'
}
```

**Comment by dougaitken** [comment]
FWIW, my bank shows "Dougs testi" on the statement which is shorter than the 22 characters we say are allowed. 

Then within that charge, I see the full `DOUGPRESS* DOUGSTESTI` descriptor.

FWIW - `dougpress` is from my Stripe.com account details. `dougs testi` is from Stripe settings in WooCommerce.

**Comment by travisanderson99** [comment]
I reached out to Stripe support regarding this issue and they said the following:

“Looking into the statement descriptor I can see we cannot completely override it. If you try to override the statement descriptor it will add what is in the dashboard first and then add the additional text. Since we cannot override it completely to not include what is in the dashboard I will submit feedback to our engineer team to see if we can get this updated for us.”

**Comment by treibalen** [comment]
Thank you for your input, @travisanderson99! So it looks like something to be looked at Stripe's end and they are aware of it already.

**Comment by dougaitken** [comment]
Found this looking for something else - it looks like this is due to an API update which is later than the one currently used in the extension:

`https://stripe.com/docs/upgrades#2019-02-19`
```Statement descriptor behaviors for card payments created via /v1/charges have changed. See our statement descriptor guide for details.```

Marking as a bug as the functionality of the extension has changed due to this

**Comment by stefankroesbergen** [comment]
Hi, not sure if this is the correct string, but I'm experiencing that my personal information is shown after the checkout redirects to sofort or ideal. It says "personal name" on behalf of "company name". And on the bank statement customers only see my personal name and not the company name. All statement descriptions in Woocommerce and Stripe are set to the company name. Does someone have an idea how to solve this issue? 
All help would be much appreciated!

Best Stefan

**Comment by dougaitken** [comment]
Hey @stefankroesbergen - can I ask you to reach out to Stripe.com directly about this, please?

**Comment by tijosh** [comment]
@dougaitken @treibalen are you still able to reproduce this issue? I'm not able to replicate on my end.

![Screenshot](https://d.pr/i/Ns0Oqu+)
*Link: https://d.pr/i/Ns0Oqu*

![Screenshot](https://d.pr/i/HaGSlb+)
*Link: https://d.pr/i/HaGSlb*

**Comment by dougaitken** [comment]
Yes @tijosh thanks for replying - I can confirm that the statement descriptor added in the Stripe payment gateway settings is the only one shown on the payment page on Stripe.com.

Want to close this one if you see the same @treibalen?

**Comment by treibalen** [comment]
Yep, I see only the statement description text from the plugin's settings on Stripe.com now. Closing it.

Thanks @dougaitken and @tijosh 🙌
