### ISSUE TITLE
Suggestion: Add WeChat as Payment Option to Stripe Plugin

### ISSUE THREAD

**Issue by juliankauai** [woocommerce/woocommerce-gateway-stripe#873]
Stripe now offers WeChat as a payment option.

China has a huge population that uses WeChat to pay. Therefore it would be a good payment option to add in the woocommerce-gateway-stripe.

Thanks for a great plugin.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by dougaitken** [comment]
Hi @juliankauai 

WeChat is still in Public Beta so when it is a full release, we will include it - `https://stripe.com/docs/sources/wechat-pay`

Related: #351

**Comment by chestnutbak** [comment]
WeChat has been out of Public Beta for quite a while now and should be added to the plugin ASAP to support the community in China
