### ISSUE TITLE
Intent verification errors not properly displayed after Payment Request

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce-gateway-stripe#879]
When checking out via Payment Request Button from the Checkout screen (available using a filter [[doc](https://docs.woocommerce.com/document/stripe/#section-23)]) using a 3D Secure card, and when the verification fails, an error shows up in the payment method section below (below the form or a saved card).

Edit. i.e. here:

<img width="796" alt="Screen Shot 2020-12-07 at 3 03 56 PM" src="https://user-images.githubusercontent.com/1595739/101415858-793d1800-389d-11eb-93cb-63ed35507f19.png">

From the Cart or Single Product screen, the **error doesn't show at all** (other than in the JS console).

Tested with Chrome using card `4000000000003063` in test mode.

Note – before PaymentIntents, the flow would redirect back to Checkout with an error on top:

<img width="821" alt="Screen Shot 2019-05-30 at 7 18 43 PM" src="https://user-images.githubusercontent.com/1867547/58671220-ca1a9a80-830f-11e9-8036-4d36ec9cfb1d.png">

**Comment by allendav** [comment]
Is this still a bug @dechov  ?
