### ISSUE TITLE
Payments Intent (SCA) causes CSRF validation failure when creating user accounts on checkout

### ISSUE THREAD

**Issue by edwardkay** [woocommerce/woocommerce-gateway-stripe#882]
#### What I expected

To successfully complete checkout with an SCA-enabled test card and with user account creation enabled.

#### What happened instead

Order initially fails with "Payment verification error: CSRF verification failed." (but succeeds on a second attempt).

![Checkout – woo](https://user-images.githubusercontent.com/299935/59048528-ea050d80-887d-11e9-94ac-1a35c4e4bf7a.png)

#### Steps to reproduce the issue

1. Create new WordPress instance (5.2.1); fresh installs of latest WooCommerce (3.6.4) and WooCommerce Stripe gateway (4.2.0)
1. Create a product; connect to Stripe in test mode.
1. WooCommerce settings: tick 'Allow customers to create an account during checkout'
1. As an anonymous user, go to buy the product and **tick 'create an account' on the checkout page**.
1. Use the SCA test card for payment: 4000000000003220
1. Place order.
1. When the SCA pop-up appears, authorise the payment.
1. Order fails with error: **Payment verification error: CSRF verification failed**.

If you try the order again (reenter the same SCA card details) it succeeds.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by kevinbrown041** [comment]
I have the same problem.

**Comment by jkirk26** [comment]
I am getting the same problem too, though I am going to try switching off  'create an account' on the checkout page for now, and see if that stops people from submitting there order 2 or more times!
