### ISSUE TITLE
Ugandan Shilling (UGX) is a zero decimal currency

### ISSUE THREAD

**Issue by jpknz** [woocommerce/woocommerce-gateway-stripe#883]
#### What I expected

UGX to be returned as a zero decimal currency.

#### What happened instead

UGX is not returned as a zero decimal currency.

See https://stripe.com/docs/currencies#presentment-currencies which shows UGX as a zero decimal currency.
class-wc-stripe-helper.php has the function `no_decimal_currencies()` which does not list UGX as a zero decimal currency. To fix this code needs to be updated to include ugx as below.

```
public static function no_decimal_currencies() {
		return array(
			'bif', // Burundian Franc
			'djf', // Djiboutian Franc
			'jpy', // Japanese Yen
			'krw', // South Korean Won
			'pyg', // Paraguayan Guaraní
			'vnd', // Vietnamese Đồng
			'xaf', // Central African Cfa Franc
			'xpf', // Cfp Franc
			'clp', // Chilean Peso
			'gnf', // Guinean Franc
			'kmf', // Comorian Franc
			'mga', // Malagasy Ariary
			'rwf', // Rwandan Franc
			'vuv', // Vanuatu Vatu
			'xof', // West African Cfa Franc
			'ugx', // Ugandan Shilling
		);
	}
```

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by hackerkid** [comment]
The docs also says this

> The Ugandan Shilling (UGX) was a decimal-based currency but is now effectively a zero-decimal currency. To maintain backwards compatibility, amounts must be passed in with two decimals (e.g., to charge 5 UGX, provide an amount value of 500) and be evenly divisible by 100 (e.g., an amount value of 499 is not allowed).

https://stripe.com/docs/currencies#special-cases

So probably worth double checking whether including `UGX` in `no_decimal_currencies` is the right way.
