### ISSUE TITLE
Adding shipping details via `wc_stripe_generate_payment_request` filter no longer works after 4.2.0

### ISSUE THREAD

**Issue by indextwo** [woocommerce/woocommerce-gateway-stripe#884]
#### What I expected

Prior to v4.2.0 I had a filter on `wc_stripe_generate_payment_request` to add the order's shipping address to the Stripe request, as it was used by the client's Radar rules:

	function vnmWooExtend_stripeExtension_addShippingInfo($post_data, $order, $prepared_source) {
		
		$post_data['shipping'] = array(
			'name'		=> $order->get_shipping_first_name() . ' ' . $order->get_shipping_last_name(),
			'address'	=> array(
				'line1'			=> $order->get_shipping_address_1(),
				'line2'			=> $order->get_shipping_address_2(),
				'state'			=> $order->get_shipping_state(),
				'city'			=> $order->get_shipping_city(),
				'postal_code'	=> $order->get_shipping_postcode(),
				'country'		=> $order->get_shipping_country(),
			),
		);
		
		error_log(print_r($post_data, true) . "\n", 3, dirname(__FILE__) . '/stripe-post-data.log');
		
		return $post_data;
	}

	add_filter('wc_stripe_generate_payment_request', 'vnmWooExtend_stripeExtension_addShippingInfo', 20, 3);

This worked as expected in Stripe gateway < 4.2.0.

#### What happened instead

After the update, this filter still runs and logging the result shows that it is adding the Shipping details, but they're not showing up in Stripe.

#### Steps to reproduce the issue

Add the filter as above; updated `$post_data` array will be logged, but won't be passed through to Stripe.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by indextwo** [comment]
**SOLVED.**

I have another site where I was filtering `wc_stripe_generate_payment_request` to add an `application_fee` and that was also failing. As a test, I decided to add a line of meta-data:

	$post_data['application_fee'] = $applicationFee;
	$post_data['metadata']['test_response'] = 'Trying to see if meta data will go through, but assuming not.';

For whatever reason, the `metadata` went through, _but the `application_fee` did not_. I solved this by instead hooking into `woocommerce_stripe_request_body`:

	add_filter( 'woocommerce_stripe_request_body', 'add_application_fee', 20, 2 );

	function add_application_fee( $request, $api ) {
		
		//	Try to retrieve the order ID from the metadata
		
		$orderID = $request['metadata']['order_id'];
		$order = wc_get_order($orderID);
		
		//	This filter is hit multiple times, so the order ID might not be available. If not, just return the request.
		
		if (!$order) {
			return $request;
		}
		
		//	This is a custom filter that returns a fee based on the order total. 
		
		$applicationFee = (int)apply_filters('vnm_wc_stripe_connect_application_fee', $order, $request);
		//	$applicationFee = 25;	//	<- Use this for testing
		
		if ($applicationFee > 0) {
			$request['application_fee_amount'] = $applicationFee;
		}
		
		return $request;
	}

Remember that for any of this to work, you also need to be enqueuing a modified version of the `stripe.js` file to pass the destination `stripeAccount`, as per ticket #791

**Comment by grahamsmith** [comment]
I have checked out the repo and I think I have located where the potential issue is. I was going to open a new issue but then found this closed one as the work around is not ideal.

```
$full_request = $this->generate_payment_request( $order, $prepared_source );

//the following code ignores any additional fields created by the filter used on the last line of the generate_payment_request() method.

		$request = array(
			'source'               => $prepared_source->source,
			'amount'               => WC_Stripe_Helper::get_stripe_amount( $order->get_total() ),
			'currency'             => strtolower( WC_Stripe_Helper::is_wc_lt( '3.0' ) ? $order->get_order_currency() : $order->get_currency() ),
			'description'          => $full_request['description'],
			'metadata'             => $full_request['metadata'],
			'statement_descriptor' => $full_request['statement_descriptor'],
			'capture_method'       => ( 'true' === $full_request['capture'] ) ? 'automatic' : 'manual',
			'payment_method_types' => array(
				'card',
			),
		);
```

I *think* the filters extra values are ignored when the new new request object is created. I could file a PR for this but am unsure if attaching the extra values from the filter to the new request will cause any issues.

@mikejolley @roykho - would you like a new issue for this or is there a preference to limit issues to a minimum and we can reopen here?
