### ISSUE TITLE
Unable to remove "Via WooCommerce" via snippet in functions.php but can via Code Snippets

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce-gateway-stripe#888]
#### Affected ticket(s)

https://wordpress.org/support/topic/remove-via-woocommerce-from-apple-pay/

#### What I expected

Being able to remove the `via WooCommerce` which appears on the Apple Pay dialog

#### What happened instead

Using a snippet in `functions.phps` now no longer works.

However, if the snippet is added using the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin, this work. As confirmed by @madeincosmos 

Snippet from #307 

https://gist.github.com/madeincosmos/4e9c047c8433bccce931f0facb4dbe41 

#### Steps to reproduce the issue

* Open `functions.php` from your child theme
* Paste code snippet and save
* Reload Apple Pay to see that `via WooCommerce` still shows
* Delete from `functions.php`
* Add Code Snippet plugin
* Add new snippet and save
* Reload Apple Pay and see that `via WooCommerce` has been removed

Interestingly, if I keep the snippet in both functions.php and Code Snippet, I get a Fatal Error so the snippet is being seen in `functions.php` but it's not working.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by v18** [comment]
Going to close as 'wontfix' for now - since it works in the Code Snippets plugin.
