### ISSUE TITLE
Duplicate processing notes/duplicate emails around payment intent related webhooks

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#889]
#### Affected ticket(s)

2094750-zen

#### Description

From @WillBrubaker 👍 

> I have checked it also in a staging system and the error still occurs there. Now I have take a look at the source code of the plugin and think I found the problem:

>In the file includes/class-wc-stripe-webhook-handler.php (on line 604) the method process_payment_intent_success has been added. This method is called by the Stripe webhook on the payment_intent.succeeded notification (see line 692).

> The method process_payment_intent_success only returns in case of order status "pending" or "failed" (line 619). Otherwise the method process_response will be called. At this point, however, process_response has already been called by the regular payment processing and the order has already the status "completed" when called via the webhook.

> On line 619 there should also be a return in order of order status "completed" or (I think) "on-hold". Or - I’m not sure - the notification payment_intent.succeeded should be completely ignored like in the previous versions of the plugin.

> If you test it on your system, make sure that payment_intent.succeeded is activated on the Stripe webhook detail panel:

![E3a7e_yg](https://user-images.githubusercontent.com/11487924/59292872-e4c40c00-8c4b-11e9-873e-96997b0654ff.png)

> After completing the payment you should see the notification on the Stripe webhook log:

![XLZeS3fA](https://user-images.githubusercontent.com/11487924/59292877-e68dcf80-8c4b-11e9-9071-8f5074b93e92.png)

Possibly related: #882

**Comment by MANOJMANI07** [comment]
A similar issue is happening with both refund and completed order. Duplicate processing notes/duplicate email for the order has been sent after the latest update v4.2. A possible related issue with the refund: #838.

**Comment by lanzalf** [comment]
I can confirm that my system is sending duplicate new order emails to myself and to my customers when they are paying via Stripe. No duplicate emails are being sent when paying with PayPal.

**Comment by bgf2** [comment]
same issue, woocom is sending duplicate order emails to my notification.

**Comment by tecguru** [comment]
I am having this same issue after upgrading from 4.1.16 to 4.2.0

**Comment by tecguru** [comment]
It isn't happening on every order, but it is happening very often.

**Comment by erick3000** [comment]
Hi there, i opened a support request on forum but now here.

Same problem i can confirm that does not happen with paypal orders.

Also i will add this. Comparing orders to before latest stripe update

- orders made before update or bug
https://i.imgur.com/0x9oRFU.png

- orders made AFTER update or bug
https://i.imgur.com/8rRwtoh.png

- Paypal order for reference
https://i.imgur.com/8H0irEr.png


i believe some how
"Order status changed from Pending payment to Processing." and "Stripe charge complete" its been sent twice to woocommerce perhabs the duplicate emails

**Comment by tecguru** [comment]
-#-#- Please reply above this line -#-#-

Dear woocommerce/woocommerce-gateway-stripe,

We have received your request and someone will be looking at it shortly. We are committed to resolving every ticket as promptly as possible, and we encourage you to let us know if you have any additional concerns or questions by replying to this email. You will receive an email when any action has been taken on your ticket.
---------------------------------------------------------------

Ticket Details
Ticket #: 24102
Subject: Re: [woocommerce/woocommerce-gateway-stripe] Duplicate processing notes/duplicate emails around payment intent related webhooks (#889)
Status: Open

---------------------------------------------------------------

Staff - 12/31/1969 7:00 PM

Attachments
---------------------------------------------------------------
You can review the ticket by going to:
https://support.tecguru.co/en/tickets/view/24102?token=fd637120c67a7a5fb5aa49c3f78779c0e22c5321
Blessings,
TecGuru

Self-Hosted Help Desk Software by [SupportPal](http://www.supportpal.com)

**Comment by RadoslavGeorgiev** [comment]
To everyone who is participating in the issue and is experiencing this issue: We believe that the solution is already available in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/890.

Until we release `4.2.1` you could download the [ZIP file](https://github.com/woocommerce/woocommerce-gateway-stripe/archive/fix/sca-duplicate-actions.zip) containing the changes. Please report here whether this fixes the issue for you, or you are still experiencing it.

**Comment by tecguru** [comment]
-#-#- Please reply above this line -#-#-

Dear woocommerce/woocommerce-gateway-stripe,

We have received your request and someone will be looking at it shortly. We are committed to resolving every ticket as promptly as possible, and we encourage you to let us know if you have any additional concerns or questions by replying to this email. You will receive an email when any action has been taken on your ticket.
---------------------------------------------------------------

Ticket Details
Ticket #: 24135
Subject: Re: [woocommerce/woocommerce-gateway-stripe] Duplicate processing notes/duplicate emails around payment intent related webhooks (#889)
Status: Open

---------------------------------------------------------------

Staff - 12/31/1969 7:00 PM

Attachments
---------------------------------------------------------------
You can review the ticket by going to:
https://support.tecguru.co/en/tickets/view/24135?token=610063d02b783f128766d26d50d4e796424c6757
Blessings,
TecGuru

Self-Hosted Help Desk Software by [SupportPal](http://www.supportpal.com)

**Comment by tecguru** [comment]
-#-#- Please reply above this line -#-#-

Dear woocommerce/woocommerce-gateway-stripe,

We have received your request and someone will be looking at it shortly. We are committed to resolving every ticket as promptly as possible, and we encourage you to let us know if you have any additional concerns or questions by replying to this email. You will receive an email when any action has been taken on your ticket.
---------------------------------------------------------------

Ticket Details
Ticket #: 24237
Subject: Re: [woocommerce/woocommerce-gateway-stripe] Duplicate processing notes/duplicate emails around payment intent related webhooks (#889)
Status: Open

---------------------------------------------------------------

Staff - 12/31/1969 7:00 PM

Attachments
---------------------------------------------------------------
You can review the ticket by going to:
https://support.tecguru.co/en/tickets/view/24237?token=4a61f54437b649e0b90a4d681fd6ef32091a5ac5
Blessings,
TecGuru

Self-Hosted Help Desk Software by [SupportPal](http://www.supportpal.com)

**Comment by leopard3330** [comment]
The bug is still there

**Comment by AlexGThess** [comment]
> The bug is still there

i confirm...bug its still here and we receive two emails for new orders,failed etc... from pending to complete two times.....
