### ISSUE TITLE
Mobile Centering Issues with "Inline Credit Card Form" Option 

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-gateway-stripe#892]
#### Affected ticket(s)

2106878-zen

#### What I expected

When the `Inline Credit Card Form` option is selected in the Stripe settings (`WooCommerce > Settings > Payments > Stripe`), when a mobile user goes to enter their credit card number in the form, the form stays centered when it zooms in.

#### What happened instead

When the `Inline Credit Card Form` option is selected in the Stripe settings (`WooCommerce > Settings > Payments > Stripe`), when a mobile user goes to enter their credit card number in the form, it makes the page wider than the screen when zoomed in:

![https://cld.wthms.co/sAK2zW](https://cld.wthms.co/sAK2zW+)
Image link: https://cld.wthms.co/sAK2zW

![https://cld.wthms.co/gK7I5k](https://cld.wthms.co/gK7I5k+)
Image link: https://cld.wthms.co/gK7I5k

#### Steps to reproduce the issue

1. Setup Stripe and enable the `Inline Credit Card Form` option in the settings.
2. Test form on mobile in either live or staging mode to reproduce the issue.

I tested with Storefront enabled and only Stripe and WooCommerce installed, and still had the issue, which shows up only when the `Inline Credit Card Form` option is selected in the Stripe settings.

UPDATE: User reports that the issue also occurs on the Expiry Date and CVC fields when the `Inline Credit Card Form` option is deselected. I cannot replicate that, but wanted to add that info.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by wyter** [comment]
I tested with Stripe version 6.4.3. There is no longer an option for `Inline Credit Card Form` in Stripe settings. Thus, this bug can be moved to a close.

![No inline setting](https://user-images.githubusercontent.com/11092629/178790807-74ca3e1d-e842-4d61-8498-b5fa5af7f657.png)

**Comment by thenbrent** [comment]
Closing this one as the option for Inline Credit Card Form is no longer available, as mentioned above.
