### ISSUE TITLE
Undefined variable `$prepared_source`

### ISSUE THREAD

**Issue by codereviewvideos** [woocommerce/woocommerce-gateway-stripe#894]
#### What I expected

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-webhook-handler.php#L183

It would appear `$prepared_source` is not defined at this point.

I don't understand the code enough to suggest a definitive fix for this problem. At a guess, should this be:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-webhook-handler.php#L161

Based on the comment on line 159? 

#### What happened instead

I have not yet run the code to see what goes wrong here. 

#### Steps to reproduce the issue

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by v18** [comment]
Here's a new link reference to the offending line:

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/9a4a015f97b023b28e82607efdee96c1ea763e7f/includes/class-wc-stripe-webhook-handler.php#L183
