### ISSUE TITLE
Publishable keys in settings should not be type="password"

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce-gateway-stripe#895]
In the WooCommerce Stripe extension settings, the input fields for the publishable keys have type="password". This is unhelpful (you can't see what you just pasted) and useless, as the publishable key is public and exposed in the checkout page DOM. i.e. Hidden from the site owner in the settings, but (rightly) exposed to the world on the site itself.

**Comment by njeffers** [comment]
I usually have to change the field type to "text" in the admin area to reveal them, including the private key. Not sure if anything should be done about the false sense of security on the private key (it's a password field, so other privaleged admin users can't see them) , but I agree with you on showing the public key in text.

**Comment by allendav** [comment]
Easy fix we'll tackle in 4.2.3
