### ISSUE TITLE
How/where to include code to display last 4 digits of CCs

### ISSUE THREAD

**Issue by ldr2273** [woocommerce/woocommerce-gateway-stripe#897]
> Before version 4.2, /js/stripe.js was fairly easy to update to include the last 4 of credit cards in receipt & payment info. Stripe.js is now completely different and I’m not sure where to include my line of jqeury to display this information.

Can anyone point me in the right direction on this?

**Comment by allendav** [comment]
This might help. Here is an example of fetching the last 4 digits: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/07740bf0144acbdb1edf5794eaa4c17222e79de8/includes/compat/class-wc-stripe-subs-compat.php#L541
