### ISSUE TITLE
Cancelling an order should NOT run a refund

### ISSUE THREAD

**Issue by rynaldos** [woocommerce/woocommerce-gateway-stripe#900]
Howdy, 

It looks like this recent change https://github.com/woocommerce/woocommerce-gateway-stripe/commit/e6b8c5ab083cea67af151b117176b3cf2ae7f7ae, automatically refunds an order when the `Cancelled` status is set in the order. 

<img width="419" alt="Screen Shot 2019-06-26 at 08 27 26" src="https://user-images.githubusercontent.com/6198774/60156291-7dca5980-97ec-11e9-98b3-af245f925019.png">

I imagine that it would make sense to refund a canceled order, but since both the `Cancelled` and `Completed` status is so close to each other it is possible that the wrong one can be selected (mistakes happen). Here's what it looks like: 

<img width="361" alt="Screen Shot 2019-06-26 at 08 24 14" src="https://user-images.githubusercontent.com/6198774/60156271-760ab500-97ec-11e9-87fc-b21db6893e60.png">

Additionally, there is no popup notification, similar to refunding the order via the button on the edit order screen, to ask the user is he/she is sure about proceeding, like so: 

<img width="436" alt="Screen Shot 2019-06-26 at 07 54 32" src="https://user-images.githubusercontent.com/6198774/60156247-64291200-97ec-11e9-9d1a-5d641e402b17.png">

.. so there is no way to reverse it in case of an accidental wrong selection. Currently, the only way would be to ask the user to make another payment — not good.

Here is how to replicate the issue: 

1. Place an order on the site and pay with Stripe
2. Go to WP-Admin and view that order
3. Set the status of the order to `Cancelled`
4. Click `Update`

Is there anything we can do here? 

Cheers!

**Comment by kosiew** [comment]
#2182498-zen
Customer said this happened again.

**Comment by DanReyLop** [comment]
@kosiew I don't have access to that ticket (ping me in Slack if you prefer not to put more information in the open). Did they update to 4.2.2? The only thing that should happen now when the order is set to Cancelled/Refunded is that an authorized payment will be voided.
