### ISSUE TITLE
Payment Request Buttons required at end of Checkout

### ISSUE THREAD

**Issue by RunningBe** [woocommerce/woocommerce-gateway-stripe#904]
#### New feature request - Payment Request Button at end of Checkout

<sup><sup>The final cost of an order may not be known until the customer details are gathered at checkout.  In the case of postage, particularly the address can affect the total cost.  Thus, the Payment Request Buttons need to be just another payment option that can be placed with the credit card option.</sup></sup>
-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by tommyshellberg** [comment]
Hey @RunningBe - the purpose of the Payment Request buttons is to allow for users to "skip" the standard checkout flow. Their address should be loaded from their payment method(Apple Pay, Google Pay) so they don't need to enter it manually. The shipping cost should be calculated based on that address.

**Comment by RunningBe** [comment]
Hello Tommy,

It is essential that the Payment Request Button be at the end of checkout, because until then the total cost is not known.  The user has postage options: normal delivery, express postage, even pickup, all of which have different costs.  Then again, the delivery address may not be the billing address.  We really do need the Payment Request Button after all this is resolved.  

It's still advantageous at the end of checkout to use, say,  Apple Pay, as no card details entry is required and the transaction will appear on the customer's Apple Pay history.

Please would you reopen this issue.  Thank you, Barry

P.S. Incidentally, how in Wordpress/WooCommerce does one access the payment method address to display it on the checkout page? B.

**Comment by RunningBe** [comment]
Hello Thomas,


Please see, I have commented on the issue:

Hello Tommy,

It is essential that the Payment Request Button be at the end of checkout, because until then the total cost is not known. The user has postage options: normal delivery, express postage, even pickup, all of which have different costs. Then again, the delivery address may not be the billing address. We really do need the Payment Request Button after all this is resolved.

It's still advantageous at the end of checkout to use, say, Apple Pay, as no card details entry is required and the transaction will appear on the customer's Apple Pay history.

Please would you reopen this issue. Thank you, Barry

P.S. Incidentally, how in Wordpress/WooCommerce does one access the payment method address to display it on the checkout page? B.
