### ISSUE TITLE
Invalid filter argument in prepare_order_pay_page() in class WC_Gateway_Stripe (class-wc-gateway-stripe.php)

### ISSUE THREAD

**Issue by sumudumathew** [woocommerce/woocommerce-gateway-stripe#906]
add_filter( 'woocommerce_available_payment_gateways', '__return_empty_array' );
#### What I expected

I didnt expect any warning to be thrown in the debug log when checkingout an order

#### What happened instead

The following warning appears when checkingout an order with a 3DS-2 cards
call_user_func_array() expects parameter 1 to be a valid callback, class 'WC_Gateway_Stripe' does not have a method '__return_empty_array'
 Type: PHP Warning Line: 286
 File: /home/koopicaf/public_html/koopicafenet_dev/wp-includes/class-wp-hook.php

#### Steps to reproduce the issue
1. Add a 3DS-2 card to a user
2. Checkout an order
3. Check the debug log
 
The reference to $this must be removed in line: add_filter( 'woocommerce_available_payment_gateways', array( $this, '__return_empty_array' ) );

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by sumudumathew** [comment]
Any update on this bug please ?

**Comment by RadoslavGeorgiev** [comment]
I created #1008 to fix the issue.

Small note: The mentioned line (which is the only instance of `__return_empty_array` in the gateway) only generates warnings on the __Pay for Order__ page, but not the checkout page. I believe the PR will fix the issue, but the testing instructions seem to be incorrect.

**Comment by DanReyLop** [comment]
This was fixed in the `4.3.0` release. Closing.
