### ISSUE TITLE
Undefined index: statement_descriptor when statement_descriptor is empty in settings

### ISSUE THREAD

**Issue by yanmorinokamca** [woocommerce/woocommerce-gateway-stripe#907]
#### What I expected

No notice when trying to checkout.

#### What happened instead

Message with Undefined index: statement_descriptor

#### Steps to reproduce the issue

Set statement descriptor to an empty value (not required/set in the form)
Activate debug of notice in wordpress.

How to not get the problem: write something in the statement_descriptor setting field.

Source:
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/9bcd635e041c49401b74fb8e21ccfca7c596834f/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L1040
Use of description, metadata, statement_descriptor and capture in $full_request array declared by the function generate_payment_request.

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/9bcd635e041c49401b74fb8e21ccfca7c596834f/includes/abstracts/abstract-wc-stripe-payment-gateway.php#L333

generate_payment_request function always set indexes: currency, amount, description, expand[], metadata.
indexes: capture, statement_descriptor, customer and source are not always set.

Proposed solution: 
$post_data['statement_descriptor'] = '';  // line 342.

$post_data['capture'] should also be set to remove a potential notice.

**Comment by tommyshellberg** [comment]
I also ran into this today because the Statement Descriptor was left blank. Given that it seems like it's important to have, maybe there should be some validation to ensure it's not left blank?

From Stripe's docs:

>Bank and card network rules require that statement descriptors clearly indicate the business responsible for the charge or payment, in addition to providing other details to help the customer understand their statements.

https://stripe.com/docs/statement-descriptors

**Comment by RadoslavGeorgiev** [comment]
Fixed in #962, see https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1006#issuecomment-535005275
