### ISSUE TITLE
woocommerce_get_page_id is deprecated since version 3.0

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce-gateway-stripe#932]
Came across this notice on our logs.

> The woocommerce_get_page_id function is deprecated since version 3.0. Replace with wc_get_page_id.

It appears to originate from https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-intent-controller.php#L95

**Comment by RadoslavGeorgiev** [comment]
Closing because of #1009. Not sure why the `Fixes ` keyword doesn't work.
