### ISSUE TITLE
SCA: Handle new subscription payments where the customer is charged right away for the first charge

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#935]
For new subscriptions where the user is charged right away for the first charge, create the first Payment Intent with `setup_future_usage: ‘off_session'`:

https://stripe.com/docs/api/payment_intents/create#create_payment_intent-setup_future_usage

As part of this issue, make sure that variable subscriptions are handled (or create new issues for it).

**Comment by allendav** [comment]
@RadoslavGeorgiev please link a PR when you can, even an in-progress one - thx!

**Comment by allendav** [comment]
Hey @RadoslavGeorgiev - what's the next step on this issue?

**Comment by RadoslavGeorgiev** [comment]
Sorry @allendav, https://github.com/woocommerce/woocommerce-gateway-stripe/pull/962 (the corresponding PR) got merged already, so no next steps are required.
