### ISSUE TITLE
SCA: Use SetupIntent for subscriptions where customer is not charged right away

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#936]
For new subscriptions where you **don’t** charge anything when signing up, we’ll need to use a SetupIntent ([#](https://stripe.com/docs/api/setup_intents)) instead of a PaymentIntent. That will go through the SCA flow (maybe requesting extra authentication) but won’t charge the customer anything.

As part of this issue, make sure that variable subscriptions are handled (or create new issues for it).

**Comment by allendav** [comment]
@DanReyLop  please link a PR when you can, even an in-progress one - thx!

**Comment by DanReyLop** [comment]
Solved by #1024
