### ISSUE TITLE
SCA: Annotate recurring payments with have off_session: true

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#938]
For recurring payments to go through, they need to be annotated with `off_session: true`:

https://stripe.com/docs/api/payment_intents/create#create_payment_intent-off_session

To test: Make sure that a recurring transaction works with this implemented. Is it possible to test a recurring transactions failing without this before Sept 14?

**Comment by DanReyLop** [comment]
> Is it possible to test a recurring transactions failing without this before Sept 14?

Stripe has some test credit card numbers we can use: https://stripe.com/docs/payments/cards/charging-saved-cards#testing

**Comment by v18** [comment]
> To test: Make sure that a recurring transaction works with this implemented. Is it possible to test a recurring transactions failing without this before Sept 14?

There's a new card for this - `4000003800000446 `

**Comment by v18** [comment]
Closed by #955
