### ISSUE TITLE
SCA: Are SEPA subscriptions affected?

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#939]
https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/compat/class-wc-stripe-sepa-subs-compat.php

**Comment by allendav** [comment]
@thorsten-stripe - does SCA/3DS2 affect SEPA?

**Comment by thorsten-stripe** [comment]
No, SCA only affects customer initiated transactions, SEPA Debits are considered as always merchant initiated.

**Comment by allendav** [comment]
Closing as not an issue
