### ISSUE TITLE
SCA Doc: Update Stripe extension docs

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#940]
https://docs.woocommerce.com/document/stripe/#section-17 (SCA/PSD2)

**Comment by dwainm** [comment]
Is this related to the extension running on WooCommerce.com or does it refer to the extension for merchants: https://woocommerce.com/products/stripe/?

**Comment by allendav** [comment]
Merchants

**Comment by allendav** [comment]
@jobthomas @californiakat - we will have updates to the Stripe extension doc this month - how can we best coordinate with you?

**Comment by jobthomas** [comment]
I'll leave that one to @californiakat - normally with big updates, Kat works with duplicating the existing doc in a draft and updating that so it can replace the live one when it's ready to publish.

**Comment by californiakat** [comment]
@allendav I'm flexible about how I receive information to update docs.

If someone tells me what was changed/improved/added to the product, I can sort out what needs updating on my own. There are multiple ways to tell me:
- P2/blog: Tag me if it's already stated somewhere
- Trello board: Give me access and a link
- G doc: Give me access and a link (this is usually the method used by partners or a third party that did dev work)

Or if everything will be listed on the Changelog when the version launches, I can take it from there also.

**Comment by v18** [comment]
🙌

👋@californiakat - can we tag you on PRs we merge into the feature branch? Each PR solves a specific issue and will usually have testing instructions, etc, to help illustrate what the changes are.

On that note, would you prefer to write one big update, or know about the different changes as we go along?

**Comment by v18** [comment]
Notes on some docs that we'll want to update (posting as I find them):

- https://docs.woocommerce.com/document/managing-orders/#section-13 (and the whole page) - will want to note which status an order has when its payment is pending due to 3DS / authentication_required response from Stripe
- https://docs.woocommerce.com/document/configuring-woocommerce-settings/#section-18 -- indicate the authentication_required email we'll send out
