### ISSUE TITLE
SCA: make sure the pre-orders work

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#941]
Issue #937 mentions that the link to re-authenticate the payment method should work for pre-orders. This issue is to make sure nothing else is missed for pre-orders using Stripe as the payment gateway.

**Comment by RadoslavGeorgiev** [comment]
We'll have to do a final test, but AFAICT the usage of `SetupIntent` in #997 and and email in #991 should be sufficient for Pre-Orders SCA support.

**Comment by RadoslavGeorgiev** [comment]
> We'll have to do a final test, but AFAICT the usage of SetupIntent in #997 and and email in #991 should be sufficient for Pre-Orders SCA support.

https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1026 is a very obvious exception to this statement :\

**Comment by allendav** [comment]
> he usage of SetupIntent in #997 and and email in #991 should be sufficient for Pre-Orders SCA support.

#997 is now going to be covered by #1024
