### ISSUE TITLE
SCA: Ensure that WooCommerce Deposits works with Stripe

### ISSUE THREAD

**Issue by DanReyLop** [woocommerce/woocommerce-gateway-stripe#943]
I'm 99% sure that WooCommerce Deposits won't be affected by the SCA changes, but at the very least we should test it.

WooCommerce Deposits ([extension description](https://woocommerce.com/products/woocommerce-deposits/)) allows a customer to pay for a product in "installments". For example, monthly. Every period, the customer receives an e-mail (sent using the `$mailer->customer_invoice( $order )` method [here](https://github.com/woocommerce/woocommerce-deposits/blob/e395198b04504cca25d08b46511f4454eb8c8126/includes/class-wc-deposits-scheduled-order-manager.php#L128)) so he can pay. That flow is similar as when a merchant creates a manual order and sends an e-mail invoice to the customer.

As such, the Deposits extension never stores the customer's credit card data, and never charges the credit card "off-session". We should still double-check that everything works while using a credit card that requires SCA authentication.

**Comment by DanReyLop** [comment]
I've confirmed that Deposits sends the customer an "invoice" email for each deposit installment. That e-mail has a link that directs the user to a payment flow directly. Credit cards don't need to be saved, and there's never a transaction without the customer present. Closing this.

**Comment by v18** [comment]
Looks like Deposits don't play nice with SCA yet.

Steps to reproduce:

1. Enable deposits on your test site
2. Checkout with an item, paying with a deposit
3. Pay using test card `4000002760003184`
4. Authenticate payment, and see that it successfully goes through
5. As the store owner, invoice the customer for the rest of the order
6. As the customer, get invoice email, go to pay using `4000002760003184`
7. See that payment fails. With the branch for `4.2.5` you can see the failure reason, and with the branch for `4.3` (aka `sca-subs/master`), the error is not available.

The error is:

```
[code] => payment_intent_unexpected_state
[doc_url] => https://stripe.com/docs/error-codes/payment-intent-unexpected-state
[message] => This PaymentIntent's source could not be updated because it has a status of succeeded. You may only update the source of a PaymentIntent with one of the following statuses: requires_payment_method, requires_confirmation, requires_action.
```

**Comment by DanReyLop** [comment]
I get the same thing @tommyshellberg got while testing:
- The first payment succeeds
- The second payment succeeds, you can see it in Stripe Dashboard...
- ... but the order for the second installment of the deposit is not updated

I'm pretty sure that issue is caused by the custom order types that the Deposits extension registers. I'm looking into it.

@v18 I can't reproduce the behaviour you posted. In my case, the payment succeeds. I tried both in the `4.3.0-alpha-1`, in `sca-subs/master`, and in `4.2.5`. We can try to troubleshoot it when you come back.

**Comment by v18** [comment]
> but the order for the second installment of the deposit is not updated

@DanReyLop this sounds like an issue.

**Comment by DanReyLop** [comment]
Yeah, and that's what I fixed in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1050 and https://github.com/woocommerce/woocommerce-deposits/pull/306 :)

What I was trying to say (poorly worded) is that I **did** manage to reproduce the same issue that @tommyshellberg had, but **not** yours.
