### ISSUE TITLE
SCA: Is there a way to simulate a failing recurring subscription that comes into effect Sept 14?

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#945]
Ask Stripe, so we can test that our PRs are actually solving the issue.

**Comment by dwainm** [comment]
@v18 Do we know what kind of error codes are we expecting? I'm looking for documentation on this but don't recall where I saw this mentioned.

**Comment by v18** [comment]
@dwainm we are looking for a failing recurring transaction that requires 3DS after the first purchase.

I think the test credit card I was looking for is 4000002500003155

**Comment by dwainm** [comment]
@v18 I was thinking about one of these. 

It seems like Stripe provides:
`payment_intent_authentication_failure`
`setup_intent_authentication_failure`

https://stripe.com/docs/error-codes

I assume we are looking for `payment_intent_authentication_failure`?

**Comment by v18** [comment]
@dwainm I think I am looking for `payment_intent_authentication_failure`, but it's a special case. I want to be able to check out with this credit card at checkout for a subscription. However I then want see it fail on a renewal payment with the same card, because we didn't use the `off_session` parameter.

**Comment by v18** [comment]
Mmm - maybe `4000003800000446` will work?

> This card requires authentication for one-time and other on-session payments. However, all off-session payments will succeed as if the card has been previously set up.

https://stripe.com/docs/testing#regulatory-cards

h/t @yoavf

**Comment by v18** [comment]
`4000003800000446` works 🎉:

- payment succeeds for first-time payments
- payment succeeds for recurring payments with `off_session: true`
- payment fails with `authentication_required` if `off_session` is not used

Closing issue.

**Comment by dwainm** [comment]
Thank you for the ping @v18 !
