### ISSUE TITLE
PaymentRequestButton: Option to hide and style different payment methods

### ISSUE THREAD

**Issue by KrystianErgotopia** [woocommerce/woocommerce-gateway-stripe#946]
The Apple Pay Button looks great. But the automatically activated Google Pay Button is purble and has a weird animated arrow and may confuse the user with the simple text "buy now". It would be much better if it would be possible within the plugin to decide which payment method you want to use and which styling and text you wand. This blogpost has a solution for the styling issue but it would mean to manually update the plugin every time which is bad: https://justentrepreneurship.com/stripe-payment-request-button-style/
Thatswhy I wondered if you could implement this ?

**Comment by asuh** [comment]
There have been multiple requests for this, and I talked with both Stripe developers who prefer to keep the purple button and WooCommerce developers who don't have plans to make any changes to this. You can see my reply to an older thread here:
https://github.com/woocommerce/woocommerce-gateway-stripe/issues/753

**Comment by allendav** [comment]
Would be ideal to sort this out at the same time we sort out #1071 and #751. See also (closed) issue #753  with some of the back and forth. Props @dougaitken
