### ISSUE TITLE
Idempotency error when checking out with 3DS Required Card + Pre-Orders

### ISSUE THREAD

**Issue by tommyshellberg** [woocommerce/woocommerce-gateway-stripe#949]
#### What happened instead

* When the pre-order was released, an attempt to charge the card was made but it failed:

```
Stripe Transaction Failed (Keys for idempotent requests can only be used with the same parameters they were first used with. Try using a key other than ...
```

![https://cld.wthms.co/qrI7Ge](https://cld.wthms.co/qrI7Ge+)
Image link: https://cld.wthms.co/qrI7Ge

What's worse, the Pre-Order was still marked `Completed`.

#### Steps to reproduce the issue

* Create a Pre-Order product and set to charge upon release at a later date(it can even be just 5-10 minutes in the future):
![https://cld.wthms.co/4UicEq](https://cld.wthms.co/4UicEq+)
Image link: https://cld.wthms.co/4UicEq

* Purchase said product with a Stripe test card that should always prompt 3DS verification:

![https://cld.wthms.co/YqnJBu](https://cld.wthms.co/YqnJBu+)
Image link: https://cld.wthms.co/YqnJBu

https://stripe.com/docs/testing

* Note that it doesn't prompt 3DS at checkout(issue #937).
* Wait until the CRON job runs which checks for Pre-Orders:

![https://cld.wthms.co/8wBzzM](https://cld.wthms.co/8wBzzM+)
Image link: https://cld.wthms.co/8wBzzM

* Once the Pre-order is released, check that the pre-order is marked Completed and view the associated order and its order notes.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by v18** [comment]
@tommyshellberg can you try using the credit card `4000002500003155`?

**Comment by tommyshellberg** [comment]
@v18 - same errors as above with *3155. Transaction goes through on the front-end, fails in the backend, but the Pre-Order is still Completed.

**Comment by v18** [comment]
Perfect, thank you 👌

**Comment by RadoslavGeorgiev** [comment]
Closing because #1039 was just merged.
