### ISSUE TITLE
Customer email appearing in Stripe Dashboard under 'Name' field

### ISSUE THREAD

**Issue by alexryans** [woocommerce/woocommerce-gateway-stripe#95]
#### What I expected

The customer's billing name to be entered into the 'Name' field in the Stripe Dashboard.

#### What happened instead

When an order is submitted to Stripe through the plugin, it seems to be entering the customer's email as the 'Name'. Is this expected behaviour? Could it be changed to the customer's billing name?

![screen shot 2016-11-02 at 11 28 33](https://cloud.githubusercontent.com/assets/3007053/19927064/ff0ba86a-a0ef-11e6-92d5-51741a919b4b.png)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
What version are you using and are using Stripe Checkout or just Stripe?

**Comment by alexryans** [comment]
I'm currently using the latest version of WooCommerce Stripe Gateway - v3.0.5 - and I'm using just the standard Stripe gateway method.

**Comment by roykho** [comment]
During checkout, just the user logged in?

**Comment by alexryans** [comment]
I've tested this with both a guest user and a logged in user, with the same result.

**Comment by roykho** [comment]
Ah... Ok I knew I addressed this already. Its already in master branch so you will need to wait until next release. Or if you want to test it, grab it from master.

**Comment by alexryans** [comment]
No worries, thanks!

**Comment by PJCwasHere** [comment]
I have the same issue.  The email address is added in the Name Field.  I have the next version of WooCommerce Stripe Gateway - Version 3.0.6  and it is still doing it! Any chance of this being fixed soon?
Cheers,
Peter
