### ISSUE TITLE
Webhook event validity period too short

### ISSUE THREAD

**Issue by twistedpixel** [woocommerce/woocommerce-gateway-stripe#952]
#### What I expected

Webhook event to process and return status code 200.

#### What happened instead

Status code 400 was received with no PHP errors in log file.

On checking the code for Webhooks handling, it looks like you verify the event by checking the signing secret. I believe this to be where it's failing.

The Stripe account is on a higher API version that the plugin supports but there are no changes that should affect this plugin between 2019-02-19 and 2019-05-16 (latest, the one we're using). I don't see anything from Stripe about Webhook signing signatures having changed between these version so I'm really not sure what to make of this.

On the server, I've temporarily changed your plugin code slightly to return a string describing which stage of signature verification is failing and to print this as response to Stripe. Unfortunately Stripe won't let me retry live Webhooks manually so I need to wait until the next attempts to see which part of the signature verification is causing failure.

I will update once I view the Stripe logs after the next Webhook retries.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by twistedpixel** [comment]
Just had one hit the server. It’s failing on the timestamp check.

**Comment by twistedpixel** [comment]
I think this is happening because Stripe appears to set the timestamp in the event signature and then schedule it for sending but some time may go by between scheduling and actually sending. In the case I'm examining: the time logged by the server when receiving the Webhook event was about 5 minutes after it was generated by Stripe and hence, your code rejected it as invalid.

Your code only allows 60 seconds before it invalidates the timestamp. I'd suggest instead using a longer validity duration. I think 10 minutes would be sufficient.

Although realistically, the most bulletproof way would be to simply ignore the timestamp altogether, verify the signature hash and then (if valid) retrieve the event directly from Stripe via the API. I think it's just asking for trouble by defining arbitrary validity durations when it cannot be accurately determined how long these need to be.

**Comment by allendav** [comment]
@twistedpixel - would you verify your server clock is up-to-date? A quick way to check is by visiting wp-admin/options-general.php and observing the time in the Timezone section

**Comment by twistedpixel** [comment]
Hmm, strange: it was indeed off by a few minutes, thanks.

I'd still perhaps suggest using a 5 minute validity window as advised by Stripe since I imagine this could potentially happen to others in our situation who aren't using NTP.
