### ISSUE TITLE
What happens to subscription while we wait for a user to authenticate a recurring payment?

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#957]
Say a recurring payment has the status `needs_authentication`. What does the subscription order status look like?

cc @LCmry

**Comment by v18** [comment]
Learnings from @LCmry @james-allan:

>  subscription statuses are tied to the order status so what ever status the order is will dictate what the subscription status is

> Subscriptions have a fairly small set of statuses at the moment. Pending (not widely used), on-hold, active, pending-cancelled, cancelled.

> On-hold is the only status we currently used for a subscription which isn’t active because it is awaiting payment.

Therefore, here's what we need to do to make sure payments that are awaiting authentication are working:

- [ ] make sure that while the payment is awaiting authentication, the order has the correct status.
- [ ] probably the right status is `on-hold` but we need to double-check that

Other considerations:

- [ ] we'll want input from the subscriptions team when we implement on this to make sure there are no problems with orders being on hold for this - for example, do store owners expect that their customers will continue to have their subscriptions working? etc. make sure we are not causing any unexpected problems there.
- [ ] what is the expected behaviour if a user tries to make multiple payments for a recurring subscription?

**Comment by v18** [comment]
Question: why don't we save the payment intent for the error response case? e.g. in `create_and_confirm_intent_for_renewal()` using `save_intent_to_order()`.

**Comment by allendav** [comment]
@v18 wrote

>  here's what we need to do to make sure payments that are awaiting authentication are working

Do we have PRs for those items? What are they?

**Comment by v18** [comment]
@allendav yeh - the PR related to first two points, including "make sure that while the payment is awaiting authentication, the order has the correct status", is #975 .

This was resolved as well, but will need to be tested:

> what is the expected behaviour if a user tries to make multiple payments for a recurring subscription?

The user will not be able to make multiple payments for the same order without the order changing status and updating the subscription correctly.

I think the following consideration is resolved, but we should double-check with the Subscriptions team:

> we'll want input from the subscriptions team when we implement on this to make sure there are no problems with orders being on hold for this - for example, do store owners expect that their customers will continue to have their subscriptions working? etc. make sure we are not causing any unexpected problems there.
