### ISSUE TITLE
Version 3.0.5 Checkout Modal popup not displayed but payment continues to be attempted after using fraudulent test card.

### ISSUE THREAD

**Issue by clariontools** [woocommerce/woocommerce-gateway-stripe#96]
#### What I expected

Using the checkout modal I enter the stripe test card 4100000000000019, the card is rejected and error "card_declined: Your card was declined." is displayed.  I expect when I click the "Continue To Payment" button on the checkout page that the checkout modal will be displayed again and I can try to enter a different card.
#### What happened instead

When I click the "Continue To Payment" button for the second or any subsequent time *after* the initial usage and failure of stripe test card 4100000000000019, the checkout modal popup does *not* appear.  What is worse is that the transaction is actually submitted again and again each time I click the "Continue To Payment" button with the fraudulent card and information and failed transaction even though the checkout modal popup does not appear.
#### Steps to reproduce the issue

1. Activate Checkout Modal.
2. Add items to card and proceed to checkout page.
3. Click "Continue To Payment" button.
4. Enter stripe test card 4100000000000019 with future exp. date and 3 digit cvc.
5. Card is processed, popup receives green check.
6. Checkout page gets error: card_declined: Your card was declined.
7. Without reloading the page, click the "Continue To Payment" button.
8. Checkout Modal popup does not appear.
9. Charge is still submitted from previous entered data and rejects.
10. Checkout page continues to get error: card_declined: Your card was declined.
11. Goto step 7 and repeat, each time you will effectively submit another charge with fraudulent card.
12. Finally go to your stripe account and see all the failed charges.

* As I recall there were a couple other cases where this same issue came up.  Must be related to the type of error.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
This seems to only happen if the modal did not decline the card right then and there which is weird as that card number is stated in the docs will be declined. If you for example used `4000000000000002` you will see it declines it within the modal without the modal closing. Perhaps there is no logic to defend against the case you mentioned.

**Comment by clariontools** [comment]
I saw the fix in #98, that clearly looks like it would solve the issue, thank you!

**Comment by roykho** [comment]
@clariontools - awesome, if possible, please test it out and let me know if it works. Its in the master branch.

**Comment by clariontools** [comment]
Just tested with the latest master and using test card number 4100000000000019, it still has the same problem after the first submit fails and throws the error "The card was declined.", subsequent clicks on the "Continue To Payment" immediately submit the payment and the checkout modal popup does not appear, but the payment is attempted and error is thrown again and with each "Continue To Payment" click.  Here is the response as status 402 for the transaction if that helps:

**Comment by roykho** [comment]
So I just tested this again and it is working fine on my end. Did you make sure to clear any/all cache and re-test?

**Comment by clariontools** [comment]
Just did a little more testing and find that since the order is inserted with card 4100000000000019 as long as you use the same cart to checkout again with a valid card, woo will process the payment on the order that was inserted when the payment was rejected.

So the only thing that really needs to be fixed is still the original problem where the checkout modal popup does not appear after the Charge is declined with a card_declined code and a fraudulent reason. event.

**Comment by clariontools** [comment]
I did clear the caches, but will try again...

**Comment by roykho** [comment]
Please see my screencast here of my test http://cld.wthms.co/oo56/41UBzFGp

**Comment by clariontools** [comment]
I saw your screencast, so that is what I was expecting.  I will switch browser from firefox to chrome and see if that makes a diff.

**Comment by clariontools** [comment]
Ok! Yes, on chrome it is working as expected!  So now to see why it is not on firefox... will report back here if it is just a firefox cache issue or other...

**Comment by roykho** [comment]
In my screencast, it was FireFox. I've already tested on Chrome and it works as expected.

**Comment by clariontools** [comment]
Yes, it was just some arcane caching issue on firefox, but all is working as expected with this latest release from master.  Thank you!

The testing did help me appreciate the workflow a bit better and it is good to see all the other recovery and processing features are working in coordination with particular decline error.  I like the fact that this fraudulent declined order shows up in the customer account with a pay button.  It is still a bit confusing because the error in this case shows up on the checkout when in fact an order was already created.  Not terrible, but from the customer view, there was no order processed.  Overall, this is a big improvement, now on to the next issue :) ...
