### ISSUE TITLE
Enhancement: Make PaymentIntent value filterable

### ISSUE THREAD

**Issue by indextwo** [woocommerce/woocommerce-gateway-stripe#960]
I've developed an extension to the WC Stripe gateway that allows customers to pay for the order total via instalments. The instalments are dynamic, so some examples might be:

* Order total of £400, as instalments over 4 months, so;
  * Initial charge of £50;
  * Recurring subscription of £50 for 3 more months

* Order total of £379.98 as instalments over 5 months, so;
  * Initial charge of £76.02;
  * Recurring subscription of £75.99 for 4 more months

I originally developed this as a standalone plugin over 5 years ago(!), but with all the SCA regulations coming up and the amazing work you have done with the WC Stripe plugin, it just made sense to redevelop it as an extension of this. I've done that and it's all working; however I've had to make a tweak to your plugin, which is to make the PaymentIntent values filterable; otherwise the initial charge still goes through as the full order value (i.e. what was sent as the PI) regardless of what actual charge value you send through with the actual transaction.

The filters only need to be added in two places (I believe); `create_intent()` & `update_existing_intent()` in `abstract-wc-stripe-payment-gateway.php`: 

```
public function create_intent( $order, $prepared_source ) {
	$full_request = $this->generate_payment_request( $order, $prepared_source );

	$request = array(
		'source'               => $prepared_source->source,
		'amount'               => apply_filters('vnm_payment_intents_amount', WC_Stripe_Helper::get_stripe_amount( $order->get_total() ), $order),
		//...
```

and

```
public function update_existing_intent( $intent, $order, $prepared_source ) {
		$request = array();

		if ( $prepared_source->source !== $intent->source ) {
			$request['source'] = $prepared_source->source;
		}

		$new_amount = apply_filters('vnm_payment_intents_amount', WC_Stripe_Helper::get_stripe_amount( $order->get_total() ), $order);
		///...
```

Personally I can't see any drawbacks, and it would certainly make my own life a lot easier!

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by thenbrent** [comment]
Closing this one due to lack of activity / broad demand for the change.

If it would still be of value now (4 years later), please open a new issue for visibility and discussion.
