### ISSUE TITLE
WC Subs Renewals: Refactor to use order amount instead of custom amount

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#969]
For subscription renewals, we get an `$amount` variable. But, the amount to charge the customer is also available from the order directly. @LCmry mentioned that there probably aren't any issues with using the order amount. We should review the relevant code and make the change if there aren't any issues.

Convo here: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/955#issuecomment-521287507

Once this change goes through, it will make it easier to refactor the subscriptions compatibility class to use its parent `create_intent()` instead of a custom `create_and_confirm_intent_for_renewal()`.

Convo about that here: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/963#discussion_r316319862

**Comment by thenbrent** [comment]
Closing this as it looks like it is out of date and has already been implemented.

Previously Stripe would use the $amount arg as outlined in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/963#discussion_r316319862 linked from the issue.

Stripe’s renewal payment flow now uses the parent methods for collecting the payment which all rely on being passed an order for which it pulls the total from.
