### ISSUE TITLE
Any way to hook into failed transactions before or after failed email sent?

### ISSUE THREAD

**Issue by pjv** [woocommerce/woocommerce-gateway-stripe#97]
I have a client whose WC shop is being repeatedly abused by some reprobate who is using them as a way to screen fraudulent CCs. He sets up an order and tries to pay for it with one CC after another, every 30 seconds or so, until it goes through. Which generates fail after fail after fail...

I want to log these fails somewhere that I can fail2ban the IP address being used after a few fails but since failed stripe transactions are not changing the order status (or even writing order notes) I haven't been able to find anything to hook into so far. If anyone can suggest a way to do this, I'd be grateful, otherwise, I will write an action hook in [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/ee31e2a7fd3fd01eea0eee43235b8c2c5a475b2a/includes/class-wc-gateway-stripe.php#L727) somewhere and send in a PR.

**Comment by roykho** [comment]
There are already hooks you can use within the WC core on the order failed process. Once you are hooked in, you can match the order payment type to Stripe and add your logic accordingly.

**Comment by pjv** [comment]
Hi @roykho, thanks, but the failed stripe transactions happen (over and over) without setting the WC order to failed, or in fact changing the status at all. The order status remains 'pending payment'. I believe this is so that a customer can re-try a payment without creating a new order every time. So in this case, I can't use the WC core hooks.

**Comment by roykho** [comment]
Ok I will add an action hook when a payment process fails, does that work for you?

**Comment by pjv** [comment]
That would be great. This is what I am testing with now which is working fine (modification of function `send_failed_order_email` in `class-wc-gateway-stripe.php`:

    public function send_failed_order_email( $order_id ) {
        $emails = WC()->mailer()->get_emails();
        if ( ! empty( $emails ) && ! empty( $order_id ) ) {
            $emails['WC_Email_Failed_Order']->trigger( $order_id );
        }
        do_action('wc_gateway_stripe_transaction_failure', $order_id);
    }

**Comment by roykho** [comment]
So that would be too specific to the email action. So I put the action outside/after that where you can hook in. If you want, please pull down the master branch and test it if it works for you. Ref https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-gateway-stripe.php#L611

**Comment by pjv** [comment]
hi @roykho. I tried it and I'm not getting the `$order` object passed in as an argument. Maybe it would be better to pass the $order_id?

**Comment by roykho** [comment]
I just tested this and I get the $order object. What does your code look like?

**Comment by pjv** [comment]
function plx_wc_order_failed ($e, $order) {
      $order_num = $order->get_order_number();
      // log failed orders to auth log
      $host = $_SERVER['HTTP_HOST'];
      $remote_addr = $_SERVER['REMOTE_ADDR'];
      $prefix = "woocommerce($host)";
      openlog($prefix, LOG_PID, LOG_AUTH);
      syslog(LOG_NOTICE, "Failed woocommerce order ($order_num) from $remote_addr");
      closelog();
    }
    
    add_action( 'wc_gateway_stripe_process_payment_error', 'plx_wc_order_failed' );

**Comment by roykho** [comment]
So that's why it is not working for you. Your hook should look like this, `add_action( 'wc_gateway_stripe_process_payment_error', 'plx_wc_order_failed', 10, 2 );`

**Comment by pjv** [comment]
Thanks, that works.

Unfortunately now my little function is no longer logging to my auth.log, though if I spit the same stuff out to the the WP debug log it works.
