### ISSUE TITLE
Payment Request Buttons necessary at end of Checkout

### ISSUE THREAD

**Issue by RunningBe** [woocommerce/woocommerce-gateway-stripe#976]
#### Payment Request Button NECESSARY at end of Checkout

The final cost of an order may not be known until the customer has made choices at  checkout. In the case of postage, the delivery mode affects the total cost (please see screenshot). Thus, the Payment Request Buttons need to be just another payment option that can be placed with the credit card option.  It still provides speed and convenience for the customer, because they do not need to enter their card details and the transaction is on their Apple Pay or Google Pay transactions list.

Please do not close this ticket as done with #904 before:
a) Recognising this makes the Payment Request Buttons useless before the end of checkout in our case.
b) This feature or very similar has been requested many times before by others.  Examples:
[Move Apple pay button inside the checkout page](https://wordpress.org/support/topic/move-apple-pay-button-inside-the-checkout-page/)
[WooCommerce Apple Pay: Move Buttons Below Customer Details](https://remicorson.com/woocommerce-apple-pay-move-buttons-below-customer-details/)
[Move Buy With Apple Pay Button](https://wordpress.org/support/topic/move-buy-with-apple-pay-button/)
and so on, and so on, and so on ..........

Please, please recognise this issue.  Thank you.
 
![Screen Shot 2019-08-27 at 5 46 04 PM](https://user-images.githubusercontent.com/11532450/63751692-3434e280-c8f3-11e9-9cff-675c7bfb3017.png)

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by martines374** [comment]
I definitely agree, this is something necessary. Any chance this will be implemented?

**Comment by Buzut** [comment]
I agree 200%. The thing is, you can choose some options in the default Apple Pay modal.
For instance, it prompts me about which delivery method I want.

![apple-pay](https://user-images.githubusercontent.com/6450536/79568722-a93d6e00-80b6-11ea-8e2a-cd2df8f14f3f.png)

But for more sophisticated flows, it just cannot do. For exemple, if the website offers a pickup option, you can select the pickup location on a list or a map. This option cannot be offered with Apple Pay.


![checkout](https://user-images.githubusercontent.com/6450536/79568936-06d1ba80-80b7-11ea-9403-fe9dab31946a.gif)


The solution would be to be able to use Apple Pay for payment only, not for getting the customer information.

Ideally :
* I'd offer Apple Pay as a one click purchase with limited options on the cart page,
* offer the other options normally on the checkout page with Apple Pay showing with the other payment methods. In this case Apple Pay would be used just to process the payment, not to get customer information.

**Comment by zdenys** [comment]
Another report in 25231264-hc. In this case site, visitors are able to skip shipping costs by using Apple Pay button earlier at product pages and the cart.

**Comment by RunningBe** [comment]
We've just opened our site for sales and shipping to multiple countries, so once again, until the shipping address is known, the postage is unknown.  Once more the payment request buttons need to be after the address details on the checkout page and the postage cost may have no relationship to the purchaser's billing address.  I continue to be perplexed why this is not an option.

What a wonderful new year gift it would be to the community and particularly those supporting this request to see it implemented.  Happy New Year WooCommerce Stripe Gateway developers and plugin users.

**Comment by RunningBe** [comment]
## This is Where We Need Apple Pay 
So here we see in the screenshot, two postage options (so the final cost is not yet certain), the customers details to set up their account (which we do not have before the checkout page) and three payment options.  All that's being asked for is to also have a payment request button WITH the other payment options.  Then the final payment can be charged and the customer's account created.

Automatic Un-Happiness Engineers seem determined not to understand or acknowledge this business case:
[Create account from Apple/Google Pay checkout](https://wordpress.org/support/topic/create-account-from-apply-pay-google-pay-checkout/)
[How to enable Apple Pay on Checkout Page with Stripe 4](https://wordpress.org/support/topic/how-to-enable-apple-pay-on-checkout-page-with-stripe-4/)

![Apple Pay needed with other payment methods](https://pasteboard.co/JLdLQCH.png)

Please, please.

**Comment by RunningBe** [comment]
## This is Where We Need Apple Pay

So here we see in the screenshot, two postage options (so the final cost is not yet certain), the customers details to set up their account (which we do not have before the checkout page) and three payment options. All that's being asked for is to also have a payment request button WITH the other payment options. Then the final payment can be charged and the customer's account created.

Automatic Un-Happiness Engineers seem determined not to understand or acknowledge this business case:
[Create account from Apple/Google Pay checkout](https://wordpress.org/support/topic/create-account-from-apply-pay-google-pay-checkout/)
[How to enable Apple Pay on Checkout Page with Stripe 4](https://wordpress.org/support/topic/how-to-enable-apple-pay-on-checkout-page-with-stripe-4/)

![WhyNoApplePay](https://user-images.githubusercontent.com/11532450/105662632-4b329680-5f24-11eb-9ea3-6b7b429b8f44.png)

Please, please.

**Comment by v18** [comment]
The [payment request button can be added to the checkout page](https://docs.woocommerce.com/document/stripe/#show-payment-request-button-checkout-page) using this snippet:

```
add_filter( 'wc_stripe_show_payment_request_on_checkout', '__return_true' );
```

You can add this snippet using the Code Snippets plugin:
https://wordpress.org/plugins/code-snippets/

I'm closing this issue since there's a way to make it work.

**Comment by RunningBe** [comment]
No, this does not put the Payment Request buttons “at the end of Checkout”, it places them at the start of checkout.  Quite useless and completely unacceptable for us.  It is only ‘at the end of Checkout’ that we want the transaction completed.  Then we have all the customer details, the requested postage method and any delivery notes.  We do not want the transaction processed before that.  We are not Robinson Crusoe in this!  

The reason why all the other payment options are at the end of checkout is that that is when the transaction should complete.  For us, that is where the Payment Request Buttons need to be too.

The suggestion is often, get a developer to do this.  But why, surely this is a clear case of a business requirement and the topic has been supported by others.  It was even set as a low priority enhancement, so someone there understood.

Please reopen this ticket.

**Comment by RunningBe** [comment]
Hi Valerie,

In case you miss it, this is my update:

No, this does not put the Payment Request buttons “at the end of Checkout”, it places them at the start of checkout. Quite useless and completely unacceptable for us. It is only ‘at the end of Checkout’ that we want the transaction completed. Then we have all the customer details, the requested postage method and any delivery notes. We do not want the transaction processed before that. We are not Robinson Crusoe in this!

The reason why all the other payment options are at the end of checkout is that that is when the transaction should complete. For us, that is where the Payment Request Buttons need to be too.

The suggestion is often, get a developer to do this. But why, surely this is a clear case of a business requirement and the topic has been supported by others. It was even set as a low priority enhancement, so someone there understood.

Please reopen this ticket.

Kind regards,
Barry
