### ISSUE TITLE
Add dismissable notice to tell the merchant that the extension is SCA-compliant

### ISSUE THREAD

**Issue by DanReyLop** [woocommerce/woocommerce-gateway-stripe#982]
To reassure the merchants, we should communicate with them that the extension is now SCA-compliant. Since we don't have all their e-mails, and we can't be sure that they will all read a blog post on woocommerce.com, the next best thing is a dismissable WP-Admin notice. It should be green ("success"), and maybe have a link to [this blog post](https://woocommerce.com/posts/introducing-strong-customer-authentication-sca/).

cc/ @woocommerce/hydra If y'all agree with this idea, we should add it to all the other SCA-compliant extensions too.

**Comment by allendav** [comment]
Avoid the word "compliant" - instead use "Ready for SCA" or "SCA Ready" or "Updated for SCA"

Plugins are not allowed to claim compliance per https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#9-developers-and-their-plugins-must-not-do-anything-illegal-dishonest-or-morally-offensive

> implying that a plugin can create, provide, automate, or guarantee legal compliance

**Comment by RadoslavGeorgiev** [comment]
Closing because #1014 is now merged.
