### ISSUE TITLE
Apple Pay not initially showing correct total (quantity) if used on Product Page

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce-gateway-stripe#985]
#### Affected ticket(s)

2332304-zen

#### What I expected

When the Apple Pay button is used from an individual product page, the initial total should take into acccount the product's price X the quantity selected (ex: `$15.00 x 2`).

#### What happened instead

The checkout totals if Apple Pay is used from the product page are incorrect, as they don't take quantity into account for the total initially, they only show the product price 1X: 

![https://cld.wthms.co/j9jlrW](https://cld.wthms.co/j9jlrW+)
Image link: https://cld.wthms.co/j9jlrW

Then click button: 

![https://cld.wthms.co/B0wXnr](https://cld.wthms.co/B0wXnr+)
Image link: https://cld.wthms.co/B0wXnr

As we can see, it should show $30 (`$15 x quantity of 2`), but only shows $15.00 - it also doesn't display the total correctly if there is a `Default` variation option set.

The end total that gets calculated is correct though.

#### Steps to reproduce the issue

1. Setup Apple Pay.
2. Setup a variable product.
3. Go to the individual product page on the front end and select a variation option with a quantity of 2 or more.
4. When selecting `Apple Pay`, the initial total does not reflect the quantity selected, although the end total is correct.

Not sure if this is a Stripe/Apple Pay limitation, but either way it's `Low` priority as the final total is correct.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by ryanr14** [comment]
I think the issue I've discovered is the same/similar here. What I've found is if you update the quantity on a product page using the up/down arrows this isn't triggering something to refresh and update the payment request buttons. See if this little screencast helps explain it.

https://d.pr/v/uaxulu

If you use the arrows the quantity field becomes active, but selecting the payment request button doesn't reflect the correct price in the payment form. If you type in the quantity this does trigger the payment request to refresh, it briefly shows a loading icon, then gives you the correct total in the payment form popover / popdown.

**Comment by dougaitken** [comment]
As a note - I haven't been able to reproduce this error at all but I appreciate this has been replicated by other Happiness Engineers. 

I've tested this product `https://doug.press/product/coffee-single-product/`
I've tested on Chrome, Safari, Microsoft Edge. Each time, any interaction with the quantity either the arrows or the number, will result in a recalculation. You can see this by the Payment Request button becoming inactive and a spinner gif showing.
