### ISSUE TITLE
Subscriptions: Not using latest Payment Intents API on Subscriptions

### ISSUE THREAD

**Issue by planetahuevo** [woocommerce/woocommerce-gateway-stripe#988]
#### What I expected

Stripe API to use the new payment intents API for renewals and any charges from the Subscriptions Plugin.

#### What happened instead

The charges are made using v1/charges endpoint 
This is causing a lot of payments to fail, as some banks are already using SCA measures to prevent fraud (even if this is not enforced until the end of the week).

#### Steps to reproduce the issue

Just create a new subscription with the stripe API. 
You will go into Stripe and check the logs. All payments are made using the old charges API.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by thorsten-stripe** [comment]
@planetahuevo it is unlikely that this is related to SCA as enforcement will be gradual, see https://support.stripe.com/questions/strong-customer-authentication-sca-enforcement-date

Can you please provide detailed error messages and decline codes you're seeing in live mode?

**Comment by allendav** [comment]
Closing this as it will be covered by https://github.com/woocommerce/woocommerce-gateway-stripe/issues/936 and others

**Comment by planetahuevo** [comment]
Subscriptions Support say it is not their fault but Stripe, but at the same time they say that they are not following the SCA standards. 

You say this is not SCA. 

Stripe support say that SCA it most probably the reason this is failing, as we are not using the payments-intent API. 

So, everyone is blaming the others. 

The only fact is that subscriptions is not using the proper API recommended by Stripe, so this needs to be fixed. 

Until then, Stripe will of course say that the issue is the wrong API used and they are completely right. 

Not sure, as you closed this, if I should reply this somewhere else. 
I do not understand why is this closed either, as I have not seen anywhere that this is going to be addressed soon (the deadline is in 2 hours...)

**Comment by thorsten-stripe** [comment]
@planetahuevo https://github.com/woocommerce/woocommerce-gateway-stripe/issues/988#issuecomment-530342141

**Comment by gppuddinpie** [comment]
This is still a major issue.
