### ISSUE TITLE
SCA: handle failed payment hook

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce-gateway-stripe#992]
If we are using `on-hold` for order status for SCA payment failures that require authentication (`authentication_required` error), then we should also change the incoming hook so that it does not mark order status as failed.

**Comment by RadoslavGeorgiev** [comment]
We already decided to stick to the `failed` status and the change is pending merge: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/986/files#r324323558

When the `failed` status is used, the webhook will not affect the order.
