### ISSUE TITLE
Ignore retry attempt from woocommerce subscriptions

### ISSUE THREAD

**Issue by dwainm** [woocommerce/woocommerce-gateway-stripe#995]
Subscriptions give us the order when retrying failed orders

We should just check if the order has a payments intent and ignore it.

It will send another email but we can choose to charge or not. We should not as SCA failures are special.

We should also hook into the emails to make sure the content is consistent with our initial SCA failure.

cc @v18

**Comment by v18** [comment]
@james-allan suggested that we solve this by hooking into the renewal action, sending our own email, and returning early to prevent renewals from going through.

**Comment by RadoslavGeorgiev** [comment]
Closing because #996 got merged.
