### ISSUE TITLE
Unrecognized create() parameter: betas is not a recognized parameter

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce-gateway-stripe#998]
#### What I expected

No messages in the javascript developer console during checkout

#### What happened instead

I see the following in the dev console:

> Unrecognized create() parameter: betas is not a recognized parameter. This may cause issues with your integration in the future. https://js.stripe.com/v3/fingerprinted/js/controller-xxxx.js

Doesn't look like it breaks anything right now, but we should keep this clean as a priority.

#### Steps to reproduce the issue

Add an item to the cart, checkout. Enter a test card. Observe console log

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by allendav** [comment]
cc @v18 @DanReyLop @RadoslavGeorgiev - easy fix?

**Comment by darsh4tech** [comment]
Hi Dears,
when i press button to pay my order at dev environment i see the following message in the console:

> Unrecognized payment-request-google-pay-inner.html parameter: betas is not a recognized parameter. This may cause issues with your integration in the future

and there is a link beside it: controller-207a0a1b39a190f1e22c08ab25c9f3ee.js:formatted:274

thanks in advance

**Comment by allendav** [comment]
Hi @darsh4tech - what version of the WooCommerce Stripe extension are you running?

Also - I don't recognize the "payment-request-google-pay-inner.html" filename. Are you certain it is our (WooCommerce official) Stripe extension, or might it be someone else's?
